### ISSUE TITLE
MBtiles file problem 

### ISSUE THREAD

**Issue by Artestico** [mousebird/WhirlyGlobe#1000]
Hi there , 
I install the test app and it works perfectly , but problems start when i try to test a new offline map .

Basically the i test the offline map with the geography-class_medres.mbtiles file and it works , but i try couple of MBtiles file from https://openmaptiles.com but always the screen is black . 
The point is i'm using an area map like sheffield map or asti map like this one : 
https://openmaptiles.com/downloads/tileset/osm/europe/italy/asti/

Is there any advice on how to generate MBtiles file or from where to get proper one that will work with the app .

**Comment by mousebird** [comment]
Those may be missing levels or have areas that don't contain tiles.
Make sure you're over an area that contains tiles and zoom in far enough to find them.

**Comment by Artestico** [comment]
Hi , 
Thank you for the feedback . 
I use This file mbtiles file for Tunisia : https://openmaptiles.com/downloads/tileset/osm/africa/tunisia/
And i use this coordinate to point and zoom to the right location like you suggest : 
mapControl.setPositionGeo( 0.17603291352 ,0.64298575415 , 0.01);
but i have the black screen when i point to the tunis.mbtiles and the same code work for the geography-class_medres.mbtiles 

![screenshot_20170922-152615](https://user-images.githubusercontent.com/12445754/30749233-b282132a-9faa-11e7-8008-06991b44fd82.png)

![screenshot_20170922-152615](https://user-images.githubusercontent.com/12445754/30749267-c115c986-9faa-11e7-81bb-c92d09d4cc8e.png)

![screenshot_20170922-152505](https://user-images.githubusercontent.com/12445754/30749253-ba42a5ca-9faa-11e7-8f9c-b03228a77d89.png)

**Comment by mousebird** [comment]
At this point I'd suggest stepping into the initWithMBTiles: call and the imageForTile: calls in MaplyMBTileSource.mm to see what it's doing.

**Comment by klokan** [comment]
OpenMapTiles MBTiles contains VECTOR tiles!

It means vector data in PBF format - it is not a raster image like PNG or JPEG...

Is WhirlyGlobe able to draw the MVT PBFs?

**Comment by paulgee31** [comment]
I believe WhirlyGlobe will be expecting raster and not vector data in the MBTiles.

**Comment by mousebird** [comment]
Certainly for that loading it is.

The toolkit can handle vector tiles, but you need a working style.  We support SLD, Mapnik XML to a certain extent, and a subset of Mapbox GL Style sheet format.

There are examples in the AutoTester, but it's not as easy as image tiles.
