### ISSUE TITLE
Compile Error importing MaplyComponent.h

### ISSUE THREAD

**Issue by RandyHBH** [mousebird/WhirlyGlobe#1001]
Hi Guys,
I'm using xcode 8.2.1 and trying to set up an ios app using cocoapods, but when i create the bridging-header.h and try to import the MaplyComponent.h according to the guide [Your First Map](http://mousebird.github.io/WhirlyGlobe/tutorial/ios/your_first_map.html) giveme 
`MaplyComponent.h file not found`

this is my pod file
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
target 'MyMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'WhirlyGlobe', '2.4'
  pod 'WhirlyGlobeResources'
end
```
i'm missing something, any help please.
Regards

**Comment by mousebird** [comment]
The podspec in their main repo has fallen behind.
You can use the [podspec](https://github.com/mousebird/WhirlyGlobe/blob/develop/WhirlyGlobe.podspec) in the develop branch and that'll work.

**Comment by RandyHBH** [comment]
what should i do whit the file? Should i copy in my workspace and execute some command??

**Comment by mousebird** [comment]
You can point a pod file at a Podspec URL.

**Comment by RandyHBH** [comment]
hi i try this in my pod file

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

```
target 'CubaMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CubaMap
	pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe.git', :branch => 'develop'
	pod 'WhirlyGlobeResources'

end
```
Still give me the same error  ` error: 'MaplyComponent.h' file not found`

**Comment by RandyHBH** [comment]
Any help about this???
