### ISSUE TITLE
[ios] CocoaPods Analyzing dependencies

### ISSUE THREAD

**Issue by yangjing901** [mousebird/WhirlyGlobe#1003]
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `AFNetworking (~> 3.1.0)` required by `Podfile`
- `AFNetworking (~> 2.4.0)` required by `WhirlyGlobe/MaplyComponent (2.4)`

**Comment by mousebird** [comment]
There's a podspec in the develop branch that will work better.
Or just use the binaries or a submodule.

I'm really ambivalent about Cocoapods right now.  It's been more work than it's worth.
