### ISSUE TITLE
How to get the correct middle point coordinates by "MaplyVectorObject"?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#1004]
Hi,
     When I use "MaplyVectorObject" to get middle coordinates,  always can not get the correct midpoint coordinates: 

CODE:
![aa](https://user-images.githubusercontent.com/13251217/31005908-49777abc-a4c0-11e7-879d-495d3d8d4f61.png)

RESULT:
1) init result
![1](https://user-images.githubusercontent.com/13251217/31005984-9a309d4e-a4c0-11e7-9e4b-acc01b7944d0.PNG)  

2) after zoom (The more to zoom, the greater the distance)
![2](https://user-images.githubusercontent.com/13251217/31006022-b9b87466-a4c0-11e7-9447-ef8a0b45762e.PNG)

       How to get the correct middle point coordinates by "MaplyVectorObject"?

**Comment by mousebird** [comment]
The middle is probably calculated in lat/lon and then the line is overlaid.
That calculation isn't suitable for the globe.  It's meant for a flat map or small areas, primarily for calculating label rotation.

So don't use that to place objects on the globe.  You'll need to calculate something that takes real coordinates into account.
