### ISSUE TITLE
[Android] Performance problem with markers

### ISSUE THREAD

**Issue by Tourmen** [mousebird/WhirlyGlobe#1005]
Hello WG team.
Ive been playing with Android and iOS examples, trying to add thousand of markers and faced the situation when a method "setClusterGroup" has huge influence on performance on Android. The globe with markers works very slowly using this method in main logic.
Just in case iOS SDK works fine.

**Comment by mousebird** [comment]
I've confirmed this.  Just increase the number of markers runs on Android to 50 and it turns up.

**Comment by mousebird** [comment]
This is a lot better now.  There were some performance problems in the texture management and in the screen space generation.
Give it a try and let me know if it's still slow.  There are probably a few other places I could look.

**Comment by mousebird** [comment]
develop branch

**Comment by Tourmen** [comment]
Ive tried release and debug versions on the latest develop branch with ClusteredMarkersTestCase. 
Performance is still poor. It is barely possible to rotate a globe. Even if I zoom in and try only a part of the globe.

**Comment by Tourmen** [comment]
@mousebird Should I open another ticket for further improvements?

**Comment by mousebird** [comment]
No, I'll take another look at it.
Is it bringing up the clusters faster now?  That's what I was optimizing.

**Comment by Tourmen** [comment]
@mousebird 
Seems it brings up clusters faster, but then (when clusters are appearing on a map) anyway the globe works slowly.

**Comment by Tourmen** [comment]
@saildronesteve awesome! But, can it be fixed soon or it is a part of big upcoming development?

**Comment by Tourmen** [comment]
Tried with next set up:
1. 5 quad paging layers were added
2. different cluster group is assigned to every layer
3. hundreds and thousand markers added on every layer

Current performance in the latest library is good enough to be used.
Thank you.
