### ISSUE TITLE
15000 screenMarkers on globe, memory leak 200-300Mb [IOS]

### ISSUE THREAD

**Issue by dmertsalov** [mousebird/WhirlyGlobe#1008]
I add on the globe 15000 markers. it consists of picture 1KB (25*25 pixels) and userObject: id by String. If is used memory is increased by 200-300 Mb. The objects themselves also added quite a long time - about 1 minute. How to optimize memory usage and increase the speed of adding markers?

**Comment by mousebird** [comment]
It doesn't sound like a memory leak, just usage.  I can suggest a few improvements:
- Add your picture once as a MaplyTexture and then reuse it for each marker
- Add the markers, I assume these are screen markers, together as one big group and not individually

**Comment by dmertsalov** [comment]
Thank you! texture instead of the image helped to accelerate the addition of 100 times! well, the memory usage dropped by 70%. Maybe add it to the tutorial, because now it is written very superficially.
