### ISSUE TITLE
[IOS] Wide vectors not closed

### ISSUE THREAD

**Issue by dmertsalov** [mousebird/WhirlyGlobe#1010]
Hi! I create vectors from a single geoJson file. 
example for wideVectors:
```
guard let vectorObjects =  MaplyVectorObject.init(fromGeoJSON: data) else {
      return nil
    }
globeViewController?.addWideVectors([vectorObjects], desc: desc, mode: .current)
```
with conventional vectors, everything is fine but with widen not-so - polygon is not closed. Do I need to specify some extra parameter in the desc?

![img_0125](https://user-images.githubusercontent.com/17335832/31756805-a6f86522-b4ae-11e7-91f3-f55685f2f49d.jpg)
![img_0126](https://user-images.githubusercontent.com/17335832/31756806-a7153e90-b4ae-11e7-869a-6cf5ce4b7b54.jpg)

**Comment by mousebird** [comment]
Are those areal features in the GeoJSON or linears?

**Comment by dmertsalov** [comment]
... "geometry": {"type": "Polygon", "coordinates": [[[92.966672, 56.020001], [93.011117, 56.020001], [93.011117, 56.000001], [92.966672, 56.000001], [92.966672, 56.020001]]]}, ...
The first and last point the same. How to use widen vectors for this?

**Comment by dmertsalov** [comment]
@mousebird 
Maybe there are some ideas how to solve the problem?

**Comment by mousebird** [comment]
It should be picking up on that.  I haven't had a chance to test the example.

**Comment by mousebird** [comment]
The square.geojson example in the AutoTester appears to be working fine.  I'm seeing a closed wide vector in there.

Try square.geojson with your code and see what you get.

**Comment by dmertsalov** [comment]
I found the cause - in the presence of these parameters in desc is no circuit grounds. Maybe something in the implementation of the subdiv?

`Params in desc:
kMaplySubdivType: kMaplySubdivGreatCircle,
kMaplySubdivEpsilon: ...,`

**Comment by saildronesteve** [comment]
Ah, I see.  The issue then is that the subdivision isn't keeping the closed-ness of the feature intact.

**Comment by mousebird** [comment]
Fixed.
