### ISSUE TITLE
Cannot invoke initializer for 'MaplyQuadImageTilesLayer'

### ISSUE THREAD

**Issue by Carkin** [mousebird/WhirlyGlobe#1014]
Hi, 

I'm trying to follow the tutorial on adding mbtitles to the WhirlyGlobe swift project. I've imported the mbtitles into the project and named it in the viewcontroller. Now I get this issue: 

Cannot invoke initializer for type 'MaplyQuadImageTilesLayer' with an argument list of type '(tileSource: MaplyMBTileSource)'

Here is the code I'm trying to add: 

// set up the data source
        if let tileSource = MaplyMBTileSource(mbTiles: "geography-class_medres"),
            let layer = MaplyQuadImageTilesLayer(tileSource: tileSource) {
            layer.handleEdges = (globeViewC != nil)
            layer.coverPoles = (globeViewC != nil)
            layer.requireElev = false
            layer.waitLoad = false
            layer.drawPriority = 0
            layer.singleLevelLoading = false
            theViewC!.add(layer)
        }

The issue appears on the first let layer line. 

I've imported the WhirlyGlobeComponent.h into my bridging header. I've been looking for a few hours and can't figure this out.

**Comment by saildronesteve** [comment]
I put those lets on separate lines and they compiled fine.  Swift changes periodically, but this is with the latest.

**Comment by Carkin** [comment]
That's odd. Can't get it to work on mine. Also running the lastest

**Comment by ChrisLowe-Takor** [comment]
Try using the constructor that defines  a coordinate system:

`let coordSystem = MaplySphericalMercator(webStandard: ())
let layer = MaplyQuadImageTilesLayer(coordSystem: coordSystem, tileSource: tileSource) 
`

Here is a full working example I use:

`func tileSource() -> MaplyQuadImageTilesLayer? {
        if let tileSource = MaplyMBTileSource(mbTiles: "country-lowres") {

            let coordSystem = MaplySphericalMercator(webStandard: ())

            if let layer = MaplyQuadImageTilesLayer(coordSystem: coordSystem, tileSource: tileSource) {
                layer.handleEdges = false
                layer.coverPoles = false
                layer.singleLevelLoading = false
                layer.requireElev = false
                layer.drawPriority = 0

                return layer
            }
        }
        return nil
    }
`

**Comment by ChrisLowe-Takor** [comment]
Sorry bad advice.  It looks like that mbtile file is corrupt or badly formatted.  I tried swapping that exact `geography-class_medres.mbtile` and it wouldn't load.  I also tried loading it locally with [MBView](https://github.com/mapbox/mbview) and it crashed with following error:  `format is not defined`.

**Comment by Carkin** [comment]
A corrupt mbtfile would make sense! I'll try downloading another. Know where I can find an uncorrupted version?

**Comment by ChrisLowe-Takor** [comment]
Here is one from a much older version of WhirlyGlobe I've been using for some time.

https://www.dropbox.com/s/m93q1ixc8v2sguz/country-lowres.mbtiles?dl=0

**Comment by StefanoBiasu** [comment]
Not sure it helps, I had problems running tutorial too. To solve, I wrote:

`let layer = MaplyQuadImageTilesLayer(coordSystem: tileSource.coordSys, tileSource: tileSource) `

**Comment by mousebird** [comment]
That would probably work fine.  You're giving it the coordinate system to use, which is likely Spherical Mercator and that's the default anyway.

As for geography class being corrupted, that's odd.  I use the version in resources all the time for testing.  Maybe it's the download link.
