### ISSUE TITLE
Simple example: tile loading partially

### ISSUE THREAD

**Issue by StefanoBiasu** [mousebird/WhirlyGlobe#1015]
I'm new to WhirlyGlobe. I followed the tutorial and I wrote these lines (mostly only reported from examples):
- iOS 11
- both simulator and Device
- no errors or warnings shown in consolle
- WhirlyGlobe downloaded from cocoapods (2.4 last current release)

`import UIKit
import WhirlyGlobe

class ViewController: UIViewController {

    private var theViewC: MaplyBaseViewController?
    private var globeViewC: WhirlyGlobeViewController?
    private var mapViewC: MaplyViewController?
    
    private let doGlobe = true
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        if doGlobe {
            globeViewC = WhirlyGlobeViewController()
            theViewC = globeViewC
        }
        else {
            mapViewC = MaplyViewController()
            theViewC = mapViewC
        }
        
        self.view.addSubview(theViewC!.view)
        theViewC!.view.frame = self.view.bounds
        addChildViewController(theViewC!)

        // we want a black background for a globe, a white background for a map.
        theViewC!.clearColor = (globeViewC != nil) ? UIColor.black : UIColor.white
        
        // and thirty fps if we can get it ­ change this to 3 if you find your app is struggling
        theViewC!.frameInterval = 30
        
        // set up the data source
        if let tileSource = MaplyMBTileSource(mbTiles: "geography-class_medres"),
            let layer = MaplyQuadImageTilesLayer(coordSystem:tileSource.coordSys, tileSource: tileSource) {
        
        
            layer.handleEdges = (globeViewC != nil)
            layer.coverPoles = (globeViewC != nil)
            layer.requireElev = false
            layer.waitLoad = false
            layer.drawPriority = 0
            layer.singleLevelLoading = false
            theViewC!.add(layer)
        }
    
        // start up over Madrid, center of the old-world
        if let globeViewC = globeViewC {
            globeViewC.height = 0.8
            globeViewC.animate(toPosition: MaplyCoordinateMakeWithDegrees(-3.6704803, 40.5023056), time: 1.0)
        }
        else if let mapViewC = mapViewC {
            mapViewC.height = 1.0
            mapViewC.animate(toPosition: MaplyCoordinateMakeWithDegrees(-3.6704803, 40.5023056), time: 1.0)
        }
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }`

The result is not what expected:

<img width="994" alt="screen shot 2017-11-19 at 19 24 55" src="https://user-images.githubusercontent.com/7943119/32993899-5ee550aa-cd5f-11e7-9117-85a683f0c6e5.png">

What can I do to load correctly all tiles? Zooming and moving triggers tile loading, but there is always an half screen badly loaded.
Thanks

**Comment by mousebird** [comment]
Have you added any layers other than Geography Class on there?

**Comment by StefanoBiasu** [comment]
No, I followed the tutorial, and download link, and it seems to work.
I think the reason is that I downloaded via cocoapods. (2.4).
Last release is 2.5. I’ll try that version too.

When cocoapods will accept 2.5 version?
Thanks

**Comment by mousebird** [comment]
If you point Cocoapods at the pod in the master branch you'll get 2.5 right now.
At some point I need to change the documentation to do that rather than point to the main Cocoapods repo.

**Comment by StefanoBiasu** [comment]
Currently I get this:

<img width="1381" alt="screen shot 2017-11-20 at 17 10 56" src="https://user-images.githubusercontent.com/7943119/33028305-e059a18e-ce15-11e7-9ea7-b691d1d3a1a7.png">

Maybe it needs some time to load the version

**Comment by mousebird** [comment]
2.4 is pretty old, but it's the last version that I was able to update to the Cocoapods repo.
Instead, we use the podspec in the repo itself.  Honestly, I wish I could nuke the one out of the Cocoapods repo and just do this.  So much simpler on my end.

Pointing to the [podspec](https://github.com/mousebird/WhirlyGlobe/blob/master/WhirlyGlobe.podspec) in the master will get you 2.5.  If you point to the [develop branch](https://github.com/mousebird/WhirlyGlobe/blob/develop/WhirlyGlobe.podspec) you'll get 2.6.

**Comment by StefanoBiasu** [comment]
`develop` branch works perfectly.

Thank you!
