### ISSUE TITLE
[Android]How to Use MultiplexTileSource?

### ISSUE THREAD

**Issue by Buzzfease** [mousebird/WhirlyGlobe#1016]
In the Globe case,
I want to use two different RemoteTileSourse 
one shows at earth night, other one shows at earth day,
I have successfully obtained them and saved into cacheDir
but only one layer appear
do i need to change the shader program?

**Comment by mousebird** [comment]
Yes, you need a different shader that takes those into account.
I don't have the device in front of me, but I believe there may be a test case for this on Android.  I'll check later.

**Comment by Buzzfease** [comment]
thanks! here is my code
` MultiplexTileSource fullTileSource = new MultiplexTileSource(globeControl, sources, coordSystem);
                fullTileSource.debugOutput = true;
                fullTileSource.setCacheDir(cacheDir);
                tileSource = fullTileSource;

                QuadImageTileLayer baseLayer = new QuadImageTileLayer(globeControl, coordSystem, tileSource);
                baseLayer.setImageDepth(2);
                baseLayer.setCoverPoles(true);
                baseLayer.setHandleEdges(true);
                baseLayer.setSingleLevelLoading(false);
                baseLayer.setShaderName("Default Triangle;nightday=yes;multitex=yes;lighting=yes");`
once add the default shader,it will change my lights setting but still cant show the night layer

**Comment by mousebird** [comment]
Look at the AtmosphereTestCase in the AutoTester app.  That sets up an atmospheric shader that uses two textures.
If you want to do something simpler, without the atmosphere, you could borrow the shader code and modify it.

**Comment by Buzzfease** [comment]
sorry to bother you again 
The RemoteTileSourse of the **AtmosphereTestCase** have gone missing , so i changed them with available sources,using the atmospheric shader ,but still just show the day images,
(can see the day/night images at local,with the same name such as 0_0_1_dark.png 0_0_1_light.png)

**Comment by mousebird** [comment]
That sounds like the shader isn't doing the right thing.  Make sure the shader's set up.
I'd recommend changing the Android AutoTester to use your sources and see what happens.

**Comment by Buzzfease** [comment]
I run the Android AutoTester with my own sources , the shader set by the Atmosphere Working fine when using single RemoteTileSource,
it will cover the earth-night area with black (becasue no sources ) and the edge between day-night was handled with transition effect,
but when using  MultiplexTileSource, nothing happens then, please check.
