### ISSUE TITLE
How can I "MaplyVectorObject"

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#1018]
Hi,
     Now, I load "MaplyVectorObject" like this:

![1](https://user-images.githubusercontent.com/13251217/33876183-b9fba3a6-df5f-11e7-953d-4c854a722d51.png)

     result in ipad:
[pic1]
![img_0239](https://user-images.githubusercontent.com/13251217/33876137-901eb0dc-df5f-11e7-914e-6a82986ffeb6.PNG)

     I want to load description text like follows(18°W, 19°W....), and The description text is always in the middle of the screen, no matter how it moves:
[pic2]
![2](https://user-images.githubusercontent.com/13251217/33876285-0beb167e-df60-11e7-8e3a-02f9d8963a58.png)

     in a words,  Can you tell me how to judge the current "MaplyVectorObject" is within the scope of the screen, whether the intersection with the screen and get the intersection position?  So as to achieve the effect of [pic2].

**Comment by mousebird** [comment]
I guess you could look at the viewable area coming back from the view controller.  That's in the delegate.  You'll get a new bounding box each time the user moves.

Then you'll need to run the rest of that logic yourself.

**Comment by marychenyuan** [comment]
thank you!   
  Yes, I can get a new bounding box each time the user moves,  but... I can't get that objects(MaplyVectorObject) in  the viewable area, How can I get that objects?

**Comment by saildronesteve** [comment]
There's no facility for doing a bounding box search into what's currently loaded.
You'll need to keep track of what you load in and do this yourself.
