### ISSUE TITLE
Nightly binaries not available.

### ISSUE THREAD

**Issue by hneil** [mousebird/WhirlyGlobe#1022]
The "Available Builds and Status" section of the binary builds page isn't loading. The "Loading" symbol runs for a long time, followed by the message "This table is generated by an external Javascript module that is not signed. If you see an error message you may need to turned of browser plugins such as HTTPS Everywhere in order to see it."

**Comment by saildronesteve** [comment]
We're not changing the code base as much, so the 2.5 build on that page should be fine.
