### ISSUE TITLE
Current  build version number

### ISSUE THREAD

**Issue by dmertsalov** [mousebird/WhirlyGlobe#1024]
In my Podfile has a link to version 2.5:
pod 'WhirlyGlobe', :http => 'https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/WhirlyGlobe-Maply_Distribution_2_5.zip'

but after installation - version 2.4.1:
Installing WhirlyGlobe 2.4.1-nightly295 (was 2.4.1-nightly295)

this is a normal situation?

**Comment by dmertsalov** [comment]
I solved it with 
```pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe.git', :branch => 'develop'```

but when I build my project an error appears in vector_tile.pb.h:
'google/protobuf/stubs/common.h' file not found

**Comment by mousebird** [comment]
By default the vector tiles support shouldn't be on.  Are you turning it on in your build settings?

**Comment by dmertsalov** [comment]
Yes, i have key NOTPODSPECWG=1 in  build settings.
I have build error in line 9 #include <google/protobuf/stubs/common.h>

**Comment by mousebird** [comment]
Just take that out for now.  Then it won't pull in the vector tiles code.

I have a newer version in the works that just sticks those files in the repo.  But that's not checked in.

**Comment by dmertsalov** [comment]
I just need the vectors, so I decided to use the version 2.5.  How about protobuf? can I somewhere to take it and install it

**Comment by mousebird** [comment]
Probably best to use the submodule then.  That's the safest way to get all the dependences for vector tiles.

**Comment by dmertsalov** [comment]
Sounds good, but like instructions for setting up using submodules have not been updated?

**Comment by mousebird** [comment]
The [instructions for submodules](https://mousebird.github.io/WhirlyGlobe/tutorial/ios/building_from_source.html) are a bit old, it's true.

Consult the AutoTester app for an example of how it's set up.
I'd recommend using the develop branch, which will be 2.6 when I get a chance to release it.
