### ISSUE TITLE
When will GeoJson and GreatCircle be availabl for Android?

### ISSUE THREAD

**Issue by r3dstorm4** [mousebird/WhirlyGlobe#1027]
First of all, many thanks for this great lib!
This is just awesome. Hope the android version will get all the possabilities the iOS version has.
Is there a way in android to use GeoJson and add GreatCircle, scince they are not documented?

**Comment by mousebird** [comment]
There's a subdivideToGlobeGreatCircle routine in the VectorObject.
I also see a fromGeoJSON method.
