### ISSUE TITLE
[IOS] build issue

### ISSUE THREAD

**Issue by Madankapoor** [mousebird/WhirlyGlobe#1032]
I included the whirlyGlobe as mentioned in 

http://mousebird.github.io/WhirlyGlobe/tutorial/ios/building_from_cocoapod.html

I got the following issue 

The build fails with lexical or preprocessor issue 
'grpc/support/port_platform.h' file not found

Xcode version : 9.2
macOS High Sierra Version 10.13.3

could any one please help me out ?

I am building a Swift 4 project

**Comment by mousebird** [comment]
First thing to do is use the Podspec in the develop tree:
https://github.com/mousebird/WhirlyGlobe/blob/develop/WhirlyGlobe.podspec

That's more up to date.

**Comment by Madankapoor** [comment]
Thank you @mousebird  

I tried it out with the given podspec but I still having issues.

The build fails with lexical or preprocessor issue
'google/protobuf/stubs/common.h' file not found

**Comment by mousebird** [comment]
Are you defining NOT_PODSPEC?  That should be the only way the vector tiles headers are pulled in.

**Comment by Madankapoor** [comment]
I just  added the pod  and compiled it 
 pod 'WhirlyGlobe',  :git => 'https://github.com/mousebird/WhirlyGlobe.git', :branch => 'develop'

I saved the spec file locally and also tried.
pod 'WhirlyGlobe',  :podspec => "podspec/WhirlyGlobe.podspec"

Could you guide me a little please . thank you

**Comment by mousebird** [comment]
It's probably easier to use the submodule approach at this point.  I'll be pulling in the vector tile code in the next version to work around this, but it's not ready yet.

**Comment by Madankapoor** [comment]
I used a pre-build in the pod file  as for now:
pod 'WhirlyGlobe',  :http => 'WhirlyGlobe-Maply_Distribution_2_5.zip'.
