### ISSUE TITLE
add fix compilation issue with Xcode 9.3 from KissXML

### ISSUE THREAD

**Issue by dmertsalov** [mousebird/WhirlyGlobe#1034]
please update your KissXML fork for compilation with Xcode 9.3.

[https://github.com/robbiehanson/KissXML/commit/24842063a24bf29bf14136a2a727dd5ad9eec69b](url)

**Comment by mousebird** [comment]
Which branch are you on in WhirlyGlobe?

**Comment by dmertsalov** [comment]
develop

**Comment by LivioGama** [comment]
+1 thanks for the fix @dmertsalov
