### ISSUE TITLE
WhirlyGlobe  Compilation issue with Xcode 9.3

### ISSUE THREAD

**Issue by marwenmoalla** [mousebird/WhirlyGlobe#1036]
HI,
After updating my XCode to the latest version 9.3 i found an issue when compiling my project.
Issue: .../WhirlyGlobeMaplyComponent.framework: unsealed contents present in the root directory of an embedded framework

I use : WhirlyGlobe 2.6.0-nightly726
[pod 'WhirlyGlobe', :http => 'https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/iOS_daily_builds/WhirlyGlobe-Maply_Nightly_latest.zip']

Pod Version 1.5.0
XCode version 9.3
MacOS: High Sierra 10.13.4

PS: There is no problem with WhirlyGlobe 2.4.0 

Have you any idea about this !!
Thanks in advance.

**Comment by mousebird** [comment]
I think I ran into this.  Definitely fixed it in the develop branch, but I do not specifically remember what caused it.
If you switch to using the develop branch directly it should fix it.

**Comment by marwenmoalla** [comment]
I switched to version nightly 725 released at 2018-03-21 and it solve my problem. 

Thanks.
