### ISSUE TITLE
MaplySun getDirection() returning incorrect position vector

### ISSUE THREAD

**Issue by alexstgeorge** [mousebird/WhirlyGlobe#1037]
Hi,
I've been using your MaplySun object and it seems that the y and z elements in the vector returned by  getDirection() are flipped. I was using the vector to set the position of another MaplyLight (using the pos property) and it was positioned incorrectly until I flipped those values.

I'm working with the 2.5 compiled binary on iOS.

Thanks.

**Comment by mousebird** [comment]
Yes, I believe you're right.  Take a look at the makeLight method.

**Comment by alexstgeorge** [comment]
Thanks for the quick reply! I am aware of the makeLight method, however for my application it made more sense to just update the position of the light rather than reconfiguring the light, since I am using diffuse and ambient colours that are different from the default. 

Thanks again.

**Comment by alexstgeorge** [comment]
No worries! The workaround is very simple so it's not a problem for me. I just thought I should let you know.
