### ISSUE TITLE
Bounding Box used in validTile function of the MaplyTileSource protocol is the incorrect size.

### ISSUE THREAD

**Issue by alexstgeorge** [mousebird/WhirlyGlobe#1038]
Hi all,
When creating my own tile source using the MaplyTileSource protocol I was using the validTile(_ tileID: bbox:) function to check if the tiles should be loaded. I used the bbox parameter to check against another bounding box I had set for the layer and it seems that the bbox is not the same size as the tile. It seems like bbox doesn't take into account that the coordinate system is spherical mercator and so the tiles are stretched awkwardly at the edges of the map.

![image](https://user-images.githubusercontent.com/19505007/38645935-e7b00b68-3db3-11e8-88fe-946b74300832.png)

I've created a work around for now using this function to calculate the coordinates of the tile.
`
/**
     Get the lower left corner of a tile given it's x, y, z position.
     
     - parameters:
        - x: x position of the tile
        - y: y position of the tile
        - z: The zoom level of the tile
     
     - returns: The coordinates of the lower left corner of the tile.
     
     */
    
    func XYZToCoordinate(x: Int32, y: Int32, z: Int32) -> MaplyCoordinate {
        let n = Float(1<<(z))
        let lon = (2*Float(x)/n - 1)*180
        //we have to flip the y as the coordinate system used by whirly globe is the inverse in the y direction of the coordinate system used by these equations.
        let flipedY = Int32(n)-y
        let lat = atan(sinh(Float.pi*(1-2*Float(flipedY)/n)))*180/Float.pi
        
        return MaplyCoordinateMakeWithDegrees(lon, lat)
    }
`
With the results being:

![image](https://user-images.githubusercontent.com/19505007/38645965-11c5c474-3db4-11e8-9b5a-d375ae5ec028.png)

I am using the 2.5 compiled binary distribution.

Thank you.

**Comment by mousebird** [comment]
At one point the bounding box query in a layer was wrong.  I fixed that in more recent versions so you should be able to get a local bounding box and a lat/long bounding box, depending on the call.

**Comment by alexstgeorge** [comment]
Ok sounds good. I just wanted to make sure you were aware of the issue.
