### ISSUE TITLE
Ability to reload single frame

### ISSUE THREAD

**Issue by alexstgeorge** [mousebird/WhirlyGlobe#1040]
Hi,
I was wondering if it were possible to make a function for the MaplyQuadImageTilesLayer to reload a single frame instead of the entire layer. I have frames in my layer that update more frequently than others and I think it would be beneficial to be able to only reload the frames that needs to be updated.

I'm using the 2.5 binary distribution.

Thank you.

**Comment by alexstgeorge** [comment]
I've been digging around in the code and I've come up with a solution that works for me. The implementation can be found on [this branch](https://github.com/alexstgeorge/WhirlyGlobe/tree/feature/single-frame-reload) at [this commit](https://github.com/alexstgeorge/WhirlyGlobe/commit/d3091731f782ce40ce233c63077082c36354e0c4) on my forked copy of the SDK. 

In addition to adding the single frame reload functionality to the QuadImageLayer, I also created a new method of determining if a frame is fully loaded and fixed a NullPointerException on the QuadImageLayer reload() function on Android (the layerThread has the possibility of being null if a reload happens to be called on an orientation change).

Let me know what you think about the changes.

**Comment by mousebird** [comment]
Whoa.  You really got into that code.  Cool!

**Comment by mousebird** [comment]
Sure, go ahead and do a pull request.

This subsystem is complex, though, so it'll take me a while to inspect and test it.

I've written a new version for 2.6, but it will be a while before it gets to Android.

**Comment by alexstgeorge** [comment]
Ok sounds good! I've made the [pull request](https://github.com/mousebird/WhirlyGlobe/pull/1070). Please let me know if you need me to explain/fix anything.

Thanks again!
