### ISSUE TITLE
Xcode cocoapod failure

### ISSUE THREAD

**Issue by hneil** [mousebird/WhirlyGlobe#1041]
When building with the latest nightly build using cocoapods, Xcode fails with the error WhirlyGlobeMaplyComponent.framework: unsealed contents present in the root directory of an embedded framework.

**Comment by mousebird** [comment]
Ran into this one myself, but I believe it's fixed in the develop branch.

**Comment by hneil** [comment]
Doesn't the nightly build use the develop branch? If not, how do I point to that?

**Comment by mousebird** [comment]
The nightly builds are out of date.  The machine running them is down.
For the freshest source, you'll need the develop branch on the github repo.  You can either reference it by submodule or through its podspec.

**Comment by hneil** [comment]
OK thanks. Do you have an ETA for version 2.6?

**Comment by mousebird** [comment]
Soonish, I think.  It's pretty stable.
