### ISSUE TITLE
WhirlyGlobe about overlap problem

### ISSUE THREAD

**Issue by XuLiCC** [mousebird/WhirlyGlobe#1043]
when text and line are overlap，I don't want to hidden text or line， I hope that text  can cover a line section , how can I achieve ？

**Comment by NasH5169** [comment]
Hello? :)

Take a look at setLayoutImportance(Float.MAX_VALUE)

Bye bye

**Comment by mousebird** [comment]
Look at the offset of the MaplyScreenLabel.
