### ISSUE TITLE
Create Compiled iOS Framework off of develop branch

### ISSUE THREAD

**Issue by alexstgeorge** [mousebird/WhirlyGlobe#1047]
I've been trying to create a compiled binary from the `develop` branch and I can't seem to figure out how to do so. I've successfully done so on the `master` branch by running `buildframework.sh`, but for some reason this no longer works on the `develop` branch. If I add the framework into my project and run the app I get this runtime error that crashes the app on launch:
```
dyld: Library not loaded: @rpath/WhirlyGlobeMaplyComponent.framework/WhirlyGlobeMaplyComponent
  Referenced from: /Users/alexstgeorge/Library/Developer/CoreSimulator/Devices/234AA0AC-5B0D-4B32-984A-586795ADB5B1/data/Containers/Bundle/Application/D84126A3-7F71-4A7B-85DA-8A77C4B7D791/WhirlyGlobeTest.app/WhirlyGlobeTest
  Reason: image not found
```
This happens both on the simulator and a real device.

I also noticed that you change from the framework from static to dynamic, so I tried adding the framework as an embedded binary and I get this code sign error:
```
CodeSign /Users/alexstgeorge/Library/Developer/Xcode/DerivedData/WhirlyGlobeTest-cvgjwzmbhbwpbebblisszspopxrz/Build/Products/Debug-iphonesimulator/WhirlyGlobeTest.app/Frameworks/WhirlyGlobeMaplyComponent.framework
    cd /Users/alexstgeorge/Documents/XcodeProjects/WhirlyGlobeTest
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/alexstgeorge/Library/Developer/Xcode/DerivedData/WhirlyGlobeTest-cvgjwzmbhbwpbebblisszspopxrz/Build/Products/Debug-iphonesimulator/WhirlyGlobeTest.app/Frameworks/WhirlyGlobeMaplyComponent.framework

/Users/alexstgeorge/Library/Developer/Xcode/DerivedData/WhirlyGlobeTest-cvgjwzmbhbwpbebblisszspopxrz/Build/Products/Debug-iphonesimulator/WhirlyGlobeTest.app/Frameworks/WhirlyGlobeMaplyComponent.framework: unsealed contents present in the root directory of an embedded framework
Command /usr/bin/codesign failed with exit code 1
```
Am I doing something wrong? Am I supposed to sign the framework before I build the framework?

Please note that I have successfully managed to run the framework as a submodule in my project but I would prefer using a compiled binary instead.

Thank you!

**Comment by nhevaweb** [comment]
@alexstgeorge I have exactly the same issue on the develop branch. Did you find out another solution ?

**Comment by alexstgeorge** [comment]
Unfortunately I wasn't able to figure it out. I tried signing the Framework and building but I still got the same errors. Best I can suggest is to work with the submodule approach as @mousebird has stated as it is the only way this framework seems to work at the moment.

If you are having issues using submodules, please refer to [this tutorial](http://mousebird.github.io/WhirlyGlobe/tutorial/ios/building_from_source.html) and [this issue](https://github.com/mousebird/WhirlyGlobe/issues/1066) that I posted yesterday about fixing the Eigen submodule. Be sure to specify the branch you want to build off of using the `-b branch` flag in the submodule command
```
% git submodule add -b develop https://github.com/mousebird/WhirlyGlobe.git libs/WhirlyGlobeMaply
```
Please let me know if you have any other questions or issues and I'll be happy to help.

**Comment by nhevaweb** [comment]
@alexstgeorge All right thanks for tip 👍

**Comment by nhevaweb** [comment]
@alexstgeorge @mousebird I'm having a weird issue with the lastest develop branch. 
I was using cluster with the release 2.5 of the framework and everything worked fined.

Since I pulled out the last develop branch, I can pinch to zoom in/out and it works just like before... 
Whenever I tap on the map (on anything) however, my MaplyScreenMarker and MaplyScreenLabel holds still and doesn't move (no grouping/degrouping within the cluster, nor labels placement changes).

Any ideas ? Thanks

**Comment by mousebird** [comment]
Could be a real problem.  Please open a new issue so we can track it.
