### ISSUE TITLE
At large zooms precision is not sufficient

### ISSUE THREAD

**Issue by jerzykiler** [mousebird/WhirlyGlobe#1052]
I am trying to create an indoor map and at large zooms - even those zooms that still have the fill color (#1051) - the polygons look skewed a little, like there is not enough precision. 

I have examples of the same map from another library (not WhirlyGlobe) for android and WhirlyGlobe:

Android:
![android_example](https://user-images.githubusercontent.com/2103762/40022635-d9d507b2-57c8-11e8-993e-28db4eb81d1a.png)

iOS WhirlyGlobe:
![ios example](https://user-images.githubusercontent.com/2103762/40022513-8a28acbe-57c8-11e8-91dc-a3096f423087.png)

The iOS WhirlyGlobe version looks kind of artistic but I'm not sure if my client would like it :)

**Comment by mousebird** [comment]
Try setting kMaplyVecCentered to YES or true when you're calling addVectors

**Comment by jerzykiler** [comment]
Setting kMaplyVecCentered didn't work, no difference.

**Comment by mousebird** [comment]
If you set kMaplyVecCenterX and kMaplyVecCenterY you can offset the coordinates from those values.  This lets you use more precision.
