### ISSUE TITLE
Fill lofted polygons

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#1053]
Hello!

Is there a way to fill the inside of a lofted polygon?

Cheers,

Sebastien Boulnois.

**Comment by mousebird** [comment]
Do you mean have it show that color when the viewer is inside the polygon?

**Comment by Sebboulnois** [comment]
Yes.

**Comment by mousebird** [comment]
Ah, then no.

**Comment by Sebboulnois** [comment]
Alright. Thank you for the information.
