### ISSUE TITLE
A question about addVectors, hope everybody can help me, thank you!

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1055]
I get a standard Geojson data from the network.
Generate the MaplyVectorObject object using VectorObjectFromGeoJSON.
I used addvator to draw the line, then CPU>100%,5 seconds, and added 30 MB of ram.
Here's the problem:
My Geojson contains "properties" and I need to use its Value "type" to make a judgment, Then I use vecObj. Splitvector to do "for in" and generate the MaplyComponentObject object., and then the CPU is 10 seconds and Memory increases by 500MB.
Please tell me what to do.
<img width="1323" alt="2018-05-21 5 41 23" src="https://user-images.githubusercontent.com/15685672/40301474-d598046e-5d1e-11e8-9bee-dc72b10927d5.png">
<img width="1334" alt="2018-05-21 5 41 53" src="https://user-images.githubusercontent.com/15685672/40301479-d8635392-5d1e-11e8-81f0-56a8a03e4ce9.png">

**Comment by mousebird** [comment]
I believe I answered this one by email.
