### ISSUE TITLE
Error while trying to install it via CocoaPods 

### ISSUE THREAD

**Issue by malavagile** [mousebird/WhirlyGlobe#1058]
Hi,

I'm trying to add this library into my project, but everytime I run pod install, I get the following error:

[!] Error installing eigen
[!] Unable to locate the executable hg

Am I missing something?

Thanks,
Malav .
![screen shot 2018-05-22 at 12 26 37 pm](https://user-images.githubusercontent.com/10988932/40346770-788e399e-5dbb-11e8-9158-7caaae39e65e.png)

**Comment by mousebird** [comment]
That looks like a Cocoapods installation problem.
I would suggest you use one of the binaries or submodule approach.

**Comment by kensei** [comment]
Hi, 

https://github.com/RLovelett/eigen/

eigen is not available repository??

**Comment by mousebird** [comment]
Finally fixed.
