### ISSUE TITLE
I want to make a texture of a picture.

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1059]
Dear developer, please tell me what to do?
My pictures:  
![chegui](https://user-images.githubusercontent.com/15685672/40356680-671ebd60-5dec-11e8-8858-c1733b0d227d.png)

My code:
<img width="1401" alt="2018-05-22 6 17 11" src="https://user-images.githubusercontent.com/15685672/40356722-8775b866-5dec-11e8-815d-9fddb618fb5b.png">

**Comment by mousebird** [comment]
I do not understand the question.

**Comment by songyuyang0918** [comment]
I use addWideVectors: draw the line, now want to add texture MaplyTexture to draw lines, I have a picture, you can set it into a texture?
Is there any reference code or demo?
Thank you so much!

**Comment by songyuyang0918** [comment]
I found relevant instances in TextureVectorTestCase.
What you write is to set the image to texture and load it into the drawing surface.
I tried to set the texture according to the code: the image was set up and loaded into the "draw line". The result was unsuccessful. I tried to modify the desc attribute, but still failed.

<img width="964" alt="2018-05-25 6 35 49" src="https://user-images.githubusercontent.com/15685672/40540529-144fd37e-604b-11e8-9af8-980a15b9371a.png">

<img width="1176" alt="2018-05-25 6 39 02" src="https://user-images.githubusercontent.com/15685672/40540533-1825dec6-604b-11e8-9f72-9d66a0ee098f.png">

**Comment by mousebird** [comment]
Only wide vectors work with textures.
That is in the WideVectorsTestCase.  Please look closely at that.

**Comment by coderDeven** [comment]
@songyuyang0918   ,  你解决这个问题了么？ 我也卡住了，能否帮我解答一下，怎么实现用Texture 加载自定义图片的。

**Comment by coderDeven** [comment]
@songyuyang0918  好吧，遗憾... 我继续尝试吧. 谢谢
