### ISSUE TITLE
Rotate a MaplyScreenMarker

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#1060]
Hello,

I have been trying to rotate a MaplyScreenMarker but I couldn't make it work. It always stays up North. Here is the function I created:

`
func instanciate(onMap map: MaplyViewController, atCoordinates coordinates: MaplyCoordinate, withHeading heading: Double)->MaplyComponentObject{
        
        instance2D = MaplyScreenMarker()
        instance2D.loc = coordinates
        instance2D.image = UIImage(named:"airplane2DModel_orange")
        instance2D.color = UIColor.orange
        instance2D.size = CGSize(width: 0.001, height: 0.001)
        instance2D.rotation = heading*Double.pi/180
        
        return map.addMarkers([instance2D], desc: [kMaplyLabelHeight: 100/earthRadius])!
    }
`

Am I doing something wrong?

Cheers,

Sebastien Boulnois.

**Comment by mousebird** [comment]
How about addScreenMarkers?

**Comment by Sebboulnois** [comment]
It works!

Cheers,

Sebastien.
