### ISSUE TITLE
Instanciate a 3D model with MaplyMatrix(yaw:, pitch:, roll:)

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#1061]
Hello!

I am trying to instantiate a 3D model of an airplane in my globe. Since I am want to synchronize the position of the airplane with our B737 cockpit simulator, I wanted to use the MaplyMatrix(yaw:, pitch:, roll:).

Here is my code:

` func instanciate(inGlobe globe: WhirlyGlobeViewController, atCoordinates coordinates: MaplyCoordinate3d, withHeading heading: Double, withPitch pitch: Double, withRoll roll: Double)->MaplyComponentObject{
        instance3D = MaplyGeomModelInstance()
        instance3D.model = model
        let scaletMat = MaplyMatrix(scale: Double(12.0/earthRadius))
        //let rotMat = MaplyMatrix(angle: Double.pi/2.0, axisX: 1.0, axisY: 0.0, axisZ: 0.0)
        let orientationMatrix = MaplyMatrix(yaw: -heading*Double.pi/180, pitch: pitch, roll: roll)
        let localMat = orientationMatrix.multiply(with: scaletMat)
        instance3D.transform = localMat
        instance3D.colorOverride = UIColor.orange
        instance3D.center = MaplyCoordinate3dMake(coordinates.x, coordinates.y, coordinates.z)
        
        return globe.addModelInstances([instance3D], desc: [kMaplyDrawPriority: 1000], mode: MaplyThreadMode.any)!
    } `

Here is what I get:

![fullsizeoutput_bcb](https://user-images.githubusercontent.com/15698398/40428250-d3d348f0-5e6d-11e8-892c-a144a2c671a7.jpeg)

It guess that the original model file that I am using is rotated with 90 degrees off somehow. am I right? If so, how do I fix it?

Edit: I added 90 degrees to whatever input I have for the pitch and it seems to correct the issue. Is there a better solution though?

Cheers,

Sebastien Boulnois.

**Comment by mousebird** [comment]
Heh.  Looks right to me.

I usually have to mess around with a rotation until I get it right.  Pitch is one solution.  Applying a rotation matrix ahead or behind the orientation matrix is a good one too.  Then you're applying a logical yaw/pitch/roll and your model is already in the right orientation.

Of course, the model instancing doesn't care.  It's just a single matrix by the time it gets there.  Whatever incorporates the rotation is fine.

**Comment by Sebboulnois** [comment]
Alright.

Would it be please possible to explain to me how the MaplyMatrix(angle:, axisX:, axisY:, axisZ:) work?

Thanks,

Sebastien.

**Comment by mousebird** [comment]
That's a rotation around each axis.  I like to build them up one by one until I get what I need.

With moving models I'll try to get the model oriented UP at the right point on the globe and then I'll add in the yaw/roll/pitch.

**Comment by Sebboulnois** [comment]
Thanks a lot!

Sebastien.
