### ISSUE TITLE
Vector formats supported in WhirlyGlobe

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#1062]
Hello!

Is it possible to import a regular vector file (i.e. .eps, .svg, other) as a vector object in a globe?

Cheers,

Sebastien Boulnois.

**Comment by mousebird** [comment]
I'm afraid not.

**Comment by Sebboulnois** [comment]
Alright.

Let me explain in details what I want to do in the scope of my experiments for the project.

I collected onboard weather radar images capturing a weather situation:

![scenario 1 before take off - nd range 80 wr 0d](https://user-images.githubusercontent.com/15698398/40478986-80d59dc8-5f18-11e8-8404-7c0cbe3be745.png)

I would like to somehow recreate this in my globe thanks to lofted polygons. What I have done so far is that I would use a web-based shape file generator to "recreate" these shapes and I would then import the stuff as a vector object.  It works:

![green layer contour - shape file](https://user-images.githubusercontent.com/15698398/40479236-1b02c5a6-5f19-11e8-93e4-db8ab3eb40c6.png)

![fullsizeoutput_bcc](https://user-images.githubusercontent.com/15698398/40479376-619d3776-5f19-11e8-970a-8648157b0cf9.jpeg)

The issue in my case is that since the tool does not have any layers capabilities, it is really hard to be precise regarding what you are drawing. In addition, I am stuck on certain geographical locations and cannot move the shape around once it is created. 

Is there any other way, by any other mean, that I can import any object in WhirlyGlobe so I can recreate this onboard weather radar image in 2D and 3D?

Cheers,

Sebastien.

**Comment by mousebird** [comment]
Neat!  We do read GeoJSON, so if you can give those shapes geographic coordinates you could probably convert to that format.

Alternatively, you could get an SVG reader and create the vectors in code, giving them a center around the viewer.

**Comment by Sebboulnois** [comment]
The shape file already embeds geographic coordinates when I export it. If I design a vector over Miami and then export it as a shape file, it will directly display the shape over Miami when I import it in WhirlyGlobe. I could not find a way to move the shape around.

Another issue is that if I create the 3 vectors (i.e. green layer, yellow layer, red layer) in one shape file, I am not sure I can change colors once it is imported in WhirlyGlobe easily. That would be nice if you could confirm that.

As I am doing rapid prototyping here, I wanted to avoid geographic conversions from the onboard weather radar picture to the actual shape file I am creating. This is why I thought of creating regular vectors (e.g. through Adobe Illustrator) that I could draw over the radar image. That would have allowed me to then adjust the scale and the center of the shape directly in WhirlyGlobe to make it match the weather radar image.

The alternative seems time consuming as my experiments period is getting closer. I guess I would have to go with geographic conversions and then draw in my web based tool then.

Let me know your thoughts about this.

Cheers,

Sebastien.

**Comment by mousebird** [comment]
For the shapes in a shapefile, you can get the MaplyVectorObject and then call splitVectors.  That will give you individual vector objects you can manipulate.

I guess what I would do in your case is create the vectors out of arrays in the app.  Then you can move the shapes around by creating new vectors.

**Comment by Sebboulnois** [comment]
Thanks for the trick! I didn't know that.

Are you saying you would create vectors with arrays of coordinates? I am not sure to understand.

**Comment by mousebird** [comment]
MaplyVectorObjects are not meant to manipulate vectors, just represent them.  So you need to pull your data out into a form you can mess around with it.

One way would be to use a data format you can parse easily yourself, like SVG or CSV.  Load your data in, manipulate it in a way you feel comfortable and then create the MaplyVectorObjects from that.

Another would be to use the asCLLocationArrays method on a MaplyVectorObject, ideally after you've split it and manipulate the coordinates.  Then initialize a new VectorObject with the new coordinates.
