### ISSUE TITLE
MaplyVectorObject with holes is filled incorrectly

### ISSUE THREAD

**Issue by marcin-gryszko** [mousebird/WhirlyGlobe#1064]
Hi,
I have problem with filling areals containing holes.
When I set kMaplyFilled to true holes are also filled.
When I set kMaplyFilled to false I see that the line of hole is drawn so the object is created correctly.

 ```
              let woVectorDict = [
                    kMaplyColor: UIColor.blue.withAlphaComponent(0.2),
                    kMaplySelectable: false,
                    kMaplyFilled: true,
                    kMaplyDrawPriority: 1,
                    kMaplyVecWidth: 2.0] as [String : AnyObject]
                var points = [
                MaplyCoordinateMakeWithDegrees(21.675794, 53.843990),
                MaplyCoordinateMakeWithDegrees(21.764032, 53.841814),
                MaplyCoordinateMakeWithDegrees(21.775459, 53.808746),
                MaplyCoordinateMakeWithDegrees(21.668282, 53.812173),
                MaplyCoordinateMakeWithDegrees(21.675794, 53.843990)
                ]
                var holePoints = [
                MaplyCoordinateMakeWithDegrees(21.711013, 53.832270),
                MaplyCoordinateMakeWithDegrees(21.738059, 53.830028),
                MaplyCoordinateMakeWithDegrees(21.725970, 53.817146),
                MaplyCoordinateMakeWithDegrees(21.711013, 53.832270)
                ]
                let vector = MaplyVectorObject(areal: &points, numCoords: Int32(points.count), attributes: nil)
                vector.addHole(&holePoints, numCoords: Int32(holePoints.count))
                self.theViewC?.addVectors([vector], desc: woVectorDict)
```

**Comment by tcriess** [comment]
Hi,
have you tried reversing the order of the coordinate pairs? They appear to be ordered in the same orientation. Don't know if that is actually the problem here, but usually, polygons with holes are defined by an outer closed line string given in a certain orientation (f.e. counter-clockwise) and one or more closed line strings that define the holes, but those are ordered the other way (f.e. clockwise). So it might be worth a try.

**Comment by marcin-gryszko** [comment]
Thanks.
Tried that. No difference.

**Comment by mousebird** [comment]
You could try explicitly tessellating the polygon before passing it in.
Take a look at the VectorHoleTestCase in the AutoTester for an example.

**Comment by marcin-gryszko** [comment]
It worked. 

It looks like a workaround because this time there is a problem with displaying vector as a linestring but it is better solution than none. 

Thanks.
