### ISSUE TITLE
Questions about Marker Clustering

### ISSUE THREAD

**Issue by nhevaweb** [mousebird/WhirlyGlobe#1065]
Clustering works great but I was wondering how to detect if a MaplyScreenMarker is in fact clustered with others or is standing alone on the map. In other words: how can I know if a marker is clustered or not

I tried to use the method:
`- (NSArray * _Nonnull)objectsAtCoord:(MaplyCoordinate)coord;`
Using this logic: if it does return nil or an empty array it means that the marker isn't at his supposed position so it is clustered.
For some reason this method doesn't return any MaplyScreenMarker. Only one MaplyVectorObject which description is in fact the geo feature below my markers.

**Comment by nhevaweb** [comment]
Indeed the `allSelect: `works but it only gets triggered on selection but I'm trying to find out which ones are clustered or not on the fly.
I searched on the documentation a way to trigger this event but it seems the only way without re-building the library would be to 'fake' tap on the view at the position of coordinate wanted.
Thanks for the advice

**Comment by mousebird** [comment]
We don't have that method at present.   The full selection only works as a delegate.
