### ISSUE TITLE
Eigen submodule link is broken

### ISSUE THREAD

**Issue by alexstgeorge** [mousebird/WhirlyGlobe#1066]
I think the eigen submodule that this SDK uses is broken. It looks like the [eigen repository](https://github.com/RLovelett/eigen.git/) was either deleted or made private since it returns a 404 when I try to access it.

**Comment by alexstgeorge** [comment]
I've change the submodule to link to [this repository](https://github.com/eigenteam/eigen-git-mirror.git) instead (which looks like the official eigen repo) and it seems to be working now. You can see my updated version of the SDK at [this link](https://github.com/alexstgeorge/WhirlyGlobe/tree/feature/single-frame-reload) with the relevant commits being [here](https://github.com/alexstgeorge/WhirlyGlobe/commit/fa24e964767610be54e58ad20c1ccf3be1519a3e) and [here](https://github.com/alexstgeorge/WhirlyGlobe/commit/2909e389e71f8ba233efcd4f3d9405bcdcb56735).

Thanks.

**Comment by mousebird** [comment]
Thanks.  I've got a version that points to the mirror.  The only issue that may come up is how they create the mirror.  There used to be a problem that they blew away all the old commits each time, so you couldn't point to it consistently.

Haven't got much choice, really, so we'll switch to this.

**Comment by alexstgeorge** [comment]
Oh I see... Would it be worth it to fork the eigen repo to avoid this issue? That way you can always be sure that there is a valid endpoint to get the module. 

On a side note, would running `$ git submodule update --remote` also avoid this issue? (Assuming you assign the master branch to the submodule in the `.gitmodule`) I don't really know how submodules work, but from what I've read it seems like it would pull and update the submodule to the most recent commit on the branch, thus always giving us a valid endpoint to get the submodule. But then again, this is the first time I work with submodules so I might be entirely wrong about this.

**Comment by mousebird** [comment]
There's been a lot of progress in submodules since I set this up.  I need to do some research.

**Comment by mousebird** [comment]
I just gave up on submodules for the packages I use.  Most of the questions I get are about Cocoapods and submodules and I'm just sick of it.

So.  The dependent libraries are now all included in the local_libs directory in the latest develop.  We should have the right version of all the libraries now.

**Comment by alexstgeorge** [comment]
Ok thanks for the heads-up. I'll be sure to pull the updates.

**Comment by alexstgeorge** [comment]
So this shift has seemed to have broken the `gradlew` build script on the Android side. I've submitted [this issue](https://github.com/mousebird/WhirlyGlobe/issues/1084) about that.

**Comment by saildronesteve** [comment]
Oh, right.  I'll try to push those fixes tonight.  Should just be path changes.
