### ISSUE TITLE
Some of the globeViewController methods, the mapViewController doesn't

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1067]
Hello!
I use the MapViewController to display the map.
Need to monitor gestures, I found that globeViewController delegate (globeViewController: allSelect: atLoc: onScreen: and globeViewController: didMove:) is listening to what I need.
But I'm using MapViewController, which doesn't have a delegate.
Why is that?
Do I have to write one myself?

**Comment by mousebird** [comment]
MaplyViewController's delegate is called MaplyViewControllerDelegate

**Comment by songyuyang0918** [comment]
I know what you mean!
MaplyViewControllerDelegate is also not the two methods,
I went to the copy write their own according to globeViewControllerDelegate, although can appear effect, but I still want to ask your opinion!
Is my framework version too low?

**Comment by mousebird** [comment]
The allSelect: method is available in the MaplyViewControllerDelegate.
Make sure you're on the develop branch.

**Comment by songyuyang0918** [comment]
You mean:
Only in the development environment, I can use the inside of the WhirlyGlobeViewControllerDelegate (globeViewController: allSelect: atLoc: onScreen method:)?

**Comment by mousebird** [comment]
No, the develop branch on github.  That's the latest.
