### ISSUE TITLE
The problem of animation display of MaplyScreenMarker

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1068]
I want to remove the animation display of MaplyScreenMarker, but I did not find the attribute in the corresponding class, please tell me.
Thank you very much!

**Comment by mousebird** [comment]
I'm not sure what you're asking.

**Comment by songyuyang0918** [comment]
<img width="513" alt="2018-06-05 6 13 43" src="https://user-images.githubusercontent.com/15685672/40970134-4b1b01a4-68ec-11e8-87ed-1103a3536ebf.png">
<img width="524" alt="2018-06-05 6 13 51" src="https://user-images.githubusercontent.com/15685672/40970221-7ebc1d90-68ec-11e8-843d-62edab4bdfde.png">
Look, I have a moving object, which is created by constantly deleting it. Now, there are many objects that have not been eliminated in time. I think it is an animation effect.

**Comment by mousebird** [comment]
Use the mode: argument of the addScreenMarkers and removeObjects methods.  Set that to MaplyThreadCurrent.  It will force the change immediately.

**Comment by songyuyang0918** [comment]
Following your instructions, the thread is changed, which is a lot smoother, but there are still multiple objects that are not eliminated in time during sliding.
I think I should is the effect of loading animation, that is to say, draw lines and plot points, will be before the formation of a transitional display (display) slowly, I actually want to close him, do not know to have the desc

**Comment by mousebird** [comment]
I'm sorry, I didn't follow that.
