### ISSUE TITLE
I want to realize a function of moving the point object generated by MaplyScreenMarker

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1069]
I want to realize a function of moving the point object generated by MaplyScreenMarker, and keep moving through PanDelegate.
I want to know, does this function need to be implemented by myself or is there a specific method?
My current thinking is: through the didMove agent, the generated point of MaplyScreenMarker has been redrawn all the time. Do you have any good idea?
Please!
Thank you very much!

**Comment by mousebird** [comment]
Yes, the MaplyScreenMarker must be removed and a new one added.
