### ISSUE TITLE
MaplyViewController stops detecting layout changes after a tap

### ISSUE THREAD

**Issue by nhevaweb** [mousebird/WhirlyGlobe#1074]
Hi everyone.

I'm having a weird issue with the `develop branch`.
I was using a flat MaplyViewController and was working with cluster with the `release 2.5` of the framework and everything worked fined.

I pulled out the `last develop branch` and used it as a submodule, I can pinch to zoom in/out and it works just like before...
However when I tap on the map (on anything) however, my MaplyScreenMarker and MaplyScreenLabel holds still and doesn't move (no grouping/degrouping within the cluster, nor labels placement changes). Even markers selection won't work
It's like the interaction layer doesn't detect any changes after the tap...

Any thoughts?  ideas ? Thanks

**Comment by mousebird** [comment]
Yeah, I've noticed this one with clustering.  I'll dig into it.

**Comment by mousebird** [comment]
Yes.  It's a very odd bug.  Hopefully not too long to fix it.

**Comment by mousebird** [comment]
I believe this is fixed in the latest develop.

**Comment by nhevaweb** [comment]
@mousebird Sorry for the late answer but yes it's fixed now! Thanks
