### ISSUE TITLE
Use of undeclared type 'MaplyLocationTrackerDelegate' (iOS)

### ISSUE THREAD

**Issue by vedaarya** [mousebird/WhirlyGlobe#1075]
I am following the LocationTracking tutorial to implement GPS functionality in one of my swift project. But when I try to implement MaplyLocationTrackerDelegate I am getting compiler error as : Use of undeclared type 'MaplyLocationTrackerDelegate'. Do i have to import any other framework.

**Comment by mousebird** [comment]
The LocationTrackingRealTestCase in the AutoTester appears to do just that in Swift.
Make sure you're on the develop branch.

**Comment by vedaarya** [comment]
I am using Whirlyglobe library using cocoapods. And the pods don't have files related to LocationTracking. So instead of cocoapods should i add the source (WhirlyGlobeMaplyComponent.xcodeproj) directly into my project or is there any other way around. Can you please assist me as how should i get the LocationTracking work in my project. Thanks
