### ISSUE TITLE
About map zoom control [IOS]

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1076]
Dear developers,
I want to know how to use fixed values to control the scale of the map to change and display?
Or give me an idea,
Thank you very much.

**Comment by songyuyang0918** [comment]
In other words, how to customize control map zoom,
Hope to have done similar try of the master, can tell me, thank you!

**Comment by saildronesteve** [comment]
You set the height of the viewer above the map.  That's in setHeight: and it takes a floating point value.  Try some of the values you see in the AutoTester app to find one that works for you.
