### ISSUE TITLE
How do I keep the display the same when the view width of the map changes [IOS]

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1077]
Dear developers, hello!
I changed the width of maplyviewcontroller.view,
Notice that the display of the view has changed (enlarged and reduced according to the Width change),
How do you keep it constant?

![fd0158f4338ad70ceae8925caa706025](https://user-images.githubusercontent.com/15685672/42212671-61ba6022-7ee9-11e8-93b5-dd3ba73ff3b9.jpeg)

![a0491c373a9c18b5778b8c251ae0d2b2](https://user-images.githubusercontent.com/15685672/42212678-66ab7ddc-7ee9-11e8-9be4-ab18ccd2940c.jpeg)

**Comment by saildronesteve** [comment]
You would need to calculate the viewing are and then adjust the height to the new value.
