### ISSUE TITLE
[IOS] I want to get the offset of the map in real time and pass it to another map for simultaneous movement.

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1078]
Dear developers, hello!
I want to get the offset of the map in real time and pass it to another map for simultaneous movement.
Do you have any good ideas?

**Comment by songyuyang0918** [comment]
I tried initAsTetheredFlatMap: tetherView: method,
But the map doesn't show up. It's embarrassing.

**Comment by mousebird** [comment]
Don't use that method.  You can get location and gesture feedback via the GestureDelegate
