### ISSUE TITLE
[IOS] I want to add UILabel in MaplyScreenMarker

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1080]
Dear developers, hello!
I want to add UILabel in MaplyScreenMarker,
Can't find a View or a UIImageView?

<img width="882" alt="2018-07-05 4 59 24" src="https://user-images.githubusercontent.com/15685672/42313228-cba001a4-8074-11e8-9389-226b87c2b006.png">

**Comment by mousebird** [comment]
You want a MaplyScreenLabel

**Comment by songyuyang0918** [comment]
I tried MaplyScreenLabel,
But I need UILabel to be displayed in the middle of the imgView of MaplyScreenMarker,
I looked at all the objects, and they don't support that.
So I want to add it myself, but I can't find the implementation class,
Could you tell me what to do?

**Comment by mousebird** [comment]
You could try using a MaplyAnnotation instead

**Comment by songyuyang0918** [comment]
Dear developer, I tried to implement my requirements using MaplyAnnotation.
But the result wasn't what I wanted.
Attached below:
![82b898f61ca4eb6eeab420df13af307d](https://user-images.githubusercontent.com/15685672/45741600-99378100-bc2a-11e8-98cc-6e61ae692c39.png)
The "1" in the figure is displayed dynamically by UILabel, but the appearance of this bubble makes me wonder what to do.
I just want to show the following style, I hope you can tell me, thank you!
<img width="166" alt="2018-09-19 4 42 00" src="https://user-images.githubusercontent.com/15685672/45741909-4e6a3900-bc2b-11e8-9ecb-9e8a05f9c73a.png">
<img width="166" alt="2018-09-19 4 42 00 2" src="https://user-images.githubusercontent.com/15685672/45741916-4f9b6600-bc2b-11e8-8adb-2c93fce9d621.png">
"1" and "2" are dynamically generated, and I think I should require a UILabel

**Comment by mousebird** [comment]
Rather than use a MaplyAnnotation, use the ViewTracker to move your own UIViews around.

Alternatively you could add those as ScreenMarkers.
