### ISSUE TITLE
[IOS] The map I showed, when I zoom in and out it loads slowly

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1081]
Dear developers, hello!
The map I showed, when I zoom in and out it loads slowly,
Please refer to the zip video file I sent for details. Please tell me how to deal with this matter?

[Calm 2018-07-07 17.35.21.mp4.zip](https://github.com/mousebird/WhirlyGlobe/files/2165957/Calm.2018-07-07.17.35.21.mp4.zip)

Below is my code property setup diagram:

<img width="1340" alt="2018-07-05 5 40 08" src="https://user-images.githubusercontent.com/15685672/42315648-900ddc82-807a-11e8-9081-694cb583a275.png">

**Comment by songyuyang0918** [comment]
My data sources are all from local databases and should be fast

**Comment by mousebird** [comment]
A frameInterval of 5 would be 12 frames/second.  Try leaving it the default.
Also make sure you have a version of the toolkit compiled with Release mode.
