### ISSUE TITLE
iOS 9.3.5 / iPad 2 No map and crashing in AutoTester

### ISSUE THREAD

**Issue by paulgee31** [mousebird/WhirlyGlobe#1083]
When building the AutoTester for iOS 9.3.5 and running on an iPad 2, the AutoTester fails to display any mapping source tests, just a black screen.

When running the ScreenLabels test, the app crashes with a  EXC_BAD_ACCESS (code=1, address=0x0) in BasicDrawable.mm
in the method:
// Adds the basic vertex data to an interleaved vertex buffer
void BasicDrawable::addPointToBuffer(unsigned char *basePtr,int which,const Point3d *center) 

line 673:
            memcpy(basePtr+pointBuffer, &pt.x(), 3*sizeof(GLfloat));

**Comment by mousebird** [comment]
Should all be fixed now.
