### ISSUE TITLE
Vectors problems.

### ISSUE THREAD

**Issue by andreipanishev** [mousebird/WhirlyGlobe#1085]
Can not draw vectors from directory. 

let allOutlines = Bundle.main.paths(forResourcesOfType: "geojson", inDirectory: "country_json_50m") - Does not work

let allOutlines = Bundle.main.paths(forResourcesOfType: "geojson", inDirectory: nil) as! [String] - Works

Thank you in-advance

**Comment by andreipanishev** [comment]
if let attrs = wgVecObj.attributes,
The problem is here, in function add countires

**Comment by mousebird** [comment]
Thanks.  The tutorials need an update.
