### ISSUE TITLE
Does not work MaplySphericalMercator

### ISSUE THREAD

**Issue by devRizvan13** [mousebird/WhirlyGlobe#1086]
Look, I'll initialize it correctly.

```
private func setupTiles() {
        guard let filepath = Bundle.main.path(forResource: "tiles-world-simple", ofType: "mbtiles"),
        let tileSource = MaplyMBTileSource(mbTiles: filepath),
        let coordinateSystem = MaplySphericalMercator(webStandard: ()),
        let layer = MaplyQuadImageTilesLayer(coordSystem: coordinateSystem, tileSource: tileSource)
        else { return }

        layer.color = Color.mapLayerBackground
        layer.imageDepth = 1
        layer.singleLevelLoading = true
        layer.useTargetZoomLevel = true
        layer.handleEdges = true
        layer.coverPoles = true
        layer.numSimultaneousFetches = 16
        add(layer)
}
```

**Comment by mousebird** [comment]
Try with the geography class example first.  It might be the MBTiles file.

**Comment by devRizvan13** [comment]
I changed **mbtiles** **to geography-class_medres** but it still does not work. Did you mean it?

**Comment by mousebird** [comment]
Well we have a Geography Class example in the AutoTester app.  So I'd suggest running that and then modifying it to load your own data.

**Comment by devRizvan13** [comment]
Thank you. But I have a request please update the library. I need to import this file "#import <libXML / Parser.h>" into "Pods / WhirlyGlobe / WhirlyGlobeSrc / local_libs / KissXML / DDXMLDocument.m" after each update of pods.
