### ISSUE TITLE
Debugging Android WhirlyGlobe

### ISSUE THREAD

**Issue by pangers** [mousebird/WhirlyGlobe#1088]
Hi, I would like to make some modifications to the library and be able to debug my modifications in an efficient manner. Currently I am able to build the library from source and import the .aar file into an app (eg. AutoTesterAndroid). However when trying to debug, the breakpoints don't seem to enter the native parts of the code. Also, with my current workflow, changes to native code would require building the .aar binary and importing into the app again. Is there a way to simplify this workflow and be able to debug the native code?

Thanks

**Comment by mousebird** [comment]
The structure of the project predates newer versions of Android Studio.  I use to run Eclipse and gdb in  Emacs to properly debug both Java and native code.

You don't have to do that anymore.  If you compile the AAR right you can step into the native code and set breakpoints.  But you can't edit and automatically have it recompile at the moment.

**Comment by pangers** [comment]
Thanks for the info.

Would you be able to elaborate on how to compile the AAR in the correct manner to allow stepping into native code and setting breakpoints?

**Comment by mousebird** [comment]
I compile the AAR in Debug mode.
