### ISSUE TITLE
[iOS] Add pan gesture to markers

### ISSUE THREAD

**Issue by vedaarya** [mousebird/WhirlyGlobe#1089]
Hello,

I need to make the markers added on globe movable using drag/drop or the pan gesture. I checked in the documentation but i did not find anything to add gestures to the markers. Please let me know how can this be achieved.

Thanks

**Comment by mousebird** [comment]
You need to implement that yourself.  Add and remove the markers using the ThreadCurrent mode so it happens immediately.

I've done similar things for clients in the past.  Works fine.  But it's definitely not in the toolkit by default.

**Comment by vedaarya** [comment]
Hi Steve,

Can you please guide me as how can i get the drag event so that i can
remove and add marker as i move the finger on ipad screen.

Thanks

**Comment by saildronesteve** [comment]
In the past I've used the long press and then added and removed the screen marker as they move.

**Comment by vedaarya** [comment]
Thanks Steve for the suggestion.

I was able to move the screen marker  (add and remove) using the long press
gesture. The screen marker moves for a while after long press and then the
globe moves. Is there any way i can stop moving the globe when there is
long press.

I tried using autoMoveToTap = false and then i had also set later,
rotateGesture = false pinchGesture = false, but it didn't worked instead
the globe was behaving weirdly . Can you please let me know if this is
possible.

Thanks

**Comment by mousebird** [comment]
panGesture = false

**Comment by vedaarya** [comment]
Thanks. This worked.
