### ISSUE TITLE
Tapping on screen marker return ALL objects that the marker represents

### ISSUE THREAD

**Issue by rmandavilli** [mousebird/WhirlyGlobe#1093]
Hello, I am looking to implement a feature that displays the information associated with all objects that a marker represents.  So, for example, if markers are displayed for some information from a city, such as New York, then at the globe view, there will probably be only one marker.  As we zoom in, different markers are then displayed.  In the case, where only one marker is displayed for a group of objects, how can I get a list of objects that the one marker represents when the user taps on this "high-level" marker?

**Comment by mousebird** [comment]
The selection logic will return the marker the user taps on.  If you're using clustering, it will return a list of markers.  The rest of the logic is in your app.
