### ISSUE TITLE
how to add custom picture to create wideVector

### ISSUE THREAD

**Issue by coderDeven** [mousebird/WhirlyGlobe#1094]
Dear sir, 
I want to use some pictures to make them as a dashed line . But the wide vector test case seems not works.  
Is there any method to add custom picture to create wideVector ?

e.g :  
I want to create a wide vector use the picture below .
![image](https://user-images.githubusercontent.com/18394988/44127873-0a841758-a072-11e8-8d75-06b2d54adbca.png)

The target line is : 
![image](https://user-images.githubusercontent.com/18394988/44127949-9204f652-a072-11e8-8272-994beaeed554.png)
###

**Comment by mousebird** [comment]
Wide Vectors do take a texture.  Take a look at the wide vector test case in the AutoTester.  There's a dashed line example.

**Comment by LiuzhongweiHup** [comment]
Have you achieved it? Can you share a solution?
