### ISSUE TITLE
iOS - Showing dots/points not working.

### ISSUE THREAD

**Issue by vedaarya** [mousebird/WhirlyGlobe#1095]
Hello,

I want to show points/dots on globe. i am using following code : 
func addCircles() {

       vectorDict = [kMaplyColor: UIColor.red, kMaplySubdivType: kMaplySubdivSimple,
                     kMaplySubdivEpsilon: 0.001,
                     kMaplyVecWidth: 14.0]

       let capitals = [MaplyCoordinateMakeWithDegrees(-77.036667, 38.895111),
                       MaplyCoordinateMakeWithDegrees(120.966667, 14.583333),
                       MaplyCoordinateMakeWithDegrees(55.75, 37.616667),
                       MaplyCoordinateMakeWithDegrees(-0.1275, 51.507222),
                       MaplyCoordinateMakeWithDegrees(-66.916667, 10.5),
                       MaplyCoordinateMakeWithDegrees(139.6917, 35.689506),
                       MaplyCoordinateMakeWithDegrees(166.666667, -77.85),
                       MaplyCoordinateMakeWithDegrees(-58.383333, -34.6),
                       MaplyCoordinateMakeWithDegrees(-74.075833, 4.598056),
                       MaplyCoordinateMakeWithDegrees(-79.516667, 8.983333)]

       let circles = capitals.map { capital -> MaplyVectorObject in
           var ss = capital
           let vector = MaplyVectorObject(point: &ss, attributes: nil)
           return vector!
       }
       _ = self.theViewC?.addVectors(circles, desc: self.vectorDict)

   }

The above code is not working. Can you please guide on this.

Thanks,
Vandana

**Comment by mousebird** [comment]
Use MaplyScreenMarker for points.  Vectors won't show points.
