### ISSUE TITLE
iOS : Showing tick marks on globe

### ISSUE THREAD

**Issue by vedaarya** [mousebird/WhirlyGlobe#1096]
Hello,

We have following requirements to show vectors programmatically on the globe. But we are facing memory issues while rendering this data. 
- Show 10 degree graticules lines and degree labels upto zoom level 5.
- Show 1 degree graticules lines, degree labels and 30,10,5 minute tickmarks between zoom level 5 above
- Show 1 minute dot tickmarks above zoom level 8
- Here is the code snippets for 1 minute tick marks used to render vectors programatically. 

func create1MinuteTicks() {

       vectorDict = [kMaplyColor: UIColor.green, kMaplySubdivType: kMaplySubdivSimple, kMaplyDrawPriority: 1000,
                     kMaplyVecWidth: 2.0]

       var vecObj = [MaplyVectorObject]()

       // 1 Minute
       // longitude
       var longitude = 0.000000
       for x in stride(from: -180, to: 180, by: 1){
           for y in stride(from: -90, to: 90, by: 1){
               for count in 1...60 {
                   if count == 1{
                       longitude = Double(y) + 0.0166667
                   }else{
                       longitude += 0.0166667
                   }
                   var coordinates: [MaplyCoordinate] = []
                   coordinates.append(MaplyCoordinateMakeWithDegrees(Float(x)-0.001, Float(longitude)))
                   coordinates.append(MaplyCoordinateMakeWithDegrees(Float(x)+0.001, Float(longitude)))

                   if let lineShape = MaplyVectorObject(lineString: &coordinates, numCoords: Int32(coordinates.count), attributes: nil) {
                       vecObj.append(lineShape)
                   }
               }
           }
       }
       _ = self.theViewC?.addVectors(vecObj, desc: self.vectorDict, mode: MaplyThreadCurrent)

       vecObj = [MaplyVectorObject]()

       // 1 Minute
       // latitude
       var latitude = 0.000000
       for x in stride(from: -90, to: 90, by: 1){
           for y in stride(from: -180, to: 180, by: 1){
               for count in 1...60{
                   if count == 1{
                       latitude = Double(y) + 0.0166667
                   }else{
                       latitude += 0.0166667
                   }
                   var coordinates: [MaplyCoordinate] = []
                   coordinates.append(MaplyCoordinateMakeWithDegrees(Float(latitude),Float(x)-0.001))
                   coordinates.append(MaplyCoordinateMakeWithDegrees(Float(latitude),Float(x)+0.001))

                   if let lineShape = MaplyVectorObject(lineString: &coordinates, numCoords: Int32(coordinates.count), attributes: nil) {
                       vecObj.append(lineShape)
                   }
               }
           }
       }

       _ = self.theViewC?.addVectors(vecObj, desc: self.vectorDict, mode: MaplyThreadCurrent)
   }

Previously we had used TileMill to show the 10 degree, 1 degree, 30 min, 60 min, 5 min and 1 min tick marks and generated the mbtile to show on globe. But the mbtile size was very huge around 650 MB which was not feasible to ship with the app. So we decided to do all the tick marks programatically, but we are facing memory issues. Can you please guide on this scenario? Your help will be really appreciated.

Thanks,
Vandana

**Comment by mousebird** [comment]
You need to build the geometry on demand.
Take a look at the QuadPagingLayer.  There are some examples in the AutoTester.
