### ISSUE TITLE
Labels not being rendered correctly on latest develop branch

### ISSUE THREAD

**Issue by dragonikpl** [mousebird/WhirlyGlobe#1097]
I have Whirly framework build from latest develop, but I have some issues with `MaplyScreenLabel`.

When I add labels on visible screen they will render correctly, but when I move the map the a different place where I have more labels they won't show up. I have no `kMaplyMaxVis` and `kMaplyMinVis` set, priorities are ok, checked with different fonts, issue still is showing up.

**Comment by saildronesteve** [comment]
Does this happen with the screen label test case in the AutoTester
