### ISSUE TITLE
iOS : Change location marker icon

### ISSUE THREAD

**Issue by vedaarya** [mousebird/WhirlyGlobe#1098]
Hello,

We have used MaplyLocationTracker for simulating GPS. Can we change the default blue circle icon to a different image?

Thanks.

**Comment by saildronesteve** [comment]
Apparently not.  It's being generated inside MaplyLocationTracker.mm

**Comment by vedaarya** [comment]
Thanks for the reply. Is there any workaround you can suggest to achieve this. Your help will be greatly appreciated.

**Comment by saildronesteve** [comment]
You would need to dig into the code and change it.  Pass in a set of UIImages rather than letting the module generate its own.
