### ISSUE TITLE
ios - screen label - centroid error

### ISSUE THREAD

**Issue by yogesh2209** [mousebird/WhirlyGlobe#1099]
@mousebird  @dragonikpl
Hi,
I am trying to give centroid() to label.loc but there is no centroid. and if i pass label.loc = wgVecObj.center() - it shows labels on wrong side. 

Please help.

<img width="1159" alt="screen shot 2018-08-27 at 5 35 13 pm" src="https://user-images.githubusercontent.com/8548476/44693949-c6c04e80-aa1f-11e8-9ed8-e7cbb32c927e.png">

**Comment by mousebird** [comment]
The centroid call returns a Bool to verify that it worked, but you have to pass in an unsafe MaplyCoordinate.
