### ISSUE TITLE
Using submodule integration requires the framework to be included in Embedded Binaries

### ISSUE THREAD

**Issue by hneil** [mousebird/WhirlyGlobe#1100]
I'm using the submodule integration approach on the develop branch with Xcode 9.4.1. I've found that in addition to including the framework in the link binary section of Build Phases, it also needs to be added to the Embedded Binaries section, or the app crashes with a dyld: Library not loaded: @rpath/WhirlyGlobeMaplyComponent.framework/WhirlyGlobeMaplyComponent Resaon:image not found  error. The only problem with this is that while this works for iOS 11.0 and later, it causes a device crash in iOS 9.5 (not simulator though) in the getManager(const char *name) method of scene.mm. Any ideas on how to get this to work on iOS 9.5? Thanks.

**Comment by saildronesteve** [comment]
I'm looking into ios9 issues for another user.  Should be fixed soon enough.

As for the submodule issue, I'll need to update the documentation.

**Comment by hneil** [comment]
Thanks.  Submodule integration is still my least favorite form of integration - any chance of resuming the nightly builds, or fixing the development branch podspec.

**Comment by mousebird** [comment]
The podspec is soon.  I pulled all the annoying submodules into a local directory to make that easier.  2.6 should be podspec friendly soon.

**Comment by mousebird** [comment]
And so it is.
