### ISSUE TITLE
globe zoom doesn't work

### ISSUE THREAD

**Issue by yogesh2209** [mousebird/WhirlyGlobe#1101]
@mousebird 
globeViewC?.setZoomLimitsMin(1.0, max: 2.0) not working.

Globe can be zoomed more and more..don't know why. any help would be much appreciated?

**Comment by mousebird** [comment]
ZoomLimits should work.
Try looking at the StamenWatercolorRemote example.  I'd suggest modifying the setZoomLimits call there to verify that it does what you need.

**Comment by yogesh2209** [comment]
Thanks! i got my mistake!
