### ISSUE TITLE
i have 2 questions: is it free for simple using, and give some example.

### ISSUE THREAD

**Issue by fukemy** [mousebird/WhirlyGlobe#1102]
First give bigggg thanks to development team. So hard to found our project.
I am finding free opensource project for map, just display map and add some object like image, marker, polyline into map.

Can you answer my question, i know it's a bit sily. THanks you :)

**Comment by mousebird** [comment]
There is an AutoTester app included with the distribution.  You might want to build that and start there.

**Comment by fukemy** [comment]
"There is an AutoTester app included with the distribution" -> Can you explain that line? 

I just want to ask did i have to pay money for over sample 50000 map download, or similar.... Thanks

**Comment by mousebird** [comment]
WhirlyGlobe is a map toolkit.  We don't provide a map service.

The toolkit is on github (https://github.com/mousebird/WhirlyGlobe) and includes an AutoTester app in the ios directory.
