### ISSUE TITLE
How to remove shapes? iOS

### ISSUE THREAD

**Issue by yogesh2209** [mousebird/WhirlyGlobe#1107]
Hi,

Is there any way to remove shapes that has been already added? @mousebird 

I have the reference of the object and self.globeVC.remove(object here) doesn't work.

Also, how can i have the 250 m resolution of the point (shape) ? I need to have the radius of the shape to 250 m, but how can i achieve that? 

Any help in unit conversions for the radius of the shapes?

Any help would be highly appreciated.

**Comment by mousebird** [comment]
Each add method return s a MaplyComponentObject.  You need to pass that to remove.

To convert to meters, divide by the earth's radius: 6371000 m

**Comment by yogesh2209** [comment]
thank you so much for your prompt response. :)

**Comment by grantd77** [comment]
hello,
I also need some help with this kind of removal from a 2D map.

I have taken over a map app project, where objects are added to the map using **addActiveObject**.
When the objects are no longer required and are removed using **removeActiveObject** they remain on the map. These include map markers, and routes from location to location.

Is there anything special that needs to be done to make this work or force the map to redraw without the objects that were added?

Thank you

**Comment by mousebird** [comment]
Most developers don't use active objects, so this must be a fairly advanced project.

Active Objects are just callbacks right before the rendering phase.  You would need to add special remove calls to have them clean up their data.  Only they know what that is.

It might also be a good idea to sign up for support if this is an app with revenue.  I can answer these sorts of questions directly if you have a support contract.

**Comment by grantd77** [comment]
Hi again, after a bit of digging around I figured out how to remove the objects from the map.
