### ISSUE TITLE
How to draw special line

### ISSUE THREAD

**Issue by lyp1992** [mousebird/WhirlyGlobe#1108]
I have a demand, drawing such lines on the map
<img width="169" alt="2018-09-25 4 19 54" src="https://user-images.githubusercontent.com/14368439/46002055-8ec03000-c0df-11e8-8464-118947bc733b.png">
I tried to use the method of painting line，like this
<img width="610" alt="2018-09-25 4 28 49" src="https://user-images.githubusercontent.com/14368439/46002246-23c32900-c0e0-11e8-9455-ae3143e1b083.png">
With my local pictures.Method to replace the drawing pictures, but doesn't work.
Can you give me a guide, is this why ? thank you

**Comment by mousebird** [comment]
Please look at the WideVectorsTestCase in the AutoTester app for an example of how to build a dashed line.

**Comment by lyp1992** [comment]
Mr.  I'll find the method in this class, try to change his color, but I find that fill color won't change, so I want to ask, have in the content of the framework is set for transparent images
![11538017403_ pic_hd](https://user-images.githubusercontent.com/14368439/46121231-7b2ed980-c245-11e8-82c1-2897af4b1809.jpg)
<img width="596" alt="2018-09-27 11 06 44" src="https://user-images.githubusercontent.com/14368439/46121237-81bd5100-c245-11e8-9c31-b7b81b1550cf.png">
The picture above, for example, I have already set up the grey, but she is still transparent。
Can you help me to solve, thank you

**Comment by lyp1992** [comment]
hi, Sir, I find a way to draw a dotted line in the class.I tried to change the picture of the filling line, but I found the picture color was changed to transparent.
![11538017403_ pic_hd](https://user-images.githubusercontent.com/14368439/46121403-2c357400-c246-11e8-9150-5c7a088c5cf1.jpg)
<img width="596" alt="2018-09-27 11 06 44" src="https://user-images.githubusercontent.com/14368439/46121407-30fa2800-c246-11e8-800c-b563572237b4.png">
In the above, for example, I have to fill the colors of the picture changed to gray, but is still a transparent display。
Could you help me solve this is why，thank you

**Comment by mousebird** [comment]
Search for kMaplyColor in the WideVectorsTestCase
