### ISSUE TITLE
Fill color in country / state in Globe - iOS 

### ISSUE THREAD

**Issue by yogesh2209** [mousebird/WhirlyGlobe#1111]
Hi,

Is there any way to fill color in country or states or boundaries ( VECTORS i mean - particular region of geojson files - shapefiles) of that country ?

Thanks in advance!

@mousebird

**Comment by mousebird** [comment]
Take a look at the VectorHoleTestCase.
Look for kMaplyFilled.

**Comment by yogesh2209** [comment]
Thanks but i need to fill different color for different geojson file, but we pass array of objects to add vector method and dictionary (which contains one color - maplyfilled). Is there any way to pass one color per geojson file ?

**Comment by mousebird** [comment]
You can add them individually or you can set kMaplyColor per feature.
