### ISSUE TITLE
Vector boundary and maplyfilled color different ios?

### ISSUE THREAD

**Issue by yogesh2209** [mousebird/WhirlyGlobe#1112]
Hi,

Is there any way to have vector boundary and maplyfilled color different?
Right now, 

  vectorDict = [
            kMaplyColor: UIColor.black,
            kMaplySelectable: true as AnyObject,
            kMaplyFilled: true as AnyObject,
            kMaplyVecWidth: 4.0 as AnyObject
        ]

MaplyColor is Black - vector boundaries are black but when i do maplyfilled to true, it just fills black inside also. I need different color for that, is that possible?
@mousebird  Please reply.

**Comment by mousebird** [comment]
Just add it twice.
