### ISSUE TITLE
iOS - Show labels and ScreenMarkers parallel to line.

### ISSUE THREAD

**Issue by vedaarya** [mousebird/WhirlyGlobe#1113]
Hi ,

In my app I have to show the label and image(screenmarker) parallel to line of the route. Fig :

![image](https://user-images.githubusercontent.com/36707476/46352430-61432b80-c677-11e8-82bb-bcb4f8a3beb4.png)

I tried to find the bearing between 2 points and gave this value to label rotation but that is not working. 

Can you please help me out on how to achieve this.

Thanks,
Vandana

**Comment by mousebird** [comment]
Rotation is how I would would do it, so that's the right approach.
I'm not sure what your problem might be.

**Comment by dmertsalov** [comment]
> Hi ,
> 
> In my app I have to show the label and image(screenmarker) parallel to line of the route. Fig :
> 
> ![image](https://user-images.githubusercontent.com/36707476/46352430-61432b80-c677-11e8-82bb-bcb4f8a3beb4.png)
> 
> I tried to find the bearing between 2 points and gave this value to label rotation but that is not working.
> 
> Can you please help me out on how to achieve this.
> 
> Thanks,
> Vandana

Hi! Please tell me what source you're using to display the surface layer?

**Comment by vedaarya** [comment]
Its a globe created using tilemill and the lines and text is been added programatically.

**Comment by dmertsalov** [comment]
> Its a globe created using tilemill and the lines and text is been added programatically.

Very simple texture without countries and cities!
can you give a link to tilemill?
