### ISSUE TITLE
In VectorManager. Mm time code is too long in this class

### ISSUE THREAD

**Issue by lyp1992** [mousebird/WhirlyGlobe#1116]
Hello, we through a lot of testing, found that when loading large amounts of data, in VectorManager. Mm class time this code is too long

<img width="662" alt="2018-10-09 6 54 26" src="https://user-images.githubusercontent.com/14368439/46665099-6a8f4380-cbf5-11e8-94d9-1bde67063390.png">
Is there anyone good solution, thank you

**Comment by mousebird** [comment]
Run it on a background thread.  WhirlyGlobe-Maply is very thread safe.

**Comment by lyp1992** [comment]
Any algorithm can substitute him this way, if I were in a background thread to run it, time is not optimized.

**Comment by mousebird** [comment]
What's your use case?  Is it taking too long to load data?  Data too large?  I really need more details to comment.

**Comment by mousebird** [comment]
Ah, lots of data indeed.

What I typically do in these cases is break it up spatially and load the data as needed.

Are you a support customer?  This is the kind of thing I'd discuss with a support customer in more detail.

**Comment by lyp1992** [comment]
How do I become your support customers?If I pay you to help me put the functional optimization, this how long will it take?

**Comment by mousebird** [comment]
Support is $950 (USD) per year.  I offer advice and bug fixes.

Contact me at contact@mousebirdconsulting.com and we can discuss it further.

**Comment by lyp1992** [comment]
If I need you to help me achieve a function, rather than just consulting, this how do you charge?

**Comment by mousebird** [comment]
This is a conversation to have over email.  contact@mousebirdconsulting.com
