### ISSUE TITLE
cannot select markers in 2.5 Android using globeControl

### ISSUE THREAD

**Issue by sirMuffles91** [mousebird/WhirlyGlobe#1117]
I have followed the marker select guide on the website but userDidSelect override in fragment is not being called. If I step through, the code is being run in GlobeController but never being overridden in my fragment.

I have set `globeControl.gestureDelegate = this;`
I have overridden userDidSelect in my fragment and set my marker `marker.selectable = true;`

But still does not seem to work. I had a look at the AndroidTutorialProject but that seems to be using a rather outdated version of WhirlyGlobe.

**Comment by saildronesteve** [comment]
Yes, those tutorials haven't been updated in a while.
I'm redoing the Android build and will take a look later this week.

**Comment by sirMuffles91** [comment]
Any possibility to get a brief overview on selecting markers in Android here for anyone who is struggling with this currently?

**Comment by mousebird** [comment]
Look for "userDidSelect" in the MaplyTestCase base class.
You need to provide fill out GlobeController.GestureDelegate or MapController.GestureDelegate and assign your object to the gestureDelegate for map or globe.
