### ISSUE TITLE
[iOS] I want to draw a special area border. Can you guide me?

### ISSUE THREAD

**Issue by LiuzhongweiHup** [mousebird/WhirlyGlobe#1118]
E.g 
![img_1500](https://user-images.githubusercontent.com/27271547/47200780-fbaaab00-d3a9-11e8-9c85-b7261e191b91.JPG)
I want to draw the border of this style, the solid line plus the dotted line, I hope you can help me.

**Comment by saildronesteve** [comment]
At this point I think you'd need to either make a one sided texture.  Or if that doesn't work shrink the polygon a little bit and do the dotted lines that way.

**Comment by LiuzhongweiHup** [comment]
I tried to separate the solid line from the dotted line, but I didn't find any way.
How do you narrow down the dotted area? I hope that you can guide me.
My code:
![snip20181022_1](https://user-images.githubusercontent.com/27271547/47280780-99041a00-d60a-11e8-93aa-32179ee1e4d3.png)
effect:
![img_1553](https://user-images.githubusercontent.com/27271547/47280849-f009ef00-d60a-11e8-8348-069cf10dffff.JPG)

**Comment by saildronesteve** [comment]
I think you'd have to shrink that object yourself.  I don't have any features to do it for you.

**Comment by mousebird** [comment]
I know of a user who does this every time the screen moves.  It's not a great solution, but it can be made to work.

**Comment by LiuzhongweiHup** [comment]
Thank you for your guidance, but this doesn't help me draw a special border. I found that the arguments of the proxy method that stopped moving are not an array, but the comment says it is an array of length 4. I feel weird.

I very much hope that you can add custom to draw special borders or lines, so that developers can draw their own lines or borders by simply passing in a small picture.
