### ISSUE TITLE
Plate Carrée Tile Server

### ISSUE THREAD

**Issue by fvlasie** [mousebird/WhirlyGlobe#1119]
Hello,

I am trying to make a tile server to serve EPSG:4326 tiles to WhirlyGlobe. I cannot find an example of a tile server that does not use mercator.

I need to display pole data so mercator will not work for me.

Does a single tile at zoom level zero for EPSG:4326 contain the entire globe or half of it?

TIA

**Comment by saildronesteve** [comment]
Tile 0,0,0 contains the whole world.
There are tiling schemes that divide it into two, but they're more complex to set up in WG-Maply.

As for the server side, I'm afraid I can't help there.

**Comment by mousebird** [comment]
On the WG-Maply side you just pass in the Plate Carrée coordinate system.  Otherwise it's the same.
I don't have a handy test case, I'm afraid.  It looks like the WMSTileSource uses it sometimes, but that's not what you're doing here.

**Comment by fvlasie** [comment]
Is the whole world top aligned in tile 0,0,0?
(Bottom aligned definitely isn't working.)

Thanks again!

**Comment by mousebird** [comment]
I always forget.  That's what the flipY property is for.  Try it one way and then the other.

**Comment by fvlasie** [comment]
Middle aligned seems to be promising.

Is it possible to display a plate carree layer over a mercator base layer?

Thanks!

**Comment by saildronesteve** [comment]
Sure.  Every layer is separate.

**Comment by fvlasie** [comment]
After some experimentation, unfortunately, the MaplyPlateCarree projection seems to not to be correct.

**Comment by fvlasie** [comment]
I have tried it with a test image.
The tile 0,0,0:

![worldgrid](https://user-images.githubusercontent.com/33334298/47530327-250e7f80-d85f-11e8-9967-a6195c0dd610.png)

**Comment by fvlasie** [comment]
Globe:
![screen shot 2018-10-25 at 3 17 03 pm](https://user-images.githubusercontent.com/33334298/47530358-3788b900-d85f-11e8-83ed-68e2794c7b27.jpg)
![screen shot 2018-10-25 at 3 17 18 pm](https://user-images.githubusercontent.com/33334298/47530370-3e173080-d85f-11e8-96e3-07dd5170bb90.jpg)
![screen shot 2018-10-25 at 3 17 30 pm](https://user-images.githubusercontent.com/33334298/47530375-42dbe480-d85f-11e8-9c89-9ce0f38eb481.jpg)

**Comment by fvlasie** [comment]
The top or the bottom should be cut off since an equirectangular world map is oblong.

**Comment by mousebird** [comment]
Plate Carrée as implemented in the toolkit is a simple unrolling of lat/lon that runs from -90 to +90.

**Comment by cpansprout** [comment]
It looks to me as though WhirlyGlobe is treating the tiles as equidistant cylindrical with the latitude of true scale at 45°; i.e., +proj=eqc +lat_ts=45.

For it to be plate carrée, latitude should run from -90° to 90°, but the longitude should run from -180° to 180°.  This is not what WhirlyGlobe is doing in these screen shots.

The same distance on the tile is being treated as an extent of 180° vertically but 360° horizontally.

**Comment by cpansprout** [comment]
I was wrong about 45° latitude of true scale. It is 60° of course.

For my use case, I have found it easier to program the tile server to reproject maps to +proj=eqc +lat_ts=60 rather than to figure out how to get WhirlyGlobe to support plate carrée tiles.
