### ISSUE TITLE
How to set an image background to a WhirlyGlobe?

### ISSUE THREAD

**Issue by Aimannab** [mousebird/WhirlyGlobe#1121]
Hi,
I'm trying to set an image of space/stars behind the WhirlyGlobe. I've used the following code in the GlobeFragment:
        globeSettings.clearColor = Color.TRANSPARENT;
Also, has set up the image in fragment_detail.xml, so when the background goes transparent, the image behind it is visible. But I cannot achieve that. What can I do to make the image visible behind the globe?
Here's my code: https://github.com/Aimannab/Capstone_Project/blob/master/app/src/main/java/com/example/android/capstone_project/GlobeFragment.java
Thanks,
Aiman

**Comment by mousebird** [comment]
That's what I've done in the past.  Try setting the clearColor to red to make sure it's working right.
But if that works, then TRANSPARENT will work as well.

**Comment by Aimannab** [comment]
Thanks for replying. I tried it out and using a red color works but not transparent. Is it even possible to set up a custom background image, behind the globe?

**Comment by mousebird** [comment]
Yes, I've done it in the past.
What that suggests is there is a view between the globe view and your view that needs to be set transparent as well.

There's also a way of putting actual starts in the view.  Take a look at the MaplyStartModelTestCase.

**Comment by Aimannab** [comment]
Can you please link me to MaplyStartModelTestCase?

**Comment by mousebird** [comment]
It's in the AutoTester app in the github repo.
