### ISSUE TITLE
Whether the IOS version supports WKT format

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1123]
Dear developers, I would like to ask whether the IOS version supports WKT format.

**Comment by songyuyang0918** [comment]
The appended drawings:

**Comment by songyuyang0918** [comment]
<img width="906" alt="2018-10-25 5 50 56" src="https://user-images.githubusercontent.com/15685672/47492130-e2f53600-d87e-11e8-820f-a5c60bda596d.png">

**Comment by songyuyang0918** [comment]
<img width="906" alt="2018-10-25 5 50 56" src="https://user-images.githubusercontent.com/15685672/47492169-f6080600-d87e-11e8-90df-b37b81dea111.png">

**Comment by mousebird** [comment]
No WKT support, I'm afraid.
