### ISSUE TITLE
I want to synchronize the changes between the two maps

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1124]
Dear developers,
I want to add a left and a right map to a view.
The map on the right moves with the map on the left, zooming in and zooming in.
Any ideas?
Thank you very much!

**Comment by songyuyang0918** [comment]
I use the notification mechanism to get the map and height of the left map, and then use the setPosition method to send it to the right map to realize linkage. I hope you have a better method.
Send you an effect video.

[Calm 2018-10-10 18.16.52.mp4.zip](https://github.com/mousebird/WhirlyGlobe/files/2514367/Calm.2018-10-10.18.16.52.mp4.zip)

**Comment by mousebird** [comment]
On iOS there's a WhirlyGlobeViewControllerDelegate that has didStartMoving and stopMoving calls.

**Comment by songyuyang0918** [comment]
Dear developer
I used the start and end method you mentioned
The movement is obtained through the agent and transmitted to the main controller for tracking.
There is delay in the linkage of cashback map A and map b. is there any better method?
thank you
