### ISSUE TITLE
[Android] Cant set cluster groups

### ISSUE THREAD

**Issue by Tourmen** [mousebird/WhirlyGlobe#1126]
Hi team.
I set up next code:
```
globeControl.addClusterGenerator(new BasicClusterGenerator(new int[]{Color.argb(165, 255, 255, 0)}, 1, new Point2d(64, 64), baseControl, baseControl.getActivity()));
markerInfo.setLayoutImportance(1.f);
markerInfo.setClusterGroup(1);
```
and then added some markers on a map.

And I got crashes(see attached file). Seems like there is an ability to use only default cluster group "0". Other numbers(tried "1", "2") lead to crashes.

Seems like this feature that allows to work with several clusters is needed to be fixed. 
Thank you.

[wg_clustering_crashes.txt](https://github.com/mousebird/WhirlyGlobe/files/2558016/wg_clustering_crashes.txt)

**Comment by mousebird** [comment]
This code worked for me in the Cluster test case.  I got yellow clusters.

**Comment by Tourmen** [comment]
Works fine on the latest sources /develop branch.
