### ISSUE TITLE
[iOS][Android] Ability to group markers by layers

### ISSUE THREAD

**Issue by Tourmen** [mousebird/WhirlyGlobe#1127]
Hi team.
Description:
I add some Screen Markers on 1st QuadPagingLayer and then more markers on 2nd layer. 
Then if I zooming in/out, all these markers from 1st and 2nd layer are grouping. And even more, they are grouping together. So, the WG SDK treat them as markers on one layer. (Like the default clustering feature when layoutImprortance = 1.0f ).
It would be nice to have an ability to get default grouping by layer independently. Is it possible?
Thank you.

**Comment by mousebird** [comment]
Can you use the cluster number to do this?
Layers don't really existing inside the toolkit as a grouping mechanism.  We don't know what data is coming from which QuadPagingLayer.

**Comment by Tourmen** [comment]
iOS:
Clustering works in general, but it needs complex development to achieve our needs. I assume we must investigate and rewrite the default cluster generator and some related stuff to pass needed data, icons and coordinates.

Android:
Only custom group 0 works. Other numbers lead to crashes. Also performance of the group 0 is very poor. I cant use the feature as is.  And the same efforts to implement after issues are fixed.

PS: Ive created tickets on the github mentioned above.

**Comment by mousebird** [comment]
For iOS, I'd be interested in knowing what else you're trying to do.  

For Android, I'm looking into the performance problem.  I've verified it in my test case and am closing in on the fix.

**Comment by mousebird** [comment]
I think you folks resolved this, or at least learned to make the current functionality work.  If you'd like to discuss it further, email me.
