### ISSUE TITLE
WebGL and Webassembly support

### ISSUE THREAD

**Issue by jcimoch** [mousebird/WhirlyGlobe#1128]
Are there any plans to complie this library to WA and WebGL and support web as 3rd platform? As most of the core is c++ I would assume that it should be possible without enormous amount of work.

**Comment by mousebird** [comment]
I've experimented with it.  It's possible, but it would be an enormous amount of work.
The C++ core has to be hooked up to Javascript the same way we did with ObjC/Swift and Java.

Moreover, I don't think the toolkit would be accepted by the Javascript community in that form.  I think it needs to be rebuilt from the ground up in Javascript.

That might happen if someone pays for it, but it would not be cheap.

**Comment by mousebird** [comment]
Still an interesting idea, but outside the scope of the Issue tracker.
