### ISSUE TITLE
Xcode10 Can't use WhirlyGlobeMaplyComponent framework on IPHONE6s

### ISSUE THREAD

**Issue by showzh20** [mousebird/WhirlyGlobe#1134]
This is error:
dyld: Library not loaded: @rpath/WhirlyGlobeMaplyComponent.framework/WhirlyGlobeMaplyComponent
  Referenced from: /var/containers/Bundle/Application/AB79F929-D783-4E6B-AB08-CEBD68DCF4DB/HelloEarth.app/HelloEarth
  Reason: image not found
Message from debugger: Terminated due to signal 6

**Comment by mousebird** [comment]
You need to included the library as an embedded binary.
The documentation is out of date.  We need to add that.
