### ISSUE TITLE
[iOS] Blinking map image for multiple maps that overlap

### ISSUE THREAD

**Issue by Tourmen** [mousebird/WhirlyGlobe#1135]
When I add several mbtiles map and zoom in/out (see attached video) they start blinking.

Investigation has shown that this behavior can be observed when drawing priority of charts are too close to each other.
"too close" can be considered as difference between drawing priorities of charts is less that 5.

Chart A with lower priority can sometimes be consistently drawn "above" chart B with higher priority,
this can be seen when chart A has tiles on deeper zoom levels than chart B, on those deep zoom levels this behavior is manifested.

Video evidence:
https://drive.google.com/file/d/1-9G6XjeXQ3dilSNUtqCKMkNW7hUQMExh/view?usp=sharing

**Comment by mousebird** [comment]
Right, give the charts a wider range of draw priorities.  The toolkit uses several draw priorities beyond the one you give it.  This is even more common with the newer Loader/Sampler.
