### ISSUE TITLE
[Android] Issue with offset for labels

### ISSUE THREAD

**Issue by Tourmen** [mousebird/WhirlyGlobe#1137]
When I add labels, with positive offset by Y, it is always ok.
When offset is negative - labels does not appear at all often.

```
val label = ScreenLabel()
label.offset = Point2d(0.0, -markerIconSize * 1.05)
```

I guess it might be related to importance. Some of them are Float.MAX_VALUE and some of them are not. So, for some values it is not rendered correctly.

**Comment by mousebird** [comment]
That suggests it's a problem in the layout manager.
