### ISSUE TITLE
IOS The map is not smooth

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1138]
Dear developers, 
I set the project to release for presentation,
I found that when the map moved and zoomed, there would be a white block refresh. The whole process was not smooth.
Can it be like an apple native map without white transitions?

[1545214200172840.mp4.zip](https://github.com/mousebird/WhirlyGlobe/files/2694367/1545214200172840.mp4.zip)
Thanks!

**Comment by songyuyang0918** [comment]
For your convenience,
I convert video to GIF

![calm 2018-12-12 18 21 32 2018-12-19 18_22_01](https://user-images.githubusercontent.com/15685672/50214340-0211cf00-03bb-11e9-975b-4b0885b47c23.gif)

**Comment by mousebird** [comment]
Yes, you can tune this to a certain degree.  Use a multi-level loading mode.
This is also much improved with the new Loading/Sampling architecture on iOS in 2.6.

**Comment by songyuyang0918** [comment]
Hello! I tried to use multi-level loading mode.
Own data in single - level loading is no problem.
Once multilevel loading is used, the (imageForTile:) returns an identity that is always 0?
How can I adjust it?
<img width="614" alt="2019-02-18 4 51 57" src="https://user-images.githubusercontent.com/15685672/52938820-9ab5d280-339d-11e9-9c73-ed38c561630e.png">

**Comment by songyuyang0918** [comment]
My data, starting at level 4

**Comment by mousebird** [comment]
Did you specify a minZoom and maxZoom when setting up the loader?
That minZoom should be your lowest loadable level.
