### ISSUE TITLE
[Android] Location offset to the North 

### ISSUE THREAD

**Issue by JtxGit** [mousebird/WhirlyGlobe#1144]
I've been trying to compile the latest source (2.6.1). After lots of experimentation, I finally managed to build the aar file. 

Using this file in my app, causes some strange location behaviour when zooming in a lot. 
The current location marker is shown too much north and the map window centre is too much south... The real location is somewhere between those 2 positions. 

With 2.5 it always works correctly. 

With 2.6.1 the location marker is placed several metres to the North of the real location. 

When zoomed out it looks OK. 

Perhaps this is caused by the way I built the library, but I have no way of checking it, since I have unfortunately never managed to build 2.5 myself ...

**Comment by JtxGit** [comment]
OK, some more clarification. I am quite far north (60 degrees).
Looking at the behaviour, it actually seems like the map tiles are placed a few metres to the north  of where they should be and the location marker is placed another few metres further north.

**Comment by mousebird** [comment]
The AAR is just a zip file.  Looking inside it I can see a armv7a and arm64 versions.  Presumably it's using the latter.
What AAR were you using for 2.5?

**Comment by JtxGit** [comment]
I am using whatever is included in the app when Android Studio builds the app with the following dependency set in the app build.gradle file:
implementation 'com.mousebirdconsulting.maply:Android:2.5'

I have never manually downloaded the aar file myself.

**Comment by JtxGit** [comment]
I would really appreciate it if someone can point me to a download link for a built version of the aar file for 2.6.1. That way I can check if my building process caused this behaviour or not.

**Comment by mousebird** [comment]
I'm working on replacing the official builds on the site.  Next couple of days, I think.

**Comment by JtxGit** [comment]
Just for my understanding, are you planning to release an official build (android) for 2.6.x, or will it only be when 3.0 is done?

**Comment by mousebird** [comment]
I'm planning to release a 2.6 AAR for Android.  Just really busy with the 3.0 port.  Soon, I hope.  I have to test it, is the issue.

**Comment by JtxGit** [comment]
That's great! Thanks for the information.

**Comment by mousebird** [comment]
I've put a 2.6 AAR up on the builds page.
I haven't specifically addressed your problem, as I haven't seen it.  But let me know if it's still there with this build.

**Comment by NasH5169** [comment]
I'm not an expert but the new aar 2.6 does not contain armeabi, there is armeabi-v7a but not armeabi.

It could make so trouble with I release something on the store?

**Comment by mousebird** [comment]
Unfortunately armeabi was phased out in ndk17.

I am not sure how to compile against older NDKs using this version of Android Studio.  Moreover, if I link against ndk16 will that still work with modern devices?  Or do I need two versions of the AAR?

This is tricky.

**Comment by NasH5169** [comment]
I'll take a look at https://developer.android.com/ndk/guides/abis#armeabi

For now i'm restricting my app on:

```
ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"
        }
```

No problem with theses 3 arch on the store. I will have to check if armeabi can be removed.

**Comment by JtxGit** [comment]
For me this aar (2.6.2) still gives me the same "location offset" issue as my own built aar (2.6.1) did.
Looking at the contents compared to 2.5:
![screenshot from 2019-02-20 21-16-37](https://user-images.githubusercontent.com/46416002/53123058-7e11ca00-3558-11e9-93b6-86270f19fb0f.png)

**Comment by mousebird** [comment]
Under jni would be the important one.

**Comment by JtxGit** [comment]
JNI
![screenshot from 2019-02-20 21-18-12](https://user-images.githubusercontent.com/46416002/53123674-df866880-3559-11e9-86ee-272019b44b71.png)

**Comment by mousebird** [comment]
That's what I'd expect.  I'm building the default architectures with the latest and they dropped mips as well.

So the problem might well be with armeabi.  Perhaps that was the version being picked up.

**Comment by JtxGit** [comment]
I have tested it on all my android devices, and they all behave like this... Unfortunately I do not know how to check what architecture file is really used by the devices...
To clarify the behaviour:
![screenshot_20190220-220029](https://user-images.githubusercontent.com/46416002/53124701-50c71b00-355c-11e9-9040-0fd5671e704d.png)

**Comment by mousebird** [comment]
Thinking about this further I wonder if it's an image or a location problem.
Can you try putting a marker right at that location and see how it compares?

**Comment by JtxGit** [comment]
The blue dot is a screen marker placed at the current location.

**Comment by mousebird** [comment]
I see.  That I might be able to duplicate.

**Comment by NasH5169** [comment]
Just an update about armeabi.

No issue with removing armeabi because there is no armeabi support since Android 4.4+

**Comment by JtxGit** [comment]
Just some more clarification to assist in recreating / duplicating / replicating this issue.

The "direction ring" (for a lack of a better word), is just a png that is placed in the centre of the view window.
The map is then centred on the current (GPS) location using "mapControl.setPositionGeo...".
The blue dot is a screen marker placed at the current (GPS) location using "you.loc = Point2d.FromDegrees(lon, lat);"

When using aar 2.5.0, these three coincide (the centre of the png, the map location and the screen marker)
When only changing the aar to 2.6.2 (and nothing else), these three do not coincide any more. The png is still in the centre of the view window, but the map tiles are placed some metres too much to the north, and the blue dot screen marker is placed some more metres further north...
My estimate is that it is in the range of 5 to 6 metres we are talking about.

I really hope someone can replicate this...

**Comment by JtxGit** [comment]
After a lot of testing and trying, without success, I decided to create a new simple app. The (old) app grew out of many trials and code tests, so especially the view lay-outs ended up a little convoluted, with for example several layers and a permanently peeking bottom sheet. Since this might contribute to this issue, I wanted a simple and clean test app.

So creating 2 copies of this new app, and running them side-by-side. One using the 2.6.2 aar and the other the old 2.5.0 aar, this is what I get:
![20190321_123102](https://user-images.githubusercontent.com/46416002/54778713-b5d26700-4c15-11e9-8bd5-7059bf602ede.jpg)

So this confirms that the offset is still there between the 2 aar versions. Now my main question is: which one shows the correct position?
From the evidence it looks like the map tiles are placed in the wrong North-South position by a few (5 to 6) metres in one of the versions.
With this "cleaner" android view layout, at least the map centring correctly lines up the location market position on the map with my "direction ring" cursor. 

Any ideas?

**Comment by JtxGit** [comment]
Is this fixed in 3.0?

**Comment by mousebird** [comment]
I haven't explicitly tested that.  Would be a good test case for 3.0, though.

**Comment by JtxGit** [comment]
Anything I can do?

**Comment by JtxGit** [comment]
Any news on this issue?
(I'm getting a bit desperate...)

**Comment by mousebird** [comment]
I'm sorry, I've been very busy of late.
Support customers take priority and there's been a lot related to ios13.

I don't know when I'll get to this.

**Comment by JtxGit** [comment]
I understand. Thanks for the feedback.

I would really appreciate if you can point me to the place (file or files) where the placement of the tiles are calculated. Then I could try to see what is different between 2.5 and 2.6.1.

**Comment by mousebird** [comment]
The only change I can think of was bumping the shaders up to high precision in there somewhere.
Otherwise, this part of 2.5 on Android didn't change all that much.

I still suspect the issue was floating point precision between the various ABIs.  Particularly which one was being used on which architecture.  But I honestly don't know.  

This is probably a multi-day exploration to set up a test and track it down and I haven't had the time after clients and support customers.

**Comment by JtxGit** [comment]
I must say that I am amazed that nobody else in the Android camp has an issue with this... Is it really possible  that nobody else wants / needs to display their position accurately on the map?

**Comment by mousebird** [comment]
I'm aware of a few users who depend on this sort of precision, but they're using vector tiles.

**Comment by JtxGit** [comment]
So, does this mean that vector tiles are placed in a different way?

**Comment by mousebird** [comment]
Each individual point in a vector tile is projected into display space.  So, in theory, they should be more accurate.  It depends on their level.  Everything is scaled into a 2D integer space of a defined size and then scaled back out when read.

**Comment by JtxGit** [comment]
Is there a public source of vector tiles available to test with?

**Comment by mousebird** [comment]
You can get some from OpenMapTiles, I believe.
There's no default style on Android to render them, though.  You will have to put a number of things together to get them working in 2.6.

**Comment by JtxGit** [comment]
OK, so I've been trying to get vector tiles to work, but so far with only limited success. Unfortunately none of the map sources that I need in my app have vector sources, so I really still need the raster tiles to be placed accurately.

Since it is now already so close to the end of the year, I will just skip this 2.6.x version and hope it is fixed in 3.0.

By the way, what is the earliest I can have a test version of 3.0 to test this in my app?

**Comment by mousebird** [comment]
3.0 will be made public to everyone on January 1st.

**Comment by JtxGit** [comment]
Perfect. As a compiled .aar file as well?

**Comment by mousebird** [comment]
Probably, yes.

**Comment by JtxGit** [comment]
Really looking forward to test this new version... Where should I look for it?

**Comment by JtxGit** [comment]
I must be looking in all the wrong places... Please let me know where it was / will be made public.

**Comment by mousebird** [comment]
https://github.com/mousebird/WhirlyGlobe-3

I haven't specifically addressed your issue, so I just don't know if it's fixed in 3.0.

**Comment by JtxGit** [comment]
Thanks for the information. I will test it now.

**Comment by JtxGit** [comment]
I could not find any pre-built aar file under that link. I finally managed to build the aar file (hopefully correctly), but it seems that the loading logic for a raster tile layer changed quite dramatically. Can you please point me to a brief description of the logic or briefly explain it to me? Thanks in advance.

**Comment by mousebird** [comment]
Yes, the loading logic has changed and the documentation for Android hasn't caught up.  But you can find examples in the AutoTester like the CartoLightTestCase.kt

**Comment by JtxGit** [comment]
Thanks for the pointer.
I've been trying to get the AutoTester app to run, but without any success so far... It builds and installs, but as soon as I try to run a test case, it crashes with this error:

`2020-01-03 22:55:48.406 2866-3551/com.mousebirdconsulting.autotester A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 3551 (GLThread 132626), pid 2866 (ting.autotester)`

**Comment by JtxGit** [comment]
Still no success... Whatever I try, it just ends up crashing.
In 2.5 the loading logic was quite straight forward:
```
define a RemoteTileSource
define a QuadImageTileLayer
add the layer with globeControl.addLayer
```

In 3.0 it is not obvious to me (despite looking at CartoLightTestCase.kt)
```
define RemoteTileInfoNew
define SamplingParams
define QuadImageLoader
```
but I don't see it ever being added to the globe...

I must be missing something obvious?

I would really appreciate it if someone could just briefly explain the new logic. Especially how this new loader should be used by the GlobeController.

**Comment by mousebird** [comment]
I'll check the AutoTester app on Monday.  As for the setup, try the CartoLightTestCase.

**Comment by JtxGit** [comment]
Some progress...
I can load local vectors as in VectorsTestCase.java
(and I get white country outlines on a black background)
but as soon as I try to load tiles (even local mbtiles as in  GeographyClass.java), it crashes with this error:
`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 25496 (GLThread 2997), pid 25466 (test.wg3test)`

Is there a pre-built aar file that I can try? 
Just in case it is something due to the way my system builds this.

**Comment by JtxGit** [comment]
As it is Tuesday, I was wondering if there is any news on the Android AutoTester app?

And of course, if there is a pre-built aar file available for download?

**Comment by mousebird** [comment]
Looks like there was an error introduced from the iOS side.  I've sorted it out for Android.  I'm now seeing the test cases working again on develop.

**Comment by JtxGit** [comment]
Thanks! I will try again

**Comment by JtxGit** [comment]
Finally managed to get my testing app running. The first result seems very encouraging. It seems that 3.0 places the tiles the same as 2.5. I will continue with some more testing to get proper confirmation.

**Comment by mousebird** [comment]
I have no earthly idea why that would be different.  But I'll take good news.
