### ISSUE TITLE
[iOS] Memory cycle

### ISSUE THREAD

**Issue by BerlinWheatley** [mousebird/WhirlyGlobe#1145]
We have a ViewController which is a subclass of MaplyViewController, which does not deinit when it should. Xcode says there is a memory cycle inside WhirlyGlobe:

![bildschirmfoto_2019-01-25_um_17 04 14](https://user-images.githubusercontent.com/45199427/51829180-529b1700-22ed-11e9-8d90-748d8ff942d0.png)

Our podfile is loading version 2.5 of WhirlyGlobe: `pod 'WhirlyGlobe', :http => 'https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/WhirlyGlobe-Maply_Distribution_2_5.zip'`

**Comment by mousebird** [comment]
2.6.2 is the latest.  You can reference the podspec directly from that tag.

You can try explicitly calling teardown in your shutdown code.
Also be careful to call the various super. life cycle methods.

**Comment by legion-zver** [comment]
@mousebird Could you please give a link to the most recent version of the distribution (on the Amazon only 2.5)? Or need to build from source manually?

**Comment by mousebird** [comment]
I'm afraid you'll need to build from source.  You can use the Cocoapod distribution if that's easier.
Apple has sufficiently changed the binary framework format that I can't get it working again.
