### ISSUE TITLE
Error submodule iOS

### ISSUE THREAD

**Issue by chaotzu** [mousebird/WhirlyGlobe#1146]
stdp:openstreetfighters jdiazm$ git submodule add https://github.com/mousebird/WhirlyGlobe.git libs/WhirlyGlobeMaply
Cloning into '/Users/jdiazm/Documents/Xcode/openstreetfighters/libs/WhirlyGlobeMaply'...
remote: Enumerating objects: 265, done.
remote: Counting objects: 100% (265/265), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 58981 (delta 129), reused 196 (delta 122), pack-reused 58716
Receiving objects: 100% (58981/58981), 489.61 MiB | 2.37 MiB/s, done.
Resolving deltas: 100% (41654/41654), done.
git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
Unable to checkout submodule 'libs/WhirlyGlobeMaply'

**Comment by mousebird** [comment]
You might need to install git-lfs for the larger objects.

**Comment by chaotzu** [comment]
thanks
