### ISSUE TITLE
[[EAGLContext alloc] initWithAPI:] return nil  ,the version string Transmitted successfully.

### ISSUE THREAD

**Issue by iSuAbner** [mousebird/WhirlyGlobe#1147]
The scenario is that I'm constantly trying to include the VC of the earth through the dealloc navigation bar and pushing it into the newly created VC that contains the earth
![1550136390180](https://user-images.githubusercontent.com/17755274/52776963-bb201d00-307d-11e9-9494-7cb2082af570.jpg)

**Comment by mousebird** [comment]
I'm not sure I understand the question.

**Comment by iSuAbner** [comment]
sorry , what i said was too vague . When we try to release a ViewController that contains a WhirlyGlobeViewController .what additional Settings do we need for WhirlyGlobeViewController . for example ,the WhirlyGlobeViewController is not yet rendered .

**Comment by iSuAbner** [comment]
@mousebird

**Comment by mousebird** [comment]
So you're tearing down the view controller before it's been properly set up?
That should be fine, I'd think.  Most of the setup is done when the view is instantiated.

You could try touching the .view to at least fault in the WhirlyGlobeViewController so it completes its setup.
