### ISSUE TITLE
findHeightToViewBounds returns different results for the same inputs

### ISSUE THREAD

**Issue by W74Wolf** [mousebird/WhirlyGlobe#1148]
Greetings 
I am using version 2.5
it seems there is a bug in this functionality, i always feed it the same input i checked but i get at least 3 different results for height the maximum (4.0) the minimum (1.0e-5) the one that i need to zoom on the box.

Or is there something i missed like setting some constraints for the map?

**Comment by mousebird** [comment]
Is this the 2D map?

**Comment by W74Wolf** [comment]
Sorry for the late reply yes it is the 2D map.

**Comment by mousebird** [comment]
The AutoTester test case works, so I'm not sure what to suggest.

Can you duplicate the problem in the AutoTester?

**Comment by W74Wolf** [comment]
Eventually i found out that the function works as intended but there is a threading problem i was unable to solve in my application which results in these different results because it is sometimes running before the map is loaded

**Comment by mousebird** [comment]
Threading or timing?
If it's timing, there's an addPostSurfaceRunnable() method you can use to have your logic run right after things are initialized.
