### ISSUE TITLE
Display Shapefiles in Android

### ISSUE THREAD

**Issue by Rskut** [mousebird/WhirlyGlobe#1149]
Hello,

could you tell me what I'm missing here? 
I would like to display Shapefiles but the readFromFile method returns false.

I already posted this question on stackoverflow:
https://stackoverflow.com/questions/54883225/display-shapefiles-with-whirlyglobe

**Comment by mousebird** [comment]
You need the fromShapeFile() method.  readFromFile() only parses a binary vector file format.
