### ISSUE TITLE
[ iOS] The globe isn't smooth in WhirlyGlobe v.2.6.1

### ISSUE THREAD

**Issue by bobkexit** [mousebird/WhirlyGlobe#1150]
Hi, I tried example of remote layer from tutorial and found that globe is not smooth. 
<img width="584" alt="2019-03-05 20 35 32" src="https://user-images.githubusercontent.com/5675375/53825359-3131e880-3f87-11e9-86c1-2b356c8958b3.png">
And I've got the same result on the real device. 
If set minZoom to 1, then result looks very odd:
<img width="584" alt="2019-03-05 20 45 22" src="https://user-images.githubusercontent.com/5675375/53825597-b3221180-3f87-11e9-9389-cb05c3d34ded.png">

Here is the code what I used:
```
        theViewC = WhirlyGlobeViewController()
        self.view.addSubview(theViewC!.view)
        theViewC!.view.frame = self.view.bounds
        addChild(theViewC!)
        
        let globeViewC = theViewC as? WhirlyGlobeViewController
        let mapViewC = theViewC as? MaplyViewController
        
        // we want a black background for a globe, a white background for a map.
        theViewC!.clearColor = (globeViewC != nil) ? UIColor.black : UIColor.white
        
        // and thirty fps if we can get it ­ change this to 3 if you find your app is struggling
        theViewC!.frameInterval = 2
        
        // add the capability to use the local tiles or remote tiles
        let useLocalTiles = false
        
        // we'll need this layer in a second
        let layer: MaplyQuadImageTilesLayer
        
        if useLocalTiles {
            guard let tileSource = MaplyMBTileSource(mbTiles: "geography-class_medres") else {
                // can't load local tile set
            }
            layer = MaplyQuadImageTilesLayer(tileSource: tileSource)!
        }
        else {
            // Because this is a remote tile set, we'll want a cache directory
            let baseCacheDir = NSSearchPathForDirectoriesInDomains(.cachesDirectory, .userDomainMask, true)[0]
            let tilesCacheDir = "\(baseCacheDir)/stamentiles/"
            let maxZoom = Int32(18)
            
            // Stamen Terrain Tiles, courtesy of Stamen Design under the Creative Commons Attribution License.
            // Data by OpenStreetMap under the Open Data Commons Open Database License.
            guard let tileSource = MaplyRemoteTileSource(
                baseURL: "http://tile.stamen.com/terrain/",
                ext: "png",
                minZoom: 0,
                maxZoom: maxZoom) else {
                    // can't create remote tile source
                    return
            }
            tileSource.cacheDir = tilesCacheDir
            layer = MaplyQuadImageTilesLayer(tileSource: tileSource)!
        }
        
        layer.handleEdges = (globeViewC != nil)
        layer.coverPoles = (globeViewC != nil)
        layer.requireElev = false
        layer.waitLoad = false
        layer.drawPriority = 0
        layer.singleLevelLoading = false
       
        theViewC!.add(layer)

        // start up over Madrid, center of the old-world
        if let globeViewC = globeViewC {
            globeViewC.height = 1.0
            globeViewC.keepNorthUp = true
            globeViewC.animate(toPosition: MaplyCoordinateMakeWithDegrees(-3.6704803, 40.5023056), time: 1.0)
        }
        else if let mapViewC = mapViewC {
            mapViewC.height = 1.0
            mapViewC.animate(toPosition: MaplyCoordinateMakeWithDegrees(-3.6704803, 40.5023056), time: 1.0)
        }
```

WhirlyGlobe v.2.6.1

**Comment by mousebird** [comment]
The globe will get smoother as it loads more data with that example.
Starting at level 1 will result in gaps, it's true.  You need to let it start at level 0.

**Comment by bobkexit** [comment]
Hi, thanks for answer. Is it possible to enforce app load more data and if it does then how?

**Comment by mousebird** [comment]
It should load more data on its own unless the tiles are missing.

You can adjust the amount of sampling for the globe if that's really the problem.  From experience, I would say continue with your development, try it on a real device, and then come back to the sampling problem.

**Comment by bobkexit** [comment]
Same problem on the real device. But in the WhirlyGlobe v2.4 no such problem. The glob is smooth:

![IMG_5CAC5D4F487C-1](https://user-images.githubusercontent.com/5675375/54446697-9ab8b080-4758-11e9-824e-86f4b02eca5e.jpeg)

**Comment by mousebird** [comment]
Can you duplicate that with the AutoTester app?
Specifically, try using the Stamen example.

**Comment by bobkexit** [comment]
Didn't find test for Stamen in AutoTester

![image](https://user-images.githubusercontent.com/5675375/54681094-973c7500-4b1c-11e9-92f2-32d23c62ff75.png)

**Comment by mousebird** [comment]
The Stamen example is the first one.  It uses the Stamen Watercolor basemap.

**Comment by bobkexit** [comment]
Hi, thank you! My problem solved. Here is the autotester result, the globe looks nice and smooth:
![image](https://user-images.githubusercontent.com/5675375/54737036-0ec2e080-4bbf-11e9-996a-38cfb3146619.png)

I found that setup globe in autotester not like in tutorials, so I used code from autotester and it solved my problem. Here is what I've got:
![image](https://user-images.githubusercontent.com/5675375/54737114-71b47780-4bbf-11e9-8880-781daefc478f.png)

I didn't find any mentions about `MaplyRemoteTileInfoNew`, `MaplySamplingParams` and `MaplyQuadImageLoader` in document reference. The WhirlyGlobe is the great and powerful SDK, but unfortunately it is quite hard to use, because it's not well documented.

**Comment by mousebird** [comment]
Right, I pointed you to the new sampler/loader objects because I knew they would solve some of the problems you were seeing.

MaplyRemoteTileInfoNew, MaplySamplingParams and MaplyQuadImageLoader are new versions of the older quad image loading functionality.  I haven't had time to update the tutorials.
