### ISSUE TITLE
[Android] LinearTextureBuilder not work, can't build a dashed pattern

### ISSUE THREAD

**Issue by HuWenHao92** [mousebird/WhirlyGlobe#1152]
I have build app AutoTesterAndroid,And I've found WideVectorsTestCase.java.But it doesn't create a dash line when I run this app. Method "makeImage" is wrong?

**Comment by mousebird** [comment]
The first thing to do is to look at the image it is producing and see that it makes sense.
If it does, make sure that image is being attached to the vector feature.

If the example appears to work, then it should be possible.

**Comment by HuWenHao92** [comment]
the example doesn't work,I’ve found bitmap create successful.And then attached to the vector feature.But dash line doesn’t appear.I did not modify the example app code

**Comment by HuWenHao92** [comment]
I've finish this task . Just make a dashline bitmap replace LinearTextureBuilder#makeImage method . And then attached to the vector feature . Thanks a lot.
