### ISSUE TITLE
[iOS] [WhirlyGlobe v2.6.1] WhirlyGlobeComponentTester do not build

### ISSUE THREAD

**Issue by bobkexit** [mousebird/WhirlyGlobe#1153]
I cloned master branch. According to the tutorial docs (http://mousebird.github.io/WhirlyGlobe/tutorial/ios/component_tester.html) I can find WhirlyGlobeComponentTester in ` libs/WhirlyGlobeMaply/WhirlyGlobeSrc/WhirlyGlobeComponentTester `. But there is no such path. I found WhirlyGlobeComponentTester in `ios/apps/WhirlyGlobeComponentTester`. I tried to build project, but it failed. First I've got this error:
<img width="2105" alt="Снимок экрана 2019-03-20 в 14 06 16" src="https://user-images.githubusercontent.com/5675375/54681584-cbfcfc00-4b1d-11e9-98bf-05c4c295e456.png">
After fix, I've got this error:
<img width="2105" alt="Снимок экрана 2019-03-20 в 14 05 27" src="https://user-images.githubusercontent.com/5675375/54681625-e3d48000-4b1d-11e9-8f7a-0a0174b13736.png">
I commented out this line and failed again with new error:
<img width="1666" alt="Снимок экрана 2019-03-20 в 14 04 45" src="https://user-images.githubusercontent.com/5675375/54681686-0d8da700-4b1e-11e9-83ee-dc32b85eefd5.png">

**Comment by mousebird** [comment]
Unfortunately, the tutorials are out of date.
If you bring up the AutoTester app it should provide a complete example of linking in the toolkit.  It is up to date.
