### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by gelonggld** [mousebird/WhirlyGlobe#1154]
I followed the **android** tutorial **Your First Globe or Map** and encountered the following problem - 

`java.lang.IllegalAccessError: Illegal class access: 'com.xy.test3d.GlobalFragment' attempting to access 'com.mousebird.maply.Layer' ( Declaration of 'com.xy.test3d.GlobalFragment' appears in /data/app/com.xy.test3d-K6OpbGuxSlI6gbiBwkIr4g==/split_lib_slice_3_apk.apk).`
The difference between what I can find and the tutorial is that I am using kotlin, and everything else is the same.
This is my code

**activity-main.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <fragment
        android:id="@+id/fragment"
        android:name="com.xy.test3d.GlobalFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</android.support.constraint.ConstraintLayout>
```

**GlobalFragment**

```
class GlobalFragment : GlobeMapFragment() {


    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {
        // Inflate the layout for this fragment
        super.onCreateView(inflater, container, savedInstanceState)
        return baseControl.contentView
    }


    override fun chooseDisplayType() = MapDisplayType.Globe


    override fun controlHasStarted() {
        val cacheDirName = "stamen_watercolor"
        val cacheDir = File(activity!!.cacheDir,cacheDirName)
        cacheDir.mkdir()
        val remoteTileSource = RemoteTileSource(RemoteTileInfo("http://tile.stamen.com/watercolor/", "png", 0, 18))
        remoteTileSource.setCacheDir(cacheDir)
        val coordSystem = SphericalMercatorCoordSystem()

        val baseLayer = QuadImageTileLayer(globeControl,coordSystem,remoteTileSource)
        baseLayer.imageDepth = 1
        baseLayer.setSingleLevelLoading(false)
        baseLayer.setUseTargetZoomLevel(false)
        baseLayer.setCoverPoles(true)
        baseLayer.setHandleEdges(true)

        globeControl.addLayer(baseLayer)
        globeControl.animatePositionGeo(-3.6704803, 40.5023056, 5.0, 1.0)
        mapControl.setAllowRotateGesture(true)

    }





}
```

**build.gradle (module: app)**

```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.xy.test3d"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'

    //3d global
    implementation('com.mousebirdconsulting.maply:Android:2.5')
//            {
//        exclude group: 'com.android.support', module: 'support-v4'
//    }



    implementation 'com.android.support:support-v4:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```

Please help me find out what went wrong, thank you

**Comment by mousebird** [comment]
I don't think I've see this one before.
Can you compile and run the AutoTester app?  That should do essentially the same thing.

**Comment by JtxGit** [comment]
I'm still very much a WhirlyGlobe novice, learning mostly from trial and error... I know even less about Kotlin, but I've seen errors when not renaming all "map" to "globe", so perhaps it might make a difference if you change:
"mapControl.setAllowRotateGesture(true)"
to
"globeControl.setAllowRotateGesture(true)"
in the last line of "GlobalFragment"

**Comment by gelonggld** [comment]
I found the problem because **com.mousebird.maply.Layer** is not public, so kotlin is wrong when adding, to change to this
```
public class KotlinFix {

    public static void addLayer(GlobeController globeController, QuadImageTileLayer layer){
        globeController.addLayer(layer);
    }

}
```
Then change the
 `globeControl.addLayer(baseLayer)`
 to 
`KotlinFix.addLayer(globeControl,baseLayer)`

**Comment by mousebird** [comment]
What version of the toolkit are you using?

I see the Layer is public in the latest version and the addLayer method in the BaseController is also public.

Maybe this is an odd interaction with Kotlin.

**Comment by wliadmin** [comment]
I have face same this issue need to required fix on next release.
By the way Thanks @gelonggld

**Comment by gelonggld** [comment]
This is my build 
`implementation ('com.mousebirdconsulting.maply:Android:2.5')`

**Comment by mousebird** [comment]
Is that from the master branch?

**Comment by beersheba** [comment]
Having the same issue w/ Kotlin.
Still reproduced on 2.6.2.
Isn't it resolved yet?

**Comment by mousebird** [comment]
I've checked again and the addLayer method is public as is the Layer class.

If this is an actual bug in the toolkit, I'm happy to fix it.  But for now it looks like a Kotlin bug.

The workaround to the Kotlin bug seems fine.

**Comment by JtxGit** [comment]
Since 2.6.x is unusable for me due to the north-south offset error, I have been using the time while waiting for 3.0 to learn Kotlin. I really like it thus far. 
When using Kotlin, of course I ran into this "Layer" error. I have tried this mentioned workaround, but can't get it to work, since it just seems to move the problematic Layer call to another place (where it still causes the same error).
Can someone please explain exactly where I should put/create the "KotlinFix" class for this to work? Thanks in advance!
