### ISSUE TITLE
[Android] VectorObject fromShapefile method not found

### ISSUE THREAD

**Issue by MSBilgin** [mousebird/WhirlyGlobe#1156]
I use WhirlyGlobe-Maply_Distribution_2_6_2.aar library in the project. I noticed that **fromShapefile** method is missing.
Note: **fromGeoJSON** exists

**Comment by mousebird** [comment]
I'm looking at the 2.6.2 library for Android and I see fromShapeFile() as a public method on VectorObject.  Moreover, the AutoTester app uses it in the Shapefile test case.

Can you compile and run the AutoTester app?  That should be definitive.

**Comment by MSBilgin** [comment]
I downloaded currently latest release 2.6.1 from the [repo](https://github.com/mousebird/WhirlyGlobe/releases/tag/v2.6.1 ). Checked that you are right. But in the website 's Build page there is [2.6.2 version AAR file](https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/WhirlyGlobe-Maply_Distribution_2_6_2.aar). This library does not contain **fromShapefile**. Also I used another app [Native Libs Monitor](https://play.google.com/store/apps/details?id=com.xh.nativelibsmonitor.app&hl=en) for compare your Test app and my app. Weirdly Test app 's native .so file is about 9MB but my app's .so file is about 4.5MB.  Which AAR version should I use ?

**Comment by mousebird** [comment]
That's very strange and I'll add to the list of problems to look into on 2.6.2. on Android.
Quick question, though.  Do you work for a company that's on WhirlyGlobe-Maply support?  That bumps the priority up a bit.

**Comment by MSBilgin** [comment]
I am trying to consider which library is suitable for our projects. In fact i use spatialite database not shapefiles. This method just drew my attention.
