### ISSUE TITLE
[Android] mapDidStopMoving method firing after every tapping

### ISSUE THREAD

**Issue by MSBilgin** [mousebird/WhirlyGlobe#1158]
Without moving the map **mapDidStopMoving** method fired after tapping. Also **userDidTap** method fired after that

**Comment by mousebird** [comment]
I can see why that would be happening.  Is this causing a problem?

**Comment by MSBilgin** [comment]
I have a huge (250MB vector) spatialite db.  So I load features on **mapDidStopMoving** event by current extent. If user tap without move it tries to load redundantly.

**Comment by mousebird** [comment]
Ah, that would be a problem.

Have you looked at the QuadPagingLayer?  Loading things like that in chunks is what it's designed for.

**Comment by MSBilgin** [comment]
Thanks for fast answer. I 'll try that class.
