### ISSUE TITLE
Errors in xcode 10.2 

### ISSUE THREAD

**Issue by zzjiong** [mousebird/WhirlyGlobe#1160]
error: no matching function for call to object of type 'std::__1::__tree<std::__1::shared_ptr<WhirlyKit::ChunkSceneRep>, WhirlyKit::IdentifiableRefSorter, std::__1::allocator<std::__1::shared_ptr<WhirlyKit::ChunkSceneRep> > >::value_compare' (aka 'WhirlyKit::IdentifiableRefSorter')
<img width="945" alt="图片" src="https://user-images.githubusercontent.com/15756920/56008284-4f210480-5d0e-11e9-9bb5-ee829d12b8d6.png">

**Comment by mousebird** [comment]
This should be fixed on the develop branch.

**Comment by zzjiong** [comment]
thanks！

**Comment by TinyUlt** [comment]
thanks

**Comment by iSuAbner** [comment]
@zzjiong @mousebird   I don't quite understand the meaning. Can you elaborate on it

**Comment by mousebird** [comment]
What is your question?

**Comment by Asha-Pris** [comment]
I am unable to install develop branch.


![Screenshot 2020-02-28 at 5 47 02 PM](https://user-images.githubusercontent.com/47142020/75548149-91e8e980-5a52-11ea-8e74-1f5d9d2c1fa1.png)

**Comment by mousebird** [comment]
You need to install git-lfs:
https://git-lfs.github.com/
