### ISSUE TITLE
Android: Render map on RecyclerView

### ISSUE THREAD

**Issue by CurtesMalteser** [mousebird/WhirlyGlobe#1163]
Is there any way to use the library on RecyclerView?
Any lite version or supported views that are not based on Fragment?
Thank you!

**Comment by mousebird** [comment]
You can instantiate the controllers themselves and manage their life cycles, but people tend to run into problems when they do that.

I'm not sure how this would interface with a RecyclerView.  Can you elaborate?

**Comment by CurtesMalteser** [comment]
Add a small view with a map on each item on the RecyclerView for a particular region of interest.
Using a fragment inside of view holder doesn't make sense, even if this works, this should be the other way.
Also the fragment is always using the open OpenGL and keeps rendering the map, that it's bad in terms of performance on a recycler view that has the purpose of show a generated png from the map.
So the idea would be generate a map and display it as an image, something similar to lite mode from other maps libraries.
I was trying to use the controllers on a custom view and like you mentioned, 

> people tend to run into problems when they do that.

So for some reason it doesn't work.
Also, the tutorial to build the .aar 2.6 is pointing a directory that doesn't exist
Tried the directory that makes sense to me and gradle assemble fails because the repo is using old version of gradle wrapper. When update gradle wrapper I get a lot of errors from NDK.
Can you help somehow to solve/achieve these situations?

**Comment by mousebird** [comment]
Is this build problem with the master branch on github? 

The RecyclerView idea is intriguing and I'll squirrel it away if a use case comes up.

**Comment by CurtesMalteser** [comment]
I'll try to explain.
If I try to compile the .aar from the following directory:
.../WhirlyGlobe/android/library/Android
 I get a lot of errors from gradle like minSDK shouldn't be on manifest.
When I fix these errors, I get errors from NDK.
So I'm trying to use the lib as local module providing this directory .../WhirlyGlobe/android/library/maply that I saw you use on AutoTesterAndroid app.

The idea for RecyclerView is quite used and I can illustrate the following scenario.
I was asked on a job interview, to make a list of Meteorite Landings making usage of NASA API and showing a small view of a map that displays where the landing happened.
Using the Fragment for that is impossible, but a simple view that displays an image like Google Maps makes after rendering the map, is completely ok in terms of performance.
I'm trying to make my own custom view but not having success.
Any suggestions?

**Comment by mousebird** [comment]
I'm not sure what to say on the compile errors.  I'm using it without trouble from the AutoTester app.

As for the RecyclerView, it's a cool idea but is probably outside of what's possible at the moment.  The toolkit has outstanding threads and other interactions that need to settle after setup.  And it needs to fetch data.
 That makes is difficult to use it in a more static way.

**Comment by CurtesMalteser** [comment]
Thank you anyway. So you can close this issue.
