### ISSUE TITLE
[Android] Best Database for app with WhirlyGlobe

### ISSUE THREAD

**Issue by cristianabraga** [mousebird/WhirlyGlobe#1164]
Could you please recommend me the best (easiest) database (not local one) to use in order to store all data for every user? Many Thanks :) 

PS: If you can share same documentation or apps developed related to it I will be very grateful.

**Comment by mousebird** [comment]
Remote database?
It really depends on what you're doing.  It's very application specific.
You might look at PostGRES/PostGIS to start.
