### ISSUE TITLE
Maply crash app v2.6.2

### ISSUE THREAD

**Issue by wliadmin** [mousebird/WhirlyGlobe#1165]
Currently, I have used android v2.6.2. and I have faced lots of crashing during switching fragment or back pressed with a navigation controller.

Library gives me below message and crashing application.
--1. `Maply: GL Error: 1285 - DynamicTexture::createInGL() glTexImage2D()`
--2. `Maply: Crash in QuadImageTileLayer::nativeTileDidLoad()`

Can anyone help with these type of crashes?

**Comment by mousebird** [comment]
See if you can reproduce this in the AutoTester app.  It would be good to have a test that sets up and tears down the fragment repeatedly.

If you're on support, please contact me directly and we'll see what we can do.

**Comment by wliadmin** [comment]
I am using openmaptiles images for globe tiles and the issue is been generated when globe map is loaded again and again when I go to any other fragment and come back to my map fragment its memory increases and my device gets stuck and many times restarted automatically
And there is no such way to reproduce that issue in the autotester app

**Comment by mousebird** [comment]
I'm sorry, but if you can't give me a reproducible case and you're not on support, there's not much I can do for you.
