### ISSUE TITLE
[iOS] Sliding stuck due to Runloop ?

### ISSUE THREAD

**Issue by iSuAbner** [mousebird/WhirlyGlobe#1166]
When I turn on the timer to toggle the texture on Globe, I slide the earth and get stuck. Is this caused by Runloop? I tried adding methods to commandModes but it still seems to be stuck.
And I don't know how to added 
```Texture * Tex = [self createTexture:image desc:desc mode:threadMode];```  
 This method  to commandModes.

**Comment by mousebird** [comment]
Before you mess with the run loop, check to see where the system is getting stuck.
And which version is this?

**Comment by iSuAbner** [comment]
@mousebird      It's only when the timer loads the next texture, and my hand slides across the ground, then a flash of caton . if i comment out the create Texture function . caton disappear . 
 is it a problem because RunLoop or Render ?

**Comment by mousebird** [comment]
I'm sorry, I don't understand what you're saying.
