### ISSUE TITLE
Downloaded Offline MBTiles

### ISSUE THREAD

**Issue by radubc** [mousebird/WhirlyGlobe#1170]
Hi all,

I am trying to work with MBTiles, but it's kind of hard being new to Swift and Maply. I managed to make the geography class file to work. However, it works when the file is in the app bundle. My goal is to create MBTiles with Map Tiler and offer them to clients for download. Is there a way to load downloaded MBTiles. The Apple App Bundle is read-only, so I would like to load the tiles from Library directory. Is there a way to do that?

**Comment by radubc** [comment]
Hi all,

I am trying to work with MBTiles, but it's kind of hard being new to Swift and Maply. I managed to make the geography class file to work. However, it works when the file is in the app bundle. My goal is to create MBTiles with Map Tiler and offer them to clients for download. Is there a way to load downloaded MBTiles. The Apple App Bundle is read-only, so I would like to load the tiles from Library directory. Is there a way to do that?

**Comment by mousebird** [comment]
Yes, you can pass the whole path into the MBTiles initialize call.

**Comment by radubc** [comment]
Thanks. I will try.
