### ISSUE TITLE
getting error when compile

### ISSUE THREAD

**Issue by emreayaydin** [mousebird/WhirlyGlobe#1172]
Hello There, I installed pods with cocoapod  and tried to build with swift I m getting this error.

No matching function for call to object of type 'std::__1::__tree<boost::shared_ptr<WhirlyKit::ChunkSceneRep>, WhirlyKit::IdentifiableRefSorter, std::__1::allocator<boost::shared_ptr<WhirlyKit::ChunkSceneRep> > >::value_compare' (aka 'WhirlyKit::IdentifiableRefSorter')

**Comment by mousebird** [comment]
Boost?  This must be very old.  What version are you using?

**Comment by emreayaydin** [comment]
hello Thanks for your reply,
When I type "brew info boost" at terminal I m getting this message I guess boost version is 1.69.0

boost: stable 1.69.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb
==> Dependencies
Required: icu4c ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
Building of Boost.Log is disabled because it requires newer GCC or Clang.
==> Analytics
install: 52,709 (30 days), 176,460 (90 days), 629,846 (365 days)
install_on_request: 17,704 (30 days), 59,084 (90 days), 195,059 (365 days)
build_error: 0 (30 days)

**Comment by mousebird** [comment]
My point was that we no longer use Boost in WhirlyGlobe-Maply and haven't for some time.

Try using the PodSpec in the WhirlyGlobe-Maply repo:
https://github.com/mousebird/WhirlyGlobe/blob/develop/WhirlyGlobe.podspec

**Comment by emreayaydin** [comment]
Okay I understood... I was install with " pod 'WhirlyGlobe', '2.4' " and I guess it  was old version. I tried newer version with  " pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe.git', :branch => 'develop' " 
It worked well :)) thanks for everything

**Comment by grantd77** [comment]
I tried the above solution and it did not help me.
I see the issue is now closed but is there any other suggestions?

**Comment by grantd77** [comment]
Sorry it has helped but has just introduced many code differences from an older code base I am working on.

**Comment by mousebird** [comment]
I'm not sure what the question is.
