### ISSUE TITLE
[iOS] transparent stripes on globe

### ISSUE THREAD

**Issue by Pryotic** [mousebird/WhirlyGlobe#1173]
Hello,
thank you a lot for whirly globe, it's really helping with my project. I have some issues though, and it would be very nice to get some help since I can't find any similar reports or a solution to it.

to keep it short, in certain angles my globe looks like that:

![IMG_4663](https://user-images.githubusercontent.com/48635754/58640461-6a18f980-82f9-11e9-90ef-9a1e2a6e327b.jpg)

For me it seems like if parts of the globe, that are on the turned-away-side are visible through the side of the globe that is actually in the users field of vision. (for example I can see small stripes of Africa through the globe, when I look at Australia)

please excuse my english, I hope it's possible to understand me.

**Comment by mousebird** [comment]
If you tesselate arbitrary polygons to form the globe that can happen.

What you can do is use a different shader, one that takes the back side of the globe into account.  Is this iOS or Androd?

**Comment by Pryotic** [comment]
thank you for the fast answer, it's iOS. Could you gibe me hint about who to set that back side shader?

**Comment by mousebird** [comment]
If you set the kMaplyShader to kMaplyShaderDefaultLine it will pick up a shader that does the back-of-globe logic.

**Comment by Pryotic** [comment]
Thanks! It's working now
