### ISSUE TITLE
Question: vertically-oriented markers?

### ISSUE THREAD

**Issue by wdcurry** [mousebird/WhirlyGlobe#1174]
Hey, just found WhirlyGlobe, love the potential! I have an app idea on the back-burner as I didn't know that such a repo existed that I could tap into, so THANK YOU!  A portion of the app, but significant to my idea, is presenting a globe as you offer, with markers, but the markers visual indicate important via visual height extending out at 90º from the globe's surface. 

It that was not clear enough, imagine a person with a metal detector who would scan a field and mark spots of interest for a digging crew, and drop taller markers for areas of stronger interest, and shorter markers for the average pings she might encounter.  Then the dig crew could quickly assess the field and see the varying flag heights and concentrate their efforts around the taller flagpoles. 

Sorta like that but only digitally.  Is this kind of ability currently available with WG ( the ability to create and display the vertically-oriented marker, not the ability to engage a crew ;)  )

**Comment by mousebird** [comment]
Cool, thanks.

You might be able to make that happen with a MaplyBillboard.  Try it with kMaplyBillboardOrient set to kMaplyBillboardOrientGround

**Comment by wdcurry** [comment]
Thank you.  I have no clue about MaplyBillboard as yet of course, but *really* hope this can solve this unusual request without turning me into a renewed math major!
