### ISSUE TITLE
[iOS] load single zoom-levels smoothly

### ISSUE THREAD

**Issue by Pryotic** [mousebird/WhirlyGlobe#1176]
Hello,
I'm sorry for asking a lot of questions, but I'm pretty new to everything and it's kinda hard to find my way through everything. I appreciate WhirlyGlobe a lot, though!

I have a visual issue, when WhirlyGlobe is loading different zoom levels of my tile-data at the same time: (the sea and the label-layer are looking kinda odd, because different zoom levels are mixed up)

![Picture](https://user-images.githubusercontent.com/48635754/58726279-9b6cf480-83e1-11e9-89cf-7c38eef5b251.jpg)

I know that behavior is probably wanted, it makes sense to show areas that are further away (like the sides of the globe) in different zoom levels. Still I hope there is a solution to my problem.

I know about the `singleLevelLoading` Attribute of the layers, but I think it's made for maps, not globes, because when I set it to true, stuff like that is happening:

![IMG_4679](https://user-images.githubusercontent.com/48635754/58726625-817fe180-83e2-11e9-9149-8c0ce20f3a56.PNG)

Is there a way, to only load one zoom-level at once and still make it look properly?

I appreciate your help, thank you.

**Comment by mousebird** [comment]
Try updating to 2.6.1 and using the sampler/loader approach.  The first example in the AutoTester is doing that.  It gives you better control over the zoom levels on the globe.

**Comment by Pryotic** [comment]
Hello Mousebird,

I have a problem with Vector-Objects again. When I fade them out over time the shader doesn’t really seem to support that, because their are stripes occurring that I think the shader should handle with.

I added a short clip, to show what I’m talking about. [ShortClip](http://sendvid.com/9na5vyig)
Also in the first few seconds of the video, when the globes borders are still visible, the underlying map is visible through the VectorObjects that are forming the "blue countries“.   Is there a way to fix that?

I appreciate WhirlyGlobe and your support a lot. Thank you!
