### ISSUE TITLE
Fading Out Vector Objects

### ISSUE THREAD

**Issue by Pryotic** [mousebird/WhirlyGlobe#1177]
Hello,
I'm struggling to find a way to fade out, or even just remove vector objects from my GlobeViewController.

I tried to keep track of them using an array of `MaplyComponentObject` and remove them using `WhirlyGlobeViewController.remove(theObj: MaplyComponentObject)` but that's not working, nothing happens. 
I also tried to put the vector objects on a certain layer and then to fade out that layer but I couldn't figure out how to do that. 

What am I doing wrong?

**Comment by mousebird** [comment]
When you add one or more vector objects at the same time, you get a MaplyComponentObject back.  You need to pass that MaplyComponentObject to the remove call.  Be sure that it's not spitting out any warnings when you do that.  It should say something if you pass in something bad.

Fading is a function of adding or removing.  It's just part of the description dictionary you pass in.

**Comment by Pryotic** [comment]
Thank you very much, I found the problem and fading is working now as well.

**Comment by Pryotic** [comment]
Hello Mousebird,

I have a problem with Vector-Objects again. When I fade them out over time the shader doesn’t really seem to support that, because their are stripes occurring that I think the shader should handle with.

I added a short clip, to show what I’m talking about. 
Also in the first few seconds of the video, when the globes borders are still visible, the underlying map is visible through the VectorObjects that are forming the "blue countries“.   Is there a way to fix that?

I appreciate WhirlyGlobe and your support a lot. Thank you!










> Am 21.06.2019 um 03:07 schrieb Steve Gifford <notifications@github.com>:
> 
> When you add one or more vector objects at the same time, you get a MaplyComponentObject back. You need to pass that MaplyComponentObject to the remove call. Be sure that it's not spitting out any warnings when you do that. It should say something if you pass in something bad.
> 
> Fading is a function of adding or removing. It's just part of the description dictionary you pass in.
>
