### ISSUE TITLE
[Android] Migrate to AndroidX

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe#1179]
Hi Steve,

Hope everything is OK for you.

I wonder if there is any chance to see WhirlyGlobe migrate to AndroidX?

As I understand, AndroidX is refactoring all the links to the Android Support Library.

I think the migration will not be very complicated, for example:

The GlobeMapFragment extends Fragment from:

import android.support.v4.app.Fragment;
will be...
import androidx.fragment.app.Fragment;

Anyway, do you have the time?

If not, i can get time to do it: Clone the repo, create a branch and migrate the Android code.

What is the best branch to start and create a new one? develop or master?

Regards.

**Comment by mousebird** [comment]
I've done it for 3.0 and it's a pretty easy transition.

Just start with the develop branch and do the Migrate thing.  Works great.

**Comment by NasH5169** [comment]
Sorry but what do you mean with "3.0"?

:)

**Comment by mousebird** [comment]
Ah, that's the latest version of the toolkit.  Only subscribers are getting it until 2020.
I'm still supporting 2.6, so I may get to this update for that branch as well.

**Comment by NasH5169** [comment]
Ok great.

I clone the repo and I was able to run on my old Samsung S5 (Android 9).

One little question, for now i'm using the android-ndk-r12b. You know your toolkit :-) so what is today the recommended NDK version for Whirly 2.6.2?

**Comment by mousebird** [comment]
I haven't seen problems with an NDK in quite some time.  I'm just letting Android Studio pick at the moment.

**Comment by NasH5169** [comment]
In other words, I can take the last one r20? (will try).

By the way, the Android X migration has been very easy for the kit (maply) and also the AutoTesterApp. 👍
