### ISSUE TITLE
Android Building from Source Failed

### ISSUE THREAD

**Issue by HuWenHao92** [mousebird/WhirlyGlobe#1180]
branch:develop 
Error building from source , here is my error log.

[build.log](https://github.com/mousebird/WhirlyGlobe/files/3333606/build.log)

local.properties content:
sdk.dir=/Users/huwenhao/develop/Android/SDK
ndk.dir=/Users/huwenhao/develop/Android/android-ndk-r10e

I've already download NDK r16b,r20 and build with them , But all failed to build.
build.gradle content:
[build.txt](https://github.com/mousebird/WhirlyGlobe/files/3333636/build.txt)

**Comment by mousebird** [comment]
I'm not clear what that error really is.
I did just fix a problem in the develop branch related to a compiler problem on Android.  It's now building successfully for me with the latest Android Studio.

**Comment by HuWenHao92** [comment]
I have pull git repository . The last git log data is Jun 27 2019 . But many errors has occurred . 

Build with this command:`./gradlew assemble     `

1.  `package com.squareup.okhttp does not exist`
How to set okhttp complie? in build.gradle? 

2. `*** No rule to make target `jni/../../../..//common/local_libs//proj-4/src//p_series.c', needed by `obj/local/arm64-v8a/objs/Maply/__/__/__/__//common/local_libs//proj-4/src//p_series.o'.  Stop.`

I didn't find a file named `p_series.o` , Where is this file?


```
Skipped header for WideVectorInfo
Compiling java for WideVectorManager
./com/mousebird/maply/MaplyBaseController.java:20: error: package com.squareup.okhttp does not exist
import com.squareup.okhttp.Dispatcher;
                          ^
./com/mousebird/maply/MaplyBaseController.java:21: error: package com.squareup.okhttp does not exist
import com.squareup.okhttp.OkHttpClient;
                          ^
./com/mousebird/maply/MaplyBaseController.java:52: error: cannot find symbol
    private OkHttpClient httpClient;
            ^
  symbol:   class OkHttpClient
  location: class MaplyBaseController
./com/mousebird/maply/MaplyBaseController.java:132: error: cannot find symbol
    public synchronized OkHttpClient getHttpClient()
                        ^
  symbol:   class OkHttpClient
  location: class MaplyBaseController
./com/mousebird/maply/MaplyBaseController.java:135: error: cannot find symbol
                        httpClient = new OkHttpClient();
                                         ^
  symbol:   class OkHttpClient
  location: class MaplyBaseController
./com/mousebird/maply/MaplyBaseController.java:139: error: cannot find symbol
                        Dispatcher dispatch = httpClient.getDispatcher();
                        ^
  symbol:   class Dispatcher
  location: class MaplyBaseController
./com/mousebird/maply/ClusterGenerator.java:46: error: cannot find symbol
            baseController.removeTexturesByID(new ArrayList<Long>(oldTextures), MaplyBaseController.ThreadMode.ThreadCurrent);
                          ^
  symbol:   method removeTexturesByID(ArrayList<Long>,ThreadMode)
  location: variable baseController of type MaplyBaseController
7 errors
Skipped header for WideVectorManager

> Task :buildNative
Android NDK: Found platform level in ./project.properties. Setting APP_PLATFORM to android-18.    
make: Entering directory `/Users/huwenhao/develop/Android/workspace/PersonalProject/WhirlyGlobePro/WhirlyGlobe/android/library/Android'
make: *** No rule to make target `jni/../../../..//common/local_libs//proj-4/src//p_series.c', needed by `obj/local/arm64-v8a/objs/Maply/__/__/__/__//common/local_libs//proj-4/src//p_series.o'.  Stop.
make: *** Waiting for unfinished jobs....
make: Leaving directory `/Users/huwenhao/develop/Android/workspace/PersonalProject/WhirlyGlobePro/WhirlyGlobe/android/library/Android'

```

**Comment by mousebird** [comment]
Try building the AutoTester app in Android Studio.  See if that generates errors.

**Comment by HuWenHao92** [comment]
I have import WhirlyGlobe/android/library/maply module , Then add dependency . I found my app start up slower than use WhirlyGlobeMaply.arr (2.6.2) . Should I modify some options? What is the version number of maply module?

**Comment by mousebird** [comment]
Make sure you are compiling Release.

**Comment by HuWenHao92** [comment]
Thx for your help ~ very thx :)

**Comment by CurtesMalteser** [comment]
@HuWenHao92 can I ask if you were able to build .aar?
If yes, how?
I'm getting same error, but I need to update gradle to androidX.
Thank you in advance.

**Comment by mousebird** [comment]
Make sure you're on the latest version.

**Comment by CurtesMalteser** [comment]
I'm on develop with submodules also initialized.
When I try to assemble the maply I get:
`A problem occurred evaluating root project 'maply'.`
`> Plugin with id 'com.android.library' not found.`

But if I try to compile Android directory from Android Studio I get same error that HuWenHao92 shared.

Also I'm getting references for androidX but Gradle file still using support lib.
Does this make sense?

**Comment by mousebird** [comment]
This this in building the AutoTester app or your own app?

**Comment by CurtesMalteser** [comment]
This this in building the AutoTester.

copy/paste from GlobeMapFragment

`import androidx.fragment.app.Fragment;`

In fact I want to do that and update OkHttp to version 4 so I can use the lib on my project.
But I can't generate the .aar or compile even without changing anything.

**Comment by CurtesMalteser** [comment]
Well, definetly there was a try to update to androidX changes on Gradle file were not commited. I just updated dependecies and all the code to androidX.
I'll update to OkHttp 4 later.
If you want I can make a pull request.
I appreciate any help to build an .aar so I can keep using WhirlyGlobe lib.

**Comment by mousebird** [comment]
Sure, I'd love to see what you had to do.

**Comment by CurtesMalteser** [comment]
Ok, as soon as I finish the update to OkHttp 4.
I noticed that there's no build script on directory maply but instead is on Android directory that when I try to compile makes usage of  C++ lib. When I change it to C++ shared instead I get the initial error of this issue docummented by HuWenHao92.
