### ISSUE TITLE
Android 2.6.2 Marker with rotate bitmap

### ISSUE THREAD

**Issue by HuWenHao92** [mousebird/WhirlyGlobe#1181]
I found marker image didn't update when I rotated bitmap by matrix . If create new bitmap in loop , Markers are update . But Graphic Memory And Native Memory growing fast . So I want to reuse bitmap , I don't create new bitmap for each execution of the loop.

```
 int count = 0;

    private class TimerHandler extends Handler {
        public TimerHandler(Looper looper) {
            super(looper);
        }

        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);

            count++;
            Marker marker = rotateBitmapTest(count * 10, bmp_holdline_1, 116.593872, 40.0858555);
            MarkerInfo markerInfo = new MarkerInfo();
            markerInfo.setLayoutImportance(Float.MAX_VALUE);
            markerInfo.setDrawPriority(MarkerInfo.ScreenMarkerPriorityDefault);
            markerInfo.setMinVis(0.0f);
            markerInfo.setMaxVis(0.001f);
            final ComponentObject coMarkers = mapController.addMarker(marker, markerInfo, MaplyBaseController.ThreadMode.ThreadAny);
            timerHandler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    mapController.removeObject(coMarkers, MaplyBaseController.ThreadMode.ThreadAny);
                }
            }, 500);

            timerHandler.sendEmptyMessageDelayed(0, 1000);

        }
    }

```

I rotate Bitmap with canvas , This is my code:

```java
    private Matrix matrix = new Matrix();
    private Paint paint = new Paint();
    private Bitmap emptyBmp;
    private Canvas canvas;
    public Marker rotateBitmapTest(float degree, Bitmap srcBitmap, double lon, double lat) {
        if (emptyBmp == null) {
            emptyBmp = Bitmap.createBitmap(srcBitmap.getWidth(), srcBitmap.getHeight(), Bitmap.Config.ARGB_8888);
            canvas = new Canvas(emptyBmp);
        }

        canvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.MULTIPLY);//clear
        int offsetX = srcBitmap.getWidth() / 2;
        int offsetY = srcBitmap.getHeight() / 2;
        matrix.reset();
        matrix.postTranslate(-offsetX, -offsetY);
        matrix.postRotate(degree);
        matrix.postTranslate(offsetX, offsetY);
        paint.reset();
        paint.setAntiAlias(true);
        paint.setFilterBitmap(true);//位图过滤

        canvas.drawBitmap(srcBitmap, matrix, paint);

        Marker marker = new Marker();
        marker.image = emptyBmp;
        marker.loc = Point2d.FromDegrees(lon, lat);
        marker.size = new Point2d(0.0001, 0.0001);

        return marker;

    }
```

**Comment by mousebird** [comment]
I'm afraid the Marker object doesn't have a rotation on that version.  What you can do it use ScreenMarker or pre-generate a variety of rotated markers.

**Comment by HuWenHao92** [comment]
I can generated rotated markers by rotated bitmap . I just want to know if I can reuse same bitmap object . rotateBitmapTest method generate new marker with same bitmap object  for each execution of the loop . I rotated same bitmap object for different degree , But markers doesn't update with rotated bitmap.

**Comment by mousebird** [comment]
The toolkit makes a new texture when you hand it a bitmap.  It doesn't check back on the bitmap.

Are you sure you don't want to use ScreenMarkers?  Those have a rotation.

**Comment by HuWenHao92** [comment]
Yes . ScreenMarkers couldn't zoom in or out by gesture . So we choose Markers instead of ScreenMarkers . How the toolkit remove texture ? Can I set a same bitmap with different pixel data?

**Comment by mousebird** [comment]
Take a look at the addTexture and removeTexture methods.
You can't overwrite an existing texture.

**Comment by HuWenHao92** [comment]
How does Marker add or remove Texture ?   I didn't found method...

**Comment by mousebird** [comment]
It just sort of figures it out.  And it doesn't do that good a job.
In 3.0 you can use a Sticker, which gives you more control.
But for 2.6 it may be best to just use a ScreenMarker for now.

**Comment by HuWenHao92** [comment]
When is Android WhirlyGlobeMaply 3.0 released ?

**Comment by HuWenHao92** [comment]
The Android WhirlyGlobeMaply 2.6.2  also has a problem with ScreenLabel . backgroud color set up failed . Would be fixed in 3.0?

**Comment by mousebird** [comment]
3.0 will be out January 1 2020.
And yes, background color is fixed, as are many other things.

Are you on support?

**Comment by HuWenHao92** [comment]
No, Is there a beta version of 3.0 ? :) I can take test .

**Comment by mousebird** [comment]
I'm afraid not.

**Comment by HuWenHao92** [comment]
Thanks for your help ~
