### ISSUE TITLE
[Android] Support custom tile matrix for a tile layer

### ISSUE THREAD

**Issue by sveta-wl** [mousebird/WhirlyGlobe#1182]
Hey WhirlyGlobe Team,

is there a way to provide a custom resolutions matrix (similar to the [OpenLayers TileGrid](https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_TileGrid-TileGrid.html) ) for a tile layer (local and remote source)?

**Comment by mousebird** [comment]
You can set up your own RemoteTileInfo objects and try to do something per zoom level.

**Comment by sveta-wl** [comment]
Hi @mousebird 

thank you for your reply but I don't really get what do you mean by "try to do something per zoom level" :)

The problem is that my origin tile for `x=0 y=0 z=0` for example from a local tile source (a data base on a sd card) looks like this:
<kbd><img src="https://user-images.githubusercontent.com/10789303/60571950-ccd83780-9d74-11e9-8368-11f7df40c8b0.png" width="180"/>

When I render it on a WhirlyGlobe map on Android it looks like this:
<img src="https://user-images.githubusercontent.com/10789303/60572038-014bf380-9d75-11e9-8d23-b183a7707dd4.png" width="180"/>

When I render it in QGIS or OpenLayers with provided resolution matrix in a tile grid, it's displayed correctly:
<img src="https://user-images.githubusercontent.com/10789303/60572105-293b5700-9d75-11e9-86b5-49458031b78f.png" width="180"/>

The data have the EPSG:25832 projection and the bounding box 
```
362801.72   5619395.23
369001.74   5625242.12
```

The resolution matrix for all zoom levels looks as following:
```
zoom 	pixel_x_size	pixel_y_size
0 	152.746		152.746
1	76.373		76.373
2	38.187		38.187
3	19.093		19.093
4	9.547		9.547
5	4.773		4.773
6	2.387		2.387
7	1.193		1.193
8	0.596		0.596
9	0.298		0.298
```
The tile size is `256x256`.

Could you please explain or give some hint what exactly should be implemented to get such tiles rendered in a correct way with correct resolutions?

**Comment by mousebird** [comment]
I think I see.  The top tile isn't complete.  It's using the extents to clip.
Clever, and there are cases where I've done similar things, but in general that's not going to work with a tile source.  The extents of the tile and the data in the tile really need to match.

**Comment by sveta-wl** [comment]
Hi @mousebird  
I have another related question: is there a way to provide a custom tile matrix as a quad tree to a tile layer?  
My tile source has a EPSG:25832 projection, defined bounding box and a tile matrix like this:

```
zoom_level    matrix_width   matrix_height
0             3              2
1             11             9
2             21             17    
...
```
so, it's not like a default tile matrix, where for the zoom level = 0 there is only one tile, but it has 6 and so on. In QuadImageTileLayer when I set up the projection with the bounding box the `fetchTile` method for zoom level 0 for example requests only tile data for 0,0,0 (what is absolutely correct, if you have a standart tile matrix), but for the custom tile matrix it needs to request all 6 tiles.
Can I rewrite or extend `QuadImageTileLayer` class (or any other) to achieve a custom tile matrix support? 

Thank you for help.

**Comment by mousebird** [comment]
QuadImageTileLayer is extremely complex.  I wouldn't recommend trying to modify it.

What I've done in other cases like this is to map the tile matrices into a regular quad tree starting at level 0.  Then I do the translation in the RemoteTileInfo objects.

**Comment by sveta-wl** [comment]
Then in this case when to one tile in the regular quad tree for the zoom level 0 in the source there are six: two columns and three rows, I have to combine the tiles together (and crop them if for a some other zoom levels it will be 5 and half source tiles for a one quad tree tile) so, that they will match. Am I right?

**Comment by mousebird** [comment]
That's not the way I've done it in the past.
Your level 0 is probably more like level 2, which would be 4x4 tiles with a few of them empty.
I usually have to draw the structure out to figure out if it can be represented as a quad tree.

**Comment by sveta-wl** [comment]
Well, it works on first couple of levels, but at some point it becomes completely mess :(

**Comment by mousebird** [comment]
My experience is, even if it can be mapped into a normal quad tree, it's difficult to debug.
