### ISSUE TITLE
Is there an imageWMS loading like openlayers?

### ISSUE THREAD

**Issue by songyuyang0918** [mousebird/WhirlyGlobe#1183]
Dear developers,
Is there an imageWMS loading like openlayers?
I want to display it by loading the entire image of WMS getmap, without slicing it.
WhirlyGlobe I think is very flexible, but I have no idea what to do?

**Comment by mousebird** [comment]
On iOS there is a WMSTestCase in the AutoTester app.  You can look at that.
On Android, there is no WMS support.
