### ISSUE TITLE
Globe animate to 0,0

### ISSUE THREAD

**Issue by llvinhll** [mousebird/WhirlyGlobe#1186]
I'm new to Whirlyglobe. So i'm experience a weird behavior when doing .animate(toPosition: MaplyCoordinateMakeWithDegrees(0, 0), time: 1.0), while the center is 0,0 the globe is rotated where north is pointing to the left. But if you do MaplyCoordinateMakeWithDegrees(0.1, 0), everything looks as expected, north is up. I assume 0 lat gives undefined or can't divide by zero issue somewhere. No sure if this is an expected behavior, thought it might be worth a look. 
I'm using 2.6.1 release on iOS

**Comment by mousebird** [comment]
Set keepNorthUp to true if you'd like to keep north up.
You can also use some more the more specific animation methods if you want to control the heading.  setViewState: is the most specific.

**Comment by llvinhll** [comment]
yea, i tried animate with heading params, and keepNorthUp, and .rotate same issue. i mean work around is just use anything not 0 lat. Also just tried setViewState with pos = (0,0) and heading = 0 
Same thing unless theres another param in WhirlyGlobeViewControllerAnimationState I need to change to rotate it
