### ISSUE TITLE
Assertion Failure in Resize, iPhone Xs with example project

### ISSUE THREAD

**Issue by douglasteeple** [mousebird/WhirlyGlobe#1187]
There is an alignment assertion failure (align to 64 bytes) on iPhone Xs (the simulator works fine, the actual iPhone gets fault). In WhilryKitSceneRenderES resizeFromLayerES.mm line 558. Please see attached image.
<img width="1440" alt="Screen Shot 2019-07-27 at 4 28 25 AM" src="https://user-images.githubusercontent.com/17880539/61995971-af705380-b02a-11e9-9fee-af456fe021d6.png">

**Comment by mousebird** [comment]
For anyone who runs into this, you just need to turn off the Metal Verification.  It's an Apple bug.
