### ISSUE TITLE
addPostSurfaceRunnable method

### ISSUE THREAD

**Issue by HuWenHao92** [mousebird/WhirlyGlobe#1189]
I just want to know where I should use addPostSurfaceRunnable method ? And How to judge OpenGL surface was created ?

**Comment by mousebird** [comment]
If you do an addTask() on the MaplyBaseController with ThreadCurrent it will be run after the surface is attached.  That method defers the runnable until the surface is ready.

**Comment by HuWenHao92** [comment]
If I want to update screenmarkers with a timer in HandlerThread , Should I use addPostSurfaceRunnable method ?

**Comment by mousebird** [comment]
It depends on how you're doing it.  If you're updating the screen markers every frame, use an ActiveObject.  If you're doing it periodically, just make the add/remove calls with ThreadCurrent.
