### ISSUE TITLE
Remote Vector Tile

### ISSUE THREAD

**Issue by llvinhll** [mousebird/WhirlyGlobe#1192]
I have a vector tile service and I'm trying to incorporate in my whirlyglobe app. I found that I can use MaplyVectorTiles.StartRemoteVectorTiles() but my service doesn't have a descriptions json endpt, that the function needs. I was looking to just extending that class and massage it use what i have but i'm having issues with the style dictionary format. Is there documentation or a reference or sample of the that style dictionary.  Or is there a way to use something like maplyvectorstylesimplegenerator and have maplyvectortiles use that ?

**Comment by mousebird** [comment]
Maply Vector Tiles are deprecated.  That's an old format no one uses.
You'll want to switch to the Mapbox Vector Tile support.
Look at the AutoTester app for the various Mapbox test cases.

**Comment by llvinhll** [comment]
Which vers of mapbox vector tile spec is supported?

**Comment by mousebird** [comment]
I believe 2.1.  I haven't checked it strictly, though.
Mapbox Style sheet support is much more chaotic at the moment.

**Comment by carlos-mg89** [comment]
I'm trying to access to the AutoTester app to test loading of Offline Mapbox Vector Tiles, but it seems I need access granted. Or at least, this is what I think based on this page http://mousebird.github.io/WhirlyGlobe/tutorial/android/auto-tester-android.html

The first link, to the example app, is giving me a 404.

I've subscribed to your newsletter and I believe you are giving access to 3.0 version only to subscribers. Right?

**Comment by mousebird** [comment]
The AutoTester app is in the WhirlyGlobe repo:
https://github.com/mousebird/WhirlyGlobe/tree/master/ios/apps/AutoTester

If you close the repo and then set up the submodule to get the resources, you should be able to compile and run it.

**Comment by llvinhll** [comment]
i think we can close this issue. thanks
