### ISSUE TITLE
Touch point to latitude/longitude - Apple Pen

### ISSUE THREAD

**Issue by radubc** [mousebird/WhirlyGlobe#1193]
Hello,

I am trying to capture the touch points from an Apple Pen as GPS coordinates. For this, I am using touchesBegan and capture the touch points in the UIView. With MKMapkit, it's easy to convert to GPS coordinates. However, I couldn't find any method to do this with WhirlyGlobe. 

I was able to get the geocentric coordinates with geocPoint(fromScreen: CGPoint). Is there any way to convert these coordinates in normal lat/long coordinates, even in radians?

I also know about the didTapAt delegate method, but it does not differentiate between finger and stylus tap. I need to filter out the hand touches and only get the stylus touches.

Can anyone help me please?

Thank you.

**Comment by mousebird** [comment]
geoPointFromScreen: should give you a point in lon/lat.

**Comment by radubc** [comment]
I am a little bit confused about that method. Is it called on the WhirlyGlobeViewController()? When I try to select it, I see that it returns a Bool. Then, it takes a CGPoint, which I have, and a geoCoord, of type UnsafeMutablePointer<MaplyCoordinate>. I'm not sure what this is, but it looks like a set of coordinates to me. This is actually what I'm trying to get. I tried creating a MaplyCoordinate based on a set of geocentric coordinates, but it didn't work.

The description says that it calculates a set of geo coordinates from a point on the screen, but it returns a Bool. Do I call it the right way?

**Comment by mousebird** [comment]
Yes, it's on the WhirlyGlobeViewController.

The method predates the Swift integration.  So the second argument is the return value (a MaplyCoordinate struct) which Swift treats as an UnsafeMutablePointer.

The reason the method returns a bool is you can tap outside the globe.

**Comment by radubc** [comment]
Thank you for your answer. 

The method might predate Swift, but my programming skills don't. :) So, I tried to do something, but I'm not sure if it's right, or if there are better ways to do it.

Here's what I have:

First, I created a pointer
var coordinatesPointer: UnsafeMutablePointer<MaplyCoordinate>!

Then, an array of coordinates for it to point to
var coordinates: [MaplyCoordinate] = []

I told the pointer to point to the coordinates (not sure if necessary)
coordinatesPointer = UnsafeMutablePointer(mutating: coordinates)

I called the geoPoint method
_ = theViewC?.geoPoint(fromScreen: touchPoint, geoCoord: coordinatesPointer)

Lastly, I took the x and y of the pointee, and converted them to degrees
let latitudeRad = Double(coordinatesPointer.pointee.y)
let longitudeRad = Double(coordinatesPointer.pointee.x)
            
let ladDegrees = Measurement(value: latitudeRad, unit: UnitAngle.radians).converted(to: .degrees).value
let longDegrees = Measurement(value: longitudeRad, unit: UnitAngle.radians).converted(to: .degrees).value

I get something that look like GPS coordinates. Is this the right way to do it, or there are better ways?

Thank you.

**Comment by mousebird** [comment]
A note for Tim.  This falls under making thing easier to use from Swift.

**Comment by TimSylvester-mousebird** [comment]
@radubc First, I believe your use of `UnsafeMutablePointer` is not quite right.  For one, that object is only valid during its initialization, and should usually be used with an explicit scope, as in the example below.

Secondly, you only need a single result object rather than an array and, while you could use the first element of an array, the one in your example is empty.  I expect this confusion comes from the result of `geocPointFromScreen` being an array, but in that case it's an array of individual values (x,y,z) rather than an array of coordinates.

I've added a version of the `geoPointFromScreen` method for the globe controller which returns an optional coordinate (by wrapping it in `NSValue`) to obviate the need for unsafe mutables.  

The following Swift code compiles and runs for me using the latest `develop` branch, XCode 12.2, and Swift 5.

```
var coordinates: MaplyCoordinate = MaplyCoordinate()
if withUnsafeMutablePointer(to: &coordinates, { vc.geoPoint(fromScreen: screenPt, geoCoord: $0) }) {
    print("\(coordinates.y) \(coordinates.x)")
}
if let geo = vc.geoPoint(fromScreen: screenPt)?.maplyCoordinateValue {
    print("\(geo.y) \(geo.x)")
}
```
