### ISSUE TITLE
Controlling Vector Texture opacity

### ISSUE THREAD

**Issue by llvinhll** [mousebird/WhirlyGlobe#1194]
I'm trying to modify the opacity of texture on the fly. Is there way to do this besides, removing and adding the texture and vectors with a new UImage of a different opacity?
or maybe a way to modify the componentobject's opacity somehow?

**Comment by mousebird** [comment]
Try using changeVector:

**Comment by llvinhll** [comment]
with kMaplyColor or kMaplyVecTexture ?

**Comment by mousebird** [comment]
I believe you can change color with that.

**Comment by llvinhll** [comment]
thanks
