### ISSUE TITLE
build fails: 'grpc/support/port_platform.h' file not found after adding WhirlyGlobe & WhirlyGlobeResources pod

### ISSUE THREAD

**Issue by kubramiis** [mousebird/WhirlyGlobe#1197]
after adding pod 'WhirlyGlobe' & pod 'WhirlyGlobeResources' to my project im not able to build it anymore. see pod's installed below: 

<img width="569" alt="Bildschirmfoto 2019-08-28 um 23 03 31" src="https://user-images.githubusercontent.com/14977322/63892953-3711ff00-c9e9-11e9-97ec-3b495e2104b2.png">

<img width="1142" alt="pic" src="https://user-images.githubusercontent.com/14977322/63893001-57da5480-c9e9-11e9-8cca-f4e8e7a150ec.png">

for more information just trigger me.

Arigato!

**Comment by mousebird** [comment]
That's a pretty old version.  Try using the podspec in the WhirlyGlobe repo.

**Comment by kubramiis** [comment]
did in my Podfile: 
pod 'WhirlyGlobe', :podspec => 'https://raw.githubusercontent.com/mousebird/WhirlyGlobe/master/WhirlyGlobe.podspec'

but the problem is remaining..

**Comment by mousebird** [comment]
Not sure what to suggest.  I'm not seeing this in other Pod projects.
