### ISSUE TITLE
[iOS] loading marker and label while globe in motion

### ISSUE THREAD

**Issue by Pryotic** [mousebird/WhirlyGlobe#1198]
Hello,
when my globe is in motion, the labels and markers on it won't appear instantly. Only when the motion stops, the labels are displayed. I'm actually not really sure if that is a general problem or if I messed something up.
Is there a way to fix that? It is pretty unhandy, since when a user is rotating the globe slowly without stopping it at any point, the labels won't load at all.

Here is a short clip to show the issue:
[Short Clip](http://sendvid.com/6uhe5j02)

I'm grateful for any help :)

**Comment by mousebird** [comment]
If you're using the layout engine (layoutImportance is set to something other than MAXFLOAT) then this will happen.  The layout engine runs when the user stops moving.

If you don't need the layout engine, you can set the layoutImportance to MAXFLOAT for those markers and text.

**Comment by Pryotic** [comment]
ok, thank you. And there is no way to make the layout-engine running while moving the globe?

**Comment by mousebird** [comment]
I see it running periodically even when I'm moving.  What version are you using?
