### ISSUE TITLE
[iOS] VectorObjects border with width

### ISSUE THREAD

**Issue by Pryotic** [mousebird/WhirlyGlobe#1199]
Hello,
I want to draw country-borders with a certain width and I'm using vector-objects to do so, in fact two overlaying vector-objects, one small line and one bigger line.

Here is how it looks right now:
![Picture 1](https://user-images.githubusercontent.com/48635754/65054659-39bf9e80-d96e-11e9-9486-51ef3a1d5a0b.jpg)

So there are a few problems occurring. First I'm setting alpha-values but the vector-objects doesn't seem to stick to that. kMaplyVolor should support alpha values right?

second at the edges of the polygons there are breaks visible, is there any feature to get smooth edges?

My working goal is to make it look kind of like this: (altthought even there, these little gaps are occuring)

![Picture 2](https://user-images.githubusercontent.com/48635754/65055078-de41e080-d96e-11e9-8202-307e7b3ea34d.PNG)

so third question, but this one is of no real importance, just out of interest: Is it possible to do dashed lines as border of the vector-objects?

**Comment by mousebird** [comment]
Try wideVectors rather than just vectors.  There's an example in the AutoTester.

You can do dashed lines.  Again, look in the AutoTester app for the WideVectors test case.
