### ISSUE TITLE
ShapeCylinder and animation

### ISSUE THREAD

**Issue by beersheba** [mousebird/WhirlyGlobe#1201]
From Shape class documentation:
> The maply shape is just the base class. Look to ShapeCircle, ShapeCylinder, ShapeSphere, ShapeGreatCircle, and ShapeLinear.

Where can I find them? I want to add a cylinder to the globe surface on Android.
Also, I want to animate it. Is there any example of shape animation?

**Comment by mousebird** [comment]
In 2.6 only ShapeRectangle and ShapeSphere are available.
The rest were ported in 3.0 for Android.

Sorry for the confusion.  That comment was copied from the iOS version.

**Comment by beersheba** [comment]
Thank you for your answer!

What about shape animation? It's described in a [blog post about v. 2.2](http://mousebirdconsulting.blogspot.com/2013/08/whirlyglobe-maply-22.html). Can you provide some example of Android implementation?

**Comment by mousebird** [comment]
AnimatedScreenMarkersTestCase uses Active Objects.
They're pretty simple.  You get a callback right before the frame render and you have to delete your old objects and create new ones right then.  Be sure to MaplyBaseController.ThreadMode.ThreadCurrent when you add or remove things.
