### ISSUE TITLE
Can't compile 2.6.1. on iOS device with issues with Eigen

### ISSUE THREAD

**Issue by tobsterH** [mousebird/WhirlyGlobe#1203]
Hi,

I've upgraded from 2.5 to 2.6.1. recently (iOS). On the simulator everything works fine, but when I try to compile on my iPhone I get several errors related to Eigen. The first being in `Block.h` on line 14

> Unknown type name 'namespace'

After googling around for hours I assume this must be related to a specific configuration on my end but unfortunately no solution in sight. Maybe someone else has come across the same issue - any pointers highly appreciated.

Many thanks!

**Comment by mousebird** [comment]
Is this using the podspec?

**Comment by tobihann** [comment]
I'm using CocoaPods

I have checked out the latest development branch in order to benefit from the latest font fix (https://github.com/mousebird/WhirlyGlobe/commit/087f3b133d8a79a6c007bfc8550243b2155014d8)

**Comment by mousebird** [comment]
Sometimes projects using Cocoapods will set a flag that recursively searches all the include directories.  In this case header files with the same name will be included in the wrong places.
You typically have to turn this off to fix the problem.
