### ISSUE TITLE
MaplyQuadImageTilesLayer fade and reload()

### ISSUE THREAD

**Issue by MBLRN** [mousebird/WhirlyGlobe#1204]
Hi there

Is there an equivalent of MaplyQuadImageTilesLayer fade and reload() in the new MaplyRemoteTileInfoNew, MaplySamplingParams and MaplyQuadImageLoader method. I’m using the new method to fix the low polygon globe issue (https://github.com/mousebird/WhirlyGlobe/issues/1150) but can’t work out how to fade a layer or get it to reload. Typically when I’ve used MaplyQuadImageTilesLayer:reload() only a subset of the tiles have changed so (superficially) there wouldn’t be a need to re-render all the tiles.

Cheers!

**Comment by MBLRN** [comment]
Thanks.
I'm not on support. What is it?

**Comment by mousebird** [comment]
It's a yearly contract for maintenance of the toolkit.  Support customers get first crack at my time for fixing bugs.  If you have an app with revenue, it's something you should consider.

In this case, I'd look at moving reload back into 2.6.

**Comment by paulgee31** [comment]
We can definitely recommend the support contract, we had this for a number of years now and it has been invaluable in ensuring quick responses to technical issues and fixing bugs.

**Comment by MBLRN** [comment]
Unfortunately I don’t have an app with revenue but hopefully that will change soon. I’ve solved the problem using the older method for the layers needing reload, then the newer method for layers that don’t.
Thank you for your help.
