### ISSUE TITLE
MaplyScreenLable showing wrong text on iOS 13

### ISSUE THREAD

**Issue by Vaibhavk11** [mousebird/WhirlyGlobe#1205]
Hi @mousebird ,
MaplyScreenLable shows the incorrect text on the new iPadOS. 
on previous iPad version is working fine, please have a look into the attached file. 

The following screenshot is from the new version of the iPadOS (13.1.3) .
![Screenshot 2019-10-18 at 4 54 59 PM](https://user-images.githubusercontent.com/18654253/67091191-a924ea00-f1c9-11e9-8b09-6ff02710ef9c.png)

And this is one from the previous version 12.2

![Screenshot 2019-10-18 at 4 54 27 PM](https://user-images.githubusercontent.com/18654253/67091324-f99c4780-f1c9-11e9-92f2-7ddaf243e773.png)

Here is the following code which we are using.

 ```
let label = MaplyScreenLabel()
label.layoutImportance = 0.0
label.text = strStateName
label.loc = vectorObj.center()
label.selectable = false
globeController.addScreenLabels([label], desc: [kMaplyFont: UIFont.systemFont(ofSize: 12.0), kMaplyTextOutlineColor: UIColor.black, kMaplyTextOutlineSize: 2.0, kMaplyColor: UIColor.white, kMaplyDrawPriority: 0])
```

Thanks

**Comment by mousebird** [comment]
You should join the mailing list, where I make announcements about things like this.  Scroll to the bottom:  https://mousebird.github.io/WhirlyGlobe/

In any case, this is fixed in both the master and develop branches of 2.6.
