### ISSUE TITLE
Garbled code in xcode11.1

### ISSUE THREAD

**Issue by zzjiong** [mousebird/WhirlyGlobe#1206]
MaplyScreenLabel text is garbled code in xcode11.1
<img width="689" alt="图片" src="https://user-images.githubusercontent.com/15756920/67171939-ef599380-f3eb-11e9-9677-d4a00b436292.png">

**Comment by mousebird** [comment]
Join the mailing list.  That's where I announce things like this.
Scroll to the bottom:  https://mousebird.github.io/WhirlyGlobe/

And the fix is already on the develop branch.
