### ISSUE TITLE
Screenlabel shows confusion in xcode11

### ISSUE THREAD

**Issue by zzjiong** [mousebird/WhirlyGlobe#1207]
Hi，
I asked before about MaplyScreenLabel text is garbled code in xcode11.1. I updated the latest file FontTextureManager.mm. The garbled problem has been solved. But now there is a problem of screenlabel shows confusion.
<img width="762" alt="图片" src="https://user-images.githubusercontent.com/15756920/67273139-74c66c00-f4f0-11e9-9d28-52ef2bfce1e6.png">
<img width="778" alt="图片" src="https://user-images.githubusercontent.com/15756920/67273204-9293d100-f4f0-11e9-8aeb-6f9a4f712aa1.png">
The first picture is normal, and the second picture is marked with a red frame.
I hope I can get your help, thank you.

**Comment by mousebird** [comment]
Ah, it looks like a glyph problem.  
Are you on support?

**Comment by zzjiong** [comment]
How can I on support?

**Comment by mousebird** [comment]
Email me at contact@mousebirdconsulting.com for pricing.

The issue here is that there's obviously something wrong with the glyph selection.  None of my support customers are running into this problem, so it's a low priority.

**Comment by zzjiong** [comment]
OK, Thank you！

**Comment by xieytt** [comment]
@zzjiong  你好，你这个乱码的问题解决了吗？

**Comment by zzjiong** [comment]
> @zzjiong 你好，你这个乱码的问题解决了吗？

解决了

**Comment by xieytt** [comment]
@zzjiong  怎么解决的啊？更新最新版本？

**Comment by zzjiong** [comment]
> @zzjiong 怎么解决的啊？更新最新版本？

加微信沟通吧 微信号jiong668

**Comment by zzjiong** [comment]
在最新代码已经解决

**Comment by mousebird** [comment]
Oh yeah, this is fixed now.
