### ISSUE TITLE
[IOS] Wide Vectors texture

### ISSUE THREAD

**Issue by llvinhll** [mousebird/WhirlyGlobe#1210]
I've tried a bunch of different images(triangles, circles, etc) for the texture for a wide vector. And it pretty much always ends up being a dashed line or some flavor of it. Is this just a limitation of the texture or is there a special way in which I need to make the texture image? Also it seems like the texture image size plays in effect in the appearance, ie if its too big it doesn't appear at all.

**Comment by mousebird** [comment]
It's not likely to work or symbols.  Textures on wide vectors are really just meant or dots and dashes.

**Comment by LiuYanli** [comment]
If using a custom image to draw a dashed line or a special line ,  Which way should I do?

Thank you in-advance

**Comment by llvinhll** [comment]
if you are doing dashed lines, you probably want to use wide vectors and use the maplylinearTextureBuilder to generated the dash line image. the autotest example should have a wide vector case in it to model after.

**Comment by mousebird** [comment]
Recently fixed this for a support customer.
