### ISSUE TITLE
Attach IGeoPackageVectorLayer to a VectorObject like it is doable with ScreenMarkers.userObject

### ISSUE THREAD

**Issue by breezyS** [mousebird/WhirlyGlobe#1211]
I made the features on the map selectable and I want to obtain the information that is in the features IGeoPackageVectorLayer object when I click it. 
With the ScreenMarkers I could just put it in its userObject but I can't seem to find a solution for the vectorObjects.

Is there a workaround? I am working on Android.

**Comment by mousebird** [comment]
Vector Objects do have attributes.  You could put something on one of those.
