### ISSUE TITLE
[Android] Unable to render NASA Remote Tiles appropriately

### ISSUE THREAD

**Issue by ARomina** [mousebird/WhirlyGlobe#1212]
Hi! I've followed the steps mentioned in the tutorial, but they are for iOS; I thought that it would would work for Android as well, but I'm unable to render the map tiles correctly. I'm quite new to the SDK. I'm also working on Kotlin (yeap, I've also encountered the Illegal Access Exception mentioned in another issue haha) Am I missing something to config?

Here's the tutorial: https://mousebird.github.io/WhirlyGlobe/tutorial/ios/remote_NASA_image_layers.html
Here's the map I'm trying to render: http://map1.vis.earthdata.nasa.gov/wmts-webmerc/VIIRS_CityLights_2012/default/2015-07-01/GoogleMapsCompatible_Level8/{z}/{y}/{x}
Here's a screenshot: https://ibb.co/KXQmNHZ

**Comment by mousebird** [comment]
The NASA Image URLs can move around a bit.  I know the dark layer moved.
Were you able to get the AutoTester running?

**Comment by ARomina** [comment]
Yes, I've been able to compile the AutoTester after migrating to AndroidX, and I can see some maps in the app; some of them update a bit when spinning the globe, but none leaves empty black areas like in my case with the NASA one. The Stamen ones render and behave perfectly.

**Comment by mousebird** [comment]
The NASA maps are often missing level 0, which can cause gaps.
How are you setting up the remote tile source?
