### ISSUE TITLE
AutoTester crash on xcode11 running on device iPad iOS12!

### ISSUE THREAD

**Issue by zzjiong** [mousebird/WhirlyGlobe#1214]
AutoTester crash on xcode11 running on device iPad iOS12,iOS13 is OK!
<img width="1277" alt="图片" src="https://user-images.githubusercontent.com/15756920/68747441-830e3080-0635-11ea-94c4-0faa835653c1.png">

**Comment by mousebird** [comment]
That's an error in the Metal Validation Layer. You'll need to turn validation of on the scheme under Options->Metal API Validation.
