### ISSUE TITLE
[iOS] Duplicate of MapboxVectorStyleSymbol.h

### ISSUE THREAD

**Issue by Alex0072005** [mousebird/WhirlyGlobe#1215]
When I installed WhirlyGlobe via command 

```pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe.git'```

I received many compile errors. 
Reason of errors were duplicate files `MapboxVectorStyleSymbol.h`and `MapboxVectorStyleSymbol 2.h`

**Comment by mousebird** [comment]
Should be fixed on develop.  Try that one.

**Comment by Alex0072005** [comment]
@mousebird Yes. Thanks 

```pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe.git', :branch => 'develop'``` 

works correct
