### ISSUE TITLE
Can I customize the style of MaplyBasicClusterGenerator?

### ISSUE THREAD

**Issue by yangjing901** [mousebird/WhirlyGlobe#1216]
Can I customize the style of MaplyBasicClusterGenerator?

**Comment by mousebird** [comment]
Yes, you'll see the BasicClusterGenerator inherits from a superclass.  Just use the Basic example as a guide.

You will need to register the cluster generator with a particular index (say, 2) and then use that cluster ID when adding labels and markers.

Be sure to grab a recent version of the toolkit.  There have been some updates to clustering on iOS.
