### ISSUE TITLE
[iOS] Adding pan gesture to screen markers

### ISSUE THREAD

**Issue by jaredrada** [mousebird/WhirlyGlobe#1217]
Thanks for a great framework!

I have a requirement to add a pan gesture to a screen marker, I understand I'll need to implement this on my own and rapidly add/remove screen markers. Following [this thread](https://github.com/mousebird/WhirlyGlobe/issues/1089) I've added a long press gesture. My idea is to use the ```geocPointFromScreen``` method to find the position of the gesture but I'm not sure how to convert this location into something usable for ```MaplyScreenMarker```? I was looking at using  ```MaplyCoordinateMakeWithDegrees``` but it expects degrees rather than the geocentric coordinate/meters given from the  ```geocPointFromScreen``` method.

My other question is how to use the ```ThreadCurrent``` mode... is this a setting on the ```MaplyScreenMarker``` itself?

**Comment by mousebird** [comment]
geoPointFromScreen is the one you want, though it can be annoying to access from Swift.

You apply the mode (ThreadCurrent) when you call addScreenMarkers.

**Comment by jaredrada** [comment]
Thank you! I was able to achieve this effect but the rendering rate seems to be slow. Something seems to be blocking the removing & adding actions. I did indeed use the ```mode: .current``` setting.

![out](https://user-images.githubusercontent.com/526082/71765806-aaaba780-2ec6-11ea-972a-9981b973307b.gif)

If anyone runs in this same requirement, heres' my code

```Swift
var mutableGeoCoord = MaplyCoordinate(x: 0, y: 0)

// location variable is the long press gesture sender
 _ = theViewC?.geoPoint(fromScreen: CGPoint(x: location.x, y: location.y), geoCoord: &mutableGeoCoord)
              
// radians to degrees is: radians * 180 / pi = degrees
let gestureLocation = MaplyCoordinateMakeWithDegrees(
  radiansToDegrees(radian: mutableGeoCoord.x),
  radiansToDegrees(radian: mutableGeoCoord.y)
)
                
let icon = UIImage(named: "circle-24")
let marker = MaplyScreenMarker()
marker.image = icon
marker.loc = gestureLocation
marker.size = CGSize(width: 20, height: 20)

theViewC?.remove([peg0Maply], mode: .current)
peg0Maply = theViewC?.addScreenMarkers([marker], desc: nil, mode: .current)
```

**Comment by mousebird** [comment]
Create a MaplyTexture once and use that instead of a UIImage.  The speed issue is likely converting the image each time.
