### ISSUE TITLE
[Android] mapController.heading behaviour

### ISSUE THREAD

**Issue by breezyS** [mousebird/WhirlyGlobe#1221]
Hi,

I am trying to understand the heading value as it seems kind of random. It seems dependent on the speed of the rotation and/or the zoomlevel because sometimes a full rotation equals 6, sometimes 12 and sometimes it goes negative, even tho to rotation direction stays the same. 

Sometimes the first rotation will be 12 and the second one 18 or 30.

I am trying to adjust a compass icon to the current heading, but this behaviour makes it kind of weird. What does the heading depend on and how would one get the heading change in degrees?

**Comment by mousebird** [comment]
Heading should be in radians 0 -> 2pi

**Comment by breezyS** [comment]
That makes sense, thanks! Although that does not explain the random jumps of the heading.
f.e.

2020-02-11 14:51:53.488 25176-25176/com.android.app D/heading: -0.22337654
2020-02-11 14:51:54.455 25176-25176/com.android.app D/heading: -0.6492568
2020-02-11 14:51:55.288 25176-25176/com.android.app D/heading: -1.2268202
2020-02-11 14:51:55.989 25176-25176/com.android.app D/heading: 4.15619

This happens every now and then when casually rotating the map which causes the spin animation on the icon to go a little wild.

**Comment by mousebird** [comment]
Ah, my explanation is too short.

It's best to interpret the heading as mod 2pi.  There may be a pi offset in there somewhere, I don't remember.
