### ISSUE TITLE
[Android] Failed to create image decoder with message 'unimplemented'

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe#1224]
Hello,

I have errors with OpenStreetMap tiles I don't have before.

`2020-03-09 11:36:49.950 18673-18730/com.mousebirdconsulting.autotester D/skia: --- Failed to create image decoder with message 'unimplemented'`

It is easy to reproduce, just change the StamenTestCase with this url:

https://c.tile.openstreetmap.org/{z}/{x}/{y}

Don't really understand why.

**Comment by NasH5169** [comment]
Extra info: I've the same with Whirly v3

2020-03-09 12:27:09.803 22124-22204/com.mousebirdconsulting.autotester D/Maply: MaplyQuadImageLoader: Merging data from tile 7: (86,56)
2020-03-09 12:27:09.803 22124-22253/com.mousebirdconsulting.autotester D/skia: --- Failed to create image decoder with message 'unimplemented'

**Comment by mousebird** [comment]
That tends to be old hardware.  Are you seeing something wrong with the resulting visual?

**Comment by NasH5169** [comment]
In fact, the result is just black screen.

My device is a basic but not very old Xiaomi MiA2 (Android 10), same with old Samsung Galaxy S5 (Android 9).

I've just test with theses other URLs:

https://b.tile.openstreetmap.fr/osmfr/{z}/{x}/{y} (OSM France) --> It's working!

Or

https://c.tile.opentopomap.org/{z}/{x}/{y} (Open Topo Map) --> It's working too...

If I put back the official OpenStreetMap URL, it fails with black screen and the log:

`--- Failed to create image decoder with message 'unimplemented'`

**Comment by mousebird** [comment]
https://c.tile.openstreetmap.org/{z}/{x}/{y} doesn't work for me, but https://c.tile.openstreetmap.org/{z}/{x}/{y}.png does

**Comment by NasH5169** [comment]
Yes.

Without extension is for WhirlyGlobe 2
With extension is for for WhirlyGlobe 3

However, as I said, I have the error

`--- Failed to create image decoder with message 'unimplemented'`

And black screen on the map.

![error](https://user-images.githubusercontent.com/6979479/76301207-2c9cc000-62be-11ea-845a-465017a38782.png)

**Comment by mousebird** [comment]
Are you on support?  I don't think so, but I should ask.
If you were on support, I'd dig in and fix this directly.  But if you're not, I'll point you to the code.

This problem has turned up on older versions of Android, typically, and possibly more obscure devices, but I'm not entirely clear on that.  It's an issue decoding images.  Specifically, we try to turn off the alpha pre-multiply, which isn't always supported.

The code itself is in ImageLoaderInterpreter (v3).  I'd step through around line 77 to see what happens in BitmapFactory.decodeByteArray.

**Comment by NasH5169** [comment]
Hi Steve,

Not on support but if this issue will take some importance for us, we'll renew our support (the support could help us too in order to move forward with the WhirlyGlobe v3 migration).

I'll take a look into the code. Thanks.

**Comment by NasH5169** [comment]
You are right, the error is the line 77 of ImageLoaderInterpreter.java

`Bitmap bm = BitmapFactory.decodeByteArray(image,0, image.length, options);`

returns null.

As many users (devices & android versions) have this issue and, as many other remotes maps like Google or OSM France works, I think something changed with the official OSM tiles PNG images or the OSM webserver...

Close the issue.

**Comment by austindouglasgriffith** [comment]
This was very helpful, thank you. 
I was encountering this issue, and had to search for a different tile resource for satellite Imagery. 
Ended up finding a great one that WhirlyGlobe was happy with; provided below.
https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
Good luck to all that find this!

**Comment by ivan-avalos** [comment]
I can confirm OpenStreetMap image tiles aren't working.

This is the URL I'm using: https://tile.openstreetmap.org/{z}/{x}/{y}.png

**Comment by mousebird** [comment]
Strange.  I wonder what OSM is doing with its PNGs.
Well, as with all bugs that aren't from support customers, we'll put this in the backlog and take a look when we've got some time.

**Comment by austindouglasgriffith** [comment]
@ivan-avalos, I also ran into this issue, but was able to get around it by using the following tile server: "http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}.png"
This was taken from [this](https://gist.github.com/Yago/05d479de169a21ba9fff) GitHub post, which includes a few more alternatives that WhirlyGlobe seems to be happy with. 
Hope this helps!
