### ISSUE TITLE
[iOS] inverting a vectorObject, to cover everything but a given other vecObject

### ISSUE THREAD

**Issue by Pryotic** [mousebird/WhirlyGlobe#1226]
Hello,

my problem is as described in the title. To give a little more context, I want to have a vector object that is representing the oceans and seas in my globe (so everything that is not countries), and I wanted to achieve that by get an vectorObject that covers the whole globe and "substracting" all country-vectorObjects.

My approach was to set up a vectorObject that covers the whole globe with the following geojson:

`{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
      [
        0,
        90
      ],
      [
        180,
        90
      ],
      [
        180,
        -90
      ],
      [
        0,
        -90
      ],
      [
        -180,
        -90
      ],
      [
        -180,
        0
      ],
      [
        -180,
        90
      ],
      [
        0,
        90
      ]
    ]
        ]
      }
    }
  ]
}`

but that crashes the app with error-message: `-[MaplyVectorObject loc]: unrecognized selector sent to instance 0x282ac8db0`
although it's working on geojson.io

Anyway, even if that would work, I wouldn't really know how to substract the country-vector-objects of the resulting vector-object. Maybe using `MaplyVectorObject.addHole()`, but this takes `(coords: UnsafeMutablePointer, numCoords: Int32)` as an input and not just an vector object.

Would be really thankful for any help.

**Comment by mousebird** [comment]
That's wild.  I'll take a look at the crash.

But in general, MaplyVectorObjects are set up to do topological operations.  If you know that nothing overlaps, then you could add the holes in as holes.  But if you're not sure, then you should do those operations in something like QGIS.  Or find a data set where they've already figured all that out, like Natural Earth.

**Comment by Pryotic** [comment]
Thank you, for answering. I think the problem was, that the GlobeViewController didn't create this big vector-object around the bending of the globes surface, but tried to do it straight through the globe. Anyway, I kinda fixed my problem with a workaround, using a .geojson that contained a lot of smaller vectorObjects covering the whole globe.
