### ISSUE TITLE
How to draw an ellipse

### ISSUE THREAD

**Issue by xuehuawanlipiao** [mousebird/WhirlyGlobe#1227]
I want draw an ellipse with centor location ,long axis,short axis,angle from north.the I can’t found an sdk method from whirlyglobe layers.Sou I calculate the 360 points around the ellipse.If the axis is long it works well.But when the long axis and short axis under 10 meters,the points draw at wrong position.But it draw at MapKit From iOS works well.
How can I draw a good ellipse?
![mp](https://user-images.githubusercontent.com/7851130/77053646-9e38e480-6a09-11ea-88d8-caafc32b2d43.png)
![wg1](https://user-images.githubusercontent.com/7851130/77053713-b6106880-6a09-11ea-91e2-e9c6d6ac79b9.png)
![wg3](https://user-images.githubusercontent.com/7851130/77054252-801fb400-6a0a-11ea-9f09-88ae2463a24e.png)

Ellipse Data link
[https://github.com/xuehuawanlipiao/EllipseData/blob/master/ellipse.json](url)

**Comment by mousebird** [comment]
I can think of a couple of reasons.
If the ellipse is under 10m you might need to use a center or create it with doubles, rather than floats.
If it's just the rendering, then you might want to use Wide Vectors rather than regular vectors.

**Comment by xuehuawanlipiao** [comment]
Wide vectors work better than regular vectors.But it cant
I found MaplyCoordinateD is double .But vector and marker ,sticker doesn't have this property.
When I draw small sticker in 5 meters it can be obscure.
How can I use MaplyCoordinateD to draw a Better sticker or vector?

**Comment by mousebird** [comment]
Stickers aren't meant for that level of precision.
Did you ask this in another Issue?

**Comment by xuehuawanlipiao** [comment]
yes,I'll try it
