### ISSUE TITLE
Draw questions using MaplySticker

### ISSUE THREAD

**Issue by LiuYanli** [mousebird/WhirlyGlobe#1228]
Hello,

  Draw a MaplyBoundingBox based on coordinates，Then use MaplySticker to load the image。
  But the drawn image is offset，what is causing the drawing problem？

  Would be really thankful for any help.

Used image： 
<img width="254" alt="image" src="https://user-images.githubusercontent.com/5698159/77150439-da824880-6ace-11ea-8b2b-017e7b290107.png">

results：
<img width="428" alt="image" src="https://user-images.githubusercontent.com/5698159/77150497-fd146180-6ace-11ea-83e8-1e05cb728a0b.png">

**Comment by mousebird** [comment]
Stickers aren't really designed for that level of precision.
For building things like runways, we try to use the geometry builder.  Take a look at the runway example in the AutoTester app.
