### ISSUE TITLE
wide vector zoom blinking

### ISSUE THREAD

**Issue by xuehuawanlipiao** [mousebird/WhirlyGlobe#1229]
Hello 
I draw wide vector using texture.Then I set  globeview  ViewState  tilt to 1.0
when I zoom the map to little scale ,the screen become blinking.
How can I fix it?
![WX20200325-173926](https://user-images.githubusercontent.com/7851130/77522707-9ffa2080-6ebf-11ea-9585-6243ce35181d.png)

**Comment by mousebird** [comment]
What version is this?
And are you a support user?

**Comment by xuehuawanlipiao** [comment]
I use it from tag 2.6.2.
And what the support user mean?

**Comment by mousebird** [comment]
Support refers to customers who pay a yearly support fee.  I answer their questions and fix their bugs first.
It looks like there's a bug in wide vectors for off-axis use cases.  I don't know when I'll get to that, but good to know.
