### ISSUE TITLE
How to draw the earth's surface with mountain heights and ocean levels

### ISSUE THREAD

**Issue by xuehuawanlipiao** [mousebird/WhirlyGlobe#1230]
like this
![1585150493244](https://user-images.githubusercontent.com/7851130/77554826-85d93600-6ef1-11ea-9f96-2074b6be5aa6.jpg)

**Comment by mousebird** [comment]
Cool picture.
This wouldn't be easy.  You'd need all the data to support that, a custom shader to get the lighting right and you'd need to feed the elevation in to the right place.
It's something I could do, but I don't think I could describe it to another developer at this point.

**Comment by xuehuawanlipiao** [comment]
Got it.
Then the picture come from echarts.
https://www.echartsjs.com/examples/zh/editor.html?c=globe-layers&gl=1
