### ISSUE TITLE
[iOS] issue with displaying wideVectors

### ISSUE THREAD

**Issue by Pryotic** [mousebird/WhirlyGlobe#1232]
Good morning,

I'm working on a globe. I set up the sea/ country-borders with wideVectors, as shown in the picture below.
It's not really a big problem, but in some spots there are gaps occuring between the lines of the wideVectors. 

![IMG_581B8A92F36C-1](https://user-images.githubusercontent.com/48635754/77847385-f9629800-71bc-11ea-81d0-d22c16fb618b.jpeg)

Here is my code to add the wideVectors:

```

wideVectorDict[kMaplyDrawPriority] = (kMaplyVectorDrawPriorityDefault - 2) as AnyObject
wideVectorDict[kMaplyFilled] = false as AnyObject
wideVectorDict[kMaplyColor] = borderColor
wideVectorDict[kMaplyEnable] = true as AnyObject
wideVectorDict[kMaplyVecWidth] = borderWidht as AnyObject
// wideVectorDict[kMaplyWideVecJoinType] = kMaplyWideVecBevelJoin as AnyObject
wideVectorDict[kMaplyWideVecJoinType] = kMaplyWideVecMiterJoin as AnyObject
wideVectorDict[kMaplyWideVecMiterLimit] = 10 as AnyObject
wideVectorDict[kMaplyWideVecEdgeFalloff] = 3 as AnyObject
wideVectorDict[kMaplyVecCentered] = true as AnyObject
wideVectorDict[kMaplyWideVecCoordType] = kMaplyWideVecCoordTypeScreen as AnyObject

GlobeView.addWideVectors([vectorObj], desc: wideVectorDict, mode: MaplyThreadMode.current)!
```

I would appreciate any help there.

**Comment by mousebird** [comment]
Are these lines or areal features?

**Comment by Pryotic** [comment]
I'm using a geojson file, that contains polygons. I guess those are areal features, although since `kMaplyFilled` is set on false, only lines are drawn.
I hope that answers the question.

**Comment by mousebird** [comment]
Could be a bug, then.  Do the problems remain as you zoom in or go away?

**Comment by Pryotic** [comment]
they remain. Do you have an idea what the cause could be?

**Comment by mousebird** [comment]
Probably something not being handled well in the data.  For example, a duplicated vertex or two very close together.
