### ISSUE TITLE
animatePositionGeo for globeControl

### ISSUE THREAD

**Issue by gregcabrera422** [mousebird/WhirlyGlobe#1233]
I used lat and long for animatePositionGeo but it seems like its going to an inaccurate position, is there a way that I can use lat long for animatePositionGeo using globeControl? 

NOTE: I used the same lat long for labels and it went to the right point on the globe.

**Comment by mousebird** [comment]
The order is: longitude, latitude and it needs to be in radians.
Easiest to use the MaplyCoordinate constructor that takes lon/lat in degrees and let it do that.

**Comment by gregcabrera422** [comment]
Thank you for the response. I'm using version 2.5 of library in Android, it seems like MaplyCoordinate is missing. Sorry for the late reply.

**Comment by mousebird** [comment]
Ah, for Android it's just Point2d, but there is a constructor that takes degrees and has the lon/lat ordering.

**Comment by gregcabrera422** [comment]
Already fixed my issue, I'm sorry for the confusion I think I was using animatePositionGeo wrong. As stated in the API I had to use radians for latitude and longitude, so I actually had to convert both the coordinates using * PI / 180 first. Thank you for the response.
