### ISSUE TITLE
MaplyShapeLinear clipping just above the horizon

### ISSUE THREAD

**Issue by 696GrocuttT** [mousebird/WhirlyGlobe#1236]
I've got an issue with MaplyShapeLinear not displaying properly when its above the horizon. However other shapes behave correctly. EG the code below should display a red ball at the end of a vertical line: 
```
let s = MaplyShapeSphere()
s.radius = 100 / 6371000
s.height = 3000 / 6371000
s.color  = .red
s.center = MaplyCoordinateMakeWithDegrees(Float(jump.dzCoordinate!.longitude),
                                          Float(jump.dzCoordinate!.latitude))

var lineCoords = [ MaplyCoordinate3d(x: s.center.x, y: s.center.y, z: 0),
                   MaplyCoordinate3d(x: s.center.x, y: s.center.y, z: s.height) ]
let line = MaplyShapeLinear(coords: &lineCoords, numCoords: Int32(lineCoords.count))
line?.color = .yellow
line?.lineWidth = 10
addShapes([s, line], desc: nil)
```

If the view is tilted so everything is below the horizon, everything is displayed correctly and we get the screen shot below:
![IMG_0359](https://user-images.githubusercontent.com/48135139/82799261-abdb7200-9e71-11ea-8ddc-96aeae83c17f.jpg)

However if I change the tilt/zoom the top part of the MaplyShapeLinear disappears, as show below:
![IMG_0360](https://user-images.githubusercontent.com/48135139/82799256-a847eb00-9e71-11ea-9360-e5287347c1aa.jpg)
As I change the tilt / zoom / pan the point at which the line disappears stays just above the horizon.

This is a really cool framework, but my app will displays the flight paths of skydivers, so the line disappearing is a bit of a show stopper for me. Any idea what could be causing this?

Thanks

Tom

**Comment by 696GrocuttT** [comment]
I've been doing a bit more digging and found something (possibly) interesting. The point at which the line disappears in just above the horizon for v2.6.1 and later. However if I step back to v2.6.0 the point at which it disappears  is slightly below the horizon. Not sure if this helps narrow it down, but thought I'd mention it.

Tom

**Comment by mousebird** [comment]
Can you make a video of that?

**Comment by 696GrocuttT** [comment]
You can download the video here:
https://www.icloud.com/photos/#0WeudgBtncCTe6rG5-6GV1T0Q

**Comment by mousebird** [comment]
Looks like z buffer weirdness.  Try setting the kMaplyZBufferRead to false for the addShapes call.

**Comment by 696GrocuttT** [comment]
Just tried that, but unfortunately it doesn't fix the problem.

**Comment by 696GrocuttT** [comment]
Disabling the Z buffer reads did change the rendering slightly, as the yellow line in now being rendered on top of the red ball (when its below the horizon).

![IMG_0366](https://user-images.githubusercontent.com/48135139/82942675-3adeac00-9f90-11ea-9729-a9a2467d8344.jpg)

But its still clipping the line when above the horizon.
![IMG_0367](https://user-images.githubusercontent.com/48135139/82942663-374b2500-9f90-11ea-9cb8-c58166fe109a.jpg)

I've also tried playing around with the drawing priority, but that didn't fix it either.

**Comment by mousebird** [comment]
Are you drawing anything in the background?

**Comment by mousebird** [comment]
So this is probably the shader.  By default the globe will use a shader that fixes backface problems on the globe with lines and other random stuff.

You probably want a shader that doesn't do that.
If you put kMaplyShader: kMaplyNoBackfaceLineShader in the description dictionary.
That might do it.

**Comment by 696GrocuttT** [comment]
Adding kMaplyNoBackfaceLineShader fixed it :-)

Thanks for your help!!
