### ISSUE TITLE
[iOS] issue with displaying Vectors

### ISSUE THREAD

**Issue by ForTraces** [mousebird/WhirlyGlobe#1238]
kMaplyFilled: YES addVectors （As you rotate the earth around the poles, lines will enter the earth） thanks
<img width="447" alt="图片" src="https://user-images.githubusercontent.com/8295724/84143301-e99ee400-aa88-11ea-903b-5d0d0855c339.png">

**Comment by mousebird** [comment]
Displaying flat polygons on the globe is always going to be tricky.  What you need to do is break them up into smaller pieces.

Take a look at TextureVectorTestCase in the AutoTester app.  Start around line 62 or so and follow the explanation of breaking up large areal features.

**Comment by ForTraces** [comment]
As you said, new problems have arisen. The figure appears to circle the earth. Thanks
<img width="596" alt="图片" src="https://user-images.githubusercontent.com/8295724/84251087-71dfc080-ab3f-11ea-825f-655509e85a7e.png">

**Comment by ForTraces** [comment]
Same data  Adding split code is not the same as not adding draw code
1.Adding split code
![1591837629945](https://user-images.githubusercontent.com/8295724/84333735-338be500-abc3-11ea-9cc7-965a003b0afd.jpg)
2. No split code
<img width="564" alt="图片" src="https://user-images.githubusercontent.com/8295724/84333933-abf2a600-abc3-11ea-83a5-3f0df468a409.png">

**Comment by ForTraces** [comment]
This is the code,Please look at it for me. thanks
 <img width="677" alt="图片" src="https://user-images.githubusercontent.com/8295724/84334043-f1af6e80-abc3-11ea-9aeb-5bfbaa2282ee.png">
<img width="698" alt="图片" src="https://user-images.githubusercontent.com/8295724/84334108-17d50e80-abc4-11ea-9016-892d0f0cd5eb.png">

**Comment by ForTraces** [comment]
I want to fill the polygon with color

**Comment by mousebird** [comment]
Try displaying just the outlines to see what your polygons look like.  There may be something odd about your data.

By the way, you have an open issue here.  You don't need to send me the exact same questions by email.  Unless you're support, of course, then you're welcome to.
