### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by vvaleed** [mousebird/WhirlyGlobe#1240]
Hi Steve,
I hope you are doing well. I am facing a small memory leak problem. What I am trying to achieve is to move objects over time. This is done by removing the the objects and re-adding them. I do this every 3 seconds and see a 1 mb jump in 3 seconds.
<img width="988" alt="Screenshot 2020-07-24 at 5 55 51 AM" src="https://user-images.githubusercontent.com/10007144/88455450-ce4c3480-ce8e-11ea-8168-2d5ab044781d.png">
I use the following to remove the objects

```
if (TanLines) {
        [globeViewC removeObjects:TanLines mode:MaplyThreadCurrent];
        
        if([TanLines count]>0){
            [TanLines removeAllObjects];
            TanLines=nil;
        }
    }
```

Add push them into and array to create them
`[TanLines addObject:[globeViewC addWideVectors:@[vfuel] desc:@{ kMaplyColor: [UIColor blueColor], kMaplyEnable: @(YES), kMaplyVecWidth: @(6.0), } mode:MaplyThreadCurrent]  ];`

I am using the Metal June-2019 "Stable-3". 
What stable Metal branch do you recommend?

**Comment by mousebird** [comment]
Might as well update to the current develop branch and see if that still happens.
