### ISSUE TITLE
LableInfo.setBackgroundColor(), this method doesn't seem to work?

### ISSUE THREAD

**Issue by 1e0Messi** [mousebird/WhirlyGlobe#1241]
Hi mousebird ,I try to use LableInfo.setBackgroundColor() ,like that
` labelInfo = new LabelInfo();
            labelInfo.setFontSize(20f);
            labelInfo.setTextColor(Color.YELLOW);
            labelInfo.setTypeface(Typeface.DEFAULT);
            labelInfo.setLayoutPlacement(LabelInfo.LayoutAbove | LabelInfo.LayoutCenter);
            labelInfo.setTextJustify(LabelInfo.TextJustify.TextCenter);
            labelInfo.setMinVis(0.f);
            labelInfo.setMaxVis(0.03f);
            labelInfo.setOutlineColor(Color.WHITE);
            labelInfo.setOutlineSize(1.5f);
            labelInfo.setBackgroundColor(Color.BLACK);`
Did I do something wrong？ Thank you！

**Comment by mousebird** [comment]
What version of the toolkit is this?

**Comment by 1e0Messi** [comment]
> What version of the toolkit is this?

I use 2.6.2 version

**Comment by mousebird** [comment]
I believe I fixed a bug in setBackgroundColor() a few months ago.  If not in 2.x it should be working in 3.0.

**Comment by 1e0Messi** [comment]
> I believe I fixed a bug in setBackgroundColor() a few months ago. If not in 2.x it should be working in 3.0.

where to get 3.0 version? I find that the Latest version is v2.6.5 in github souce code tag

**Comment by 1e0Messi** [comment]
I find it in another  repository,I will try to use.Thanks  to your answer

**Comment by mousebird** [comment]
Fixed in 3.0
