### ISSUE TITLE
SLD dash patter issue

### ISSUE THREAD

**Issue by wim-bo** [mousebird/WhirlyGlobe#1243]
There is a mixup in the variable to assign the index in the array and the dash pattern itself.

https://github.com/mousebird/WhirlyGlobe/blob/23990cc4ff511d5232e88b29dcb8d5510c36aa94/android/library/maply/src/main/java/com/mousebird/maply/sld/sldsymbolizers/SLDSymbolizer.java#L165

**Comment by mousebird** [comment]
Nice catch, thanks.
