### ISSUE TITLE
Error installing eigen

### ISSUE THREAD

**Issue by NPasini** [mousebird/WhirlyGlobe#1245]
When I try to install the _WhirlyGlobe_ Pod using CocoaPods I get the following error message when the installation of _eigen_ is prompted:

> Installing eigen (3.2.10)
>
> [!] Error installing eigen
> [!] /usr/local/bin/hg clone https://bitbucket.org/eigen/eigen --rev 3.2.10 /var/folders/sg/8hzsvn9d0hgdmdwx71v045480000gp/T/d20200825-54356-1kh5btl
> 
> abort: http authorization required for https://bitbucket.org/eigen/eigen

I then tried to open the bitbucket repository which is supposed to host the _eigen_ project, but found it empty. 
[Eigen official page](http://eigen.tuxfamily.org/index.php?title=Main_Page) says that now the project is now hosted on GitLab.

**Comment by mousebird** [comment]
Use the Podspec in the WhirlyGlobe repo on github.

**Comment by NPasini** [comment]
I have followed the [tutorial](http://mousebird.github.io/WhirlyGlobe/tutorial/ios/building_from_cocoapod.html). Can you clarify how should I use the Podspec in the WhirlyGlobe github repo?

**Comment by mousebird** [comment]
It's best to use the podpsec from the repo directly:
https://github.com/mousebird/WhirlyGlobe-3/blob/master/WhirlyGlobe.podspec

**Comment by Tillmania** [comment]
Having the same issue. Even when specifying the source in the Podfile

`source = { :git => 'https://github.com/mousebird/WhirlyGlobe-3.git', :branch => 'develop' }`

**Comment by mousebird** [comment]
I'm using it on a project within a target like so:
pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe-3.git', :branch => 'develop'

One wrinkle is that eigen uses hg, so make sure you have hg installed.

**Comment by Tillmania** [comment]
Is hg the same as mercurial? If so then that is installed already....

**Comment by mousebird** [comment]
It would appear the eigen project pulled their old repo and isn't updating their Cocoapod.
I suggest just using the WhirlyGlobe-3 submodule for now.  It includes all the utility libraries as source.

**Comment by Tillmania** [comment]
So no cocoa pods? Just download the submodule and add that to my project?

**Comment by mousebird** [comment]
Yes, there's another tutorial for that approach, though all the tutorials are out of date.
The Eigen pod will have to be fixed eventually because I have customers using it, but I can't say when.

**Comment by Tillmania** [comment]
Yeah I noticed the tutorials are out of date. Any chance of a quick getting
started guide? I’m happy to pay.

**Comment by danielrotaermel** [comment]
Hi, just noticed that our app suddenly stopped building due to this. 
As per eigens website there is no mention that the bitbucket instance should get deleted rather be usable as an archive.
> The old mercurial repository is still readable on bitbucket.org, but it is not synchronized with the git repository, meaning that it should be used for archive purposes only. 
http://eigen.tuxfamily.org/index.php?title=News:Eigen_is_now_on_GitLab.com
 
Is there any way to update eigens podspecs?
Or is it maybe possible to change WhirlyGlobes podspec to use eigen from another source? Maybe just the one from the common/local_libs/?

**Comment by mousebird** [comment]
This is what I hate about Cocoapods.
But I'll have this fixed shortly.  Just have to sort out the pathing issue to local_libs.

**Comment by mousebird** [comment]
Should be fixed on both WhirlyGlobe and WhirlyGlobe-3 develop branches.

**Comment by danielrotaermel** [comment]
Thanks for the quick response! Just tried to use WhirlyGlobe-3 but I'm getting this error
```
/Users/ezekills/Git/iOS/Pods/WhirlyGlobe/ios/library/WhirlyGlobe-MaplyComponent/include/GlobeTapMessage.h:22:9: 
Include of non-modular header inside framework module 
'WhirlyGlobe.GlobeTapMessage': '/Users/ezekills/Git/iOS/Pods/WhirlyGlobe/common/WhirlyGlobeLib/include/WhirlyVector.h'
``` 
Podfile:
```
pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe-3', :branch => 'develop' 
```

**Comment by mousebird** [comment]
I tried to clean up the podspec a bit which was a mistake.
I've dropped back to the minimum change necessary to pull in the local version of Eigen.
Let me know if it works for you.

**Comment by danielrotaermel** [comment]
I just tried it and get these 2

<img width="678" alt="Screenshot 2020-09-14 at 11 27 18" src="https://user-images.githubusercontent.com/10634154/93068929-5ecc1780-f67d-11ea-8b5a-6e36f704f0c3.png">
<img width="661" alt="Screenshot 2020-09-14 at 11 27 11" src="https://user-images.githubusercontent.com/10634154/93068947-61c70800-f67d-11ea-8ffe-2d3581d22cb5.png">


The header is there though.

<img width="681" alt="Screenshot 2020-09-14 at 11 29 24" src="https://user-images.githubusercontent.com/10634154/93069198-aeaade80-f67d-11ea-86ca-f73fc6daf2ae.png">

I tried to move WhirlyVector.h into public but then the "non-modular header inside framework module" error appears again.

<img width="1108" alt="Screenshot 2020-09-14 at 11 33 31" src="https://user-images.githubusercontent.com/10634154/93069589-224ceb80-f67e-11ea-9a22-f6232e6b20e6.png">

Also tried to change the build settings of whirlyglobe according to this https://stackoverflow.com/a/28552525/8472592 but without it stayed without any effect.
<img width="723" alt="Screenshot 2020-09-14 at 11 36 42" src="https://user-images.githubusercontent.com/10634154/93070943-c8e5bc00-f67f-11ea-899c-dbb51bcab0df.png">

**Comment by mousebird** [comment]
I went down that rabbit hole with Cocoapods and it didn't lead anywhere good.  So I backed out most of my changes and went with the simplest changes to the Podspec that pulled in eigen.  That's what's in the develop branches of both WhirlyGlobe and WhirlyGlobe-3.  However, it looks like there are multiple ways to get into this mess with Cocoapods.

I just set up a new project to test this and it's working for me, which is the least useful answer.

Here's the Podfile I used to set things up:

```
platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false
project 'PodTest2.xcodeproj'
inhibit_all_warnings!

target 'PodTest2' do
  pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe-3.git', :branch => 'develop'

end

```

Then I had to add a bridging header and pull in WhirlyGlobeComponent.h.  Once that's in place I can just use it in a swift module like so.

```
import UIKit

class ViewController: UIViewController {
    
    var viewC: WhirlyGlobeViewController? = nil

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        viewC = WhirlyGlobeViewController()
    }


}


```

The same thing should work with the WhirlyGlobe repo as well.
