### ISSUE TITLE
Unable to compile Android library into .AAR

### ISSUE THREAD

**Issue by austindouglasgriffith** [mousebird/WhirlyGlobe#1248]
Hello WhirlyGlobe Team! I am trying to compile the Android library into an .AAR from terminal using the instructions found [here](https://mousebird.github.io/WhirlyGlobe/tutorial/android/building-from-source.html).
But I'm met with exactly the same error encountered by @HuWenHao92 [here](https://github.com/mousebird/WhirlyGlobe/issues/1180) and @gulguruth [here](https://github.com/mousebird/WhirlyGlobe/issues/396).

The specific error codes I am experiencing after executing "./gradlew assemble" are as follows:
`*** No rule to make target jni/../../../..//common/local_libs//proj-4/src//p_series.c', needed by obj/local/arm64-v8a/objs/Maply/__/__/__/__//common/local_libs//proj-4/src//p_series.o'. Stop.`
 and 
`ndk-build'' finished with non-zero exit value 2`

I've recorded a screencast of myself attempting to compile the library and posted it [here](https://youtu.be/rChpP3UjBy8), if you could review it and check for any errors in my process I would greatly appreciate it. 
I properly initialize my submodules, create the local.properties file, and have also attempted this process from scratch using each of the following NDK versions, downloaded from [here](https://developer.android.com/ndk/downloads/older_releases): r10e, r11c, r12b, r13b, r14b, r15c, r16c, r17c, r18b, r19c, r20b, and r21d. I've been at this for a while now :( 

Ultimately, I need to compile the library to try a larger value for the "nearPlane" parameter in MaplyView.cpp to resolve an issue I'm experiencing with Z buffering, visible [here](https://drive.google.com/file/d/1IfOHzR2d_VcBqOs3hGZKo6syEWNo2xxD/view?usp=sharing).
But I'll also need to compile the Android library to implement the fix for ShapeSpheres not triggering the userDidSelect method, ticketed [here](https://github.com/mousebird/WhirlyGlobe/issues/1244).

Your assistance would truly be appreciated: these two issues mentioned above are now the only items preventing me from publishing on Android, and I feel I've tried everything in my power to bring them to light.

For context, I have also thoroughly reviewed threads [1084](https://github.com/mousebird/WhirlyGlobe/issues/1084) and [987](https://github.com/mousebird/WhirlyGlobe/issues/987): each related to issues compiling the library. Unfortunately neither solved the issue described. 

Thank you for reading,
-Austin Griffith

**Comment by mousebird** [comment]
I'm afraid those instructions are very much out of date.
We're using the newer cmake based build system.

One trick you can use to force the library to build is to bring up the AutoTester project in Android Studio and make it build.  Then search for the .aar and grab that.

**Comment by austindouglasgriffith** [comment]
Thank you for your quick response!
I have now successfully built the AutoTesterAndroid app, and it works as expected. 

But after searching through the folder, I've found that this process did not generate the AAR file. 
Are you building it in any special way? I am simply deploying it to my device.

**Comment by mousebird** [comment]
It will make an aar file deep within one of the Build directories.  Under the library.

**Comment by austindouglasgriffith** [comment]
After building the project a second time and going through each file in the WhirlyGlobe folder, I can confirm that the AAR doesn't seem to be present. Is it supposed to be generated each time?

**Comment by mousebird** [comment]
When I build the AutoTester app in Android studio I'll get a maply-debug.aar in android/library/maply/build/outputs/aar

**Comment by austindouglasgriffith** [comment]
That's odd, my "outputs" folder only contains a "logs" folder. The "aar" one isn't there. 
Will try the whole process from scratch once more.

**Comment by mousebird** [comment]
Try just building the maply module.  That just worked for me.

**Comment by austindouglasgriffith** [comment]
`Build>Make Module 'maply'` created the .aar in the WhirlyGlobe/android/library/maply/build/outputs/aar folder, thank you so much!
I tossed it into my app and it does seem to be notably more sluggish compared to the 2.6 AAR provided [here](https://mousebird.github.io/WhirlyGlobe/builds/builds.html).
Is this because it is in debug mode? If so, how can I create a production .aar?

**Comment by mousebird** [comment]
That's the debug version.
In the Build Variants, you can change to release.

**Comment by austindouglasgriffith** [comment]
Switching the build variant created the maply-release.aar, which works beautifully! 
Thank you so much for your assistance. I will now attempt to resolve my Z buffering problem. 
But given the title of this post and the issue it addresses, I will close this item, as those concerns have been resolved!
