### ISSUE TITLE
Weird Vector Tile Border

### ISSUE THREAD

**Issue by dissymmetryoflift** [mousebird/WhirlyGlobe#1251]
Finally got Vector Tiles loading. I generated them using a mix of QGIS and Tippecanoe. I used the basic command that they suggested in their cookbook:

`$ tippecanoe -zg -o out.mbtiles --drop-densest-as-needed in.geojson`

Styling is very basic with an SLD file just specifying some fills and line styles. I'm getting what appears to be some strange borders on actual tiles (see attached image). The gap between the parallel lines will change based on zoom level. So I'm assuming it's something to do with how the tiles are being styled.

Anyone have this before?

<img width="397" alt="Screen Shot 2020-10-22 at 11 41 14 PM" src="https://user-images.githubusercontent.com/72475956/96957498-6b376180-14c0-11eb-8407-bcc325ba8ad0.png">

**Comment by mousebird** [comment]
Vector tiles will often extend outside their stated boundaries.  There's some overlap built in.
So those are features at the edge of each vector tile, but outside the real boundaries.

They look like lines to me, water or possibly land.  What's happening is you're clipping polygons to the larger tile boundaries and then using those clipped polygons to display the boundaries.

There are a couple ways to fix this.  First is to not use polygons to show the land/water boundaries.  Use lines instead.

The second is to control the tile ordering in the renderer and have a tile render on top of its neighbor to just hide this problem.  That's outside your control, but lucky for you, a client is asking for that soonish.

**Comment by ZJW1643027592** [comment]
Hello, congratulations on successfully loading VectorTile data, I want you to ask for help, can you teach me how to load VectorTile ? I tried to load VectorTile data with WhirlyGlobe version3.5, but failed, and I did not find relevant tutorials. Could you please teach me the specific operation process or method of loading VectorTile ? Thank you very much!
