### ISSUE TITLE
Is elev_tile_pyramid still supposed to work?

### ISSUE THREAD

**Issue by dissymmetryoflift** [mousebird/WhirlyGlobe#1255]
I've managed to get the tool compiled. And it seems to successfully create an sqlite database that has tiles in it. However, the tiles don't render and I'm getting a constant stream of "DynamicDrawableAtlas::addDrawable(): Drawable mismatch.  Punting drawable" errors.

Is there a newer method for generating elevation tiles?

**Comment by mousebird** [comment]
If this is for 3.0 then the answer is no.  I have a big project in the works to replace the whole elevation subsystem with something truly great, but it hasn't been funded yet.

**Comment by dissymmetryoflift** [comment]
Nope. Using master branch. If I download the database from your blog post I get everything working just fine. 

If I try to use the elev_tile_pyramid tool to generate my own database it completes without errors, says it wrote tiles, but they aren’t showing up properly on the globe. 

Is it possible that something in the GDAL library changed that is causing the tool to build the tiles wrong? I could send you a copy of the database I generated if you like. 

What does it cost to fund the new elevation functionality for v3?

**Comment by mousebird** [comment]
I haven't used elev_tile_pyramid in years so I don't know what might be wrong with it.

For costs on the Synthetic Vision effort talk to contact@mousebirdconsulting.com
