### ISSUE TITLE
How to adjust the minimum distance between the two fingers for android

### ISSUE THREAD

**Issue by maxiang-010** [mousebird/WhirlyGlobe#1268]
In the Android version, the two fingers can't fully knead when they shrink。How to adjust the minimum distance between the two fingers。My device screen 10.8。

**Comment by mousebird** [comment]
Not completely clear on what the issue is, but I would point you to the gesture handler on Android:  GlobeGestureHandler.java or MapGestureHandler.java depending on which one you're using.
