### ISSUE TITLE
iOS: Issue lining up calculated locations with vectors over a long distance

### ISSUE THREAD

**Issue by onepointsixtwo** [mousebird/WhirlyGlobe#1269]
Hi. I have an issue whereby over a long distance, the calculated position along a line, using Haversine equations, doesn't line up with the actual drawn vector. I've attached two screenshots, one zoomed out and one zoomed much closer in. Basically it is an array of lines drawn on the map with bounding boxes indicating areas around them. There are also horizontal lines drawn as vectors calculated by using a bearing along the line to calculate the positions to the +90/-90 of the line, for a set number of metres. As you can see, around the centre of a long line, the coordinates don't quite match up with where the vector is actually drawn. I don't really understand projections well enough to understand why this is, but I was hoping maybe you could suggest a solution. 

The ones I could think of were basically either:
a) an explanation that allows for the difference in the calculation of the coordinates for the horizontal bars such that they do line up with the edges of the bounding box wide vector.
b) A shader that shades the wide vector bounding box every x metres with a horizontal line.

First I guess, which of these would be more straightforward in theory? Second, if it's option b. are there any guides anywhere as to how to achieve that with a Metal shader? I have absolutely no knowledge of 3D graphics I'm afraid, I work more with data driven applications!

Thanks in advance, I know this is a bit of a long post.

![Screenshot 2020-11-24 at 20 34 48](https://user-images.githubusercontent.com/5874664/100148776-1dce5b80-2e95-11eb-9cd9-c69ecb34e959.png)
![Screenshot 2020-11-24 at 20 35 07](https://user-images.githubusercontent.com/5874664/100148790-20c94c00-2e95-11eb-99b4-4942f8f3a8d6.png)

**Comment by onepointsixtwo** [comment]
If it helps actually, here's the code I'm using to generate the coordinate pairs forming the horizontal bars. I'm really confident the maths is right for the moveBy() extension of CLLocationCoordinate2D because I initially wrote it by hand, then tried using several versions from Swift libraries to check my maths wasn't wrong - they all gave exactly the same result.

```
func createHorizontalFlightLines(for line: Line,
                                 metresSpacing: Double,
                                 metresAwayFromLine: Double,
                                 pointsInOrder: [CLLocationCoordinate2D],
                                 lineBearing: Double) -> [[CLLocationCoordinate2D]] {
    var horizontalLines = [[CLLocationCoordinate2D]]()

    let ninetyDegreesLeft = (lineBearing - 90.0).normalizedDegrees
    let ninetyDegreesRight = (lineBearing + 90.0).normalizedDegrees

    let lastPoint = pointsInOrder.last!
    var currentPoint: CLLocationCoordinate2D = pointsInOrder.first!.moveBy(distanceMetres: metresSpacing, onBearing: lineBearing)
    let lineAsSimpleLine = SimpleLine(startPoint: currentPoint, endPoint: lastPoint)

    // While we're still before the last point
    while currentPoint.bearing(to: lastPoint).degreesAreWithin(margin: 10.0, fromOther: lineBearing) {
        horizontalLines.append(createHorizontalLine(for: currentPoint,
                                                    ninetyLeft: ninetyDegreesLeft,
                                                    ninetyRight: ninetyDegreesRight,
                                                    metres: metresAwayFromLine))

        currentPoint = currentPoint.moveBy(distanceMetres: metresSpacing, onBearing: lineBearing)
        currentPoint = currentPoint.closestPoint(on: lineAsSimpleLine)
    }

    return horizontalLines
}
```

**Comment by mousebird** [comment]
This is on the globe rather than the flat map?

**Comment by onepointsixtwo** [comment]
Actually this is just the flat map

**Comment by mousebird** [comment]
I'm assuming the flat map is Spherical Mercator.  In that case you might expect to see some divergence if there's a latitude difference in the start and end points of vector features.

Features are defined with points in (longitude,latitude) which are then converted to the local coordinate system, which I'm assuming is spherical mercator.  If the latitude differs across the features, then there will be some error.

The way this is typically dealt with is to sample the feature along the way.  We do offer some options for that.  Take a look at the [addVectors method](https://mousebird.github.io/WhirlyGlobe/reference/ios_3_0/Classes/MaplyBaseViewController.html#/c:objc(cs)MaplyBaseViewController(im)addVectors:desc:mode:), particularly the kMaplySubdivType and kMaplySubdivEpsilon attributes.

**Comment by onepointsixtwo** [comment]
OK, I'll have a play with those and see how I can get it to work. Out of interest would it be possible to use a projection with the map that would flatten it so the curvature was no longer existent? Something like UTM?

**Comment by mousebird** [comment]
In theory, yes.  I'm not sure what state the map initialization is in with a custom projection for 3.x.  That option is rarely used.

**Comment by onepointsixtwo** [comment]
Sorry for the slow reply (we're in pretty different timezones I think), but just wanted to say thanks for the help. The subdivision works - it keeps it in line with the calculated points. I did play around with custom projections, but it's easier to avoid, and whilst technically this curves the lines, it's subtle enough over a 40km line to not be noticeable for my purposes.

**Comment by mousebird** [comment]
Thanks for the followup!
