### ISSUE TITLE
Eigen link is missing on Bitbucket 

### ISSUE THREAD

**Issue by vaibhavidvt** [mousebird/WhirlyGlobe#1270]
Hi @mousebird ,

I try to install the WhirlyGlobe using the Cocoapods and getting the following issue.

[!] Error installing eigen
[!] /usr/local/bin/hg clone https://bitbucket.org/eigen/eigen --rev 3.2.10 /var/folders/0q/qnqzwvh12s7ftzpj_j8xxq_c0000gn/T/d20201126-15927-v7d62s

abort: HTTP Error 404: Not Found

It seems that the eigen is moved from the bitbucket could you please have a look into that.

![Screenshot 2020-11-26 at 2 38 32 PM](https://user-images.githubusercontent.com/75068296/100330521-10c87e00-2ff5-11eb-9774-51daec038c3d.png)

Thanks so much.

**Comment by mousebird** [comment]
That's an old podspec.  Use the one on the master branch of the WhirlyGlobe repo.

**Comment by vaibhavidvt** [comment]
@mousebird I have updated the pod and the WhirlyGlobe 3.0 is installed but now I ran into another problem. Please check the attached file. Do I have to update these classes, If yes any reference do you have?

![Screenshot 2020-12-02 at 5 01 03 PM](https://user-images.githubusercontent.com/75068296/100867494-4b805980-34c0-11eb-9c81-12da9e40b08e.png)

**Comment by mousebird** [comment]
Ah, you have an app based on 2.x.
In that case, use the v2.6.6 tag on the WhirlyGlobe repo.  That will get you the latest 2.x version.

**Comment by vaibhavidvt** [comment]
@mousebird Yes I just set up with v2.6.1 and it is working as expected, Thank you so much for the help. Just a quick question for you, Do we support Vector Mbtiles in WhirlyGlobeController?

**Comment by mousebird** [comment]
To a very limited extent in 2.x.  In 3.0, to a much greater extent.

**Comment by vaibhavidvt** [comment]
@mousebird Thank you so much.
