### ISSUE TITLE
No default metal library compiled for cocoapods

### ISSUE THREAD

**Issue by gregbuehler** [mousebird/WhirlyGlobe#1280]
While attempting to work through the hello world project, I'm seeing the following issue in the console:
```
2021-01-13 17:51:18.824168-0800 zxcv[24108:206948] Metal GPU Frame Capture Enabled
2021-01-13 17:51:18.824399-0800 zxcv[24108:206948] Metal API Validation Enabled
2021-01-13 17:51:18.869393-0800 zxcv[24108:206948] Failed to set up default Metal library in MaplyRenderController::loadSetup.  Things will be missing.
```

The underlying error in `MaplyRenderController::loadSetup` seems to be
```
Error: Error Domain=MTLLibraryErrorDomain Code=6 "no default library was found" UserInfo={NSLocalizedDescription=no default library was found}
```

This seems to be an issue with how Cocoapods attempts to bundle things.

**Comment by mousebird** [comment]
There should be a .metal library in there.  Try adding it directly to your main project and see if that helps.

**Comment by gregbuehler** [comment]
I updated my Podfile to specify `use_frameworks!` and added an empty metal file to the main project. This seems to have avoided the warning message.

It's kind of curious though since I'm still not seeing anything render using the globe or maply view controllers. After the `viewDidLoad()` function completes I'm seeing the view clear to the requested `clearColor` value. I'm also observing the remote tile source making network requests to fetch tiles, but the display remains empty.

**Comment by mousebird** [comment]
Rather than an empty Metal file, I'd suggest finding the .metal file included with the Pod and linking that in directory to your project.  That's worked in the past for me.

If your shaders are missing it makes sense you won't see anything drawing.

**Comment by gregbuehler** [comment]
Seems this is likely separate issues since I gave the binary distribution a try and I'm seeing the same effect.

**Comment by mousebird** [comment]
I thought the binary build had this working, so I'm confused on that front.  When you get a chance, @TimSylvester-mousebird, could you look into this?  Thanks.

**Comment by gregbuehler** [comment]
Not sure if it helps, but I have my current state captured in https://github.com/gregbuehler/HelloWhirly.

**Comment by gregbuehler** [comment]
I'm gonna close this and open a new issue since I think I found the origin.
