### ISSUE TITLE
maply ndk build failed——invalid operands to binary expression ('std::ostream'...

### ISSUE THREAD

**Issue by NodeGIS** [mousebird/WhirlyGlobe#1309]
I tried to build the latest code on the develop branch, and the result was the following error exception. It looks like the header file import is missing. Is it because my ndk version is incorrect?

**exception:**

WhirlyGlobe\common\local_libs\eigen\Eigen\src\SparseCore\SparseMatrix.h:791:11: error: invalid operands to binary expression ('std::ostream' (aka 'basic_ostream<char>') and 'const char [18]')

WhirlyGlobe\common\local_libs\eigen\Eigen\src\SparseCore\SparseMatrixBase.h:251:30: error: no member named 'endl' in namespace 'std'; did you mean 'end'?

**build tool**

- os: windows 10
- android studio: 4.1.3
- ndkVersion: 22.1.7171670

**Comment by NodeGIS** [comment]
> We don't use Windows in our work so we haven't seen this.
> 
> I see a suggestion online to include iostream.h. That would be in the .cpp file including Eigen.

Yes, I did, and everything is ok now,thank you！

**Comment by mousebird** [comment]
Well that was lucky.  Let us know which file you changed, or do a pull request.  Might as well fix it for everyone.
