### ISSUE TITLE
Cause: null pointer dereference - name: FinalizerDaemon

### ISSUE THREAD

**Issue by harikrishna-daraji** [mousebird/WhirlyGlobe#1325]
I have Implemented with 3.0 in Android. It seems running fine first time, after finishing the activity when I try to open the activity again, it always crash, therefore I can't open the same activity again, any help would be appreciated as I don't have much choice.I am also posting the screenshot of issue:
<img width="1390" alt="Screen Shot 2021-04-12 at 3 54 23 PM" src="https://user-images.githubusercontent.com/65469425/114454169-4d61d400-9ba8-11eb-8b7c-58d216c99fc1.png">
<img width="1398" alt="Screen Shot 2021-04-12 at 3 54 29 PM" src="https://user-images.githubusercontent.com/65469425/114454251-6a96a280-9ba8-11eb-936b-fbe3fcbec6fc.png">

<img width="1398" alt="Screen Shot 2021-04-12 at 3 54 36 PM" src="https://user-images.githubusercontent.com/65469425/114454372-8dc15200-9ba8-11eb-91a9-181513430bb2.png">
<img width="1393" alt="Screen Shot 2021-04-12 at 3 54 41 PM" src="https://user-images.githubusercontent.com/65469425/114454430-9ade4100-9ba8-11eb-9528-c7248f5f1570.png">
<img width="1396" alt="Screen Shot 2021-04-12 at 3 54 49 PM" src="https://user-images.githubusercontent.com/65469425/114454509-b0536b00-9ba8-11eb-904a-bc23e76114d1.png">
<img width="1394" alt="Screen Shot 2021-04-12 at 3 55 06 PM" src="https://user-images.githubusercontent.com/65469425/114454531-b5181f00-9ba8-11eb-8b01-af94953d75d5.png">

**Comment by mousebird** [comment]
We've been cleaning up a lot of shutdown related problems on Android lately.
If you try the latest develop does this still happen?

**Comment by harikrishna-daraji** [comment]
Yes, I have implemented with 3.0 and it is latest at the moment. Any idea why this is happening?

**Comment by mousebird** [comment]
The latest from develop?

**Comment by harikrishna-daraji** [comment]
Not from the develop.
