### ISSUE TITLE
MaplyBaseViewController removeLayer: sometimes freezes

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#147]
Sometimes calling MaplyBaseViewController removeLayer: from the main thread will cause an app to deadlock.

The offending line is LayerThread.mm:1113:
`[self performSelector: @selector(removeLayerThread:) onThread: self withObject:layer waitUntilDone:YES];`

Is this a bug? Calling removeLayer off of the main thread seems to fix it.

See attached screenshot for stack trace.
![screen shot 2014-03-04 at 11 31 08 am](https://f.cloud.github.com/assets/2048291/2325301/993300ae-a3d3-11e3-8040-d2f7054383cb.png)

**Comment by rastandy** [comment]
I think I also encountered this problem. Sometimes my UI freezes and It takes from 5 to 15 seconds to become responsive again.
I attached this screenshot in the hope it is sufficient to understand the problem. Let me know if there is any other useful information I can give you.

In the screenshot you can see the layer thread busy clearing textures.

![whirlyglobe-removelayer-freeze](https://cloud.githubusercontent.com/assets/3983720/10070793/1f3876ec-62b5-11e5-9c1b-b3829364dcb8.png)

**Comment by mousebird** [comment]
What does your quad images layer look like.  Does it have an image depth greater than one?

**Comment by rastandy** [comment]
Yes it has an image depth of 8.

Here is the code I use to build my layer:

- (void) loadTMSLayer:(NSDictionary *)layer cacheDir:(NSString *)thisCacheDir
{
    // Create a layer that animates
    MaplyCoordinateSystem *coordSys;
    NSString *srs;
    
    if (self.show2DGlobe) {
        srs = @"EPSG900913";
        coordSys = [[MaplySphericalMercator alloc] init];
    } else {
        srs = @"EPSG4326";
        coordSys = [[ClimEarthCoordinateSystem alloc] init];
    }

    // Collect up the various precipitation sources
    NSMutableArray *tileSources = [NSMutableArray array];
    
    NSUInteger start_year = [layer[@"start-year"] unsignedIntegerValue];
    NSUInteger end_year = [layer[@"end-year"] unsignedIntegerValue];
    NSUInteger year_step = [layer[@"year-step"] unsignedIntegerValue];
    
    for (NSUInteger ii=start_year; ii < end_year; ii+=year_step)
    {
        NSString *year = [@(ii) stringValue];
        NSString *tileURL = [NSString stringWithFormat:@"%@/%@/%@/%@/", layer[@"tiles"][0], layer[@"palettes"][0], year, srs];
        
        MaplyRemoteTileInfo *tileSource = [[MaplyRemoteTileInfo alloc] initWithBaseURL:tileURL ext:@"png" minZoom:0 maxZoom:4];
        tileSource.coordSys = coordSys;

        tileSource.cacheDir = [NSString stringWithFormat:@"%@/%@/%@/%@/",thisCacheDir, layer[@"palettes"][0], year, srs];
        //tileSource.cachedFileLifetime = 3600; // Tile cache files will be updated every hour

        [tileSources addObject:tileSource];
    }
    
    MaplyMultiplexTileSource *tileSource = [[MaplyMultiplexTileSource alloc] initWithSources:tileSources];
    // Create a layer that animates
    MaplyQuadImageTilesLayer *mapLayer = [[MaplyQuadImageTilesLayer alloc] initWithCoordSystem:tileSource.coordSys tileSource:tileSource];

    self.currentVariableTileSource = tileSource;
    self.currentVariableTileSources = tileSources;
    
    tileSource.delegate = self;
    tileSource.acceptFailures = true;
    
    mapLayer.allowFrameLoading = false;
    mapLayer.imageDepth = (int)[tileSources count];

//    NSMutableArray *framePriorities = [NSMutableArray arrayWithObjects:@(10000), @(10000), @(10000), @(10000), @(100000), @(100000), @(100000), @(100000), nil ];
//    for (int i=0; i < mapLayer.imageDepth; i++) {
//
//    }
//    [mapLayer setFrameLoadingPriority:framePriorities];

    mapLayer.imageFormat = MaplyImageUShort565;
    //layer.maxTiles = 256;
    
    mapLayer.coverPoles = true;
    mapLayer.handleEdges = true;
    mapLayer.asyncFetching = true;
    mapLayer.numSimultaneousFetches = 8;
    mapLayer.waitLoad = true;

    mapLayer.flipY = FALSE;
   
    mapLayer.animationPeriod = [tileSources count];
    mapLayer.maxCurrentImage = mapLayer.imageDepth;

    //layer.animationWrap = true;
    //layer.currentImage = 0;
    //layer.flipY = true;
    //layer.multiLevelLoads = @[@(3)];
    //layer.singleLevelLoading = true;
    
    mapLayer.importanceScale = 1000000;

    self.currentVariableTileSource = tileSource;
    self.currentVariableTileSources = tileSources;
    self.currentVariableLayer = mapLayer;
}

**Comment by mousebird** [comment]
In recent versions I added an explicit clear for entries in the texture atlas.

Try turning off the code in DynamicTexture::clearTextureData() in DynamicTextureAtlas.mm and see if that helps.  If it does, let me know.  I'll need to add a special path for when a layer shuts down.

**Comment by rastandy** [comment]
As you suggested, I commented all the code in DynamicTexture::clearTextureData in DynamicTextureAtlas.mm, and that seems to fix the problem. I tried dozens of times to switch layer and trigger the removeLayer method call and nothing freezed.

**Comment by mousebird** [comment]
Thanks for the followup.  I'll fix this in the toolkit.

**Comment by rastandy** [comment]
Thank you very much for your help!

**Comment by mousebird** [comment]
Ranen, from our conversation on Slack... what needs to happen here is that we need to turn off the clearing flag right before we destroy the dynamic texture atlas.  So in this case the flag is on because it's a multi-frame texture atlas.  But then right before we destroy it, we clear out all the textures.  It right there that we need to set that flag to false.

I think this could be done in the QuadTile code.  If it detects it's being shutdown, that'll work.  You may need to try this out in the ComponentTester app with either the weather layer or the fake multi-frame layer.

**Comment by mousebird** [comment]
I think we may have inadvertently fixed this with a change to when the tiles were cleared.  I'm gonna close it and see if it comes back.
