### ISSUE TITLE
Error building develop via CocoaPods: duplicate symbol 'lodepng_crc32(unsigned char const*, unsigned long)'

### ISSUE THREAD

**Issue by akovalov** [mousebird/WhirlyGlobe#1552]
Error building develop via CocoaPods: duplicate symbol 'lodepng_crc32(unsigned char const*, unsigned long)'

```
duplicate symbol 'lodepng_crc32(unsigned char const*, unsigned long)' in:
    /Users/alexkovalov/Library/Developer/Xcode/DerivedData/App-frfjptbqnbzpcjcqtkfctgpmopjn/Build/Intermediates.noindex/Pods.build/Development-Debug-iphoneos/WhirlyGlobe.build/Objects-normal/arm64/lodepng.o
    /Users/alexkovalov/Library/Developer/Xcode/DerivedData/App-frfjptbqnbzpcjcqtkfctgpmopjn/Build/Intermediates.noindex/Pods.build/Development-Debug-iphoneos/WhirlyGlobe.build/Objects-normal/arm64/RawPNGImage.o
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Looks like `lodepng_crc32` in `RawPNGImage` is not used and can be removed. 
```
unsigned lodepng_crc32(const unsigned char* buffer, size_t length)
{
    return crc32_z(crc32(0L, Z_NULL, 0), buffer, length);
}
```

**Comment by sjg-wdw** [comment]
Can you take a look at this @TimSylvester

**Comment by TimSylvester** [comment]
Ah, right, the preprocessor definitions listed in that file also need to be applied when building that cpp file, particularly `LODEPNG_NO_COMPILE_CRC`.  I never found a good way to do that in the podspec, but I guess it should be fine to apply them to everything, I'll try it...

**Comment by TimSylvester** [comment]
I pulled develop into a project via pod and was surprised to find that it built without error.  You're referencing `develop`, right?  Are you using frameworks in the podfile?

**Comment by paulgee31** [comment]
I had the same issue and yep was using frameworks.

I reverted back to using the source instead.

**Comment by TimSylvester** [comment]
See if referencing [`topic/pod`](https://github.com/mousebird-consulting-inc/WhirlyGlobe/tree/topic/pod) works.

**Comment by paulgee31** [comment]
Yep switching to topic/pod builds fine.
