### ISSUE TITLE
GeoJSON wrong position in 2d map

### ISSUE THREAD

**Issue by akovalov** [mousebird/WhirlyGlobe#1554]
In the latest code of `develop` branch the GeoJSON is rendered OK in the globe map. 
But in 2d map it is rendered in a wrong position. 
It can be reproduced in the AutoTester project in the "Textured Vectors" test case. Please see the screenshots. 

<img src="https://user-images.githubusercontent.com/9693643/182321365-b944f49f-803c-4d5c-9d90-2f306eab3afe.jpeg" width="300">
<img src="https://user-images.githubusercontent.com/9693643/182321379-4f04ca35-4513-4af7-8531-07cd762858ac.jpeg" width="300">

**Comment by sjg-wdw** [comment]
@TimSylvester Might be worth verifying.

**Comment by TimSylvester** [comment]
Should be resolved in develop.  Thanks!
