### ISSUE TITLE
Areal VectorObjects not displayed 

### ISSUE THREAD

**Issue by PeterQi1117** [mousebird/WhirlyGlobe#1568]
Using `VectorObject::addAreal`, certain polygons are missing while others display. 

Example list of `Point2d` which does not display: [points.txt](https://github.com/mousebird-consulting-inc/WhirlyGlobe/files/10044991/points.txt)

Using commit 36118a27fcdff20261c8653a79d680f303161bb5

**Comment by sjg-wdw** [comment]
Try turning Filled off to make sure the outline is coming through.
If it is, then it might be an ordering problem.

**Comment by PeterQi1117** [comment]
The outline does come through. All the polygons used to appear on an older version (possibly 3.1).

**Comment by sjg-wdw** [comment]
You can try tessellating the outline before passing it in.  If you set Filled to off there, then you should see the outlines of the triangles.  If you do, then it's probably an ordering issue and the polygon is wound the wrong way.

**Comment by PeterQi1117** [comment]
Ok I see the tessellated triangles. Reversing the order of the points causes the polygons that previously did not display to display, and vice versa. What determines if a list of points is wound the right way or needs to be reversed?

**Comment by sjg-wdw** [comment]
Winding order.  The ones that work are pointing one way, up ideally.  The ones that don't are pointing the other way.
If you on a flat map you can safely turn off backface culling, so that might be a workaround.  On the globe we need the backface culling to avoid seeing things through the earth.
