### ISSUE TITLE
Markers appear above labels while having a lower draw priority

### ISSUE THREAD

**Issue by PeterQi1117** [mousebird/WhirlyGlobe#1569]
Labels can be made to appear above the marker if `LabelInfo.drawPriority` > `MarkerInfo.drawPriority` + 1,000,000. A difference of 500k does not produce the same effect.

On commit 36118a27fcdff20261c8653a79d680f303161bb5

**Comment by sjg-wdw** [comment]
All drawPriority values can be intermingled.  We try to offset them by 1M by default, but you can also turn that off in the BaseController.
