### ISSUE TITLE
Vertex reverse order drawing

### ISSUE THREAD

**Issue by akovalov** [mousebird/WhirlyGlobe#1571]
I am drawing Uber's H3 hexagons using a generated GeoJSON. Looks like when hexagon vertex coordinates are in a clockwise direction Whirly draws just fine. But when order is in a counter clockwise direction the hexagons are drawn somehow on a back side of the map in a globe. 

For example, when CCW hexagons are in US they will not be visible on a map over US. But if I rotate the globe to Australia so US is on a back side of the globe - I will see those hexagons drawn on back of US territory. So I see that hexagon through the globe.

Do you have any idea how to fix it? 
<img width="573" alt="Screenshot 2022-11-24 at 21 37 15" src="https://user-images.githubusercontent.com/9693643/203858178-61cc536a-e39d-4181-8d24-d25d50691a0d.png">

**Comment by sjg-wdw** [comment]
Since you need backface culling here, you'll have to fix the winding order.  If it's always wrong, you can reverse it.
