### ISSUE TITLE
How to draw areas so that it shows different colors at different heights

### ISSUE THREAD

**Issue by FeiXueKK** [mousebird/WhirlyGlobe#1587]
I want to draw areas that shows different colors at different map heights.
What I can think of right now is drawing the same piece of data multiple times and then giving them different display heights.
However, this approach inevitably increases the memory footprint, which becomes an urgent problem when I have a lot of area data to draw.
Is there a better way to do this?

**Comment by sjg-wdw** [comment]
That's the simplest way to do it, yes.  You could try instancing, but I'm not sure that would work in this case.
A custom shader would do the trick too.
