### ISSUE TITLE
Fill polygon with texture

### ISSUE THREAD

**Issue by akovalov** [mousebird/WhirlyGlobe#1595]
Is it possible to fill a polygon with a pattern image (texture)? I saw `kMaplyVecTecture` can be used with `addWideVector` but it's only for lines as I understand. Is it possible to apply texture to an `addVector` that is a closed polygon? Thanks

**Comment by sjg-wdw** [comment]
Check out the TextureVectorTestCase

**Comment by akovalov** [comment]
thank you @sjg-wdw How properly use texture with opacity? When I use an image as a texture that has some opacity it looks like it is combined with some dark color in semi or fully-transparent pixels. 

When trying to use a no-transparent image as a texture and apply opacity via color as `kMaplyColor: UIColor.white.withAlphaComponent(0.8)` it applies opacity but also combines texture with a color which changes texture colors.

So how apply opacity to a texture without changing texture image colors? Thanks

texture with transparency
![texture](https://github.com/mousebird-consulting-inc/WhirlyGlobe/assets/9693643/eda7bce7-38de-4e36-9fa6-c9ed1d6e89af)

rendered without setting kMaplyColor
![rendered1](https://github.com/mousebird-consulting-inc/WhirlyGlobe/assets/9693643/69702802-6320-4e11-970c-9151641e78f3)

rendered with setting kMaplyColor
![rendered2](https://github.com/mousebird-consulting-inc/WhirlyGlobe/assets/9693643/ae09525d-d896-477f-9f7c-3c1bfaf16848)

**Comment by sjg-wdw** [comment]
I assume it's multiplying the opacity through the color.  The workaround for that might just be to bake that into the texture.
