### ISSUE TITLE
Some tiles not getting loaded using MaplyQuadImageTilesLayer multilLevelLoads

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#208]
This seems to mostly happen at zooms < 5, and zooming in and out seems to fix it.

Im using rasterMultiLevelLoads = @[@(-4), @(-2)];

![photo 14](https://cloud.githubusercontent.com/assets/2048291/3476051/3d9c554e-02f9-11e4-8ffb-f65682a7f632.PNG)
![photo 15](https://cloud.githubusercontent.com/assets/2048291/3476052/3d9d0c3c-02f9-11e4-991f-2bf849232132.PNG)

**Comment by mousebird** [comment]
I suspect this is long gone.  If it turns up again, just reopen.
