### ISSUE TITLE
Memory consumtion and tile loading

### ISSUE THREAD

**Issue by vmirgorod** [mousebird/WhirlyGlobe#218]
Sometimes component consumes huge amount of memory. This leads to crash on real iPhone. Screenshot from simulator is attached. Bing and google sources were used for testing.

```
            NSMutableDictionary *specification = [NSMutableDictionary dictionary];
             specification[@"name"] = NSLocalizedString(@"Google Hybrid", "");
             specification[@"tiles"] = @[@"http://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}"];
             specification[@"scheme"] = @"xyz";
             specification[@"minzoom"] = @(0);
             specification[@"maxzoom"] = @(22);

             MaplyRemoteTileSource *remoteSource = [[MaplyRemoteTileSource alloc] initWithTilespec:specification];
             remoteSource.cacheDir = [NSString stringWithFormat:@"%@/%@/",caches,newTileSource];
```

I think this is because of loading hudge amount of detail tiles (please note, they are unnecessary).

![memory](https://cloud.githubusercontent.com/assets/6309609/3653277/ade6e7fc-114e-11e4-930d-3d609cfbe040.png)

**Comment by mousebird** [comment]
Added single level loading for overlay layers recently.
