### ISSUE TITLE
maply stroke-width

### ISSUE THREAD

**Issue by halset** [mousebird/WhirlyGlobe#229]
Tried the following, but the line got too wide
<LineSymbolizer stroke="#a39452" stroke-width="1"/>

Tried to switch "1" with "0.5", "0.1" and even "0", but it still got wide. Changing to a negative number made the line thin.

The solution works fine for me, so no rush.

**Comment by mousebird** [comment]
Not totally clear on what this one is.  Reopen if you need with a longer explanation.
