### ISSUE TITLE
Memory Leaks while Objects reloading

### ISSUE THREAD

**Issue by vmirgorod** [mousebird/WhirlyGlobe#231]
While markers reloading we encountered memory leak issue.
It seems that component is not unloading old images. 
This is regarding for both master branch and 2.3 branch.

You can test it easily via sample project (please check testAddingOfObjects method):
https://www.dropbox.com/s/29m7z1fxsn8y480/MaplyTester.zip?dl=0

**Comment by vvaleed** [comment]
This post saved my life

**Comment by mousebird** [comment]
Hmm, perhaps time to start thinking about 2.4.
