### ISSUE TITLE
Is there any chance for improvement of the "findHeightToViewBounds:" method?

### ISSUE THREAD

**Issue by awedeebawe** [mousebird/WhirlyGlobe#246]
So, I have all the countries geoJSON generated by geoPHP on my server. I want when the user taps any country, the globe to pan and zoom to the bounding box of the polygon. I have the LL and UR points of the bounding box, I also have the centroid (for the "animateToPosition:" method). However "findHeightToViewBounds:" is not working properly.

Is there any replacement or improvement for this method? It's written in the comments, that it's inefficient, but I need to make this method working :)

**Comment by mousebird** [comment]
This should stop making the globe view twitch in 2.4.
