### ISSUE TITLE
LoadedTile::updateTexture question

### ISSUE THREAD

**Issue by rghosh0** [mousebird/WhirlyGlobe#252]
Hi, I'm trying to debug an error I'm encountering with develop/HEAD, and have found this on line 988 of WhirlyGlobeLib/src/LoadedTile.mm :

if (!loadImage && loadImage.type == WKLoadedImagePlaceholder)

To me that looks like something else was intended... is that correct?

**Comment by rghosh0** [comment]
I'd like to prioritize this with paid support, if possible.  I'll email you to ask for details.  Thanks!

**Comment by rghosh0** [comment]
I seem to have solved the flaky animation problem by changing the implementations of my tile sources, without needing any changes in the WhirlyGlobe codebase.  There is another related issue which I will post soon.

**Comment by rghosh0** [comment]
Specifically, what seems to have fixed this is:
  - I had to implement imageForTile:frame:  (instead of implementing imageForTile: )
  - I had to implement tileIsLocal:frame: (instead of tileIsLocal:)
  - I had to implement validTile:bbox:  (I didn't previously implement this; I assumed if not implemented it would be assumed to be valid)

I guess it took me a while because there were no error messages, but I had to put in all of the changes simultaneously for things to work.  Also I have these changes in the WhirlyGlobe codebase:

https://github.com/rghosh0/WhirlyGlobe/commit/9ee31ad557efe1f897b399186a81ee3cd6632c82
https://github.com/rghosh0/WhirlyGlobe/commit/bf613efd1d26b57698219e2abedb9d6830c32067

The first one was necessary, I believe, and the second one avoided a crash that I was experiencing when there was only one animation frame available.

**Comment by mousebird** [comment]
I need to look into this further.  Glad you got a workaround going.

**Comment by rghosh0** [comment]
OK, right.  If possible you can remove this from Support (unless another party is interested).

To avoid confusion, when I said earlier that using singleLevelLoading caused nothing to show up, I now believe that was my fault: I used a custom subclass of MaplyViewController which had an obsolete overridden setup method.
