### ISSUE TITLE
Two MaplyComponentObjects - can't touch the bottom one

### ISSUE THREAD

**Issue by awedeebawe** [mousebird/WhirlyGlobe#253]
So, I have a MaplyComponentObject with the vector polygons of some areas. On top of it I have MaplyComponentObject with some markers, that hide on certain height and the polygon remains "alone" on the map. However, if I tap on the polygon, in the ```- (void)globeViewController:(WhirlyGlobeViewController *)viewController didSelect:(NSObject *)selectedObj``` the selectedObj's class is still `MaplyScreenMarker` and the polygon fires this method only when I don't create the markers' MaplyComponentObject. How can I hide the markers without removing them from the globeView and allowing my users to touch the polygon itself? :) Thanks

**Comment by mousebird** [comment]
I'm definitely not seeing this behavior in 2.4.
