### ISSUE TITLE
WhirlyGlobe 2.3 CocoaPod build fails with GoogleProtobuf 2.6.1 dependency

### ISSUE THREAD

**Issue by restjohn** [mousebird/WhirlyGlobe#254]
The WhirlyGlobe pod spec pull the 2.6.1 version of the GoogleProtobuf pod, but the build fails because WhirlyGlobe's protobuf-generated artifacts are not compatible with that version.  If I override the GoogleProtobuf version to 2.5.0, the build succeeds.

**Comment by mousebird** [comment]
The Cocoapods spec is back!
I had to drop out GoogleProtobuf because there's just no way to specify the version I need.  But at least you can build with the Pod again.
You'll need the direct version for 2.4 beta1 for now:
https://github.com/mousebird/WhirlyGlobe/blob/develop/WhirlyGlobe.podspec
