### ISSUE TITLE
MaplyScreenMarker rotation

### ISSUE THREAD

**Issue by rghosh0** [mousebird/WhirlyGlobe#255]
Hi, it seems that MaplyScreenMarker rotation is not working with the latest in develop.

Sample code would look like this:
```
    MaplyScreenMarker *marker = [[MaplyScreenMarker alloc] init];
    marker.loc = MaplyCoordinateMakeWithDegrees(-96.75, 32.75);
    marker.rotation = kRadiansPerDegree * _slider.value;
    marker.image = _arrowImage;
    marker.size = CGSizeMake(_arrowImage.size.width*0.5, _arrowImage.size.height*0.5);
    _compObj = [mapViewC addScreenMarkers:@[marker] desc:_markersDesc];
```

I tried to test out the WhirlyGlobeComponentTester sample app in the latest codebase, but there seem to be files missing (MapzenSource h and m files)

**Comment by mousebird** [comment]
Fixed this one a while ago.  Rotation on a globe projecting down to 2D is kind of tricky.  But it's working.
