### ISSUE TITLE
MaplyQuadPagingLayer overlaps objects which come from tiles of diferent levels

### ISSUE THREAD

**Issue by alasarr** [mousebird/WhirlyGlobe#264]
At the attached screenshot (circle black) you can see 3 ScreenMarkers at the same location. These 3 points comes from different levels:

- Purple: zoom level 4.
- Red: zoom level 6.
- Green: zoom level 7.

Is that normal? If so, what can I do to remove previous zoom levels from the viewport? Should I play with kMaplyMinVis and kMaplyMaxVis? Is it an issue?

![captura de pantalla 2014-12-23 a las 18 48 45](https://cloud.githubusercontent.com/assets/1161870/5541257/001c43fe-8ad6-11e4-9189-3460a85bdfd6.png)

**Comment by alasarr** [comment]
Any news about this?

To clarify what could be happening I’ve created a sample project at https://github.com/GeographicaGS/TestMaplyQuadPaging.

This is how I instance the QuadPagingLayer: https://github.com/GeographicaGS/TestMaplyQuadPaging/blob/56d4b6b4621bcce7baea4431d5b74e7c526fb594/TestMaplyQuadPaging/ViewController.m#L75

If there is anyway I can help let me know. If you could give me some direction to start debugging I’ll really appreciate it.

**Comment by JesseCrocker** [comment]
I think the problem is that you are using `MaplyDataStyleAdd`(which is the default), when you need `MaplyDataStyleReplace`

Instead of `[self addData:@[object] forTile:tileID]` try `[self addData:@[object] forTile:tileID tyle:MaplyDataStyleReplace]`

**Comment by alasarr** [comment]
Right! It works.

Thanks a lot!

**Comment by mousebird** [comment]
Thank you Jesse!  I hadn't thought to look at that!

**Comment by alasarr** [comment]
Finally I discover what was happening, that's really odd. I'm running the current version of the branch develop (187aa8c750a6c144b4a4975b4d36a26fe856df6c).

In certain occasions I'm pretty sure that elements of zoom 2 appears when you're at zoom 6 or deeper. 

I've the following drawTiles method for debugging, it draws several labels at each tile:

```
-(void) drawTile:(MaplyTileID) tileID{
    MaplyComponentObject * object;
    MaplyCoordinate ll,ur;
    
    [self geoBoundsforTile:tileID ll:&ll ur:&ur];

    int nValues = 10;
    float incSizeX = (ur.x-ll.x) / nValues;
    float incSizeY = (ur.y -ll.y) / nValues;
    int k=0;
    
    NSMutableArray * labels = [[NSMutableArray alloc]init];
    
    for (float i=ll.x;i<ur.x;i+=incSizeX){
        for (float j=ll.y;j<ur.y;j+=incSizeY,k++){
            
            MaplyScreenLabel * label = [[MaplyScreenLabel alloc] init];
            label.text = [NSString stringWithFormat:@"%d",tileID.level];
            label.loc = MaplyCoordinateMake(i,j);
            [labels addObject:label];
        }
    }
    
    object = [self.viewC addScreenLabels:labels desc:@{kMaplyEnable:@(NO),
                                                       kMaplyFont: [UIFont fontWithName:@"Arial" size:10],
                                                       kMaplyTextColor: [UIColor blackColor]} mode:MaplyThreadCurrent];
    [self addData:@[object] forTile:tileID style:MaplyDataStyleReplace];
    [self tileDidLoad:tileID];
}
```
And the result:

![issue_overlap](https://cloud.githubusercontent.com/assets/1161870/8108965/463cb90a-1054-11e5-9995-bbf6e43234e2.png)

After hours of debugging I've found out that it only happens if your previously called to animateToPosition with a time of 0.0.

So I've changed 
```
[globeViewC animateToPosition:MaplyCoordinateMakeWithDegrees(4,37)
                                 time:0.0];
```

to 

```
[globeViewC animateToPosition:MaplyCoordinateMakeWithDegrees(4,37)
                                 time:1.0];
```

And it works fine! I hope this help.

**Comment by mousebird** [comment]
What are the settings on the paging layer?

**Comment by alasarr** [comment]
I've uploaded the project with the issue.

Here are the options:

https://github.com/GeographicaGS/TestMaplyQuadPaging/blob/master/TestMaplyQuadPaging/ViewController.m#L77

 ```
  // Let's create the MaplyPaging Layer
    QuadLayer* quadlayer = [[QuadLayer  alloc] init];
    MaplyCoordinateSystem * srs = [[MaplySphericalMercator alloc] initWebStandard];
    QuadTileSource *tilesource = [[QuadTileSource alloc] init];
    [quadlayer initWithCoordSystem:srs delegate:tilesource];
    [theViewC addLayer:quadlayer];```

**Comment by mousebird** [comment]
I believe recent bug fixes to the quad paging layer addressed this.
