### ISSUE TITLE
User Location?

### ISSUE THREAD

**Issue by 4Points** [mousebird/WhirlyGlobe#267]
Is it possible to show the users' current location with WhirlyGlobe/Maply?  This looks like a very robust and useful application but I am not seeing user location which is really nice to have in a mobile app.

**Comment by mousebird** [comment]
Sure, but you need to implement it yourself.

Use CoreLocation to get the user's location and get updates.  Then create a MaplyScreenMarker at that location.  Every time it updates, delete the old one and add the new one.
