### ISSUE TITLE
How to Refresh the WhirlyGlobeViewControllerDelegate in IOS?

### ISSUE THREAD

**Issue by DennisZP** [mousebird/WhirlyGlobe#268]
I think somewhere in the program to refresh the WhirlyGlobeViewControllerDelegate,That How to walk again WhirlyGlobeViewControllerDelegate
Thank you very much

**Comment by DennisZP** [comment]
"-(void)globeViewController:(WhirlyGlobeViewController *)viewC didStopMoving:(MaplyCoordinate *)corners userMotion:(bool)userMotion"        I want this method, walk again

**Comment by mousebird** [comment]
I'm sorry I don't really know what you're asking.

That method is called every time the user stops moving around.
