### ISSUE TITLE
Hiding the Vector back side..

### ISSUE THREAD

**Issue by Feras07** [mousebird/WhirlyGlobe#269]
I'm having problem hiding the vector backside , for example  in this snapshot we can see the Antarctica vector from back side .. any solution ?

![screen shot 2015-01-17 at 8 33 42 pm](https://cloud.githubusercontent.com/assets/3783751/5789568/136441c4-9e8a-11e4-948e-fd037249562a.png)

**Comment by mousebird** [comment]
There's a custom shader that handles line backside culling.  So it's odd that's showing up.

How are you adding that?  Is the whole thing a lofted polygon or is the line around the bottom being added with addVectors?

**Comment by Feras07** [comment]
Sorry for being late here is the full method
```
- (void)addCountries :(MaplyBaseViewController*)theViewC vectorDict:(NSDictionary*)vectorDict coloredDict:(NSDictionary*)coloredDict maxDisb:(double)maxDisb
{
    // handle this in another thread
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,0),
                   ^{
                       NSArray *allOutlines = [[NSBundle mainBundle] pathsForResourcesOfType:@"geojson" inDirectory:nil];
                       
                       for (NSString *outlineFile in allOutlines)
                       {
                           NSData *jsonData = [NSData dataWithContentsOfFile:outlineFile];
                           if (jsonData)
                           {
                               MaplyVectorObject *wgVecObj = [MaplyVectorObject VectorObjectFromGeoJSON:jsonData];
                               
                               
                   
                               
                               MaplyVectorObject *vecObj = [MaplyVectorObject VectorObjectFromGeoJSON:jsonData];
                               
                           
                               NSString *vecName = [[wgVecObj attributes] objectForKey:@"ADMIN"];
                                NSString *isoName = [[wgVecObj attributes] objectForKey:@"ISO_A3"];
                               
                               
                               wgVecObj.userObject = vecName;
                               float disbrate;
                               double disbvalue;
                               
                               @try {
                                   
                                   if (coloredDict!=nil /* && d !=nil && d > 0 */){
                                       
                                      disbvalue =[[coloredDict valueForKey:isoName] doubleValue];
                                       
                                       NSLog(@"%f SssssS %@",disbvalue,isoName);
                                       double mxvalue = maxDisb;
                                       if ( disbvalue > 0) {
                                           disbrate=disbvalue / mxvalue;
                                       }
                                   }
                               } @catch (NSException *exception) {
                                   NSLog(@"%@",exception.description);
                               }

                               UIColor *uclr=[UIColor colorWithRed:1.0f green:1.0f*(1-disbrate) blue:1.0f*(1- disbrate) alpha:1.0];

                               
                               MaplyComponentObject *compObj = [theViewC addVectors:[NSArray arrayWithObject:wgVecObj] desc:vectorDict];
                               
                               
                               
                               MaplyComponentObject *filledObj =[theViewC addVectors:@[vecObj]  desc:@{kMaplyColor:uclr,
                                                                                                       kMaplyFilled: @(YES),
                                                                                                       kMaplyEnable: @(YES)
                                                                                                       }
                                                                                mode:MaplyThreadCurrent];

                               if ([vecName length] > 0)
                               {
                                   MaplyScreenLabel *label = [[MaplyScreenLabel alloc] init];
                                   label.text = vecName;
                                   label.loc = [wgVecObj center];
                                   label.selectable = true;
                                   label.layoutImportance = 10.0;
                                   [theViewC addScreenLabels:@[label] desc:
                                    @{
                                      kMaplyFont: [UIFont boldSystemFontOfSize:12.0],
                                      //kMaplyTextOutlineColor: [UIColor blackColor],
                                      // kMaplyTextOutlineSize: @(2.0),
                                      kMaplyColor: [UIColor whiteColor]
                                      }];
                               }
                               
                               
                               
                           }
                       }
                   });
}
```

**Comment by mousebird** [comment]
Just to confirm, it's the white line that's showing up on the back side?

**Comment by Feras07** [comment]
No, it is Red which showing as backside of Antarctica , I just used white oval to highlight it 
Any vector back side can be seen if you able to reach it from ocean side,it might related to blue color ( sea).

**Comment by Feras07** [comment]
Back side of America 

![image](https://cloud.githubusercontent.com/assets/3783751/6021090/68ae7e52-abcc-11e4-8883-dfc0ed45fe31.jpg)

**Comment by Feras07** [comment]
Here sample of used Polygons:

{
"type": "FeatureCollection",
                                                                                
"features": [
{ "type": "Feature", "properties": { "ScaleRank": 3, "LabelRank": 3, "FeatureCla": "Adm-0 map subunits", "SOVEREIGNT": "Andorra", "SOV_A3": "AND", "ADM0_DIF": 0.0, "LEVEL": 2.0, "TYPE": "Sovereign country", "ADMIN": "Andorra", "ADM0_A3": "AND", "GEOU_DIF": 0.0, "GEOUNIT": "Andorra", "GU_A3": "AND", "SU_DIF": 0.0, "SUBUNIT": "Andorra", "SU_A3": "AND", "NAME": "Andorra", "ABBREV": "And.", "POSTAL": "AND", "NAME_FORMA": "Principality of Andorra", "TERR_": "", "NAME_SORT": "Andorra", "MAP_COLOR": 8.0, "POP_EST": 83888.0, "GDP_MD_EST": 3660.0, "FIPS_10_": "AN", "ISO_A2": "AD", "ISO_A3": "AND", "ISO_N3": 20.0 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 1.706025, 42.503297 ], [ 1.678482, 42.496657 ], [ 1.586394, 42.455962 ], [ 1.534046, 42.441699 ], [ 1.486194, 42.434464 ], [ 1.448832, 42.437436 ], [ 1.428161, 42.46131 ], [ 1.43028, 42.497871 ], [ 1.42196, 42.530815 ], [ 1.414829, 42.548411 ], [ 1.428316, 42.595902 ], [ 1.458857, 42.621688 ], [ 1.501335, 42.64272 ], [ 1.568153, 42.634995 ], [ 1.709901, 42.604428 ], [ 1.73946, 42.575929 ], [ 1.740184, 42.556731 ], [ 1.713932, 42.525622 ], [ 1.706025, 42.503297 ] ] ] } }

]
}

**Comment by mousebird** [comment]
It's not the input polygons that are the problem.  It's the tessellation.  Lofted polygons breaks the area up on a grid before tessellating, which helps with this problem.  Switch to lofted polys.

**Comment by Feras07** [comment]
Okay thank you for highlighting this point
But after checking the distribution verstion WhirlyGlobe_Maply_Distribution_2_3
setLoftedPolyDesc is not existing in MaplyBaseViewController !?
