### ISSUE TITLE
Help with currentMapZoom method

### ISSUE THREAD

**Issue by alasarr** [mousebird/WhirlyGlobe#270]
I'm running a Globe, and I'd like to get the zoom when tap over the globe. To accomplish this task I've tried:

```
- (void)globeViewController:(WhirlyGlobeViewController *)viewC didTapAt:(WGCoordinate)coord
{
    NSLog(@"Zoom level: %f",[self currentMapZoom:coord]);
}
```
Unfortunately the zoom returned doesn't match with the zoom displayed by MaplyAnimationTestTileSource. MaplyAnimationTestTileSource says that tile zoom value is 5, whereas currentMapZoom method says 8.47184. 
```
MaplyAnimationTestTileSource *tileSource = [[MaplyAnimationTestTileSource alloc] initWithCoordSys:[[MaplySphericalMercator alloc] initWebStandard] minZoom:0 maxZoom:21 depth:1];
MaplyQuadImageTilesLayer *layer = [[MaplyQuadImageTilesLayer alloc] initWithCoordSystem:tileSource.coordSys tileSource:tileSource];
[globe addLayer:layer];
```

Why is that happening?

**Comment by mousebird** [comment]
The map zoom level corresponds to what Mapnik would see as the zoom level.  When you're using the globe it's, at best, approximate.  It makes more sense for the 2D map.

The tile sources calculate what to load based on the screen size of their tiles and the number of pixels in each tile.  So there's no fixed zoom from their perspective... unless you're using the 2D map and single level mode.

So the question is what you're trying to do with that zoom level.  There may be another number that would work better.

**Comment by alasarr** [comment]
I want to make interactive MBTiles. I had thought on build an object which is capable of understanding the Mapbox UTFgrid specification https://github.com/mapbox/utfgrid-spec. 

My idea is to capture the coordinate where a tap happens (didTapAt method), get the zoom level and with this information I can have a MaplyTileID object. Once I have the tile I'll read the MBTile, deal with the utfgrid format and show interactive information over a raster.

I can't use vector tiles for this task because I need a very complex symbology and I need Mapnik for that.

**Comment by mousebird** [comment]
Seems reasonable.  I think the way I'd do that, though, is to load the UTF tiles at the same time I loaded the underlying image tiles.  Or if you wanted to separate them use a paging layer like in the [CartoDB example](http://mousebird.github.io/WhirlyGlobe/tutorial/cartodb_layer.html).

Then just keep a big list of the UTF tiles I'd loaded and, when I get a tap, just work through each one to see if it encompasses the point.  It's not super fast, but it's simple.

**Comment by alasarr** [comment]
Thanks a lot. I'll try that!

**Comment by nreynaud** [comment]
I'm having kinda the same issue as @alasarr and I don't understand how @mousebird 's solution work..

I'm running a Globe and I created a MaplyRemoteTileSource and i'm loading the UTF tiles needed.
On tap I only get the WGCoordinate point tapped on. 
How do you translate this coordinate to get the character in the UTFGrid ? 
At least get the current MaplyTileID tapped on ?

**Comment by mousebird** [comment]
We don't directly support UTF grids.  You'll need to translate that coordinate into a tile and then query the tile.  That's all in your code, I'm afraid.

**Comment by nreynaud** [comment]
All right then !
Thanks for the very fast response :+1:

**Comment by mousebird** [comment]
Or you could pay to add it.  I always forget to mention that part.

**Comment by klyatskin** [comment]
Seems for me that zoom calc is wrong in  WhirlyKitView.mm: 236. 
RadToDeg is redundant, a constant should be adjusted (how?). The function versioned below works fine for me and returns zoom for the Globe as expected... 

- (double)currentMapZoom:(WhirlyKit::Point2f &)frameSize latitude:(double)latitude
{
  double mapWidthInMeters = (2 * self.heightAboveSurface *  tan(_fieldOfView/2.0) * EarthRadius);
  double metersPerPizel = mapWidthInMeters/frameSize.x();
  double zoom = log2(EarthRadius * /*RadToDeg*/(cos(latitude))/ metersPerPizel) - 8 - 6.856230 + 9; 
  return zoom;
}
