### ISSUE TITLE
Failed to parse pbf when using MaplyMapnikVectorTiles

### ISSUE THREAD

**Issue by alasarr** [mousebird/WhirlyGlobe#271]
I'm trying to draw Mapnik Vector Tiles using MaplyMapnikVectorTiles but I got the following error:
```
Failed to parse pbf 6/17/25
```
I'm creating the MaplyQuadPagingLayer as follow:

```
 // Create the mbtile source
    MaplyMBTileSource *vectortileSource = [[MaplyMBTileSource alloc] initWithMBTiles:@"mapboxstudio_mapnikvectorties"];

    //Create mapnik vector tiles delegate
    MaplyMapnikVectorTiles *mapnikVectorTiles = [[MaplyMapnikVectorTiles alloc]init];
    // Init the delegate with the MBTile tile source
    mapnikVectorTiles = [mapnikVectorTiles initWithMBTiles:vectortileSource];
    
    // Create the quand paging layer using mapnik vector tiles delegate
    MaplyQuadPagingLayer *vectortileLayer = [[MaplyQuadPagingLayer alloc]init];
    MaplyCoordinateSystem * srs = [[MaplySphericalMercator alloc] initWebStandard];
    vectortileLayer = [vectortileLayer initWithCoordSystem:srs delegate:mapnikVectorTiles];
    
    [globe addLayer:vectortileLayer];
```

As the error point, it looks like a problem with the format of the tile, I've tried to generated the mbtile using   mapbox-studio and also using tile-live copy (It would be the same because Mapbox says that mapbox-studio uses tile-live under the hoods). These are the two MBTiles:

https://drive.google.com/open?id=0B0Own39wCNYCSnhDUUZkam5XZGM&authuser=0
https://drive.google.com/open?id=0B0Own39wCNYCQ3ExUnhJbHZFcnc&authuser=0

Am I doing something wrong or I should start fighting with the format?

**Comment by mousebird** [comment]
The format changed with v4.  I have some fixes for a specific client, but I need to integrate those and do a more comprehensive test.

I've been collecting examples to test all together when I'm cleaning this up for a different client.  Should be in the next few days.

**Comment by alasarr** [comment]
Thanks a lot ;) Let us know when this feature is accomplished. Also I you need some help for testing, debugging, etc. let me know.

**Comment by alasarr** [comment]
If the problem is the format of the version 4. Do you know an specific version of tile-live or MapBox Studio which generates something compatible with the current version of WhirlyGlobe?

**Comment by mousebird** [comment]
I've already updated to the new version.  So if you're using a Mapnik XML for styling, you should be able to proceed.

Right now I'm adding support for Mapbox's new style sheet.  Turns out to be pretty simple.

**Comment by alasarr** [comment]
This is at develop branch, right?

Mapbox's new style sheet would be really nice!

**Comment by mousebird** [comment]
Yes.  I haven't done a clean test, though, so let me know what you run into.

There's a new submodule there too.

**Comment by alasarr** [comment]
With the develop branch I still got the same issue: Failed to parse pbf 2/1/2. 
This is the latest commit I'm running:
```
$ git log
commit 7fff8beacb6b53d6eda7ac5578f7d820a0edc67b
Author: Steve Gifford <sjg@mousebirdconsulting.com>
Date:   Mon Feb 16 09:39:39 2015 -0800

    Passing more information around the vector tiles (for a client project).
```

**Comment by mousebird** [comment]
It'll want the Mapnik XML, yes.  But it should be able to parse the vector tiles on its own.

I haven't had a chance to try out the MBTiles archives yet.  I've just been working with vector tiles direct from Mapbox.  I'll try those soon.

**Comment by mousebird** [comment]
PDF parsing should be fixed (a while ago).  Styles are another issue, though.
