### ISSUE TITLE
Android Layout updates

### ISSUE THREAD

**Issue by darenig** [mousebird/WhirlyGlobe#272]
I've noticed Maply doesn't properly update its rendering when layout changes occur. The GLSurfaceView updates (touch input is properly received), but the map ends up only rendering its the same relative viewport, but the image becomes distorted. The greater the difference in layout, the more pronounced the distortion.

Example:
Before removing the gray View.
![before](https://cloud.githubusercontent.com/assets/5464599/5982142/3480bc12-a88e-11e4-9ac0-ec19302aba0b.png)

After removing the gray View.
![after](https://cloud.githubusercontent.com/assets/5464599/5982151/59c3bc2c-a88e-11e4-8ecb-128aff889eef.png)
Note: The black area to the right of the map is fully interactive. The map has also become distorted.

Taking a look in MaplyRenderer_jni, I can see a call to the MapView's runViewUpdates() method hasn't been ported yet. Is there a way to get a reference to the View and have the render within the full bounds to GLSurfaceView?

**Comment by mousebird** [comment]
It's probably looking once at startup and then ignoring it after that.

I'm doing an update for WhirlyGlobe at the moment.  So I'll look into this then.
