### ISSUE TITLE
How do I export a view into a picture?

### ISSUE THREAD

**Issue by DennisZP** [mousebird/WhirlyGlobe#277]
How to make the current WhirlyGlobeViewController of view, to generate a image?       For example, I drew a vector data on globeViewC,I would like to generate a current view pictures saved, how should I do?

**Comment by mousebird** [comment]
http://mousebird.github.io/WhirlyGlobe/reference/ios_2_3/Classes/MaplyBaseViewController.html#//api/name/snapshot
