### ISSUE TITLE
How do the elements directly drawn on a canvas?

### ISSUE THREAD

**Issue by DennisZP** [mousebird/WhirlyGlobe#278]
Can I draw MaplyScreenMarker in a UIImageView directly?   
I want to draw elements directly on an image, for example, I want to draw a point,

 '[_globeViewC addScreenMarkers:ImgArrDP desc:@{kMaplyMinVis: @(0.0), kMaplyMaxVis: @(1.0), kMaplyFade: @(0.0)} mode:MaplyThreadCurrent];'

 the need for such a method, which is painted it on the map can not be directly in the picture on the stipple

**Comment by mousebird** [comment]
No, MaplyScreenMarkers are drawn into the OpenGL ES view that WhirlyGlobe-Maply controls.

What are you trying to do?

**Comment by DennisZP** [comment]
Dear Sir ,The map displays slowly when the data volume of the current interface is large and the elements needed to add are too much( map elements including point ,line and surface). The reason of the problem，which leads to unpleasant experience, is the elements that the map loads are too much.  I am looking for ways to draw those elements on one picture or one View. And I control the picture. 
In this case, it will be fast in the process of panning ,Pinching. 

Or,You can give me a way.Close the method when drawn in panning,Pinching process . When the statusEnd ,Disposable drawn again.

**Comment by DennisZP** [comment]
Is simply,There is no way you can make a map in case load a lot of elements, showing faster

**Comment by mousebird** [comment]
First, you should try the following first:
- Build the app in Release, not Debug.
- Add your geometry in big groups, not individually.  Each of the add methods takes an NSArray.

If you truly have too much data to display at once, there is a mechanism for loading it by tile.  Look at the [CartoDB example](http://mousebird.github.io/WhirlyGlobe/tutorial/cartodb_layer.html) of the MaplyPagingLayer.

There are also callbacks for viewport changes in the WhirlyGlobeViewController if you need them.  That approach isn't as efficient as tile loading, but will work.
