### ISSUE TITLE
label issue with XCode 6 / custom projection / old Maply

### ISSUE THREAD

**Issue by rghosh0** [mousebird/WhirlyGlobe#282]
Hi, this is a weird bug for which I've found a work-around.  I just wanted to document it in case others have had this problem.

When XCode 6 came out I wanted to use a more recent WhirlyGlobe version, but some issues [1] [2] with 2D Maply forced me to stick with the older WhirlyGlobe (March 11, 2014).  Up to now I've also been forced to stick with XCode 5, because of a label layout issue that only seemed to occur when compiled with XCode 6.

This issue only showed up when using a custom projection and running a Release build.  Basically all labels were stuck in the center of the screen, and moving the map didn't move the labels with it.

Then I found that changing the Optimization Level of WhirlyGlobeLib / Release from -Os to -O3 removed the problem.  So that's my workaround.

Since it only happens with my custom projection, and not when using  e.g. MaplyPlateCarree or MaplySphericalMercator, I at first figured that my custom projection was to blame.  I am now not so sure, because (A) I couldn't find any uninitialized local variables or bounds issues for which optimizaiton level could reveal an otherwise unmanifested bug, and (B) I had to change the optimization level of WhirlyGlobeLib specifically, and not my test app project, where the custom projection code was.

Of course my custom projection uses proj4 code, which resides at the WhirlyGlobeLib level, so maybe the issue is there.  I saw that there was at least one change there for uninitialized variables [3], but this change didn't remove the problem I'm seeing.

Also, using a more recent version of WhirlyGlobe (Dec 2, 2014) doesn't recreate this problem.  (I can't use this newer version for reasons above).

[1] https://github.com/mousebird/WhirlyGlobe/issues/252
[2] https://github.com/mousebird/WhirlyGlobe/issues/255
[3] https://github.com/mousebird/proj-4/commit/302f5c534afdb227e2093e1d0c64dc349831fe69

**Comment by rghosh0** [comment]
I'm closing this issue as it was mainly just to document the issue.  I give the workaround in the original post.

**Comment by mousebird** [comment]
Sounds like a bug in WG-Maply.  I'll add it to the list.

**Comment by rghosh0** [comment]
OK, then I'll provide the coordinate system

https://s3.amazonaws.com/kastra/MercatorCoordSystem.h
https://s3.amazonaws.com/kastra/MercatorCoordSystem.mm

I switch the coordinate system for different tests like this:

    mapViewC = [[MaplyViewController alloc] init];
    mapViewC.coordSys = [[MaplyMercator alloc] initMercCoverage];
    //mapViewC.coordSys = [[MaplyPlateCarree alloc] initFullCoverage];
    //mapViewC.coordSys = [[MaplySphericalMercator alloc] initWebStandard];

**Comment by rghosh0** [comment]
Maybe this ticket should be closed since it only affects an older version of Maply?

**Comment by mousebird** [comment]
Works for me.
