### ISSUE TITLE
Styling vectors and labels

### ISSUE THREAD

**Issue by alasarr** [mousebird/WhirlyGlobe#283]
I need to style a geojson with polygons. I need to apply a border to the polygons and a label in the center.

What I'm doing right know is prepare the geometries to something that WhirlyGlobe could understand. For a layer of polygons I need to calculate the boundaries and the position of the label. At the end I need to pass to WhirlyGlobe three types of vectors: polygons, lines (boundaries) and points (labels).

 I'd like to know if exists a better way out of the box.

**Comment by mousebird** [comment]
For something like geojson or Shape, I just do it manually.  If you're using Mapnik for Maply Vector Tiles, you can use Mapnik XML, probably derived from CartoCSS.

If you're feeling clever you could hook the Mapnik style support up to a GeoJSON tile reader, but it would be more work than just doing the thing you need to do.

I'll keep this in mind for the future. There's no reason we couldn't handle GeoJSON the same way we do Mapnik Vector Tiles.

**Comment by alasarr** [comment]
Thanks!

**Comment by mousebird** [comment]
The Mapzen reader handles both GeoJSON and PBF, so I'm going to close this.
