### ISSUE TITLE
Crash in BigDrawable::executeFlush due to glMapBufferRange returning null

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#286]
I've seen many crash reports of an EXC_BAD_ACCESS in BigDrawable::executeFlush but had never seen it happen in testing, until today. The problem appears to be glMapBufferRange returning null, then when it's padded to memcpy it crashes. I don't know enough about openGL to understand why this happens, and what properly catching this error would look like, but I tried  https://github.com/trailbehind/WhirlyGlobe/commit/7130b2a817394602d30eea2adc42e1bc81cb0c12 

Unfortunately I haven't been able to reproduce the bug since making that change to see if it actually fixes it, or just leads to another crash.

Does that seem like a reasonable fix? Or does glMapBufferRange returning null indicate that things are so FUBARed that there is no recovering?

**Comment by mousebird** [comment]
That does seem like a reasonable fix.  All that will happen is the BigDrawable won't get updated.  That might result in blank or missing map tiles, but it beats a crash.

This shouldn't happen, of course, but if the buffer were gone out from under us, I could see it returning that.

**Comment by mousebird** [comment]
Put in a similar fix.
