### ISSUE TITLE
EXC_BAD_ACCESS in WhirlyKit::BigDrawable::draw(WhirlyKitRendererFrameInfo*, WhirlyKit::Scene*)

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#288]
This crash happens somewhat frequently, but i don't know how to reproduce it. 
http://crashes.to/s/71f26017fd9/details

![screen shot 2015-02-26 at 8 17 43 am](https://cloud.githubusercontent.com/assets/2048291/6401642/179df68c-bdbf-11e4-8d9c-89da86ff79f1.png)

**Comment by mousebird** [comment]
I think that one just runs out of memory.  OpenGL tries to alloc something and boom!

**Comment by mousebird** [comment]
If I'm wrong and this one isn't about memory, feel free to reopen.
