### ISSUE TITLE
How to adjust the alpha MaplySticker?

### ISSUE THREAD

**Issue by DennisZP** [mousebird/WhirlyGlobe#290]
I use MaplySticker add an image on the map,But I want to adjust the alpha of the image.
Or, is there a way to adjust the alpha of the MaplySticker.

**Comment by mousebird** [comment]
The kMaplyColor property on the description dictionary when you call [addStickers](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_3/Classes/MaplyBaseViewController.html#//api/name/addStickers:desc:mode:).
