### ISSUE TITLE
Zoom out in MaplyViewController to show the map in its entirety

### ISSUE THREAD

**Issue by rastandy** [mousebird/WhirlyGlobe#299]
I'm using the WhirlyGlobeViewControlelr controller and MaplyViewController to show climatic variables in 2D and 3D mode.

While in 3D mode I can zoom out and see the entire globe, in 2D map mode I can't zoom out to see the map as a whole. Is there a way to do that?

I've also tried to initialize my MaplyViewController instance with a scrollView, but I had no luck in showing the entire map when zooming out. I'm not sure if that's the path to follow.

Thank you very much for any help you would give and for your awesome framework.

Andrea.

**Comment by mousebird** [comment]
I'd stay away from scroll views.  That was an experiment I won't be repeating.  UIScrollView is not well suited to this sort of thing.

As for showing the entire map, you should just be able to set the height to something suitably large.  There will be an upper limit, but I'm not sure what it is offhand.  The map will also try to repeat.  You can turn that off if you need to.

**Comment by rastandy** [comment]
Steve Gifford <notifications@github.com> writes:

> I'd stay away from scroll views. That was an experiment I won't be
> repeating. UIScrollView is not well suited to this sort of thing.

Oh, thanks! I was going in the wrong direction, thanks for having
stopped me.

> As for showing the entire map, you should just be able to set the
> height to something suitably large.

Tried that. But it seems that when I'm able to zoom out the upper limit
(which is not that easy because the default gesture seems to not allow
for zooming out when your view is near the upper or lower extents of the
map) all my visible layers disappear. Strangely enough, I see only
labels associated with a vector tile layer (only labels not the
geometries).

> There will be an upper limit, but I'm not sure what it is offhand. The
> map will also try to repeat. You can turn that off if you need to.

Also, I tried to activate the "viewWrap" property to "true" but map does
not repeat itself. Any idea about why it's not repeating?

Many thanks for your help.

**Comment by mousebird** [comment]
Things disappearing does make sense, unfortunately.  It's all still 3D even if you're using a flat map.  If you zoom far enough, the far clipping plane kicks in.

I had things more or less tuned to show the whole map before that kicked in, but you want to show the whole map, but small.  To do that, I think you'd need to change the far clipping plane defaults in the MaplyView.mm.  Just set the far plane higher and see if that helps.

As for wrapping, I just ran the component tester and it seems to do the right thing.  What are you seeing?

**Comment by rastandy** [comment]
> Things disappearing does make sense, unfortunately. It's all still 3D
> even if you're using a flat map. If you zoom far enough, the far
> clipping plane kicks in.
>
> I had things more or less tuned to show the whole map before that
> kicked in, but you want to show the whole map, but small. To do that,
> I think you'd need to change the far clipping plane defaults in the
> MaplyView.mm. Just set the far plane higher and see if that helps.

That was exactly what I needed, thanks! Now it works. I just need now to
change the pin and pan gestures delegates to fit my needs.

> As for wrapping, I just ran the component tester and it seems to do
> the right thing. What are you seeing?

The problem I had was related to the fact that I was trying to set the
viewWrap property after the loadSetup method was called during view
initialization.

In fact, when you set the viewErap property after view load time, the
mapView wrap property is not updated.

I've sent a one line patch for this. I hope it's the right fix for this
problem.

As usual, many thanks for your help!

**Comment by mousebird** [comment]
Thanks for the fix!
