### ISSUE TITLE
duplicate symbol for AFNetworking with cocoapods

### ISSUE THREAD

**Issue by Sylvain-B** [mousebird/WhirlyGlobe#300]
Since whirly static library (libWhirlyGlobeMaplyComponent.a) for framework embeds AFNetworking library, I get duplicate symbol errors with my AFNetworking Pod. Is there a way to prevent that?

Normally, you might want to prefix all your dependencies so it does not collide with external libraries.

Also, I tried to install WhirlyGlobe using Cocoapods, but it fails since some Pods dependencies does not install correctly into the project (eigen abd boost at least).

**Comment by mousebird** [comment]
Thanks for the bug reports.  It looks like some of the sub modules have changed since the pod was built.  When I have some time I'll look deeper into this.

**Comment by mousebird** [comment]
The podspec is back!
Until I replace the one in the Cocoapods repo, you can use beta1 directly.
https://github.com/mousebird/WhirlyGlobe/blob/develop/WhirlyGlobe.podspec
