### ISSUE TITLE
How at 180 °, and spans across the coordinates 0 °, add MaplySticker?

### ISSUE THREAD

**Issue by DennisZP** [mousebird/WhirlyGlobe#306]
I now need to map superimposed on a larger picture, the need to use MaplySticker.
This picture superimposed coordinate corners have been calculated, but it is across the set of coordinates of 0 °,
They are
LeftTopX = -17.607592419527002;
LeftTopY = 19.203949477858618;
RightButtomX = 79.465225704019375;
RightButtomY = 63.702248169131252;

I ask how should I superimposed over pictures?

**Comment by mousebird** [comment]
What happens when you naively assign those coordinates?  Does it wrap around the wrong way?

A screenshot would be good.

**Comment by DennisZP** [comment]
Ask how the picture Full Coverage whirlyGlobe,Or use MaplySticker.
How to make MaplySticker Covering the entire planet?

**Comment by mousebird** [comment]
I think if you just leave a tiny sliver, like -197.99999 to 179.0000 it might work.
Otherwise you'll have to break it into four pieces with four textures.  That would probably work too.

**Comment by JesseCrocker** [comment]
It might also be worth considering a different approach to this problem: Georeference the image, slice it  into tiles, but only do 1 or 2 zoom levels, put them in the app bundle, or an MBTiles file, and load it as a tile layer.

**Comment by mousebird** [comment]
Actually, that would probably work okay.  You'd need to reach down into the sampling for the tiles to get a decent number of pieces for the earth.  But that would be pretty simple.
