### ISSUE TITLE
Color the poles

### ISSUE THREAD

**Issue by sarahansen223h** [mousebird/WhirlyGlobe#308]
Like promised ( http://stackoverflow.com/questions/30491436/whirlyglobe-maply-poles/30513021#30513021 ) i'm going remind you about it ! :)

- It would be nice to be able to set the color directly for the poles as option

**Comment by alasarr** [comment]
+1

**Comment by mousebird** [comment]
Available in 2.4.1.
northPoleColor and southPoleColor on the Quad Images layer.
