### ISSUE TITLE
Got exception in android sample

### ISSUE THREAD

**Issue by testingandroid** [mousebird/WhirlyGlobe#309]
Hi sir, thanks for supporting, 
Here i got some problem
first of all when i compile my code in libs folder automatcally create one file under "armeabi" folder "libMaplyTester.so".
and got exception here,
public MainActivity() {
		System.loadLibrary("MaplyTester");
//		System.loadLibrary("Maply");
	}

when i use "System.loadLibrary("Maply")"  it gave me direct exception but if i use "System.loadLibrary("MaplyTester")" then i can see the first page for "globe and others" options.
when i click "Globe(3D)" . I got exception under library class same exception "MaplyBaseController" 

public MaplyBaseController(Activity mainActivity) 
	{		
		System.loadLibrary("Maply");
//		System.loadLibrary("MaplyTester");
		activity = mainActivity;
	}

if i use "System.loadLibrary("Maply")"  then got exception and if i use other one then also got exception.
one more thing, in my library "Maply" there is no autogenerated ndk file i.e. under "armeabi" folder "libMaply.so". I think this is main problem thats why my program can not synchronized with library and project sample..

--- Overall we can say we got different so file in sample code and there is use different. Library have also use one so file uder class "MaplyBaseController" and it get reference from under libs folder but no file is there.

Pls check and help me out this problem.
Here is my exception and it related to ndk file i.e "so" file are missing that why no linking.
 
06-04 21:12:12.686: E/AndroidRuntime(18193): FATAL EXCEPTION: main
06-04 21:12:12.686: E/AndroidRuntime(18193): java.lang.UnsatisfiedLinkError: Couldn't load Maply from loader dalvik.system.PathClassLoader[DexPathList[dexElements=[zip file "/data/app/com.mousebird.maplytester-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mousebird.maplytester-1, /vendor/lib, /system/lib]]]: findLibrary returned null
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at java.lang.Runtime.loadLibrary(Runtime.java:359)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at java.lang.System.loadLibrary(System.java:514)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at com.mousebird.maply.MaplyBaseController.<init>(MaplyBaseController.java:99)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at com.mousebird.maply.GlobeController.<init>(GlobeController.java:45)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at com.mousebird.maplytester.MapGlobeTestFragment.onCreateView(MapGlobeTestFragment.java:67)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.app.Fragment.performCreateView(Fragment.java:1695)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.app.BackStackRecord.run(BackStackRecord.java:694)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.os.Handler.handleCallback(Handler.java:725)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.os.Handler.dispatchMessage(Handler.java:92)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.os.Looper.loop(Looper.java:153)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at android.app.ActivityThread.main(ActivityThread.java:5297)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at java.lang.reflect.Method.invoke(Method.java:511)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
06-04 21:12:12.686: E/AndroidRuntime(18193): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by mousebird** [comment]
There should be a libMaply.so in there somewhere.  That needs to find its way into your bundle.  That's the native portion of the Wg-Maply library it's trying to load.

**Comment by testingandroid** [comment]
yeah but that native lib by default generated, in test project it generated by default but in library it's not generate..

**Comment by mousebird** [comment]
Right, I think the project doesn't pick it up automatically.  I usually make a symlink to the libMaply.so file in the test project's armebi folder.  Then it gets picked up.

**Comment by testingandroid** [comment]
I got one file but that is different one i.e. "libMaplyTester" in project sample but lib didn't create any file.I need to implement this in one project. iPhone is working properly. Android doesn't . Can you please send me full your compiled code in my mail id here i need some files missing in library so that why it didn't make any so file. It's very useful for me. Here is my mail id "android.team@beckondelve.com". 
Thanks

**Comment by mousebird** [comment]
You have to find a way to include libMaply.so in your build.  The way I've done it in the past is to copy it (or symlink) it into the armeabi folder of MaplyTester.

If you're using Android Studio it's a little easier.  You just need to copy the various pieces into place as they instruct for an NDK library.

I'm sorry this isn't easier.  I haven't had time to document and simplify as I have on iOS.  That'll come soon, I think.

**Comment by testingandroid** [comment]
okay thanks
