### ISSUE TITLE
Method for finding real height (in meters) at given zoom height

### ISSUE THREAD

**Issue by vmirgorod** [mousebird/WhirlyGlobe#310]
I don't know where this method can be placed, but i guess it should be somewhere. For example, now, i want to auto adjust height above globe near hight mountains. I should somehow convert globe relative height to real one.

**Comment by mousebird** [comment]
Are you looking for the height above the sphere, height above the datum or heigh above the actual surface of the earth?

**Comment by vmirgorod** [comment]
I guess i m looking height about sphere (or rather sea level).

**Comment by mousebird** [comment]
In the standard version it's just height above the sphere.  There's no actual datum.

In which case you multiply the height * EarthRadius.  You'll find that constant in the code.
