### ISSUE TITLE
Change Color of WhirlyGlobe Tiles

### ISSUE THREAD

**Issue by wullrich19** [mousebird/WhirlyGlobe#311]
I have been trying to solve this for a few days now and can't seem to figure it out:

I was wondering how to make is so that all of the tiles (countries) that are displayed on the WhirlyGlobe are a dark grey color, instead of multicolors that come default with the mousebird tutorial. If anyone knows how to do this via code, or knows of an alternate solution I would greatly appreciate it. Thanks!

**Comment by mousebird** [comment]
With Geography class?
Well, those are the colors of the pixels in the images that are contained in the MBTiles file.  So you have to modify those somehow.

You could:
- Make your own version of Geography Class.
- Modify the images on input.  You'd have to modify the MBTiles loader to do this.
- Mess with the pixel values in the fragment shader.  I can't believe I'm suggesting this, but if you want to go that route look in DefaultShaderPrograms.mm.  You'll want to make your own version of triShader.

None of this is really a "casual" fix and is probably not worth your time.
