### ISSUE TITLE
MaplyScreenMarker add image Picture distortion

### ISSUE THREAD

**Issue by DennisZP** [mousebird/WhirlyGlobe#312]
When I used to load an icon MaplyScreenMarker.

MaplyScreenMarker *imgMarker = [[MaplyScreenMarker alloc] init];
imgMarker.loc = MaplyCoordinateMakeWithDegrees(LonX, LonY);
imgMarker.size = size;
imgMarker.image = pinImage;
imgMarker.layoutImportance = MAXFLOAT;
imgMarker.offset = CGPointMake(0, -13);
[markers addObject:imgMarker];

CustomLinePoint_Objc = [globeViewC addScreenMarkers:markers desc:@{kMaplyFade: @(0.0)}];

Picture distortion,It has become such:
![11111](https://cloud.githubusercontent.com/assets/8907722/8122592/b37e50ec-10ee-11e5-936d-90ea07490bfc.png)

**Comment by DennisZP** [comment]
When I use ipad4 or ipad air test, load properly.But When I use ipad air2 test,This situation arises.

**Comment by DennisZP** [comment]
This image background is transparent

**Comment by mousebird** [comment]
Are you using the master or develop branch?
How big is the image in pixels?  In particular, is it a power of 2 on each side?
