### ISSUE TITLE
Animated layers not behaving properly.

### ISSUE THREAD

**Issue by mosh1** [mousebird/WhirlyGlobe#314]
In branch Develop, displaying multiple layers with MaplyMultiplexTileSource and animating them causes incorrect tiles to load while panning or zooming. It seems as if incorrect tiles are being used from the tile cache.

**Comment by mousebird** [comment]
I added a property that might help you with this one.
If you set allowFrameLoading to false in MaplyQuadImageTilesLayer it'll force all the frames to load for a given tile before moving on to the next.

That should fix the apparent bug, which is really more of an interaction between the empty frames and which frame you're displaying.

**Comment by mosh1** [comment]
I verified setting allowFrameLoading to false fixes the behavior, so the cause is due to behavior of frame loading. I've also noticed the master branch does not exhibit the behavior. Is the progressive loading code not in that branch? 

By 'apparent bug' - does that mean it's not actually a bug and I need smarter logic to avoid the empty frames? Thanks!

**Comment by mousebird** [comment]
I bet it was an optimization.  I must have taken out the clear when a dynamic texture region is released.

I could either put that back or do something a little more helpful, like copy nearby frames over to the empty frames.  I'll have to give it some thought.

In any case, this is at least working as expected for you now, so I'll shelve this particular bug.

**Comment by mousebird** [comment]
Fixed this one in 2.4.  All the frames are now cleared out when a dynamic texture region is released.
