### ISSUE TITLE
MapzenSource layers not working in develop branch.

### ISSUE THREAD

**Issue by mosh1** [mousebird/WhirlyGlobe#315]
Branch: develop

Tried to get MapzenSource layer working in TestViewController and it doesn't show. First I had to rename the MapzenStyles.json resource to MapzenGLStyle.json in the test project as that was what the test code was calling.

After that, enabling the Mapzen vector layer doesn't show anything. I've verified http accesses are working correctly to fetch the vector tiles however they don't appear over the base map.

**Comment by mousebird** [comment]
Turns out I hadn't pushed the right GL style.
It's actually in the resources repo, so just cd into resources and do a "git pull".  That should get you the GL style.

Try it with the correct style and let me know if that works.

**Comment by mosh1** [comment]
Yep, works now. Thanks.
