### ISSUE TITLE
Can't Make Other View Controller Initial View

### ISSUE THREAD

**Issue by wullrich19** [mousebird/WhirlyGlobe#317]
I have been trying to get this resolved, but have had no progress yet. 

I want Xcode to run and have a LoginViewController load first as the initial ViewController, instead of the ViewController that contains WhirlyGlobe. I have labeled the LoginViewController as the initial view controller through Storyboard, and even tried to push it programmatically. But no matter what I do I can't seem to have any other View Controller besides the view with the WhirlyGlobe to load first. I was wondering if there is some setting or aspect of WhirlyGlobe that makes this happen. OR is there a suggestion for making this not happen? Thanks!

**Comment by mousebird** [comment]
There's no reason this shouldn't work.  I bring up WhirlyGlobeViewControllers all the time during an app's run.

Odds are it's something funny in the Storyboard or the way you're invoking the view controller.  What does the code look like for the programmatic case?

**Comment by wullrich19** [comment]
I tried messing around with this: 

-------------------------------------------------------------------------------------------------------------------------------------
self.window = [[UIWindow alloc] initWithFrame:UIScreen.mainScreen.bounds];
UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"MainStoryboard" bundle:nil];

UIViewController *viewController = [storyboard instantiateViewControllerWithIdentifier:<MainSB>];
self.window.rootViewController = viewController;
[self.window makeKeyAndVisible];

return YES;
-------------------------------------------------------------------------------------------------------------------------------------

The strange part is that no matter which class I set the ViewController to be in Storyboard, WhirlyGlobe keeps appearing first - works very well, just needs to wait its turn.

**Comment by mousebird** [comment]
Okay, looks like this is just Storyboard stuff.
In general, I don't help people debug that.  Just not enough time to help out with general UIKit stuff.
However, I see the problem right there.

When you call instantiateViewControllerWithIdentifier: you're not giving it an identifier.  An identifier, in this case, is a string you assign *in Interface Builder* and then reference right here.  I assume, by not passing in an identifier, the Storyboard is just picking one of the view controllers in it that doesn't have an identifier.

So go assign your identifiers in the Storyboard and then reference one of them here.

**Comment by wullrich19** [comment]
That snippet was just a generic case of what I was doing in my appdelegate. I changed it so many times to get it to work i cant even remember which one I tried first. BUT I managed to get the LoginViewController to appear first now after I renamed all the storyboard IDs and restarted Xcode. Not sure why this worked but it did! So thanks for the help - much appreciated
