### ISSUE TITLE
remove iOS4 code

### ISSUE THREAD

**Issue by andrewljohnson** [mousebird/WhirlyGlobe#321]
I noticed in SceneRendererES2 a comment referencing code needed for pre-iOS4: https://github.com/mousebird/WhirlyGlobe/blob/master/WhirlyGlobeSrc/WhirlyGlobeLib/src/SceneRendererES2.mm#L831

Can this code be removed, also removing the warning on line 821?

**Comment by mousebird** [comment]
I've been ripping this stuff out in 2.4.  It was generating compile warnings with newer OS'.
Should be long gone now.

**Comment by andrewljohnson** [comment]
Thanks, I'll check out 2.4.
