### ISSUE TITLE
Selection priority

### ISSUE THREAD

**Issue by alasarr** [mousebird/WhirlyGlobe#323]
Is it possible to define a selection priority for vectors? Something similar to kMaplyDrawPriority but for selection.

For example, I've a geojson with the lakes and a geojson with the countries, I'd like when click on lake didSelect will catch the data of the lake.

As workaround what I'm doing is drawing the lakes before the layer of countries.

**Comment by mousebird** [comment]
Is this a selection priority separate from drawPriority?

There is a multi-selection interface in the develop branch.  It's hard to use because it returns a whole list of features, but it might allow you to do what you want.
