### ISSUE TITLE
Cocoapods install compile issue

### ISSUE THREAD

**Issue by sam899** [mousebird/WhirlyGlobe#325]
I'm getting multiple compilation issues when installing v2.3 with cocoapods (0.37.2) for iOS

eg:

glues.h platform not supported
boost/shared_ptr.hpp file not found

**Comment by mousebird** [comment]
The 2.3 podspec is completely broken.

However, the brand new 2.4 beta podspec is... brand new.  Give it a try!
https://github.com/mousebird/WhirlyGlobe/blob/develop/WhirlyGlobe.podspec

**Comment by sam899** [comment]
Thanks!
Nearly there with 2.4 beta - just an error on `use of undeclared identifier DDXMLElementDummyFunc();` and `DDXMLDummyFunc();`

I noticed in the [2.3 podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/WhirlyGlobe/2.3/WhirlyGlobe.podspec.json) passes these in as `compiler_flags` so maybe those need to be put in the podspec? Might have a go tomorrow!

**Comment by mousebird** [comment]
That's the KissXML library.  It should be turning up in the Podspec now.
Make sure it's pulling in 2.4_beta1.

**Comment by sam899** [comment]
Ah ha, that might explain it - Another library I use is pulling in the KissXML library, which is overriding the local one in WhirlyGlobe..

**Comment by sam899** [comment]
I’ve been looking into this more to figure out why a custom version of KissXML is used. Instead of using the Dummy Funcs to load in the categories, it looks like you can pass -ObjC to the linker to pull in the categories?

http://stackoverflow.com/questions/2567498/objective-c-categories-in-static-library

**Comment by mousebird** [comment]
I went through this dance a while ago.  If you use that flag, you pull in absolutely everything, causing lots of other problems.

This is a fix for the binary distribution, and maybe the source distribution.  I'll #ifdef it out of the podspec and try again next week.

**Comment by mousebird** [comment]
I believe these are sorted out in 2.4.
