### ISSUE TITLE
MaplyPagingDelegate's minZoom/maxZoom properties versus Swift

### ISSUE THREAD

**Issue by dhmspector** [mousebird/WhirlyGlobe#326]
I have been working though the tutorials for using various parts of WhirlyGlobe in Swift and its all gone perfectly until I got to the CartoDB section where I find that I cannot get past the implementation of minZoom and maxZoom as required by  MaplyPagingDelegate.  No matter what flavor of integer i declare them as Swift asserts that they do no comp form to the protocol and that they properties are missing getter functions.

The declaration is as simple as you'd expect:
var minZoom : Int  
var maxZoom : Int

results in...
/MaplyTest/MapLayers/CartoDBLayer.swift:11:1: Type 'CartoDBLayer' does not conform to protocol 'MaplyPagingDelegate'
/MaplyTest/__ObjC.MaplyPagingDelegate:10:14: Protocol requires function 'minZoom()' with type '() -> Int32'
/MaplyTest/MapLayers/CartoDBLayer.swift:14:9: Candidate is not a function

...same for 'maxZoom'

My next attempt was to, since there are horde of Int types in Swift, explicitly use Int32 since that's the type the compiler is referencing.  Same result.  :disappointed: 

Overriding the getters/setters are either the variable declaration level  returns the same errors; and overriding them as top level functions (e.g., "func minZoom() -> Int32 ...") generates an error -- naturally  -- about an illegal redeclaration of the getter for the property.

I am clearly missing something here - anyone else run into this?

**Comment by mousebird** [comment]
Huh.  That sounds really odd.  I was hoping to do a Swift run-through before the 2.4 release, but I don't immediately know what's causing this.

**Comment by dhmspector** [comment]
Happy to share my very literal translation of the Obj-C tutorial code if would be helpful. Literally everything else in working thru all the tutorial sections worked like a champ.

**Comment by mousebird** [comment]
It would be interesting to see, thanks!

**Comment by dhmspector** [comment]
Here you go:  https://github.com/dhmspector/Maply-swift-test
Just unzip the current binary distribution into the top level as the project file references both the framework and the tutorial resources direct from the distribution folder.

**Comment by mousebird** [comment]
José, have we pretty much resolved this now?

**Comment by jmnavarro** [comment]
Yes, it's already fixed. The CartoDB tutorial shows how to do it
