### ISSUE TITLE
Handling A LOT of Screen Markers

### ISSUE THREAD

**Issue by wullrich19** [mousebird/WhirlyGlobe#327]
I have a WhirlyGlobe View Controller in my xcode project and have been trying to figure out what to do regarding my screen markers. Currently I have my project set up so that it adds small circles (about 1.5x1.5 pixels) all over the map. The problem is, however, I am going to be having upwards of 500,000 points...a little more data than most people would want to be using.

SO...I know that there is no real limit on how many points can be added to the map, but I am desperately trying to avoid having every point load each time the globe is displayed, and especially each time the user zooms in or out. 

The only real solution that I can think of is having the images loaded (since not all 500,000 will be created at once), then updating each of the tiles that contain any of the markers to always include those markers. In other words, "re-draw" the images that make up each tile, like a tile-screenshot if you will, so that when the tile is loaded next time, the image is just the same tile like always BUT it now shows the markers which are part of the image file, appearing as if they are markers placed on top of the map. I know this method (if possible) would be much easier if the zoom functions were disabled - that way I would only be dealing with a fixed number or tiles, rather than having to update every tile for each zoom level.

If you have any suggestion, or maybe a solution on where I should go regarding this I would be very appreciative. Thanks!

**Comment by mousebird** [comment]
Rendering points into your map tiles is an interesting idea.  It might not actually be too hard.

You'd need to make a new MaplyRemoteTileSourceDelegate.  You might be able to use remoteTileSource:modifyTileReturn:forTile: to open your image, draw the points onto it with Quartz, and then hand it on to the system.

To do that, you'd want a fast way to looking up which points where in which tile.  Sorting by tiles to a given level in the coordinate system your image data is in would do it.

Or, if this is just a rendering problem for 500k points, you could just move to a particle system.  Those are brand new in 2.4 and not heavily documented, but they're ideally for drawing that scale of data.

**Comment by wullrich19** [comment]
Ok I will look into that - thanks for the response! 

I'm sure I'll figure something out - what I might do is look a little further into grouping the markers together depending on how many are in proximity, making some sort of static image layer of those, and associating it to a location.

If I make any interesting progress or breakthrough I'll post about it!

**Comment by mousebird** [comment]
Good luck!

**Comment by wullrich19** [comment]
Hey Steve, 

I was wondering if there was any further headway on WG 2.4? I know you have been talking about it for some time now and I was just curious if you had released it anywhere yet. I can’t seem to find anything concrete online regarding its whereabouts, as we were talking about the new atmospheric FX 2.4 would encompass. Either way just figured I would reach out to you real fast to see if you knew. Thanks and have a great week.

Best regards,

Will Von Ullrich
CEO & Founder 
Sickk Software LLC

**Comment by mousebird** [comment]
WhirlyGlobe-Maply 2.4 beta #7 is in the develop branch with the tag "v2.4_beta7".  I have a blog post almost ready to go detailing the new functionality.  What I'm lacking is time to get it out the door.

Soon, I think.

**Comment by CPLamb** [comment]
Hey Steve,Need help getting the post out?  If you outline it, maybe I could fluff it out for you.
Cheers,CPL
 


     On Monday, September 14, 2015 9:58 AM, Steve Gifford <notifications@github.com> wrote:
   

 WhirlyGlobe-Maply 2.4 beta #7 is in the develop branch with the tag "v2.4_beta7". I have a blog post almost ready to go detailing the new functionality. What I'm lacking is time to get it out the door.Soon, I think.—

**Comment by mousebird** [comment]
The thought did cross my mind, but it's all pretty hard core technical stuff, I'm afraid.  This is always the problem with handing things off.  :-(

**Comment by CPLamb** [comment]
Let's give it a try.  Send me what you got.  We'll worry about the cost later. 
 


     On Monday, September 14, 2015 10:15 AM, Steve Gifford <notifications@github.com> wrote:
   

 The thought did cross my mind, but it's all pretty hard core technical stuff, I'm afraid. This is always the problem with handing things off. :-(—
