### ISSUE TITLE
Sir i'm trying to update sample got problem

### ISSUE THREAD

**Issue by testingandroid** [mousebird/WhirlyGlobe#328]
Hi sir, i'm trying to use sample project and do little modification but it didn't work

pls check and help me out this problem. here is my activity.
I just want 3D globe not all so i do this thing. is it correct ? 

MainActivity.class
public class MainActivity extends Activity {

	RelativeLayout main_container;
	MapController mapControl = null;
	GlobeController globeControl = null;
	MaplyBaseController baseControl = null;
	QuadImageTileLayer baseLayer = null;
	Activity activity;
	View theView = null;

	@Override
	protected void onCreate(Bundle savedInstState) {
		super.onCreate(savedInstState);

		setContentView(R.layout.activity_main);
		activity = MainActivity.this;

		main_container = (RelativeLayout) findViewById(R.id.main_container);

		globeControl = new GlobeController(activity);
		globeControl.setPositionGeo(0, 0, 2.0);
		baseControl = globeControl;

		theView = baseControl.getContentView();

		Log.e("test", "base control :" + baseControl);

		if (theView != null) {
			main_container.addView(theView);
			Log.e("test", "theView is not null :");
		} else {
			Log.e("test", "theView is null :");
		}

	}
}

and my xml file here 
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity" >

</RelativeLayout>

**Comment by mousebird** [comment]
I don't immediately see anything wrong.  Try comparing it to the same project and see what's different.

**Comment by testingandroid** [comment]
sir i have tried alot but didn't find anything
