### ISSUE TITLE
Zoom to bounding box with padding?

### ISSUE THREAD

**Issue by tomtaylor** [mousebird/WhirlyGlobe#330]
I couldn't work out an easy way of doing this, and the APIs didn't seem to make it possible to construct this accurately (but I might be wrong!). In `MaplyViewController` is it possible to zoom to a latitude/longitude bounding box, but padded with something similar to a UIEdgeInsets in pixels?

If not, it'd be really useful to have. Thanks!

**Comment by mousebird** [comment]
Padded in pixels?  That's an interesting idea.
You could simulate it by zooming to a bounding box, asking where the corners of a slightly bigger frame are and then zooming to that.

**Comment by tomtaylor** [comment]
That’d work, except I need it to be animated. Is there an alternative?

**Comment by mousebird** [comment]
Ah, then that probably wouldn't work.
You'd need to dig into the findHeight logic to make it work.

It's a cool idea and the sort of thing I might do for support customers.  Alas, I'm a little backed up on general features at the moment.  I'll toss it into the feature requests.

**Comment by tomtaylor** [comment]
Thanks, it’s just for a little side project at the moment.
