### ISSUE TITLE
Globe loaded callback/notification

### ISSUE THREAD

**Issue by SandeepAppster** [mousebird/WhirlyGlobe#332]
Hi Steve,

We have implemented the Whirly globe in our application.

We are looking for some callback/notification when globe finishes rendering or loaded.

In delegate methods, it seems missing.

Thanks in advance....

**Comment by mousebird** [comment]
If the user keeps moving, the globe may never finish loading.  So it's an open question.

If you're loading from a remote source, there is the MaplyRemoteTileSourceDelegate.  You'll get notified for each loaded tile, so you could use one of the levels as a cutoff.  By the time that level loads... it's probably loaded enough.
