### ISSUE TITLE
Tap on Annotations

### ISSUE THREAD

**Issue by sam899** [mousebird/WhirlyGlobe#334]
Is there a way to be informed of taps on the annotation callouts?

I found a method in the `MaplyViewControllerDelegate` class (which I dont think WhirlyGlobe uses?), but cannot find a similar method in the `WhirlyGlobeViewControllerDelegate`

**Comment by mousebird** [comment]
Right, the two top level view controllers have different delegates.

There's quite a bit of new annotation code in the base view controller.  It looks like this one could be moved down and then we could add the callback to the other delegate.

I'll add it to 2.4, but you could probably do it yourself without too much trouble.  You just need to duplicate the code in the WhirlyGlobeViewController.

**Comment by sabiland** [comment]
I am using only WhirlyGlobeViewController instance. How to set MaplyViewControllerDelegate ?

**Comment by mousebird** [comment]
For the Globe it's a WhirlyGlobeViewControllerDelegate

**Comment by sabiland** [comment]
I am using 2.4 beta 8 framework. WhirlyGlobeViewControllerDelegate does not contain anything about annotations. What am I missing?

**Comment by mousebird** [comment]
Oh, I see.  I didn't read back up the Issue chain.

Still haven't added this specifically to the WhirlyGlobeViewController delegate.  It looks like I have it in there for 2.4.1, but I don't know when I'll get to that.

If you have an app that makes revenue or you work for a company that does, I would add this under a support contract.  If not, I'll try to get to it before 2.4.1 goes out.

**Comment by IOSDeveloperProgrammer** [comment]
@mousebird  have you implemented this? I  want to  give the action to annotations but not working, i treid with the screen markers. has per my requeirmant  i need to use annotations  so if any updates please let me know.
Thank you.

**Comment by mousebird** [comment]
Haven't gotten to it yet for 2.5 (e.g. 2.4.1).

**Comment by bintu1234** [comment]
@mousebird can we give the tap gesture to contantview ,But I tried That but even it is not recognising the   events.How to do that. I am using SMCalloutView can we give our own uiview.Please help me

**Comment by mousebird** [comment]
Well there's an SMCalloutView there so you can modify it as you like.  I'd think you could just put a tap gesture recognizer on one of its UIViews.

**Comment by IOSDeveloperProgrammer** [comment]
@mousebird Right now,  I want to stop the tap action on map. if i tap  anywhere on globe , its' showing action. 
Thank you.
