### ISSUE TITLE
Clustering Markers

### ISSUE THREAD

**Issue by sam899** [mousebird/WhirlyGlobe#336]
Is it possible to cluster markers with a count?
eg https://www.mapbox.com/mapbox-ios-sdk/examples/marker-clustering/

**Comment by mousebird** [comment]
At the moment, no.  I keep estimating that for clients, but so far no one's bitten.

**Comment by JesseCrocker** [comment]
@sam899  If your using a MaplyQuadPagingLayer for markers, this is relatively easy to implement in the MaplyPagingDelegate.

**Comment by mousebird** [comment]
Very true.  And that's one of the reasons it often gets dropped from contracts.  We'll switch to a way of storing and retrieving the data that doesn't depend on an in-memory clustering.

What's missing in the general in-memory case is the pre-sorting pass.  You'd then use the results, as Jesse intimated, with a MaplyQuadPagingLayer.

**Comment by sarahansen223h** [comment]
This would be very, vey nice to have!

**Comment by mousebird** [comment]
Implemented in 2.4.1.
