### ISSUE TITLE
WhirlyGlobe Edge - Glow?

### ISSUE THREAD

**Issue by wullrich19** [mousebird/WhirlyGlobe#341]
I was wondering if there is some sort of way to make the globe have a sort of "glow" / shadow around it, that can follow the globe as it is zoomed in and out. I thought maybe there was a way to anchor a PNG behind the globe and have it zoom in sync with the globe, but i am not quite sure how to go about doing that. 

If not, no worries, just thought it might be a cool touch. Thanks!

**Comment by mousebird** [comment]
An atmospheric layer should be in 2.4.

**Comment by wullrich19** [comment]
Is 2.4 out already or coming soon? I can't seem to find out anything about it :\

**Comment by mousebird** [comment]
It's in beta, but the glow is not yet debugged.  Probably late next week.

**Comment by mousebird** [comment]
Atmosphere is working the develop branch.
