### ISSUE TITLE
Errors in XCode

### ISSUE THREAD

**Issue by haying2005** [mousebird/WhirlyGlobe#342]
Becouse the cocoapods is broken, and the binary is not the latest version, so I want to build from the source code. But when I get all the code and open the WhirlyComponentTester in XCode, some errors exist in the project of "whirlyGlobeLib" .Becouse it is the C++ code, I don't know how to solve these problems, can you help me? Or can you tell me how to get the latest version of the binary?
Thanks!

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/13112261/8586070/265ff4c4-261d-11e5-8bce-4c4364114e75.png)

**Comment by mousebird** [comment]
Looks like the glues version is out of sync.  I had to change it to avoid collision with the one shipping with the Google Maps API.

cd into the third-party directory and do a "git submodule update".  If that doesn't work try "git submodule sync".
