### ISSUE TITLE
Set Zoom limit

### ISSUE THREAD

**Issue by Breakfast404** [mousebird/WhirlyGlobe#344]
Hey noob question here:
I am trying to use the setZoomLimit method in whirlyglobe but the globe seems to continue to run at default zoom heights. How would you change the zoom height limits? Thanks!

**Comment by mousebird** [comment]
It won't move past certain hardwired boundaries based on the view constraints.  What are you trying to set it to?

**Comment by Breakfast404** [comment]
Im trying to prevent the user from zooming too far in on the globe. For example if the set minimum now is 0 then i dont want them to zoom past 8

**Comment by mousebird** [comment]
I suggest doing a getZoomLimits first and then basing your setZoomLimits on those numbers.  Keep the minimum, but adjust the maximum.
