### ISSUE TITLE
MaplySharedAttributes are #defines

### ISSUE THREAD

**Issue by mousebird** [mousebird/WhirlyGlobe#345]
The constants in MaplySharedAttributes really shouldn't be #defines.  They should be externs with the actual strings in another file.

**Comment by mousebird** [comment]
Instead of #defines these should be externs with the definition of the NSStrings in a separate file.

This is a standard pattern, which I'm breaking.

**Comment by rghosh0** [comment]
OK, this one should be done; in the develop_2_4_1 branch.
