### ISSUE TITLE
Problems with the markers

### ISSUE THREAD

**Issue by sarahansen223h** [mousebird/WhirlyGlobe#346]
Hello,

I want to  remove the marker and re-create it every-time the globe is 

taped, because the information for the marker is going to get updated on very tap. The amount of 

markers can't be fixed, because sometimes it can be 1 marker and sometimes 100 markers.

 
what i did to test was to place: WGComponentObject *markers_Obj;  inside the "@interface".

and wrote this:

- (void)globeViewController:(WhirlyGlobeViewController *)viewC
                   didTapAt:(MaplyCoordinate)coord
{
    
    
  [theViewC removeObject:markers_Obj];
    
    UIImage *icon = [UIImage imageNamed:@"map_pin.png"];
    NSMutableArray *markers = [NSMutableArray array];
    
    MaplyScreenMarker * the_marker = [[MaplyScreenMarker alloc] init];
    
    the_marker.image = icon;
    the_marker.loc = MaplyCoordinateMakeWithDegrees(6.3, 52.2);
    the_marker.size = CGSizeMake(40,40);
    [markers addObject:the_marker];

    
    markers_Obj = [theViewC addScreenMarkers:markers desc:nil];
    
    

}

The problem is that sometimes the marker shows up and sometimes it don't. Please help me fixing it and show me how.
   

this still a problem for me...

**Comment by mousebird** [comment]
Be sure to set layoutImportance = MAXFLOAT for each marker.

It also wouldn't hurt to use the mode: parameter for the add and remove calls.  Either do them on the current thread or dispatch another thread to do it.  That way they'll appear and disappear reliably if you're doing that quickly.

**Comment by sarahansen223h** [comment]
how can the mode parameter be used??

**Comment by mousebird** [comment]
From [the docs](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_3/Classes/MaplyBaseViewController.html#//api/name/addScreenMarkers:desc:mode:).  If you pass in MaplyThreadCurrent the operations will happen immediately on the current thread.

This is convenient if you're adding and removing a lot of things quickly.

If you're not, passing in MaplyThreadAny is fine.

**Comment by sarahansen223h** [comment]
Thanks alot! i'm going take a look

but Is there anyway to reset all the layoutImportance?

- btw what i did with the marker is: layoutImportance =1.0+n;  where n keep increasing with 1.

**Comment by mousebird** [comment]
No, it's set to 0 by default.

**Comment by sarahansen223h** [comment]
I see well... it look like it does not update the layoutImportance value later on for the objects that is already made...

**Comment by mousebird** [comment]
That's right, updating an objecting you've already added to the view controller will do nothing.

**Comment by sarahansen223h** [comment]
thanks i'm going find a way around :)

**Comment by sarahansen223h** [comment]
I did:   [theViewC removeObjects:our_user_data]mode:MaplyThreadCurrent]; but it did not work...

**Comment by sarahansen223h** [comment]
our_user_data is of type:   NSMutableArray *

**Comment by mousebird** [comment]
Does that array contain MaplyComponentObjects or MaplyScreenMarker objects?  It should be the former.

**Comment by sarahansen223h** [comment]
It contain MaplyScreenMarker objects, but could you please explain more as english is not my native language.

**Comment by mousebird** [comment]
Whenever you call addScreenMarkers it returns a MaplyComponentObject.  You need to keep track of those and it is those objects you pass to removeObjects:

**Comment by sarahansen223h** [comment]
but should'nt [theViewC removeObjects:our_user_data]mode:MaplyThreadCurrent]; remove all the markers inside our_user_data?

**Comment by mousebird** [comment]
No.  You must pass in the MaplyComponentObjects passed back to you from the addScreenMarkers call.

**Comment by sarahansen223h** [comment]
so i can create NSMutableArray that holds the MaplyComponentObject's and delete the whole thing in a single line?

**Comment by mousebird** [comment]
Yes, removeObjects: takes an NSArray of MaplyComponentObject.

**Comment by sarahansen223h** [comment]
Perfect, thanks sir. I really appreciate your help and time. Thanks again :)
