### ISSUE TITLE
screenMarker layoutImportance values causing images to offset

### ISSUE THREAD

**Issue by bryanheitman** [mousebird/WhirlyGlobe#347]
Changing layoutImportance from MAXFLOAT to something else, for example: 100 causes the icon/image displayed as a screenMarker to change locations.
<img width="761" alt="screen shot 2015-07-14 at 11 55 35 am" src="https://cloud.githubusercontent.com/assets/13205913/8679731/088741ec-2a22-11e5-9ba2-6c0d1d702764.png">

<img width="759" alt="screen shot 2015-07-14 at 11 55 58 am" src="https://cloud.githubusercontent.com/assets/13205913/8679737/0ba89394-2a22-11e5-8acf-2eedb02386c1.png">

**Comment by mousebird** [comment]
I believe this one was fixed inadvertently by Jesse.
