### ISSUE TITLE
marker.offset Y direction has changed since 2.2

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#358]
Not sure if this is an intended behavior or not.
in 2.2 to line up the bottom of a marker image with the marker location I was using an offset of `CGPointMake(0, -(size.height/2))`

In 2.4 to achieve the same effect im using `CGPointMake(0, (size.height/2))`

**Comment by mousebird** [comment]
Yeah, I ripped out that entire subsystem screen label/marker subsystem and replace it with a shader based one.  In the course of doing that, the offsets moved.

At this point there are more apps using the new than the old, so I guess I'll leave it that way.
