### ISSUE TITLE
Make Vector Data Lines Different Color Than Lofted Polys

### ISSUE THREAD

**Issue by wullrich19** [mousebird/WhirlyGlobe#360]
I had a quick question regarding vector data. As of right now I have the vector lines working very well, but as soon as I turn on the LoftedPolyBase and LoftedPolySide the vectors become indistinguishable from the fill. I was wondering if there was a way to specify the "fill color" of these poly shapes. Thanks!

Here is what I am dealing with:
![screen shot 2015-07-30 at 1 33 43 pm](https://cloud.githubusercontent.com/assets/12819833/8990352/a139c6cc-36bf-11e5-90b5-359f622ea17d.png)

**Comment by mousebird** [comment]
Yes, you can set the side and top separately if you want to.
Check out the documentation for [lofted polys](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_3/Classes/MaplyBaseViewController.html#//api/name/addLoftedPolys:key:cache:desc:).
