### ISSUE TITLE
Removing a MaplyQuadImageTilesLayer with a MaplyMultiplexTileSource crashes

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#361]
What im trying to do:
I've got a layer showing animated weather radar, I need to change the sources, but there is no way to change the sources, so im removing the layer, making a new one, and adding the new layer to the map.

The problem:
As soon as i no longer have a reference to the old MaplyQuadImageTilesLayer it gets deallocated, and the app crashes. The crash is in [MaplyMultiplexTileSource dealloc].

<img width="2557" alt="screen shot 2015-07-30 at 8 28 30 pm" src="https://cloud.githubusercontent.com/assets/2048291/8999867/63437f6e-36fd-11e5-94a4-71ac4081486f.png">

**Comment by mousebird** [comment]
I'm having trouble replicating this one.  Any chance you could reproduce it in the test app?
I've tried tearing down the Forecast.IO example, but it exits cleanly.

**Comment by JesseCrocker** [comment]
I tried briefly to replicate it in the test app and couldn't, I'll try harder, probably tomorrow

**Comment by JesseCrocker** [comment]
Im not able to replicate this now, so maybe some other recent change fixed it. Closing. Will reopen if I can reproduce it.

**Comment by mousebird** [comment]
There was a lot of action around layer teardown recently, but I believe it was *before* the version you were using.

**Comment by JesseCrocker** [comment]
I pushed my test case with what i thought would crash it, but doesn't https://github.com/trailbehind/WhirlyGlobe/tree/testcase/animated-layer

**Comment by JesseCrocker** [comment]
Im seeing this crash come up in production.

**Comment by mousebird** [comment]
Is this happening a lot? The frequency seems pretty low in Crashlytics, but if you can repeat it, I'll take a look.

**Comment by JesseCrocker** [comment]
It's causing a crash on .8% of app loads, and only 30% of users have access to animated layers, so i'd say it's pretty frequent.

Im going try and see if i can reproduce it, and see if I can come up with a workaround, probably by putting in some delays between adding and removing layers.

My guess is that the difficulty of reproducing the crash is that is has to do with the the interaction between the timer that changes frames, and when the layer gets removed.

**Comment by mousebird** [comment]
That's in the fetching data structure, so it's unlikely to be setting the frame.  That takes a different path.

**Comment by mousebird** [comment]
I reviewed the code again.  All accesses to the sorted tiles are made within @sychronized blocks and the data is always copied, so there can't be any dangling pointers outside of it.

I'm going to need a repro case on this one.

**Comment by JesseCrocker** [comment]
Im wondering if reusing some or all of the tilesources from the layer being removed in the new layer could be causing the problem.

**Comment by mousebird** [comment]
Huh, that does seem a little weird.  Any reason not to set everything up again?

**Comment by JesseCrocker** [comment]
Performance optimization. Im going to stop doing that and see if it fixes the problem.

**Comment by mousebird** [comment]
I may have found this one.  I got a crash in here recently and found a small error in the cleanup.  Checked in.

**Comment by mousebird** [comment]
Closing this isn't quite right.  I'd rather just assign it to you for testing, but we don't have that option.

Reopen if it turns up again, but I think the fix is it.

**Comment by JesseCrocker** [comment]
Just shipped the fix for this, so we should know in a week or so if it worked.

**Comment by JesseCrocker** [comment]
It looks like this fix worked.

**Comment by mousebird** [comment]
Win!
