### ISSUE TITLE
Regression in MaplyQuadImageTileLayer.multiLevelLoads behavior

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#362]
I've got a tile layer that goes to zoom 16, the tiles up to zoom 15 are cached on device. Im setting layer.multiLevelLoads = [-3, -2, -1]. In 2.2/2.3 when the phone is offline and I zoom in past zoom 15 the zoom 15 tiles continue to show. In 2.4 as soon as  [layer loadError:nil forTile:tileID] gets called for the zoom 16 tile the zoom 15 tile gets unloaded.

The layer has a minVis of 0.00000326145437 on an iPhone 6, which is equivalent to zoom 19, so the zoom 16 tiles get stretched. When the phone is online and the zoom 16 tiles can be loaded this stretching happens correctly.

**Comment by mousebird** [comment]
That's odd.  I'll have to replicate that in a fake layer and try it.

**Comment by JesseCrocker** [comment]
testcase: https://github.com/trailbehind/WhirlyGlobe/tree/testcase/multi-level-loads  select map(2d), select "Quad Test Layer", zoom in to where zoom 15 tiles are showing, then zoom in a little more. What i would expect to happen, zoom 15 tiles still show, what actually happens: map is all white.

**Comment by mousebird** [comment]
Should be fixed now.

**Comment by JesseCrocker** [comment]
Fixed. Thanks!👍
