### ISSUE TITLE
need to min zoom control and set background color in globe in android

### ISSUE THREAD

**Issue by testingandroid** [mousebird/WhirlyGlobe#363]
Sir, i need to set min zoom more as it now, i have tried to do but it didn't work 
and second question i'm trying to set black background in globe but it also didn't work.It always show white color, if i set view background then it show black but obvious globe disappered. I have trying to resolve both issues from maply library also but it still it didn't work

Here is my code for zoom settings

		globeControl = new GlobeController(activity);
		globeControl.setPositionGeo(0, 0, 4.0);
		baseControl = globeControl;

		View theView = null;

		theView = baseControl.getContentView();
		
		llwhirlyglobe.addView(theView);

		QuadImageTileLayer baseLayer = null;
		String cacheDirName = null;
		QuadImageTileLayer.TileSource tileSource = null;
		RemoteTileSource remoteTileSource = null;

		if (baseLayer != null) {
			baseControl.removeLayer(baseLayer);
		}
	
		cacheDirName = "mapbox_satellite";
		remoteTileSource = new RemoteTileSource(
				"http://a.tiles.mapbox.com/v3/examples.map-zyt2v9k2/", "png",
				0, 50);

		if (remoteTileSource != null)
			tileSource = remoteTileSource;

		if (tileSource != null) {

			SphericalMercatorCoordSystem coordSys = new SphericalMercatorCoordSystem();
			baseLayer = new QuadImageTileLayer(baseControl, coordSys,
					tileSource);
			baseLayer.setSimultaneousFetches(8);

			if (mapControl != null) {
				baseLayer.setSingleLevelLoading(true);
				baseLayer.setUseTargetZoomLevel(true);
				baseLayer.setCoverPoles(false);
				baseLayer.setHandleEdges(false);
			} else {
				baseLayer.setSingleLevelLoading(false);
				baseLayer.setUseTargetZoomLevel(false);
				baseLayer.setCoverPoles(true);
				baseLayer.setHandleEdges(true);
			}

			if (remoteTileSource != null && cacheDirName != null) {
				File cacheDir = new File(this.getCacheDir(), cacheDirName);
				cacheDir.mkdir();
				remoteTileSource.setCacheDir(cacheDir);
			}
			
			baseControl.addLayer(baseLayer);
			
		}

**Comment by mousebird** [comment]
Was that an attempt to push this bug back to the top of my inbox?  That's not acceptable.

If you wanted to do that, you need to include a note asking, for instance, if I've had a chance to look at your bug.

This is an open source project and, since you're not paying, you need to be polite.

I'm back from vacation and I'll be looking into outstanding issues this week, including yours.

**Comment by testingandroid** [comment]
Sir, Sorry for inconvenience.I  just mean to say , i need your help and i'm facing problem from last 3 days.I have tried alot of things but that was not working correctly.

Sir, I need to set zoom of globe little more i.e is according to our requirement we can set zoom level of globe ?
and my second question, there is show always white background.We can change this white screen or not ?
Please help me out these problems..

**Comment by mousebird** [comment]
There's a setClearColor() in the MaplyRenderer, but it's not exposed at the MaplyBaseController level.  If you want to reach in and get the MaplyRenderer, you could set it there, I believe.

The MapView exposes get methods for minHeightAboveSurface() and maxHeightAboveSurface(), but it doesn't allow you to change them.  To modify them you'll need to reach into the C++ side for MapView and change the defaults on creation.  It's not convenient, but that's it for the moment.

**Comment by testingandroid** [comment]
ok thanks alot its working :)
