### ISSUE TITLE
2.4 version of WhirlyGlobe

### ISSUE THREAD

**Issue by sarahansen223h** [mousebird/WhirlyGlobe#364]
Hello there,

Sorry if i have marked this wrong with the issues label, but i don't know where to ask it else. What i'm trying to do is to try beta version of WhirlyGlobe, but can't find the url. Could you  please guide me to the steps to try version 2.4 for ios? i want sepcially try out the color poles feature which i'm very excited about. 

Thanks alot

**Comment by mousebird** [comment]
I haven't implement color poles in 2.4.  It's on the list of issues which, at this point, may or may not make it into 2.4.

**Comment by mousebird** [comment]
To use the beta for 2.4, you can switch to the develop branch in the github repo.

**Comment by sarahansen223h** [comment]
Okay thanks for clearing that out for me :)
- But good job you have done  and i hope to see color poles when its the right time :+1:
