### ISSUE TITLE
documentation for kMaplyWideVecMiterLimit is unclear

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#365]
`
/// This number defines a limit past which the wide vector will switch from miters to bevels
#define kMaplyWideVecMiterLimit @"miterLimit"
`
What kind of units is this in? Whats a reasonable value to use? Does past mean greater than or less than?

**Comment by mousebird** [comment]
It's the relative distance from the point that would be created from a bevel join to the center line.  Divide that by the length and we'll do a miter join if it's over this value.

By default it's 2.0.
