### ISSUE TITLE
Elevation delegate broken in develop branch

### ISSUE THREAD

**Issue by bryanheitman** [mousebird/WhirlyGlobe#366]
To recreate take component tester and run against develop branch

Results in bad output.

**Comment by mousebird** [comment]
Should work now.  The non-Cesium case is commented out in the TestViewController.m file, but I've checked it and fixed the initialization problem.

**Comment by bryanheitman** [comment]
That worked, thank you!!

Is the amount of 3d adjustable? The rocky mountains sure don’t look very grand…. Mt Rainier is the best example.

**Comment by mousebird** [comment]
You could reach in there and change the values.

**Comment by bryanheitman** [comment]
That’s one way… Could get messy. I’ll move fwd then compare with other SynVis from other vendors.

Bryan
