### ISSUE TITLE
Markers only appear when rotation has stopped

### ISSUE THREAD

**Issue by varkor** [mousebird/WhirlyGlobe#367]
If a screen marker is not visible (i.e. it's not on a part of the globe current visible) and the user rotates the globe with a swipe, the marker will not appear as soon as its position is visible on the globe—it waits until the rotation stops. This is especially noticeable if the globe is spun and left to slow down without user input.

Is there a way to make the markers appear as soon as they arrive on-screen, (as it looks a little odd to have the markers suddenly appear).

I couldn't quite tell from the description if this is the same issue https://github.com/mousebird/WhirlyGlobe/issues/296 describes or not.

**Comment by mousebird** [comment]
This is true if you have layoutImportance set to a value other than MAXFLOAT.  The layout engine only runs periodically when the user stops moving.

If you want to avoid this, you can set layoutImportance := MAXFLOAT, but then markers will overlap each other.

**Comment by varkor** [comment]
Ah, okay! It'd be nice if there was some way to combine both behaviours (it's nice to have the markers not overlap each other), but using `MAXFLOAT` is definitely an improvement. Thank you!
