### ISSUE TITLE
MaplyScreenMarker images are blurry

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#368]
MaplyScreenMarker images are fuzzy, like there is some sort of image resampling going on.
test case: https://github.com/trailbehind/WhirlyGlobe/tree/testcase/blurry-screen-markers

test case code:
```
- (void)addTestMarkers {
  MaplyScreenMarker *marker = [[MaplyScreenMarker alloc] init];
  marker.loc = MaplyCoordinateMakeWithDegrees(-120, 38);
  marker.size = CGSizeMake(32, 32);
  marker.layoutImportance = MAXFLOAT;
  UIImage *image = [UIImage imageNamed:@"state-park"];
  marker.image = image;
  [baseViewC addScreenMarkers:@[marker]
                         desc:@{kMaplyDrawPriority:@(kMaplyMarkerDrawPriorityDefault),
                                kMaplyEnable: @YES
                                }
                         mode:MaplyThreadCurrent];
  
  UIImageView *imageView = [[UIImageView alloc] initWithFrame:CGRectMake(10, 150, 100, 100)];
  imageView.contentMode = UIViewContentModeCenter;
  imageView.image = image;
  [self.view addSubview:imageView];
}
```

state-park.png is 32x32, state-park@2x.png is 64x64

![ios_simulator_-_iphone_6_-_iphone_6___ios_8_4__12h141_](https://cloud.githubusercontent.com/assets/2048291/9203205/f1f5bcd6-4012-11e5-8a52-027a2ffb1a4a.png)

**Comment by mousebird** [comment]
Should be fixed.  Might still be a problem for texture atlas textures, though.

**Comment by JesseCrocker** [comment]
This actually looks worse than before, it looks like it's using nearest pixel instead of interpolating, but it seems like the problem is that the image is being downscaled to 1x scale when the texture is created.

![screenshot_8_12_15__10_15_am](https://cloud.githubusercontent.com/assets/2048291/9229596/18549e74-40db-11e5-9c6f-548aeb08b931.png)

**Comment by mousebird** [comment]
It was ignoring the scale in UIImage.

**Comment by JesseCrocker** [comment]
Is there an easy way to choose for a marker to use linear interpolation instead of nearest? that change broke a bunch of places where I was using images that were getting scaled down.

**Comment by mousebird** [comment]
Turns out I was using GL_LINEAR for a reason.

I added an explicit addTexture: call that takes a desc NSDictionary for parameters.  You can control it there.

However, I also added some logic in the screen markers to check if the marker is the same size as the image, in which case it will default to GL_NEAREST.  So it should just work now.  Give it a try.

**Comment by mousebird** [comment]
Gonna close this one.  Reopen if it's still a problem.

**Comment by IOSDeveloperProgrammer** [comment]
@JesseCrocker  
HI
 How can i do and add multiple images based on location ?
