### ISSUE TITLE
Android : setColor: don't work in VectorInfo?

### ISSUE THREAD

**Issue by ludawei** [mousebird/WhirlyGlobe#374]
I want to add a area on the map with the following code:

```Jave
VectorInfo vi = new VectorInfo();
vi.setColor(0.0f, 0.0f, 0.0f, 1.0f);
vi.setFilled(true);
vi.setDrawPriority(100000);

mapFragment.baseControl.addVectors(voList, vi, ThreadMode.ThreadCurrent);
```

However, the area has always been the color white, the color is not my settings

**Comment by mousebird** [comment]
I'm doing some Android work next week and will take a look at this.

**Comment by ludawei** [comment]
Great, thanks. The latest version of the code works very well!
