### ISSUE TITLE
Animating globe with different height:- Loading lower layer very fast

### ISSUE THREAD

**Issue by SandeepCoder** [mousebird/WhirlyGlobe#375]
Hey Steve,

While animating the globe with only changing the height then at the beginning the loading of layers are smooth and at lower, layers are not smooth. It loading very fast so it looks like going middle to direct at bottom. 

any idea?

**Comment by mousebird** [comment]
Not sure what you're asking here.

**Comment by SandeepAppster** [comment]
When zoom in through code, lower layers are not rendered properly and landing at bottom.
code:
Initially height is 1 then
[globeObj animateToPosition:MaplyCoordinateMakeWithDegrees(currentLocationCoordinate.longitude, currentLocationCoordinate.latitude) height:0.000025 heading:globeMapView.heading time:10.0]

I will share video if needed.

**Comment by mousebird** [comment]
Yes, a video might be helpful.

**Comment by mousebird** [comment]
Haven't heard back on this one, unless it was through another channel.
I'm going to close it for now.  Reopen if you're still having the problem.
