### ISSUE TITLE
Tile Source from .tm2

### ISSUE THREAD

**Issue by varkor** [mousebird/WhirlyGlobe#376]
WhirlyGlobe currently supports using a MBTiles file as a tile source, but this format has been effectively deprecated by Mapbox, whose tools now export to .tm2. Are there any plans to support using .tm2 files (well, directories) as tile sources? This would be really handy as it's no trivial matter to convert newer maps to the old MBTiles format.

**Comment by JesseCrocker** [comment]
MBTiles have not been deprecated by Mapbox Studio styles(.tm2). A .tm2 package defines a source of vector tiles, and how to render them, but does not actually contain any geographic data. There are lots of possible sources for the vector tiles, it could be a url, a .tm2source(which is really a mapnik xml file for creating vector tiles), or the source of vector tiles could be an MBTiles file containing vector tiles. WhirlyGlobe currently supports reading vector tiles from a URL or MBTiles.

Directly supporting .tm2sources is probably beyond the scope of WhirlyGlobe, as it would require bundling Mapnik.

As for "no trivial matter to convert newer maps to the old MBTiles format", im guessing you mean creating an MBTiles file containing raster tiles, and while it might not be trivial, it's not that hard. But your probably better off just creating an MBTiles file of vector tiles, which is not that hard.

Approximate example of creating MBTiles of vector tiles:
```
FROM=“bridge://./source.tm2/data.xml”
TO=“tiles.mbtiles” 
mapbox-studio/node_modules/tilelive/bin/tilelive-copy \
    $FROM $TO \
    —concurrency=$((`nprocs` * 16))” \
    —scheme=scanline \
    —bbox="$BBOX" \
    —minzoom=$MINZ \
    —maxzoom=$MAXZ
```
Also see https://github.com/mapbox/mbtiles-spec/issues/43

**Comment by mousebird** [comment]
Jesse summed it up well.

Mapbox is doing a lot of new development and deprecating some old stuff as well.  I'm following along as best I can and, in the future, I see a lot of promise with Mapbox GL styles and MBTiles files containing vector tiles (or) online vector tiles.  The old stuff, MBTiles files full of image tiles, will continue to work just fine.

**Comment by varkor** [comment]
@JesseCrocker — Thank you, that was a very detailed explanation! That tilelive tool was also very helpful. Thanks for correcting my misconceptions!
