### ISSUE TITLE
Crashing on iOS 7.1.1 in Ipad

### ISSUE THREAD

**Issue by patriksharma** [mousebird/WhirlyGlobe#378]
App is crashing in I-pad. When i symbolicated the crash log , I got crash in below line. 
In case you need crash log file and .dsym file i can provide that to you. 
Any idea ? 

-[WhirlyGlobeSphericalEarthLayer process:] (in LifeScience) + 474
SampleGreatCircle(MaplyCoordinate, MaplyCoordinate, float, std::__1::vector<Eigen::Matrix<float, 3, 1, 0, 3, 1>, std::__1::allocator<Eigen::Matrix<float, 3, 1, 0, 3, 1> > >&, WhirlyKit::CoordSystemDisplayAdapter*, float) (in LifeScience) + 656

**Comment by mousebird** [comment]
It's likely your input data isn't quite right.  Do you have a linear with one point perhaps?

**Comment by patriksharma** [comment]
Yes , fixed. Making changes in that fixed crash on Ipad 

thanks :)
