### ISSUE TITLE
 Can I change the background color of Country?.

### ISSUE THREAD

**Issue by patriksharma** [mousebird/WhirlyGlobe#379]
I want to change the color of Hong kong country because its showing yellow , which is same color for China. 

is that possible ? in which class i need to change it ? 
any help

**Comment by mousebird** [comment]
You will have to sort through your vectors, identify one country and add that country with a different color.  Or you can just set the kMaplyColor on that particularly country.  That will work for vectors and color.

**Comment by patriksharma** [comment]
I have tried changing the MAP_COLOR=2.0 to something else to change country color in HKG.geojson
but it didn't worked . 
its still showing the same color. I tried with different numbers but didn't worked ?

**Comment by patriksharma** [comment]
Yes , that works now. 
Changing Kmaplybackground color and Kmaply color property works fine.
