### ISSUE TITLE
Example of atmosphere implementation

### ISSUE THREAD

**Issue by varkor** [mousebird/WhirlyGlobe#382]
I notice there are quite few excitingly-named commits in the `develop` branch pertaining to atmospheric rendering, as well as moon and star positions, and in https://github.com/mousebird/WhirlyGlobe/issues/341 you mention that the atmosphere is now working — I don't suppose you could provide a small snippet showing how to add it to a `WhirlyGlobeViewController`? I tried simply initialised a `MaplyAtmosphere` object with `initWithViewC:`, but it appears there's more to be done to set it up.

Thank you! It sounds like a great feature and I'm looking forward to trying it out!

**Comment by mousebird** [comment]
There's an example in the ComponentTester app.  Just search for MaplyAtmosphere.

**Comment by varkor** [comment]
I'm not sure if I'm missing something, but it appears, from the ComponentTester, that initialising the MaplyAtmosphere with the globe view controller and then setting the sun direction should be enough to display the atmosphere, but when I try it outside of the ComponentTester no glow is displayed. Is there something else I should be doing?

**Comment by mousebird** [comment]
You need to set up the light with the sun direction.  It's all in addSun in the component tester app.  You can leave off the moon and sun models if you don't want those.
