### ISSUE TITLE
Need to save globe in sdcard or in local for offline mode

### ISSUE THREAD

**Issue by testingandroid** [mousebird/WhirlyGlobe#385]
Hi sir, i need to save globe in  local in both ios and android for the purpose of using 3D Globe offline mode in app. So do you have any idea how we can do this or is this possible to do or not.
If you have some idea please share your code or give some idea .

thanks

**Comment by mousebird** [comment]
That's really an android implementation issue.  Outside the scope of the
toolkit.

**Comment by testingandroid** [comment]
Sir could you please confirm is this possible in Iphone or not ?

**Comment by jmnavarro** [comment]
It's possible. You just need to use any persistence mechanism (i.e. CoreData, sqlite or plain data files)
