### ISSUE TITLE
some advices 

### ISSUE THREAD

**Issue by ludawei** [mousebird/WhirlyGlobe#389]
Can merge the WhirlyGlobeViewController and MaplyViewController into a new ViewController, this ViewController has a maplyType property value can be MaplyGlobe, MaplyGlobeWithElevation, Maply3DMap, Maply2DMap.
And add some transition animation when switch the map type, which will make switch the map looks great;

**Comment by mousebird** [comment]
It's not easy to transition between a 2D and 3D map.  If you can do it, you're probably just faking it with a 3D map.  I'll add it to the feature request list, but it's only something I'd do if a client paid me.
