### ISSUE TITLE
"make: *** No rule to make target ... Stop. " When assemble Android native library

### ISSUE THREAD

**Issue by al11al** [mousebird/WhirlyGlobe#396]
Hi I am trying to assemble native .so files to make it possible to use as library project in Eclipse project. After jni files have being compiled and :buildNative message appears in gradle debug log it says "make: *** No rule to make target `jni/../../../third-party//proj-4/src//PJ_eck5.c', needed by `obj/local/arm64-v8a/objs/Maply/__/__/__/third-party//proj-4/src//PJ_eck5.o'.  Stop." Any ideas what can it be?
```code
:buildNative
make: Entering directory `/media/al/E02EF2032EF1D290/ar3/WhirlyGlobe/WhirlyGlobeSrc/Android'
make: *** No rule to make target `jni/../../../third-party//proj-4/src//PJ_eck5.c', needed by `obj/local/arm64-v8a/objs/Maply/__/__/__/third-party//proj-4/src//PJ_eck5.o'.  Stop.
make: *** Waiting for unfinished jobs....
make: Leaving directory `/media/al/E02EF2032EF1D290/ar3/WhirlyGlobe/WhirlyGlobeSrc/Android'
:buildNative FAILED
Error:Execution failed for task ':buildNative'.
> Process 'command '/home/al/codeworks/ndk/ndk-build'' finished with non-zero exit value 2
Information:BUILD FAILED
Information:Total time: 4.741 secs
Information:1 error
```

**Comment by mousebird** [comment]
Are the submodules there?  Look for the third-party directory at the top of the repo.  If not, do the "git submodule init" "git submodule update" dance.

**Comment by al11al** [comment]
Oh, sorry and thanks a lot for this

**Comment by gulguruth** [comment]
Sorry for posting on such an old thread, but I'm having the exact same problem and I did do the submodules thing and I see the third party folder, (only containing 'kompex-sqlite-wrapper') any other causes for this issue?

**Comment by mousebird** [comment]
I'm not quite sure what you're asking.  Perhaps you should start a new Issue.
