### ISSUE TITLE
Loading up the inner level vector tiles first. How to differ outer level tiles loading?

### ISSUE THREAD

**Issue by ambientlight** [mousebird/WhirlyGlobe#397]
My MaplyPagingDelegate has a zoom range from 6 to 17.
When my initial height correspond to the level 17, say, I will still be requested with tiles starting all way from level 6 to level 17. 

I would like to load tiles in the bottom-up way. 

However, if I don't call tileDidLoad for a given requested tileID, it won't obviously request child inner level tiles. (If I do, then when zooming out to an outer level, my PagingDelegate won't be requested for a outer level tiles, since I already called tileDidLoad on that tile).

__How should I differ the outer level tile loading?__

(My current approach is having a timer that would track zoomLevel changes, when I do zoom out to an outer level, I would add the vectors that correspond to the inner tiles to their parent tile, no really sure this is the right way)

**Comment by mousebird** [comment]
You do have to call tileDidLoad every time you've finished loading a tile.  Otherwise the loader will get stuck.

You can have the paging layer just request the highest res tiles with the singleLevelLoading option.

It sounds like you have additive features.  That is, there are features in zoom level 6 that needs to show up all the way through 17 and beyond.  If you're doing additive geometry, you have to let the pager load starting at zoom level 6.  You can't use single (or multi) level loading mode.  It must start at level 6.

**Comment by ambientlight** [comment]
Understood. 

I need offline vector maps, and for that I am parsing from the raw OSM XML from Overpass API. I do add features in additive way based on corresponding tags for zoom levels (like administrative borders from Level6 and so on). But if my initial height corresponds to level15, and I don't have all that data in my internal db, I really should start querying from level15, since overpass queries would take long time to complete in general, so calling tileDidLoad for outer level tiles, and then querying the lowest level features and then merging these features in the outer level tiles seems something that can improve the feature loading time. 

Any suggestions?

**Comment by mousebird** [comment]
Hmmm, how about breaking it into two separate layers?  One for the expensive high res features you want for a single zoom level (e.g. roads) and one for the lower level features?

In general I've moved away from additive features and OSM data.  I liked that approach, but the open source world appears to be heading in the other direction.  Replicating data per tile is just much simpler for developers to understand.

**Comment by ambientlight** [comment]
Thanks, that seems to be a pretty good option.
Interesting, in which direction you think it is heading?

**Comment by mousebird** [comment]
Individual vector tiles with all the necessary information.  It just seems to be easier on people.

**Comment by ambientlight** [comment]
Yeah, you are right, but less streamlined and generally much larger data sets to load. Well, thanks a lot for the insight.

**Comment by JesseCrocker** [comment]
If your making your vector tiles properly, they will definitely not be larger than OSM xml.

**Comment by mousebird** [comment]
It's a matter of duplication.  If you've got a big water feature, say, which belongs at level 2, you have to duplicate that features all the way down to level 17.

So the result is a bigger file, but much simpler to deal with.
