### ISSUE TITLE
Screen markers only at certein zoom level

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#399]
Is there a way to hide specific markers above/below a specified zoom level?
Similar to this: https://www.mapbox.com/mapbox.js/example/v1.0.0/markers-only-at-zoom-level/

**Comment by mousebird** [comment]
Yes, that's what kMaplyMinZoom and kMaplyMaxZoom are for.  They refer to height above the surface, though, not zoom level.

**Comment by amirfl** [comment]
Thanks!

**Comment by amirfl** [comment]
Solved it with kMaplyMaxVis and kMaplyMinVis
