### ISSUE TITLE
White screen when launch on Android

### ISSUE THREAD

**Issue by CodeCombiner** [mousebird/WhirlyGlobe#400]
Hey guys!
I have assembled Android project and imported so and jar from aar archive to eclipse as library. Tried setContentView(getContentView) in activity and then in  fragment but always blank screen.  The library loads normally, no errors in log cat. The project was assembled with option APP_ABI=' + 'armeabi armeabi-v7a x86' and without it - same result as white screen. I use ARM Cortex-A9 quad-core device. When try to assemble with option 'APP_ABI=' + (project.hasProperty('architecture') ? architecture : 'all') it says: 

```code
:buildNative
make: Entering directory `/media/al/E02EF2032EF1D290/ar3/WhirlyGlobe/WhirlyGlobeSrc/Android'
[arm64-v8a] Compile++      : Maply <= SceneRendererES.cpp
[arm64-v8a] Compile++      : Maply <= ScreenSpaceBuilder.cpp
[arm64-v8a] Compile++      : Maply <= ScreenSpaceDrawable.cpp
[arm64-v8a] Compile++      : Maply <= SelectionManager.cpp
jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//SceneRendererES.cpp: In constructor 'WhirlyKit::RendererFrameInfo::RendererFrameInfo()':
/media/al/E02EF2032EF1D290/ar3/WhirlyGlobe/WhirlyGlobeSrc/WhirlyGlobeLib/src/SceneRendererES.cpp
Error:(50, 86) error: call of overloaded 'Matrix(int)' is ambiguous
     heightAboveSurface(0), screenSizeInDisplayCoords(0), program(NULL), stateOpt(NULL)
                                                                                      ^
jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//SceneRendererES.cpp:50:86: note: candidates are:
../../third-party//eigen/Eigen/src/Core/Matrix.h:284:25: note: Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>&) [with _Scalar = double; int _Rows = 2; int _Cols = 1; int _Options = 0; int _MaxRows = 2; int _MaxCols = 1]
     EIGEN_STRONG_INLINE Matrix(const Matrix& other)
                         ^
/media/al/E02EF2032EF1D290/ar3/WhirlyGlobe/third-party/eigen/Eigen/Core
Information:(286) (Unknown) In file included
Information:(297) (Unknown) In file included
../../third-party//eigen/Eigen/src/Core/Map.h:184:8: note: Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Scalar*) [with _Scalar = double; int _Rows = 2; int _Cols = 1; int _Options = 0; int _MaxRows = 2; int _MaxCols = 1; Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Scalar = double]
 inline Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>
        ^
../../third-party//eigen/Eigen/src/Core/Matrix.h:220:34: note: Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Index) [with _Scalar = double; int _Rows = 2; int _Cols = 1; int _Options = 0; int _MaxRows = 2; int _MaxCols = 1; Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Index = long int]
     EIGEN_STRONG_INLINE explicit Matrix(Index dim)
                                  ^
make: *** [obj/local/arm64-v8a/objs-debug/Maply/__/__/__//WhirlyGlobeSrc/WhirlyGlobeLib/src//SceneRendererES.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/media/al/E02EF2032EF1D290/ar3/WhirlyGlobe/WhirlyGlobeSrc/Android'
:buildNative FAILED
Error:Execution failed for task ':buildNative'.
> Process 'command '/home/al/codeworks/ndk/ndk-build'' finished with non-zero exit value 2
Information:BUILD FAILED
```
Btw, should ndk or ndk9 be used to assemble project?

Finally assembled project well with 'mips' option and got this error when create GlobeController instance:
```code

09-06 01:45:42.593: D/dalvikvm(24416): Trying to load lib /data/app-lib/...-1/libMaply.so 0x428517a8
09-06 01:45:42.603: D/dalvikvm(24416): Added shared lib /data/app-lib/...-1/libMaply.so 0x428517a8
09-06 01:45:42.603: D/dalvikvm(24416): No JNI_OnLoad found in /data/app-lib/...-1/libMaply.so 0x428517a8, skipping init


09-06 01:37:08.013: A/libc(21665): ../../third-party//eigen/Eigen/src/Core/Matrix.h:226: Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Index) [with _Scalar = double, int _Rows = 2, int _Cols = 1, int _Options = 0, int _MaxRows = 2, int _MaxCols = 1, Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Index = int]: assertion "SizeAtCompileTime == Dynamic || SizeAtCompileTime == dim" failed
09-06 01:37:08.013: A/libc(21665): Fatal signal 6 (SIGABRT) at 0x000054a1 (code=-6), thread 22111 (Thread-30471)
```

**Comment by jmnavarro** [comment]
I'm able to compile successfully for arm64-v8a using NDK r10e
According your traces, it seems a conflict compiling Eigen code.
Did you update the submodules?

**Comment by mousebird** [comment]
I'm seeing that same compile problem on arm64.

Are you running on a mips device, though?  If not, the libMaply.so would be missing.
At least build the armeabi architecture.  I *think* that should work on your device.

**Comment by al11al** [comment]
I have downloaded submodules and updated them via "git submodule init" and then "git submodule update", should I do anything else? 
The device runs on Qualcomm Snapdragon 800, 4 cores, 2.26 GHz (LG D-802). Same error happens on LG Nexus 5 (with same processor).
I have tried the build with only armeabi (the build without architecture options) - not works. 
I will try to update to latest NDK, my NDK  is "r10c (64-bit)"

Also according to path in trace "/src/Core/Matrix.h". Probably Eigen software module still was not updated for Qualcomm Snapdragon 800 architecture. I think I had same issue with FFmpeg-Android native library last autumn untill it was updated.

**Comment by mousebird** [comment]
I suspect it's just a word size problem or something similar.  Possibly a cast in the use of the Eigen template would fix it.

**Comment by mousebird** [comment]
I've fixed the problem on arm64.  Give it a try and let me know.

**Comment by CodeCombiner** [comment]
I will check it during this hours

**Comment by CodeCombiner** [comment]
Still white screen even after compiled with latest ndk. Also tried to import plain aar to Anroid Studio an launch with API 21, same white screen. And I could not see anything except this in both Eclipse and Android Studio : 
```code
09-10 03:07:37.285  20873-20873/com.example.root.maplyexample D/dalvikvm﹕ Trying to load lib /data/app-lib/com.example.root.maplyexample-1/libMaply.so 0x42856108
09-10 03:07:37.285  20873-20873/com.example.root.maplyexample D/dalvikvm﹕ Shared lib '/data/app-lib/com.example.root.maplyexample-1/libMaply.so' already loaded in same CL 0x42856108
09-10 03:07:37.315  20873-20873/com.example.root.maplyexample I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:385>: EGL 1.4 QUALCOMM build:  ()
    OpenGL ES Shader Compiler Version: E031.24.00.02
    Build Date: 01/20/14 Mon
    Local Branch: PMH2-KK_3.5-RB1-AU61-554722-586267-set2
    Remote Branch:
    Local Patches:
    Reconstruct Branch:
09-10 03:07:37.445  20873-20873/com.example.root.maplyexample I/ActivityManager﹕ Timeline: Activity_idle id: android.os.BinderProxy@42995200 time:181428441
```

**Comment by mousebird** [comment]
If you're running the standard test app, it will come up blank to begin with.  It needs a touch event to get the globe rendering. 

If it's not the standard test app, make sure you're setting the viewer's location and adding a layer and make sure that layer is running.

**Comment by CodeCombiner** [comment]
The view initialized like this 
```code
GlobeController gc  = new GlobeController(getActivity());
MapController mc  = new MapController(getActivity());
```
The view returned like this
```code
gc.getContentView()
```
How to distinguish standard test app and not the standard test app?

**Comment by mousebird** [comment]
Are you running MaplyAndroidTester or your own app?

**Comment by CodeCombiner** [comment]
I run own app

**Comment by mousebird** [comment]
So you initialized the globe, but did you add an image layer?  Check the MaplyAndroidTester app for an example.

I've been updating the develop_3_0 tree a lot recently as I work on the Android version.  Make sure you're up to date.

**Comment by CodeCombiner** [comment]
@mousebird  you are right. I launched test app with compiled libraries and it works. I will review the initialization.
