### ISSUE TITLE
possibly loading multiple textures

### ISSUE THREAD

**Issue by rghosh0** [mousebird/WhirlyGlobe#401]
I'm creating this issue for the previously-discussed problem where translucent tiles seem to become more opaque with time (possibly because multiple identical textures are superimposed), with associated performance problem.

The video is here:
http://drive.google.com/file/d/0B9Kv4E5NP1kFVG1xZnJnRDRDN1U/view

The private repo for reproducing the problem is here:
https://github.com/rghosh0/adsbview-maply-stripped

**Comment by mousebird** [comment]
Thanks!  I'll try to sort this out in the next couple of days.

**Comment by mousebird** [comment]
I can tell you what the workaround is, but there is a real bug.

The problem is the weather layer is asking for 13 frames, but only seems to have 11.  When it tries to fetch one of the missing frames, that seems to send it into a weird tailspin.

If you just set it to 11, that'll fix it.  I'll also look into why it's going crazy when the tile fails to load.

**Comment by rghosh0** [comment]
Wow! That was fast.  That explains why some of my example programs
recreated the bug, and some didn't. OK, I'll try that.  Thanks!

**Comment by mousebird** [comment]
Fascinating bug.  I've fixed it, but the fix has its own down side.

What's supposed to happen when a frame fails to load is that we back out the entire tile.  As a result, what you'll now see in your test case is... nothing.  And that's the correct behavior.

However, it won't just keep abandoning and allocating memory as it tries to reload missing frames.  That was the bug.

The fix on your side is to not load non-existent frames.  But even if you do it shouldn't go nuts now.

**Comment by mousebird** [comment]
Oh and you can back out all those changes to try and control the problem.  The maxTiles and the simultaneousLoads can go back to normal, or at least closer to normal.

**Comment by mousebird** [comment]
Just reopen this issue if the fix doesn't work, but I think that was it.
