### ISSUE TITLE
Possible glitch in vector tile loading 

### ISSUE THREAD

**Issue by rghosh0** [mousebird/WhirlyGlobe#402]
This is a problem I'm having where, occasionally, vector tiles don't load at the right time, and their absence is noticed, but later (after panning or zooming away and back) they appear.

Here is a video with MaplyQuadPagingLayer singleLevelLoading set to false:

http://drive.google.com/file/d/0B9Kv4E5NP1kFRG9FdUVhM2EtSDA/view

At 0:11 and again at 0:54 we see the problem.

With singleLevelLoading set to true, the problem seems to become more severe, unless this is some other problem:

http://drive.google.com/file/d/0B9Kv4E5NP1kFS2R3bFpsVC05UVk/view

I'm not sure if this is related to #242 , but I am still using mode:MaplyThreadCurrent, which seemed to fix the problem at that time (with an older Maply version; not sure if that is significant)

This can be reproduced using the private repo https://github.com/rghosh0/adsbview-maply-stripped

To recreate the second video, in MapViewController.mm, set singleLevelLoading=true for nationTileSource (after line 498) and countriesTileSource (after line 526).

**Comment by mousebird** [comment]
Thanks for the test case.  I will dig into this shortly.

**Comment by mousebird** [comment]
It turns out the image case was completely unrelated.  See if you can duplicate this one and I may need to look at it again.

**Comment by rghosh0** [comment]
Sorry, I didn't realize further action was required from me until now.  This issue is still there after merging the latest changes.

![img_0149](https://cloud.githubusercontent.com/assets/1896717/9897229/ebcb39ea-5c13-11e5-8eb1-4dd7b5a13f30.jpg)

**Comment by mousebird** [comment]
Okay, good to know.  Thanks.

**Comment by rghosh0** [comment]
Rats, this seems much worse with XCode 7.3. I did several runs with both a 7.3 build and a 7.2.1 build.  The 7.2.1 build behaves as described above, but with the 7.3 build the glitches are immediate and widespread.  I will get more on this soon; for now I'll use 7.2.1 for this app.

**Comment by rghosh0** [comment]
Sorry, forgot to mention that I am using an old Maply from Sept 24, so I should really try to update Maply first before concluding that the problem's gotten worse.

**Comment by mousebird** [comment]
There might be a few changes, but I think this underlying error is still present.
