### ISSUE TITLE
Android correct marker initializtion

### ISSUE THREAD

**Issue by CodeCombiner** [mousebird/WhirlyGlobe#403]
Hi guys

Where to look for Android markers example?
In test app I tried this way
```code
baseControl.addScreenMarkers(markers, mi, MaplyBaseController.ThreadMode.ThreadCurrent);
```  
app crashes with  
```code 
A/libc﹕ Fatal signal 6 (SIGABRT) at 0x00000402 (code=-6), thread 1026 (lyandroidtester)
```
Tried this way
```code
baseControl.addScreenMarkers(markers, mi, MaplyBaseController.ThreadMode.ThreadAny);
```
No markers visible, I tried text and image markers - same effect.
Marker created this way
```code
ScreenMarker sm9 = new  ScreenMarker();
        sm.loc = new Point2d(-74.075833, 4.598056);
        sm.image = new NamedBitmap("testLabel", testMarker);
        sm.size = new Point2d(50, 50);
        markers.add(sm9);
        final MarkerInfo mi = new MarkerInfo();
        mi.setEnable(true);
        mi.setColor(125, 0, 255, 0);
```
Maybe I should initialize some markers layer? 
According to iOs example there is no need to add any layer.

**Comment by mousebird** [comment]
Locations are in radians, which should explain the second problem.  Use the FromDegrees static method in Point2d.

The first problem is just a bug.

**Comment by CodeCombiner** [comment]
Added but still not visible in mode ThreadMode.ThreadAny. Now it says 
```code
29379-29396/com.mousebirdconsulting.maplyandroidtester V/Maply﹕ Null object handle in getHandle().
```

**Comment by Superchicken1** [comment]
I have the same problem. The markers are not visible.

**Comment by mousebird** [comment]
Yes, I see the same problem.  The markers are just never showing up.

I'll sort it out in the next week or two.
