### ISSUE TITLE
Mapnik XML styles with dashed lines dont render

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#404]
The lines don't render. They worked in 2.3, now they don't.
Im going to look into this on monday.

**Comment by mousebird** [comment]
Yeah, let me know on that one.  A lot of that code had to change to support the newer versions of vector tiles.

It shouldn't be too hard to fix that.

**Comment by JesseCrocker** [comment]
It seems like this actually has nothing to do with vector tiles, but that all dashes lines are broken. 

Testcase at https://github.com/trailbehind/WhirlyGlobe/tree/testcase/dashed-lines

Here's a screenshot of the same geometry added twice, the red line has a dash pattern of [10,10], the black line has no dash pattern.
![screen shot 2015-09-14 at 7 09 50 am](https://cloud.githubusercontent.com/assets/2048291/9852165/f365aa74-5ab9-11e5-8a43-7552bb943457.png)

**Comment by mousebird** [comment]
For whatever reason you need to have both wrap flags set MaplyImageWrapX|MaplyImageWrapY.
I also made the texture a power of two, which only matters on some devices.

```
  [lineTexBuilder setPattern:@[@16, @16]];
  UIImage *lineImage = [lineTexBuilder makeImage];
  MaplyTexture *lineTexture = [baseViewC addTexture:lineImage
                                        imageFormat:MaplyImageIntRGBA
                                          wrapFlags:MaplyImageWrapX|MaplyImageWrapY
                                               mode:MaplyThreadCurrent];
```

**Comment by JesseCrocker** [comment]
I've added the wrap flag to the texture creation in MaplyVectorLineStyle, and the dashed lines show up, but they don't look right. This lines flash on and off as the map is zoomed or panned, seems like an issue with how the texture is being resampled?


![2015-09-21 07_03_58](https://cloud.githubusercontent.com/assets/2048291/9992386/f9079eb8-602e-11e5-9311-a54a31facf78.gif)



add wrap flag: https://github.com/trailbehind/WhirlyGlobe/tree/bugfix/vector-dash-line-style

**Comment by mousebird** [comment]
I'm not seeing any data showing up in that branch.
But in general, the problem might be the width.  What's the width on that?

**Comment by JesseCrocker** [comment]
I think that's a 1px wide line.

**Comment by JesseCrocker** [comment]
Is there a way to set the resampling method for the textures used for wide vectors?

**Comment by mousebird** [comment]
1 pixel isn't wide enough for the line to work.  The "line" is actually a set of polygons sampling into a texture.  The minimum is more like 3 pixels for a dashed line.

I'm using textures to do the heavy lifting here.  The idea was to keep shader complexity at a minimum on older hardware.  I'm considering going the other way and just implementing a shader for the various functionality.  It would work better in cases like this.

**Comment by mousebird** [comment]
If you look at the new addTexture:desc:mode: call you'll see one of the parameters is kMaplyTexMinFilter.  So you can set that.

However, I doubt that's it.  If it's a 1 pixel wide polygon, it may just be sampled randomly.

I'd widen it to 3pix.  It'll look like 1pix because of the ramp along either side.

**Comment by JesseCrocker** [comment]
Here's a testcase that shows dashed lines that disappear while panning, It's using a MaplyVectorTileStyleLine which is widening the width from 1 to 3. https://github.com/trailbehind/WhirlyGlobe/tree/testcase/dashed-lines2

This worked properly in 2.3

**Comment by mousebird** [comment]
I can sporadically repeat this one.  It looks different if I pan vs. let the system animate and in general the texture looks bad.

**Comment by mousebird** [comment]
I've changed the defaults on the created texture.  It seems to clean up the text case, but try it out on your data.
