### ISSUE TITLE
label offset issues with selection, layout

### ISSUE THREAD

**Issue by rghosh0** [mousebird/WhirlyGlobe#405]
There seems to be a problem with label offset.  The actual visible position of the label is fine -- it does correctly take offset into account.

But when selecting, one must tap somewhere else.  Somewhere between where the label would be with and without the offset.

And when the layout engine decides what objects to suppress (based on overlaps and importance), it seems to do this based on that same phantom location for the label.

The horizontal component of the offset seems to have no effect on the phantom location (so if you have only a horizontal offset, then the phantom location is where the label would be without any offset).

The vertical component of the offset seems to translate halfway to the phantom location (so if you have only a vertical offset, then the phantom location is halfway between where the label would be with and without an offset).

This can be recreated in the repo adsbview-maply-stripped, by checking Options >> Navigation POI, and then playing with different label offset values at line 201 in PFTileSource.mm.  For example, if you have only a horizontal offset, you will see hardly any labels, because each point feature's marker will be suppressing its own label, despite the offset.

![img_0148](https://cloud.githubusercontent.com/assets/1896717/9844237/94531f82-5a8f-11e5-9417-c8c78d838bf9.jpg)

This can also be recreated in the WhirlyGlobeComponentTester by adding a label offset in

TestViewController addScreenLabels:len:stride:offset:

**Comment by rghosh0** [comment]
New info on this issue: the two problems actually seem to be separate.  The incorrect selection problem occurred as far back as March 11, 2014 (not sure how much further).  But the incorrect overlap problem did not exist at that time, while it did exist on June 26, 2014.

The incorrect overlap is the bigger problem for us, as it causes intererence between a point feature's marker and its label.

I am trying to narrow down the problem further.

**Comment by mousebird** [comment]
I should get to this tomorrow morning.

**Comment by rghosh0** [comment]
OK, thanks.  I have narrowed down the particular change that introduces the incorrect overlap to:
https://github.com/mousebird/WhirlyGlobe/commit/9e5e39d587010139d07cd3696163fa31f80facd5

With the following diff to TestViewController.m, the problem can be recreated (by trying 2d markers and 2d labels separately and then simultaneously)

```
--- a/WhirlyGlobeSrc/WhirlyGlobeComponentTester/WhirlyGlobeComponentTester/TestViewController.m
+++ b/WhirlyGlobeSrc/WhirlyGlobeComponentTester/WhirlyGlobeComponentTester/TestViewController.m
@@ -447,7 +447,7 @@ typedef enum {HighPerformance,LowPerformance} PerformanceMode;
         marker.loc = MaplyCoordinateMakeWithDegrees(location->lon,location->lat);
         marker.size = size;
         marker.userObject = [NSString stringWithFormat:@"%s",location->name];
-        marker.layoutImportance = MAXFLOAT;
+        marker.layoutImportance = 2;
         [markers addObject:marker];
     }

@@ -489,6 +489,7 @@ typedef enum {HighPerformance,LowPerformance} PerformanceMode;
         label.size = size;
         label.text = [NSString stringWithFormat:@"%s",location->name];
         label.layoutImportance = 2.0;
+        label.offset = CGPointMake(60, 0);
         label.userObject = [NSString stringWithFormat:@"%s",location->name];
         [labels addObject:label];
     }
@@ -1121,7 +1122,7 @@ static const int NumMegaMarkers = 40000;
     if ([configViewC valueForSection:kMaplyTestCategoryObjects row:kMaplyTestMarker2D])
     {   
         if (!screenMarkersObj)
-            [self addScreenMarkers:locations len:NumLocations stride:4 offset:2];
+            [self addScreenMarkers:locations len:NumLocations stride:4 offset:0];
     } else {
         if (screenMarkersObj)
         {
```

**Comment by mousebird** [comment]
I've fixed a few things with offsets, labels, markers and selection.  Let me know if it's working for you.
Just reopen this issue if not.

**Comment by mousebird** [comment]
Note to myself.  Broke layout and rotation.

**Comment by mousebird** [comment]
Fixed!

**Comment by jerald-acacus** [comment]
@mousebird Hi Steve. I am using develop_2_4_1 and it doesn't seem to be fixed. With a vertical offset, tapping on the label does not seem to call didSelect method. But tapping on the location where the label would be without an offset works.

**Comment by mousebird** [comment]
I am using develop_2_4_1 with a vertical offset of 100 and it seems to be working.

What's the code you're using to add the labels?  I'd like to see if there's a rotation or additional offset.

**Comment by mousebird** [comment]
Reopen if you're still seeing this.
