### ISSUE TITLE
MaplyLayerThreads keep running when app is in backgrounded if no animation is in progress

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#406]
If there is an animation in progress when the app goes into the background the layer threads stop updating, but if no animation is in progress the layer threads keep running in the backgrounds, using around 2-4% of cpu time.

Im seeing [LayerThread main] keep running, and [LayoutLayer checkUpdate] using CPU time.

**Comment by mousebird** [comment]
Sure, the layer threads will keep running in the background.  I guess it might be all right to shut them down.  A few random request might pile up, but it's not likely to cause too much trouble.

**Comment by JesseCrocker** [comment]
What seems weird is they they sometimes shut down.

**Comment by mousebird** [comment]
Like actually exit?

Or do you mean they don't show up using CPU?  Because down at that level I find the sampling is a bit unreliable.

**Comment by JesseCrocker** [comment]
Im putting breakpoints on LayoutLayer.mm:110 and LayerThread.mm:255 with log messages.

**Comment by JesseCrocker** [comment]
So is [LayoutLayer checkUpdate] getting called continuously in the background the intended behavior, or should those calls stop happening when the app is in the background?

**Comment by mousebird** [comment]
It should be called every 2/10 of a second, but it doesn't do much of anything if there are no layout changes.

Or at least it shouldn't.  You could check that it's not dropping into delayCheck.

**Comment by JesseCrocker** [comment]
It seems like the problem is that the NSRunLoops are continuing to run in the background, when they should be pausing in the background.

**Comment by mousebird** [comment]
Is that something NSRunLoop does on its own?  I assumed I had to explicitly turn them off.

**Comment by JesseCrocker** [comment]
Im not sure whats causing it stop sometimes and not others. But i can reliably reproduce it sometimes running in the background.

**Comment by mousebird** [comment]
I'm puzzled that it ever shuts down.  It doesn't seem like it should.

I could explicitly pause it, but I don't want to interfere with a mechanism iOS might already have in place.

So the question really is, do NSRunLoops pause in the background normally?

**Comment by JesseCrocker** [comment]
I did some more testing, and this wasn't happening in the test app, until I turned on background location updates, then it did.

**Comment by mousebird** [comment]
Well that's all kind of consistent.  If you've got background location updates going, then the app is alive and new tiles might come in and so forth.

Rather than trying to shut down the run loops, which just sounds a bit scary, can you tell me what calls are actually taking up time?  Perhaps we could short circuit them.

**Comment by JesseCrocker** [comment]
It seems to be not just location, but also possibly background networking that can trigger this.

I tried removing all layers when the app backgrounds, and there is still one thread running. Im guessing that's because I have some markers on the map.

**Comment by mousebird** [comment]
There's always one layer thread.

**Comment by JesseCrocker** [comment]
Im not sure if this https://github.com/trailbehind/WhirlyGlobe/commit/75b4fb91d614fe81110c4e47f48cb72f62c3972a is the right solution or not, but it seems to work, and reduces cpu use while in the background.

Without this path there was 1500ms of non-main thread cpu use during 5 minutes of background GPSing, with the patch it was down to 45ms

**Comment by mousebird** [comment]
That looks fine to me.  I'll look it over a bit more closely and merge it into 2.4, I think.

**Comment by mousebird** [comment]
Can you set that up as a pull request?

**Comment by JesseCrocker** [comment]
https://github.com/mousebird/WhirlyGlobe/pull/411

**Comment by mousebird** [comment]
Thanks
