### ISSUE TITLE
findHeightToViewBounds causes zoom height to snap back to default

### ISSUE THREAD

**Issue by gyrocade** [mousebird/WhirlyGlobe#407]
Works ok in the master branch.  In develop_2_4_1, any call to findHeightToViewBounds causes the view to be reset.

**Comment by rghosh0** [comment]
I seem to be doing ok with findHeightToViewBounds using develop/74be531 (Sept 10).  I'm using a 2d map view, though, and I don't let the bbox get smaller than 0.02 degrees in either dimension.

**Comment by mousebird** [comment]
Note to me:  The globe view is fine now, it's just the map view.

**Comment by mousebird** [comment]
Both fixed!
