### ISSUE TITLE
Removing and re-adding a screen marker for mimicking movement

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#408]
I'm trying to implement a user location marker. I was following the advice on https://github.com/mousebird/WhirlyGlobe/issues/267. When a user location updates, I delete the old marker (via a MaplyComponentObject) and recreate it.

The problem is the the marker appears to flash. It disappears for about a second, sometimes more, and then comes back.

**Comment by mousebird** [comment]
Use the MaplyThreadCurrent mode for the mode: argument in the addScreenMarkers: call.
That will make it add and remove the marker in real time.
For the image you're using, it's best to create a MaplyTexture from it first so you're not recreating it each time, but it won't matter that much for a single marker.

**Comment by JesseCrocker** [comment]
To do this smoothly you probably need to use a MaplyActiveObject, and to set the layout importance to MAX_FLOAT.
I've posted the class I use for this at https://gist.github.com/JesseCrocker/2df083eeb33bfc4293d5 as an example of how to manage a MaplyScreenMarker with a MaplyActiveObject. You just add the TBActiveMarker as an activeObject, it handles adding an removing the marker as needed when you update it's location or rotation.

**Comment by mousebird** [comment]
Thanks for the example!  Any chance you could turn that a tutorial?

It's also gotten a bit easier now.  You can use the beginChanges/endChanges calls to batch a whole set of updates if you're on another thread.

**Comment by amirfl** [comment]
Thank you so much. I'm still struggling to make this work though. 
@JesseCrocker I tried to use your example class, but stuck at xcode failing to import "SceneRendererES.h". Is it a private header file? If so how can I use it?

**Comment by mousebird** [comment]
He's using the lower level toolkit for that, which is pretty advanced.

Just add and remove the marker using the MaplyThreadCurrent option for the mode.

**Comment by amirfl** [comment]
I tried that, but the issue remains... The marker flashes on and off on the screen, staying off longer then on.

**Comment by mousebird** [comment]
Make sure layoutImportance is set to MAXFLOAT.

**Comment by amirfl** [comment]
Setting layoutImportance to MAXFLOAT made it look slightly better, however, the marker still flickers on and off. Just at a more steady rhythm with less "off" time.
I also tried MaplyThreadCurrent but it didn't seem to make much of a difference in this case.

**Comment by mousebird** [comment]
Make sure kMaplyFade is set to 0.

**Comment by amirfl** [comment]
Setting kMaplyFade to 0 made no change, but I tried 0.5 and It actually creates a pretty nit "pulsating" effect when the user is in motion. Not the original intention, but this may actually look cooler then the marker just moving.
Thanks for creating this awesome framework! I'm now very curious about the low level hidden api :)

**Comment by mousebird** [comment]
So what state is this in?

**Comment by amirfl** [comment]
Sorry I'll close it back for now think I found a mistake I made while working on a demo gist and screenshots.
I reopened this because sometimes the user location marker texture wouldn't load (black square), in other times it will duplicate itself, although I used only one instances of the marker, compObject and texture.
I think this happened because I created and added the texture before creating the base map. Switching the setup order seemed to have solve it for now.

**Comment by mousebird** [comment]
Make sure the textures is being added on the current thread so there's no
delay.  I'd also make sure you're on version 2.4 (develop branch).

**Comment by amirfl** [comment]
Had to reopen again since having the same problem.
1. sometimes texture will not load at all (black square).
2. Other times it will load more than once:
![screen shot 2015-12-23 at 1 23 43 pm](https://cloud.githubusercontent.com/assets/364326/11982632/ea5bbd00-a97a-11e5-9e76-c974d11384be.png)

Do I need to wrap the texture addition in a dispatch_async with main thread?
Here is a gist, with a simplified version of my view controller:
https://gist.github.com/amirfl/27726d31f98f49c1681d

**Comment by mousebird** [comment]
Use the mode MaplyThreadCurrent for all calls related to adding and remove the screen marker as well as creating the textures, if you're using those.

**Comment by amirfl** [comment]
I changed MaplyThreadAny to MaplyThreadCurrent, but still getting more than one instance of the marker sometimes

**Comment by mousebird** [comment]
Make sure you're using WhirlyGlobe-Maply 2.4, which is the develop branch.
If it's persists then it's probably a threading logic issue.

**Comment by amirfl** [comment]
Is there a compiled version of 2.4 develop?

**Comment by mousebird** [comment]
Here's a [version of the beta](https://dl.dropboxusercontent.com/u/29069465/WhirlyGlobeMaplyComponent.framework_2_4_beta8.zip).

**Comment by amirfl** [comment]
Thanks, Ill try i

**Comment by amirfl** [comment]
Unfortunately no luck with beta 8

**Comment by amirfl** [comment]
I tried replacing 
```
[theViewC removeObject:userLocMarkerCompObject];
```
  with
```
if (userLocMarkerCompObject) {
        [theViewC removeObjects:@[userLocMarkerCompObject] mode:MaplyThreadCurrent];
    }
```
This seems to solve it. :)

**Comment by amirfl** [comment]
Sorry I thought I solved it but it still comes back once in a while
