### ISSUE TITLE
A more efficient way to add many objects?

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#409]
I'm adding more than 40000 markers to WhirlyGlobe, divided into 6 different groups. Each group of markers represents a different type of airport on the map. Each one of the 6 groups has a different icon and kMaplyMaxVis values.

Once all the markers are added, WhirlyGlobe does a very impressive job of handling them. The problem is that to get the objects passed to the framework, I have to iterate through all these airports from the databse. Then I add each group to a different MaplyComponentObject to the map. In the xcode sim it works great, but testing on an iPad 4th gen, it takes about 40 seconds to get the airports to show on the map.
Is there a better way to add that many markers to the map?
Here is the gist:
https://gist.github.com/amirfl/a2cd561b3cba1e0130ea

**Comment by paulgee31** [comment]
I think a better approach is to store the airports in a data source that allows a search by geographic location. You can then search for all airports within the currently viewable geographic region and display them. This will dramatically cut down on the number of airports being displayed and keep the performance consistent across all devices.

**Comment by amirfl** [comment]
Is there a way to do this without deleting and re-adding existing markers every time the view area changes? Can you add more objects to an existing MaplyComponentIbject?

**Comment by paulgee31** [comment]
No you just delete and re-add each time the area is repositioned, use Start/End changes to do a bulk update.

**Comment by JesseCrocker** [comment]
You probably want to use a MaplyQuadPagingLayer with a class the implements MaplyPagingDelegate  that fetches the markers one tile at a time.

**Comment by paulgee31** [comment]
Yep that is the we implemented it as well, it involves a bit more work but is the better route to take ultimately.

**Comment by amirfl** [comment]
Thank you! Trying to implement this with a MaplyQuadPagingLayer.

**Comment by mousebird** [comment]
This comes up a lot.  Many of my users have their own systems in place for building the spatial databases to do this right.  I'm wondering if I can build something simple to help out with this.  Perhaps a sorted grid object that feeds into a MaplyPagingDelegate.

When we get the support contract sorted out, let's chat about what might help make this easier.

**Comment by amirfl** [comment]
@mousebird looking forward for that! :)

**Comment by amirfl** [comment]
@mousebird, hope you don't mind I'm posting this here after discussing this in the email, but just wanted to see if someone had a solution to this problem.

Im rying the MaplyQuadPagingLayer approach.
This is how I'm trying to load the markers:
http://pastebin.com/2r7GgiAF

Unfortunately, CoreData doesn't like the multi-threading. It throws an exception "CoreData: error: NULL _cd_rawData but the object is not being turned into a fault" when I try to access a variable from the fetched objects.

I've been searching all over the place on how to get CoreData to work with GCD async, with no success. Did anyone have this problem and found a solution?

**Comment by mousebird** [comment]
It's been a long time since I've used Core Data, so I can't really be too helpful here.  There are ways to use Core Data on multiple threads.

My first suggestion is to serialize your core data queries on that dispatch queue you've created.  I think you may need to set up a managed object context just for that queue as well, but it's been a while since I've used Core Data.

Then, once you've serialized those queries, you can just do the rest of it on that same queue.  It won't take very long and should work fine from any thread.

**Comment by amirfl** [comment]
Hi Steve,
Sorry for the long wait for the response. I think I’m getting on the right track with this, following your suggestions. I reroute the fetch code to use its own core data context. Just have a few problems left I’m trying to solve with this. Will post on the issue page once I get it figured out.
Amir

**Comment by amirfl** [comment]
I think I'm finally making progress, at least with the CoreData side of things. I followed your suggestions and used a local CoreData context for each call. The app doesn't crash anymore and the markers show up fairly quickly.
However, the markers that the framework chose to show are very random. Often, the most important markers, those cinside the bounds of the screen, will not show up, or only few will show up. 
I thought MaplyDataStyleAdd in the addData method might help, but the markers will not show up at all when I try it.
Here is the gist:
https://gist.github.com/amirfl/817773cb6e8703f8564d
and a video of the problem:
https://youtu.be/8agG-DaQu2Y


 

This is the new code:
https://gist.github.com/amirfl/817773cb6e8703f8564d

**Comment by mousebird** [comment]
For each marker set layoutImportance = MAXFLOAT

**Comment by amirfl** [comment]
With layoutImportance = MAXFLOAT, its acting slightly better, but still the markers are not always showing up when they are needed.
This is how it looks now: (I also decreased the amount of airports by only fetching major airports for now)
https://youtu.be/DvvOZntjwek

**Comment by mousebird** [comment]
Here's a trick I like to use to figure out if it's the paging or the database lookup.

I figure out the bounds of the tile, shrink them by 10% and then add that outline as a MaplyVectorObject.

That way I can tell if the tile did or didn't load.  If it did load, then it's my database lookup.

**Comment by amirfl** [comment]
I replaced addScreenMarkers:markers:desc with addScreenMarkers:markers:desc:mode:
as suggeted in https://github.com/mousebird/WhirlyGlobe/issues/263.

This half-solved the problem. Once all the markers in all tiles are loaded, they stay on the map. However, it takes very long sometimes to see the markers inside the current view. I can start the map on Florida for example and wait about 15 seconds before anything shows up. However, if I zoom out at that time, I see that most of the western United States and Europe are already loaded.

**Comment by mousebird** [comment]
Prioritization isn't going to be the problem.

First, make sure you're only loading on level of tiles.  Otherwise you're doing the work repeatedly.

Then try turning off your database query and just displaying the squares.  Is it fast?  Then it's your database query.  

Make sure your lat and lon fields are indexed.  Otherwise the database is looking through every single point to return the ones you want.

**Comment by JesseCrocker** [comment]
You probably also want to minimize the number of queries by setting the importance on the layer, this controls how much screen space a tile must use before it is loaded. You don't want to end up firing 20 DB queries when the map pans by 1 screen, you want to fire 1 or 2 DB queries.

```
    if(mapView.view.window.screen.scale  > 1.9) {
      waypointLayer.importance = 2048 * 2048;
    } else {
      waypointLayer.importance = 1024 * 1024;
    }
````

Another note:
It looks like your using [UIImage imageNamed:] to load your marker icons on a background thread. That might not crash in testing, but it will crash in production. imageNamed can only be used on the main thread.

**Comment by mousebird** [comment]
The importance tweak is a good one, but solve the speed issues first.  Your queries should not take that long.

**Comment by amirfl** [comment]
@mousebird  & @JesseCrocker Thanks for the suggestions. Setting the minZoom and maxZoom to the same level, as we talked on skype helped a lot. Still working on the fine details and on loading the other data levels. Will post how it goes.

**Comment by amirfl** [comment]
Works great, there is a small delay initially loading some markers on the old iPad, but I think it will be acceptable to the user. Newer devices (iPhone 6) and the xcode sim have no visible delay at all. Thanks again

**Comment by mousebird** [comment]
Excellent!
