### ISSUE TITLE
When use Mapnik style sheet, the text label is too crowded

### ISSUE THREAD

**Issue by ZkTin** [mousebird/WhirlyGlobe#410]
I use TillMill and carto_vector_dice to generate vector tills and build my own app to fetch it, all work well on my device. But the road's name labels on the road lines is too crowded. What I wonder is that how to create more space between these labels.
The css style code of this part is as follow.
![unnamed](https://cloud.githubusercontent.com/assets/6594413/9983954/4f10ade8-6040-11e5-826a-7f178810537d.png)
The text-spacing style seems to meet my requirement. But it has not been implemented in the WhirlyGlobe-Maply.

**Comment by mousebird** [comment]
First thing I'd recommend doing is moving to the develop branch.  The overlap you're seeing (from email) should be fixed there.

I don't specifically use the text-spacing fields in Mapnik, though.  But text avoidance is implemented.
