### ISSUE TITLE
Geodesic Line

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#412]
Is it possible to draw a geodesic line between 2 points in WhirlyGlobe? If no, then please consider this as a feature request. Thanks.

**Comment by jerald-acacus** [comment]
Okay it's MaplyShapeGreatCircle.

**Comment by mousebird** [comment]
Yup, that's the best way.  There's also an option on vector objects if you have some other more complex need.

**Comment by jerald-acacus** [comment]
Any chance that a geodesic line / great circle be implemented on a flat map?

**Comment by mousebird** [comment]
Probably wouldn't be too hard, but I'm a little backed up at the moment.

**Comment by jerald-acacus** [comment]
Another way to show geodesic line is from AutoTester in GreatCircleTestCase.

**Comment by mousebird** [comment]
I'm surprised it works in 2D but that's great!  Can I close this?

**Comment by jerald-acacus** [comment]
Yes it works well on 2D flat map and 3D globe.
