### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by MorganeLeBris** [mousebird/WhirlyGlobe#414]
![bug2 2](https://cloud.githubusercontent.com/assets/11585404/10076689/a1189dda-62d4-11e5-9e7e-6eba217f9c53.png)

I have this crash when i run on my device but code works well on simulator.
Any idea?

**Comment by mousebird** [comment]
What's the stack trace in the actual crash, though?

**Comment by MorganeLeBris** [comment]
![stacktrace](https://cloud.githubusercontent.com/assets/11585404/10077194/29f0394a-62d7-11e5-9732-f4478dbd6a3b.png)

Is this what you want?

**Comment by mousebird** [comment]
If you're in debug mode, it should stop when it gets the bad access.  That'll be somewhere deep within the library.  I need to know where that is.

**Comment by MorganeLeBris** [comment]
![2](https://cloud.githubusercontent.com/assets/11585404/10077420/2d3c105a-62d8-11e5-91cd-62cf53e90eab.png)
sorry if it's not what you want.

**Comment by mousebird** [comment]
That's really odd.

What device are you running on and what version of iOS?
Are you using the binary distribution, Cocoapod, or source code from github?

**Comment by MorganeLeBris** [comment]
ipad, IOS 6.1.3, binary distribution

**Comment by mousebird** [comment]
Whoa, 6.1.

Well, that distribution certainly used to work on that version of the OS, but I have no way of helping you out here.  The current version supports ios7 at a minimum and I've never seen this particular problem.

I suggest you upgrade your hardware to something more modern and see if that helps.

**Comment by MorganeLeBris** [comment]
it helps.
Thank you
