### ISSUE TITLE
Layer with transparency not shown

### ISSUE THREAD

**Issue by sam899** [mousebird/WhirlyGlobe#417]
I'm trying to add 2 mbtiles layers to the map - one of a map, and one with labels to sit on top.

The labels layer tiles are mostly transparent, apart from the actual layers.
However, I'm not able to get the labels layer to display, even when this is the only layer drawn. As soon as I add a background colour instead of transparent to the tiles, the layer is displayed correctly.

I've uploaded some sample mbtiles with transparent / non transparent backgrounds here: https://dl.dropboxusercontent.com/u/3423599/Map%20labels%20layers.zip

Note: I'm using the develop branch

**Comment by mousebird** [comment]
Can you extract one of the individual images from the MBTiles?  I'm wondering if the transparency is somehow set on the whole image.

**Comment by sam899** [comment]
I can see the labels ok in Xcode when viewing the mbtiles file so definitely seems to have exported ok.

**Comment by mousebird** [comment]
If you just add the labels layer and set the clearColor in the view controller to something really obvious, like [UIColor redColor], so you see anything?

**Comment by sam899** [comment]
Nope, nothing displays :-(

I'll give it a go when I get home with a semi-transparent background on the layer to see if that shows anything!

**Comment by sam899** [comment]
OK, so I've found that if I make the map background almost transparent, i.e `background-color: rgba(255, 255, 255, 0.01);`, the layer is shown on the globe. As soon as it drops to full transparency, it no longer displays!

I've tried the mbtiles layer on a different map library and it seems to display correctly...

Any ideas?

**Comment by mousebird** [comment]
Is it showing up faintly when you've got that small amount of transparency?

I'm wondering if all the alpha values are being set to 0.

**Comment by sam899** [comment]
Settings background transparency to 0.01 looks transparent to me, and displays fine!

I'm happy to use that for now, but certainly a strange issue that setting it to 0 makes it immediately disappear

**Comment by mousebird** [comment]
It's likely to be an issue with the images themselves, if I had to guess.  As long as it works, it works.

**Comment by sam899** [comment]
Great thanks.
Realised it increases the size of my mb tiles a fair bit (2mb to 7mb) so still keen to find a solution.

Will do a bit more investigation later.

**Comment by mousebird** [comment]
I believe there's a utility out there to convert an MBTiles archive into a directory of PNGs.  I'd run that and then look at a few of the PNGs.
