### ISSUE TITLE
Problem linking with the WhirylGlobeMaply 2.3 binary

### ISSUE THREAD

**Issue by dboddy** [mousebird/WhirlyGlobe#420]
Hi,
I have downloaded the WhirlyGlobe_Maply_Distribution_2_3 binary and can compile and run the ComponentTester successfully.  I’ve followed the tutorial on adding it to a HelloEarth project, but when I build I get the following error:

ld: library not found for -lWhirlyGlobeMaplyComponent
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I’ve added all the references, including the WhirlyGlobeMaplyComponent.framework, and Xcode’s Project Navigator shows it (and I can reveal it in Finder) so I’m stumped as to why I get the error.  (For info, I’ve tried it with it with/without the *.a file and the *.dylib instead of the *.tbd files, all with no effect on the error.):

![screen shot 2015-10-04 at 10 13 55](https://cloud.githubusercontent.com/assets/15000967/10316344/c1d670d4-6c56-11e5-8100-836d38b1fda6.png)

![screen shot 2015-10-04 at 10 12 47](https://cloud.githubusercontent.com/assets/15000967/10316362/ce9f8f58-6c56-11e5-8a4e-c974bb0763ac.png)

I'm using Xcode 7.0.1

Thanks for any help

**Comment by mousebird** [comment]
You can try out the new [binary framework](https://dl.dropboxusercontent.com/u/29069465/WhirlyGlobeMaplyComponent.framework_2_4_beta8.zip) for 2.4 beta8.
Let me know if it works for you.

**Comment by dboddy** [comment]
I tried using 2.4 beta8 in a new HelloEarth project, but had exactly the same result.  Here's the issue text in full in case it sheds any light on something I might have done wrong:

Ld /Users/davidboddy/Dropbox/Developing-Dropbox/Snapshots/DerivedData/HelloEarth24beta8-ghplyegeegzvtlgyqmjcfszzmnlo/Build/Products/Debug-iphonesimulator/HelloEarth24beta8.app/HelloEarth24beta8 normal x86_64
    cd /Users/davidboddy/Developing/HelloEarth24beta8
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/davidboddy/Dropbox/Developing-Dropbox/Snapshots/DerivedData/HelloEarth24beta8-ghplyegeegzvtlgyqmjcfszzmnlo/Build/Products/Debug-iphonesimulator -F/Users/davidboddy/Dropbox/Developing-Dropbox/Snapshots/DerivedData/HelloEarth24beta8-ghplyegeegzvtlgyqmjcfszzmnlo/Build/Products/Debug-iphonesimulator -filelist /Users/davidboddy/Dropbox/Developing-Dropbox/Snapshots/DerivedData/HelloEarth24beta8-ghplyegeegzvtlgyqmjcfszzmnlo/Build/Intermediates/HelloEarth24beta8.build/Debug-iphonesimulator/HelloEarth24beta8.build/Objects-normal/x86_64/HelloEarth24beta8.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -lxml2 -lz -lc++ -lsqlite3 -framework CoreLocation -framework WhirlyGlobeMaplyComponent -Xlinker -dependency_info -Xlinker /Users/davidboddy/Dropbox/Developing-Dropbox/Snapshots/DerivedData/HelloEarth24beta8-ghplyegeegzvtlgyqmjcfszzmnlo/Build/Intermediates/HelloEarth24beta8.build/Debug-iphonesimulator/HelloEarth24beta8.build/Objects-normal/x86_64/HelloEarth24beta8_dependency_info.dat -o /Users/davidboddy/Dropbox/Developing-Dropbox/Snapshots/DerivedData/HelloEarth24beta8-ghplyegeegzvtlgyqmjcfszzmnlo/Build/Products/Debug-iphonesimulator/HelloEarth24beta8.app/HelloEarth24beta8

ld: framework not found WhirlyGlobeMaplyComponent
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by amirfl** [comment]
Have you added the framework to the target?
![screen shot 2015-10-07 at 8 24 55 pm](https://cloud.githubusercontent.com/assets/364326/10354823/2c97c0e0-6d32-11e5-9646-3066e4a5ec01.png)

**Comment by dboddy** [comment]
HI, I believe so (but maybe you can see something else that's wrong?):

![screen shot 2015-10-08 at 22 10 44](https://cloud.githubusercontent.com/assets/15000967/10380073/a8915f8a-6e09-11e5-98b9-00bb813387bb.png)

**Comment by amirfl** [comment]
Check your "Framework Search Paths" in Build Settings



![screen shot 2015-10-08 at 7 32 57 pm](https://cloud.githubusercontent.com/assets/364326/10382618/d88fa892-6df3-11e5-98a4-97bbe0f4b4ae.png)

**Comment by dboddy** [comment]
Hi, Thanks, that's fixed it.  I was following the HelloEarth tutorial up to the point where you should be able to build it, just to make sure things were OK, so there just needs to be a one-liner in there saying this needs to be added (for people like me who didn't know).  There's already a similar bit for the Header Search Paths.  

Thanks to both of you for replying.

**Comment by todlevi** [comment]
I'm getting the same error as above, but modifying the Framework Search Path doesn't help. I'm using xcode 7.0 beta. I'm following the tutorial. For reference, here is the error again:

ld: framework not found WhirlyGlobeMaplyComponent
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm also receiving 4 warnings informing me that the libraries are being skipped. (I'm using *.tbd files -- is that the cause of the problem?).

**Comment by mousebird** [comment]
If it's not finding the framework, that does suggest the framework search path is not quite right.  Try setting it to an absolute path just to be sure and then you can set it back relative if that's the problem.

**Comment by todlevi** [comment]
That fixed it. I added the framework search path:

$(SRCROOT)/<..myBinaryDirectory..>/

Are the warnings about skipped files a problem?

**Comment by mousebird** [comment]
If it links and runs, then I guess not.
I'm not entirely sure since I'm dealing with 2.4 and 2.4.1 with Xcode 7.  I haven't looked extensively at earlier versions on Xcode 7.
