### ISSUE TITLE
Expected release date v3?

### ISSUE THREAD

**Issue by nanako-sen** [mousebird/WhirlyGlobe#422]
Hi there,
when do you expect to have v3 ready for release? Would love to integrate WhirlyGlobe in my Android app.
Cheers

**Comment by mousebird** [comment]
I'm not sure about the formal release date.  The v3 version on Android is getting there.  I've been working on the animated image layers and the single layer basemap is in good shape.

I need to circle back to the existing features, like markers and labels, and then we'll be ready for a formal beta, I think.

Let's say sometime in November for that.

**Comment by mousebird** [comment]
Oh, but if there's money involved, it's totally different.  I have a number of clients in line for various functionality in v3 Android.  If you have a budget, I can prioritize your needs as well.
