### ISSUE TITLE
How to use MaplyShapeLinear?

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#423]
According to the description of MaplyShapeLinear it is used to create linear features that are offset from the globe. If I am not mistaken, it is possible to draw lines just like MaplyVectorObject but with z-offset or elevated. I don't get how I use it though. I tried it like the implementation of MaplyVectorObject but it shows an error "-[MaplyShapeLinear deepCopy]: unrecognized selector...". Am I missing something or absolutely doing it wrong?

```
NSArray *waypoints = flightData[@"waypoints"];
    NSMutableArray *points = [[NSMutableArray alloc] initWithArray:waypoints];
    NSMutableArray *vectors = [[NSMutableArray alloc] init];
    MaplyCoordinate3d coords[points.count];
    for (int x = 0; x < points.count; x++) {
        NSDictionary *point = [points objectAtIndex:x];
        coords[x] = MaplyCoordinate3dMake([point[@"long"] floatValue], [point[@"lat"] floatValue], [point[@"z-offset"] floatValue]);
    }
    MaplyShapeLinear *vec = [[MaplyShapeLinear alloc] initWithCoords:coords numCoords:2];
    
    [vectors addObject:vec];
    NSDictionary *desc = @{kMaplyColor: [UIColor redColor], kMaplySubdivType: kMaplySubdivStatic, kMaplySubdivEpsilon: @(0.001), kMaplyVecWidth: @(6.0)};
    _waypointLines = [maplyBaseVC addVectors:vectors desc:desc];
```

**Comment by paulgee31** [comment]
I think you need to use [maplyBaseVC addShapes:] instead of addVectors since this is a MaplyShape use created and not a vector object.

**Comment by mousebird** [comment]
I do believe Paul is correct.
