### ISSUE TITLE
Appear extra lines ：addVectors？

### ISSUE THREAD

**Issue by ludawei** [mousebird/WhirlyGlobe#424]
with he following codes:
```
-(void)testAddVector
{
    UIColor *color = [UIColor colorWithRed:1 green:0 blue:0 alpha:0.6];
    NSDictionary *vectorDict = @{
                   kMaplyColor: color,
                   kMaplyDrawPriority: @(kMaplyLoftedPolysDrawPriorityDefault),
                   kMaplyFilled: @(true),
                   };
    NSString *fileName = [[NSBundle mainBundle] pathForResource:@"USA" ofType:@"geojson"];
    if (fileName)
    {
        NSData *jsonData = [NSData dataWithContentsOfFile:fileName];
        if (jsonData)
        {
            MaplyVectorObject *wgVecObj = [MaplyVectorObject VectorObjectFromGeoJSON:jsonData];
            
            [baseViewC addVectors:[NSArray arrayWithObject:wgVecObj] desc:vectorDict mode:MaplyThreadCurrent];
        }
    }
}
```
Some extra lines appear in the filled area:
![img_0417](https://cloud.githubusercontent.com/assets/4829345/10505418/c730c5d0-733f-11e5-9742-ae28e4f45ccf.PNG)

And, rotate the earth:
![img_0423](https://cloud.githubusercontent.com/assets/4829345/10505473/62b63fb2-7340-11e5-83e0-db6b5bf7c562.PNG)

**Comment by mousebird** [comment]
Yeah, so the problem here is that you're overlaying a giant polygonal feature on a sphere.  We need to break the polygonal feature up to make it look reasonable.  In an ideal world I'd use a triangulation engine that understood spheres... but no, we have to hack it.

The way you hack it is to ask the vectors to subdivide on the sphere.  Try setting the following in the description dictionary for the addVectors call:
kMaplySubdivType: kMaplySubdivSimple, 
kMaplySubdivEpsilon: @(0.001)

**Comment by ludawei** [comment]
Yes, I tried setting the following in the description dictionary for the addVectors call:
kMaplySubdivType: kMaplySubdivSimple, 
kMaplySubdivEpsilon: @(0.001)

... but, nothing changes.

I tried some other colors and found that, 
Set the color of the alpha value is 1.0, the extra lines disappear.

Any ideas?

**Comment by mousebird** [comment]
No, it's the tessellation.  Does it at least look different with the subdivision on?

If adjusting the alpha reduces the problem, that seems like a fine workaround.

**Comment by ludawei** [comment]
But not a fundamental solution.

Setting the alpha to 1.0, will not show the map information behind the filled area.
That's not so good.

Any other ideas?

**Comment by mousebird** [comment]
True.  So you'll need to try a few things.

With the subdivision on, set kMaplyFilled: @(NO)
Ideally you should see a bunch of rectangles.  This is what we're breaking that big areal down into.  Try a small subdivision number and see if it results in more rectangles.  In any case, post the snapshot so I can see what's going on.

**Comment by ludawei** [comment]
Hi, The following are some of the test cases:

![image](https://cloud.githubusercontent.com/assets/4829345/10632092/bf1f5558-7814-11e5-8976-4bed87c162d2.png)![image](https://cloud.githubusercontent.com/assets/4829345/10631766/a2382a2a-7812-11e5-9572-82d0a2f3ed02.png)    ![image](https://cloud.githubusercontent.com/assets/4829345/10682327/fe9e03fc-7966-11e5-9f57-795011955af8.png)

**Comment by ludawei** [comment]
![image](https://cloud.githubusercontent.com/assets/4829345/10682534/36d1cee6-7969-11e5-9cbc-36d1bfa6caf4.png)
![image](https://cloud.githubusercontent.com/assets/4829345/10682517/08604164-7969-11e5-8800-51b2eca9b59e.png)<img width="150" alt="default" src="https://cloud.githubusercontent.com/assets/4829345/10682519/0fc65d58-7969-11e5-924a-c2af43d003c3.png">

**Comment by ludawei** [comment]
![image](https://cloud.githubusercontent.com/assets/4829345/10682538/531883ec-7969-11e5-831a-adb48d0973d4.png)
![image](https://cloud.githubusercontent.com/assets/4829345/10682545/6e4f94e8-7969-11e5-8742-ce95d6f67896.png)![image](https://cloud.githubusercontent.com/assets/4829345/10682549/79adffb4-7969-11e5-8ccb-083143ad241e.png)

**Comment by mousebird** [comment]
Try setting the kMaplySubdivType to kMaplySubdivGrid.

That epsilon my be too low for grid, by the way.  Try setting it back to the number I gave you before and then dividing by 10 until you get something.

What you should see is a lot of little grid cells over the areal feature.

**Comment by ludawei** [comment]
UIColor *color = [UIColor colorWithRed:1 green:0 blue:0 alpha:1.0];
    NSDictionary *vectorDict = @{
       kMaplyColor: color,
       kMaplyDrawPriority: @(kMaplyLoftedPolysDrawPriorityDefault),
       kMaplySubdivType: kMaplySubdivGrid,
       kMaplySubdivEpsilon: @(0.000001),
       kMaplyFilled: @(NO),
       };

Other settings unchanged , test epsilon from 1 to 0.000001.
But nothing appears. :)

**Comment by mousebird** [comment]
Unfortunately setting the grid doesn't show up with the outlines.
I did get this to work pretty well with the following settings:
                                 desc[kMaplyFilled] = @(YES);
                                 desc[kMaplySubdivType] = kMaplySubdivGrid;
                                 desc[kMaplySubdivEpsilon] = @(0.01);

That seems to clean things up well for me.
