### ISSUE TITLE
Develop 3.0 will not open in xcode

### ISSUE THREAD

**Issue by mikejnowak** [mousebird/WhirlyGlobe#425]
I believe I am using Xcode 7. I check out develop_3.0 and try running the component test suite. The project never opens in xcode. (I perform the same steps on master and it opens just fine)

**Comment by mousebird** [comment]
Yeah, I bet it doesn't!  3.0 is the Android development branch.

You want the develop branch or, if you're feeling saucy, develop_2_4_1.

**Comment by mikejnowak** [comment]
I saw that after pulling up almost every open and closed issue. I am saucy and I am working with 2_4_1.  I have some questions for you. Should I keep posting here or send you an email?

**Comment by mousebird** [comment]
Feel free to ask here.  Other people read it too, which is helpful.

**Comment by mikejnowak** [comment]
I noticed that WMS isn't supported. The feature is very important to me and I am debugging through the 2_4_1. I don't fully understand the code yet but i'm narrowing in on the response type not matching application/vnd.ogc.wms_xml. I would like to fix the problem and I was wondering what type of feedback you have that may help me fix it. 

Also, do you value the feature and would you like my help at fixing it?

**Comment by mousebird** [comment]
There is WMS support via the MaplyWMSTileSource object and the examples in the ComponentTester app.  It sounds like you're using that and are running into problems with it.  I don't doubt it, as it's not heavily used.

I do value WMS support, though, so any fixes you might have would be appreciated.

**Comment by mikejnowak** [comment]
I am testing with the ComponentTester app. I am using that and running into problems. Took  me a little bit to isolate the bug or what I think is a bug. I'll make sure we are in touch as I work in it.

**Comment by mikejnowak** [comment]
I fixed the component tester app bug for WMS. I changed the TestViewController.m (inside the whirlyglobecomponenttester), and the AFURLResponseSerialization.m (inside the wirlyGlobe-MaplyComponentxcodeproj. I would like to contribute this small fix and I would like to know what the procedures are to get involved.

**Comment by mousebird** [comment]
Neat!

There's two steps:
1) Glance at [these guidelines](http://mousebirdconsulting.blogspot.com/2013/09/contributions-and-copyright.html) for submissions and pick your option.
2) If you agree to transfer ownership of the copyright for the changes, go ahead and submit a pull request.  I'll review it and probably incorporate it.

**Comment by mikejnowak** [comment]
Shouldn't be a problem. It was a small fix anyway. I'll fork the project and record my changes in github in my own fork and then i'll submit a pull request. Most likely you will want it because currently I find WMS support broken without the fixes.

**Comment by mikejnowak** [comment]
I realized that part of the bug is a problem with a third party library. I have an issue and an open question with the afnetworking folks to see how I can help them fix the problem as I see it. Do you think we should get that issue fixed before I commit to this project? Also, should I file an issue and track the updated fixes there instead of polluting this tree?  

I also can't see how WMS works for you since it relies upon a third party application that doesn't fully support the MIME Type.

**Comment by mikejnowak** [comment]
After thinking about this further, I can overwrite the mime type within the testviewcontroller.m. So that would keep things separated. In addition, it looks like my "Fix" is good for the testviewcontroller which is still good to help "sell" the project. 

I have some questions for you about why the kMaplyTestUSGSOrtho definition exists and is referencing the name on the USGS server.  It seems to me they updated their URL's and the example ended up breaking. Do you need help to go through the test suite to identify problems like these?

**Comment by mousebird** [comment]
Might as well do the hack, then.  No reason to hold things up.

kMaplyTestUSGSOrtho is just part of the config view controller, which lets user pick the data they want to overlay.  I noticed that stopped working a while ago, but never tracked it down.  If you can point me to the new URL, that'd be great.  I'll fix the test.

This sort of thing can go into the new test framework when that's ready.  In the future we'll have a more formal process for noticing when these things are broken.

**Comment by mikejnowak** [comment]
Ok, I will take a look and fix it in my fork and then submit a pull request so it's more "formal". I'll also poke around a bit with the test app to see if I can catch anything wrong. 

For the kMaplyTestUSGSOrtho, do you want a "user friendly" name mapped? Currently my "fix" doesn't account for a user friendly name on the list.

**Comment by mousebird** [comment]
I'm not conversant enough with WMS to know if that makes sense or not.  Do what you think best.
