### ISSUE TITLE
MaplyShapeLinear visibility

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#426]
Is it possible to make the whole shape visible on a globe? As you can see on the photo attached, the orange line which is a MaplyShapeLinear with z values that starts from Abu Dhabi and ends in San Francisco does not show the complete shape at some angles. It seems cut-off at some angles. I was wondering if there is a property I can set to deepen/widen the viewing angle or camera of the globe. For a great circle vector, the whole vector can be seen.

![img_0058](https://cloud.githubusercontent.com/assets/14211746/10563867/471a8e9c-75ad-11e5-9ae0-ff8a48ebe0fb.PNG)

![img_0059](https://cloud.githubusercontent.com/assets/14211746/10563891/7103f116-75ae-11e5-904d-0bbf012b7281.PNG)
![img_0060](https://cloud.githubusercontent.com/assets/14211746/10563892/7408c774-75ae-11e5-9c2a-2e621b4e5c97.PNG)

**Comment by mousebird** [comment]
Right, that's an optimization that keeps vectors from being drawn when they're on the back of the globe.

If you set kMaplyShader to kMaplyShaderDefaultLineNoBackface that will remove the problem, but you may need to also set the kMaplyZBufferRead to @(YES).  You might also need to adjust the draw priority, but try those first and see if they help.

**Comment by jerald-acacus** [comment]
Cool! It worked. Thanks man.
