### ISSUE TITLE
 Each time you call the “ animateToPosition:time:  method”  method memory growth

### ISSUE THREAD

**Issue by yao201212** [mousebird/WhirlyGlobe#428]
I'm using the latest code "remotes/origin/develop_2_4_1" branch,   open "WhirlyGlobeComponentTester" project .
 In the TestViewController.m file, add this method:
 -(void)tesetZoom
{
    [mapViewC animateToPosition:MaplyCoordinateMakeWithDegrees(116.9, 39.46) time:1.0f];
    [self performSelector:@selector(tesetZoom) withObject:nil afterDelay:3.0f];
}

and at the end of  the "changeMapContents" method call it.

running  the "WhirlyGlobeComponentTester" target to iPhone device.    then MapType select Map(2D), click the Edit button , Base Layers select MapBox Satellite - Remote, click done button. 

  In xcode debug navigator, will see the memory is continuously growing up. but Everything looks fine.
Instruments doesn't report any memory leak.
I hope you can fix it,thank you!

**Comment by mousebird** [comment]
Are you running out of memory?  Some growth is normal due to caching and such.

**Comment by yao201212** [comment]
I used the demo project, and the same position , Remote Satellite map resource.  Each time call it, it growth 1.xxMB memory.   After about 5 minutes，probably more than 200 MB memory footprint.
I think this is not a normal situation.

**Comment by yao201212** [comment]
Can not be used in other ways to make the map automatically displays the user's current location?

**Comment by mousebird** [comment]
I'd suggest you move back to the develop branch.  2.4 is heavily tested.  We may have broken something in 2.4.1.

To display the user location you'll need to listen to Core Location and place a marker at the user's position.
