### ISSUE TITLE
setPosition using MaplyCoordinateD 

### ISSUE THREAD

**Issue by Crappy** [mousebird/WhirlyGlobe#429]
Hello,

I'm using GlobeController.setPosition(pos: MaplyCoordinate, height: Float)
to rotate/zoom the globe but when the zoom is too big, the float precision is not good enough, and I would need to set the position using MaplyCoordinateD (double precision)

Is this possible ?
Can I change the code and recompile the library, If so how can I do that ?

Best regards,
Vincent

**Comment by mousebird** [comment]
Ah, I see the problem.  Yes, you could change that easily enough in the code.

Just get the library off of github (the link is right up top here) and set it up with the [source distribution](http://mousebird.github.io/WhirlyGlobe/tutorial/building_from_source.html).

Although, if your project has a budget, you could get a [support contract](http://mousebirdconsulting.blogspot.com/2015/08/revisiting-support-for-whirlyglobe-maply.html).  I'd be happy to add that feature for a support customer.

**Comment by Crappy** [comment]
The project can't afford a support contract for now :)
How do you think it would take to create a new setPosition function?

**Comment by mousebird** [comment]
If you just need to modify the height, it doesn't look too bad.  The heightAboveGlobe member in the globeView is already a double.  So you just need a new setPosition call.

**Comment by Crappy** [comment]
Yep, the height parameter works just fine, it's just about latitudes/longitudes

**Comment by mousebird** [comment]
Oh, I see.  That's harder.  The internals are all doubles and have been for a couple versions now so it's possible.

However, you have to dig down to get at the doubles.  You'd need to change setPosition:height: and rotateToPoint: and then makeRotationToGeoCoord:keepNorthUp:  Rather than passing around a GeoCoord it needs to be a Point2d.

It shouldn't be all that bad to fix it, but it does go deep.

**Comment by Crappy** [comment]
Oh I see, I'm not really familiar with the internals unfortunatly ...
If you find the time, would you be able to release a patch anytime soon ?

**Comment by mousebird** [comment]
Possibly.  I'm a bit overwhelmed with support and clients.  It should be very simple, so I'll see if I can slip it into 2.4.

**Comment by Crappy** [comment]
That would be awesome, when do you plan on releasing the 2.4 version?

**Comment by mousebird** [comment]
Like, six weeks ago.

I might get to this in the next few days.  Just a few things to wrap up 2.4.  It's in the develop branch on github, though.

**Comment by Crappy** [comment]
Ahah I see :)
Yeap no problem, It's pretty complicated to build the .framework from the sources tho, as there is no documentation on the build process, I'll wait for the release I think

**Comment by mousebird** [comment]
You can include the Xcode project as a submodule.

That's what I recommend doing in the source case.

**Comment by mousebird** [comment]
The setPositionD:height: method is not in 2.4 (develop branch).

**Comment by Crappy** [comment]
Thanks! Is there a getPositionD:height: method in 2.4 too?

**Comment by mousebird** [comment]
Good point.  There is now.
