### ISSUE TITLE
animateToPosition to animate height

### ISSUE THREAD

**Issue by Crappy** [mousebird/WhirlyGlobe#430]
Hi,

Thank you again for such a nice library!
I can't seem to find a way to animate the height on the GlobeViewController

On the documentation, http://mousebird.github.io/WhirlyGlobe/reference/ios_2_3/Classes/MaplyBaseViewController.html
Only position animation is animatable,

And UIView.animateWithDuration({ Globe.height = x })
Doesn't work with the GlobeViewController (as I guess it's because it's not internally an UIView)

Best regards,
Vincent

**Comment by mousebird** [comment]
That's true in 2.3.  In 2.4 there's a nice interface that uses WhirlyGlobeViewControllerAnimationState objects.  You can animate from one state to another including height, location, heading, and tilt.

**Comment by Crappy** [comment]
Oh nice! Is there a pre-compiled binary version of the 2.4 somewhere?

**Comment by mousebird** [comment]
I really need to publish the beta, but here you go:
https://dl.dropboxusercontent.com/u/29069465/WhirlyGlobeMaplyComponent.framework_2_4_beta8.zip

**Comment by Crappy** [comment]
Thanks!

**Comment by sabiland** [comment]
@mousebird, off-topic question: will there be also a precompiled "use-bitcode" version?

**Comment by mousebird** [comment]
I turned that off for compatibility with old projects.  Maybe in 2.4.1 we can turn that back on.
You can always recompile that, of course.

**Comment by sabiland** [comment]
WhirlyGlobeViewControllerAnimationState & setViewState(...) makes an instant action without some nice animation duration. How to achieve animation (with duration)?

**Comment by mousebird** [comment]
Look at animateWithDelegate:time: and also look at WhirlyGlobeViewControllerSimpleAnimationDelegate for an example of how to use it for simple interpolation.  Or you can just use the Simple version directly.
