### ISSUE TITLE
Elevated markers

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#432]
Is it possible to create eleveted markers and put them in line with MaplyShapeLinear?

**Comment by mousebird** [comment]
At the moment the marker field does not has a Z value.
The internal data structure does have a Z value, so it would be possible.

At this point I'm a little busy with 2.4 and 2.4.1.  I'll put this on the request list.
It's the sort of thing I'd add immediately for a support contract, if you have a budget.

**Comment by mousebird** [comment]
Duplicate.
