### ISSUE TITLE
Closed wide vectors should have a join for the final vertex

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#434]
Closed in this case meaning a MaplyVectorLinear where the first vertex is the same as the last vertex.

See https://github.com/mousebird/WhirlyGlobe/pull/433 for an implementation of this.

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;boICE4ij&#x2F;47-github-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Github issues</a>

**Comment by mousebird** [comment]
If you pass them in as MaplyVectorAreals they'll do this.

**Comment by JesseCrocker** [comment]
When i create the vectors with initWithAreal instead of initWithLinestring the it doesn't render. Im trying to render the outline, not the fill.

Attributes dictionary passed to addWideVectors:desc:mode

    @{kMaplyColor: lineColor,
         kMaplyFilled: @NO,
         kMaplyEnable: @YES,
         kMaplyFade: @0,
         kMaplyDrawPriority: @(self.mapView.overlayBaseDrawPriority + kMaplyVectorDrawPriorityDefault + 10000),
         kMaplyVecCentered: @YES,
         kMaplyVecWidth: @(width)};

**Comment by mousebird** [comment]
I have a test case in the feature/widen-update branch that does just this.  That's the square example.

So I'm not sure why this would be different.

**Comment by JesseCrocker** [comment]
I didnt try in feature/widen-updates. I'll give it a try

**Comment by mousebird** [comment]
Ah, yes.  It's in there.
