### ISSUE TITLE
Screen Markers Z Indexes

### ISSUE THREAD

**Issue by Crappy** [mousebird/WhirlyGlobe#436]
Hello,

I'm currently experimenting with the Screen markers on the globe but I can't seem to find a way to manipulate Z-ordering for the markers.

Is there a way to sort the markers ?
Sometimes, depending on the globe rotation, the z-indexes are invalid, that's why I'm wondering :)

Thank you for this library!

**Comment by mousebird** [comment]
You're welcome.

There's drawPriority.  Check out the documentation... which doesn't mention kMaplyDrawPriority.  Whoops, I'll make a note of that.

**Comment by mikejnowak** [comment]
yeah i've been digging around the code with the drawPriority #Crappy#. I've noticed some interesting behavior with the drawPriority on the component tester app.

**Comment by JesseCrocker** [comment]
The docs might not make it clear, but draw priority for markers should start at kMaplyMarkerDrawPriorityDefault (40,000) and go up from there.

**Comment by mousebird** [comment]
By default is should bump the draw priority values you set by that amount.  That's to simulate a 2D screen effect, even though there's no real reason for it in the rendering.

You can turn that bump off, if you need to, in which case you can mix 2D and 3D elements.

**Comment by mousebird** [comment]
I think I left this open to update the documentation.  If there was a problem outstanding, reopen it and let me know.
