### ISSUE TITLE
didSelect delegate method not called when taping a cylinder

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#437]
Good evening everyone,

I have some issues with the didSelect delegate method. Actually, the function is not called when I try to tap one of the cylinders that I display in my globe.

Here is what I have done:

1) In ViewController.h:
#import <UIKit/UIKit.h>
#import <WhirlyGlobeComponent.h>

@interface ViewController : UIViewController<WhirlyGlobeViewControllerDelegate>
{
    WhirlyGlobeViewController *whirlyGlobeViewController;
}

@end

2) In ViewController.m:
@implementation ViewController

- (void)viewDidLoad
{
    
    [super viewDidLoad];
    [whirlyGlobeViewController setDelegate:self];
[...]
}

- (void)globeViewController:(WhirlyGlobeViewController *)viewC didSelect:(NSObject *)selectedObj
{
    NSLog(@"Cylinder selected");
}

Because this didn't work, I tried another delegate method:
- (void)globeViewController:(WhirlyGlobeViewController *)viewC didMove:(MaplyCoordinate *)corners
{
    NSLog(@"Coucou");
}

This method is not working either.

I think that I am missing something but I can't find out what.

Could anyone help me on this please?

Thank you very much. 

Sebastien.

**Comment by paulgee31** [comment]
Hi Sebastien,

How are you initialising the WhirlyGlobeViewController? This is how I typically add initialise and add the view controller in my viewDidLoad method. 

    globeViewC = [[WhirlyGlobeViewController alloc]init];
    globeViewC.delegate = self;    
    [self.view addSubview:globeViewC.view];
    globeViewC.view.frame = self.view.bounds;
    [self addChildViewController:globeViewC];

**Comment by Sebboulnois** [comment]
Ho... I am initializing the same way than you. The only thing that I changed is the location of the setDelegate function. It works now. Thank you a lot! 

Have a nice week-end. 

Sebastien.
