### ISSUE TITLE
Multi source tiles not blending frames during animation

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#438]
I have multiple frames animating on a MaplyQuadImageTilesLayer using a MaplyMultiplexTileSource.

With 2.3 the frames would blend during the animation. This stopped working after upgrading to 2.4 beta. Now the animation simply shows the solid frames, without the cool blending effect.

Was this behavior removed from the framework?

**Comment by amirfl** [comment]
Never mind... I think the problem was that my view controller tried to add the same layer twice. I removed the extra call and it works normally now.

**Comment by mousebird** [comment]
Glad it's working.
