### ISSUE TITLE
Drawing lines between two coordinates, integrating the z dimension

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#439]
Hello everyone,

I am integrating flight waypoints in my globe and I would like to draw the flightpath by joining each waypoint one by one with a line, following this idea:

<img width="614" alt="screen shot 2015-11-09 at 4 17 41 pm" src="https://cloud.githubusercontent.com/assets/15698398/11046883/ad4bd7be-86fd-11e5-9f89-925c61a4bc94.png">

Steve told me about greatCircle shapes but it seems to me that the height property is a constant so I can't create a line in the 3D space. Would you have any idea about how to do that?

Thank you in advance,

Best,

Sebastien.

**Comment by mousebird** [comment]
Well, great circles follow the curve of the earth so they're nice for long distances.  I believe they always touch down at the ends, though.

For full 3D control you can use a [MaplyShapeLinear](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_3/Classes/MaplyShapeLinear.html).  It's like a vector feature, but has 3D points.

**Comment by paulgee31** [comment]
Hi Sebastian,

This is roughly want you are probably looking to do:

MaplyCoordinate3d *Track3DCoords=malloc(sizeof(MaplyCoordinate3d)*numberOfPoints);
int index=0;

 for (NSDictionary *coord in trackData) {
      Track3DCoords[index]=MaplyCoordinate3dMake(DEGREES_TO_RADIANS([coord[@"lon"] floatValue]), DEGREES_TO_RADIANS([coord[@"lat"] floatValue]),(([coord[@"alt"] floatValue]*aHeightFactor);
index++;
}

MaplyShapeLinear *track3D =[[MaplyShapeLinear alloc]initWithCoords:Track3DCoords numCoords:numberOfPoints];
track3D.lineWidth=4.0;
[viewC addShapes:@[track3D] desc:@{kMaplyColor:trackColor} mode:MaplyThreadAny];

**Comment by Sebboulnois** [comment]
Thank you for your quick answers.

I am a bit lost. Are you using swift code here?

**Comment by paulgee31** [comment]
Nope Objective-C.
