### ISSUE TITLE
MaplyGeomModel/MaplyMovingGeomModelInstance on 2D MaplyViewController

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#440]
Are the MaplyGeomModel or MaplyMovingGeomModelInstance only for the WhirlyGlobeViewController? I got it to work on a globe however I do not see it on the map.

**Comment by mousebird** [comment]
I've never tried them in the flat map mode.  Obviously somethings broken.

What are you doing?  Maybe I can suggest an alternative while I get around to fixing the problem.

**Comment by jerald-acacus** [comment]
In a globe, I am animating a model thru waypoints with elevation.
Perhaps in a flat map, I animate without elevation and just flat on the ground.
Would something like the animated sphere like in the test project be able to do it with a 3D model?

**Comment by mousebird** [comment]
Not supporting geometry models in 2D map.  All the 3D stuff is on the globe for now.
