### ISSUE TITLE
drawPriority inside MaplyBaseViewController

### ISSUE THREAD

**Issue by mikejnowak** [mousebird/WhirlyGlobe#441]
Within addLayer of the MaplyBaseViewController I ran into a weird issue where the drawPriority wasn't working right when first running the test component app. It seemed like pre incrementing the layerDrawPriority fixed the issue I was having. 
Steve, do you experience the same issue? If so, I would like to help fix that bug. If not, what am I doing wrong?
-Mike

**Comment by mousebird** [comment]
What was the bug, exactly?

In theory the first layer should start with kMaplyImageLayerDrawPriorityDefault and there rest should go up by increments of 100.  The space is needed for 2D layers which like to play around with draw priorities when doing multi-loading.

**Comment by mikejnowak** [comment]
Within the component tester, the app comes up with a base layer (geometry class layer). I turn on the WMS layer (USGS Ortho) and I don't see the layer I put on the map. It seemed to me that the drawPriority was 100 and was equal to the base layer.  It seemed that I pre-incremented the layerDrawPriority to fix the problem but what jumped out at me was that it was in the maplybaseviewcontroller and not the testcomponent... which made me thing it was a core defect instead of a problem with the component tester. So, I was thinking I should bring it up to you to see if you can confirm or deny the issue and give me pointers to alleviate the issue I see on the component tester.

-Mike

**Comment by mousebird** [comment]
I think this is fixed now.
