### ISSUE TITLE
Any interest in having a PolyLine class?

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#442]
Are you interested in adding a class like PolyLine from https://github.com/trailbehind/WhirlyGlobe/tree/feature/polyline that makes it easy to put lines on the map, Simplifying, splitting, and adding multiple copies as needed?

If so I can clean that class up and submit a pull request, but if not i wont bother, as my private implementation of the class works fine for my needs.

**Comment by mousebird** [comment]
I imagine that would be useful to people.
Do you think this belongs in the core or in a contributed repo?
I've been contemplating moving some higher level functionality out of the core.

**Comment by JesseCrocker** [comment]
This seems like a useful thing to have in the core, as it's basically how Lines work in most other mobile mapping frameworks, and how many people would expect lines to work.

**Comment by mousebird** [comment]
Okay, I'm down with that.

I'd prefer to merge this into 2.4.1.  You would probably prefer to stay on 2.4 with the changes I'm going to merge in for widened vectors in a few days.

**Comment by mousebird** [comment]
Are you going to merge this in with 2.4.1?  It seemed useful.

**Comment by JesseCrocker** [comment]
I don't have the time to clean it up, and probably wont ever get around to it.
