### ISSUE TITLE
WhirlyGlobeViewControllerAnimationState should use doubles

### ISSUE THREAD

**Issue by mousebird** [mousebird/WhirlyGlobe#448]
Just switch the whole thing over to doubles.

**Comment by mousebird** [comment]
This refers to the MaplyCoordinate location.

**Comment by mousebird** [comment]
Switch to MaplyCoordinateD and follow the logic through.
I'd like the interpolation to be done in doubles, but if you need to convert to floats for other objects, that should be fine.

**Comment by rghosh0** [comment]
This one should also be done; in the develop_2_4_1 branch.

**Comment by mousebird** [comment]
Whoops!

Actually I just wanted you to change WhirlyGlobeViewControllerAnimationState to use MaplyCoordinateD.  Leave MaplyCoordinate as floats.

Can you revert this commit and just change WhirlyGlobeViewControllerAnimationState?
Also change any other floats like rotation and tilt to double.

**Comment by rghosh0** [comment]
Oops! OK Sure.

**Comment by rghosh0** [comment]
Changes are in feature/animation-state-doubles branch.

**Comment by mousebird** [comment]
Look good.  Thanks!
