### ISSUE TITLE
Remove AFNetworking

### ISSUE THREAD

**Issue by mousebird** [mousebird/WhirlyGlobe#453]
Get rid of AFNetworking as a dependency.  All the async stuff we use in now in UIKit.

**Comment by jerald-acacus** [comment]
Any updates on this one for 2.4.1?

**Comment by mousebird** [comment]
Is this critical for you?  AFNetworking should work fine, it's just unnecessary now that Apple's provided block based methods for a while now.

**Comment by mousebird** [comment]
The idea here is to replace any AFNetworking calls in the toolkit with their equivalent UIKit networking calls, now that we have block support there.

I'm most concerned with pulling AFNetworking out of the Cocoapod, but if we can remove AFNetworking from the test apps do that too.

Nothing against AFNetworking, just one more dependency.

**Comment by jerald-acacus** [comment]
Just a question, can I ignore classes that use this networking calls because I will only be using an offline globe/map?

**Comment by rghosh0** [comment]
Hi Jerald, I'm not sure I understand the question. If you remove the classes from the project, it probably won't build, but I'm guessing that's not what you meant...

**Comment by jerald-acacus** [comment]
@rghosh0 Hi. What I mean is for example, the classes in WhirlyGlobe that use AFNetworking are MaplyVectorTiles, MaplyRemoteTiles, etc. Is it possible to remove these files and so I can work with the library only with it's offline functionalities?

**Comment by rghosh0** [comment]
If that's what you need, it sounds like it's worth a try. As I indicated, there may be some build problems that you'll have to work around.  When I resolve this ticket, which will hopefully be soon, this will no longer be an issue.

**Comment by jerald-acacus** [comment]
Thanks. Actually I think that my solution to remove the other classes in WhirlyGlobe is a bad idea. So now I just try to use AFNetworking 2.3 on the other class that a colleague of mine is using. And use NSURLSession on most of my HTTP Request through out the project. Can you confirm that you will be updating WhirlyGlobe with NSURLSession and not with AFNetworking?

**Comment by rghosh0** [comment]
Confirmed.

**Comment by mousebird** [comment]
We'd like to remove some of the external dependencies, such as AFNetworking.  Boost is always going away soon now that everything important is in c++11.

I do worry about performance, though.  Has anyone seen problems switching from AFNetworking to NS block calls?
