### ISSUE TITLE
UIScrollView

### ISSUE THREAD

**Issue by xxxxtxxxxt** [mousebird/WhirlyGlobe#455]
I want to place this 3d globe inside a uiviewscroll as second view so you can swipe. I want help so we can prevent moving the uiviewscroll if the globe is touched/used

There should be 2 views inside the uiviewscroll. Empty red view and this 3d globe. You can swipe to the right and left. But when you are using/moving the globe i want to  prevent moving the uiviewscroll  until you remove your finger again from it and i cant find a fix to that

**Comment by mousebird** [comment]
Who is this?  I have a customer asking about the same thing and I'd like to see if you're them.

**Comment by xxxxtxxxxt** [comment]
Hello

Yeah i'm part of the team. He told me earlier in the week to ask publicly here in case someone knew what to do to solve the problem. As i understood you two have made a deal so i'm closing that for now.

**Comment by mousebird** [comment]
It's a valid bug.  And users may have some input on this.  I know Gaia GPS manages it somehow.

But yeah, I think we'll get it fixed here shortly.

**Comment by mousebird** [comment]
This was fixed for the client.
