### ISSUE TITLE
Cesium elevation data with default shader and includeElevAttrForShader true causes bad result

### ISSUE THREAD

**Issue by bryanheitman** [mousebird/WhirlyGlobe#461]
Including includeElevAttrForShader as true causes shader to not work correctly and include many blank areas.
<img width="770" alt="screen shot 2015-12-17 at 7 19 28 pm" src="https://cloud.githubusercontent.com/assets/13205913/11886739/1b8f3c76-a4f3-11e5-96e5-771de97af688.png">

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4dVl8PMb&#x2F;43-cesium-elevation-problem"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Cesium elevation problem</a>

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;boICE4ij&#x2F;47-github-issues"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Github issues</a>

**Comment by mousebird** [comment]
Cesium terrain support deprecated for now.
