### ISSUE TITLE
Map box style data rendering 

### ISSUE THREAD

**Issue by SandeepCoder** [mousebird/WhirlyGlobe#462]
Hi,

Can we load MapBox Style on satellite Globe? if yes how? I have created my custom style on map box and want to load style contents on Satellite view globe. Please suggest

**Comment by paulgee31** [comment]
Just specify the address of your JSON tile spec with the following format:

https://a.tiles.mapbox.com/v3/<your MapBox map ID>

https://a.tiles.mapbox.com/v3/forexample.123456ea.json

**Comment by SandeepCoder** [comment]
Nops. May be i'm missing something. Above is rendering the map contents. Style is created separately.

I have below Style:
https://api.mapbox.com/styles/v1/xswinter/cih5gnsnz004b90m6asw6ewv5.html?title=true&access_token=pk.eyJ1IjoieHN3aW50ZXIiLCJhIjoiMk56Vk1zcyJ9.o8Wy_5BvWb8fFoUNyBhDZQ#18.36/-37.81449/144.96310

How do we render this on Satellite globe view?

Thanks.

**Comment by paulgee31** [comment]
I don't believe you can use the new the MapBox styles. You can still create classic styles.

**Comment by mousebird** [comment]
The Mapbox GL Style isn't completely implemented.  I've been waiting for the format to settle down.  It seems to mostly have.  Mapbox Vector Format is supported.

Now I'm just waiting for someone to pay for the rest of it.  The satellite style is pretty simple.  It wouldn't take much work.
