### ISSUE TITLE
Swift & Cocoapods

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#464]
Hi there,
I have been trying to use WhirlyGlobe in a Swift 2 project with CocoaPods.

The installation seems to be OK, but I get the following error when trying to compile the project.

Are you aware of anyone using Whirly-Globe in this kind of configuration ?

Many thanks in advance,
Jean-Michel 

> Undefined symbols for architecture arm64:
>   "_deflate", referenced from:
>       google_public::protobuf::io::GzipOutputStream::Deflate(int) in gzip_stream.o
>   "_inflate", referenced from:
>       google_public::protobuf::io::GzipInputStream::Inflate(int) in gzip_stream.o
>   "_inflateInit2_", referenced from:
>       google_public::protobuf::io::internalInflateInit2(z_stream_s*, google_public::protobuf::io::GzipInputStream::Format) in gzip_stream.o
>   "_deflateEnd", referenced from:
      google_public::protobuf::io::GzipOutputStream::Close() in gzip_stream.o
>   "_deflateInit2_", referenced from:
>       google_public::protobuf::io::GzipOutputStream::Init(google_public::protobuf::io::ZeroCopyOutputStream*, > google_public::protobuf::io::GzipOutputStream::Options const&) in gzip_stream.o
>   "_inflateEnd", referenced from:
>       google_public::protobuf::io::GzipInputStream::~GzipInputStream() in gzip_stream.o
>       google_public::protobuf::io::GzipInputStream::Next(void const**, int*) in gzip_stream.o
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jmnavarro** [comment]
Hey!

Swift support is commited in branch develop_2_4_1. Are you using that code?

**Comment by jmcazaux** [comment]
No, I was just using the standard 2.3 Pod.

So I assume I just use the pod "github" syntax pointing at the the develop_2_4_1 branch ?

I'll try that tomorrow and will keep you posted.

Many thanks,
JM

**Comment by jmnavarro** [comment]
Yes, just try with:

`pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe', :branch => 'develop_2_4_1'`

Cheers
Other JM

**Comment by jmcazaux** [comment]
Ok, I made some progress with the 2.4.1 branch, but I still do have some compilation errors.

When compiling MaplyMultiplexTileSource.mm, it cannot find 'AFHTTPRequestOperation.h' (that it tries to import).

Funnily (or not), this file does not seem to belong to AFNetworking (or not anymore)...

Thanks,
JM

**Comment by mousebird** [comment]
JM, can you take a look at this?  I'm guessing it's an AFNetworking version thing.

**Comment by mousebird** [comment]
Sorry, I mean jmnavarro.

**Comment by jmnavarro** [comment]
Yeah, fixed in 70ef423. It was downloading AFNetworking 3.x and we only support 2.x at the moment

Try again and let me know, please

**Comment by jmcazaux** [comment]
Guys, it's a bit late this side of the Atlantic, so I have not been able to push it to the next stage, but at least it is compiling OK now.

Many, many thanks.

JM

**Comment by jmcazaux** [comment]
I have successfully displayed a nice globe, which is really really great, but did not get so lucky with the 2D map.
I am not sure exactly what is wrong, but it is looking like MaplyViewController does not inherit MaplyBaseViewController.
It would not accept a delegate either. Maybe something got wrong with Swift bridging header.
I have not had a chance to dig more.

**Comment by mousebird** [comment]
@jmnavarro, have we tried creating a MaplyViewController with the Swift side?
This can wait till after the holidays of course.

**Comment by jmnavarro** [comment]
If I remember well I wrote some map tests using Swift

I'll have a look tomorrow night

Merry Christmas!

**Comment by jmnavarro** [comment]
I checked and it's working as expected.

Also MaplyViewController inherits from MaplyBaseViewController (see [here](https://github.com/mousebird/WhirlyGlobe/blob/develop_2_4_1/WhirlyGlobeSrc/WhirlyGlobe-MaplyComponent/include/MaplyViewController.h#L98))

You can check some sample code in the [auto-tester branch](https://github.com/mousebird/WhirlyGlobe/tree/auto-tester)
