### ISSUE TITLE
MaplyShapeGreatCircle without height

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#465]
Is it possible to draw a great circle between two points on the globe that follows the curvature of the map? (no height)
My problem with MaplyShapeGreatCircle is that even with a small height set to 0.005 there's a 'parallax' effect. In other words, since the shape has a height, when the user drags the map or zooms in/out, the route doesn't seem to sit exactly over the same point on the map.
With any smaller height set, the route will disappear into the globe.

**Comment by mousebird** [comment]
If you set the height to 0 and you give it a kMaplyDrawPriority and set kMaplyZBufferRead to @(NO) it should do what you want.

**Comment by amirfl** [comment]
Still having the same problem. This is how I create the route and add it to the view:
```
- (void)addRouteToView{
    if (!routeSegmentShapes) {
        routeSegmentShapes = [[NSMutableArray alloc] init];
    }
    for (MapRouteSegment *segment in self.route.segments) {
        MaplyShapeGreatCircle *segmentShape = [[MaplyShapeGreatCircle alloc] init];
        segmentShape.startPt = [self MaplyCoordinateFromCLLocationCoordinate2D:segment.startPoint.location.coordinate];
        segmentShape.endPt = [self MaplyCoordinateFromCLLocationCoordinate2D:segment.endPoint.location.coordinate];
        segmentShape.height = 0.0;
        [routeSegmentShapes addObject:segmentShape];
    }
    
    routeCompObj = [theViewC addShapes:routeSegmentShapes desc:@{
                                                  kMaplyColor: [UIColor redColor],
                                                  kMaplyDrawPriority: @(1.0),
                                                  kMaplyZBufferRead: @(NO)
                                                  } mode:MaplyThreadAny];
}
```

**Comment by mousebird** [comment]
The draw priority should be an integer and it should be really large.  Start with kMaplyShapeDrawPriorityDefault and add a bit to it.

**Comment by amirfl** [comment]
I tried to set it higher, but still have a parallax when moving the map around.

```
routeCompObj = [theViewC addShapes:routeSegmentShapes desc:@{
                                                  kMaplyColor: [UIColor redColor],
                                                  kMaplyDrawPriority: @(90000),
                                                  kMaplyZBufferRead: @(NO)
                                                  } mode:MaplyThreadAny];
```

**Comment by mousebird** [comment]
If height = 0, then that should be doing what you want.

**Comment by amirfl** [comment]
height is set to 0, but it still has a parallax:
![routeparallax](https://cloud.githubusercontent.com/assets/364326/11986037/0521eb00-a999-11e5-9503-f1ea6fec6f1f.gif)

**Comment by mousebird** [comment]
I see.  It's the sampling of the curve.
Try adjusting the parameter kMaplySubdivEpsilon.  It starts out at 0.001.  Divide by 10 and see if that reduces it.

**Comment by amirfl** [comment]
That's what it was :) thanks!

P.S
How do I prevent the shape from showing  through the globe? When user rotates the globe the great circle shape shows even when it shouldn't be in view.

**Comment by mousebird** [comment]
Well at this point you might as well switch to a MaplyVectorObject since you're not lofting it up over the globe.  The shader for that will, by default, hide backward facing pixels (e.g. behind the globe).

You will need to set the kMaplySubdivType parameter to kMaplySubdivGreatCircle to get the same effect.
