### ISSUE TITLE
Can`t parse Mapzon Vector tiles using MapzenGLStyle.json and MapnikMapboxGLStyle Type

### ISSUE THREAD

**Issue by OlegPanfyorov** [mousebird/WhirlyGlobe#466]
Hi, Steve. Thanks for your Maply project! You did really great job!
I have an issue with parsing Mapzon Vector tiles using MapzenGLStyle.json and MapnikMapboxGLStyle Type. I have builded ios app from develop branch. It seems that Mapzen changed something because if I use XML style 
NSData *styleData = [NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"osm-bright" ofType:@"xml"]]; and styleType:MapnikXMLStyle (sourceType:MapzenSourcePBF) it works. 
But I want using GL to render vector tiles, it seems that it really faster. 
Here is my code:
                    NSData *mapzenStyleData = [NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"MapzenGLStyle" ofType:@"json"]];
                    MapzenSource *mzSource = [[MapzenSource alloc]
                                              initWithBase:@"http://vector.mapzen.com/osm"
                                              layers:@[@"all"]
                                              apiKey:@"vector-tiles-kpnAMpI"
                                              sourceType:MapzenSourcePBF
                                              styleData:mapzenStyleData
                                              styleType:MapnikMapboxGLStyle
                                              viewC:baseViewC];
and when I`m trying to render it, I recieve errors from MaplyMapboxVectorStyleSet.mm and see nothing on mapView

- (id)initWithValueDict:(NSDictionary *)dict dataType:(MaplyMapboxValueType)dataType styleSet:(MaplyMapboxVectorStyleSet *)styleSet viewC:(MaplyBaseViewController *)viewC

2015-12-25 12:43:22.664 WhirlyGlobeComponentTester[3481:539009] Expected JSON arrays of same length for domain and range of function.
2015-12-25 12:43:22.664 WhirlyGlobeComponentTester[3481:539009] Expected double but got something else ((null))
2015-12-25 12:43:22.665 WhirlyGlobeComponentTester[3481:539009] Ignoring fill layout
2015-12-25 12:43:22.668 WhirlyGlobeComponentTester[3481:539009] Expected JSON arrays of same length for domain and range of function.
2015-12-25 12:43:22.668 WhirlyGlobeComponentTester[3481:539009] Expected double but got something else ((null))
2015-12-25 12:43:22.668 WhirlyGlobeComponentTester[3481:539009] Expected JSON arrays of same length for domain and range of function.

Can you please fix this and update develop branch?

**Comment by OlegPanfyorov** [comment]
Hi again, Steve. Any ideas how to fix this? I`m still waiting :(

**Comment by rghosh0** [comment]
"But I want using GL to render vector tiles, it seems that it really faster."

The format of style that you use is actually independent of the rendering method, so if the XML style is working for you then you can go with that.

The code example you use seems to correspond to a blog post from June 3, 2015.  It looks like the code for handling the MapnikMapboxGLStyle case has changed since then.  The git comments seem to suggest an upgrade to Mapbox GL Style version 8, but I tried a v8 style from [1] and it gave me similar errors to yours.

[1] https://github.com/mapbox/mapbox-gl-styles/tree/master/styles

**Comment by mousebird** [comment]
Right, I upgraded to version 8 of their style sheet, but while it was still under development.  They backed out a bunch of changes, ones that I thought were rather good.  That left my code in a bad state and with a someone cautious view of Mapbox GL Style evolution.  I like it for the future, but I'd like it to settle down.

I need to either back out those version 8 changes or see what Mapbox settled on for v8 and implement that.  Then the Mapzen style sheet needs to be updated to reflect it.

I'd do either of those for a client immediately, but on my own time it may take a while.

**Comment by mousebird** [comment]
Fixed this right before I released 2.4.  The master branch should now work correctly with the older GL Style sheet.
