### ISSUE TITLE
Good free map sources

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#470]
Could you recommend a good free map tile source good for commercial use?
I’m currently using CartoDB’s Positron base map, but its too gray.
Looking for something that has the minimum of terrain, country and city labels and blue water ( any color for land is good for now). 
In the future I might consider using a paid service, or pay to host a map server, but right now I have to keep a low overhead.

**Comment by mousebird** [comment]
This comes up a lot, so if anyone has thoughts it would be great to collect them.  I'll put them in the wiki.

**Comment by jmcazaux** [comment]
I have looked into Mapbox.

You can have your own style and their free tier allows for some traffic & hosting...
That might suffice.
