### ISSUE TITLE
Center on a region with given geo coordinates

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#474]
I'm looking for a way to zoom and center the globe/map to show a route, that contains two or more geo coordinates. Maybe something similar to Apple MapView's showAnnotations or setRegion methods can work, but I couldnt find an equivalent with WhirlyGlobe. I know this can be limited with a 3d globe, but at least have it work when all the points are close together. Is there any built-in way that I'm missing to do this?

**Comment by mousebird** [comment]
Try findHeightToViewBounds:

**Comment by amirfl** [comment]
Thanks, will give it a try
