### ISSUE TITLE
WhirlyGlobeViewControllerDelegate didSelect methods not firing

### ISSUE THREAD

**Issue by jday001** [mousebird/WhirlyGlobe#479]
develop_2_4_1 branch, following the getting started docs: http://mousebird.github.io/WhirlyGlobe/tutorial/vector_selection.html

`didTapAt` works, but none of the `didSelect` methods fire. Vectors are getting added, just can't select them. Noticed the `kMaplySelectable` key in a closed ticket, I'm passing that in already.

Any ideas?

**Comment by jday001** [comment]
Figured it out, needed to explicitly set `selectable = true` on the `MaplyVectorObject` before adding.

**Comment by mousebird** [comment]
Ah, yes, thanks for figuring this out.  Selectability is off by default to cut down on memor.
