### ISSUE TITLE
Direct access to Z

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#481]
Hi there I have started playing around with Maply on Android and I am surprised with cannot directly read the z parameter of the Map or Globe Controllers...

Instead I have to use findHeightToViewBounds which seems a bit costly...
And I have to do this for every position refresh (before being able to call setPositionGeo)...

Am I looking in wrong place or am I confused ?

Many thanks,
JM

**Comment by mousebird** [comment]
For the globe it's getPosition().
For the map it wasn't exposed, so I just added a getPosition().

That's in local coordinates, so it may not be as useful as you'd like.  If you need getPositionGeo() let me know.
