### ISSUE TITLE
Exception when creating a TileSource

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#482]
I am having a go at the Android version that I have compiled myself from the source (hint ?) and I have an exception in my app when I try to create a remoteTileSource...

> java.lang.UnsatisfiedLinkError: No implementation found for void  com.mousebird.maply.CoordSystem.nativeInit() (tried  Java_com_mousebird_maply_CoordSystem_nativeInit and Java_com_mousebird_maply_CoordSystem_nativeInit__)
> at com.mousebird.maply.CoordSystem.nativeInit(Native Method)
>  at com.mousebird.maply.CoordSystem.<clinit>(CoordSystem.java:72)
> at com.mousebird.maply.RemoteTileSource.<init>(RemoteTileSource.java:49)

I Googled a bit and it seems to be tied to Native-Java bridge.
Maybe I did compile it wrong...

I am on the 3.0 branch and copied the resulting Android-debug.aa to my project.

Is it the best option ?
I have seen that there is a version on Maven but it looks really outdated.
Or should we rather use it ?

tia,
JM

**Comment by mousebird** [comment]
The source tree is the right one to use.

Can you create it without a remote tile source and does it come up?
I'm wondering if it's just missing the JNI library or if this is specific to CoordSystem.

**Comment by jmcazaux** [comment]
It is coming up indeed if I do not add any RemoteLayer (though it is desperately blank ;))

**Comment by mousebird** [comment]
Can you set the clearColor just to make sure the renderer is rendering?

I want to establish that the native library is loading correctly.

**Comment by jmcazaux** [comment]
> MovingMapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mousebird.maply.MaplyRenderer.setClearColor(float, float, float, float)' on a null object reference

It seems the renderer is null indeed...

**Comment by jmcazaux** [comment]
This is the same behaviour with a GlobeController.

**Comment by mousebird** [comment]
Sounds like the controller didn't initialize.  How are you creating the GlobeController (or MapController) in your fragment?

**Comment by jmcazaux** [comment]
I am creating it in an activity, not a fragment...

That is little bit in limbo... I am trying to plug into the middle of my existing code, so not the easiest to read.

I have a subclass of MapController with this initialiser : 
>    public MovingMap(Activity activity, QuadImageTileLayer.TileSource tileSource) {
>      super(activity);
>
>      this.context = activity;
>
>       if (tileSource != null && tileSource instanceof RemoteTileSource) {
>           this.setupImageLayer(tileSource, CACHE_DIR, 1);
>       } else {
>           this.reloadLocalMaps();
>       }
>
>    }

I have a builder that call this method with a Remote Tile source when there is no local source defined and null when local map exists.

Then from within my activity, I call the builder that send back a map and then : 
>FrameLayout r = (FrameLayout) this.findViewById(R.id.mapContainer);
>        map = MovingMapBuilder.build(this);
>        r.addView(map.getContentView(), new RelativeLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT));

Maybe it is because I do not use a fragment, or the order I do things...

**Comment by mousebird** [comment]
One thing to do is take a look at onSurfaceCreatedTask().  I typically do all my setup for the layers and such in a task I pass to that.  That way you can be certain the renderer is set up before trying to access it.

**Comment by jmcazaux** [comment]
Ok, I have started again from scratch in a new application and I succeeded displaying something... Briefly.

When using a MapController it crashes on when interacting with the map.

You can find the crash dump here: https://gist.github.com/jmcazaux/bd967f604ae892ce4997

**Comment by jmcazaux** [comment]
Ok, I have found my way around creating the map controller.
I am still not sure why it was not working using a builder pattern, but it is working with all in the same class.

The issue with the MapController remains though.

Feel free to close this one and reopen a separate issue specific to the map issue.

**Comment by mousebird** [comment]
Can you paste in your new setup code?  I want to compare it to the example.

**Comment by jmcazaux** [comment]
I have cleansed all the code not related, so I am not sure it complies, but here the thing: 
https://gist.github.com/jmcazaux/c2cd045ea597f423d60f

Note: this is the code that works.

**Comment by mousebird** [comment]
That looks reasonable to me.

I'm confused now, which case is crashing?

**Comment by jmcazaux** [comment]
Before that I was using a builder pattern where the TileSource was initialised in the (static) builder and passed to the constructor of the MovingMap as a parameter.

This was crashing when initialising the TileSource.
Do not bother with this unless you want to solve it for others.

What is still crashing though is any interaction on a MapController.

Sorry for the confusion.

JM

**Comment by mousebird** [comment]
Is this still happening?

**Comment by jmcazaux** [comment]
I came back on this branch recently and I experience a crash when I zoom out enough so that the corners of the screen are "in deep space".

It is crashing when calling the Gesture Delegate

`    private GestureDelegate mapDelegate = new GestureDelegate() {
        @Override
        public void userDidSelect(GlobeController controller, Object o, Point2d loc, Point2d screenLoc) {
            // Intentionally blank
        }

        @Override
        public void userDidTap(GlobeController controller, Point2d loc, Point2d screenLoc) {
            // Intentionally blank
        }

        @Override
        public void globeDidStartMoving(GlobeController controller, boolean userInitiated) {
            // Intentionally blank
        }

        @Override
        public void globeDidStopMoving(GlobeController controller, Point3d[] corners, boolean userInitiated) {

            Point3d center = controller.getPosition();

            Log.v(MovingMap.this, "Globe did stop moving (lat: %.6f° lon: %.6f° z: %.6f)",
                    center.getY() * RAD_TO_DEG, center.getX() * RAD_TO_DEG, center.getZ());

            for (MovingMapOverlay overlay : overlays) {
                overlay.positionDidChange();
            }
        }
    };`

**Comment by mousebird** [comment]
I believe this is now fixed.
