### ISSUE TITLE
[Android] Track up vs. North up

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#489]
Hi again,
I cannot find how to rotate the map to *not* have North up.

I'd like to have track up, but I fail miserably...

Any hint welcome.
tia
JM

**Comment by mousebird** [comment]
Is this Android?  Globe or map?

**Comment by jmcazaux** [comment]
Android and Globe.

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aG5EE1Qk&#x2F;101-android-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Android Bugs</a>

**Comment by mousebird** [comment]
keepNorthUp is exposed in the globe controller now.
There's no gesture for rotation at the moment, though.

**Comment by jmcazaux** [comment]
Ok, keepNorthUp is actually exposed, but how can you set the heading when setting the position.

What I mean is that the guy moved, I update the map with his position, but I want to rotate the map so that the track is up.

I have not found a method to do this...

Thanks,
JM

**Comment by mousebird** [comment]
You'll need access to the heading as well as the position.
It would be best to port over the full animation state logic, rather than setting them one by one.

**Comment by mousebird** [comment]
The heading is now exposed on the map.
