### ISSUE TITLE
[Android] ScreenMarker.rotation ignored

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#490]
I tried screen markers and the "rotation" attribute does not seem to be making any difference...

**Comment by mousebird** [comment]
I could believe that.  I'll take a look at your pile of Android issues on Monday.  Thanks for marking this [Android]

**Comment by jmcazaux** [comment]
If that is any comfort, it seems that it works on labels ;).

**Comment by mousebird** [comment]
Some comfort.  A lot of these fields haven't been hooked up because no one used them on Android.  It's just a matter of tracing through the logic to see where the disconnect is.

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aG5EE1Qk&#x2F;101-android-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Android Bugs</a>

**Comment by mousebird** [comment]
Should be working now.

**Comment by jmcazaux** [comment]
Yep, works!
