### ISSUE TITLE
[Android] Crash when setting label offset

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#492]
I noticed that the libs crashes when setting an offset on ScreenLabels (this is on a globe, I have not tried on a map yet).

**Comment by jmcazaux** [comment]
Forgot to add the race

> 01-25 10:57:18.442 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: attempt to access field long com.mousebird.maply.Point2d.nativeHandle from an object argument of type com.mousebird.maply.InternalLabel: 0x7f7cfbe6c0
> 01-25 10:57:18.442 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]     in call to GetLongField
> 01-25 10:57:18.442 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]     from void com.mousebird.maply.InternalLabel.setOffset(com.mousebird.maply.Point2d)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410] "Maply Layer Thread" prio=5 tid=15 Runnable
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x12eea060 self=0x5583b9e670
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=14432 nice=0 cgrp=default sched=0/0 handle=0x7f7bee1450
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 544294081 222553088 715 ) utm=54 stm=0 core=1 HZ=100
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   | stack=0x7f7bddf000-0x7f7bde1000 stackSize=1037KB
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 0000000000489d98  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::ArtMethod*, void*)+236)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 0000000000458f58  /system/lib64/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+220)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 000000000030d3c0  /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1000)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 000000000030dc78  /system/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+116)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 0000000000142fdc  /system/lib64/libart.so (art::ScopedCheck::AbortF(char const*, ...)+144)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 0000000000162be0  /system/lib64/libart.so (art::ScopedCheck::CheckFieldAccess(art::ScopedObjectAccess&, _jobject*, _jfieldID*, bool, art::Primitive::Type)+2892)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 000000000016431c  /system/lib64/libart.so (art::CheckJNI::GetField(char const*, _JNIEnv*, _jobject*, _jfieldID*, bool, art::Primitive::Type)+656)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 00000000001649f4  /system/lib64/libart.so (art::CheckJNI::GetLongField(_JNIEnv*, _jobject*, _jfieldID*)+44)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 00000000004e183c  /data/app/com.droidfav2-1/lib/arm64/libMaply.so (_JNIEnv::GetLongField(_jobject*, _jfieldID*)+44)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 00000000004eea34  /data/app/com.droidfav2-1/lib/arm64/libMaply.so (JavaClassInfo<Eigen::Matrix<double, 2, 1, 0, 2, 1> >::getObject(_JNIEnv*, _jobject*)+92)
> 01-25 10:57:18.443 14258-14432/com.droidfav2 A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 00000000004f4ac0  /data/app/com.droidfav2-1/lib/arm64/libMaply.so (Java_com_mousebird_maply_InternalLabel_setOffset+60)

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aG5EE1Qk&#x2F;101-android-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Android Bugs</a>

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aG5EE1Qk&#x2F;101-android-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Android Bugs</a>

**Comment by jmcazaux** [comment]
This works indeed now, many thanks!
