### ISSUE TITLE
[Android] minVis and maxVis are ignored on MarkerInfo & LabelInfo

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#493]
I tried to play with maxVis & minVis on a globe and it seems they have no effect.

**Comment by mousebird** [comment]
On what sort of object?  Image layer, screen marker?

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aG5EE1Qk&#x2F;101-android-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Android Bugs</a>

**Comment by mousebird** [comment]
Oh, markers and labels.  Didn't read the title.  Nevermind.

**Comment by mousebird** [comment]
Seem to be working now.

**Comment by jmcazaux** [comment]
Strangely this does only work when you set both maxVis and minVis (exactly : I had to set minVis to 0 for my maxVis to be accounted for).

Might be worth pointing out in the documentation.

**Comment by sabiland** [comment]
kMaplyMinVis / kMaplyMaxVis doesn't seem to work on iOS (WhirlyGlobe 2.3) with MaplyScreenLabel. Or am I doing something wrong ?

```
pc.WhirlyBackReferenceLabel = globe.addScreenLabels([pc.LabelData], desc: [
                    kMaplyFont: UIFont.boldSystemFontOfSize(pc.LabelFontSize),
                    kMaplyTextOutlineColor: pc.LabelOutlineColor,
                    kMaplyTextOutlineSize: pc.LabelOutlineWidth,
                    kMaplyTextColor: pc.LabelColor,
                    kMaplyMaxVis: 0.5   // TESTING:
                    ])
```

**Comment by mousebird** [comment]
You have to set both minVis and MaxVis.

**Comment by sabiland** [comment]
Omg this should be in the documentation. I thought minVis/maxVis just don't work. But they do when they are both setted :).
