### ISSUE TITLE
[Android] Relation between height and on screen distance (between 2 points)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#494]
Hi again,
experiments going on...

I was trying to experimental determine cut off height for various items on my app and I found out that it was likely to be device dependant (though I have not found the relation yet).

Let me explain:
* I have 2 physical devices
  * A Sony Xperia SP , 4.6 inches, 720 x 1280 px, 319 ppi
  * A Nexus 9, 8.9 inches, 1536 x 2048, 281 ppi
* I am tuning the zoom on both devices to have the same distance (say 1 inch) between the two same points.

I was expecting the height (controller.getPosition().getZ() to be the same on both devices...
They were actually very different.

It was 0,004341 on the phone and 0.010760 on the tablet.

It means that if you set cutoff heights the same way, the screen is likely to be cluttered on some devices, and the density of information will be completely different and unpredictable.

How can we overcome this ?
Is there a formula to convert height to plain-old-OSM-zoom ?

How can we get a value that would be representative of the density on screen ?

Many thanks,
Jean-Michel

**Comment by mousebird** [comment]
There is a formula on iOS.  I have a calculation for Mapnik scale denominator to height and vice versa.  I haven't moved that over to Android, though.

The various paging layers all use pixel space, so they're unlikely to clutter things up too much.  However, for static objects that are loaded once at startup, that can definitely happen.

**Comment by jmcazaux** [comment]
I am not sure I am on the right track, but basically, I have a handful different kind of objects and based on their kind, I won't to hide them depending on "scale" (in ancient map terminology).

So I add all of the markers & labels at the beginning with a different info for each based on when I want to see them. The issue is that my thresholds are static but it seems that they should be set depending on the device.

**Comment by mousebird** [comment]
The height calculation will change based on the screen aspect ratio.  On iOS I think people just kind of locked in on values they liked and called it a day.  On Android you've got so many different aspect ratios, screen sizes, and physical sizes that doesn't really work.

I'll take a look at moving over the scale calculation code.  It should be pretty simple.  Then you can use scale denominators (Mapnik style) and convert to heights for the appropriate device.

**Comment by jmcazaux** [comment]
Would be great to have something device independent indeed (even if it is not 100% right).

**Comment by mousebird** [comment]
Scale denominators are your best bet.

**Comment by mousebird** [comment]
I just exposed heightForMapScale in the base controller.  Let me know if that works for this.

**Comment by jmcazaux** [comment]
Works fine, thanks.

To have something truly device independent, you need to divide the scale by the displayMetrics.density.
This express the scale in DPI instead of pixels.
