### ISSUE TITLE
[Android] Label colors mixed up

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#495]
Hi there,
some more as I dig deeper...

In my app I have the concept of overlay.
An overlay contains markers and labels. They are the same color.

I use a different LabelInfo and MarkerInfo for each set of ScreenMarker and ScreenLabel.
I keep a handle on the ComponentObject for each set of LabelInfo and MarkerInfo (as I need to "show" / "hide" each layer).

I do have a very strange behaviour with the label colors. It seems they are mixed up (I really mean "it seems") or they are random but it is strange.

I use colorA for markersA and labelsA and colorB for markersB and labelsB.

MarkersA takes the right color, markers as well.
This is very strange, but it seems labelsA took colorB and labelsB took colorA.

It might not be as simple, but it really seems that it is an index issue for this sort. Maybe a shift in an array or something mile that.

**Comment by mousebird** [comment]
That sounds odd.  Is there a reproducible case for this one?

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aG5EE1Qk&#x2F;101-android-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Android Bugs</a>

**Comment by jmcazaux** [comment]
There is one in my project, but that is going to be a tough one...

I will try to reproduce this in the AndroidTester tomorrow.

**Comment by jmcazaux** [comment]
This is a dupplicate of #503

**Comment by mousebird** [comment]
Fixed
