### ISSUE TITLE
[Android] Can we get something similar to layoutPlacement on iOS ?

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#496]
Currently on Android, it seems that the anchor point for text is the lower right corner (the lower right corner of the text goes onto label.loc).

That is a bit unnatural for most uses. It would be great if we could have something similar to layoutPlacement on iOS or at least if the default anchor point was the lower left corner).

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aG5EE1Qk&#x2F;101-android-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Android Bugs</a>

**Comment by mousebird** [comment]
It should be identical to iOS, but clearly is not.  I'll take a look.

**Comment by mousebird** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aG5EE1Qk&#x2F;101-android-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Android Bugs</a>

**Comment by mousebird** [comment]
layoutPlacement is now accessible, but I suspect the defaults will now do what you want anyway.

**Comment by jmcazaux** [comment]
Unfortunately, it does not seem to work.

The placement flags are not exposed and when trying with hardcoded values (1<<2), it does not change anything.
