### ISSUE TITLE
[Android] GlobeController setPositionGeo() giving inconsistent results

### ISSUE THREAD

**Issue by drhaynes** [mousebird/WhirlyGlobe#499]
When using the `GlobeController` and calling `setPositionGeo()`, the resulting position of the globe does not correspond to the coordinates supplied.

For example, calling:
`mapController.setPositionGeo(-0.1275, 51.507222, 0.1);`

Results in (note the blue marker, which is at the location the map was told to move to):
<img width="591" alt="screenshot 2016-01-26 14 55 47" src="https://cloud.githubusercontent.com/assets/117291/12583929/feac4ffe-c43c-11e5-974d-c94fce6e7ecb.png">

**Comment by mousebird** [comment]
Ah, radians not degrees.  It's annoying, I know.
