### ISSUE TITLE
[Android] Enabling / disabling VectorInfo does not seem to work

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#500]
In my app, I have the concept of layer that the user can enable or disable.
Each layer is made of a lot areal and lined that I group (by kind) in the same vector object.
I have a vector info by layer and I keep a handle on it.

When the user enable/disable the layer, I enable/disable the VectorInfo.
It does change the screen...

JM

**Comment by mousebird** [comment]
VectorInfo has no effect after you call addVectors.

Look for enableObject(s) and disableObject(s) in the controller.

**Comment by jmcazaux** [comment]
Works much better indeed.

Thanks.
