### ISSUE TITLE
[Android] Crash when querying globe.getPosition() when completely zoomed out

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#501]
I think this happens when one of the screen edges is not on the globe.

**Comment by mousebird** [comment]
Where is it crashing?  Are you getting a stack trace?

**Comment by mousebird** [comment]
I haven't seen this.  Let me know if it's still happening.

**Comment by jmcazaux** [comment]
I have switched to another stream of work Steve. I'll try if I can switch back to that branch, but it was pretty straightforward to reproduce: just call getPosition() in GestureDelegate.globeDidStopMoving and then zoom out completely.

**Comment by jmcazaux** [comment]
This is not happening.
I have found another issue, but this one can be closed.
