### ISSUE TITLE
add a line with the arrow

### ISSUE THREAD

**Issue by lu0371** [mousebird/WhirlyGlobe#502]
I want to add a line with the arrow on the globe, should how to do?Thanks

**Comment by mousebird** [comment]
I guess you could draw it out in vectors.  Just make vector lines for each part of it.

Or you could make a line and then put a ScreenMarker at the head of it, pointing in the appropriate direction.

**Comment by lu0371** [comment]
I think I probably know how to do it，Thank you very much

**Comment by JunglerSSS** [comment]
Could you provide me with some sample code? Thanks

**Comment by JunglerSSS** [comment]
> I guess you could draw it out in vectors. Just make vector lines for each part of it.
> 
> Or you could make a line and then put a ScreenMarker at the head of it, pointing in the appropriate direction.

Could you provide me with some sample code? Thanks
