### ISSUE TITLE
[Android] Label Text Colors mixing up Red and Blue channels

### ISSUE THREAD

**Issue by darenig** [mousebird/WhirlyGlobe#503]
When setting the text color for a label, the R and B channels are switched. Setting the value to Red produces Blue, Yellow produces Cyan, etc. Green channel is fine, as is the Alpha channel.

This happens with both setTextColor (r, g, b, a) and setTextcolor (int color).

**Comment by jmcazaux** [comment]
This is actually an issue.
That would be great if it could be fixed.

**Comment by jmcazaux** [comment]
And there is a typo in lInfo.setTextcolor(color).
It should probably be lInfo.setText**c**olor(color)

**Comment by mousebird** [comment]
Fixed
