### ISSUE TITLE
[Android] Label backColor not displaying

### ISSUE THREAD

**Issue by darenig** [mousebird/WhirlyGlobe#504]
Background colors for label are always fully transparent.

Setting the background color on LabelInfo seems to be ignored at some point. I've chased it down to Label Renderer, but I can't really figure out where to check from there.

I've tried setting the RGBAColor to White (255, 255, 255, 255) on line 176 in LabelRenderer.cpp and doing a full recompile. 

Maybe its unable to draw the polygon for the background?

**Comment by mousebird** [comment]
I'll take a look.

**Comment by mousebird** [comment]
Should work now.
