### ISSUE TITLE
SQLITE_OPEN_READONLY

### ISSUE THREAD

**Issue by haidershahzad** [mousebird/WhirlyGlobe#505]
Hi Guys, im facing a issue regarding the SQLITE_OPEN_READONLY, error is Use of undeclared identifier 'SQLITE_OPEN_READONLY' although i have included the libsqlite 3 and libsqlite3.0 but it didnt work. any suggestion.

**Comment by mousebird** [comment]
I ran into this recently myself.  The headers for fmdb seem to have changed.
If you explicitly pull in the sqlite header for the module that's complaining the problem goes away.

**Comment by catarino** [comment]
yep. 

 #import <sqlite3.h> solves the problem. 

problem still exists in last binary

**Comment by mousebird** [comment]
Fixed in the library now.
