### ISSUE TITLE
Crashes in WhirlyKit::BigDrawable::isCompatible(WhirlyKit::BasicDrawable*, Eigen::Matrix<double, 3, 1, 0, 3, 1> const*, double)

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#506]
Been seeing a lot of these in 2.4
http://crashes.to/s/a8c5d49e4f5

**Comment by mousebird** [comment]
"Can you duplicate it?" is my usual question.

Does it seem to be near a layer teardown?

**Comment by JesseCrocker** [comment]
I think i may have found the cause of this, and a bunch of similar crashes. Probably easier to just post a screenshot than try to describe.
<img width="2298" alt="maplybaseinteractionlayer_mm" src="https://cloud.githubusercontent.com/assets/2048291/12830644/9c547f6c-cb4d-11e5-8a5e-9d10541c0c63.png">

**Comment by JesseCrocker** [comment]
Summary: sometimes [MaplyTexture dealloc] gets called after the scene is dealloced, but deallocing a texture ends up calling scene->addChangeRequests(changes), and changeRequests has been dealloced, so it ends up writting on dealloced memory, which causes other things to crash.

How im triggering it:
Repeatedly creating and destroying mapviews, every few seconds.

**Comment by mousebird** [comment]
Ah yes, I've seen something like this before.  Thanks.

**Comment by JesseCrocker** [comment]
I added a testcase for this, but unfortunately it doesn't reproduce the crash. https://github.com/trailbehind/WhirlyGlobe/tree/testcase%2Fsetup-teardown

@mousebird do you have enough information from me to be able to fix this? Do you need a crashing testcase?

**Comment by JesseCrocker** [comment]
It looks like the reason the test case isnt crashing is a memory leak that is causing the MaplyBaseInteractionLayer to never get dealloced.

**Comment by JesseCrocker** [comment]
This seems to fix it: https://github.com/trailbehind/WhirlyGlobe/commit/71145b20011ef970202217760c5431bce1f87294

**Comment by JesseCrocker** [comment]
After further investigation, the  [MaplyTexture dealloc] crash is not the cause of the crash i opened this issue about. the  [MaplyTexture dealloc] is a regression in 2.4.1

**Comment by JesseCrocker** [comment]
No idea how to reproduce this

**Comment by mousebird** [comment]
I don't see anything obvious here.  If it's near a layer teardown, I could see that.  But just randomly when a tile comes in seems very odd.

**Comment by mousebird** [comment]
Are you still seeing this one?  Poking through your crashes, I'm not seeing it, but then I may just be missing it.

**Comment by JesseCrocker** [comment]
Not seeing this any more.
