### ISSUE TITLE
Crash in [MaplyTexture dealloc] when tearing down map. Regression in develop_2_4_1

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#510]
Summary: sometimes [MaplyTexture dealloc] gets called after the scene is dealloced, but deallocing a texture ends up calling scene->addChangeRequests(changes), and changeRequests has been dealloced, so it ends up writting on dealloced memory, which causes other things to crash.

How im triggering it:
Repeatedly creating and destroying mapviews, every few seconds.

I added a testcase for this, but unfortunately it doesn't reproduce the crash. https://github.com/trailbehind/WhirlyGlobe/tree/testcase%2Fsetup-teardown

This seems to fix it: https://github.com/trailbehind/WhirlyGlobe/commit/71145b20011ef970202217760c5431bce1f87294

<img width="2298" alt="9c547f6c-cb4d-11e5-8a5e-9d10541c0c63" src="https://cloud.githubusercontent.com/assets/2048291/12893884/02392084-ce51-11e5-9216-df20c5e36420.png">

**Comment by JesseCrocker** [comment]
https://github.com/mousebird/WhirlyGlobe/commit/4dffdb58964e6fbe7d77bbf4404f7fa520c6b544 did not fix i, still getting a crash with the same stack trace.

**Comment by JesseCrocker** [comment]
Changing MaplyViewController dealloc to
```
- (void)dealloc
{
    if (mapScene)
        [self shutdown];
}
```

Seems to fix it.

**Comment by mousebird** [comment]
Is that actually getting called?  The base class' view controller should have already run the shutdown.

**Comment by JesseCrocker** [comment]
dealloc gets called on the subclass first, then there is an implicit [super dealloc] at the end

**Comment by mousebird** [comment]
Ah, right.  Just clearing out the subclass dealloc calls will probably work better.
I've pushed that change.

**Comment by JesseCrocker** [comment]
Fixed by https://github.com/mousebird/WhirlyGlobe/commit/4dffdb58964e6fbe7d77bbf4404f7fa520c6b544 and https://github.com/mousebird/WhirlyGlobe/commit/36655952ae6ee9417a844490d3e50f7378b9fd00
