### ISSUE TITLE
How can I adjust the camera?

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#512]
Can I adjust the camera into a certain angle? For example, I have a 3D object that I am animating in the globe. How can I adjust the angle of the camera and follow the 3D object?

**Comment by mousebird** [comment]
Take a look at the WhirlyGlobeViewControllerAnimationState and the setViewState: and getViewState methods.  There's also an animation delegate interface if you're feeling fancy.
