### ISSUE TITLE
[iOS] Day/Night shader causing globe to disappear

### ISSUE THREAD

**Issue by falloutfox** [mousebird/WhirlyGlobe#514]
I'm creating an app which will be open all day - and require an (almost) live day/night cycle. At the moment I'm repositioning the sun every hour and resetting the MaplyAtmosphere and MaplyQuadImageTilesLayer shader, which causes the globe to disappear briefly. Here's the code I'm using to reset:

	sun = [[MaplySun alloc] initWithDate:[NSDate date]];
	sunLight = [sun makeLight];
	[globeViewC clearLights];
	[globeViewC addLight:sunLight];
	
	atmosObj = [[MaplyAtmosphere alloc] initWithViewC:globeViewC];
	float wavelength[3] = {0.650f,0.570f,0.475f};
	[atmosObj setWavelength:wavelength];
	[atmosObj setSunPosition:[sun getDirection]];
	
	tileLayer.shaderProgramName = atmosObj.groundShader.name;

Is there anything I'm doing wrong?

**Comment by mousebird** [comment]
Rather than resetting the shader, can you just update the sunPosition?

**Comment by falloutfox** [comment]
Ah yes updating the sun position, without recreating the atmosphere, did it!

Thanks for your help, this is an excellent toolkit!
