### ISSUE TITLE
fly on a MaplyShapeGreatCircle path?

### ISSUE THREAD

**Issue by ludawei** [mousebird/WhirlyGlobe#521]
Can I let a image of the plane fly between two points on a MaplyShapeGreatCircle(with height) path?

**Comment by ludawei** [comment]
I tried to add a MaplyShapeSphere, and update center,height with a timer.But when get the center location between two points,
`
MaplyCoordinate center = MaplyCoordinateMakeWithDegrees((startLat + endLat)/2, (startLon + endLon)/2);
`
the center point is not on the line.

Any ideas?

**Comment by mousebird** [comment]
So a great circle doesn't actually follow a lat/lon line.  A great circle is the shortest distance between two points on the globe.

To get the shape to follow the great circle curve, you'll have to pull the logic for calculating a great circle out of the toolkit and calculate each point yourself.  It's not actually too hard.  You can find great circle calculations on the web and use those instead.
