### ISSUE TITLE
Remove boost

### ISSUE THREAD

**Issue by mousebird** [mousebird/WhirlyGlobe#522]
Boost is no longer needed in the source tree.  I cleaned it out of 3.0, but we might as well do the same in 2.4.1.

All you actually need to do is take out the <boost/...> headers and then convert:
- boost::dynamic pointer to regular std::dynamic_ptrs
- Same for anything else that begins with boost::

Take a look at commit 33654c7e8bc1ad838fb87580b786ea416d5b9e28 in the develop_3_0 tree.  Don't merge that, because the trees are too different, but you can see how to do it.

Then rip boost out of the submodules.

**Comment by rghosh0** [comment]
This one's in the feature/remove-boost branch, and looks to be done.

**Comment by mousebird** [comment]
I modified the podspec to ignore boost.  Can you give the podspec a try with develop_2_4_1?

**Comment by rghosh0** [comment]
OK, I'm trying the command:

pod lib lint --verbose --no-clean

It's failing after a while.  Some warnings about iOS 7 so I changed the platform to iOS 8 in the podspec, but that didn't help.  I opened the temporary project in XCode and it built fine both for an iPad (iOS 8.3, iPad Air) and a simulator target (iPhone 6s Plus).

I'm still working on it but here's the output from the pod lib lint command for iOS 8 and iOS 7 respectively.

https://s3.amazonaws.com/kastra/podliblint.txt.gz
https://s3.amazonaws.com/kastra/podliblint_bkiOS7.txt.gz

**Comment by mousebird** [comment]
The temporary project is fine.  I find pod lint somewhat unhelpful honestly.

Try putting the view controller from the WhirlyGlobeComponentTester in a brand new project, set up the pod and let it pull everything.  If you can compile and run, we'll call it good.

**Comment by rghosh0** [comment]
OK, looks good.

Only catch is I didn't include MapzenSource from the ComponentTester.  MapzenSource.h references MapnikStyleType which is in vector_tiles/MaplyVectorTiles.h, which is intentionally excluded from the pod (#ifdef NOTPODSPECWG ... #import "vector_tiles/MaplyVectorTiles.h")

So I remove it, set the deployment target to 8.3 (if it's lower I get lots of linker warnings), and it builds and runs.

**Comment by mousebird** [comment]
Okay, perfect.  MapzenSource.h shouldn't be in a pod version of that project anyway.  Not that there is a pod-specific version of that project, so don't sweat it.  Thanks1
