### ISSUE TITLE
Provide .framework to download with each release?

### ISSUE THREAD

**Issue by danishin** [mousebird/WhirlyGlobe#523]
Hello,

Perhaps, I'm missing something here but every time, I need to update to latest release (2.4 betas that is) version of WhirlyGlobe, I find myself building the framework manually from the source. And since the source is pretty huge, it takes a while to get started if I move my workplace etc. 

So could you release with `.framework` to download along with the zipped source? Something like the link you provided in [this comment](https://github.com/mousebird/WhirlyGlobe/issues/420#issuecomment-146004834) would be very useful.

Thank you.

**Comment by mousebird** [comment]
It's a good idea. I'd really like to do nightly builds this year and include a binary version in each.

**Comment by sabiland** [comment]
As @danishin said, that would be awesome. Would be even more awesome if .framework would also be builded with bitcode enabled. It's impossible to submit to AppStore with bitcode benefits if not all frameworks are bitcode-support compiled.

**Comment by mousebird** [comment]
Now doing nightly builds.
