### ISSUE TITLE
How to add API token for mapbox tiles request?

### ISSUE THREAD

**Issue by danishin** [mousebird/WhirlyGlobe#524]
I'm trying to move away from offline mbtiles due to storage issues. 

Mapbox's tiles request url is the [following](https://www.mapbox.com/developers/api/maps/): 
`https://api.mapbox.com/v4/{mapid}/{z}/{x}/{y}.{format}?access_token=<your access token>`

After looking at your source code [here](https://github.com/mousebird/WhirlyGlobe/blob/18d263f3f0306a10647bdc080a1df1e0f122144b/WhirlyGlobeSrc/WhirlyGlobe-MaplyComponent/src/MaplyRemoteTileSource.mm#L211), it seems like urls with query string have not been accounted for. 

Am I missing something here or has it not been supported? If so, is there a workaround / way to access lower-level api to construct url request myself?

Thanks for your help

**Comment by danishin** [comment]
So there is json spec [here](https://github.com/mapbox/tilejson-spec/tree/master/2.1.0) that we can use to pass to `init(tileSpec: )` and the spec allows us to do sth like the following, and WhirlyGlobe is very well compliant: 

```
```

**Comment by mousebird** [comment]
There's also a token replacement version of the tile source in 2.4 (develop branch).
With that you you just form it like it is in the tilespec and paste in your tiken.

**Comment by johndpope** [comment]
Thank you.

for those people still tinkering with objective-c

  NSDictionary *tileSpec = [NSDictionary dictionaryWithObjectsAndKeys:@[@"https://api.mapbox.com/v4/mapbox.mapbox-streets-v7/{z}/{x}/{y}.png?access_token=YOURACCESSTOKENHERE"], @"tiles", [NSNumber numberWithInt:0],@"minzoom", [NSNumber numberWithInt:18],@"maxzoom",nil];

        MaplyRemoteTileSource *mapboxSource =   [[MaplyRemoteTileSource alloc]
       initWithTilespec:tileSpec];

        // set up the layer
        MaplyQuadImageTilesLayer *layer =
        [[MaplyQuadImageTilesLayer alloc] initWithCoordSystem:mapboxSource.coordSys
                                                   tileSource:mapboxSource];
        layer.handleEdges = true;
        layer.coverPoles = true;
        layer.requireElev = false;
        layer.waitLoad = false;
        layer.drawPriority = 0;
        layer.singleLevelLoading = true;
        [globeViewC addLayer:layer];

**Comment by mousebird** [comment]
That's a fine way of doing it.  You can also use the constructor for MaplyRemoteTileSource and give it the base URL with the replacement text and your token and just pass in nil for the extension.

Replacement strings are the preferred way for doing this now with all the specialized stuff that can go in the query string.
