### ISSUE TITLE
Set up WhirlyGlobe 2.4 through CocoaPods

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#532]
Good afternoon everyone,

I am trying to set up WhirlyGlobe 2.4 through CocoaPods.

According to the issue #464, I created a pod file with the following line in it:

pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe', :branch => 'develop_2_4_1'

Everything installed correctly. I then add the other libraries that WhirlyGlobe needs:

![screen shot 2016-03-03 at 3 52 06 pm](https://cloud.githubusercontent.com/assets/15698398/13509118/e9ccb64a-e157-11e5-8c65-da00d04c4657.png)

My code looks like Xcode doesn't recognize the WhirlyGlobe framework. It compiles correctly though:

![screen shot 2016-03-03 at 4 00 45 pm](https://cloud.githubusercontent.com/assets/15698398/13509388/2dd2b1e0-e159-11e5-896c-3213996cfd1b.png)

Am I missing something here? 

Thank you in advance guys.

Sebastien.

**Comment by mousebird** [comment]
I assume you're loading the right project for the pod.  So check for WhirlyGlobeComponent.h in your project and see where that is.

**Comment by Sebboulnois** [comment]
I found it under Pods/Pods/WhirlyGlobe/MaplyComponent-Headers/ in my project :

![screen shot 2016-03-03 at 4 14 01 pm](https://cloud.githubusercontent.com/assets/15698398/13509732/f8e8eeac-e15a-11e5-9bd6-e703a1ac5484.png)

Do I need to do something in particular with this file?

**Comment by mousebird** [comment]
The Cocoapods setup seems to change on a regular basis, leaving me with out of date information.
I would check the Header search paths to see if it's including any of the Pod directories.
If not, you might need to explicitly include the header directory for the pods.
Or it might be as simple as using <> rather than "" in the include.

**Comment by Sebboulnois** [comment]
Hello,

It is working now. I didn't change anything. I just closed and run Xcode again.

Thank you!

Sebastien.
