### ISSUE TITLE
Support for Unity3d

### ISSUE THREAD

**Issue by bachirelkhoury** [mousebird/WhirlyGlobe#533]
Excellent library guys.
Any plans to support Unity3D?

**Comment by mousebird** [comment]
I'm not opposed to it, but it's not something I'd do out of overhead.  Someone would need to pay for the whole thing.

WhirlyGlobe-Maply has its own low level rendering engine and it's the tight integration with that engine that makes things fast.  Switching over to theirs would be a lot of work and probably couldn't be accomplished without a significant amount of native code.

The last time I looked into this, it seemed like a better approach would be to keep my rendering engine in place with native code and then then somehow make the renderers... cooperate.  Yeah, that sounds easy.  Then interface any important WG-Maply code via their DLL-like interface (Windows NT represent!  Woo!)

I don't see this happening unless a big pocketed customer steps forward who really needs it.  Looking at the state of geospatial in the Unity community, I don't see any reason to fund it myself.

So much like the Windows Phone, I'm not opposed to it, but I don't see it happening any time soon.  It is an open source toolkit, of course, so feel free to dig in.

**Comment by bachirelkhoury** [comment]
Fair enough. This is more of a complete rewrite request, to really use all the 3D capabilities Unity has to offer. I also think your idea of building perhaps a plugin that interface with the native code for each platform. 

Will require a lot of time, so understandable that you'll need some one to fund it. I will get in touch if this happens to be the case and we get some funding for this. We can then discuss the details and hopefully work together to make it happen.

**Comment by mousebird** [comment]
Are you on the mailing list?  If not, send me your email at contact@mousebirdconsulting.com and I'll add you.

**Comment by mousebird** [comment]
Just going through old Feature Requests.  Nope on this one.
