### ISSUE TITLE
Include 3D models on a Globe

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#534]
Hello everyone,

I am struggling regarding the importation of a 3D model on a globe.

So far, I created a maplyGeomModel object that is initialized with the path of the object:

MaplyGeomModel *boeing737800 = [[MaplyGeomModel alloc]initWithObj:@"/Users/Sebastien/Desktop/HCDIA/ PHD/Xcode/ projects/OWSAS_WhirlyGlobe2_4/Boeing_737_obj/Boeing_737.obj"];

I don't know what to do next. Is it working the same way than with any other shapes? 

Thank you,

Sebastien.

**Comment by mousebird** [comment]
If it successfully read the model, you'll need to instance it.

The ComponentTester should have an example of that.  Just search for MaplyGeomModel.

**Comment by Sebboulnois** [comment]
I reopen this issue because I have a question regarding models. I set the selectable property of my aircraft model to YES. However, when I click it to make an annotation appear, it doesn't recognize my tap gesture on the aircraft but on the map behind. My question is: are textures required for selecting models?

Thanks,

Sebastien.

**Comment by mousebird** [comment]
That should work, yes.  Can you try the same thing with the AutoTester and let me know what happens?

**Comment by Sebboulnois** [comment]
By AutoTester, you mean ComponentTester?

**Comment by mousebird** [comment]
No AutoTester.  You'll find it in the source distribution.
