### ISSUE TITLE
Flat MaplyScreenMarkers?

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#535]
Is it possible to make MaplyScreenMarker work like MaplySticker?
Or is there any way that I can catch user interaction such as taps in a MaplySticker?

**Comment by mousebird** [comment]
A MaplySticker has a real size on the globe.  The MaplyScreenMarker is a screen object.  So the equivalent is a MaplyMarker.

Any feature can be selected.  Just fill in the delegate for the WhirlyGlobe or the Maply ViewController.
