### ISSUE TITLE
2.4 beta 8 - Annotations CPU heavy?

### ISSUE THREAD

**Issue by sabiland** [mousebird/WhirlyGlobe#538]
I've just realized that if many (> 5) annotations are visible then CPU goes really high? Is maybe there any simple solution to this?

**Comment by mousebird** [comment]
Annotations are implemented with UIViews.  They tend to be more expensive.

A cheaper alternative are MaplyScreenMarkers.

**Comment by sabiland** [comment]
Ok thx, I totally overlooked they were UIViews.

**Comment by bintu1234** [comment]
@mousebird Hi I am working with the Annotations but as you said i am following screen markers.But i want some thing like below when i use 3d & 2d markers it is not showing what i am expecting.how to do that.Please find the attachmant
![anootations](https://cloud.githubusercontent.com/assets/15229187/19756651/e0b744b8-9c3b-11e6-843a-04c9667af50c.png)

**Comment by mousebird** [comment]
I'm sorry I'm not sure what you question is.

**Comment by bintu1234** [comment]
Sorry my bad, I found some solution.Thanks for the Replay
