### ISSUE TITLE
GlobeView transparency

### ISSUE THREAD

**Issue by solevic** [mousebird/WhirlyGlobe#539]
I've been struggling with setting a transparent background to the GlobeView on Android for some time now.

The issue is the following:

When setting a clear color with full transparency, the view background remains black.
Setting the property setZOrderOnTop to true manages to achieve a transparent background, however, all the views placed above on the layout gets pushed below the GlobeView and pushing them back to the top is not possible.

So here is my question:

Is there any other way of achieving a transparent background other than setting setZOrderOnTop to true? If you're not aware of any, how could I be able to set a background image to the view?

Best regards.

**Comment by mousebird** [comment]
I'd have to experiment with this to give you a complete answer.
Though the clearColor is set, it may be that the Surface's background color also needs to be set.

**Comment by mousebird** [comment]
I think I'm dealing with you directly on this.  If I'm talking to someone else let me know.
For the record, we do seem to need setZOrderOnTop.
