### ISSUE TITLE
Ergonomic issues - tiles updating rate

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#540]
Hi everyone,

I am using remote tiles as a main layer on my globe. I end up with these kind of visuals when I get closer: 

![thumb_img_2281_1024](https://cloud.githubusercontent.com/assets/15698398/13816630/82dc0cfc-eb65-11e5-8594-00a815ce2abf.jpg)

Is there any way to fix this issue? I looked at all the properties of MaplyQuadImageTilesLayer and tried a lot of things but it seems like I am not figuring it out.

I have another question. Do you guys know about globe layers that are very accurate (close to Google earth ones)? I need a very realistic layer for my application.

Thank you,

Sebastien.

**Comment by mousebird** [comment]
HERE has a good layer, as does Bing.  Mapbox's satellite layer is quite nice as well.

I'm not sure what I'm seeing in this picture.  What part of it is wrong?

**Comment by Sebboulnois** [comment]
Thank you for the information. I am going to have a look at it. 

For giving you more context, I am developing an application that is gonna be used by professional aircraft pilots. 
In the picture, you can see different shades of quality, accuracy and color according to the distance between the camera and the terrain (let me know if you dont see the same thing). 
From a human-centered approach, it is not that good regarding their Situation Awareness. I was wondering if I could fix that by just having the best quality all the time, or at least trying to get something smoother.

Best,

Sebastien.

**Comment by mousebird** [comment]
Are you a support customer?  If not, that might be a good idea.

I can only address the technical side of the display.  If you want to see how it's loading, there's a MaplyAnimationTestTileSource you can use to see what levels are loading where.  Take a look at the ComponentTester app to see how it's used.
