### ISSUE TITLE
Vector tiles from URL

### ISSUE THREAD

**Issue by haidershahzad** [mousebird/WhirlyGlobe#545]
Hi,

Hope you guys doing well. Im having a problem while loading vector data from url, pleases give me a possible answer on how can i load data from the url below,

http://192.168.10.200:8080/composite/{z}/{x}/{y}.json

The url i provided is currently working on local host but i have attached the image of response generated by url.

Please point me the right directions.

Thanks.
![screen shot 2016-03-18 at 2 14 17 pm](https://cloud.githubusercontent.com/assets/119604/13910492/ca31cfa0-ef44-11e5-96fd-cc3f1c282ccb.png)

**Comment by mousebird** [comment]
Possibly you should look at [CartoDB Example](http://mousebird.github.io/WhirlyGlobe/tutorial/cartodb_layer.html) because it loads vector data in tiles using the MaplyQuadPagingLayer.
