### ISSUE TITLE
How to set max zoom level of the globe

### ISSUE THREAD

**Issue by dhawaldawar** [mousebird/WhirlyGlobe#547]
Hi Steve,

Firstly thanks for providing the great map sdk.

I'm facing one problem while setting the max zoom level of the globe.

Actually I'm using mbtile file to show map on globe but zoom is going beyond its max zoom level while pinch in. Could you please help me to restrict the zoom level for offline maps.

Thank you.﻿

**Comment by mousebird** [comment]
The method for that is [setZoomLimits](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/WhirlyGlobeViewController.html#//api/name/setZoomLimitsMin:max:)
