### ISSUE TITLE
How to show offline terrain data on globe

### ISSUE THREAD

**Issue by dhawaldawar** [mousebird/WhirlyGlobe#548]
Hi Steve,

Could you please guide me how to show offline terrain data on globe as I'm new to this. Also I have checked the code "WhirlyGlobeComponentTester" but in the APP whenever I select "Globe w/ Elevation (3D)", it shows me globe with tile numbers on it, like 5: (5,10)

I have also read your blog on terrains http://mousebirdconsulting.blogspot.in/2013/09/whirlyglobe-maply-feature-elevation.html but "Mapbox Terrain - Remote" section is not in the base layers list.

Could you please help me to sort out this. I would really appreciate it.

Thank you.

**Comment by mousebird** [comment]
Mapbox Terrain is just an image layer.  It still works, but Mapbox isn't providing sample basemaps anymore so I've taken it out of the samples.  I don't want to be checking my Mapbox keys into github, obviously.  It's not really terrain, though.

Cesium Terrain is really good, but their tiling scheme doesn't correspond to anything else so we can't easily overlay data on top.

For offline terrain... well that should work.  I'll take a look at the AutoTester example and see what's going on.  Perhaps we're not including the data.  I'll get back to you on that.

**Comment by mousebird** [comment]
The example in the AutoTester for a local elevation database is working again.  It was just a missing file.

Take a look in the develop_2_4_1 branch in the AutoTester app, specifically the ElevationLocalDatabase testCase.

**Comment by dhawaldawar** [comment]
Thanks for your help Steve.

We have contracted with terrain provider and they have given us terrain in zip file format to show on maps, under this file we are getting many files, please check sample below:

062.rgba
64\53\archive.txp
64\53\tileFile_0.tpf

I have searched a lot regarding the same but didn't find anything useful, Are you supporting this kind of files in your sdk to show terrain layers?

Thank you again for all your help.

**Comment by mousebird** [comment]
You've contracted someone to give you TerraPage?  Huh.
That's not a standard part of the toolkit and I know of only one user right now who also has the only implementation within WhirlyGlobe-Maply.

Let's take this offline.  Email me at sjg@mousebirdconsulting.com
