### ISSUE TITLE
Android Installation

### ISSUE THREAD

**Issue by hallahan** [mousebird/WhirlyGlobe#550]
I'm having trouble building still. Do you have any instructions for building on Android?

When trying to execute buildmaply.sh, I am getting this exception:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':buildNative'.
> A problem occurred starting process 'command '/usr/local/Cellar/android-sdk/24.4.1_1/ndk-build''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

This is after updating local.properties with:
```
sdk.dir=/Users/njh/Library/Android/sdk
ndk.dir=/usr/local/Cellar/android-ndk/24.4.1_1
```

**Comment by jmnavarro** [comment]
You need to point your `ndk.dir` variable to a valid NDK path. Notice Android SDK and NDK a different packages and you need to install both

**Comment by hallahan** [comment]
Thanks, just caught that as you were writing your response : ).

Am I going down the right path by executing `buildmaply.sh` to get all the native bits compiled? Do you have any README regarding building example apps for Android?

**Comment by mousebird** [comment]
That's right script for now.  We need to document that a bit better.

At some point I imagine this will all change when Android Studio handles the NDK better.

**Comment by hallahan** [comment]
I got the app building now. Thank you!
