### ISSUE TITLE
Marker Max/Min Size

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#552]
Right now the MaplyMarker doesn't seem to have a max/min size. Like at a certain point it would only be this small if I zoom out and this big if I zoom in. I was thinking about resizing the markers on change of zoom level but I know this would not be efficient.

**Comment by jerald-acacus** [comment]
Okay. Would this actually be the MaplySticker? Just what is the difference of a MaplyMarker and a MaplySticker?

**Comment by mousebird** [comment]
MaplyMarker is a 3D marker in that it has a size in the real world.  It always stays that size (in the real world).

MaplySticker is like a MaplyMarker but can be much bigger.  It will adapt itself to the globe to accomplish that.

MaplyScreenMarker is a 2D marker that is projected to the screen from its central point and then drawn in 2D.  It will stay the same size in screen space.
