### ISSUE TITLE
How can i show my data by lambert projection?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#555]
Hi,When I use MaplyViewController class to show my custom data from database,I found it only can use Spherical Mercator.

**Comment by mousebird** [comment]
Yes, you can display any valid proj.4 [coordinate system](http://mousebirdconsulting.blogspot.com/2016/03/map-projections.html).  You'll need the develop_2_4_1 tree and the proj.4 string describing LCC.

**Comment by marychenyuan** [comment]
Thanks!  but...Can you give me some demo or more details? I was a little confused about how to do by coding...

**Comment by mousebird** [comment]
Look for the British National Grid (BNG) example in the AutoTester app.

**Comment by marychenyuan** [comment]
Thank you very much! 
I know how to do it.  But...When I look the [samples](http://mousebirdconsulting.blogspot.com/2016/03/map-projections.html),I did't find "MaplyProj4CoordSystem" class in source code.   so，How can i create the objects like this:
let coordSys = MaplyProj4CoordSystem(string: proj4Str)
...

**Comment by mousebird** [comment]
So the example was written for Swift.  You'll just need to do the equivalent thing in Objective-C.

Make sure you have the develop_2_4_1 branch, though, because the MaplyProj4CoordSystem object is in there.

**Comment by marychenyuan** [comment]
Awesome~~~!!! Thank you for your patience guidance！
