### ISSUE TITLE
Docs - Add App Transport exception to remote image tutorial

### ISSUE THREAD

**Issue by mousebird** [mousebird/WhirlyGlobe#556]
As it exists, the remote image tutorial won't work.
We either need to find an HTTPS image layer or instruct the user to add the App Transport exception.

**Comment by mousebird** [comment]
Can you take a look at this one?
All you need to do is add language to the tutorial to show them how to add the transport permission to get http: rather than https: tile sources.  A screen shot would be helpful for that too.
Thanks!

**Comment by jmnavarro** [comment]
Fixed on https://github.com/mousebird/WhirlyGlobe/commit/5e3464693c5e418601bba067ba33025a0eda7f45
