### ISSUE TITLE
[Android] Supported Architectures?

### ISSUE THREAD

**Issue by darenig** [mousebird/WhirlyGlobe#557]
Hi,

I was wondering if WhirlyGlobe-Maply supports architectures other than armeabi. I've checked out the most recent code, and it doesn't seem to compile for anything other than armeabi (armeabi-v7a, x86, etc.). 

I also get warnings regarding unsupported extensions for the aaplus lib files:
>  Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module Maply
> Android NDK:   ../../..//WhirlyGlobeSrc/local_libs/aaplus/\ ../../..//WhirlyGlobeSrc/local_libs/aaplus/\ ../../..//WhirlyGlobeSrc/local_libs/aaplus/\ ../../..//WhirlyGlobeSrc/local_libs/aaplus/\ ../../..//WhirlyGlobeSrc/local_libs/aaplus/\ ../../..//WhirlyGlobeSrc/local_libs/aaplus/\ ../../..//WhirlyGlobeSrc/local_libs/aaplus/\ ../../..//WhirlyGlobeSrc/local_libs/aaplus/\

I was able to compile for armeabi-v7a and x86 in versions prior to the inclusion of aaplus files.

**Comment by mousebird** [comment]
Those warnings are related to an error in the way I included the aaplus library in the Android.mk file.  I'm not sure why, exactly, but they seem to be benign.

I regularly compile for armeabi-v7a and x86.  If you use the buildmaply.sh script in the AndroidAutoTester it should compile for several other architectures by default as well.

What error are you getting?

**Comment by darenig** [comment]
The build process generally fails in cygwin.
> ./gradlew: line 2: $'\r': command not found

I usually build the shared objects via ndk-build, and assemble the jar separately. 

The error I get when compiling is:
> [arm64-v8a] Compile++      : Maply <= glwrapper.cpp
> [arm64-v8a] SharedLibrary  : libMaply.so
> aarch64-linux-android-g++: error: CreateProcess: No such file or directory
> make: *** [obj/local/arm64-v8a/libMaply.so] Error 1
Generally the same for each architecture I attempt to build.

**Comment by mousebird** [comment]
Cygwin?  So this is Windows?
I'm afraid I don't have a setup to test this on Windows.

**Comment by darenig** [comment]
Yes, I develop in a Windows environment. The cygwin error is related to windows style newline, but correcting for that still fails on running buildheaders.sh

> Caused by: java.io.IOException: Cannot run program "./buildheaders.sh" (in directory "...\WhirlyGlobe\WhirlyGlobeSrc\Android"): CreateProcess error=193, %1 is not a valid Win32 application

**Comment by mousebird** [comment]
So that runs javac and javah on all the various files that need to generate JNI headers.  However, those headers are checked in, so you could just turn off the buildheaders.sh call in the gradle setup.

**Comment by darenig** [comment]
Bypassing the buildheaders script allows the build process to run, until it reaches shared object creation. It fails in the same manner as running ndk-build directly.

Currently investigating ndk-build.cmd and exit code 2

**Comment by mousebird** [comment]
Well that at least makes sense.  I don't have an environment to test this on so I can't really suggest what to look at next.

**Comment by jmnavarro** [comment]
I've just pushed the fix in the build to support Windows.

Can you try it and let us know?

Thanks!

**Comment by mousebird** [comment]
Going to close this now that José's pushed the fix.  If it's not working for you, please reopen.
