### ISSUE TITLE
the first person perspective

### ISSUE THREAD

**Issue by lu0371** [mousebird/WhirlyGlobe#558]
Hi,does the WhirlyGlobe has the first-person perspective with Animation?And if have how todo that?
Thanks!

**Comment by mousebird** [comment]
For the globe, you do have full control over the view state.  Take a look at the [animation delegate](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/WhirlyGlobeViewControllerSimpleAnimationDelegate.html) and the [animation state](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/WhirlyGlobeViewControllerAnimationState.html).

**Comment by lu0371** [comment]
I‘am sorry，I didn't do it！I set up the GlobeView heading, but the display effect  didn’t agree with I had expected 。
examples：
I need the globe animate from position (10,110) to position (50,110),I want the globe rotation 90 degree first，and then animation move to (50,110)；
I use solution like this：
set up the heading
     _globeViewC.heading = M_PI/2；_
Interpolate temp position between (10,110) and (50,110)，
and animate to each temp position：
    _[globeViewC animateToPosition:tmpCoord time:0.0];_
but the globe view is not correct，Can you help me to complete this demo Or provide some better Suggestions about this？ Thank you very much！

**Comment by mousebird** [comment]
I suggest using [animation state](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/WhirlyGlobeViewControllerAnimationState.html) and the [setViewState:](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/WhirlyGlobeViewController.html#//api/name/setViewState:) method to set all of the values at once.  You can even use the [getViewState:](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/WhirlyGlobeViewController.html#//api/name/getViewState:) method to fetch the existing state and then modify it.
