### ISSUE TITLE
Clipping a MaplyVectorLinear where the first and last points are coincident drops the last point

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#559]
Im calling `[MaplyVectorLinear clipToMbr:upperRight]` on a Linear where the first and last points are coincident and is fully within the clipping MBR, and the returned Linear has the last point dropped. The problem seems to be in `GridClipper ClipLoopToMbr`.

@mousebird Im planning on trying to fix this in the next few weeks, but if you know of a fix for this, let me know.

**Comment by mousebird** [comment]
Well that kind of makes sense.  It converts the linear over to the representation the clipper uses and then converts it back.

You could check to see if the bounding box of the linear is completely within the clip area and then just do nothing.

**Comment by JesseCrocker** [comment]
This seems to be the correct behavior for clipper, and not something that can be changed in how we are calling clipper, and the points seem to be sometimes returned in reverse order, so there is no  way around this. I think it's just caller beware for now.

**Comment by mousebird** [comment]
The semantics for areal vs linear may be getting in the way here.
It may be assuming that a closed linear is really an areal in disguise.

**Comment by JesseCrocker** [comment]
Test case for this https://gist.github.com/JesseCrocker/88997dd761e17f2cd098b17cec3da222

**Comment by mousebird** [comment]
I assume the fix you checked in fixes this, right?

**Comment by JesseCrocker** [comment]
Yes, fixed.
