### ISSUE TITLE
Getting duplicate symbol while adding WhirlyGlobeMaplyComponent framework

### ISSUE THREAD

**Issue by Coder-iOS** [mousebird/WhirlyGlobe#560]
I have added WhirlyGlobe framework into my existing project where I had already using AFNetworking and MapBox libraries, due to this I'm getting below error while compiling the code.

duplicate symbol _OBJC_IVAR_$_FMStatement._query in:
    /Users/amitvyas/Desktop/GAV Unit Configurator T3/GAV Unit Configurator T3/Classes/Supporting Classes/MapBox/libMapbox.a(FMDatabase.o)
    /Users/amitvyas/Desktop/GAV Unit Configurator T3/GAV Unit Configurator T3/Supporting Files/Framework/WhirlyGlobeMaplyComponent.framework/WhirlyGlobeMaplyComponent(FMDatabase.o)

duplicate symbol _OBJC_CLASS_$_AFHTTPSessionManager in:
    /Users/amitvyas/Library/Developer/Xcode/DerivedData/GAV_Unit_Configurator_T3-hjbpigmtxuicmqhbokjydojjxqge/Build/Intermediates/GAV Unit Configurator T3.build/Debug-iphonesimulator/Pilot.build/Objects-normal/x86_64/AFHTTPSessionManager.o
    /Users/amitvyas/Desktop/GAV Unit Configurator T3/GAV Unit Configurator T3/Supporting Files/Framework/WhirlyGlobeMaplyComponent.framework/WhirlyGlobeMaplyComponent(AFHTTPSessionManager.o)

I think framework already have these classes that's why I'm facing this issue, Could you please help me how to resolve that.

**Comment by mousebird** [comment]
Yup, this can happen.  We removed the AFNetworking dependency recently so if you want to grab a [binary version](https://dl.dropboxusercontent.com/u/29069465/WhirlyGlobeMaplyComponent.framework_2_4_1_beta8.zip) of the recent beta this should fix it.

**Comment by Coder-iOS** [comment]
Yes, now I'm not getting any duplicate symbol for AFNetworking.

Thanks
