### ISSUE TITLE
Terrain is not showing in AutoTester APP

### ISSUE THREAD

**Issue by Coder-iOS** [mousebird/WhirlyGlobe#561]
I have checked AutoTerrain APP for "Elevation (local)" but its not showing the terrain instead its showing some number over the globe. Please check attached image.

![simulator screen shot 27-apr-2016 12 42 52 am](https://cloud.githubusercontent.com/assets/18679844/14830831/575b7c18-0c10-11e6-8dd2-168f9c850333.png)

Please help me how to show this.

**Comment by mousebird** [comment]
Keep zooming in.

**Comment by Coder-iOS** [comment]
Please see below screenshot

![simulator screen shot 27-apr-2016 1 05 54 am](https://cloud.githubusercontent.com/assets/18679844/14831486/a6cc5c42-0c13-11e6-828e-d40343fee08a.png)

Now I can see some textures there, this is what you are talking about?

**Comment by mousebird** [comment]
No textures, that's terrain.  You'll have to move around to find somewhere interesting.

The blog has a description of the state of [Cesium terrain](http://mousebirdconsulting.blogspot.com/2015/08/cesiumjs-terrain-support.html) support.

**Comment by Coder-iOS** [comment]
I have gone through your blog regarding elevation: http://mousebirdconsulting.blogspot.in/2013/09/whirlyglobe-maply-feature-elevation.html

And used the sample database world_map_mercator_pacnw.sqlite but still not able to see something like below

![screen shot 2016-04-27 at 1 43 32 am](https://cloud.githubusercontent.com/assets/18679844/14843789/9977f9d6-0c70-11e6-9bfa-9d8b35bc657e.png)

**Comment by Coder-iOS** [comment]
Could you please help to solve this issue as I need to implement it in my project as soon as possible.

Thank you for your help! I really appreciate it.

**Comment by mousebird** [comment]
I just ran the Elevation (local) test case in the AutoTester and it's loading the world_web_mercator database just fine.  If you substitute the pacnw database (which is large) it'll load that too.

By default I'm just overlaying that with a test layer (the tiles with numbers, basically).  If you want imagery, you'll need to find an imagery source.  Mapbox provides a nice imagery layer, but not for free which is why it's not turned on in the example.

**Comment by Coder-iOS** [comment]
Sorry for asking so many questions but I really appreciate your help.

I hope you are talking about similar imagery that you are using for "Blue Marble Single Res" or "NASA GIBS" in your sample Apps, so for loading imagery locally do I need to find in pvrtc texture format or you are supporting some other formats also. Please help!

**Comment by mousebird** [comment]
The NASA GIBS imagery is probably jpeg (possibly PNG) from NASA's site.  I'm not sure if you're allowed to reuse that.  Blue Marble is probably too low resolution to overlay on that terrain. You could also use something like Digital Globe or Mapbox, but they cost money.

**Comment by Coder-iOS** [comment]
What you suggest if we want to load imagery in offline mode?

**Comment by mousebird** [comment]
People usually stuff that into an MBTiles file or put the individual tiles on the device.

**Comment by Coder-iOS** [comment]
Thank you for your prompt response. I will check for mbtiles then.

**Comment by Coder-iOS** [comment]
Hi Steve, 

Sorry to disturb you again. Actually I have used with mbtile but now globe is not visible, I have noticed that whenever I'm setting requireElev property of layer to true globe is not showing.

I am checking with Cesium terain example code in which I removed MaplyAnimationTestTileSource tile source and added mbtile layer only. Please let me know what I am doing wrong here.

**Comment by mousebird** [comment]
When you set requireElev the loader is going to require an elevation tile for every image tile it loads.  If the elevation tile is missing, then nothing will be visible.

As for Cesium elevation, that should load fine on its own, but you can't overlay regular TMS data sources in spherical mercator.  Those are the tiles you get from OpenStreetMap, Bing, Mapbox and so forth.
