### ISSUE TITLE
Exception thrown when trying to add Natural Earth road vectors shapefile

### ISSUE THREAD

**Issue by ACoyte** [mousebird/WhirlyGlobe#562]
I am getting an exception thrown as soon as I try to load the Natural Earth roads shapefile (zip attached).

It is very easy to reproduce this:

- Add files ne_10m_roads.shp, ne_10m_roads.shx and ne_10m_roads.dbf to project (included in attached zip file)
- Insert the following line of code
`MaplyVectorDatabase *vecDb = [[MaplyVectorDatabase alloc] initWithShape:@”ne_10m_roads”]`
- Add an exception breakpoint to your project

The following image shows the call stack when the exception is thrown

![wg-ne-vector-issue-call-stack](https://cloud.githubusercontent.com/assets/1835827/14845645/7d75f5a8-0c57-11e6-99d8-bf5506a26280.png)

It seems like it’s crashing when creating the SQLite cached database of the vector file.

This is reproduced using code from WhirlyGlobe_Maply_Distribution_2_4.

[ne_10m_roads.zip](https://github.com/mousebird/WhirlyGlobe/files/238200/ne_10m_roads.zip)

**Comment by mousebird** [comment]
Was a sanitized (or not) input problem.  Should be working again.

**Comment by ACoyte** [comment]
Thanks Steve! Is it possible to get a binary with these fixes?

 

Cheers

 

Andy C
