### ISSUE TITLE
Wide vectors on far side of planet showing through in WG 2.4

### ISSUE THREAD

**Issue by ACoyte** [mousebird/WhirlyGlobe#563]
I added a GeoJSON vector file (attached) and shamelessly ripped off your TestViewController function `addGeoJson:name`.

Normal vectors works perfectly.

Wide vectors shows the vectors on the other side of the planet behind as shown in the image below.

![wg-issue-2](https://cloud.githubusercontent.com/assets/1835827/14845843/ba8482a6-0c58-11e6-9473-06a78eead958.png)

This is reproduced using code from WhirlyGlobe_Maply_Distribution_2_4.

[ne_10m_roads-major-highway.zip](https://github.com/mousebird/WhirlyGlobe/files/238216/ne_10m_roads-major-highway.zip)

**Comment by mousebird** [comment]
Fixed.
