### ISSUE TITLE
WhirlyGlobeViewControllerDelegate didSelect methods not called

### ISSUE THREAD

**Issue by fontduroy** [mousebird/WhirlyGlobe#564]
Seeing this on iOS.

Although #479 is closed, I still can't select a MaplyVectorObject. I have the kMaplySelectable attribute set to true and explicitly set MaplyVectorObject.selectable to true before adding the vector (using either addVector or addWideVector). Also, explicitly set WhirlyGlobeViewController.selection to true.

The vector is displaying properly on the globe.

`
            MaplyCoordinate testCoords[5];
            testCoords[0] = MaplyCoordinateMakeWithDegrees(-100, 40);
            testCoords[1] = MaplyCoordinateMakeWithDegrees(-110, 40);
            testCoords[2] = MaplyCoordinateMakeWithDegrees(-110, 30);
            testCoords[3] = MaplyCoordinateMakeWithDegrees(-100, 30);
            testCoords[4] = MaplyCoordinateMakeWithDegrees(-100, 40);

```
        NSDictionary *testDesc = @{kMaplyColor: [UIColor redColor],
                                   kMaplyVecWidth: @(16.0),
                                   kMaplySelectable: @(true),
                                   kMaplyDrawPriority: @(1)};

        MaplyVectorObject* testVector = [[MaplyVectorObject alloc] initWithLineString:testCoords
                                                                            numCoords:5
                                                                           attributes:testDesc];
        testVector.selectable = true;

        mco = [self addWideVectors:@[testVector] desc:testDesc];
```

`

The following delegate methods are being called:
- (void)globeViewControllerDidTapOutside:(WhirlyGlobeViewController *)viewC 
- (void)globeViewController:(WhirlyGlobeViewController *)viewC didTapAt:(WGCoordinate)coord
- (void)globeViewControllerDidStartMoving:(WhirlyGlobeViewController *)viewC userMotion:(bool)userMotion
- (void)globeViewController:(WhirlyGlobeViewController *)viewC didStopMoving:(MaplyCoordinate *)corners userMotion:(bool)userMotion
- (void)globeViewController:(WhirlyGlobeViewController *)viewC didMove:(MaplyCoordinate *)corners

**Comment by mousebird** [comment]
That looks like it's creating a linear rather than areal.  Does this work better if you create an areal feature?  Try initWithAreal:

**Comment by mousebird** [comment]
I think linear selection is not fully supported.

**Comment by fontduroy** [comment]
Okay, thanks for the quick reply. Incidentally, I may be interested in helping implement that functionality if the opportunity is there (and my schedule allows).

**Comment by mousebird** [comment]
Actually, my mistake.  Jesse contributed this code a while ago, but it doesn't seem to always work.

The problems is you have to project the lines onto the screen to do it properly.  For some reason that's not always happening correctly.  The code is in MaplyVectorObject.mm pointNearLinear:

So it may not be all that difficult to find and fix the problem.

**Comment by mousebird** [comment]
If you change line 126 in WGInteractionLayer.mm to:
    NSArray *vecObjs = [self findVectorsInPoint:Point2f(msg.whereGeo.x(),msg.whereGeo.y()) inView:(MaplyBaseViewController*)self.viewController multi:false];

It might just work.  I'm at a conference at the moment, so I can't properly test this.

**Comment by mousebird** [comment]
The user made some further changes.  Let's look at these before 2.5.

//Fuzzy matching for selecting Linear features
- (bool)pointNearLinear:(MaplyCoordinate)coord distance:(float)maxDistance inViewController:(MaplyBaseViewController*)vc
{
    for (ShapeSet::iterator it = _shapes.begin();it != _shapes.end();++it)
    {
        VectorLinearRef linear = std::dynamic_pointer_cast<VectorLinear>(*it);
        if (linear)
        {
                CGPoint p = [vc screenPointFromGeo:coord];
                VectorRing pts = linear->pts;
                float distance;
                for (int ii=0;ii<pts.size()-1;ii++)
                {
                    distance = MAXFLOAT;
                    Point2f p0 = pts[ii];
                    MaplyCoordinate pc;
                    pc.x = p0.x();
                    pc.y = p0.y();
                    CGPoint a = [vc screenPointFromGeo:pc];

                    Point2f p1 = pts[ii + 1];
                    pc.x = p1.x();
                    pc.y = p1.y();
                    CGPoint b = [vc screenPointFromGeo:pc];
                    
                    CGPoint aToP = CGPointMake(a.x - p.x, a.y - p.y);
                    CGPoint aToB = CGPointMake(a.x - b.x, a.y - b.y);
                    double aToBMagitude = pow(hypot(aToB.x, aToB.y), 2);
                    double dot = aToP.x * aToB.x + aToP.y * aToB.y;
                    double d = dot/aToBMagitude;
                    
                    if(d < 0)
                    {
                        distance = hypot(p.x - a.x, p.y - a.y);
                    } else if(d > 1) {
                        distance = hypot(p.x - b.x, p.y - b.y);
                    } else {
                        distance = hypot(p.x - a.x + (aToB.x * d),
                                         p.y - a.y + (aToB.y * d));
                    }
                    
                    if (distance < maxDistance)
                        return true;
                }
        }
    }
    
    return false;
}
