### ISSUE TITLE
Exception in addSelectionVectors

### ISSUE THREAD

**Issue by fontduroy** [mousebird/WhirlyGlobe#565]
Calling addSelectionVectors is causing the following exception:

2016-05-03 10:18:08.430 [2106:1007150] -[__NSDictionary0 setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x145507190
2016-05-03 10:18:08.431 [2106:1007150] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionary0 setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x145507190'
*** First throw call stack:
(0x181596e38 0x180bfbf80 0x18159dccc 0x18159ac74 0x181498d1c 0x10016492c 0x100168cc4 0x10016ad7c 0x10017b274 0x1001169f8 0x1004dda7c 0x1004dda3c 0x1004ecc9c 0x1004ec364 0x1811f9470 0x1811f9020)
libc++abi.dylib: terminating with uncaught exception of type NSException

`MaplyCoordinate testCoords[5];
testCoords[0] = MaplyCoordinateMakeWithDegrees(-100, 40);
testCoords[1] = MaplyCoordinateMakeWithDegrees(-110, 40);
testCoords[2] = MaplyCoordinateMakeWithDegrees(-110, 30);
testCoords[3] = MaplyCoordinateMakeWithDegrees(-100, 30);
testCoords[4] = MaplyCoordinateMakeWithDegrees(-100, 40);
                        
MaplyVectorObject* selectionVector = [[MaplyVectorObject alloc] initWithLineString:testCoords
                                                                                numCoords:5
                                                                               attributes:nil];
            
selectableMco = [self addSelectionVectors:@[selectionVector]];`

Using the same coordinates for a regular vector rendered the vector on the globe.

**Comment by mousebird** [comment]
Fixed in 2.4.1.  Thanks for the fix!
