### ISSUE TITLE
Hosting vector tiles on the device

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#566]
For an offline map solution I am using MBTiles but the problem with it is that the file can get large.
So I am looking at vector tiles which I believe (please correct me if I am wrong) can only work remotely when hosted online in a server. If I can put a http server locally on the device, would WhirlyGlobe be able to behave normally if I host the vector tiles locally, like it is requesting from an online server? Also, if I am missing anything, is there any other solution for MBTiles that I can use for offline mapping? Thanks.

**Comment by mousebird** [comment]
You can put vector tiles in an MBTiles file.
