### ISSUE TITLE
MaplyRemoteTileInfo proxy causes corrupt cache

### ISSUE THREAD

**Issue by bryanheitman** [mousebird/WhirlyGlobe#568]
For users who temporarily connect to a proxy who provides invalid content to a remote tile source can cause the content to be saved to the cache under the 0_0_0.png which will forever cause content to not be requested from the valid tile source when a valid internet connection becomes available.

As a temporary work-around users should check for a corrupt 0_0_0 file upon adding a MaplyRemoteTileInfo source and/or limit the cache lifetime.

**Comment by mousebird** [comment]
If the image doesn't parse, it won't cache now.
