### ISSUE TITLE
[Android] GlobeView.pointOnSphereFromScreen NullPointerException

### ISSUE THREAD

**Issue by darenig** [mousebird/WhirlyGlobe#571]
When using the globe, calling animatePositionGeo(). geoPointFromScreen(), getCurrentViewGeo(), causes a NullPointerException.

It seems GlobeView.pointOnSphereFromScreen() always returns null, regardless of position on globe.

**Comment by mousebird** [comment]
Fixed, but getCurrentViewGeo() will now return null if it can't form a valid bounding box.
