### ISSUE TITLE
Wrong label position for some countries in the tutorial

### ISSUE THREAD

**Issue by jmnavarro** [mousebird/WhirlyGlobe#572]
Doing the [Screens Labels tutorial](http://mousebird.github.io/WhirlyGlobe/tutorial/screen_labels.html) for branch `develop_2_4_1`, some countries (United States and France) have wrong label position.

Notice the country vector and the label.

![simulator screen shot 18 may 2016 00 19 21](https://cloud.githubusercontent.com/assets/219908/15342014/89275c20-1c92-11e6-883d-357e5be7d6ac.png)

Debugging the values for the States, the country vector bounds are the following:

ll = (-3.110081, 0.330983)
ur = (3.137753, 1.246299)

And computed center is (0.0138358,0.788641) which seems reasonable.

However, the data in the GeoJSON files is quite different, in the range of (-160,20). Maybe the projection or the unit is different

**Comment by mmerickel** [comment]
I ran into this the other day. The tutorials recommend using the center of the vector. I started using the centroid instead because its docs say its good for label positioning and things looked fine. I didn't investigate much further than that.

**Comment by mousebird** [comment]
Oh, if it's average vs. centroid then you may get some funkiness with Alaska.  I'll take a look when I get a chance.  Centroid of the biggest loop is best except when it isn't.

**Comment by jmnavarro** [comment]
Yeah, I tested with `centroid()` and it's working fine. I agree with @mmerickel that centroid is more accurate for label positioning (the biggest loop is usually the main one). I'm gonna change the tutorial to recommend that.

However, something weird is happening with `center()`. AFAIK, the center is supposed to be the middle point of the bounding box of the polygon (correct me if I'm wrong), so for the States, if should be somewere in the Pacific ocean (considering Alaska and Hawai outliers). But currently is't being placed in France.

**Comment by mousebird** [comment]
Parts of Alaska may wrap across the +180/-180 boundary.  So the center of the bounding box is pretty bogus.  Just switch it to centroid.  Thanks!
