### ISSUE TITLE
Add Image on map

### ISSUE THREAD

**Issue by rohitnagori** [mousebird/WhirlyGlobe#573]
Hi,
I am using whirlyGlobe for my aviation app. I have to add airport diagram on map I have PNG and PDF both with me. How can I add or draw this on globe. I am attaching screen shot from another app which also using whirlyGlobe to show airport diagram on map.
Your help will be appreciable.  
Thanks.
![img_9598](https://cloud.githubusercontent.com/assets/5022126/15388395/68916aa8-1dcf-11e6-8912-969a323fb6c3.PNG)
![kphl](https://cloud.githubusercontent.com/assets/5022126/15388496/d4e9d2da-1dcf-11e6-9bda-960e7c5cd65f.gif)
![img_9599](https://cloud.githubusercontent.com/assets/5022126/15388537/f61fe228-1dcf-11e6-82e4-070830e3a9e9.PNG)

**Comment by rohitnagori** [comment]
In MKmap View of native ios, we can use rendererForOverlay method to draw image on map but in whirlyGlobe I have no clue. 
Please guide me with some idea.

**Comment by mousebird** [comment]
It's a little tricky and I forget exactly how they did it.
Do you know the position of the corners of the chart?  Is it rectangular in lat/lon?  If so, you could use a MaplySticker.

If it's not rectangular in lat/lon then you might need to do a bit of math, convert it to a MaplyMarker and give it a center and rotation.

Do I know about this app?  Would you like to be on the WhirlyGlobe-Maply apps page?

**Comment by rohitnagori** [comment]
Hi Steve, 
Thanks for your comment on this. I am having lower left and upper right coordinate with me. The image will be rectangular. I have started the app few more days before. It is in development phase right now and I would definitely like to be on whirlyGlobe-Maply till the development phase of app.

**Comment by rohitnagori** [comment]
Hi Steve,
Below are the values I am assigning to sticker, please see and tell me what wrong I am doing.As I can not see sticker.

     MaplySticker *sticker = [[MaplySticker alloc] init];
     sticker.ll =  MaplyCoordinateMake(72.8397, 20.4283);
     sticker.ur =  MaplyCoordinateMake(80.9462, 26.8467);
     sticker.rotation = (3.14/2);
     sticker.coordSys = tileSource.coordSys;
     sticker.image = [UIImage imageNamed:@"0A2_FLIGHTGUIDE"];
     sticker.imageFormat = MaplyImage4Layer8Bit;
    [globeController addStickers:[NSArray arrayWithObject:object] desc:@{kMaplyDrawPriority:@(kMaplyStickerDrawPriorityDefault)}];

**Comment by rohitnagori** [comment]
I think I found out what was preventing it to draw.
 sticker.coordSys = tileSource.coordSys;
the cordSys value was preventing it to draw.

**Comment by mousebird** [comment]
You shouldn't need a coordinate system if the extents are in geographic.

**Comment by NasH5169** [comment]
Hi all,

Sorry to answer a old thread, but just a related question: Is it possible with Android Maply SDK ? I didn't find the MaplySticker class.

Thanks.

**Comment by mousebird** [comment]
There's a Sticker class.
