### ISSUE TITLE
[Android] Error when building the SDK

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#574]
Hi there,
I pulled the last modification from the SDK but it seems I cannot build it.

I get the following error when running buildmaply.sh:
```
:buildNative
[x86] Compile++      : Maply <= Maply_jni.cpp
[x86] Compile++      : Maply <= AttrDictionary_jni.cpp
[x86] Compile++      : Maply <= AngleAxis_jni.cpp
[x86] Compile++      : Maply <= BaseInfo_jni.cpp
In file included from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/WhirlyGlobe.h:80:0,
                 from jni/Maply_jni.h:28,
                 from jni/Maply_jni.cpp:22:
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/TileQuadOfflineRenderer.h:208:10: error: 'mutex' in namespace 'std' does not name a type
     std::mutex mut;
          ^
In file included from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/WhirlyGlobe.h:80:0,
                 from jni/Maply_jni.h:28,
                 from jni/BaseInfo_jni.cpp:22:
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/TileQuadOfflineRenderer.h:208:10: error: 'mutex' in namespace 'std' does not name a type
     std::mutex mut;
          ^
In file included from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/WhirlyGlobe.h:80:0,
                 from jni/Maply_jni.h:28,
                 from jni/AttrDictionary_jni.cpp:22:
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/TileQuadOfflineRenderer.h:208:10: error: 'mutex' in namespace 'std' does not name a type
     std::mutex mut;
          ^
In file included from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/WhirlyGlobe.h:80:0,
                 from jni/Maply_jni.h:28,
                 from jni/AngleAxis_jni.cpp:22:
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/TileQuadOfflineRenderer.h:208:10: error: 'mutex' in namespace 'std' does not name a type
     std::mutex mut;
          ^
make: *** [obj/local/x86/objs/Maply/BaseInfo_jni.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [obj/local/x86/objs/Maply/Maply_jni.o] Error 1
make: *** [obj/local/x86/objs/Maply/AngleAxis_jni.o] Error 1
make: *** [obj/local/x86/objs/Maply/AttrDictionary_jni.o] Error 1
:buildNative FAILED

FAILURE: Build failed with an exception.
```

I have update the submodule so I do not think it coming from that.

I doubt it has an impact, but I am using build tools 24 rc4 (`buildToolsVersion "24 rc4"`).

I am pretty sure I have something wrong in my set up, but cannot figure out what.
Anyone else seeing this ?

JM

**Comment by mousebird** [comment]
Does this happen with any of the arm architectures?

**Comment by jmcazaux** [comment]
Mmmmm...

How can I test this? I just launched the build either from gradle (`./gradlew assembleRelease`) or with the provided build script un the tester project.

If there is anything you want me to try, please advise.

JM

PS : tried with build tools 23.0.2, no dice.

**Comment by mousebird** [comment]
I usually use the buildmaply.sh script.  Try "buildmaply.sh Debug armeabi-v7a"

**Comment by jmcazaux** [comment]
Same thing, and I have no more output.

JM

**Comment by mousebird** [comment]
std::mutex is a part of C++11.  I think people have seen this before, but the problem always goes away before I dig into it.

Did this just start happening?

**Comment by jmnavarro** [comment]
What NDK version are you using? I'm working with r10e and it's compiling fine.

If I remember well, I tried with a newer version and it failed (not sure if it failed with your error)

**Comment by jmcazaux** [comment]
I never looked too deep into these kind of things... I am on a Mac if it helps... XCode 7.3.1 (is it linked with cpp compiler ?). Android Studio 2.1.1 & Android NDK 12.

OMG have I upgraded the Android NDK too early ?

**Comment by mousebird** [comment]
I'll update to the latest Android Studio tomorrow and see if that pulls in NDK 12.

**Comment by jmcazaux** [comment]
This can be closed, it works with NDK 11c which is recent enough.

**Comment by mousebird** [comment]
Thanks!
