### ISSUE TITLE
Any Sample/Tutorial for Android?

### ISSUE THREAD

**Issue by pingothedoer** [mousebird/WhirlyGlobe#584]
Hi, i have searched , but couldn't find anything useful that could lead me towards any sample or tutorial how can i use whirlyGlobe in my project. Kindly guide me towards proper way. The tutorial mentioned on web is only for IOS.

**Comment by gulfam-powerfulpal** [comment]
Hi, I am also looking for same, no tutorial or help available for Android. Can you please guide us, how to develop a sample application for Android.

**Comment by mousebird** [comment]
There is currently no tutorial for Android.  We'd love to develop one, but we need more support customers to pay for it.

For now, there is the AndroidAutoTester.  It's a collection of test cases that implement specific functionality.  It provides good examples.

**Comment by gulfam-powerfulpal** [comment]
Thanks for your reply. I am trying to compile AutoTesterAndroid and facing an issue. The error is mentioned below, can you please help me regarding this?

Error:A problem was found with the configuration of task ':app:prepareAutoTesterAndroidMaplyUnspecifiedLibrary'.
> File 'D:\AndroidStudio\Workspace\AutoTesterAndroid\Maply\Maply.aar' specified for property 'bundle' does not exist.

It does not have Maply.aar file. How can I add that file to successfully compile this code.

**Comment by jmnavarro** [comment]
You need to compile the Maply library yourself.

For OSX you have a bash script (buildmaply.sh). You can do the same steps in Windows (just clean directories, launch gradle and copy the output)

**Comment by mousebird** [comment]
There are now [Android tutorials](http://mousebird.github.io/WhirlyGlobe/tutorial/android/getting-started.html)!
