### ISSUE TITLE
[Android] Crash when calling BaseController.dispose()

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#585]
I thought it was necessary to call shutdown and dispose on the GlobeController when quitting the activity.

It did not like "dispose()" at all and was crashing.
If it should not be called, it should be documented and possibly removed from the public interface.

**Comment by mousebird** [comment]
shutdown() yes, but not dispose().  The first shuts down the the rendering and all related threads.  The second actually deletes the C++ objects.

dispose() is part of the JNI setup and I don't think I can hide it.  You should never call it directly.

**Comment by mousebird** [comment]
Note to myself:  Put a comment on dispose and see if we can hide it.

**Comment by mousebird** [comment]
Turns out I can hide it.
