### ISSUE TITLE
[Android] Application stalls when calling baseController.shutdown() in a fragment

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#586]
When the GlobeController has been created in a fragment and calling controller.shutdown() (fragment.onDetach or fragment.onDestroy) the application stalls.
The screen turns back and nothing happens (bar ANR alerts).

**Comment by mousebird** [comment]
Can you try this one again?  I've cleaned up a lot of the shutdown code.
Just reopen if it's still broken.
