### ISSUE TITLE
[Android] ScreenLabel textSize not consistent with ScreenMarker size

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#587]
It seems that there is some confusion in units when setting ScreenLabel textSize and ScreenMarker size.

Here is a screen grab showing a Marker of size 32x32 (it is actually 32x32 pixels) and a text with textSize 24px which seems to be at best 12px -caps are 10px, we can assume 2px descent).

![textsize issue](https://cloud.githubusercontent.com/assets/2640502/15632375/6a734054-258f-11e6-83c9-490169381c31.png)

It could that some DIP-to-PX conversion was applied (but then the wrong way ?).
At least it is not a consistent unit with the ScreenMarker size.

All sizes should be in the same unit (on Android you can chose DIP or pixels).

**Comment by mousebird** [comment]
It was scaling things by 0.5.  See if it looks right now.

Also let me know if the fonts look reasonable.  I think I was scaling the bitmaps up to make them look better.
