### ISSUE TITLE
Previous tiles still showing

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#589]
I am using MBTiles for different layers in my globe. In the image below, i have a base layer which is basically a raster MBTile and I also have another layer which is the names of the countries. For some tiles, the previous tiles are still showing, like for example in Djibouti when I zoom in, it is still showing the previous tile for it. Is there a way to just load or show the current tiles for a zoom level so I avoid the image from the previous tiles?

![djibouti](https://cloud.githubusercontent.com/assets/14211746/15633850/01743c64-25c8-11e6-9696-1c16bbf0c8f9.png)

**Comment by mousebird** [comment]
Is this a 3D globe or 2D Map?

**Comment by jerald-acacus** [comment]
It's a 3D globe.

**Comment by mousebird** [comment]
A movie might help me understand exactly what's going on.  However, it's probably working as designed.

For the globe, you can have multiple resolutions visible at the same time.  It's designed for continuous surfaces and not things like labels.

In 2D you can specify a single level to display, but that mode hasn't been ported to 3D.

**Comment by jerald-acacus** [comment]
Yes it does seem like having an MBTile for labels is not a good idea. As for now, I combined my base layer and my labels layer as a work around. But I need something to put above my base layer and below the labels layer, so I might be looking at using a MaplyScreenLabel.

Just a quick question regarding MaplyScreenLabel in 3D, is it really just flat or can it wrap around the surface of the globe to project an arced label rather than just a straight label on top of the globe?

**Comment by mousebird** [comment]
There are two options.  MaplyScreenLabel is 2D and will not wrap around.  The MaplyLabel is 3D and will wrap around the globe.
