### ISSUE TITLE
[Android] VectorInfo lineWidth not consistent / not working.

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#590]
VectorInfor.setLineWidth seems to act strangely.

It seems it has an effect, but only to a certain point.

![lw_1](https://cloud.githubusercontent.com/assets/2640502/15648203/3cae2f50-2669-11e6-9f09-b7fbb64e4166.png)
On the example above, bullets are 26x26px, lineWidth is 4px.

![lw_2](https://cloud.githubusercontent.com/assets/2640502/15648211/496bea02-2669-11e6-8ebb-9858b695bfcc.png)
Here bullets are still 26x26px, lineWidth should be 20 (it does not look like it is).

![lw_3](https://cloud.githubusercontent.com/assets/2640502/15648217/501a104a-2669-11e6-8cb8-20e96c11f787.png)
Last, still the same bullets with a line width of 100 (it obviously is not).

I cannot really analyse, but setLineWidth does not behave as expected.

**Comment by mousebird** [comment]
For a regular line width, using OpenGL's line renderer, there's a maximum.
I can't say for sure that it's showing you the maximum, but there definitely is one.

**Comment by jmcazaux** [comment]
Ouch, that would be disapointing.

**Comment by mousebird** [comment]
You'd need to switch to Wide Vectors, but we haven't hooked those up on Android.

**Comment by mousebird** [comment]
Duplicate feature request.
