### ISSUE TITLE
[Android] drawPriority ignored

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#591]
It seems that BaseInfo.drawPriority is ignored or at least, I have not been able to make it work.

![p](https://cloud.githubusercontent.com/assets/2640502/15648594/cde538c2-266b-11e6-9374-5288e2baeafa.png)

In the above, the plane (marker) has a drawPriority of 1000, bullets (marker) have a draw priority of 1000 and the line (vector) has as well a priority of 1000. It is to note that the line starts below the plane (center line of the wings).

I have the exact same result when setting the draw priority of the bullets to 900 and the one of the line to 1100 or the priority of the bullets to 1100 and the one of the line to 900.

**Comment by mousebird** [comment]
I think you have full control over drawPriority now for both ScreenMarkers and ScreenLabels and the defaults are somewhat coherent as well.

Just reopen if it's still a problem.
