### ISSUE TITLE
[Android] Vector line joint

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#592]
Here is a shape drawn with vectors (ignore the blurry background, WIP).

![line_j](https://cloud.githubusercontent.com/assets/2640502/15667775/496220b2-2718-11e6-82a3-66fdf66edbec.png)

Is it possible to have better looking line joint ?
I have not found a way to specify it in the SDK.

**Comment by mousebird** [comment]
Another one for Wide Vectors.

**Comment by mousebird** [comment]
Duplicate feature request.
