### ISSUE TITLE
[Android] How to enable anti-aliasing ?

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#593]
Here is an enlarged (200%) shot of a vector line.

![aa](https://cloud.githubusercontent.com/assets/2640502/15667874/c7758a98-2718-11e6-97e3-b73e13b5b661.png)

A bit of anti aliasing would be great, but I have not found how to enable it.

Thanks.

**Comment by mousebird** [comment]
Wide Vectors again.  It does a nice transparent blending at the edges of the "lines" (they're really polygons).

**Comment by jmcazaux** [comment]
I cannot find WideVectors in the iOS doc. Is it there http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/index.html ?

**Comment by mousebird** [comment]
http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/MaplyBaseViewController.html#//api/name/addWideVectors:desc:mode:

**Comment by mousebird** [comment]
The WideVector implementation has been ported at the C++ level, so that's good.  But the control logic to Java has not been implemented.

**Comment by jmcazaux** [comment]
What I meant is that it does not seem to be in the iOS kit either.

**Comment by mousebird** [comment]
But it is.  Look for addWideVectors: in the iOS version.  It's been in there for a while, but it's much better in 2.4.1.

**Comment by jmcazaux** [comment]
Did not look in the right place indeed.
This would be perfect on the Android side ;)

**Comment by mousebird** [comment]
Yes.  The internals are ported, but not hooked up.  Let's get through the current round of changes and then discuss it.
