### ISSUE TITLE
MaplyVectorTileSubStyleMarker always gets fillColor and strokeColor set, even if not requested

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#596]

**Comment by mousebird** [comment]
I see fillColor getting whiteColor by default and then if strike isn't filled in it gets blackColor if the fillColor is set.

What would you like it to default to?

**Comment by JesseCrocker** [comment]
Fill gets set to white by default at https://github.com/mousebird/WhirlyGlobe/blob/develop_2_4_1/WhirlyGlobeSrc/WhirlyGlobe-MaplyComponent/src/vector_tiles/MaplyVectorTileMarkerStyle.mm#L60

Then later on stroke gets set to black if fill is set but stroke isn't https://github.com/mousebird/WhirlyGlobe/blob/develop_2_4_1/WhirlyGlobeSrc/WhirlyGlobe-MaplyComponent/src/vector_tiles/MaplyVectorTileMarkerStyle.mm#L79

So no matter what the input is, fill and stroke will always be set, so it's not possible to have an icon thats just an icon.

**Comment by mousebird** [comment]
That all gets passed in to the icon manager.  So presumably if we take out those defaults we'll get a pure icon.  Is that what you'd like?

**Comment by JesseCrocker** [comment]
Fixed by #597
