### ISSUE TITLE
[Android] MapDelegate.userDidTap gives wrong geo coordinates (as userDidLongPress now)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#602]
When testing the newly added userDidLongPress, I realized that the returned geo coordinates where wrong.

I was testing for [Montpellier Airport (France)](https://goo.gl/maps/At8MKdTR51t) which is lat = 43.578748, lon = 3.9592936.
MapDelegate.userDidTap (AutoTester) finds it at x = 0.722679337, y = 0.050120679 (radians) or in degrees lat = 2.871703376, lon = 41.40647597...

When testing with a place everyone can locate (New York's Statue of Liberty), I had results that are massively off off as well.
In radians x = 0.208473245, y = -0.728918484
Layman friendly lat = -41.76395276, lon = 11.94463707.

Can it be linked to #601 ?

Many thanks,
JM

**Comment by mousebird** [comment]
Should be fixed now for both globe and map.
