### ISSUE TITLE
Glyphs occasionally missing from vector tile labels

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#605]
Both of these screenshots were taken immediately after app launch, so there shouldn't be any difference in state.

## What it should look like
![screen shot 2016-06-07 at 8 59 07 am](https://cloud.githubusercontent.com/assets/2048291/15862887/55c1bb94-2c8e-11e6-9705-1774e35cedc0.png)

## Every once in a while this happens
![screen shot 2016-06-07 at 8 58 32 am](https://cloud.githubusercontent.com/assets/2048291/15862905/6d57a796-2c8e-11e6-9ae6-d1db2523a7d4.png)

**Comment by JesseCrocker** [comment]
It's not the same glyphs missing every time

**Comment by mousebird** [comment]
I've seen this very, very, very sporadically but I've never had a test case reliable enough to address it.

Do you have one or is this really sporadic?

**Comment by JesseCrocker** [comment]
I dont have a simplified test case, but i've got a saved app state where this happens ~ 1/4 times on launch.

If you want to clone the repo and build i can send you the data to drop into the simulator to reproduce.

**Comment by mousebird** [comment]
Can you experiment for me a little?

Can you try turning off everything but the map layer with the labels and then everything but the labels?

**Comment by JesseCrocker** [comment]
Rendering just one layer still causes the problem

![screen shot 2016-06-07 at 10 41 52 am](https://cloud.githubusercontent.com/assets/2048291/15866581/82213e5e-2c9c-11e6-93b3-e0d6c8fbcbcd.png)

Mapnik xml that is rendering this:
```
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE Map []><Map font-directory="./fonts" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">

<Parameters>
  <Parameter name="attribution"><![CDATA[Map data © OpenStreetMap contributors]]></Parameter>
  <Parameter name="bounds">-180,-85.0511,180,85.0511</Parameter>
  <Parameter name="center">-119.4835,37.8042,12</Parameter>
  <Parameter name="format">png8:m=h</Parameter>
  <Parameter name="maxzoom">22</Parameter>
  <Parameter name="minzoom">0</Parameter>
  <Parameter name="bufferSize">256</Parameter>
  <Parameter name="name"><![CDATA[topo map gaia tiles]]></Parameter>
  <Parameter name="metatile">1</Parameter>
</Parameters>

<FontSet name="fontset-0">
  <Font face-name="Open Sans Bold"/>
  <Font face-name="Open Sans Regular"/>
</FontSet>
<FontSet name="fontset-1">
  <Font face-name="Open Sans Regular"/>
  <Font face-name="Open Sans Regular"/>
</FontSet>
<Style filter-mode="first" name="land">
  <Rule>
    <PolygonSymbolizer fill="#fefdf5"/>
  </Rule>
</Style>
<Layer name="land">
    <StyleName>land</StyleName>  </Layer>

<Style filter-mode="first" name="natural_poi">
  <Rule>
    <Filter>([type] = 'cave_entrance')</Filter>
    <MarkersSymbolizer file="cave-halo-20x20@2x.png" fill="#000000" height="20" width="20"/>
    <TextSymbolizer character-spacing="1" dx="5" fill="#000000" fontset-name="fontset-0" halo-fill="#ffffff" halo-radius="2" justify-alignment="center" placement="point" placement-type="simple" placements="W,E" size="10" wrap-before="true" wrap-width="60"><![CDATA[[name]]]></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>([type] = 'peak')</Filter>
    <MarkersSymbolizer file="triangle-stroked-15-8x8@2x.png" fill="#000000" height="8" width="8"/>
    <TextSymbolizer allow-overlap="false" character-spacing="1" dx="6" dy="0" fill="#000000" fontset-name="fontset-0" halo-fill="#ffffff" halo-radius="2" justify-alignment="center" placement="point" placement-type="simple" placements="W,E" size="10" wrap-before="true" wrap-width="60"><![CDATA[[name]+'\n '+[ele_meters]]]></TextSymbolizer>
  </Rule>
  <Rule>
    <MarkersSymbolizer fill="#000000" height="3" width="3"/>
    <TextSymbolizer character-spacing="1" dx="5" fill="#000000" fontset-name="fontset-0" halo-fill="#ffffff" halo-radius="2" justify-alignment="center" placement="point" placement-type="simple" placements="W,E" size="10" wrap-before="true" wrap-width="60"><![CDATA[[name]]]></TextSymbolizer>
  </Rule>
</Style>
<Layer name="natural_poi">
    <StyleName>natural_poi</StyleName>  </Layer>
</Map>
```

**Comment by JesseCrocker** [comment]
Rendering all layers except that label layer
![screen shot 2016-06-07 at 10 51 10 am](https://cloud.githubusercontent.com/assets/2048291/15866879/cac65a1c-2c9d-11e6-9939-45dc5a6e758f.png)

**Comment by mousebird** [comment]
It's great you can reproduce this.

One more thing to try.  Somewhere in the loader you'll see a QuadPagingLayer with numSimultaneousLoads set to some number.  Set it to 1 and see if the problem persists.

I've always thought this might be a threading problem.

**Comment by JesseCrocker** [comment]
Setting `pagingLayer.numSimultaneousFetches = 1;` fixes it. I was using a value of 4. Still happens at 2.

**Comment by mousebird** [comment]
Great!  So it's definitely a threading issue.  You're on develop_2_4_1, right?

**Comment by JesseCrocker** [comment]
yeah, all this testing was on develop_2_4_1

**Comment by JesseCrocker** [comment]
@mousebird Any idea when you might fix this one?

**Comment by mousebird** [comment]
Hopefully next week.  Got a bunch of support stuff to work through.

**Comment by mousebird** [comment]
Does this ever happen after startup?
That is, do you only see it right after the map is loaded and/or the app is started?

**Comment by mousebird** [comment]
And can you send me an endpoint for the vector tiles?  Obviously not in the github issue.

**Comment by JesseCrocker** [comment]
Only happens right at startup

**Comment by JesseCrocker** [comment]
https://vectortilerendering.gaiagps.com/feet/{z}/{x}/{y}.pbf

**Comment by JesseCrocker** [comment]
Mapnik style sheet http://static.gaiagps.com/gaia-styles/gaia_topo.tm2z

**Comment by mousebird** [comment]
While I'm setting up this case, do you want to try a shot in the dark?
In DynamicTextureatlas.mm right after line 433 do a "glFlush()"

**Comment by mousebird** [comment]
What's the location of that screenshot?

**Comment by mousebird** [comment]
Though I did turn up another problem related to the layout manager, I haven't been able to duplicate this one, even with your own endpoint.

This is turning up on hardware, right?  Any particular hardware?

**Comment by jmcazaux** [comment]
I do have this as well, quite a lot actually.

Happens on my Nexus 9 randomly when moving, zooming ,etc.
I do not remember seeing it as much on my phone, but I use is lot less for tests as well.

Is the "shot in the dark" proposed above still current because line 433 in current DynamicTextureatlas.mm an if statement (`if (dynTexVec->at(0)->findRegion(numCellX, numCellY, thisRegion))`) immediately followed by an opening bracket so the file has probably changed.

**Comment by mousebird** [comment]
The code differs between Android and iOS.

You're seeing this on Android?  That's interesting.  Can you put together an example in the AutoTester?

**Comment by jmcazaux** [comment]
I'll create a separate issue then.

But I am fairly sure it happens out of the box with the ScreenLabels test case...
Will double check though.

**Comment by mousebird** [comment]
I believe the screen labels test has a visibility range so you won't see
them until you zoom in.

**Comment by JesseCrocker** [comment]
Seems to be working now.

**Comment by mousebird** [comment]
I haven't pushed that change because I was waiting for feedback.  Is it working with the glFlush()?

**Comment by JesseCrocker** [comment]
I didnt make any changes other than pulling develop_2_4_1 and now it's working. I give up.

**Comment by mousebird** [comment]
Huh.  Well I'm sure it won't come back to haunt me.
