### ISSUE TITLE
[Android] Array based function for geoPointFromScreen and screenPointFromGeo

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#606]
Calls to geoPointFromScreen and screenPointFromGeo seem to be pretty costly (wild guess 1/4th to 1/3rd of a millisecond per call on my Nexus 9).
When ones need to do a lot of conversions, maybe an array based function would be more efficient.

To really nail it, it could even be based on an array of doubles ([x1,y1, x2, y2...] for pt 1 , pt 2), this way it would not need to instantiate Point2ds for each result.
Agreed this is a bit less clean, but if it is more efficient it is not a massive price to pay.

**Comment by mousebird** [comment]
Should be there now.

**Comment by jmcazaux** [comment]
Actually, we are using the Map.
Those are only on the globe (I tried to copy the code over to the map, but it failed)...

**Comment by mousebird** [comment]
Should work in the map now.
