### ISSUE TITLE
[Android] AttrDictionary are hard to see thru

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#607]
Well, strange way to phrase this, buh when dealing with AttrDictionary from the SDK, we have no way to see what they contain (you have to know it upfront).

A getKeys (or key enumerator) ala HashMap would help debugging.

**Comment by mousebird** [comment]
José, let's add a couple of methods to the AttrDictionary.  One is just description() that dumps the whole thing in a string.

For the others, how about we return an array of keys and an array of values?  That should let us  iterate reasonably well.  Doing a full enumeration interface is more work than I feel like.

**Comment by jmnavarro** [comment]
Fixed on https://github.com/mousebird/WhirlyGlobe/tree/issue/607
