### ISSUE TITLE
Re-add objects to MaplyViewController

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#612]
I am currently using a globe with an option to switch to a map and back. I adding vectors to my MaplyBaseViewController and keep track of them through an array. When I switch to a map I want to also make these vectors appear on the map like how they were in the globe.

Is there any method to add a MaplyComponentObject to a MaplyBaseViewController so I dont have to recreate my objects and just re-use them whenever I switch to a WhirlyGlobeViewController or a FlatMapViewController? Or at least get the MaplyVectorObject from the MaplyComponentObject so I don't have to recreate them again?

**Comment by mousebird** [comment]
No, I'm afraid not.  The internal representations can be very different.
Moreover, we don't always keep track of the MaplyVectorObjects if you're not doing selection.

You'll have to re-add them to each controller.  However, if there's something expensive you're doing, like tesselating areal features, you could do that ahead of time.
