### ISSUE TITLE
[Android] color shit for areals in VectorStyles

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#622]
I have started implementing some vector styles and I have a strange behaviour when using areals.

Colors are darkened.

Linears display correctly, clear color display correctly, but areals are much darker than expected.

Here is an example:

![maply colors issue](https://cloud.githubusercontent.com/assets/2640502/16156077/ab8ae254-34b2-11e6-8735-e8b69213a171.png)

My code just uses the vector info to add the component:
```
private ComponentObject[] buildObjects(List<VectorObject> vectors, MaplyTileID maplyTileID, MaplyBaseController controller) {

        long start = System.currentTimeMillis();

        VectorInfo vecInfo = new VectorInfo();
        vecInfo.setColor(this.color);
        vecInfo.setFilled(true);
        vecInfo.setDrawPriority(this.drawPriority);
        vecInfo.setEnable(true);
        ComponentObject component = controller.addVectors(vectors, vecInfo, MaplyBaseController.ThreadMode.ThreadCurrent);

        return component != null ? new ComponentObject[]{component} : null;

    }
```

**Comment by mousebird** [comment]
Are you using any alpha?

**Comment by jmcazaux** [comment]
Nope, they are no alpha colors.

Le ven. 17 juin 2016 19:18, Steve Gifford <notifications@github.com> a
écrit :

**Comment by mousebird** [comment]
Are you using the globe or the map?
If it's the globe it could be lighting.

**Comment by jmcazaux** [comment]
This issue exhibits on the map.
There are color differences on they globe, but they are indeed due to lighting.

**Comment by mousebird** [comment]
Was a lighting problem.  Lights turned off for the map again.
