### ISSUE TITLE
Include MapBox tiles in my IOS application

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#623]
Hi guys,

I am trying to use MapBox tiles for my map. I downloaded their API, got a token, did everything I was told to do according to their website.

I don't find the good structure for the URL that I have to input when I use this instruction:

MaplyRemoteTileSource *tileSource =
    [[MaplyRemoteTileSource alloc]
     initWithBaseURL:@"'https://api.mapbox.com/styles/v1/mapbox/streets-v9/tiles/{z}/{x}/{y}?access_token=pk.eyJ1Ijoic2ViYm91bG5vaXMiLC[...]"
     ext:@"png" minZoom:0 maxZoom:18];

Could someone help me please? 

Thank a lot,

Sebastien.

**Comment by mousebird** [comment]
Seems like that should work, but the token looks wrong.  Which is just as well as you probably don't want to paste your token in here.

A RemoteTileSource can take a substitution URL like that.  To make sure it's right, form the URL with a tile 0/0/0 in your web browser and make sure it works.  That's what I usually do.

**Comment by amirfl** [comment]
I had a similar issue and solved it by simply changing the extension to @"jpg"
