### ISSUE TITLE
[Android] MapController.GestureDelegate is incomplete

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#626]
It seems that MapController.GestureDelegate is GlobeController.GestureDelegate poor cousin.

It misses the `mapDidStartMoving`, `mapdDidMove` & `mapDidStopMoving`.

_I'll try to have a go at this, should not be massively complicated to replicate what is done for globe._

**Comment by mousebird** [comment]
Should all be there now.
