### ISSUE TITLE
Minimum app size with WG-Maply library?

### ISSUE THREAD

**Issue by drhaynes** [mousebird/WhirlyGlobe#628]
Hi, I've noticed that the built WG-Maply library is fairly large - several hundred mb for a fat binary on iOS.

However, other apps that use the library appear to be much smaller than this - Dark Sky for example is only ~15mb when downloaded from the App Store.

Can you advise/comment on how this reduction in size was achieved?

Many thanks.

**Comment by mousebird** [comment]
The lib has a lot of extra information.  Symbols, for instance, even in Release.  There's probably also the simulator version in there too, depending on how you built it.

That's all stripped out when you build the app bundle.  Dark Sky isn't doing anything special.

**Comment by drhaynes** [comment]
Thanks
