### ISSUE TITLE
[Android] LabelInfo LayoutPlacement constants are shifted

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#632]
... or mixed up, or whatever but:
- when using LabelInfo.LayoutCenter the result is actually LabelInfo.LayoutRight
- when using LabelInfo.LayoutRight the result is actually LayoutAbove

These are just to examples that I use, but I assume the others are shifted as well.

**Comment by mousebird** [comment]
Also a problem with the layout offsets.  Fixed.
