### ISSUE TITLE
[Android] Vector draw priorities are confused when using more than 1 layer

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#633]
When using one vector layer, my map draws with the priorities I have defined.

When using more than one layer, I encounter 2 different issues:

**The priorities in each layer are ignoring the ones of other layers.**
For example I have layer A with an aeral of priority 1000 and lines of priority 2000.
In layer B I have an aeral of priority 3000 and lines of priority 4000.
I should never see the lines of layer A, but I do.

**The priorities in each layer are completely confused**
Still with the example above, it happens that I see the aeral in layer B, but **not** the lines in layer **B**.

**Comment by mousebird** [comment]
I don't have this exact case to test, but I did modify the simple style generator to put the lines below the areals and it worked.

Layers aren't carried down to the renderer as a concept, so the drawPriority you assign should be the one that's used.  Lines aren't being intentionally sorted after areals so it's not that.

**Comment by jmcazaux** [comment]
Cock up was in my own code.... Sorry about the confusion.
