### ISSUE TITLE
[Android] setClearColor randomly ignored

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#634]
When initializing my controller (in PostSurfaceRunnable) I set the clearColor.

this is randomly ignored and the beckground remains black (this is on the map). I cannot say if it happens on the globe as well.

**Comment by mousebird** [comment]
Rather than calling setClearColor, try passing in the clear color via the Settings when you create the controller.

**Comment by jmcazaux** [comment]
I'll try that, but it requires changing a bit my code (as the settings are passed in the constructor).

**Comment by mousebird** [comment]
I think this is now resolved.  Let me know if it isn't.
