### ISSUE TITLE
Questions about Marker Clustering

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#635]
First of all thanks for the feature. I have a few questions regarding the Marker Clustering.

What does kMaplyClusterGroup exactly corresponds to?

Also, when selecting a clustered group, say for example I tap a cluster of 3 markers, it returns the userObject of one of the markers inside that cluster. Is it possible to handle selection of marker clusters it self? Or atleast get the distance that groups these markers into cluster upon tapping on a cluster number.

**Comment by mousebird** [comment]
kMaplyClusterGroup is just a number.  By default there's a cluster group 0 in effect.  So if you want to turn on clustering, just add kMaplyClusterGroup: @(0) to your description.

To get the full information about what a user selected back take a look at the [allSelect:](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Protocols/WhirlyGlobeViewControllerDelegate.html#//api/name/globeViewController:allSelect:atLoc:onScreen:) variant of the WhirlyGlobeViewControllerDelegate protocol.

**Comment by jerald-acacus** [comment]
Hi. Another question regarding cluster groups. Can I modify the minimum distance between markers to include them in a cluster?

**Comment by mousebird** [comment]
The clustering decision is based on the layout size.  So you could change the layoutSize of your individual MaplyScreenMarkers.

**Comment by Spotunes** [comment]
How can we apply clustering for markers of type MaplyMarker?

**Comment by mousebird** [comment]
Clustering only works for screen objects like ScreenLabel or ScreenMarker.  They go through their own sorting and consolidation subsystem that 3D objects like markers do not.

It would be interesting to add that sort of thing.  I've also contemplated adding dead areas on the screen to the layout engine (for things like HUD).  That would be a significant amount of work, though.
