### ISSUE TITLE
Manual tilt

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#636]
Hi Guys,

I was wondering if we could simulate a manual tilt in WhirlyGlobe. The auto tilt feature is great but I would like to be able to tilt the view, whatever the height where I am. 

Best,

Sebastien.

**Comment by mousebird** [comment]
Sure, just set the tilt property.  Tilt is also part of the view state for animation.
There's also a tiltGesture that can be turned on for manual tilt.
