### ISSUE TITLE
MaplyGeomModel issue

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#637]
Hi Guys,

I have some problems with instantiating my aircraft model.
Here is the code:

![codetodisplay3dmodel](https://cloud.githubusercontent.com/assets/15698398/16500640/7dd98592-3ed3-11e6-8eae-a580df0f95a5.png)

I followed the example provided in WhirlyGlobe Component Tester. It compiles but my object aircraftModel is associated with nil value even if the path is correct:

![parametersresult](https://cloud.githubusercontent.com/assets/15698398/16500807/318cc90a-3ed4-11e6-9e51-f4c112013c42.png)

Do you guys have any idea about that?

Best,

Sebastien.

**Comment by mousebird** [comment]
Sounds like the OBJ parser is failing.  Which is not hugely surprising.  OBJ has some variants and the parser probably doesn't support them all.

The OBJ parser may be spitting out some errors in the log.  If not you'll have to step into it and see what it doesn't like.

**Comment by Sebboulnois** [comment]
Would you have any advices regarding the OBJ standards that are supported by the OBJ parser?

**Comment by mousebird** [comment]
You'll need to step into the OBJ parser to see what's going on, I'm afraid.

**Comment by Sebboulnois** [comment]
Where can I find this parser? Is it located in your framework or is it part of IOS?

**Comment by mousebird** [comment]
The OBJ reader is in the toolkit.  You'd need to step in to initWithObj:

Do you have a support contract?  This is the sort of thing I do for support customers.

**Comment by Sebboulnois** [comment]
Unfortunately, I don't have one. I hope I will have one next year if I get a grant for my Ph.D.

**Comment by Sebboulnois** [comment]
In the meantime, would you have any obj model of an aircraft to share with me please?

**Comment by mousebird** [comment]
I have a soft spot for research.  Can you send me your plane model?

**Comment by mousebird** [comment]
Was there a material file with that?
It's referencing a "texture" material, but there's no material file.

**Comment by Sebboulnois** [comment]
No, the folder I sent you is all I got for the obj extension. I also got a .dae folder and .3ds folder.

**Comment by mousebird** [comment]
The OBJ is invalid or it's using some weird shorthand that it shouldn't.

To fix it, you'll need to create a .mtl file and add a mtllib statement.
That mtl file should contain entries for all your materials.  Basically everything that is referenced in a usemtl line.

[Here's a simple version](https://people.cs.clemson.edu/~dhouse/courses/405/docs/brief-obj-file-format.html) of the spec.

**Comment by Sebboulnois** [comment]
Hi,

Thank you for this information and thank you for having looked at it. I will try to add this mtl file a bit later. In the meantime, I succeeded to retrieve a Boeing model that embeds this file and it works!

I only have two issues:

1) Whatever the height I set for the instantiation of the model (setCenter), it stays on the ground. 

2) I am synchronizing my lab Boeing 737 simulator with the model that I instantiate in WhirlyGlobe. I am getting the GPS position (longitude, latitude, altitude), pitch and bank in real time. How could I set these parameters so the model is affected in real-time? So far, I just saw that we could init MaplyMatrix with angles and pitches but not set them.

Best,

Sebastien.

**Comment by mousebird** [comment]
You might need to add the height in the matrix.

To make the model move, just remove and then add the new model instance.  You can do this with MaplyThreadCurrent to make it happen immediately and avoid any flashing.  Instances are simple enough that it takes no real time to set them up.

**Comment by Sebboulnois** [comment]
Thank you for this information.

I have another question. The instantiation of the models takes forever when I run the application (around 15 seconds). I am assuming it takes some time to parse the .obj, but is this normal for loading this kind of model?

**Comment by mousebird** [comment]
Is this in Release or Debug?

**Comment by Sebboulnois** [comment]
Both. The model takes one minute to load.

**Comment by mousebird** [comment]
Is this the Boeing model that's 1.3MB in size?

**Comment by Sebboulnois** [comment]
No. The one I am using now is 11MB.

**Comment by mousebird** [comment]
Eh, parsing 11MB of text can be a bit slow.
I'm sure this could be sped up, but it would take some work.

**Comment by Sebboulnois** [comment]
That's what I thought. I might be able to find another one smaller.
