### ISSUE TITLE
Can I use "develop_2_4_1" by CocoaPod?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#638]
Hi,
     I found main branch is 2.4 version,How can I use "develop_2_4_1" by CocoaPod?

**Comment by jmnavarro** [comment]
Sure thing.

You can add the pod file as follows:

`pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe', :branch => 'develop_2_4_1'`

**Comment by marychenyuan** [comment]
Thanks!

but... when I use the that line code , error follows:
![030804f7-8553-4a9c-a887-8e94c31c39d2](https://cloud.githubusercontent.com/assets/13251217/16571269/49fe6ef2-428b-11e6-814a-12d97160d3de.png)

What should i do...

**Comment by marychenyuan** [comment]
Sorry, I use "pod update" fix upper bug. but...   another error appear:
![4f60cec2-84e2-408b-a45a-e4a4facff488](https://cloud.githubusercontent.com/assets/13251217/16571406/123c65ac-428e-11e6-9498-98f7012a80ca.png)

**Comment by jmnavarro** [comment]
I tried with the following `Podfile` and it worked fine

```
target :TEST do
	pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe', :branch => 'develop_2_4_1'
end
```

Remember that you need a pretty decent connection. Dependencies are quite heavy. According your log it seems you're having connectivity problems

**Comment by marychenyuan** [comment]
Thanks, I tried many times... then ok.
but...When I build application with my ipad,error appear:

![0ed5a2c0-bef7-4444-85f6-4dd84ab99521](https://cloud.githubusercontent.com/assets/13251217/16580930/7a2306d0-42d9-11e6-8da3-b2532e529f68.png)

How do you config you pod and application about "Vaild Architectures"?

and maybe other things cause this error...

**Comment by mousebird** [comment]
There was a path problem.  Try it again and let us know.

**Comment by marychenyuan** [comment]
Thank you very much! It's worked.

I have an other question,How can I get the aerisID and aerisKey to config "MaplyAerisTiles" objects?now I can't get any weather message...

**Comment by jmnavarro** [comment]
You need to signup in the [aeris weather API](http://www.aerisweather.com/support/docs/api/)

**Comment by marychenyuan** [comment]
Thanks！！

When I registered my App on http://www.aerisweather.com/account/apps,I found I couldn't register successful, but I don't what is worry...
![c208f6e5-7c5f-49c4-bd99-df4f0c3bc01b](https://cloud.githubusercontent.com/assets/13251217/16613794/74d9195e-43a0-11e6-8ba3-1f4df03bcdc7.png)
