### ISSUE TITLE
Undefined symbols for architecture arm64:   "WhirlyKit::IntersectionManager::IntersectionManager(WhirlyKit::Scene*)", referenced from:

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#640]
Hi,
     When I use this by Cocoapod，error follows: 

![cb0e2850-52c5-409b-8d90-a230d80c65fb](https://cloud.githubusercontent.com/assets/13251217/16577390/8a6c1a84-42c7-11e6-9712-31c4b6bc698c.png)

What should I do...

**Comment by mousebird** [comment]
Pathing problem.  Should be fixed now.
