### ISSUE TITLE
Whirlyglobemaplycomponent.framework - mapbox vector + mbtiles

### ISSUE THREAD

**Issue by johndpope** [mousebird/WhirlyGlobe#641]
Hi Steve,

I've been reviewing the development branch develop_2_4_1
I haven't been able to get an offline database .mbtiles to use the MaplyMapnik / Mapbox VectorTiles class as they aren't included in framework. 

        MaplyMBTileSource *tiles = [[MaplyMBTileSource alloc]initWithMBTiles:@"countries"];
        MaplyBaseViewController *vc = [[MaplyBaseViewController alloc]init];
        Test *style = [[Test alloc]init];
        MapboxVectorTiles *tileSource = [[MapboxVectorTiles alloc]initWithMBTiles:tiles style:style viewC:vc];
        
        MaplyQuadPagingLayer   *vectorTiles = [[MaplyQuadPagingLayer alloc]initWithCoordSystem:[[MaplySphericalMercator alloc] initWebStandard]  delegate:tileSource];
        [globeVC addLayer:vectorTiles];

I tried to add the mapbox headers to framework - but it doesn't take.

Previous issues referenced this - 
https://github.com/mousebird/WhirlyGlobe/issues/271
but with the mapbox updates / changes - it seems like something is no longer working.
Or am I missing something?

![screen shot 2016-07-05 at 10 11 29 pm](https://cloud.githubusercontent.com/assets/289994/16587496/78591cc6-42fd-11e6-8934-afbdb7bcf5d8.png)

![screen shot 2016-07-05 at 9 43 03 pm](https://cloud.githubusercontent.com/assets/289994/16586726/d8c5f0c4-42f9-11e6-8129-58919d1e95f0.png)
![screen shot 2016-07-05 at 9 45 25 pm](https://cloud.githubusercontent.com/assets/289994/16586727/d963c81c-42f9-11e6-8f88-e19b0f7a2c22.png)

**Comment by mousebird** [comment]
Are you using the Podspec?  If so, the vector tiles are included in the podspec.
They are in the submodule, though.
The AutoTester app is using offline MBTiles in the develop_2_4_1 branch.  Can you compile and run that app?

**Comment by johndpope** [comment]
Hi Steve,

Thanks for the pointer - I run the autotester sample app - I get this red screen for the mbtiles + vector / Mapzen / Mapjam.

![img_0634](https://cloud.githubusercontent.com/assets/289994/16642291/1feef5d4-443c-11e6-8d60-d0676494c67a.jpg)

Ok - after some digging the test case for vectors seems to be hitting MaplyTestCaseOptionGlobe
By commenting this out - I get the vector maps. Correctly. Thanks. 

- (void)start:(bool)manual
{
	self.running = YES;

	dispatch_group_t lock = dispatch_group_create();

//	if (self.options & MaplyTestCaseOptionGlobe) {
//        if (!manual)
//            dispatch_group_enter(lock);
//
//        [self runGlobeTestWithLock:lock manual:manual];
//
//        if (manual)
//            return;
//	}

	if (self.options & MaplyTestCaseOptionMap) {
        if (!manual)
            dispatch_group_enter(lock);

        [self runMapTestWithLock:lock manual:manual];

        if (manual)
            return;
	}
....
}



I had intended to use the vector mbtile db with the mapbox styles - completely offline.
with this file - > 
https://raw.githubusercontent.com/mapbox/mapbox-gl-styles/master/styles/bright-v8.json

but looking at the internals of the style file - it's referencing externals files - so this maybe more challenging. Did you have any experience with this?

```
  "sources": {
        "mapbox": {
            "url": "mapbox://mapbox.mapbox-streets-v7",
            "type": "vector"
        }
    },
    "sprite": "mapbox://sprites/mapbox/bright-v8",
    "glyphs": "mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
    "layers": [


```

Also - fyi - (unrelated) it seems like this file is no longer available -  https://raw.githubusercontent.com/mapbox/mapbox-gl-styles/master/styles/emerald-v8.json

**Comment by mousebird** [comment]
So you were able to get things working?

Support for Mabox GL Style sheets is incomplete, but it may be complete enough for your task, depending.  References to the sprite and glyph sheets aren't used.  For glyph sheets, there's no real need since we use the fonts on the local device.  Sprites are just missing at the moment.

**Comment by johndpope** [comment]
Hi Steve, 
I was unsuccessful in styling the maps. 
It's a bit of a deal breaker as I need the app to look great. I acknowledge your efforts.  
It's a pity one can't cherry pick the code from mapbox.
Looking at the mapbox-gl - these guys have done a great job too. 
I'm exploring commercial options / if you could send me a quote to upgrade the style sheets - I'd be happy to mention it. or call me - 347 515 8848

![screen shot 2016-07-25 at 5 21 57 pm](https://cloud.githubusercontent.com/assets/289994/17117885/517befa4-528c-11e6-8e8f-75160c3aa807.png)

**Comment by mousebird** [comment]
Depending on what you need it might not be difficult to nudge the style sheet support the rest of the way.  I'd love to do that, of course.

Can you hit me up at contact@mousebirdconsulting.com?  I'm traveling so it's hard to arrange a phone call.
