### ISSUE TITLE
[Android] Kit does not compile after last commit in develop_3_0

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#642]
Getting 
```
.../WhirlyGlobeSrc/Android/src/com/mousebird/maply/GlobeController.java:125: error: unreported exception Throwable; must be caught or declared to be thrown
		super.finalize();
		              ^
1 error
:compileReleaseJavaWithJavac FAILED
```

**Comment by mousebird** [comment]
I've pushed a fix.  It's odd that it's not showing up for me, but the GlobeController's finalized turned out unnecessary.

**Comment by jmcazaux** [comment]
Same happened for the map. Will create a PR in a sec.


Same thing fot the map.
Object.finalize() actually throws errors (https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#finalize--).

I heve no idea why it does not show in your set up... Compiler settings ? I am not aware if this can be tweaked.

**Comment by mousebird** [comment]
Fixed that one now too.
