### ISSUE TITLE
[IOS] -Tracks over North Pole

### ISSUE THREAD

**Issue by speedbird5** [mousebird/WhirlyGlobe#648]
I was wondering if there is a fix for this?
The track is a vector created from an array of MaplyCoordinates and goes over the north pole.

![screen shot 2016-07-06 at 21 17 24](https://cloud.githubusercontent.com/assets/20328510/16637977/bba074dc-4426-11e6-99ba-b824da246fd4.png)

**Comment by mousebird** [comment]
Are you having the toolkit subdivide it in some way?
If so, which method are you using?

**Comment by speedbird5** [comment]
No, here is the code...

let desc: [String:AnyObject] = [kMaplyColor: UIColor.blueColor(), kMaplyVecWidth: 7]

**Comment by mousebird** [comment]
And then you're just doing an addVectors:  ?

**Comment by speedbird5** [comment]
Yes.  Here is the full code...

        let points = geodesicPolyline!.points()
        let pointscount = geodesicPolyline!.pointCount-1

        for i in 0.stride(through:pointscount + 20, by: 20) {
            guard i < pointscount else {
                let point = MKCoordinateForMapPoint(points[pointscount])
                let x = Float(point.latitude)
                let y = Float(point.longitude)
                coords.append(MaplyCoordinateMakeWithDegrees(y, x))
                break
            }
            let point = MKCoordinateForMapPoint(points[i])
            let x = Float(point.latitude)
            let y = Float(point.longitude)
            coords.append(MaplyCoordinateMakeWithDegrees(y, x))
        }

        let coordsCount = Int32(coords.count)
        let desc: [String:AnyObject] = [kMaplyColor: UIColor.blueColor(), kMaplyVecWidth: 7]
        let vec = MaplyVectorObject(lineString: &coords, numCoords: coordsCount, attributes: nil)
        theViewC?.addVectors([vec], desc: desc)

**Comment by mousebird** [comment]
Can you print those coordinates out in a form I could past into an array?
I'd like to set up a test case based on this.

**Comment by speedbird5** [comment]
Hi Steve, I have uploaded a .txt file with the coordinates listed.

The track is from JFK airport to Singapore airport as shown below.

[Maply Coordinates Array.txt](https://github.com/mousebird/WhirlyGlobe/files/353566/Maply.Coordinates.Array.txt)

![screen shot 2016-07-08 at 15 05 30](https://cloud.githubusercontent.com/assets/20328510/16677947/d805682e-451d-11e6-8c14-bcdae65a3dc3.png)

**Comment by mousebird** [comment]
I'm going through trying to clean up old issues.  Is this one still active?

**Comment by speedbird5** [comment]
Hi Steve, yes it still happens. Has it got something to do with the hole in the sphere over each pole or the cap over each pole?

I was wondering if you had a solution 

Peter

**Comment by mousebird** [comment]
It's related in a sense.  It's probably going through spherical mercator on its way.
