### ISSUE TITLE
Do I need to register an new aeris developer account?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#650]
Hi,
   Do I need to get an new aerisID and aerisKey?  I didn't see any infomation to require me to do this,I just use the "2kDDnD7Q1XFfFm4CwH17C" and "FQmadjUccN3CnB4KG6kKeurUpxHSKM0xbCd6TlVi",right?

**Comment by mousebird** [comment]
You need your own keys.  We just provided those for testing.  They're attached to a demo account and won't provide very many views.
