### ISSUE TITLE
[IOS]  Stars viewable through globe.

### ISSUE THREAD

**Issue by speedbird5** [mousebird/WhirlyGlobe#651]
Hi,

When I add stars, they are visible through the globe as shown below.  Is there a way of making the globe opaque?

I am using starcatalog_orig.txt and star_background.png.

Here is the code:

               if let globeViewC = globeViewC {
                let sun = MaplySun(date: NSDate())
                let light = sun.makeLight()
                
                light.ambient = UIColor(red: 0.18, green: 0.18, blue: 0.18, alpha: 1.0)
                light.diffuse = UIColor(red: 0.9, green: 0.9, blue: 0.9, alpha: 1.0)

                light.viewDependent = true
                theViewC?.clearLights()
                theViewC?.addLight(light)
                
                let starsFileName = NSBundle.mainBundle().pathForResource("starcatalog_orig", ofType: "txt")
                let stars = MaplyStarsModel(fileName: starsFileName!)
                let starsImage = UIImage(named: "star_background")
                stars?.setImage(starsImage!)
                stars?.addToViewC(globeViewC, date: NSDate(), desc: nil, mode: .Current)
                
                globeViewC.keepNorthUp = true
                globeViewC.height = 6371 * 1.0/6371.0
                globeViewC.heading = 90.0
                let startPt = MaplyCoordinateMakeWithDegrees(-73.78, 40.64)
                globeViewC.animateToPosition(startPt, time: 2.0)

![screen shot 2016-07-08 at 23 39 20](https://cloud.githubusercontent.com/assets/20328510/16689421/433cc298-4566-11e6-9456-d1950fc5b6f6.png)

**Comment by mousebird** [comment]
It's probably not the stars.  It's probably the image layer.
See if you're setting the kMaplyDrawPriority for the base layer there.  I bet it's being set to 0.
If it is, set it to at least kMaplyImageLayerDrawPriorityDefault

**Comment by speedbird5** [comment]
Thanks Steve, I will try that and make a post on Github.

Regards,

Peter

**Comment by speedbird5** [comment]
Yep.   I did have it set to zero.
kMaplyImageLayerDrawPriorityDefault fixed it.
Many thanks.
