### ISSUE TITLE
3D "smooth" shapes representing weather information

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#652]
Good afternoon,

I was wondering how I could implement this kind of 3D shapes in WhirlyGlobe:

![owsaso2bis](https://cloud.githubusercontent.com/assets/15698398/16700603/059f9d08-4529-11e6-9bef-8bc15206ce58.png)

![owsaso3bis](https://cloud.githubusercontent.com/assets/15698398/16700612/0e75ec70-4529-11e6-9045-eb4e302191fe.png)

Best,

Sebastien.

**Comment by mousebird** [comment]
Neat!  What's the from?

The first version you could probably do as Lofted Polygons.  There's a min and max height for just this purpose.

The second you'd need to build yourself.  You'd have to use raw geometry to build a MaplyModel and instance it in the right place.

**Comment by Sebboulnois** [comment]
My colleague developed these shapes by hand. It has been done for a individual interview with professional pilots. Thank you for your answers. I will look at that this week.

Cheers,

Sebastien.

**Comment by Sebboulnois** [comment]
Hi Steve.

We played a bit with the lofted polygons and we created some simple shapes:

![img_0283](https://cloud.githubusercontent.com/assets/15698398/16771950/4f6a3bba-4820-11e6-9bb4-7540eaa20595.PNG)

Here is the code for adding the polygons (I am not putting the previous code about coordinates):

[exocentricViewpoint addLoftedPolys:@[[test objectAtIndex:0]] key:nil cache:nil desc:@{kMaplyColor: [UIColor colorWithRed:1.0 green:0.0 blue:0.0 alpha:0.25], kMaplyLoftedPolyBase:@(0.0),kMaplyLoftedPolyHeight:@(0.0131847)} mode:MaplyThreadCurrent];

We notice that the shapes are not entirely drawn. Is this done on purpose or is this an issue?

Sebastien.

**Comment by mousebird** [comment]
I'd try the reverse ordering for the coordinates.  It looks like it's inside out.

**Comment by Sebboulnois** [comment]
It works! Thank you. I have another question. It looks like the only way to change viewpoints is to apply our touch controls on the map. Is there any way to apply these controls on objects? The thing is that we can't turn around the object correctly because it takes the map chunk behind as a reference.

**Comment by mousebird** [comment]
Oh, ha.  Well, I did add some low level support for that in the IntersectionManager.  I'm using it for LIDAR.  I calculated a minimum Z mesh below the LIDAR data and use that for moving around.  Works pretty well.

It's not hooked up to other objects at the moment, I'm afraid.  And it's C++.

**Comment by Sebboulnois** [comment]
Thank you for the information! I'll leave it this way for now and talk about it as a current technical issue.

So my colleague has been working on lofted polygons and he wanted to use extruded shapes as well. First, he created a lofted polygon (in green). Then, he created an extruded shape so he could integrate another shape in this green polygon. He tried to use your example regarding red arrows you integrated in a yellow shape (in the component tester).

Here is the code he used:

<img width="718" alt="screen shot 2016-07-18 at 11 05 55 am" src="https://cloud.githubusercontent.com/assets/15698398/16919443/a2f87b14-4cd7-11e6-8081-675a4bce8eba.png">

And we get this output: 

![img_0292](https://cloud.githubusercontent.com/assets/15698398/16919476/cbad9dc8-4cd7-11e6-8457-fe660cb0f137.PNG)

The green shape he created before is here but we don't get anything about the extruded shape. What are we doing wrong here?

Thank you for your help.

Sebastien.

**Comment by mousebird** [comment]
Can you add that code in the Issue?  Or how about as a gist?
I want to stick it in the AutoTester and see what happens.

**Comment by Sebboulnois** [comment]
Here is the full code for the green lofted polygon and the shape extruded:

-(MaplyShapeExtruded *) addRandomLoftedPolygonsWithLongitude:(float) longitudePosition latitude:(float) latitudePosition altitude:(float) altitudePosition cloudHeight:(float) cloudHeight cloudRadius:(int) cloudRadius color:(UIColor*)color cloudInside:(MaplyShapeExtruded *) cloudInside definitiveDisplay:(bool)definitiveDisplay
{
    float theta=360.0;
    float xCloud, yCloud, zCloud;
    float xInCloudFrame,  yInCloudFrame, zInCloudFrame;
    float xInEarthFrame,  yInEarthFrame, zInEarthFrame;
    float pointRadialDistance, pointAltitude, pointLongitude, pointLatitude;
    int distanceFromCloudCenter;
    NSMutableArray *shapes = [NSMutableArray new];
    MaplyShapeExtruded *shapeExtruded;
    NSMutableArray *shapesExtruded = [NSMutableArray new];
    MaplyCoordinate coords2D[11];
    double coords[2*11];
    MaplyVectorObject *vectObj;
    
    for(int i=0;i<10;i++)
    {
        
        distanceFromCloudCenter = (arc4random() % (cloudRadius/2))+ cloudRadius/2;
        
        xInCloudFrame=-2*(altitudePosition+6371000)*sinf(distanceFromCloudCenter/((altitudePosition+6371000)*2))*sinf(distanceFromCloudCenter/((altitudePosition+6371000)*2));
        yInCloudFrame=-2*(altitudePosition+6371000)*sinf(distanceFromCloudCenter/((altitudePosition+6371000)*2))*cosf(distanceFromCloudCenter/((altitudePosition+6371000)*2))*sinf(theta*M_PI/180);
        zInCloudFrame=2*(altitudePosition+6371000)*sinf(distanceFromCloudCenter/((altitudePosition+6371000)*2))*cosf(distanceFromCloudCenter/((altitudePosition+6371000)*2))*cosf(theta*M_PI/180);
        
        xCloud = (altitudePosition+6371000)*cosf(latitudePosition * M_PI / 180)*cosf(longitudePosition * M_PI / 180);
        yCloud = (altitudePosition+6371000)*cosf(latitudePosition * M_PI / 180)*sinf(longitudePosition * M_PI / 180);
        zCloud = (altitudePosition+6371000)* sinf(latitudePosition * M_PI / 180);
        
        
        xInEarthFrame=cosf(latitudePosition * M_PI / 180)*cosf(latitudePosition * M_PI / 180)*xInCloudFrame-sinf(longitudePosition * M_PI / 180)*yInCloudFrame -cosf(longitudePosition * M_PI / 180)*sinf(latitudePosition * M_PI / 180)*zInCloudFrame+xCloud;
        yInEarthFrame=sinf(longitudePosition * M_PI / 180)*cosf(latitudePosition * M_PI / 180)*xInCloudFrame + cosf(longitudePosition * M_PI / 180)*yInCloudFrame-sinf(longitudePosition * M_PI / 180)*sinf(latitudePosition * M_PI / 180)*zInCloudFrame+yCloud;
        zInEarthFrame=sinf(latitudePosition * M_PI / 180)*xInCloudFrame+cosf(latitudePosition * M_PI / 180)*zInCloudFrame+zCloud;
        
        pointRadialDistance=sqrtf(xInEarthFrame*xInEarthFrame+yInEarthFrame*yInEarthFrame+zInEarthFrame*zInEarthFrame);
        //pointAltitude=pointRadialDistance-6371000;
        pointLatitude=(asinf(zInEarthFrame / pointRadialDistance)); //radians
        pointLongitude=(atanf(yInEarthFrame / xInEarthFrame));
        if(pointLongitude > 0)
        {
            pointLongitude=-M_PI+pointLongitude;
        }
        
        coords2D[i].x=pointLongitude;
        coords2D[i].y=pointLatitude;
        coords[2*i]=pointLongitude;
        coords[(2*i)+1]=pointLatitude;
        theta=theta-36.0;
        
    }
    
    coords2D[10].x=coords2D[0].x;
    coords2D[10].y=coords2D[0].y;
    coords[20]=coords[0];
    coords[21]=coords[1];
    
    
    vectObj = [[MaplyVectorObject alloc] initWithAreal:coords2D numCoords:11 attributes:nil];
    [shapes addObject:vectObj];
    
    shapeExtruded = [[MaplyShapeExtruded alloc] initWithOutline:coords numCoordPairs:11];
    shapeExtruded.center= MaplyCoordinateMakeWithDegrees(longitudePosition, latitudePosition);
    shapeExtruded.height=altitudePosition;//altitudePosition/6371000;
    shapeExtruded.thickness=cloudHeight;//cloudHeight/6371000;
    shapeExtruded.color=color;
    shapeExtruded.scale=1.0;
    //NSLog(@"%f", shapeExtruded.coordData[7]);
    
    
    if(definitiveDisplay==true)
    {
        [exocentricViewpoint addLoftedPolys:@[[shapes objectAtIndex:0]] key:nil cache:nil desc:@{kMaplyColor: color, kMaplyLoftedPolyBase:@(altitudePosition/6371000),kMaplyLoftedPolyHeight:@((altitudePosition+cloudHeight)/6371000)} mode:MaplyThreadCurrent];
        [worldReferenceViewpoint addVectors:@[[shapes objectAtIndex:0]] desc:@{kMaplyColor:color, kMaplyFilled:@(YES)}];
        
        /*for(int i=0;i<5;i++)
        {
            coords2D[10-i]=coords2D[i];
        }
        
        vectObj = [[MaplyVectorObject alloc] initWithAreal:coords2D numCoords:11 attributes:nil];
        [shapes addObject:vectObj];
        
        [exocentricViewpoint addLoftedPolys:@[[shapes objectAtIndex:1]] key:nil cache:nil desc:@{kMaplyColor: color, kMaplyLoftedPolyBase:@(altitudePosition/6371000),kMaplyLoftedPolyHeight:@((altitudePosition+cloudHeight)/6371000)} mode:MaplyThreadCurrent];*/
    }
    
    if(cloudInside != nil)
    {
        MaplyGeomModel *shapeModel = [[MaplyGeomModel alloc] initWithShape:cloudInside];
        MaplyGeomModelInstance *geomInst = [[MaplyGeomModelInstance alloc] init];
        geomInst.center=MaplyCoordinate3dMake(cloudInside.center.x,cloudInside.center.y,cloudInside.height);
        MaplyMatrix *orientMat = [[MaplyMatrix alloc] initWithYaw:0.0 pitch:0.0 roll:0.0];
        geomInst.transform = [[[MaplyMatrix alloc] initWithScale:1.0/6371000.0] multiplyWith:orientMat];
        //geomInst.selectable=true;
        geomInst.model=shapeModel;
        [shapesExtruded addObject:geomInst];
        
        [exocentricViewpoint addModelInstances:shapesExtruded desc:@{kMaplyColor:cloudInside.color} mode:MaplyThreadAny];
        [worldReferenceViewpoint addModelInstances:shapesExtruded desc:@{kMaplyFilled:@(YES)} mode:MaplyThreadAny];
        
    }
    
    return shapeExtruded;
    
}

MaplyShapeExtruded *test = [MaplyShapeExtruded new];
    test=[self addRandomLoftedPolygonsWithLongitude:-81.01869674 latitude:27.6827425 altitude:7*8000.0 cloudHeight:7*4000.0 cloudRadius:10000 color:[UIColor colorWithRed:0.6 green:0.2 blue:0.2 alpha:0.7]cloudInside:nil definitiveDisplay:false];

[self addRandomLoftedPolygonsWithLongitude:-81.01869674 latitude:27.6827425 altitude:7*8000.0 cloudHeight:7*4000.0 cloudRadius:50000 color:[UIColor colorWithRed:0.45 green:0.7 blue:0.45 alpha:0.7] cloudInside:test definitiveDisplay:true];

**Comment by mousebird** [comment]
Is this one still an active problem?

**Comment by Sebboulnois** [comment]
I think it will work this way for now. This is not the big priority.

Thanks!
