### ISSUE TITLE
[Android] random crash when building QuadPaginglayer on a running MapConttroller

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#653]
I my app, I lett user change map background while the map is being displayed.

To do so, I build another paging layer and swap, remove the current one and adds the new one.

When building the new layer (so right at the begining of this process) I sometimes get the following exception:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
                                                                   at com.mousebird.maply.MaplyBaseController.getLayerThread(MaplyBaseController.java:125)
                                                                   at com.mousebird.maply.QuadImageTileLayer.<init>(QuadImageTileLayer.java:106)
```

**Comment by jmcazaux** [comment]
I do have this one fairly often and the strange thing is that it happens as well when the map has been shutdown.

**Comment by mousebird** [comment]
I think I know the cause of the normal case, but it's odd that it would happen any length of time after the map is shutdown.

Unless you see it appearing in the Finalizer Daemon.

**Comment by jmcazaux** [comment]
Nope, there is no finalizer messages around this crash.

And actually the "length of time" is my fault (sorry if I caused any worries)... So if you have found the main cause, we should be OK then.

**Comment by mousebird** [comment]
This should now be fixed.
It might lead to other problems, though.  Let me know what you see.
