### ISSUE TITLE
[iOS] Mapquest have Discontinued Open Tiles. How to Use their new static maps instead?

### ISSUE THREAD

**Issue by speedbird5** [mousebird/WhirlyGlobe#658]
It appears that Mapquest has discontinued it’s open tiles at    http://otile1.mqcdn.com/tiles/1.0.0/sat/     

It seems you have to have an API key, which one can get for free.  The information here   http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/  says that you can use the static maps as a replacement.

Unfortunately, when I use their static maps and try to use it as a remote tile source in Whirlyglobe - as both a globe and map,  I get a black screen.

The URL that I am using gives me the following PNG shown below so I know the URL is valid.

Can you tell me how to access the new Mapquest maps and use them as a source for the globeView and mapView?

Thanks,

Peter
![image](https://cloud.githubusercontent.com/assets/20328510/16789228/17f3f4f8-48ef-11e6-8a41-eea5933af5e7.png)

**Comment by mousebird** [comment]
The simplest way is to probably form the full URL string with {x} {y} and {z} in the appropriate places.  If you initialize a remote tile source with that string it will substitute x,y, and z where it needs.

**Comment by speedbird5** [comment]
I have tried the following URL string and code (with my API key obviously attached) and it returns the above image, but I still get a black globe or map for that matter.

Anyone got it to work yet?

    			guard let tileSource = MaplyRemoteTileSource(
				baseURL: "http://www.mapquestapi.com/staticmap/v4/getmap?size=1024,1024&type=map&scale=110935786&center=39.740112,-104.98485600000001&imagetype=PNG&projection=sm/{z}/{y}/{x}&key=YOUR-KEY-HERE",
				ext: "png",
				minZoom: 0,
				maxZoom: 2) else {
				print("Can't create the remote tile source")
				return
			}

**Comment by mousebird** [comment]
That's the static map URL.  The clue is that it contains "staticmap" in the name.  :-)
You can't ask a static map URL for tiles.  Did they give you a TMS compatible URL?

**Comment by speedbird5** [comment]
The information here http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/ says that the available options are now 

MapQuest plugin for Leaflet

iOS mobile SDK

Android mobile SDK

Static map API

**Comment by mousebird** [comment]
Wow, they really locked that up.

I can see the requests going out to their server if I use the leaflet plugin, but it looks like they have a layer of security on them.

You should probably ask Mapquest if you can use the tiles directly in someone else's API.  If you want to cc: me on it, that would be fine.

**Comment by speedbird5** [comment]
Judging by the comments on the forums, it seems they don't want to allow that.

**Comment by mousebird** [comment]
I looked through the forums as well.  Looks like Mapquest tiles are no longer usable outside of Mapquest's own plugins.

Now I'm sure I could engineer around that, but I'm not going to.  I respect the wishes of all data providers.

As for alternatives, I suggest looking into Mapbox's pricing or see if you can use one of Stamen or CartoDB's free tile sets.
