### ISSUE TITLE
Can not find Maply project source files for android due to which i am not able to compile android test project Android

### ISSUE THREAD

**Issue by Ahsanejazz** [mousebird/WhirlyGlobe#659]
Actually i am trying to compile whirly library for my android project. I pulled whole whirlyGlobe project on my desktop then i made a checkout for develop 3_0 branch. Now i am trying to compile the sample project AutoTesterAndroid. But i am not able to compile this project. Android studio is saying {Error:A problem was found with the configuration of task ':app:prepareAutoTesterAndroidMaplyUnspecifiedLibrary'.
> File '/Users/ahsan/Documents/SoftCircles/Android/chef-koochooloo/tags/WhirlyGlobe/WhirlyGlobeSrc/AutoTesterAndroid/Maply/Maply.aar' specified for property 'bundle' does not exist.} Why i am getting this error and how to resolve this? My soul purpose is to use this library in my android project. Please help me in this. 
One thing i would like to mention here is that why is Maply Library project is empty in AutoTesterAndroid project. There exists no source file in this. Only a gradle file and .iml file.

**Comment by mousebird** [comment]
There are instructions in the Android directory.  Look for how-to-build.txt.

I see that our [daily builds](https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/) for Android are now online as well.  We haven't had a chance to work up a web page yet, but you can pick through that S3 bucket to find the latest one.

**Comment by Ahsanejazz** [comment]
Thank you mousebird. Hopefully i will be able to build it now.
