### ISSUE TITLE
red color and light

### ISSUE THREAD

**Issue by coderLeng** [mousebird/WhirlyGlobe#661]
**this is the result on genymotion:**![f_8l25u a7e s vqiqa6l](https://cloud.githubusercontent.com/assets/15138573/16831408/6ea000ba-49d7-11e6-93e1-d7930f1cdcfa.png)
**this is the result on physical device:**![1d8d25b4741cf222a6b045b9d06114dd](https://cloud.githubusercontent.com/assets/15138573/16831430/856aad4a-49d7-11e6-9a3d-8a9ab3dfaa25.jpg)

what's the reason of that? the second picture has some red color and light.
@mousebird

**Comment by mousebird** [comment]
What architectures is that second one?

**Comment by coderLeng** [comment]
the architectures is arm64-v8a

**Comment by songday** [comment]
Another device with the same situation
CPU: MT6735(Cortex-A53 architecture 64-bit)
GPU: Mali-T720

**Comment by mousebird** [comment]
It seems to happen on the 64 bit versions.  If you just use the 32 bit version of the NDK library for now, that should work around it.

**Comment by sonyraj** [comment]
Can you share your code for setting up WhirlyGlobe in android

**Comment by coderLeng** [comment]
https://github.com/coderLeng/WhirlyGlobeTest has the test code

**Comment by sonyraj** [comment]
Thanks man. :+1:

**Comment by coderLeng** [comment]
@mousebird I set the latest ndk version 12 ---->ndk.dir=E\:\\ndk\\**android-ndk-r12b-windows-x86**\\android-ndk-r12b ,but it don't work well.

**Comment by sonyraj** [comment]
@coderLeng sorry to trouble you again, can you tell me , how can i change the language, now its is showing Chineese. Thanks again

**Comment by songday** [comment]
@sonyraj Did you mean those Chinese shown on tellurion?

**Comment by sonyraj** [comment]
@coderLeng Language used to display names of countries on the globe. PLease see the screen shot
![untitled](https://cloud.githubusercontent.com/assets/8150087/16911092/261213d0-4cfa-11e6-8f3c-6b834f38aecf.png)

**Comment by songday** [comment]
Hi, @sonyraj those country names were saved in geography-class.mbtiles. they're un-configurable.

**Comment by sonyraj** [comment]
@coderLeng OK... But how can i get another one with english language

**Comment by songday** [comment]
@sonyraj we will let you know when it's ready , but since we're not in office now, we will upload to Github  tomorrow :)

**Comment by sonyraj** [comment]
No worries :+1:  Thanks man... :-)

**Comment by songday** [comment]
@sonyraj Hi, I uploaded at http://www.tourting.com/geography-class_d5fdb1.mbtiles

**Comment by coderLeng** [comment]
You meet the above situation? @sonyraj

**Comment by sonyraj** [comment]
@coderLeng Which sitution? Change of language? 
@songday the language is still Chineese. Thanks for your effort. I've another problem, the background of globe is displayed in black. I tried to change it to android.R.color.transparent but it didn't work. do you know how to change that background to transparent. Please see the attached screenshot
![capture](https://cloud.githubusercontent.com/assets/8150087/16977562/710ff124-4e74-11e6-8b87-18fd33de8b63.PNG)

**Comment by songday** [comment]
@coderLeng meant the 'Red shadow' issue
I don't have experience on changing background color, this may take a while to investigate
by the way, how did you address 'Red shadow' problem?

**Comment by sonyraj** [comment]
@songday  I didn't see any red light (Tested in SAMSUNG GALAXY NOTE2 CPU : Quad-core 1.6 GHz Cortex-A9, GPU : Mali-400MP4). Please see the screenshot. 
![screenshot_2016-07-20-14-25-33](https://cloud.githubusercontent.com/assets/8150087/16981013/52f57eea-4e86-11e6-979f-fe91ffe5694c.png)

**Comment by coderLeng** [comment]
I'm sorry,i don't know .The class GlobeController has the method setClearColor (),but the alpha can't change the background.I also don't know the reason.The red shadow' problem have bean solved.

**Comment by sonyraj** [comment]
@coderLeng :+1:

**Comment by mousebird** [comment]
You can change the background color with setClearColor().
If you need it to be transparent, you need to switch to a TextureView on startup.  Look in the Settings passed to the controller on creation.

**Comment by sonyraj** [comment]
@mousebird , Sorry I didn't get you? What do you mean by on starup? I tried setting 
`useSurfaceView=false` and then the background using setTextColor(). But it is not working. Here is my code, 

`public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        GlobeController.Settings settings = new GlobeController.Settings();
        settings.useSurfaceView = false;
        mGlobeController = new GlobeController(getActivity(), settings);
        mGlobeController.setClearColor(ContextCompat.getColor(getActivity(), android.R.color.transparent));
        mGlobeController.gestureDelegate = mGestureDelegete;
        ViewGroup holder = (ViewGroup) view.findViewById(R.id.globeHolder);
        if (holder != null) {
            View globe = mGlobeController.getContentView();

            int margin = (int) getResources().getDimension(R.dimen.activity_horizontal_margin);

            DisplayMetrics dm = getResources().getDisplayMetrics();
            int width = dm.widthPixels;

            RelativeLayout.LayoutParams lp = new RelativeLayout.LayoutParams(width, width);
            lp.addRule(RelativeLayout.CENTER_IN_PARENT, RelativeLayout.TRUE);
            lp.setMargins(margin, margin, margin, margin);

            globe.setLayoutParams(lp);
            holder.addView(globe);

        }
    }
`

What changes should i make in this code tom make it working?

**Comment by mousebird** [comment]
In the Settings there's a color.  Use that along with useSurfaceView = false.
That's if you want a transparent background.  For a non-transparent background, you can leave useSurfaceView alone.

**Comment by mousebird** [comment]
The color problems are fixed on 64 bit builds.
