### ISSUE TITLE
Setup WhirlyGlobe in Android

### ISSUE THREAD

**Issue by sonyraj** [mousebird/WhirlyGlobe#666]
First of all thank you for sharing this awesome library and SORRY FOR RAISING THIS AS AN ISSUE ACTUALLY THIS IS NOT AN ISSUE :-) I've searched a lot and I can't find any reliable examples or sample projects to setup WhirlyGlobe in Android. Can you Provide some links to setup WhirlyGlobe in Android or add a sample get started project in the Source repo. Thanks in advance.

**Comment by mousebird** [comment]
I've just pushed a preliminary version of the first part of the [Android tutorial](http://mousebird.github.io/WhirlyGlobe/tutorial/android/getting-started.html).

Give it a try and let us know if it worked for you.

**Comment by sonyraj** [comment]
@mousebird  Thanks a lot. I'll give it a try and let you know :+1:  :-)

**Comment by sonyraj** [comment]
@mousebird Sorry for being late. THE CODE WORKS :+1:

**Comment by mousebird** [comment]
Nice!
