### ISSUE TITLE
MaplyAerisTileSet fails with nil tileSource

### ISSUE THREAD

**Issue by meyumeapps** [mousebird/WhirlyGlobe#667]
Hi,

Am following the example here:

http://mousebird.github.io/WhirlyGlobe/tutorial/aeris_weather.html

Have checked out and built 2.4.1

Have got id and key from Aeris.

I'm finding that it fails with an error:

`          self.aerisLayer = MaplyQuadImageTilesLayer(coordSystem: multiSource!.coordSys, tileSource: multiSource!)
  `

multiSource is nil because tileSources is nil when passed into the callback

Can you advise please

Scott Wilson-Billing
Met Office

**Comment by meyumeapps** [comment]
Please close.

My Aeris subscription didn't have maps, my bad, sorry!

**Comment by mousebird** [comment]
Glad it's working.

I'm curious about your use of AerisWeather, though.  Can I contact you outside of the Issues?

**Comment by meyumeapps** [comment]
Hi Steve,

Sure you can.

Was using Aeris as a rapid way of testing out the animated weather layers on the globe.

I’m doing some prototyping for the Met Office to look at various options for maps in our new app.

Regards
Scott

**Comment by mousebird** [comment]
Can I get your email address?  I'd love to discuss this more.
sjg@mousebirdconsulting.com is mine.

**Comment by meyumeapps** [comment]
meyumeapps@gmail.com
