### ISSUE TITLE
How to show english feature's name with Mapbox GL Style

### ISSUE THREAD

**Issue by P-Luca** [mousebird/WhirlyGlobe#668]
Hi Steve, and thank you for this great project!

I'm using Mapzen's mvt data and I would like to show in my map the english version for name of countries and other features. 
I tried to simply add `"text-field":"{name_en}"` to the style but it doesn't seem to be working at all
Is there any way for doing it?

Thank you!

**Comment by mousebird** [comment]
Take a look at MapboxVectorStyleSymbol.mm.  Right around line 138 it's directly pulling the name out of the attributes.

You can fix this simply by just changing that to @"name_en" I would think.  Longer term, we had code for this in the Mapnik styles, so we'd need to move that over.

**Comment by P-Luca** [comment]
Thank you Steve!

I figured it out and changed the code in order to use the `_textField` value.

p.s. Mapzen vector tile identify translation with `name:en` and not with `name_en`

Thank you very much for your help!
