### ISSUE TITLE
[Android] Programatically changing altitude shifts coordinates North

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#671]
In my app I have buttons for zoom in and zoom out.

I thought that would be as simple as changing the altitude and I wrote the following code:
```
    public void zoomIn() {

        Point3d position = this.getPosition();
        this.animatePositionGeo(position.getX(), position.getY(), position.getZ() / 2.0, ZOOM_ANIMATION_TIME);
    }

    public void zoomOut() {

        Point3d position = this.getPosition();
        this.animatePositionGeo(position.getX(), position.getY(), position.getZ() * 2.0, ZOOM_ANIMATION_TIME);
    }
```

Strangely, in both cases the horizontal position is altered as well and shifts North quite significantly.

Should I be doing something else ?
This is on a map currently.

Many thanks,
JM

**Comment by jmcazaux** [comment]
Is there actually an issue in getPosition ?
Or I might have misunderstood what it returns.

Making more tests, I remembered that I had issues with it in another place and replaced with `getCurrentViewGeo().getCenter()`.

Here some example exhibiting the difference:
```
Using Mbr         (x=3.915722°, y=43.618959°, z=0.0266)
Using getPosition (x=3.915722°, y=48.571268°, z=0.0266)
--
Using Mbr         (x=3.915722°, y=43.076191°, z=0.4740)
Using getPosition (x=3.915722°, y=48.568886°, z=0.4740) 
--
Using Mbr         (x=-122.034905°, y=38.943336°, z=0.2657)
Using getPosition (x=-122.034902°, y=42.558675°, z=0.2657)
--
Using Mbr         (x=-122.430144°, y=37.831199°, z=0.0169)
Using getPosition (x=-122.430147°, y=40.924573°, z=0.0169)
--
Using Mbr         (x=-145.196834°, y=57.874582°, z=1.6816)
Using getPosition (x=-145.196833°, y=82.481006°, z=1.6816)
```
I cannot see a pattern, unless the error increases the further North? Not sure.

**Comment by mousebird** [comment]
We may need an explicit keepNorthUp.
When calculating the quaternion for a given position, it may rotate it any which way it chooses if we don't explicitly keep north pointed up.

**Comment by jmcazaux** [comment]
That is an issue as there will be situation where I need to call this and North is not up...

Any workaround ?

**Comment by mousebird** [comment]
It does seem odd that just changing the height is doing this.
If you call setPositionGeo with the same values twice in a row does it do this?
How about with animatePositionGeo?

**Comment by mousebird** [comment]
There is a setKeepNorthUp in the GlobeController.
I think I'm missing what the issue is here.

**Comment by jmcazaux** [comment]
Steve I just realized reading my previous comment that I wrote this is a confusing way.

It seems it is actually getPosition that is giving the wrong results.
See my comment above where I compare the result of getCurrentViewGeo().middle  and getPosition.

Does it help?

**Comment by mousebird** [comment]
The MBR is going to vary as you move farther north.  I don't know if I'd expect the center to numerically be near the middle the screen.  There's a lot of wackiness there.

But I think there's a simple test case here.  If we animate to the current position, does it move?  I'll duplicate that.

**Comment by mousebird** [comment]
Sure enough, it was just wrong.  I never noticed because I was using the mapView and globeView internally.

I've fixed the problem and tacked a "Geo" on the end of "getPostion" to reflect what it's doing now that it's doing the right thing.
