### ISSUE TITLE
[Android] Any way to stop the user spinning more than 360°

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#672]
It might look like a nice thing in some situation, but when user are zoomed out, they can "spin the globe" (or the map) more than 360° (or 180°) well you get the idea.

Then when they interact with the map, I do have coordinates outside (-PI, +PI).
That quite some trouble to handle on the application side as there are a quite a few endpoints.

Is there any way to stop this ?
Or is there an option so that the the angles returned are always normalised ?

Many thanks.

**Comment by mousebird** [comment]
Are you getting large numbers in getPosition()?
Where do the big numbers turn up?

**Comment by jmcazaux** [comment]
This is in getCurrentViewGeo.

As getPosition gives latitude that is much shifted North I am using getCurrentVieGeo().middle to get the center of the view.

It shows in the MapDelegate functions as well.

**Comment by mousebird** [comment]
I've fixed this under another Issue, I believe.  Unless there's more to this.
If there is, just reopen.
