### ISSUE TITLE
Double tap event

### ISSUE THREAD

**Issue by rohitnagori** [mousebird/WhirlyGlobe#676]
I get delegate call when tapped on globe - (void)globeViewController:(WhirlyGlobeViewController *)viewC didSelect:(NSObject *)selectedObj. 
How can i get double tap event.
Your help will be really precious. Thanks in advance.

**Comment by mousebird** [comment]
I think you'd need to implement a double tap gesture.  I don't believe we're trapping that for selection by default.

**Comment by rohitnagori** [comment]
I need to get double tap event on maplyobject to show some information. How can i achieve this.

**Comment by mousebird** [comment]
You'll have to write a double tap gesture for the view and then call [findObjectAtLocation:](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/WhirlyGlobeViewController.html#//api/name/findObjectAtLocation:)

**Comment by rohitnagori** [comment]
findObjectAtLocation: does not return any maply object ?

**Comment by mousebird** [comment]
Not sure what you're asking.

**Comment by rohitnagori** [comment]
I have implemented double tap event on globe. Whenever i double tap the outline area i get point and pass it to findObjectAtLocation: but it does not return any maply object.
![screen shot 2016-07-21 at 11 33 36 am](https://cloud.githubusercontent.com/assets/5022126/17012692/0fbfcd5e-4f37-11e6-8769-4ab9923ae2d2.png)

**Comment by mousebird** [comment]
Make sure the vectors were added with selectable set to YES.

**Comment by rohitnagori** [comment]
This is the dictionary i am adding but it does not responde.
vectorUnSelected = @{
                         kMaplySelectable: @(true),
                         kMaplyColor: [UIColor clearColor],
                         kMaplyFilled: @(false),
                         kMaplyDrawPriority:@(50000)};

**Comment by mousebird** [comment]
You're making it invisible?  If you want vectors that just show up for selection but aren't visible, then try [addSelectionVectors:](http://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/MaplyBaseViewController.html#//api/name/addSelectionVectors:)
