### ISSUE TITLE
[Android] Any advice for a Proguard config that would work with Maply ?

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#677]
I did not use to use Proguard (bad boy) but I'll have to use it.

I tried the obvious almost default configuration, but Maply did not like it one bit...

Though I have 
```
-keepclasseswithmembernames, includedescriptorclasses class * {
    native <methods>;
}
```
it crashes as soon as I access the map saying it cannot find field "J"...

If anyone could share a working Proguard setup that would be great.

**Comment by mousebird** [comment]
I don't know much about Proguard.  Does it need to be mangling the WG-Maply?  Can you tell it just leave that alone?

**Comment by jmcazaux** [comment]
Normally with teh snippet above it does leave all native code untouched...

Ah, maybe what I am missing is to tell him to leave alone the Java bits of Maply as well...
I'll try that.

**Comment by mousebird** [comment]
Were you able to get this working?

**Comment by jmcazaux** [comment]
No I have not had time to look into this further yet.

**Comment by mousebird** [comment]
I'm gonna punt this one since it's not strictly related to the library.  However if you did find a solution other people might find that useful.

**Comment by geftimov** [comment]
Working solution is:
```java
##---------------Begin: proguard configuration for Maply ----------

-keep class com.mousebird.maply.** { *; }

-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

##---------------End: proguard configuration for Maply ----------
```

**Comment by mousebird** [comment]
Thanks!  We should put that somewhere.

**Comment by jmcazaux** [comment]
Excellent, I'll have a go at this.
