### ISSUE TITLE
How to apply css file in cartoDB map for layer presentation?

### ISSUE THREAD

**Issue by jigarmt92** [mousebird/WhirlyGlobe#680]
I have created polygon by using cartoDB but i dont have any idea for applying css for this polygon so if anybody applied css for this before? Need help to apply css or how should i pass in url or anything else?

Thank you.

**Comment by mousebird** [comment]
You'll need to give it style information when you add it to the visual.  Look at the arguments to addVectors:desc:  You'll want to use some of the dictionary options in the desc: argument.
