### ISSUE TITLE
Add Seletion Vector Cuases crash 

### ISSUE THREAD

**Issue by rohitnagori** [mousebird/WhirlyGlobe#683]
If you can provide me whirly framework with fix. It will be a great help.
Thanks in advance.

**Comment by rohitnagori** [comment]
I have a geojson file "US_State_Outline_20m.geojson" I use below code for adding selection vector

1)NSArray *allOutlines = @[[[NSBundle mainBundle] pathForResource:@"US_State_Outline_20m.geojson" ofType:nil]];

2) MaplyVectorObject *wgVecObj = [MaplyVectorObject VectorObjectFromGeoJSON:jsonData];
3) NSArray *arr=[wgVecObj splitVectors];
4) for (MaplyVectorObject *vectorObj in arr)
   {
5)  MaplyComponentObject *maplyobj = [globeController addSelectionVectors:[NSArray  arrayWithObject:vectorObj]];
   }

LIne 5 cause a crash Mentioned below:


2016-07-22 12:21:33.929 Pilot[1463:126235] -[__NSDictionary0 setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x7f8682508900
2016-07-22 12:21:33.978 Pilot[1463:126235] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionary0 setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x7f8682508900'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105f72d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001059e4deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105f7bd3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000105ec1cfa ___forwarding___ + 970
	4   CoreFoundation                      0x0000000105ec18a8 _CF_forwarding_prep_0 + 120
	5   Pilot                               0x0000000100b3238a -[MaplyBaseInteractionLayer applyDefaultName:value:toDict:] + 120
	6   Pilot                               0x0000000100b37d70 -[MaplyBaseInteractionLayer addVectorsRun:] + 418
	7   Pilot                               0x0000000100b3a757 -[MaplyBaseInteractionLayer addSelectionVectors:desc:] + 366
	8   Pilot                               0x0000000100b4ed26 -[MaplyBaseViewController addSelectionVectors:] + 78
	9   Pilot                               0x00000001009171e3 -[SyncChatViewController addCountries] + 3171
	10  Pilot                               0x0000000100915a53 -[SyncChatViewController setupMap] + 4163
	11  Pilot                               0x0000000100919089 -[SyncChatViewController parseChartDataResponse:] + 265
	12  Pilot                               0x0000000100918904 __40-[SyncChatViewController fetchChartData]_block_invoke_2 + 68
	13  libdispatch.dylib                   0x00000001066f6d9d _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00000001067173eb _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00000001066ff1ef _dispatch_main_queue_callback_4CF + 1738
	16  CoreFoundation                      0x0000000105ecc0f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x0000000105e8db99 __CFRunLoopRun + 2073
	18  CoreFoundation                      0x0000000105e8d0f8 CFRunLoopRunSpecific + 488
	19  GraphicsServices                    0x0000000107d55ad2 GSEventRunModal + 161
	20  UIKit                               0x000000010392bf09 UIApplicationMain + 171
	21  Pilot                               0x0000000100815a2f main + 111
	22  libdyld.dylib                       0x000000010674c92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by mousebird** [comment]
I just modified an AutoTester case to do this and it worked.

What version of WG-Maply are you using?

**Comment by rohitnagori** [comment]
Where can i see the version. I am not using pods. I am using ".framework"  file.

**Comment by mousebird** [comment]
Sounds like you're using the binary distribution.  You can grab the latest [one from here](https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/iOS_daily_builds/WhirlyGlobe_Maply_Nightly_20160726.zip).
