### ISSUE TITLE
[Android (& iOS ?)] MapDelegate.mapDidStopMoving not really called often enough

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#684]
As far as I understood, the map delegate functions and especially MapDelegate.mapDidStopMoving (and similar on the globe) are our only bite at the cherry to know that the view port has changed.

Unfortunately this function is not called often enough:
- when the user zooms in or out with double tap or tap with 2 fingers
- when you change the zoom programatically
- when the user swipe and stop (instead of giving momentum to the map/globe)

In those case, the viewport change is going unnoticed.

Maybe I have the wrong end of the stick, but I need to trigger "things" on viewport change (like dynamically displaying objects, etc.).

That would be good if didStopMoving was comprehensive (I think this is the best solution) or if there was another catch all method in the delegate called after each viewport change (after the change).

Many thanks,
JM

**Comment by mousebird** [comment]
I'll look at the cases where mapDidStopMoving isn't working.

There is also mapDidMove if that works better for you.

**Comment by mousebird** [comment]
I fixed the gestures.
I'm not sure we should do start/stop moving when we move programatically.

didMove might be the simplest thing to use if you need to track absolutely everything.  It will be triggered every frame, more or less.

**Comment by jmcazaux** [comment]
How did I miss didMove ?

It is indeed much more suited for my use case.
Many thanks,
JM
