### ISSUE TITLE
[Android] SDK keeps crashing on some devices

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#687]
Since I have distributed the last version of the SDK, one of my users with Samsung tablet (Galaxy tab III 8", code name SM-T310) cannot access the map.

From the crash reports I had, it seems to be this one, but it looks very strange to me.
```
java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_relocate(linker.cpp:976): cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "libMaply.so"...
	at java.lang.Runtime.loadLibrary(Runtime.java:371)
	at java.lang.System.loadLibrary(System.java:535)
	at com.mousebird.maply.MaplyBaseController.<init>(MaplyBaseController.java:199)
	at com.mousebird.maply.MapController.<init>(MapController.java:117)
	at com.droidfav2.map.MovingMap.<init>(MovingMap.java:576)
```

Edit:
After more digging, it seems it is affecting 3 users (out of my 15ish testers), all with this device, all with 4.2.2.

The kit was compiled with a port of buildmaply.sh, using `Release`as argument.

**Comment by mousebird** [comment]
One possibility is I'm not explicitly linking with the c++ library.  But I believe I am and I'd expect that to crash everywhere.
So another possibility is that the runtime library I linked with is incompatible with the one on their device.

**Comment by mousebird** [comment]
The build.gradle specifies a minSdkVersion of 14.  I assume your app has a similar minSdk?

You could try modifying the library's build.gradle to target version 16 and send them a specific build.  If that works, then we'll know what the problem is.

**Comment by jmcazaux** [comment]
I had min SDK in the app already. Recompiled the kit with minSDK 16 as as well, but it did not help.

**Comment by mousebird** [comment]
I'm traveling, but I have some really old hardware back at home.  I'll try it there when I'm back.

Assuming I have the same problem, I'm not sure what the solution is.

**Comment by jmcazaux** [comment]
Hold fire Steeven tester now says it works.

I think he got confused when testing teh first fix and did not test with the right version.

I'll confirm tomorow.

**Comment by jmcazaux** [comment]
Steve, this is definitely still happening with the last version of code.

**Comment by mousebird** [comment]
This has to be an old Android version problem.  I'm at a loss as to how to fix it.

**Comment by jmcazaux** [comment]
Actually it is not that old and fairly prevalent on the market.

It is a samsung Tab 3 8.0 ([code name SM-T310](http://www.gsmarena.com/samsung_galaxy_tab_3_8_0-5456.php)) running Android 4.2.2.

Indeed not last year device, but still fairly used.

It really seems all my testers with this device have the issue.

**Comment by mousebird** [comment]
Is the libgnu_shared.so shipping with your app?
It should be in the Maply AAR.  You might want to check that it's making its way into the bundle.

**Comment by jmcazaux** [comment]
This have been solved when referencing lib_gnustl explicitely

**Comment by mousebird** [comment]
Yes!

**Comment by jmcazaux** [comment]
But we still need to address the washed out buttons issue :(

**Comment by mousebird** [comment]
I'm guessing that's resource contention, but I'm not seeing anything quite like it elsewhere.
