### ISSUE TITLE
Visualization issue: objects located inside opaque shapes still visible.

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#689]
Hi,

I have a Visualization issue on my aviation application. I set up a flight-path (in green) composed of flight waypoints (white spheres) and this one is passing behind a lofted polygon that represents critical weather:

<img width="831" alt="screen shot 2016-07-26 at 10 29 59 am" src="https://cloud.githubusercontent.com/assets/15698398/17141883/f03226c4-531b-11e6-9e79-7c92eab83606.png">

However, the flight-path is still visible even if the red lofted polygon's opacity is set to 1. The consequence is that we think we are flying above the critical weather this is not the case. How can I fix that?

Thank you.

Sebastien.

**Comment by Sebboulnois** [comment]
I have also another issue on my bird's eye view (Orthogonal view). The critical weather information is not consistent all the time, especially when I zoom in/out:

<img width="847" alt="screen shot 2016-07-26 at 10 53 12 am" src="https://cloud.githubusercontent.com/assets/15698398/17142725/33223016-531f-11e6-8b2b-c7279eaa6e4e.png">

<img width="837" alt="screen shot 2016-07-26 at 10 53 19 am" src="https://cloud.githubusercontent.com/assets/15698398/17142731/3906c708-531f-11e6-9158-47b4d5d5352f.png">

Do you know where this could come from?

Sebastien.

**Comment by mousebird** [comment]
It all boils down to kMaplyDrawPriority.  You need to set the kMaplyDrawPriority on every object and you can expect them to be drawn in that order.  If two objects have the same priority, it's random as to the order they are drawn in.

There is a pure Z buffered mode, which we can drop into and out of, but that only works well with solid objects.  With transparency, you have to make use of the priority.

**Comment by Sebboulnois** [comment]
Thank you a lot! We will be working on that.
