### ISSUE TITLE
[Android (& iOS ?)] ScreenLabels competition for space ignores label offset (and possibly LayoutPlacement)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#690]
I am trying to do this with screen labels and have been pulling my hair most of the afternoon.

```
   MyName
x  MyDescription
   SomeOtherData
```

x is a marker, the rest are screen labels placed with offset and LayoutPlacement bu they all share the same location (the one of the marker).

I have tried everything I could and I could only ever display one of the labels.
They work independently from each others, not anymore as soon as there more than one.
I can only conclude that the layout algorithm ignores the label offset (I have tried with large offsets, no dice either) and possibly the LayoutPlacement as well.

Thanks,
JM

**Comment by jmcazaux** [comment]
Or possibly the zone that is evaluated around a label is way too big...

**Comment by mousebird** [comment]
I'll look at this, but it will take me a little while to set up a good test case.
My impression is that the simpler settings should work better.

**Comment by jmcazaux** [comment]
Maybe I have the wrong end of the stick indeed, but if you could elaborate on _the simpler settings_, I might find my way around.

Thanks,
JM

**Comment by mousebird** [comment]
I usually just use one layout option.  The offsets should work.

If you could set up a case in the AutoTester that's breaking, I'll be happy to get on it.  I am on vacation now, though, so probably not this week or next.

**Comment by jmcazaux** [comment]
Test case on its way, was on my TODO for the day.

JM

Le jeu. 28 juil. 2016 à 18:08, Steve Gifford <notifications@github.com> a
écrit :

**Comment by jmcazaux** [comment]
In the meantime if you can suggest a workaround to achieve what I am trying to do, I'll happily give it a go.

Thx,
JM

**Comment by jmcazaux** [comment]
Take this one with a pinch of salt.

After more experiment I am not sure this is a bug or if I expect the layout engine to leave less room around each item (maybe this should be a parameter).

**Comment by jmcazaux** [comment]
Ok, I have made more investigation and I must that I have no clue what is happening as it makes no sense.

Basically I have hacked more ScreeLabelTest to display only France (sorry about that), it should display once normally, once reverse ("ecnarF") and I am applying opposite offset to each label.

So if Xoffset is defined at 50 and YOffset is defined at 100, "France" should display 50 pixels left and 100 pixels above the marker, "ecnarF" should display 50 pixels right and 100 pixels below the marker.

Here what I get for various X/Y values.

![screenshot_20160804-170032](https://cloud.githubusercontent.com/assets/2640502/17407473/b445b6a0-5a67-11e6-978b-36735f6acf6c.png)
X=0, Y=0, this si what I'd expect


![screenshot_20160804-170221](https://cloud.githubusercontent.com/assets/2640502/17407530/e966d116-5a67-11e6-9695-d031703f0001.png)
X=150 Y = 0 I'd expect this as well


![screenshot_20160804-170707](https://cloud.githubusercontent.com/assets/2640502/17407555/01925d8c-5a68-11e6-9f6f-48c30456cbfb.png)
X=130 Y =0, this is all fine


![screenshot_20160804-170846](https://cloud.githubusercontent.com/assets/2640502/17407629/47523c98-5a68-11e6-99f7-e881366cd6eb.png)
X = 100 Y =0, **there is still plenty of room, I'd expect both labels to show.**


![screenshot_20160804-170914](https://cloud.githubusercontent.com/assets/2640502/17407714/a24d43fe-5a68-11e6-95e2-598aaac29ab8.png)
**Still with X = 100 and Y = 0 I had this on a couple of occasions... just cannot understand it**


![screenshot_20160804-171008](https://cloud.githubusercontent.com/assets/2640502/17407781/dd4b2674-5a68-11e6-9da9-4d2188765bfe.png)
X = 0, Y = 100, **I would expect to see both labels as there is plenty of room**


![screenshot_20160804-171036](https://cloud.githubusercontent.com/assets/2640502/17407818/0377002a-5a69-11e6-9e12-a42ac6738362.png)
X = 0, Y = 150 **did not work better **


![screenshot_20160804-171126](https://cloud.githubusercontent.com/assets/2640502/17407887/40380c84-5a69-11e6-9906-f02b7a9a9e71.png)
X = 150, Y = 150 **1) I would ecpect to see both labels, 2) the label that displays should be furter left (should look like a square)**



![screenshot_20160804-171155](https://cloud.githubusercontent.com/assets/2640502/17408036/e778abca-5a69-11e6-88df-d1c9be946d74.png)
X = 200, Y = 200 Both labels show, but the Y offset of France is wrong (should be symetrical).

@mousebird I will leave this in your capable hands, but I completely fail to understand what happens.

PS / i have updated the PR so that you can reproduce this.

**Comment by mousebird** [comment]
I've ported over an update from the iOS branch that fixes all the outstanding label problems there.  It seems to do on Android as well.

Take a look at these again, if you would, and let me know if it's working as you expect.

**Comment by mousebird** [comment]
As far as I know this is all cleared up.  Reopen if not.
