### ISSUE TITLE
MaplyAnnotation in globe - doesn't stick to the object when viewpoint is changed.

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#691]
Hi,

Is there any way or trick to make the annotation stick to the selected object when you change the globe viewpoint? It looks like we can't assign any height when the annotation is instantiated.

Thanks a lot,

Sebastien.

**Comment by Sebboulnois** [comment]
I also implemented an annotation in my flat map. When I drag it so I don't see the annotation anymore, it still goes through my globe view:

![img_0298](https://cloud.githubusercontent.com/assets/15698398/17184214/0a487ae4-53f9-11e6-8ca2-00266a03ad8f.PNG)

Is this normal? I tried it the other way (annotation in the globe view) but it works well.

Sebastien.

**Comment by mousebird** [comment]
Is that a split screen with a globe and a flat map?
Did you implement that with two full View Controllers or by grabbing the views from each view controller?
I suspect it's a matter of what the top view is.  If you were to put a view in between the full view and each of the subviews, it would probably work.

**Comment by Sebboulnois** [comment]
Correct.

This is a split screen. I have a main view controller. Then I added these two view controllers views (map and globe) in my main view controller view:

// Initializes a globe view.
    exocentricViewpoint = [[WhirlyGlobeViewController alloc] init];
    [exocentricViewpoint setDelegate:self];
    [self.view addSubview:exocentricViewpoint.view];
    exocentricViewpoint.view.frame = CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height/2);
    [self addChildViewController:exocentricViewpoint];
    
    // Initializes a map view
    worldReferenceViewpoint = [[MaplyViewController alloc] initWithMapType:MaplyMapTypeFlat];
    [worldReferenceViewpoint setViewWrap:true];
    [worldReferenceViewpoint setDelegate:self];
    [self.view addSubview:worldReferenceViewpoint.view];
    worldReferenceViewpoint.view.frame = CGRectMake(0, self.view.bounds.size.height/2, self.view.bounds.size.width, self.view.bounds.size.height/2);
    [self addChildViewController:worldReferenceViewpoint];


--

Do you have any idea regarding my first comment?

Thank you for your help, I appreciate that a lot.

Sebastien.

**Comment by Sebboulnois** [comment]
I put a view in between the mainViewController.view and the two map and globeViewController.view but it didn't work.

**Comment by mousebird** [comment]
Try setting clipToBounds on the globe and map views.

**Comment by Sebboulnois** [comment]
It works! Thank you. :-)

Coming back to the height problem in the globe view, it looks like I can't instantiate an height for the annotation so it sticks to an object. Would you have any advice for that?

Sebastien.

**Comment by mousebird** [comment]
There is no height for an annotation at present, I'm afraid.

**Comment by Sebboulnois** [comment]
Thank you!
