### ISSUE TITLE
[Android] Screen labels do not show when using LabelInfo.LayoutBelow

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#693]
When using LabelInfo.LayoutBelow only in the LabelInfo, the screen labels do not show.

When using LabelInfo.LayoutBelow | LabelInfo.LayoutCenter, it has the same behaviour as LabelInfo.LayoutCenter only.

JM

**Comment by mousebird** [comment]
Should be fixed now.
