### ISSUE TITLE
[Android] Cannot have layout engine ignoring labels

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#694]
If I understand the documentation right, when adding a label, letting LabelInfo.layoutImportance unset or setting it to Float.MAX_VALUE will make the layout engine "not controlling" the label.

I have tried:
- letting layoutImportance unset
- setting it to 0
- setting it to Float.MAX_VALUE
I still do have labels disapearing randomly (I assume by choice of the layout engine rather than randomly).

I have labels that are close (but I know they do not overlap) and I want them to be displayed... But I cannot.

**Comment by mousebird** [comment]
Thanks for the test case.
Bug is now fixed.
