### ISSUE TITLE
MaplyBillboard issue

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#695]
Hi (again, I know...),

I tried implementing some billboards following the example in the component tester.

The billboard is displayed in the globe but is not always visible according to my position:

<img width="577" alt="screen shot 2016-07-29 at 9 10 32 am" src="https://cloud.githubusercontent.com/assets/15698398/17249698/29734134-556f-11e6-99ff-8ff228524304.png">

<img width="573" alt="screen shot 2016-07-29 at 9 10 51 am" src="https://cloud.githubusercontent.com/assets/15698398/17249714/3f0d4594-556f-11e6-9ec1-e5970975a65d.png">

Am I missing something here?

Sebastien.

**Comment by mousebird** [comment]
You'll want to set the kMaplyDrawPriority to more than the base layer.  And you'll want to set kMaplyZBufferRead: @(NO) for the billboard.

**Comment by Sebboulnois** [comment]
Thank you, again. That worked!

**Comment by Sebboulnois** [comment]
So I am playing with the billboards and I put a billboard in a maplyShapeSphere with the following properties:

    UIImage *billImage = [UIImage imageNamed:@"BOWEE WP.png"];
    CGSize imageSize = CGSizeMake(0.0006, 0.000178);
    
    MaplyBillboard *bill = [[MaplyBillboard alloc] init];
    bill.center = MaplyCoordinate3dMake(melbourne.x, melbourne.y, [sphere1 height]*6371000);
    bill.selectable = false;
    bill.screenObj = [[MaplyScreenObject alloc] init];
    [bill.screenObj addImage:billImage color:[UIColor greenColor] size:imageSize];

The billboard appears this way:

<img width="577" alt="screen shot 2016-07-29 at 1 49 58 pm" src="https://cloud.githubusercontent.com/assets/15698398/17258163/9d21c3a2-5593-11e6-9d97-02b11e6952fd.png">

It seems to me that the property "center" actually refers to the origin of the billboard. The issue is that when I turn around my sphere, the billboard gets out of it because the position of the billboard is not set according to the center. Is there any way to fix that?

Sebastien.

**Comment by mousebird** [comment]
You can set your billboard up with a MaplyScreenObject.  It allows more control of the layout of text and images within a billboard.

**Comment by Sebboulnois** [comment]
I've been looking to this object. I don't really understand how I can move the origin point to the center of the image thanks to it.

Sebastien.

**Comment by mousebird** [comment]
Translate maybe?

**Comment by Sebboulnois** [comment]
That works! Thank you a lot. The flight-path is gonna be great now. :-)

**Comment by Sebboulnois** [comment]
I also would like to ask you a question about these billboards. I am loading a png that is around 30 kb for each of them. I can't even display 30 elements before I get a memory issue. I can see that my 30 billboards are instantiated but at display time, the memory goes crazy and the system crashes. 

Is this normal?

**Comment by Sebboulnois** [comment]
I have another question. How do you use screenObject addString? Nothing is visible on my globe with this kind of instruction:

UIFont *font = [UIFont fontWithName:@"Helvetica Neue" size:12];
[WPSpec addString:@"Test" font:font color:[UIColor colorWithRed:0.7 green:0.7 blue:0.7 alpha:1]];

Sebastien.

**Comment by mousebird** [comment]
I'll take a look at this when I get back.  It won't be for a few days.

**Comment by Sebboulnois** [comment]
Ok. Thank you very much.

**Comment by Sebboulnois** [comment]
Good afternoon,

I was wondering if you had some time to look at this issue.

Sebastien.

**Comment by mousebird** [comment]
Not yet, sorry.  I'm traveling again.  I will try to do this soon.

**Comment by Sebboulnois** [comment]
No worries. Have a safe trip.

**Comment by IOSDeveloperProgrammer** [comment]
@Sebboulnois  Hi
 How can i do and add multiple images based on user location view ?

**Comment by Sebboulnois** [comment]
Good morning @IOSDeveloperProgrammer ! I'm not sure about what you are asking. Do you want some images to appear at a specific location when the user "fly over" this location?

**Comment by mousebird** [comment]
They're asking this on their own issue too.  I'm not sure why they're spamming other peoples' issues.  I'd just ignore it.

**Comment by Sebboulnois** [comment]
If they already have an issue opened, I'll leave it to you then. Thank you for letting me know. :) Happy New Year @mousebird !

**Comment by IOSDeveloperProgrammer** [comment]
@Sebboulnois  Good morning.. I was asking about how to add multiple images ?

please check here : [https://github.com/mousebird/WhirlyGlobe/issues/820]

 I think you will understand my what am was asking

**Comment by mousebird** [comment]
Yes, but that has nothing to do with this old issue.  I'm discussing your question in your own issue.
