### ISSUE TITLE
[Android] SDK does not fully honor label's typeface

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#698]
I am trying to use a Roboto condensed bold type face (`Typeface.create("sans-serif-condensed", Typeface.BOLD)`) and it is not actually condensed.

This plus a few missing pixels on the right of glyphs when using outline makes me guess that the labels are rendered character by character.

This completely bypass the Android typographic goodness ;).

this is probably a substantial change and there are probably reason why this is so, but I think that there would be some merit in rendering labels as a whole.

**Comment by mousebird** [comment]
Is there a specific size where the cutoff is happening?
I'm doing these at 128 pixels and they're coming fine.
Though I couldn't say if the result is condensed or not.

**Comment by mousebird** [comment]
Is this still happening?

**Comment by mousebird** [comment]
I feel like this is fixed.  If not, reopen.
