### ISSUE TITLE
local tiles

### ISSUE THREAD

**Issue by ivangorelow** [mousebird/WhirlyGlobe#699]
'@Override
    protected void controlHasStarted() {
        // setup base layer tiles
        String cacheDirName = "stamen_watercolor";
        File cacheDir = new File(getActivity().getCacheDir(), cacheDirName);
        cacheDir.mkdir();'
        'RemoteTileSource remoteTileSource = new RemoteTileSource(new RemoteTileInfo("http://172.20.255.79/osm_tiles/", "png", 1, 18));
        remoteTileSource.setCacheDir(cacheDir);
        SphericalMercatorCoordSystem coordSystem = new SphericalMercatorCoordSystem();
        // globeControl is the controller when using MapDisplayType.Globe
        // mapControl is the controller when using MapDisplayType.Map
        QuadImageTileLayer baseLayer = new QuadImageTileLayer(mapControl, coordSystem, remoteTileSource);
        baseLayer.setImageDepth(1);
        baseLayer.setSingleLevelLoading(false);
        baseLayer.setUseTargetZoomLevel(false);
        baseLayer.setCoverPoles(true);
        baseLayer.setHandleEdges(true);
'
'
        // add layer and position
        mapControl.addLayer(baseLayer);
        mapControl.animatePositionGeo(-3.6704803, 40.5023056, 5, 1.0);
        mapControl.setAllowRotateGesture(true);
    }`

i try to use tiles in my local network, but I have only black window

**Comment by mousebird** [comment]
That URL doesn't look valid to me.  I'd think you'd need an http://

**Comment by ivangorelow** [comment]
with http it doesn't work

**Comment by mousebird** [comment]
There's a Stamen watercolor example in the AutoTester app.  Take a look at that.

**Comment by ivangorelow** [comment]
it's the same code, i  have changed only tile sources

**Comment by ivangorelow** [comment]
and it doesn't work in this way RemoteTileInfo("http://a.tile.openstreetmap.org/", "png", 0, 18)

**Comment by mousebird** [comment]
I'm not sure what error you're seeing.  Build and run the AutoTester to make sure the Stamen example works for you.  Then try directly changing the URL that example uses.  If that works, then compare your code to the Stamen example code.
