### ISSUE TITLE
Maply Vector tiles iOS - working example needed

### ISSUE THREAD

**Issue by dangustafsson** [mousebird/WhirlyGlobe#701]
I am evaluating using WhirlyGlobe in an app I'm currently developing. We need to be able to embed the map data in the shipping app. Have been looking at OSM data and it contains the data we need.

I have been going through the various samples and test apps but I have not been able to make the MapBox Vector tile data to render on the screen. I just get a black screen.

First I have tried the AutoTester. It has a test case for remote maps. It appears the style json file is no longer available. I have attempted to use the url of another style json file but the screen just renders black. There are no errors logged so I don't really know where to go next.

The goal is to use a local mbtiles file with vector tiles and styles exported from MapBox Studio. I have exported a mbtiles database and I'm trying to use it in the app but I really can't get anywhere. I'm at a point without any baseline. I don't know if my code is wrong, my mbtiles data or the style. If I had some kind of fully working example I should be able to start eliminating issues. 

This is also mentioned in https://github.com/mousebird/WhirlyGlobe/issues/641 & https://github.com/mousebird/WhirlyGlobe/issues/265 but there's not really any solutions posted.

**Comment by mousebird** [comment]
There is no good solution at present with Mapbox Studio.

I'm [pulling Mapbox GL Style Sheet support out of WhirlyGlobe-Maply](http://mousebirdconsulting.blogspot.com/2016/08/deprecating-mapbox-gl-style-sheet.html).  I don't think it's fully compatible with an open source stack.  Mapbox Vector Tiles will continue to be supported and encouraged.  You should only use MBTiles derived from your own data sources, not scraped from Mapbox.

So your best bet is the Mapbox GL API if you're intent on using Mapbox Studio to generate the styles.

In a few weeks we'll have Styled Layer Descriptor (SLD) support which will work with tools like QGIS.  Not as slick a solution, but more compatible with open source values.

**Comment by dangustafsson** [comment]
The GL style is not a priority. Nor is using anything Mapbox.

The goal is to use offline vector maps in the application. As a first attempt I have downloaded shapefiles from geofabrik.de. I was initially trying to use your osm-to-maply tool but it requires tile mill which has been deprecated in favour of Mapbox Studio - Hence why I ended up with Mapbox Studio mbtiles.

What would be the best approach going forward? I'm also interested in being able to show a 3d representation. Outdoors kind of app so elevation is one of the most important parts.

thanks!

**Comment by mousebird** [comment]
Okay, that's workable, then.

The Maply Vector Format is deprecated in favor of Mapbox Vector Tiles.
Mapbox Vector Tiles in an MBTiles file should load fine on iOS and Android at present, it's just the styling that's an issue.

You could style with custom code.  Not the best solution.
You can style with Mapnik XML.  That's difficult to write now that TileMill has been deprecated.
In a few weeks you'll be able to style with SLD, which you can use QGIS to build.

We're setting up the SLD solution for a client now.  I think we'll have a decent test case in a couple of weeks.

In the mean time you could use the Simple styling code to just get things working.  It shows points, lines and areals to verify that your data loads correctly.

**Comment by dangustafsson** [comment]
Thank you for entertaining my ignorance. I'm struggling to understand the source data and the various forms of mbtiles and what is required of the backing data to make the map work. This is all new to me. The penny is dropping slowly :)

These seems to be multiple mbtiles formats. Let's ignore the rasterised image tiles. I have been trying to convert my own data into mbtiles format for whirlyglobe. I've tried 3 different methods. First from Mapbox Studio the application. Second I've downloaded ready converted mbtiles files from osm2vectortiles.org. And finally I've tried to roll my own using tilemaker.

`		// Image tiles - works with geography but not with my own .mbtiles
		MaplyMBTileSource *tileSource = [[MaplyMBTileSource alloc] initWithMBTiles:@"ire"];
		MaplyQuadImageTilesLayer *layer = [[MaplyQuadImageTilesLayer alloc] initWithCoordSystem:tileSource.coordSys tileSource:tileSource];
		layer.handleEdges = YES;
		layer.coverPoles = YES;
		layer.requireElev = false;
		layer.waitLoad = false;
		layer.drawPriority = 0;
		layer.singleLevelLoading = false;
		[_currentMapController addLayer:layer];
		
		
		// from http://mousebirdconsulting.blogspot.ie/2014/03/vector-maps-introduction.html
		// Just renders a black screen for all .mbtiles files
		NSString *mapFile = [[NSBundle mainBundle] pathForResource:@"ire" ofType:@"mbtiles"];
		MaplyVectorTiles *vecTiles = [[MaplyVectorTiles alloc] initWithDatabase:mapFile viewC:_currentMapController];
		MaplyQuadPagingLayer *layer = [[MaplyQuadPagingLayer alloc] initWithCoordSystem:[[MaplySphericalMercator alloc] initWebStandard] delegate:vecTiles];
		layer.numSimultaneousFetches = 8;
		[_currentMapController addLayer:layer];
		
		
		// This does work somewhat with a .mbtiles file downloaded from http://osm2vectortiles.org/ but not with
		// mbtiles file generated from Mapbox studio or tilemaker
		NSString *mapFile = [[NSBundle mainBundle] pathForResource:@"ire" ofType:@"mbtiles"];
		NSString *styleFile = [[NSBundle mainBundle] pathForResource:@"osm-bright" ofType:@"xml"];
		MapnikStyleSet *style = [[MapnikStyleSet alloc] initForViewC:_currentMapController];
		[style loadXmlFile:styleFile];
		[style generateStyles];
		
		MaplyMBTileSource *tileSource = [[MaplyMBTileSource alloc] initWithMBTiles:mapFile];
		MaplyMapnikVectorTiles *vecTiles = [[MaplyMapnikVectorTiles alloc] initWithMBTiles:tileSource style:style viewC:_currentMapController];
		
		MaplyQuadPagingLayer *pageLayer = [[MaplyQuadPagingLayer alloc] initWithCoordSystem:[[MaplySphericalMercator alloc] initWebStandard] delegate:vecTiles];
		pageLayer.numSimultaneousFetches = 6;
		pageLayer.flipY = false;
		pageLayer.importance = 1024*1024*2;
		pageLayer.useTargetZoomLevel = true;
		pageLayer.singleLevelLoading = true;
		
		[_currentMapController addLayer:pageLayer];`

The first snippet is for image tiles so doesn't apply. But the other 2 options should probably work. But I'm not sure what mbtiles format works with which methods. 
The best result so far (in that _something_ is rendered) have been using the osm2vectortiles tiles. But there is clearly something missing (screenshot).

<img width="432" alt="screen shot 2016-08-05 at 08 51 43" src="https://cloud.githubusercontent.com/assets/14436702/17430263/052588d8-5aeb-11e6-8ef6-61f954c989f0.png">

So I know the problem is my data but I don't know what I'm doing wrong.

**Comment by nickplee** [comment]
@dangustafsson Did you get anywhere with this?  I'm experiencing the exact same behavior.

**Comment by mousebird** [comment]
@nickplee If I'm reading Mapbox's terms correctly then their data in MBTiles files outside of Mapbox GL is completely off limits.  Luckily, there are other sources.  Also, vector tiles are problematic on the globe at low zoom levels.  They can work reasonably well once you get past the low levels.

@dangustafsson One thing I would try is using the MaplyVectorStyleSimpleGenerator instead of one of the style sheet based styles.  That way you can at least see your data and verify that it's coming in correctly.  Once you get things showing up like you expect with the Simple style, then you can look at a more complex style.

**Comment by dangustafsson** [comment]
Where can I find the MaplyVectorStyleSimpleGenerator? It doesn't seem to be anywhere in this repository. I've searched all of GitHub.

**Comment by radumvlad** [comment]
Did you guys manage to work this out? I'm still having kind of the same issues. I'll post if i succeed into actually doing this.

**Comment by nickplee** [comment]
@radumvlad I was able to achieve my desired ends by using a raster base layer (in my case, a satellite image layer) underneath the vector map.  With some massaging of the style XML, looks pretty good.

**Comment by mousebird** [comment]
The MaplyVectorStyleSimpleGenerator is in MaplyVectorStyleSimple in the develop_2_4_1 branch.

**Comment by dangustafsson** [comment]
Ok, so I have checked out the develop branch in my project and using the MaplyVectorStyleSimpleGenerator all my mbtiles files actually work! This is great!
I will keep working away with the MaplyVectorStyleSimpleGenerator for the time being. 

For anyone else doing this, you need to add the WhirlyGlobeMaplyComponent framework to the Embedded Binaries section. It's not a library anymore. Then this is the code I used

`MaplyVectorStyleSimpleGenerator *simpleStyle = [[MaplyVectorStyleSimpleGenerator alloc] initWithViewC:_currentMapController];
		MaplyMBTileSource *tileSource = [[MaplyMBTileSource alloc] initWithMBTiles:@"ireland"];
		MapboxVectorTiles *vecTiles = [[MapboxVectorTiles alloc] initWithMBTiles:tileSource style:simpleStyle viewC:_currentMapController];
		MaplyQuadPagingLayer *layer = [[MaplyQuadPagingLayer alloc] initWithCoordSystem:tileSource.coordSys delegate:vecTiles];
		layer.flipY = false;
		[_currentMapController addLayer:layer];`

**Comment by mousebird** [comment]
I'm glad that's working!

**Comment by o15a3d4l11s2** [comment]
I am currently testing the offline mbtiles functionality, but the maps rendered look really strange:
![img_6519](https://cloud.githubusercontent.com/assets/934385/19328915/be02aa92-90de-11e6-9144-1d4aefe5e3f1.PNG)

I am using the ready VectorMBTilesTestCase from develop_2_4_1 branch. Is there something that I am doing wrong?

**Comment by mousebird** [comment]
So that's all the labels you're loading showing up all at once.  The VectorMBTilesTestCase uses a MaplyVectorStyleSimpleGenerator.  The simple styles are supposed to show everything.

If you want to do something more interesting with your data set you need to impose a more interesting style.  One way, for simple data sets, is to subclass MaplyVectorStyleSimpleGenerator and go from there.  Another way is to use a Mapnik XML file.  There's also Styled Layer Descriptor if you're more of a GIS shop.
