### ISSUE TITLE
How to add the Tiles to Globe?

### ISSUE THREAD

**Issue by bintu1234** [mousebird/WhirlyGlobe#703]
HI I am new to WhirlyGlobe,Can any body please tell me how to add Tiles to the globe.I just follow the mapQuest and Mapbox but both are showing Black Screen. where i am missing. bellow is my code,
` theViewC = [[WhirlyGlobeViewController alloc] init];
    [self.view addSubview:theViewC.view];
    theViewC.view.frame = self.view.bounds;
    [self addChildViewController:theViewC];
    
    WhirlyGlobeViewController *globeViewC = nil;
    MaplyViewController *mapViewC = nil;
    if ([theViewC isKindOfClass:[WhirlyGlobeViewController class]])
        globeViewC = (WhirlyGlobeViewController *)theViewC;
    else
        mapViewC = (MaplyViewController *)theViewC;
    
    
    // we want a black background for a globe, a white background for a map.
    theViewC.clearColor = (globeViewC != nil) ? [UIColor blackColor] : [UIColor whiteColor];
    
    // and thirty fps if we can get it ­ change this to 3 if you find your app is struggling
    theViewC.frameInterval = 2;
    
    // add the capability to use the local tiles or remote tiles
    bool useLocalTiles = false;
    
    // we'll need this layer in a second
    MaplyQuadImageTilesLayer *layer;
    MaplyMBTileSource *tileSource =
    [[MaplyMBTileSource alloc] initWithMBTiles:@"geography-­class_medres"];
    
    if (useLocalTiles)
    {
        MaplyMBTileSource *tileSource =
        [[MaplyMBTileSource alloc] initWithMBTiles:@"geography­-class_medres"];
        layer = [[MaplyQuadImageTilesLayer alloc]
                 initWithCoordSystem:tileSource.coordSys tileSource:tileSource];
    } else {
        // Because this is a remote tile set, we'll want a cache directory
        NSString *baseCacheDir =
        [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES)
         objectAtIndex:0];
        NSString *aerialTilesCacheDir = [NSString stringWithFormat:@"%@/osmtiles/",
                                         baseCacheDir];
        int maxZoom = 18;
        MaplyRemoteTileSource *tileSource =
        [[MaplyRemoteTileSource alloc]
         initWithBaseURL:@" https://api.mapbox.com/v4/mapbox.dark/-76.9,38.9,5/400x200@2x?access_token=pk.eyJ1IjoiYmludHUiLCJhIjoiY2lycTQyM2pkMDBhdGhwbTFhdzBncG4xNyJ9.BEfawwOVtJshIsC0JGN8-Q"
         ext:@"png" minZoom:0 maxZoom:maxZoom];
        tileSource.cacheDir = aerialTilesCacheDir;
        layer = [[MaplyQuadImageTilesLayer alloc]
                 initWithCoordSystem:tileSource.coordSys tileSource:tileSource];
        [theViewC addLayer:layer];
        
      
    }

`
the above url for MapBox.Where i am missing i tried  with the MapQuest Library also But Same Result.Thnaks in advance.

**Comment by mousebird** [comment]
Mapquest is no longer offering their layers for free.  I haven't pulled all the examples for that yet.

In the AutoTester you can find a CartoDB light example.  Try switching to that.

As for the Geography Class example, that will work.  I see you're creating the tileSource twice.  Make sure you have the mbtiles file in your bundle.
