### ISSUE TITLE
[Swift] Got error " GL Error: 1281 - Texture::createInGL() glTexImage2D() "

### ISSUE THREAD

**Issue by Takuro-Ito** [mousebird/WhirlyGlobe#705]
Hi, I've been developing a project using WhirlyGlobe that is very helpful.
When I implement MaplyAtmospehere,  the globe doesn't have atmosphere in myApp and I got ` GL Error: 1281 - Texture::createInGL() glTexImage2D() ` error from `Pods/Pods/WhirlyGlobe/Lib/Texture.mm`. 

I guess its cause is that Swift cannot read .mm file but I don't know how to deal with it. 
I have to use other Library written in Swift, so I can't change Swift to Obj-C.(If there is a solution using library in Swift and this issue on OpenGL won't fixed, I would do that)
How can I fix this issue on OpenGL?

`WhirlyGlobe 2.4` installed by Cocoapods.(also tried 2.4.1)
`import WhirlyGlobe` in myViewController.swift (I didn't write in bridging-header.h because some file not found.)

**Comment by mousebird** [comment]
I don't think that's a Swift issue.

I'd recommend using the [Podspec](https://github.com/mousebird/WhirlyGlobe/blob/develop_2_4_1/WhirlyGlobe.podspec) in the develop_2_4_1 branch if you're not already.

**Comment by Takuro-Ito** [comment]
Could you tell me how to add and install to my existing project?

**Comment by mousebird** [comment]
If you're using Cocoapods you can specify a Podspec from a specific URL.  The Cocoapods documentation discusses that.  Just use the [Podspec at this URL](https://raw.githubusercontent.com/mousebird/WhirlyGlobe/develop_2_4_1/WhirlyGlobe.podspec).

**Comment by Takuro-Ito** [comment]
I did `pod update` after specifying the Podspec but now atmosphere has gone.
I am really trying to figure it out from this repo, Do you have any idea or notice for showing atmosphere in Swift?

**Comment by mousebird** [comment]
There's an atmosphere test in the AutoTester app.  Look for StarsSunTestCase.swift.

**Comment by Takuro-Ito** [comment]
Thank you for the reply. I wrote the exact same code of functions with StarsSunTestCase.swift but still can't solve this issue...
I guess I miss something related to C++ file or OpenGL?

Are there any requirements for displaying atmosphere?

WHAT I DID SO FAR
`pod update` by specifying podspec
`import WhirlyGlobe` in ViewController.swift (not *-Bridging-Header.h since Xcode says file not found)
Using `DigitalGlobeMap` 

Here is  code. Could you please tell me what is missing?
```
class ViewController: UIViewController, WhirlyGlobeViewControllerDelegate {
...
}
```

```
  var baseViewC: MaplyBaseViewController?
  var globeViewC: WhirlyGlobeViewController?
```

```
func createGlobe() {
    globeViewC = WhirlyGlobeViewController()
    globeViewC?.delegate = self
    baseViewC = globeViewC
    self.view.addSubview((baseViewC?.view)!)
    baseViewC?.view.frame = self.view.bounds
    self.addChildViewController(baseViewC!)
}
```

```
  func addDesitalGlobeLayer() {
    globeViewC!.frameInterval = 3
    
    let baseURL = "https://api.tiles.mapbox.com/v4/\(MAP_ID)/{z}/{x}/{y}.png?access_token=\(MAP_ACCESS_TOKEN)"
    let tileSource = MaplyRemoteTileSource(baseURL: baseURL, ext: nil, minZoom: 1, maxZoom: 22)
    let baseCacheDir = NSSearchPathForDirectoriesInDomains(.CachesDirectory, .UserDomainMask, true)[0] as String
    tileSource!.cacheDir = "\(baseCacheDir)/\(MAP_ID)/"
    
    var imageLayer = MaplyQuadImageTilesLayer()
    imageLayer = MaplyQuadImageTilesLayer(coordSystem: tileSource!.coordSys, tileSource: tileSource!)!
    imageLayer.drawPriority = kMaplyImageLayerDrawPriorityDefault + 100
    imageLayer.importanceScale = 1.0
    globeViewC!.addLayer(imageLayer)
  }
```

```
  func addSunLight() {
    var atmosObj = MaplyAtmosphere()
    globeViewC!.clearColor = UIColor.blackColor()
    
    let sun = MaplySun(date: NSDate())
    let sunLight = sun.makeLight()
    
    globeViewC!.clearLights()
    globeViewC!.addLight(sunLight)
    
     /*
     let bill = MaplyBillboard()
     let centerGeo = sun.asPosition()
     .
     .

     globeVC.addBillboards([billMoon],
     desc: [
     kMaplyBillboardOrient: kMaplyBillboardOrientEye,
     kMaplyDrawPriority: NSNumber(int: kMaplyMoonDrawPriorityDefault)
     ],
     mode: MaplyThreadMode.Any)
     */
    
    
    // And some atmosphere, because the iDevice fill rate is just too fast
    atmosObj = MaplyAtmosphere.init(viewC: globeViewC!)!

    atmosObj.setWavelengthRed(0.650, green: 0.570, blue: 0.47)
    atmosObj.setSunPosition(sun.getDirection())
  }
```

**Comment by mousebird** [comment]
It's not a C++ issues.  The test case I pointed you to is in Swift, after all.

I don't really know what the problem is.  What is the error again?

**Comment by Takuro-Ito** [comment]
This is strange... Now there is no error.
The only thing I can't do is atmosphere. Starts, sun and moon are normally displayed.

Would you like to maintain WhirlyGlobeSwiftTester in develop_2_4_1 because Xcode says AFNetworking is not found and then linker command error after installing it and commenting out code related to AFNetworking?
Then I'd modify the WhirlyGlobeSwiftTester Project to mine. I spent almost a week to try to figure this issue out.

**Comment by jmnavarro** [comment]
I'm afraid the WhirlyGlobeSwiftTester is deprecated. The preferred way to implement tests and sample code in using the AutoTester (it supports both Obj-C and Swift code)

**Comment by Takuro-Ito** [comment]
All right, I'd use AutoTester for my project and keep trying to figure out the cause.
If any updates, let me know in this thread.
Thanks a lot for very quick replies!

**Comment by Takuro-Ito** [comment]
Finally, I figured out what was wrong!

The only thing I did mess was that I defined `var atmosObj = MaplyAtmosphere()` in `func addSun(globeVC: WhirlyGlobeViewController)`
I thought `var atmosObj = MaplyAtmosphere()` was ok inside of function or not, but this tiny change was affected.why?

HERE IS A SOLUTION
1. Use `WhirlyGlobe 2.4.1` ( `pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe.git', :branch => 'develop_2_4_1' `)
2. make sure that `atmosObj` is used as **global variable**
like this
```
  var atmosObj = MaplyAtmosphere()
	
	func addSun(globeVC: WhirlyGlobeViewController) {
        ....
    }
```

**Comment by jmnavarro** [comment]
You're right, and it makes totally sense.

The atmosphere object has a (weak) reference to the view controller, but nobody is retaining the atmosphere object. Making it a property fixes the mess.

Maybe we can add some defensive checking to raise a more descriptive error

Congrats for figuring it out!
