### ISSUE TITLE
[iOS] - MaplyMovingScreenMarker isn't appearing on screen

### ISSUE THREAD

**Issue by dangustafsson** [mousebird/WhirlyGlobe#706]
I'm adding a user position marker to the globe view. I want to be able to animate the user position using the new MaplyMovingScreenMarker instead of removing and re-adding the marker for each location update.
But when using MaplyMovingScreenMarker the annotation does not show up on the screen.

This snippet is working and is updating as the user is moving along.
`- (void) updatePositionMarker:(CLLocation *) location {
	
	if (!_userPositionMarker) {
		_userPositionMarker = [[MaplyScreenMarker alloc] init];
		_userPositionMarker.image = [UIImage imageNamed:@"arrow.png"];
		_userPositionMarker.size = CGSizeMake(32, 32);
		_userPositionMarker.layoutImportance = MAXFLOAT;
		_userPositionMarker.selectable = NO;
	}
	
	if (_userPositionMarkerComponentObject) {
		[_currentMapController removeObject:_userPositionMarkerComponentObject];
	}

	_userPositionMarker.loc = MaplyCoordinateMakeWithDegrees(location.coordinate.longitude, location.coordinate.latitude);
	self.userPositionMarkerComponentObject = [_currentMapController addScreenMarkers:@[_userPositionMarker] desc:nil mode:MaplyThreadCurrent];
}`

This is not working. I have not been able to put a MaplyMovingScreenMarker onto the screen in any way shape or form. Even using the above method and just replacing 'MaplyScreenMarker' with 'MaplyMovingScreenMarker' causes the arrow not to appear on the screen.

`- (void) updatePositionMarker:(CLLocation *) location {
	
	if (!_userPositionMarker) {
		
		_userPositionMarker = [[MaplyMovingScreenMarker alloc] init];
		_userPositionMarker.image = [UIImage imageNamed:@"arrow.png"];
		_userPositionMarker.size = CGSizeMake(32, 32);
		_userPositionMarker.layoutImportance = MAXFLOAT;
		_userPositionMarker.selectable = NO;
		_userPositionMarker.duration = 1.0;
		_userPositionMarker.loc = MaplyCoordinateMakeWithDegrees(location.coordinate.longitude, location.coordinate.latitude);
		self.userPositionMarkerComponentObject = [_currentMapController addScreenMarkers:@[_userPositionMarker] desc:nil mode:MaplyThreadCurrent];
	}
	else {
		_userPositionMarker.endLoc = MaplyCoordinateMakeWithDegrees(location.coordinate.longitude, location.coordinate.latitude);
	}
}`

Is there a different way of doing this or is this perhaps not working?
I'm on the current development branch btw.

**Comment by mousebird** [comment]
I think you need to set the endLoc before you call addScreenMarkers:

**Comment by dangustafsson** [comment]
Ok, I figured it out. I thought you could add a marker and then continuously update it. Much like setting the frame or center of a UIView. 

Here is a working code snippet with animation should anyone else need it.

```
- (void) updatePositionMarker:(CLLocation *) location {
	
	if (_userPositionMarkerComponentObject) {
		[_currentMapController removeObject:_userPositionMarkerComponentObject];
	}
	
	if (!_userPositionMarker) {
		self.userPositionMarker = [[MaplyMovingScreenMarker alloc] init];
		_userPositionMarker.image = [UIImage imageNamed:@"arrow.png"];
		_userPositionMarker.size = CGSizeMake(32, 32);
		_userPositionMarker.layoutImportance = MAXFLOAT;
		_userPositionMarker.selectable = NO;
	}
	
	CLLocation *lastLocation = _lastLocation ?: location;
	NSTimeInterval duration = [location.timestamp timeIntervalSinceDate:_lastLocation.timestamp];
	self.lastLocation = location;
	
	_userPositionMarker.duration = duration;
	_userPositionMarker.loc = MaplyCoordinateMakeWithDegrees(lastLocation.coordinate.longitude, lastLocation.coordinate.latitude);
	_userPositionMarker.endLoc = MaplyCoordinateMakeWithDegrees(location.coordinate.longitude, location.coordinate.latitude);
	self.userPositionMarkerComponentObject = [_currentMapController addScreenMarkers:@[_userPositionMarker] desc:@{}];
}
```
