### ISSUE TITLE
[Android]Geo-oriented ScreenMarkers

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#707]
I have used screen markers intensively and just realized that they were not rotating when the map orientation changes (they keep their orientation relative to the screen).

Is there a way to have them rotating with the map instead ? (some magic in VertexAttributes ? or somewhere) ?

I understand that Stikers would do that, but I really need the fixed size of the markers.

**Comment by mousebird** [comment]
As near as I can tell the rotation is working as designed on the globe.
ScreenMarkers will rotate from due north on the globe.

Is this problem on the map?

**Comment by mousebird** [comment]
It seems to be working on the map too.
Now there is a bad case where rotation = 0.0.  It can't tell between that and when you don't want to rotate.

My solution is to set it to 1e-10 or something similar.

**Comment by jmcazaux** [comment]
Hi Steve, this did the trick.

Thanks
