### ISSUE TITLE
MaplyShapeExtruded - wrong placing on flat map(iOS)

### ISSUE THREAD

**Issue by radumvlad** [mousebird/WhirlyGlobe#708]
I am trying to build a map that would programatically display some zones with a specific colour. The shapes are polygons with no specific details and they are constructed with a variable number of coordinates. 
For this I considered using a `MaplyShapeExtruded` object that would be added to the map with the `- (MaplyComponentObject *)addShapes:(NSArray *)shapes desc:(NSDictionary *)desc` method. I managed to align all the parameters to have a pretty good result in displaying the shape, but it seems its position on the map is wrong. 

Sample code: 

 ```
       var areasShapes : [MaplyShapeExtruded] = []
        let areaGeometry = [[26.4, 46.2], [26.4, 46.6], [26.8, 46.6]]
        var arrayData : [Double] = []
        
        let nrCoords = areaGeometry.count
        
        for item in areaGeometry {
            
            arrayData.append(Double(DegToRad(item[0])))
            arrayData.append(Double(DegToRad(item[1])))
        }
        
        let areaShape =  MaplyShapeExtruded(outline: &arrayData, numCoordPairs: Int32(nrCoords))
        areaShape.thickness = 0.0005
        areaShape.height = 1.0/6371000
        areaShape.scale = 1.0
        
        areasShapes.append(areaShape)
        
        self.maplyVC?.addShapes(areasShapes, desc: [
            kMaplyColor: UIColor(red: 0.0, green: 0.2, blue: 0.0, alpha: 0.75)])

```

In the code above I am trying to display a triangle with a green colour with alpha 0.75 in Romania(somewhere in the middle of the country). Instead the shape is displayed somewhere in Bulgaria, very close to Greece.

<img width="284" alt="screen shot 2016-08-16 at 00 59 09" src="https://cloud.githubusercontent.com/assets/5338134/17683640/b4371314-634c-11e6-83f7-e0690c3684e8.png">

**Comment by mousebird** [comment]
Extruded shapes are best in 3D.
Maybe this would work better with MaplyVectorObject and addVectors:  ?

**Comment by radumvlad** [comment]
I will try to implement them with `MaplyVectorObject` then, with the method `- (nonnull instancetype)initWithLineString:(NSArray *__nonnull)coords attributes:(NSDictionary *__nullable)attr;`, that seems to suit the best for me. Thank you!

**Comment by radumvlad** [comment]
I tried doing the same thing with MaplyVectorObject and this is what I get:

* Sample code: 

```
var areasVectors : [MaplyVectorObject] = []
let areaGeometry = [[26.4, 46.2], [26.4, 46.6], [26.8, 46.6]]
var arrayData : [Double] = []

for item in areaGeometry {

    arrayData.append(item[0])
    arrayData.append(item[1])
}

let areaVector =  MaplyVectorObject.init(lineString: arrayData, attributes: nil)

areasVectors.append(areaVector)

let options = [kMaplyColor: UIColor(red: 0.0, green: 0.2, blue: 0.0, alpha: 0.75),
               kMaplyFilled : true,
               kMaplyDrawPriority : 10000,
               kMaplySelectable : true]

self.maplyVC?.addVectors(areasVectors, desc: options)
```

*result(ignore the red cross, that's another image) : 

<img width="286" alt="screen shot 2016-08-16 at 01 50 59" src="https://cloud.githubusercontent.com/assets/5338134/17684480/f903cf30-6353-11e6-9509-8bc2a4e9b0a8.png">

**Comment by mousebird** [comment]
Input values would need to be in radians, I think.

**Comment by mousebird** [comment]
No wait, my mistake.  It's doing the conversion to radians.

**Comment by radumvlad** [comment]
I managed to do it by generating a geoJSON from the points and it worked. However the issue is probably still there. It's up to you if you want this as closed or open :). 

Thanks a lot and keep up the good work!

**Comment by mousebird** [comment]
Ah, I bet lat/lon where switched.
