### ISSUE TITLE
Polygon fill and border color

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [mousebird/WhirlyGlobe#713]
Is it possible to have polygons/areals with a seperate fill and border color?  

I'm adding vectors loaded from a shapefile to a flat `MaplyViewController` and defining the description dictionary like so:

```
let vectorProperties =
                [kMaplyColor: UIColor.whiteColor(),
                 kMaplyVecWidth: 2.0,
                 kMaplyFilled: true,
                 kMaplyBackgroundColor: UIColor.blackColor()]
```

I've also tried using a 1x1 px texture but in both cases `kMaplyFilled: true` doesn't render the border, just the fill.

**Comment by mousebird** [comment]
Just add them twice.  The second one with kMaplyFilled set to false and give it a kMaplyDrawPriority of one more.

**Comment by ChrisLowe-Takor** [comment]
Thanks, that did the trick. 

Any idea why some polys aren't being filled?  It looks like they are only the ones that cover a large area .

![2016-08-26 15 09 17](https://cloud.githubusercontent.com/assets/13913685/17997193/9f68b5c2-6b9f-11e6-93a6-f3465883447a.png)

**Comment by mousebird** [comment]
Could be draw priority.  Try setting kMaplyDrawPriority explicitly to something very large and see what you get.
