### ISSUE TITLE
Screen Markers do not respect Z buffer between each others

### ISSUE THREAD

**Issue by castics** [mousebird/WhirlyGlobe#715]
Hello, I'm playing with WhirlyGlobe and screen markers (2d) and have an issue that they do not respect their Z-coordinate between each others and are rendered by the wrong order, so one marker that is in behind in 3d scene is rendered on top of a marker that is in front in 3d scene. I understand that it's 2d and they follow "draw priority", but is there any way to force them use their "geo-location" on "3d scene" in order to calculate it's draw priority and to be rendered in a right order?

**Comment by mousebird** [comment]
Screen markers are always going to sit right in front of the 3D geometry.  Their location is calculated in 2D and then rendered from there.  In effect, this puts them right on the near clipping plane.

You can have them intermingle with the rest of the geometry using kMaplyDrawPriority, but you must set the screenObjectDrawPriorityOffset to 0.

True 3D interaction would require a change in the Screen Object shaders.
