### ISSUE TITLE
[android]MarkerProperties userObject sometimes causes selection to fail

### ISSUE THREAD

**Issue by hallahan** [mousebird/WhirlyGlobe#720]
Sometimes, when I assign an object to `MarkerProperties#userObject`, `userDidSelect` stops working.

https://github.com/mousebird/AndroidTutorialProject/blob/b911ddbf24c0eabecf02f3b120fa9ef790fea3cf/app/src/main/java/io/theoutpost/helloearth/HelloMapFragment.java#L158

**Comment by mousebird** [comment]
José, can you try and replicate this one?

**Comment by jmnavarro** [comment]
I can't replicate it. Added test on [branch issue/720](https://github.com/mousebird/WhirlyGlobe/compare/develop_2_4_1...issue/720)
