### ISSUE TITLE
setDrawPriority method does not work in MaplyQuadPagingLayer

### ISSUE THREAD

**Issue by sunhongyue4500** [mousebird/WhirlyGlobe#724]
hello, I have two MaplyQuadPagingLayer. When I set the same settings.markerImportance equals MAXFLOAT,  and  different drawPriority. No matter what drawPriority I set, two layers's markers  do not draw in  right order. How can I fix it. 
Thanks a lot.
Sun Hongyi

**Comment by mousebird** [comment]
So this is a vector tile style?
Because markerImportance is in MaplyVectorStyleSettings

**Comment by sunhongyue4500** [comment]
Yes. I have a try again. Thank you.
