### ISSUE TITLE
How can i fill the place with white color?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#725]
Hi,
    My local data is not temp data(like 'world_2646e3.mbtiles'), instead of myself data named "GRTerrain.mbtiles". My question is :
    When I load the data, I found poles is black. so I set by "layer.coverPoles = true;". then you can see the result png.  How can i fill the place with white color?
    and I found My data "GeoCoord..." is  -180,-81  not  -180, -85.0511 , associated this?
    What can I do for this ? Thanks!!!

load png:
![f74d3f1c-3f27-4910-9780-56e815cd3ab5](https://cloud.githubusercontent.com/assets/13251217/18467706/9d9c5db0-79d3-11e6-8178-4289b01540de.png)

result png:
![default](https://cloud.githubusercontent.com/assets/13251217/18467539/ea83ff26-79d2-11e6-9c9a-6430e79014b0.png)

**Comment by marychenyuan** [comment]
[supplement]
and set :
    layer.northPoleColor = [UIColor whiteColor];
    layer.southPoleColor = [UIColor whiteColor];

**Comment by marychenyuan** [comment]
or How can i catch the black zone and replace a default black picture...

All in all, my question is how can i cover the black zone?!

**Comment by mousebird** [comment]
If the black is in the data set itself then it's very hard to replace.  You would need to modify the images as they come in or modify the shader to look for that color.

If you have a base layer underneath this you could make it transparent and let the base layer show through.

The best solution is to just fix it in the source data, though.  Get rid of that black bar in your source.

**Comment by marychenyuan** [comment]
I see.  Thank you !
