### ISSUE TITLE
RemoteTileSource caching issue

### ISSUE THREAD

**Issue by bryanheitman** [mousebird/WhirlyGlobe#726]
If a image is downloaded that is not really a image, such as text then it's written to the cache file corrupting the cache. This is critical because so long as this bad data is in the cache if the temporary network issue is resolved it may prevent further tiles from downloading when they do become available. 

My request is to simply not enter something that is not a image into the cache w/o causing any extra cpu cycles doing checking.

This frequently happens when clients connect to wifi networks with proxies such as in airplanes, hotels, public spaces.

**Comment by mousebird** [comment]
As a further note, it only happens when the request return a valid HTTP code.
What we need to do is not save the image if it doesn't decode into an image.

**Comment by mousebird** [comment]
Recently found this problem for multiplex tile sources.  Make sure that propagated back from ImageryPro.

**Comment by bryanheitman** [comment]
Thanks

The duplicate objects issue is still ongoing will have to get you hopefully a test case late this week.

-Bryan

**Comment by mousebird** [comment]
Should be fixed now.

**Comment by bryanheitman** [comment]
Thank you
