### ISSUE TITLE
[Android] Background colour.

### ISSUE THREAD

**Issue by geftimov** [mousebird/WhirlyGlobe#732]
I extended the GlobeMapFragment.
I want to change the BLACK colour in the background.
 
My code looks like this: 
```java
@Override
protected void preControlCreated() {
   mapSettings.clearColor = Color.RED;
}
```

How to properly change the background colour of the map?

**Comment by mousebird** [comment]
If you subclass the GlobeMapController you can modify the globeSettings or mapSettings.
The Settings contain a clearColor and that is the best place to set it on startup.

**Comment by mousebird** [comment]
Turns out this was a bug, now fixed.
