### ISSUE TITLE
How to run the carto_vector_dice command line tool?

### ISSUE THREAD

**Issue by thejeraldo** [mousebird/WhirlyGlobe#733]
I am trying to run the Xcode project. However, the project cannot find the boost files I think.
It says boost/filesystem.hpp file not found. Are there any other prerequisites for this? I have cloned the WhirlyGlobe project along with submodules.

**Comment by mousebird** [comment]
We took the boost dependency out of WhirlyGlobe-Maply but that old tool still uses it.

My suggestion would be to not use carto_vector_dice.  Better to move to vector tiles.
