### ISSUE TITLE
Swift 3 support? 

### ISSUE THREAD

**Issue by deanezra** [mousebird/WhirlyGlobe#734]
is there a version of WhirlyGlobe that works with swift 3?

**Comment by jmnavarro** [comment]
The toolkit code is Objective-C++ so the bridge should work with any version of Swift. However, we didn't try yet

**Comment by mousebird** [comment]
I let it auto convert the other day and then cleared up a few stray problems in some of the Pods the AutoTester uses.  When I get a chance I'll clean that up and check it in.

**Comment by mousebird** [comment]
In converting the AutoTester I find the toolkit works just fine.  Are you running into any Swift 3.0 issues with the toolkit?

The AutoTester itself needs to change a bit, but there are dependent projects and such.  I'll get around to it soon.

**Comment by deanezra** [comment]
hi @mousebird, Sorry for delay in responding, I havn't had a chance to convert the ios swift 2.2 project yet. Been busy troubleshooting some other map issues.

**Comment by mousebird** [comment]
We're converting the AutoTester to Swift 3.0 now.  But the toolkit itself is fine with Swift 3.0.

**Comment by deanezra** [comment]
@mousebird Yes, I can confirm that the toolkit is working in my swift 3 based project (I am using the swift3 branch of whirlyglobe).

**Comment by mousebird** [comment]
We've merged that into develop_2_4_1 now too.
