### ISSUE TITLE
App store rejection

### ISSUE THREAD

**Issue by hneil** [mousebird/WhirlyGlobe#735]
Apple rejected a new app we had developed using the WhirlyGlobe SDK 2.4 because it uses methods called "start" and "shutdown".  Apple says this violates section 2.5 of their policy not to access non-public APIs.  Despite an extended conversation with Apple, they refused to approve the app until we renamed all occurrences of "start:" and "shutdown:" in the WhirlyGlobe SDK.  You might want to consider changing the names in version 2.4.1.

**Comment by mousebird** [comment]
Oh good grief.  Do you have a contact at Apple?  This is getting stupid.

**Comment by mousebird** [comment]
Eh, who am I kidding?  That won't help at all.

So where all did you need to rename start and shutdown?  The last time this happened I just append "2".

**Comment by hneil** [comment]
The back and forth was by email with the app store review board on appreview@apple.com after they rejected the app.  I thought they may have granted my appeal, because they put the app back into review, but then they rejected it again for the same reason.  I did a search with Xcode for "start:" and "shutdown:" and prepended a "b".  I don't think it will be possible to get an exemption for this because the app is kicked out by their automatic tools before it even sees a human reviewer.

**Comment by paulgee31** [comment]
I just submitted an app and it sailed through the review. I'm still using the developer branch if that helps.

**Comment by mousebird** [comment]
Good to know, thanks.  But that's really weird.
We'll still do something in the toolkit.

**Comment by mattcollins107** [comment]
App was also rejected once for this reason, but was approved on a separate instance with the same version of the library.  I can only assume they are not 100% consistent with the checks they run against each binary.

**Comment by jmnavarro** [comment]
Fixed on [branch issue/735](https://github.com/mousebird/WhirlyGlobe/compare/develop_2_4_1...issue/735)
