### ISSUE TITLE
Position the globe on screen. IOS

### ISSUE THREAD

**Issue by HarmanIncDev** [mousebird/WhirlyGlobe#736]
Hi, it is more of like a question. Is there any way i can position the globe to the bottom right of the screen. I tried the .screenPos in the WhirlyGlobeAnimation. Thanks

**Comment by mousebird** [comment]
The globe is always going to be centered.  You could mess with the UIView, I'd think.

**Comment by HarmanIncDev** [comment]
So i think assume that .screenPos has nothing to do with the position of globe on screen.
Thanks, i am gonna hack my way around it, take a screenshot and stuff.

**Comment by mousebird** [comment]
screenPos in an animation should be where you want the position you are animating (geo position) to wind up on the screen.  Rather than just the middle.

So if you wanted -80,+20 to wind up in the bottom middle third of the screen so you could put an annotation above it, you'd use screenPos.
