### ISSUE TITLE
[Android] GlobeMapFragment in ScrollView.

### ISSUE THREAD

**Issue by geftimov** [mousebird/WhirlyGlobe#737]
Having the GlobeMapFragment in ScrollView.
When you scroll up and down the map is flickering and you can see its background.
Probably because the rendering of the map is done in different thread.

**Comment by mousebird** [comment]
It looks like the solution is to use the TextureView based view.  That appears to be the only possible solution.

**Comment by geftimov** [comment]
For information on who has to use the view in ScrollView:

```
mapSettings.useSurfaceView = false;
```
