### ISSUE TITLE
[Android] Controller.removeLayer() does not seem to do anything

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#738]
I am building a map based on layers and then I need to be able to swap these layers without shuting down the map.

I am using removeLayer(), but it does not look like it is doing anything and all layers (the ones that should be removed and the new ones) are visible.

Am I missing something ?

Thx,
JM

**Comment by jmcazaux** [comment]
and Layer.refresh() does not seem to be dong much either.

I am after a solution to change the style of my vector objects and force a full rebuild of teh layers but I have found nothing that works yet.

**Comment by mousebird** [comment]
I checked the removeLayer code and it does seem to be doing something.
There's also the LayerShutdownTestCase which does seem to work.

Is this a specific layer type?  Maybe a QuadPagingLayer?

**Comment by jmcazaux** [comment]
It is a QuadPagingLayer that I use for my vector layers.

Anything else I should do ?

**Comment by mousebird** [comment]
It may be that QuadPagingLayer is not cleaning up objects during shutdown.  I'll check.

**Comment by jmcazaux** [comment]
Many thanks !

**Comment by mousebird** [comment]
Turned out to be the QuadPagingLayer not cleaning up after itself.  Fixed.
