### ISSUE TITLE
'Bad image data for tile 1: (0,0)' when using osm2vectortiles.org mbtiles db

### ISSUE THREAD

**Issue by deanezra** [mousebird/WhirlyGlobe#739]
If I use one of the premade mbtile sqlite db's (united kingdom.mbtiles) from:

http://osm2vectortiles.org/downloads/

I get a blank map and the following errors in xcode when running:

'Bad image data for tile 1: (0,0)'

The same app works fine when using the WhirlyGlobeResources included 'geography-class_medres.mbtiles'

The sqlite data structures look the same, am I missing something or are the mbtiles data different?

I would like to use the osm2vectortiles files as they are nicely updated based on Openstreetmap data.

The app code is based on the Whirlyglobe offline tutorial except that the mbtiles file is loaded from the App documents dir.

**Comment by mousebird** [comment]
That's not image data.  It's vector data.  I think there is a vector mbtiles example in the AutoTester.

**Comment by deanezra** [comment]
@mousebird, please forgive my ignorance. I thought the 'geography-class_medres.mbtiles' was a db of vector tiles.

Is the vector tiles approach considered stable on both ios and android versions of Whirlyglobe maply?

I will go and search out the example in AutoTester

**Comment by mousebird** [comment]
Geography class is image tiles.

Vector tiles are stable, but are more complex.  If you don't have a strong need to use vector tiles, image tiles are fine.  What's your use case?

**Comment by deanezra** [comment]
I had a look at auto tester and it seems that I need access to the simple style generator, which isn't in the cocoa pods version. I guess I would need to build from source? 

I see references to embedding the binary framework on one of the past issues. 

do you have instructions for that? 

my use case is simply to have a section of the UK as an offline map (as app will run on internal private network). so raster or vector would be OK. I thought that using the osm 2 vector pre prepared mbtiles may save time, but it looks like I will spend the time configuring the WhirlyGlobe vector part instead. 

I have tried generating a mbtiles db with raster images using mobile atlas creator. but I am finding the mapview to show a mixture of zoom levels if I zoom in and out. 

Could you suggest the toolset that you have used successfully to generate raster based mbtiles files?

**Comment by deanezra** [comment]
Heres a screenshot of the whirlyglobe maply mapview with currupted zoom levels that I mentioned when using a offline raster mbtiles db generated by Mobile Atlas creator (MOBAC) of sheffield area. 

<img width="492" alt="whirlyglobe_offline_raster_mbtile_errors" src="https://cloud.githubusercontent.com/assets/141395/18808643/51ec2e9c-825f-11e6-8659-1a104877d505.png">

**Comment by deanezra** [comment]
ok, so I have updated to the develop_2.4.1 branch and I am now only seeing wierd tile effects when I zoom outside the bounds of the tiles exported to the mbtiles file.

PS I have also tried mbtiles generated from TillMill and the same happens (so I guess its not MOBAC).

Is there a way to stop the map zooming outside the mbtiles bounds?

**Comment by mousebird** [comment]
The thing with an extracted MBTiles file like that is it's going to have a weird set of tiles from a spatial perspective.

Low resolution tiles will cover larger areas than high resolution tiles.

The toolkit generally wants to cover as much display area as it can so you're seeing the low res tiles in areas where the high res tiles don't cover.

If you'd like to adjust that you have some options.  If you're using a flat map the simplest approach is to turn on singleLevelLoading int he QuadImagesLayer.  This will ensure there's only one level loaded at once and will ditch the low res tiles.

**Comment by deanezra** [comment]
Ok, So enabling the singleLevelLoading gives an odd side effect of causing the tiles to be only shown in a smaller square. 

See the attached images: At first when positioned at the center of the mbtiles area, all looked good.

But as I zoom out with gestures, I seem to get the whole map shown in a square smaller than the mapview.

<img width="494" alt="singleload_0_first_load" src="https://cloud.githubusercontent.com/assets/141395/18815185/c6353c96-8320-11e6-99ee-169f07b8294d.png">

<img width="498" alt="singleload_1" src="https://cloud.githubusercontent.com/assets/141395/18815187/d7000dc6-8320-11e6-84e8-60a41e476124.png">

<img width="497" alt="singleload2_zoomed" src="https://cloud.githubusercontent.com/assets/141395/18815189/e9b5ea26-8320-11e6-8925-954095aa4540.png">

The square seems to match the boundary of the mbtiles export? Only that if I zoom out far enough I see the whole of uk in low res.

I really appreciate your help on this.

**Comment by mousebird** [comment]
That's the data that's in the MBTiles file so that's what it's going to show.
Looks like it's working correctly.

**Comment by deanezra** [comment]
I ended up increasing the area that the mbtiles covered so that it met the coast lines. this in combination with disabling single load gave me an OK map without mixture of blurred tiles. 

thanks for your help.

**Comment by mousebird** [comment]
Great!  Glad it worked.

What's your app do, by the way?
