### ISSUE TITLE
[Android] SDK not drawing areals

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#742]
I have one instance of the SDK not drawing any areals.

It draws the background colour, it draws lines, markers and labels, but does not draw any areals.

The device is a Samsung galaxy Note 2014 running Android 4.4.

**Comment by jmcazaux** [comment]
Logs coming from the device
```
10-02 10:42:09.650 D/dalvikvm(24524): Trying to load lib /data/app-lib/com.ironbird.fav2-2/libgnustl_shared.so 0x422c2238
10-02 10:42:09.650 D/dalvikvm(24524): Added shared lib /data/app-lib/com.ironbird.fav2-2/libgnustl_shared.so 0x422c2238
10-02 10:42:09.650 D/dalvikvm(24524): No JNI_OnLoad found in /data/app-lib/com.ironbird.fav2-2/libgnustl_shared.so 0x422c2238, skipping init
10-02 10:42:09.650 D/dalvikvm(24524): Trying to load lib /data/app-lib/com.ironbird.fav2-2/libMaply.so 0x422c2238
10-02 10:42:09.650 D/dalvikvm(24524): Added shared lib /data/app-lib/com.ironbird.fav2-2/libMaply.so 0x422c2238
10-02 10:42:09.650 D/dalvikvm(24524): No JNI_OnLoad found in /data/app-lib/com.ironbird.fav2-2/libMaply.so 0x422c2238, skipping init
```

**Comment by mousebird** [comment]
No, that's just the games it plays when loading native libraries.
If it hadn't loaded the library, it would display nothing at all.

**Comment by jmcazaux** [comment]
The logs do not seem to contain anything else from the kit.

What else can we do?

**Comment by mousebird** [comment]
I can check for a buffer size limit explicitly and see if we're running into it.

**Comment by jmcazaux** [comment]
Would that require a special SDK version to run on the device ?

**Comment by mousebird** [comment]
Probably not.  If these checks make sense, they'll work everywhere.

**Comment by jmcazaux** [comment]
Hi Steve, any progress on this one ?

**Comment by mousebird** [comment]
Not yet.  I'm trying to correlate this with some problems I've seen on similar models.

You say this is a Samsung galaxy Note 2014.  Can you get me an exact model number for that?

**Comment by jmcazaux** [comment]
Here is everything I have from the bug report:
```
Device model: SM-P605
Firmware version: 4.3
Kernel version: 3.4.0-1750146 - se.infra@SEP-107 ) - #1 SMP PREEMPT Wed Oct 16 20:34:36 KST 2013
Build number: JSS15J.P605XXUBMJ9
```

**Comment by mousebird** [comment]
I'm trying to zero in on a chipset that may be causing this and a similar problem.  But I'm not as familiar with Android hardware as I am with iOS.

Do you know why they would list two different GPU chip sets here?
http://www.gsmarena.com/samsung_galaxy_tab_s_10_5_lte-6235.php

**Comment by jmcazaux** [comment]
I must say that I have no idea.

most likely there were 2 variants of this device, but I would have guessed it would be 2 SKUs...

Or is it one of those device with a GPU for powered use and another one for battery use.
I never came across such thing on an Android device, but some Windows tablets / convertible have that.

**Comment by mousebird** [comment]
I've seen the dual GPU thing on laptops, but I didn't think it was normal for Android devices.

**Comment by jmcazaux** [comment]
No neither do I.
