### ISSUE TITLE
[Android] QuadImageTileLayer.TileSource not being queried for all zoom levels

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#745]
I am using a custom QuadImageTileLayer.TileSource and it happens that I have a source with 3 layers (10, 11, 12) that are all different (not only about details).

I have noticed that when level 11 is never queried. It jumps directly from level 10 to 12.

This is on a map.

When setSingleLevelLoading(false), level 11 is queried, tiles on the map are then coming from different levels, which looks very broken in my case.

Any idea to fix this ?

**Comment by mousebird** [comment]
It should match the level to the screen resolution *but* it will jump back up a level if it fails to find a tile at the given level.

I suspect it's probably working as designed, but to check you can set up a test tile source for level 10, 11, and 12 and see how it acts.  Take a look at the TestImageSource and see if it acts as you're expecting.

**Comment by jmcazaux** [comment]
Scrap that...

I was trying to twist the SDK too much, but pixels are pixels.
