### ISSUE TITLE
android performance mapbox

### ISSUE THREAD

**Issue by khinze** [mousebird/WhirlyGlobe#746]
Hi there. 

We have implemented the globe on android. 
We are using mapbox to render the tiles. 

The tiles seems to be rendering fine on most androids devices. We are stuck I with an issue that the tiles seem to take longer to load on the gobe. There is a delay where you just see empty space until tile has loaded. The issue is occurring on a Samsung s5. Is there any device and performance limitations? Is there any enhancements in terms of configuration on android devices which I can try?

**Comment by mousebird** [comment]
I can't say I've seen this.  I'd suggest you try the Android AutoTester on that device and see if you notice anything with that device compared to other devices.

**Comment by khinze** [comment]
Thanks. I will have a look.  Is there any limitation in performance for any android devices that you are aware off?

**Comment by khinze** [comment]
Thanks. I will have a look.  Is there any limitation in performance for any android devices that you are aware off?

**Comment by mousebird** [comment]
It really depends on the device and the version of Android.

Sometimes you have to tune the image layer to get better performance.  You could try reducing the number of simultaneous connections for example.  I'd also look at the log output to see if anything is complaining.

**Comment by khinze** [comment]
Thanks so much for your input. I will give it try. Do you maybe have any example of how I can reduce the amount of simultaneous connections? Is there issues you have found so far on any devices and which versions of android have seemed to cause any issues?

**Comment by mousebird** [comment]
setSimultaneousFetches() on the QuadImages layer.
