### ISSUE TITLE
Wide Vectors use a lot of memory. Like, a ton of it.

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird/WhirlyGlobe#747]
Drawing this set of vectors as wide vectors causes 3gb of heap allocations, and crashes with an std::bad_alloc exception. Adding the same set of vectors as regular(not wide) vectors causes a 11.6 mb of heap allocations. I would expect the nicer rendering to use memory, but not 270x as much memory.

I can send you the instruments trace's if that would be helpful, but they're big, 2gb each.

Not wide vectors:
![screen shot 2016-10-11 at 2 16 55 pm](https://cloud.githubusercontent.com/assets/2048291/19287642/c9fbcb1e-8fbf-11e6-82f7-1361aa68aa0a.png)

Instruments output with regular vectors:
![regular](https://cloud.githubusercontent.com/assets/2048291/19287813/93b6cf76-8fc0-11e6-907b-339a2e797a05.png)

With wide vectors:
![wide](https://cloud.githubusercontent.com/assets/2048291/19287843/a81d5d72-8fc0-11e6-91ee-f4f80f315b43.png)

std::bad_alloc crash with wide vectors:
<img width="2551" alt="screen shot 2016-10-11 at 1 23 40 pm" src="https://cloud.githubusercontent.com/assets/2048291/19287863/c299c8d4-8fc0-11e6-97a9-8bccfb13d2be.png">

**Comment by mousebird** [comment]
I bet this is triggering a weird case.
Can I get those vectors are a GeoJSON file?

**Comment by JesseCrocker** [comment]
@mousebird would it work to send you the output from [MaplyVectorObject writeToFile:] ? If not i can write some code to dump them as geojson.

**Comment by mousebird** [comment]
Might work.  I haven't used that stuff in a long time, but it still seems to be intact.

**Comment by JesseCrocker** [comment]
I tried simplifying the geometries more before displaying. Seems like the problem is that the geometries were not simplified enough.

**Comment by mousebird** [comment]
That might help, but that still seems excessive.

**Comment by mousebird** [comment]
It was just an allocation error.  If vectors were over a certain size, it was triggering a problem.
