### ISSUE TITLE
Zooming level when MapDisplayType set to Globe

### ISSUE THREAD

**Issue by bvanderwesthuizen** [mousebird/WhirlyGlobe#748]
Hi There

We are currently have a globe implemented project which needs to zoom in to zoom level 20.
We have a RemoteTileInfo minZoom set to 0 and maxZoom set to 20.
Unfortunately we are currently getting a zoom level of around 15 when fully zoomed in.

Can you please assist us in regards to the above issue as well as how to set the limit on the zoom out as currently it is zooming out to far and the globe is then barely visible.

**Comment by mousebird** [comment]
Are you unable to zoom closer than level 15 or can you zoom really close and level 15 gets really big?

Look for setZoomLimitsMin:Max: in the view controller.  You can do a getZoomLimits and see what the default values are.  Make the Max smaller to keep the user from zooming out and make the Min smaller to let them get closer.

**Comment by bvanderwesthuizen** [comment]
Hi There

We have tried implementing the setZoomLimits to Min:1 and Max:1

After setting the setZoomLimitsMin:Max: in the Globe view Controller , when the user tries to zoom in the globe does not zoom in but the user is now limited on zoom out which is great.

Can you please assist on regards to the zoom in as when I set the Min to 0 we are able to zoom in but still only up until around 15 zoomed in level and if I set the Min > 1 and Max = 1 the globe then zooms out.

**Comment by bvanderwesthuizen** [comment]
Hi There

We Have managed to reach z-index 0 on MapDisplayType : Globe  but this is not zoomed in far enough but if we set the MapDisplayType : Map we can zoom in as far as street level.
We are currently using mapbox tiles with Satellite Streets as Style.

Please find below code snippets from where I add my tile layer and QuadImageTileLayer settings and Globe controller zoom Limits

@Override
protected MapDisplayType chooseDisplayType() {
        return MapDisplayType.Globe;
    }

    @Override
    protected void controlHasStarted() {
        globeControl.gestureDelegate = this;
        //int[] array = new int[]{-2,0};
        // setup base layer tiles
        String cacheDirName = "mapbox_tiles";
        File cacheDir = new File(getActivity().getCacheDir(), cacheDirName);
        cacheDir.mkdir();

        RemoteTileInfo remote1 = new RemoteTileInfo("https://api.mapbox.com/styles/v1/jacograba/citvbqq1a003h2itbc6cvehey/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoiamFjb2dyYWJhIiwiYSI6ImNpdHZibmFpNDAwMGozbms5M2RxNmg1MGMifQ.6rz6UhynQo3jpCfBvREb-g","jpg",0,20);

        RemoteTileSource remoteTileSource = new RemoteTileSource(remote1);


        remoteTileSource.setCacheDir(cacheDir);

        SphericalMercatorCoordSystem coordSystem = new SphericalMercatorCoordSystem();

        QuadImageTileLayer baseLayer = new QuadImageTileLayer(globeControl, coordSystem, remoteTileSource);

        baseLayer.setImageDepth(1);
        baseLayer.setSingleLevelLoading(false);
        baseLayer.setUseTargetZoomLevel(false);
        baseLayer.setCoverPoles(true);
        baseLayer.setHandleEdges(true);
        baseLayer.setSimultaneousFetches(2);


        globeControl.addLayer(baseLayer);

        globeControl.setZoomLimits(0,1);

Can you please assist in advising us on how to zoom in as far as street level with MapDisplayType set to Globe

**Comment by mousebird** [comment]
You can't really set the ZoomLimits to 0.  It's going to have a minimum value at some point.

It's entirely possible the min value is not set right on Android.  I'll have to test this out myself.
