### ISSUE TITLE
Implementing 2 layers of RemoteTileInfo onto WhirlyGlobe

### ISSUE THREAD

**Issue by bvanderwesthuizen** [mousebird/WhirlyGlobe#749]
Hi There

We have implemented the globe on android.
We are using mapbox to render the tiles and have one tile set already implemented onto the globe.

We are currently experiencing some rendering issues when adding a second layer onto the GlobeController.addLayer like when turning the globe one layers tiles are showing and then the other layers tiles.

Can you please assist with some guidance as to how to implement a second layer onto the Globe Controller

**Comment by mousebird** [comment]
Set the drawPriority on that second layer to a value at least 100 higher than the first.
