### ISSUE TITLE
Can't find clustering

### ISSUE THREAD

**Issue by ericjkunz** [mousebird/WhirlyGlobe#751]
I can't seem to find the kMaplyClusterGroup constant or the MaplyClusterGenerator class anywhere in the framework.

Thanks,
Eric

**Comment by mousebird** [comment]
Make sure you're on develop_2_4_1 or get a recent build from the builds page.

**Comment by ericjkunz** [comment]
Thanks Steve! That'll do it.

**Comment by mousebird** [comment]
Great!  Might I ask, what's your app?

**Comment by ericjkunz** [comment]
I'll have to get back to you in a few weeks when it launches.
