### ISSUE TITLE
Texture size with kMaplyProjectionTangentPlane

### ISSUE THREAD

**Issue by ericjkunz** [mousebird/WhirlyGlobe#754]
Hello. I want to use kMaplyProjectionTangentPlane as my projection to prevent stretching of the texture's image near the poles but can't seem to adjust the scale of the texture. kMaplyVecTexScaleX/Y seem to do nothing when using this projection.

**Comment by mousebird** [comment]
This only works if you're doing a direct projection of your own custom texture on the poles.  Do you have your own image?

**Comment by ericjkunz** [comment]
Yes. I am generating images and setting it to kMaplyVecTexture for my MaplyVectorObjects.

**Comment by mousebird** [comment]
Neat!

It looks like the texture scale is used for TextureProjectionNone and not for TextureProjectionTanPlane.  I see how the tangent plane logic works, but I'm not clear if it can be scaled within that.

This really deserves a good test case.  And coincidentally I think I was talking to your little company about a support contract...

**Comment by nickplee** [comment]
@mousebird noted :)

**Comment by mousebird** [comment]
Texture scaling now working with TextureProjectionTanPlane.
