### ISSUE TITLE
[iOS] swift trying to source distribution but there is no MaplyBridge.h file

### ISSUE THREAD

**Issue by seubseub** [mousebird/WhirlyGlobe#757]
Hi!
I'm trying to do source distribution

I do all thing but i have a error
This is error!
bridging header '/Users/macbookproretina/Desktop/test_whirlyglobe/test/libs/WhirlyGlobeMaply/WhirlyGlobeSrc/WhirlyGlobe-MaplyComponent/include/MaplyBridge.h' does not exist

And I see this download file, there is no MaplyBridge.h file what can I do?

**Comment by jmnavarro** [comment]
[MaplyBridge.h](https://github.com/mousebird/WhirlyGlobe/blob/develop_2_4_1/WhirlyGlobeSrc/WhirlyGlobe-MaplyComponent/include/MaplyBridge.h) is in branch `develop_2_4_1`.

**Comment by jmcazaux** [comment]
Does it mean that MaplyBridge.h is not available from the binary distribution ?

I have downloaded the binary from the link on http://mousebird.github.io/WhirlyGlobe/tutorial/ios/building_from_binary.html and MaplyBridge.h is not there.

From the URL it seems it is 2.4.

**Comment by mousebird** [comment]
Try one of the binary builds from here:
https://mousebird.github.io/WhirlyGlobe/builds/builds.html

**Comment by jmcazaux** [comment]
The first binary link links to 2.4 (no MaplyBridge.h)

Unfortunatelly

> Something bad happened... Mr. Jenkins seems to be too busy... try again later

And he has been busy for a while now...

But I tried some nightly in the past and they are pods so, apparently they do not include the vector side of things...

**Comment by mousebird** [comment]
It's not busy.  Somewhere on your browser is a button that lets you run unsafe scripts.  Turn that on and you'll see the builds.

**Comment by jmcazaux** [comment]
Ok, I finally found my way around and built my app with the WhirlyGlobeMaplyComponent.framework from the last nightly but it seem it does not expose MapboxVectorTiles...

Are vector tiles only exposed from the source distribution or am I doing something wrong ?

**Comment by mousebird** [comment]
You need to set NOTPODSPECWG=1, but it looks like you found that.

**Comment by seubseub** [comment]
Thank's! I solved it!
