### ISSUE TITLE
[Android] QuadPagingLayer.setVisbility

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#762]
It seems that there is no setVisibilty on QuadPaginglayer (vs QuadImageTileLayer).

That would be very useful...

**Comment by mousebird** [comment]
Here's the thing with a QuadPagingLayer.  It doesn't actually create any visual objects.  That's all done by the delegate (or Interface on Android).

The only parameters in a QuadPagingLayer that should be set related to loading tiles.

Now there may be delegates (I know, not a delegate on Android) which could use this functionality.  Which one are you using?

**Comment by jmcazaux** [comment]
In this case it is vector layers, so I assume VectorStyle is the delegate/interface in this case.

What you are saying is strange, because when zooming out, the objects created by the VectorStyle at higher zoom levels are removed.
If my style has created labels at zoom level 10, they are removed when I zoom out to 9, 8 etc.

I do nothing for this to happen (I think).

This state (and it is something I have been suspecting for a while) it does not seem true the other way around. At least what I am seeing is that areal created ate zoom level 8 are still drawn at zoom level 9, 10 etc (when there is actually a more detailed version in the higher zoom tile).

This is particularly an issue on mu maps for the landmask as the crude and less detailed version drawn at lower zoom levels still shows at higher zoom level. 

So I am trying to fix this by having the crude landmask in another layer, but it does seem it will help.

**Comment by mousebird** [comment]
The QuadPagingLayer will remove objects when the tile is no longer there.  Visibility is an attribute on the objects, separate from when the tiles are removed.

It can be confusing because deleting the objects will obviously make them invisible.

**Comment by jmcazaux** [comment]
I am not sure this works as expected (or at least how I understand it).

I have a vector mbtile for my background land with zoom 0 to 3 (tiles).
The detailed landmask starts at level 8 and is in another layer.

I have added some logs in the VectorStyle, here are the logs, and they look OK.

```
ComponentStyle: Style land mask default              built   18 filled objects in  109 ms (tile x=  3, y=  5, level= 3).
ComponentStyle: Style land mask default              built   26 filled objects in  163 ms (tile x=  4, y=  5, level= 3).
ComponentStyle: Style land mask HD                   built    1 filled objects in    1 ms (tile x=126, y=164, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in   15 ms (tile x=128, y=165, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in    1 ms (tile x=127, y=163, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in    1 ms (tile x=127, y=165, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in   24 ms (tile x=126, y=165, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in    1 ms (tile x=128, y=164, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in    2 ms (tile x=127, y=164, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in   22 ms (tile x=128, y=163, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in    2 ms (tile x=126, y=165, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in    1 ms (tile x=127, y=165, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in    3 ms (tile x=128, y=165, level= 8).
ComponentStyle: Style land mask HD                   built    1 filled objects in    8 ms (tile x=253, y=329, level= 9).
ComponentStyle: Style land mask HD                   built    1 filled objects in    1 ms (tile x=255, y=329, level= 9).
ComponentStyle: Style land mask HD                   built    1 filled objects in   21 ms (tile x=254, y=328, level= 9).
.../...
```

This looks consistent.

The issue is that I still can see the areal drawn at zoom 3 when the ones drawn at zoom 8 are overlaid.

Is it how it should work ?

When you say 

> The QuadPagingLayer will remove objects when the tile is no longer there

do you mean the tile is off screen (x and y are not visible) or does it account for z as well (then it is more complicated because in this case, the areals are only drawn between levels 0 and 3, but I still want them to be visible up to level 8 (not included) when the HD landmask will take over.

If this is the case for all objects, that can lead to a significant overload of the GPU.

I am not sure how to handle this...
Any clue ?

**Comment by mousebird** [comment]
A QuadPagingLayer will get rid of any tiles that aren't on screen or are not at the appropriate level for display.  But syncing objects between QuadPagingLayers can be complex.

So if you have one data source that has levels 0-3 then level 3 is the last valid level.  If you zoom in past level 3 it will just leave those objects in place.  It doesn't know about any levels beyond that.

If you have another data sources that has level 8 in it, it's not synced to your level 0-3 data source.  Working around this is complex.  You can try to figure out when data should disappear to match level 8.  That would mean using the minVis and maxVis values on each object.  But even if they disappear at the right point they would not be synced to loading from your level 8 data source.

Or you could try to make a composite source that took all the levels into account.  This is very complex.

I think setting the minVis values is probably the easiest approach.  You can ask the controller what height would correspond to which scale.  That's the more reliable way to do this, though it's not perfect.

**Comment by jmcazaux** [comment]
Ah, I see...
It would have worked well if I had put everything in the same layer.

Between level 8 and 9 the details should be pretty close, so I can probably get away with cutting off the low definifition layer around 8.5...

Will give it a go.

Thx.

**Comment by jmcazaux** [comment]
Worked around this one, closing.
