### ISSUE TITLE
[Android] Map / globe remains black with last version of the SDK (commit 2965737)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#765]
With the last version of the SDK (commit [2965737](https://github.com/mousebird/WhirlyGlobe/commit/2965737e63487ecf7d5113f8c8e89269853e7b65)), the map remains black. 
This happens both in my app and in the AutoTester with all tests. I have cleaned the projects (AutoTester), it does not change things.

**Comment by mousebird** [comment]
I am seeing this one on only certain types of hardware, but it's the bug I'm working on right now.

**Comment by jmcazaux** [comment]
It is to note that this happens only on my device with 7.0.
My other device at hand is on 5.1 and it works fine.

**Comment by jmcazaux** [comment]
Maybe something to do with https://github.com/mousebird/WhirlyGlobe/commit/6226594d43f8a7f3960c774fff6d58ba0ddf1417

**Comment by jmcazaux** [comment]
As well, it is working on the same device with an earlier version of the kit (last merge from 44edaeafe118eefcf8821897c4b1d3759a4fafb3).

**Comment by mousebird** [comment]
My current thinking is that it's e3a1fb6 causing the problem.  I'm working my way through the changes one by one to figure it out.

I hadn't considered that it might be an Android version issue rather than a hardware issue.

If you roll back to ec2e8fd it should work again.

**Comment by jmcazaux** [comment]
No, this is not the one.

**Comment by jmcazaux** [comment]
e3a1fb6 creates some issues of its own (makes app crash on selection) but IIRC, it was displaying the map.

**Comment by mousebird** [comment]
The selection crash should be fixed.  Thanks for the feedback on e3a1fb6.  I'll sort it out today.

**Comment by mousebird** [comment]
Got it.  It was the code I added for newer versions of Android where TextureView doesn't like background drawables.
