### ISSUE TITLE
How can I fix this issue when I  upgrade xcode to version 8?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#766]
Hi,
     when I  upgrade xcode to version 8, found the follow issue:

Undefined symbols for architecture armv7:
  "_sqlite3CodecAttach", referenced from:
      _attachFunc in libsqlite3.a(sqlite3.o)
  "_sqlite3CodecGetKey", referenced from:
      _sqlite3RunVacuum in libsqlite3.a(sqlite3.o)
      _attachFunc in libsqlite3.a(sqlite3.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
and Xcode 7  was ok .  How can I fix this?!    Thank you~
```

**Comment by mousebird** [comment]
Are you seeing this in your own app or in the AutoTester?

**Comment by marychenyuan** [comment]
yes, this error was appear in my own app...

**Comment by mousebird** [comment]
We're not seeing that in the AutoTester app.
I suggest you compare the settings between the two to see what the problem might be.

If you're using a binary framework, the problem could be the version of sqlite3
