### ISSUE TITLE
Android: The GlobeMapFragment is extending the non support version of 'Fragment'

### ISSUE THREAD

**Issue by deanezra** [mousebird/WhirlyGlobe#769]
WhirlyGlobes Android fragment 'GlobeMapFragment' is extending from the Android android.app.Fragment. This will cause issues when developers try to do backward compatibility using older versions of android.

It is recommended practise to use the Google Support library classes. E.g. extend from 'android.support.v4.app.Fragment'.

**Comment by mousebird** [comment]
Good point.

**Comment by mousebird** [comment]
Should be fixed.
