### ISSUE TITLE
WGMViewController animateToPosition:height:heading:time: spinning around

### ISSUE THREAD

**Issue by dangustafsson** [mousebird/WhirlyGlobe#787]
Sometimes when the device is stationary the call to WGMViewController animateToPosition:xheight:heading:time:
causes the screen to just spin around. 
I have been logging all the values - position, heaight & heading and they remain the same. But the screen is just spinning.
I'm not sure what the reason is, it can happen at any position, height and heading. 

This is how the method is called
`- (void) didUpdateLocation:(CLLocation *)location {

	MaplyCoordinate position = MaplyCoordinateMakeWithDegrees(location.coordinate.longitude, location.coordinate.latitude);
	float height = _currentMapController.height;
	float heading = heading = GLKMathDegreesToRadians(location.course);
	
	NSLog(@"Animating to %f,%f ... %f  h: %f", position.x, position.y, heading, height);

	[(WhirlyGlobeViewController *)_currentMapController animateToPosition:position height:height heading:heading time:1.0]
}`

Here is the log output of an example where the map was rotating 360 degrees every second - 1 sec being the time interval the map is being updated.

` Animating to [lat,lon] ... heading: 4.295146  height: 0.000061
 Animating to [lat,lon] ... heading: 4.295146  height: 0.000061
 Animating to [lat,lon] ... heading: 4.295146  height: 0.000061
 Animating to [lat,lon] ... heading: 4.295146  height: 0.000061`

I have omitted the actual lat & lon of my own location, but the number are exactly the same every time.

If I use any other combination of animating to the current position and setting the heading it works so I thing the data I'm feeding the VC is correct. If I do for example:
`[(WhirlyGlobeViewController *)_currentMapController setHeading:heading];
	[(WhirlyGlobeViewController *)_currentMapController animateToPosition:position time:1.0];`
it works, but it's a bit choppy as the heading is just being set without an animation.

**Comment by mousebird** [comment]
Do you have keepNorthUp set?

**Comment by dangustafsson** [comment]
That's it. 
In the didStopMoving delegate I kept setting the keepNorth value like so
`_currentMapController.keepNorthUp = (viewC.height > 0.001);` 

I was able to fix it by only setting the keepNorth value when it needs to change
`BOOL shouldKeepNorthUp = (viewC.height > 0.001);
	if (_currentMapController.keepNorthUp != shouldKeepNorthUp) {
		_currentMapController.keepNorthUp = shouldKeepNorthUp;
	}`

Thanks!

**Comment by mousebird** [comment]
Right!  That makes sense.
