### ISSUE TITLE
Android Unable to use Sticker

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe#789]
Hi,

I try to reproduce this sample of Google Maps API on a 2D map control:

https://developers.google.com/maps/documentation/javascript/examples/groundoverlay-simple?hl=en

Nothing is displayed.

Please find below the code:

```
Sticker sticker = new Sticker();
sticker.setLowerLeft(-74.22655, 40.712216);
sticker.setUpperRight(-74.12544, 40.773941);
sticker.setImageFormat(QuadImageTileLayer.ImageFormat.MaplyImage4Layer8Bit);
ArrayList<MaplyTexture> maplyTextureArrayList = new ArrayList<>();
maplyTextureArrayList.add(mapControl.addTexture(getBitmapFromURL("https://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg"), new MaplyBaseController.TextureSettings(), MaplyBaseController.ThreadMode.ThreadCurrent));
sticker.setImages(maplyTextureArrayList);

ArrayList<Sticker> stickerArrayList = new ArrayList<>();
stickerArrayList.add(sticker);
StickerInfo stickerInfo = new StickerInfo();
mapControl.addStickers(stickerArrayList, stickerInfo, MaplyBaseController.ThreadMode.ThreadCurrent);
```
The bitmap object is not null. My image is OK.

Any idea ?

Thanks for helping.

**Comment by mousebird** [comment]
I don't see anything obviously wrong with that.
There's a Stickers test in the Android AutoTester.  I'd suggest copying the code from there and adapting it until it breaks.

**Comment by NasH5169** [comment]
In Globe mode, i see something, but misplaced and moving while the user pan/zoom the globe so the sticker is not fixed.

_I'm trying the test cache_

![screenshot_20161121-172509](https://cloud.githubusercontent.com/assets/6979479/20491530/f92aad52-b011-11e6-89ea-8fd134480f4a.png)

**Comment by mousebird** [comment]
Sounds like it might be a drawPriority problem.  Be sure to set the drawPriority to more than the base layer's draw priority.  Try 1000000 just to see if that's it.

**Comment by NasH5169** [comment]
With the line:
`stickerInfo.setDrawOffset(1000000);`

I don't see the sticker anymore. Without the draw priority, the sticker moves when I pan/zoom the globe ! It is very strange :)

**Comment by NasH5169** [comment]
The setDrawPriority doesn't change anything. The strange behavior is that the image is not at the same place on the map. If I pan and/or zoom the map, the sticker moves too.

**Comment by NasH5169** [comment]
I tried to make the sticker area bigger by set these coords:

sticker.setLowerLeft(-78, 38);
sticker.setUpperRight(-76, 44);

The result (i think, there is an issue with the coordinate system?)

![test_coord](https://cloud.githubusercontent.com/assets/6979479/20526976/c79ab308-b0c6-11e6-8c5c-ecba9352b283.png)

**Comment by mousebird** [comment]
Coordinates are in radians.

**Comment by NasH5169** [comment]
It's working ! Thank you.
