### ISSUE TITLE
Android PlateCarreeCoordSystem not available

### ISSUE THREAD

**Issue by hneil** [mousebird/WhirlyGlobe#790]
Trying to create a coordinate system with PlateCarreeCoordSystem, using 
PlateCarreeCoordSystem coordSystem = new PlateCarreeCoordSystem(); results in a "PlateCarreeCoordSystem() is not public.  Cannot be accessed outside package." error.  Can you make it public so this coordinate system can be created?  Thanks.

**Comment by mousebird** [comment]
It's public now.
