### ISSUE TITLE
IOS: Swift: Markers not in a cluster group disappear

### ISSUE THREAD

**Issue by deanezra** [mousebird/WhirlyGlobe#796]
I have a sets of markers with clustering named 'incidents' and then a seperate single marker showing the users location.

The incidents set has clustering enabled with:

`self.incidentMarkersObject = (theViewC?.addScreenMarkers(markers, desc: [kMaplyClusterGroup: 0], mode: MaplyThreadMode.any))!`

Whereas the user location marker  needs to be shown all the time, so it isnt in the same cluster group, (doesn't have the kMaplyClusterGroup set):

`self.userMarkerObject = (theViewC?.addScreenMarkers(userMarkers, desc: nil, mode: MaplyThreadMode.any))!`

However I am finding when I zoom out, whirlymap intermittently decides to either show an incident marker or the user marker (it seems random) - I guess its trying to cluster the user marker in same group as incidents?

How can I make sure the user marker is not in same cluster group as incident markers?

**Comment by mousebird** [comment]
Make sure layoutImportance is set to MAXFLOAT if you don't want a marker to disappear.  Otherwise it's being handed to the layout engine.

**Comment by deanezra** [comment]
@mousebird Thanks, that worked!
