### ISSUE TITLE
Alway show black screen.

### ISSUE THREAD

**Issue by TechLoveVN** [mousebird/WhirlyGlobe#800]
Hi.
I am trying to integrate WhirlyGlobe in my project (swift 3.x).
I am using Binary Distribution 2.4
this is the source code of my viewcontroller 

import UIKit
class WorldClockViewController: UIViewController {
    private var theViewC: MaplyBaseViewController?
    
    var useLocalTiles = false
    // we'll need this layer in a second
    var layer: MaplyQuadImageTilesLayer?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "World Clock"
        // Do any additional setup after loading the view.
        theViewC = WhirlyGlobeViewController()
        
        let globeViewC = theViewC as? WhirlyGlobeViewController
        let mapViewC = theViewC as? MaplyViewController
        
        // we want a black background for a globe, a white background for a map.
        theViewC!.clearColor = (globeViewC != nil) ? UIColor.black : UIColor.white
        // and thirty fps if we can get it ­ change this to 3 if you find your app is struggling
        theViewC!.frameInterval = 3
        // set up the data source
        
        
        if useLocalTiles {
            guard let tileSource = MaplyMBTileSource(mbTiles: "geography-class_medres") else {
                // can't load local tile set
                return
            }
            layer = MaplyQuadImageTilesLayer()
            layer?.tileSource = tileSource
            
        }
        else {
            // Because this is a remote tile set, we'll want a cache directory
            let baseCacheDir = NSSearchPathForDirectoriesInDomains(.cachesDirectory, .userDomainMask, true)[0]
            let aerialTilesCacheDir = "\(baseCacheDir)/osmtiles/"
            let maxZoom = Int32(18)
            
            // MapQuest Open Aerial Tiles, Courtesy Of Mapquest
            // Portions Courtesy NASA/JPL­Caltech and U.S. Depart. of Agriculture, Farm Service Agency
            guard let tileSource = MaplyRemoteTileSource(
                baseURL: "http://otile1.mqcdn.com/tiles/1.0.0/sat/",
                ext: "png",
                minZoom: 0,
                maxZoom: maxZoom) else {
                    // can't create remote tile source
                    return
            }
            tileSource.cacheDir = aerialTilesCacheDir
            layer = MaplyQuadImageTilesLayer()
            layer?.tileSource = tileSource
        }
        
        
        
        // start up over Madrid, center of the old-world
        if let globeViewC = globeViewC {
            globeViewC.height = 0.8
            globeViewC.animate(toPosition: MaplyCoordinateMakeWithDegrees(-3.6704803, 40.5023056), time: 1.0)
        }
        else if let mapViewC = mapViewC {
            mapViewC.height = 1.0
            mapViewC.animate(toPosition: MaplyCoordinateMakeWithDegrees(-3.6704803, 40.5023056), time: 1.0)
        }
        self.view.addSubview(theViewC!.view)
        theViewC!.view.frame = self.view.bounds
        addChildViewController(theViewC!)

    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
}

I have no idea why It's always show black screen.

**Comment by mousebird** [comment]
First, I'd suggest moving to 2.4.1.  Pick a [nightly build](https://mousebird.github.io/WhirlyGlobe/builds/builds.html) off the build page.

The tutorial still refers to the Mapquest layer, which is now gone.  It won't show up as blank, so that's another issue.  But I'd suggest moving to the Stamen layer for testing.  You can see in example in the StamenTestCase in the AutoTester app.

**Comment by TechLoveVN** [comment]
I changed to 2.4.1 and it works perfectly:).
you save my life @mousebird

**Comment by fukemy** [comment]
how to change to 2.4.1? Thanks yyou
