### ISSUE TITLE
[Android] setLayoutPlacement is ignored

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe#802]
Hi,

I'm trying to align some labels around one point. Align left, right and center. As I can see, there is an issue. The setLayoutPlacement method is not working.

The three samples seem to be align right.

_(I'm using the last nightly)_

Thanks for helping (and thanks for this lib, it is awesome)

![setlayoutplacement](https://cloud.githubusercontent.com/assets/6979479/20881118/17baa550-badb-11e6-971a-eda523cc53f0.png)

**Comment by mousebird** [comment]
What does the code look like for adding the labels?

**Comment by NasH5169** [comment]
The code:

`// The marker
        ScreenMarker marker = new ScreenMarker();
        marker.image = BitmapFactory.decodeResource(getActivity().getResources(), R.drawable.marker);
        marker.loc = new Point2d(Math.toRadians(-5), Math.toRadians(40));
        marker.size = new Point2d(marker.image.getWidth(), marker.image.getHeight());
        marker.offset = new Point2d(0, marker.image.getHeight() / 2);

        MarkerInfo markerInfo = new MarkerInfo();
        markerInfo.setDrawPriority(60);

        mapControl.addScreenMarker(marker, markerInfo, MaplyBaseController.ThreadMode.ThreadCurrent);

        // Center
        ScreenLabel labelC = new ScreenLabel();
        labelC.loc = new Point2d(Math.toRadians(-5), Math.toRadians(40));
        labelC.text = "Helloworld Center !";
        labelC.layoutImportance = Float.MAX_VALUE;
        labelC.offset = new Point2d(0, 0);

        // Left
        ScreenLabel labelL = new ScreenLabel();
        labelL.loc = new Point2d(Math.toRadians(-5), Math.toRadians(40));
        labelL.text = "Helloworld Left !";
        labelL.layoutImportance = Float.MAX_VALUE;
        labelL.offset = new Point2d(0, -30);

        // Right
        ScreenLabel labelR = new ScreenLabel();
        labelR.loc = new Point2d(Math.toRadians(-5), Math.toRadians(40));
        labelR.text = "Helloworld Right !";
        labelR.layoutImportance = Float.MAX_VALUE;
        labelR.offset = new Point2d(0, 30);

        // Info Center
        LabelInfo labelInfoC = new LabelInfo();
        labelInfoC.setFontSize(14);
        labelInfoC.setTypeface(Typeface.DEFAULT_BOLD);
        labelInfoC.setOutlineColor(Color.WHITE);
        labelInfoC.setOutlineSize(3);
        labelInfoC.setDrawPriority(63);
        labelInfoC.setLayoutPlacement(LabelInfo.LayoutCenter);
        labelInfoC.setTextColor(Color.parseColor("#000080"));

        mapControl.addScreenLabel(labelC, labelInfoC, MaplyBaseController.ThreadMode.ThreadAny);

        // Info Left
        LabelInfo labelInfoL = new LabelInfo();
        labelInfoL.setFontSize(14);
        labelInfoL.setTypeface(Typeface.DEFAULT_BOLD);
        labelInfoL.setOutlineColor(Color.WHITE);
        labelInfoL.setOutlineSize(3);
        labelInfoL.setDrawPriority(61);
        labelInfoL.setLayoutPlacement(LabelInfo.LayoutLeft);
        labelInfoL.setTextColor(Color.parseColor("#800080"));

        mapControl.addScreenLabel(labelL, labelInfoL, MaplyBaseController.ThreadMode.ThreadAny);

        // Info Right
        LabelInfo labelInfoR = new LabelInfo();
        labelInfoR.setFontSize(14);
        labelInfoR.setTypeface(Typeface.DEFAULT_BOLD);
        labelInfoR.setOutlineColor(Color.WHITE);
        labelInfoR.setOutlineSize(3);
        labelInfoR.setDrawPriority(62);
        labelInfoR.setLayoutPlacement(LabelInfo.LayoutLeft);
        labelInfoR.setTextColor(Color.parseColor("#008000"));

        mapControl.addScreenLabel(labelR, labelInfoR, MaplyBaseController.ThreadMode.ThreadAny);`

**Comment by mousebird** [comment]
The layoutPlacement is part of the layout engine, so layoutImportance must be set to something other than MAX_FLOAT.

**Comment by NasH5169** [comment]
I understand but not everything :)

I've just test the layoutImportance on ScreenLabel, the label is centered on his lat/lng location.

So it's ok but the layoutImportance is available on ScreenLabel and LabelInfo too: Which one I have to use?

Another question (sorry...)

What is the settings to display a label every time even if two labels share the same place on the map?

Thanks for all.

**Comment by mousebird** [comment]
The layoutImportance on the ScreenLabel overrides LabelInfo.

You can force two labels to display by giving them a layoutImportance of MAXFLOAT.  In other words, forcing them to avoid the layout engine.

There's currently no way to use layoutPlacement without layoutImportance.  You could, however, simulate it with the ScreenLabel offset.

**Comment by NasH5169** [comment]
Ok great !

It will be hard to use the offset to center if the label size is unknown but I'll try.

Thanks again (closing)
