### ISSUE TITLE
[Android] NPE when removing layer.

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#805]
I am seeing quite a few NPEs from LayerThread.java line 270.

I am a bit behind in terms of version, but in my code set, this is when the kit is shutting down the layer before removing it.

Is it normal that a null layer is removed, I cannot say.

	public void removeLayer(final Layer layer)
	{
		addTask(new Runnable()
		{
			@Override
			public void run()
			{
				layer.shutdown(); // This is line 270
				synchronized (layers) {
					layers.remove(layer);
				}
			}
		});
	}

**Comment by mousebird** [comment]
That seems very weird, but I put a check in for it.
