### ISSUE TITLE
[Android] Vector area fill color (alpha or not)

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe#807]
Hi,

I'm trying to display an area with transparency.

So i've wrote this code:

```
vectorInfo = new VectorInfo();
vectorInfo.setColor(Color.parseColor("#4AFF8C00"));
vectorInfo.setDrawPriority(80);
vectorInfo.setFilled(true);
```

FF8C00 is "darkorange" color

The result on the map is near yellow and quite opaque!

Don't understand why. I'm using map (not globe) and the last nightly.

An idea?

Thanks.

**Comment by NasH5169** [comment]
I understand but the Color.parseColor documentation says:
https://developer.android.com/reference/android/graphics/Color.html#parseColor(java.lang.String)

**Comment by mousebird** [comment]
You have to break the components out and multiply r, g, and b by alpha.
They get fed directly into the shaders and often represent non-color values so we don't multiply them for you.  Confusing, I realize.

**Comment by NasH5169** [comment]
I search for samples but nothing sure.

I have darkorange so 255,140,0

I can write this: setColor(1.0 * alpha, 0.55 * alpha, 0, alpha); ?

**Comment by mousebird** [comment]
Yes, that's about right.

**Comment by NasH5169** [comment]
Yes ! Great ! Thank you !

`vectorInfo.setColor(red * alpha, green * alpha, blue * alpha, alpha);`

(With red, green, blue and alpha between 0.0 and 1.0)

Closing :)
