### ISSUE TITLE
Crash on iPhone 7 Plus

### ISSUE THREAD

**Issue by ludawei** [mousebird/WhirlyGlobe#808]
WhirlyGlobeMaplyComponent.framework(stable build for iOS version 2.4) works well on iPhone 5s、iPhone 6、iPhone 6 Plus, but crash on iPhone 7 Plus.

#0 Thread
NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

0 CoreFoundation	___exceptionPreprocess + 124
1 libobjc.A.dylib	objc_exception_throw + 56
2 CoreFoundation	-[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 364
3 CoreFoundation	+[NSDictionary dictionaryWithObjects:forKeys:count:] + 64
4 HelloEarth	-[MapboxVectorFilter initWithArray:styleSet:viewC:] + 444
5 HelloEarth	-[MapboxVectorFilter initWithArray:styleSet:viewC:] + 444
6 CoreFoundation	___CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
7 CoreFoundation	__CFXRegistrationPost + 400
8 CoreFoundation	____CFXNotificationPost_block_invoke + 60
9 CoreFoundation	-[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1504
10 CoreFoundation	_CFXNotificationPost + 376
11 Foundation	-[NSNotificationCenter postNotificationName:object:userInfo:] + 68
12 HelloEarth	-[MapboxVectorFilter initWithArray:styleSet:viewC:] + 444
13 libdispatch.dylib	__dispatch_call_block_and_release + 24
14 libdispatch.dylib	__dispatch_client_callout + 16
15 libdispatch.dylib	_dispatch_main_queue_callback_4CF + 1000
16 CoreFoundation	___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
17 CoreFoundation	___CFRunLoopRun + 1660
18 CoreFoundation	CFRunLoopRunSpecific + 444
19 GraphicsServices	GSEventRunModal + 180
20 UIKit	-[UIApplication _run] + 684
21 UIKit	UIApplicationMain + 208
22 HelloEarth	-[MapboxVectorFilter initWithArray:styleSet:viewC:] + 444
23 libdyld.dylib	_start + 4

**Comment by mousebird** [comment]
Is this reproducible or sporadic?

**Comment by ludawei** [comment]
This is reproducible，crash evertime on my iPhone 7 Plus.
How can I solve it？

**Comment by mousebird** [comment]
Is it actually creating a NSDictionary with empty values?

**Comment by ludawei** [comment]
NO, it can work well on iPhone 5s、iPhone 6、iPhone 6 Plus, except iPhone 7 Plus.
