### ISSUE TITLE
CRASH WG EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by bryanheitman** [mousebird/WhirlyGlobe#809]
Interacting with the globe can result in this crash:

This is the line of code
                    chunkManager->enableChunk(*it, enable, changes);

(lldb) bt
XXXX was compiled with optimization - stepping may behave oddly; variables may not be available.
* thread #3: tid = 0x3905148, 0x0000000103031078 Aerovie`WhirlyKit::SphericalChunkManager::processRequests(std::__1::vector<WhirlyKit::ChangeRequest*, std::__1::allocator<WhirlyKit::ChangeRequest*> >&) + 118, queue = 'NSOperationQueue 0x610000221860 :: NSOperation 0x608003a5e060 (QOS: DEFAULT)', stop reason = EXC_BAD_ACCESS (code=1, address=0x165c1)
    frame #0: 0x0000000103031078 Aerovie`WhirlyKit::SphericalChunkManager::processRequests(std::__1::vector<WhirlyKit::ChangeRequest*, std::__1::allocator<WhirlyKit::ChangeRequest*> >&) + 118
  * frame #1: 0x0000000102ec102a Aerovie`::-[MaplyBaseInteractionLayer enableObjectsRun:](self=<unavailable>, _cmd=<unavailable>, argArray=<unavailable>) + 1798 at MaplyBaseInteractionLayer.mm:3355 [opt]
    frame #2: 0x0000000102ec149f Aerovie`::-[MaplyBaseInteractionLayer enableObjects:mode:](self=0x00007f8417541120, _cmd=<unavailable>, userObjs=<unavailable>, threadMode=MaplyThreadAny) + 565 at MaplyBaseInteractionLayer.mm:3382 [opt]
    frame #3: 0x0000000102f17c46 Aerovie`::-[MaplyBaseViewController enableObjects:mode:](self=0x00007f841a0a2000, _cmd=<unavailable>, theObjs=<unavailable>, threadMode=MaplyThreadCurrent) + 85 at MaplyBaseViewController.mm:1107 [opt]
    frame #4: 0x0000000102ef93ec Aerovie`::-[MaplyQuadPagingLayer tileDidLoad:](self=0x00006000001bcc40, _cmd=<unavailable>, tileID=<unavailable>) + 647 at MaplyQuadPagingLayer.mm:1011 [opt]
    frame #5: 0x0000000102cdb0fb Aerovie`__48-[WhirlyAirwayLayer startFetchForTile:forLayer:]_block_invoke((null)=0x0000608005273080) + 910 at WhirlyAirwayLayer.m:195 [opt]
    frame #6: 0x00000001073cd9ad Foundation`__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
    frame #7: 0x00000001073cd68f Foundation`-[NSBlockOperation main] + 101
    frame #8: 0x00000001073cbd8c Foundation`-[__NSOperationInternal _start:] + 672
    frame #9: 0x00000001073c7ccf Foundation`__NSOQSchedule_f + 201
    frame #10: 0x000000010902b0cd libdispatch.dylib`_dispatch_client_callout + 8
    frame #11: 0x0000000109008e17 libdispatch.dylib`_dispatch_queue_serial_drain + 236
    frame #12: 0x0000000109009b4b libdispatch.dylib`_dispatch_queue_invoke + 1073
    frame #13: 0x000000010900c385 libdispatch.dylib`_dispatch_root_queue_drain + 720
    frame #14: 0x000000010900c059 libdispatch.dylib`_dispatch_worker_thread3 + 123
    frame #15: 0x00000001093da736 libsystem_pthread.dylib`_pthread_wqthread + 1299
    frame #16: 0x00000001093da211 libsystem_pthread.dylib`start_wqthread + 13
(lldb)

**Comment by bryanheitman** [comment]
This happens pretty regularly with light use.

**Comment by bryanheitman** [comment]
This is related to sticker usage in a Paging Layer.. The alternative fix to this crash is to add rotation support to MaplyMarker as it would be better suited given the size of the object.

**Comment by mousebird** [comment]
This might have been a locking conflict.  Give the new version a try and let me know.

**Comment by mousebird** [comment]
I think this is now fixed.  Reopen if not.
