### ISSUE TITLE
[Android] Aliasing and join (duplicate issue?)

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe#811]
Hi Steve, 

Like I said in the title, i think this is a duplicate issue. I found similar issues where you talk about the missing of wideVectors on Android SDK?

With a vector (linear), i've some aliasing and sometimes odd joins.

Could you confirm this for me?

Thanks again for all. I really appreciate this SDK. It's very high level compare to others.

![aliasing_and_cut](https://cloud.githubusercontent.com/assets/6979479/21267078/0810079a-c3a9-11e6-9039-4225067acb00.png)

**Comment by mousebird** [comment]
This is on Android?
Yeah, we still need to move wideVectors over there.

Be happy to do it for a support customer.

**Comment by NasH5169** [comment]
Thanks for confirm.

About support customer: http://mousebird.github.io/mousebird/products.html ? Right ?

**Comment by mousebird** [comment]
Yes.  If you're interested in support drop me a line at contact@mousebirdconsulting.com and I'll send you the details.

**Comment by mousebird** [comment]
So was there interest in a support contract?  Or am I already talking to you about it via email?

**Comment by NasH5169** [comment]
I will send you an email.

**Comment by mousebird** [comment]
Cool.  I would love to move wide vectors over to Android.
