### ISSUE TITLE
Rotate 3D globe in android

### ISSUE THREAD

**Issue by city0666** [mousebird/WhirlyGlobe#812]
First of all this is not an issue. I need your help to auto rotate the 3D globe in android. I tried this `mGlobeController.getGlobeView().animate();` and this `globe.setRotation(100.0f);` bit it i snot working. can you please tell me how to auto rotate the 3D globe. Thanks for sharing the awesome library.

**Comment by mousebird** [comment]
You want the method setAutoRotate(interval,degrees).

**Comment by city0666** [comment]
but i am not able to find the setAutoRotate(interval,degrees) in the android api doc

**Comment by mousebird** [comment]
It's new, the docs haven't been updated.  Make sure you have a recent version of the library and it should be there.

**Comment by city0666** [comment]
Thanks man. it worked.
