### ISSUE TITLE
how can I get pan gesture action of Globe in swift 3.

### ISSUE THREAD

**Issue by somequestion** [mousebird/WhirlyGlobe#813]
I think I have to use this method but it's an objective C. is there any way to get the swiping or pan gesture action event of globe?

WhirlyGlobePanDelegate
+ (WhirlyGlobePanDelegate *)panDelegateForView:(UIView *)view globeView:(WhirlyGlobeView *)globeView

**Comment by jmnavarro** [comment]
You should be able to use any ObjC method from Swift. They interoperate seamlessly.
Do you get any error?

**Comment by somequestion** [comment]
I added this line in my bridging-Header file.

#import "PanDelegate.h"

but I got this error message

'PanDelegate.h' file not found

**Comment by jmnavarro** [comment]
The file is `MaplyPanDelegate.h` but it seems it's missing in some builds

Are you using a version downloaded from Builds page?

**Comment by mousebird** [comment]
We don't expose the gesture system to this level.  There are probably other ways of getting what you want.

Do you need to know when the map has moved?  There's a delegate call for that.

**Comment by somequestion** [comment]
I'm using develop_2_4_1 version

**Comment by somequestion** [comment]
func globeViewController(_ viewC: WhirlyGlobeViewController, didMove corners: UnsafeMutablePointer<MaplyCoordinate>) {}

this delegate method can check whether globe moved or not. but I want to spin another globe by rotating earth.

**Comment by mousebird** [comment]
Take a look at the getViewState method on the WhirlyGlobeViewController.  That provides full position, rotation, etc... information for the globe at any given time.
