### ISSUE TITLE
Drawing circle issue

### ISSUE THREAD

**Issue by rohitnagori** [mousebird/WhirlyGlobe#814]
I want to draw a range circle around aircraft. I calculate points by my own for it, using radius and origin. But it doesn't seems to draw right circle, Some how it looks starched.
I am sharing code and image for the same. Please help me out.

    
![screen shot 2016-12-21 at 4 34 37 pm](https://cloud.githubusercontent.com/assets/5022126/21386946/67306512-c79b-11e6-9a59-b91581f2e2bd.png)

float x = 0;
    float y = 0;
    float x1 = 0;
    float y1 = 0;
    int num = 360;
    
    MaplyCoordinate coords[num];
    
    for (int i = 0; i < num; i++)
    {
        x = lat + radius * sin(i * 2 * M_PI/num);
        y = lon + radius * cos(i * 2 * M_PI/num);
        if(i==0)
        {
            x1 = x;
            y1 = y;
        }
        coords[i] = MaplyCoordinateMakeWithDegrees(y, x);
    }
    coords[num] = MaplyCoordinateMakeWithDegrees(y1, x1);
    
    NSDictionary *vecDesc = @{
                              kMaplyColor: [UIColor whiteColor],
                              kMaplyEnable: @(YES),
                              kMaplyVecWidth: @(1.5),
                              kMaplyVecHeight: @(0.0),
                              kMaplyDrawPriority: @(100000),
                              kMaplySubdivType: kMaplySubdivGreatCircle,
                              kMaplySubdivEpsilon: @(0.001)
                              };

    MaplyVectorObject *vec = [[MaplyVectorObject alloc] initWithLineString:coords numCoords:num+1 attributes:nil];
    
    return  [globeController addVectors:@[vec] desc:vecDesc];

**Comment by rohitnagori** [comment]
I also tried this but it does not draw the proper circle. Please see the code & image below.
MaplyShapeCircle *vec = [[MaplyShapeCircle alloc] init];
    vec.center = WGCoordinateMakeWithDegrees(lon, lat);
    vec.radius = radius;
    vec.height = 0.00;
    NSDictionary *vecDesc = @{
                                kMaplyColor: [UIColor blueColor],
                                kMaplySubdivType: kMaplySubdivGreatCircle,
                                kMaplyDrawPriority: @(100000),
                                kMaplyZBufferRead: @(NO),
                                kMaplySubdivEpsilon: @(0.001),
                                kMaplyVecWidth: @(0.5),
                                kMaplySampleX : @(100),
                                kMaplyShapeSampleX : @(100),
                                kMaplyFilled : @(false),
                                kMaplyVecMinSample : @(100),
                                };
    
     return  [globeController addShapes:@[vec] desc:vecDesc];
![screen shot 2016-12-21 at 5 23 43 pm](https://cloud.githubusercontent.com/assets/5022126/21388443/4b116c12-c7a2-11e6-85bb-34286065e028.png)

**Comment by rohitnagori** [comment]
Sry I needed to add one more qus that is.. what i need to pass in radius ? like if i want to draw circle for 30km then what would be radius value. I explored the documentation for radius, It says it is just a display unit.

**Comment by mousebird** [comment]
Vectors are in geographic.  So to draw a proper circle you need to generate the points in a local coordinate system and then convert them to geographic.

**Comment by rohitnagori** [comment]
I am not getting it. Are you saying tha I have to draw a circle using x, y coordinates and convert it to lat long then ? If yes please guide me to the right path or correct me.
Thanks in advance.

**Comment by mousebird** [comment]
Vector coordinates are in lat/lon, but when projected onto the globe (or map) lat/lon gets stretched, depending on where you are.

If you want a proper circle that actually looks like a circle you have to generate the points in a coordinate system like SphericalMercator with a center near where you're looking.  Then you can convert them to geographic.

**Comment by rohitnagori** [comment]
I am bit lost here..as you said, I searched for a formula to convert the coordinates to   SphericalMercator with center and it draws the circles properly. But its getting displaced by original center. I have used the below formula


`#define DEG2RAD(a)   ((a) / (180 / M_PI))
#define RAD2DEG(a)   ((a) * (180 / M_PI))
#define EARTH_RADIUS 6378137

double y2lat_d(double y)
{
    return RAD2DEG( atan(exp( DEG2RAD(y) )) * 2 - M_PI/2 );
}
double x2lon_d(double x)
{
    return x;
}
`
In the first post on this issues I had generated the coordinates for the circle, after that i am passing all that coordinates to this formula. It is drawing proper circle but getting displaced from original position. Please see the below image.

![screen shot 2016-12-23 at 6 51 14 pm](https://cloud.githubusercontent.com/assets/5022126/21454875/d2dbc2b4-c941-11e6-8acc-65ffdea4acd5.png)

Can you help me out in math work. I am stuck here. Your help will be appreciable.
Thanks a lot.

**Comment by mousebird** [comment]
There's a SphericalMercator class in the toolkit.  You can just use that.

The problem is likely that you're not converting the circle points back to geographic.

**Comment by rohitnagori** [comment]
Thanks a lot, It helped me out.

**Comment by IOSDeveloperProgrammer** [comment]
@rohitnagori  I am not getting. i am stuck with create a draw circle using coordinate long / lat values. could you please help me

**Comment by rohitnagori** [comment]
@IOSDeveloperProgrammer What approach you are following.

**Comment by IOSDeveloperProgrammer** [comment]
![20170111_130005](https://cloud.githubusercontent.com/assets/20769065/21839545/4045beac-d7fe-11e6-843d-c7678bcbd2f6.jpg)

**Comment by rohitnagori** [comment]
Yes my above code can generate the circle coordinate. If you provide lat long and radius. You can use above code.

**Comment by stapleup** [comment]
Hi @rohitnagori, can you please tell me how you solved this issue? I have created the circle but it is appearing like it is in your first image, more like an egg shaped.

@mousebird, is there any example code available for SphericalMercator?

Thanks

**Comment by mousebird** [comment]
There's no specific example for calculating those points, no.
