### ISSUE TITLE
Critical :: Under certain situations all objects get stuck on screen and will not remove

### ISSUE THREAD

**Issue by bryanheitman** [mousebird/WhirlyGlobe#815]
Currently I can reproduce in full app implementation easily but do not have a test project to recreate this bug. Recommend sending me strategic log entry points to determine what is going on.

This started either with commits in the last few months and/or with iOS10, undetermined.

To fix, user force closes app. I currently do not have any code that will destroy a WhirlyGlobeViewController and rebuild w/o app restart, this may also fix it but that's undetermined.

**Comment by mousebird** [comment]
I think I may have run across the problem.  Give the latest tree a try and let me know.

**Comment by bryanheitman** [comment]
Wilco

**Comment by bryanheitman** [comment]
After recreating problem, updating code, and re-testing I cannot reproduce this problem after testing. I have 80% confidence this issue is solved. What was it?

Thanks

**Comment by mousebird** [comment]
A timing issue for requests going on to the background thread.  If things happened fast enough, there was a possibility that the background thread would stop updating.

It would look exactly like what you saw.

**Comment by mousebird** [comment]
Pretty sure this is fixed now.

**Comment by bryanheitman** [comment]
Agree
