### ISSUE TITLE
How can I add weather data on globe.

### ISSUE THREAD

**Issue by rohitnagori** [mousebird/WhirlyGlobe#816]
I want to add weather data on globe. Is there any class in tool which can help me doing this ? If yes how can I use those classes and what kind of data I need.
I will get data in run time from hardware unit fit into the Pilot cock pit. Data will not come from server.

**Comment by mousebird** [comment]
Take a look at the AnimatedBasemapTestCase in the AutoTester.

Are you on support?  You're doing some very complicated stuff.

**Comment by rohitnagori** [comment]
Not right now on support. How can I be there on support.

**Comment by rohitnagori** [comment]
Where I can find "AnimatedBasemapTestCase"

**Comment by mousebird** [comment]
If you're interested in a support contract, please send me email at contact@mousebirdconsulting.com.  Some of the things you are doing are complicated enough that support would help.

As for [AnimatedBasemapTestCase](https://github.com/mousebird/WhirlyGlobe/blob/develop_2_4_1/WhirlyGlobeSrc/AutoTester/AutoTester/testCases/AnimatedBasemapTestCase.swift), you can find that in the AutoTester in the source distribution.

**Comment by rohitnagori** [comment]
If I draw shaders on globe. How would I ensure that It will be drawn on right location.
I have few question for you. It will be great help If you can answer them.
1) I saw your animatedbasemap test case. As I understood you downloading some images and converting them to blue and green effect.
2) Here I will be having bit map Information about weather. I will try to convert those information to bitmap image. Then what is the great approach to do it.

**Comment by mousebird** [comment]
I have a whole option called ImageryPro that's just for this.  It does require the data be in an optimized format, but is otherwise easy to use.

If you have a budget, you should consider buying ImageryPro.  If you want to try to do it yourself, take a look at the AnimatedColorRampTestCase.

**Comment by rohitnagori** [comment]
Hello Steve,
Thanks for your suggestion. Buying anything will depend on client decision. I am just a developer working on app. As first of all I will have to try by my own. That is why I was seeking for your help.

**Comment by mousebird** [comment]
If the client has their own weather data, then I would strongly recommend ImageryPro.  We used an indexed & stacked data format that significantly speeds up data downloads, rendering, and reduces memory usage.  It's a huge, huge improvement over simple image display.
