### ISSUE TITLE
How can add outline and Fill color to the flight path

### ISSUE THREAD

**Issue by rohitnagori** [mousebird/WhirlyGlobe#817]
![screen shot 2016-12-27 at 10 40 13 am](https://cloud.githubusercontent.com/assets/5022126/21491245/4e05a888-cc21-11e6-9ac2-0c72a8df5c1a.png)

The above line has outline and fill color to it. I use below code to draw path but not able to add out line and fill color to it.
MaplyVectorObject *v = [[MaplyVectorObject alloc] initWithLineString:z numCoords:2 attributes:nil];

**Comment by mousebird** [comment]
To get a line with a nice outline, you use two WideVectors, the second slightly smaller than the first with a higher kMaplyDrawPriority.

**Comment by rohitnagori** [comment]
Ok, Got it.
I really appreciate your suggestions. Thanks

**Comment by rohitnagori** [comment]
How can I apply transparency to the wide vector.
I tried this but not working
NSDictionary *vecDesc = @{
                                  kMaplyColor: [UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:0.1],
                                  kMaplyVecWidth: @(8.0),
                                  kMaplyVecHeight: @(0.0),
                                  kMaplyDrawPriority: @(100000),
                                  kMaplySubdivType: kMaplySubdivGreatCircle,
                                  kMaplySubdivEpsilon: @(0.001),
                                  kMaplyFilled : @(false)
                                  };

![screen shot 2017-01-10 at 1 57 28 pm](https://cloud.githubusercontent.com/assets/5022126/21798924/00aad802-d73d-11e6-8c30-6fd6d6b84e5c.png)

**Comment by mousebird** [comment]
You need to multiply the alpha through the rest of the color.

**Comment by rohitnagori** [comment]
great it worked.. Thanks steve
