### ISSUE TITLE
problem with pin annotation disappearing & Rotate 

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [mousebird/WhirlyGlobe#820]
@mousebird  Hi ,
I need to show annotation on globe , but it's disappearing on globe when user was rotating globe. The markers can't be fixed. where i should fix it ? and How to rotate marker at facing direction when user was rotate globe UP / Down ?

**Comment by mousebird** [comment]
I'm not quite sure what problem you are describing.

**Comment by IOSDeveloperProgrammer** [comment]
![screenshot_20170103-100335](https://cloud.githubusercontent.com/assets/20769065/21631730/ec409de8-d264-11e6-823f-3e188296a420.png)
 @mousebird  markers showing one direction when user was rotate globe . I need to show above image .

**Comment by mousebird** [comment]
That's rather beautiful.

Well, markers are currently only 2D or attached to the surface of the earth.  To do this offset thing you could try to do it as a ScreenMarker with an offset.

**Comment by IOSDeveloperProgrammer** [comment]
@mousebird 
`MaplyScreenMarker *marker = [[MaplyScreenMarker alloc] init];
        marker.image = icon;
        marker.offset = CGPointMake(10, -13);//ven
        marker.images=[imageNameArray objectAtIndex:ii];
        marker.loc = capitals[ii];
//        marker.size = CGSizeMake(30,30);
        marker.layoutImportance= MAXFLOAT; // 10
        marker.selectable = NO;
        [markers addObject:marker];

i'd tried with above code but still not getting anything do like that.what is wrong in that code ?`

**Comment by mousebird** [comment]
What do you get, though?

**Comment by IOSDeveloperProgrammer** [comment]
![20170104_123644](https://cloud.githubusercontent.com/assets/20769065/21634111/aa969b2a-d27a-11e6-96c1-2ccf6ab30b34.jpg)

@mousebird youp  itS working. I was passing  single image then  the result was shown above image. suppose If I was passing multiple  images then  I'm getting error

**Comment by IOSDeveloperProgrammer** [comment]
![20170104_123644](https://cloud.githubusercontent.com/assets/20769065/21634233/9d68e38a-d27b-11e6-9431-7ac6ed531d7d.jpg)
@mousebird  the above result was shown wherever I was passing single image into add marker. Suppose if was add multiple image into marker I was getting error here

**Comment by mousebird** [comment]
For one thing I see you setting marker.images to an NSString rather than a NSArray of UIImages (or MaplyTextures).
For another, an array of images will trigger an animation, but you need to set the period.

**Comment by IOSDeveloperProgrammer** [comment]
@mousebird  sorry for i won't understand your answer that " an array of images will trigger an animation, but you need to set the period".  how to get multiple images ? How can i set the period ?

**Comment by mousebird** [comment]
I'm sorry, I don't understand what you're trying to do.

If you want to display a single image per marker, you can do so using [this tutorial](https://mousebird.github.io/WhirlyGlobe/tutorial/ios/screen_markers.html)

**Comment by IOSDeveloperProgrammer** [comment]
@mousebird I'm trying to display different images per marker. suppose if i having 10 marker, i want display 10 marker with 10 images (one marker with one image).  Yes, I did that displayed a single image per marker.

when i was using below code then i'm getting error.
` marker.images=[imageNameArray objectAtIndex:ii];`

**Comment by IOSDeveloperProgrammer** [comment]
@mousebird  Thanks for supported us finally i got it.
