### ISSUE TITLE
Wide Vectors GeoJSON issue not closing polygon

### ISSUE THREAD

**Issue by bryanheitman** [mousebird/WhirlyGlobe#821]
See GeoJSON example:

{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                                                                  
"features": [
{ "type": "Feature", "properties": { "gml_id": "Airspace1", "identifier": "2159c75c-bcf6-41d4-9afb-d4533bb8f9ad", "beginPosition": "2013-01-10T09:01:00Z", "interpretation": "BASELINE", "sequenceNumber": 1, "correctionNumber": 0, "timeSlice|AirspaceTimeSlice|featureLifetime|TimePeriod|beginPosition": "2013-01-10T09:01:00Z", "designator": "MCRYSTAL", "name": "CRYSTAL MOA, TX", "operation": "BASE", "operationSequence": 1, "upperLimit": 180, "upperLimit_uom": "FL", "upperLimitReference": "STD", "lowerLimit": 6000, "lowerLimit_uom": "FT", "lowerLimitReference": "MSL", "propertyName": [ "upperLimit", "lowerLimit" ], "note": [ "EXCLUSIVE", "INCLUSIVE" ], "timeSlice|AirspaceTimeSlice|annotation|Note|propertyName": "legalDefinitionType", "timeSlice|AirspaceTimeSlice|annotation|Note|translatedNote|LinguisticNote|note": "CRYSTAL MOA, TX : Altitudes   6,000 feet MSL to but not including FL 180. \nUsing agency.  San Antonio Air Logistics Center, Kelly AFB, TX \nBoundaries   The area between the 30 NM radius arc and the 70 NM radius arc of the Laredo, TX, VORTAC (lat. 27¬∞28'44\"N., long. 99¬∞25'04\"W.), extending clockwise from the 310¬∞(M) radial to the 350¬∞(M) radial of the Laredo VORTAC excluding Restricted Area R-6316. \nControlling agency   FAA, Houston ARTCC \nTimes of use   0700-1800 local time daily; other times by NOTAM.", "saaType": "SUA", "administrativeArea": "TEXAS", "conditionalExclusion": "YES", "legalDefinitionType": "HUMAN", "suaType": "MOA" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -100.287605425248387, 28.356609244476893 ], [ -100.216083124570233, 28.40828842669417 ], [ -100.140570405801441, 28.455412734105543 ], [ -100.06143978884964, 28.497746382042202 ], [ -99.979083389913299, 28.535077271027077 ], [ -99.893910884450207, 28.56721814156834 ], [ -99.806347344472258, 28.594007598821449 ], [ -99.716830964070411, 28.615310999598826 ], [ -99.625810688485984, 28.631021195119004 ], [ -99.533743763322505, 28.641059123891118 ], [ -99.441093221640998, 28.64537425021522 ], [ -99.440833, 28.648333 ], [ -99.4275, 27.98 ], [ -99.467121833367131, 27.9769776422701 ], [ -99.50634098307232, 27.972705122900535 ], [ -99.545122762748562, 27.966016043504723 ], [ -99.58327576609463, 27.956943438134957 ], [ -99.620611817481702, 27.945532101798584 ], [ -99.656946934559116, 27.931838360243859 ], [ -99.692102265947909, 27.915929780833174 ], [ -99.725904998766538, 27.897884826220256 ], [ -99.758189230718628, 27.877792452876491 ], [ -99.787778, 27.856667 ], [ -100.285278, 28.358889 ] ] ] } }
]
}

**Comment by bryanheitman** [comment]
NSMutableDictionary *vectorDict = [[NSMutableDictionary alloc] initWithDictionary:@{
                                                                                            kMaplyColor: [myCommon color_alpha:[UIColor colorWithRed:130/255.0 green:0/255.0 blue:130/255.0 alpha:1]  alpha:0.5] ,
                                                                                            kMaplyVecWidth: [NSNumber numberWithFloat:2],
                                                                                            kWGFilled: @false,
                                                                                            kMaplyDrawPriority: [NSNumber numberWithFloat:101],
                                                                                            kMaplySelectable: @(true),
                                                                                            kMaplyWideVecEdgeFalloff: @(1.0),
                                                                                            kMaplyWideVecJoinType: kMaplyWideVecMiterJoin,
                                                                                            kMaplyWideVecCoordType: kMaplyWideVecCoordTypeScreen,
                                                                                            kMaplyWideVecMiterLimit: @(10)
                                                                                            }]; //kWGVecWidth,kMaplyVecWidth
     
        
        
        [wg_objects addObject:[layer.viewC addWideVectors:[objects objectForKey:@"moa"] desc:vectorDict mode:MaplyThreadCurrent]];

**Comment by mousebird** [comment]
Can you email me this file?  It's getting mangled through github.

**Comment by mousebird** [comment]
Should be fixed now.
I notice it wasn't a closed polygon.  You may need to repeat the first point.

**Comment by bryanheitman** [comment]
If it’s not a closed polygon then why does a non-wide vector show it closed?

**Comment by mousebird** [comment]
I guess that version is doing the closing.  I'll check.

**Comment by mousebird** [comment]
I'd fixed the turns, which were looking truncated.  Though I realize that may not be what you were talking about originally.

The polygon should be explicitly closed now.

**Comment by bryanheitman** [comment]
Ok will re-test in a future version.

-Bryan
