### ISSUE TITLE
MaplyAtmosphere issue in Swift

### ISSUE THREAD

**Issue by Minoworks** [mousebird/WhirlyGlobe#824]
![2017-01-12 17_32_21](https://cloud.githubusercontent.com/assets/4302336/21882320/439013f6-d8ed-11e6-8f37-af83801a57a4.gif)

- wired particles...... in Atmosphere

        let sun = MaplySun(date: Date())
        let light = sun.makeLight()
        let atmosObj = MaplyAtmosphere(viewC: globeViewC)
        atmosObj.setWavelengthRed(0.650, green: 0.579, blue: 0.475)
        atmosObj.setSunPosition(sun.getDirection())

I'm using develop_2_4_1 version.

**Comment by jmnavarro** [comment]
weird... Does it work in Obj-C?

**Comment by Minoworks** [comment]
@jmnavarro no I didn't test it in Objective-C

**Comment by mousebird** [comment]
It looks like the atmosphere is appearing on top of the globe rather than behind.

I suspect the blue marble layer is being added at drawPriority = 0.  Either set it to kMaplyImageLayerDrawPriorityDefault or, if it can't be set, then use another base map layer.

**Comment by Minoworks** [comment]
@mousebird is this right?

        let layer = globeViewC.addSphericalEarthLayer(withImageSet: "lowres_wtb_info")
        baseLayer = layer! as MaplyViewControllerLayer
        baseLayer.drawPriority = kMaplyImageLayerDrawPriorityDefault;

**Comment by mousebird** [comment]
Did it work?

**Comment by Minoworks** [comment]
@mousebird no it's not working. is there any example of atmosphere implementation in swift?

**Comment by mousebird** [comment]
StarsSunTestCase in the AutoTester

**Comment by Minoworks** [comment]
@mousebird where can I find it?

**Comment by rghosh0** [comment]
https://github.com/mousebird/WhirlyGlobe/tree/develop_2_4_1/WhirlyGlobeSrc/AutoTester

**Comment by mousebird** [comment]
Yup, looks like drawPriority isn't working for the blue marble layer.  I'd recommend using something else.  That layer is pretty out of date.
