### ISSUE TITLE
Circle line go wierd on zero lat long

### ISSUE THREAD

**Issue by rohitnagori** [mousebird/WhirlyGlobe#825]
Hi Steve, 
As you suggested me, I am able to draw proper circle now, but there is some problem with it. It go little weird on (0.0,0.0) lat long. I am attaching the screen shot.

![screen shot 2017-01-13 at 5 46 41 pm](https://cloud.githubusercontent.com/assets/5022126/21930182/9d61323e-d9ba-11e6-9be3-fc866bdd7bd5.png)

**Comment by mousebird** [comment]
If you're overlapping the poles you may need to break the line up.

**Comment by rohitnagori** [comment]
Can you please elaborate. I did not understand.

**Comment by mousebird** [comment]
Things get weird at the poles if you're working in geographic.  Breaking up the lines might help a bit.

**Comment by rohitnagori** [comment]
How and where I will have to break the line. Are you taking about for specific angle area for which I have to break the line.
