### ISSUE TITLE
How to get the Globe Center Position?

### ISSUE THREAD

**Issue by bintu1234** [mousebird/WhirlyGlobe#828]
Hi How can we get the globe center position with out userInteraction.When i rotate and stop then i want to know the center Lotitude and Longitude.Please help me,Thank you

**Comment by mousebird** [comment]
iOS or Android?

**Comment by bintu1234** [comment]
iOS

**Comment by mousebird** [comment]
https://mousebird.github.io/WhirlyGlobe/reference/ios_2_4/Classes/WhirlyGlobeViewController.html#//api/name/getPosition:height:

**Comment by bintu1234** [comment]
Thanks for the Replay But i want with out user interaction suppose if i use 
`- (void)getPosition:(MaplyCoordinate *)pos height:(float *)height`,What about MaplyCoordinate how will i provide this.Please help me

**Comment by mousebird** [comment]
I don't understand what you're asking.

**Comment by codaman** [comment]
getPosition returns center geo coordination
