### ISSUE TITLE
Samsung Alpha - Wiko Cink Five no displaying Globe

### ISSUE THREAD

**Issue by mranchon** [mousebird/WhirlyGlobe#829]
Hi, I have a huge problem when I want to display the Globe on my Wiko and my Samsung. Both are with API 21.
When I launch my activity fragment, I also load a class that named GlobeFragment.java that initialize the globe and add markers from an API. But, on these phones, my screen is black and when I tap on the screen, my app is crashing.
I develop on Huawei P9 lite for my tests, and I have no problem to display the globe. Can you help me please ?

Thank you in advance ! (sorry for my basic english !)
![screenshot_2017-01-17-08-51-50](https://cloud.githubusercontent.com/assets/11455455/22055118/c7b04852-dd59-11e6-92f5-9dc998d9ad13.png)

**Comment by mranchon** [comment]
Hi, I resolved my issue. In fact, I had to use v4.fragment to display the globe. It's works perfectly !

**Comment by mousebird** [comment]
Ah, makes sense.  Glad you were able to resolve it.
