### ISSUE TITLE
[Android] Recovery of latitude and longitude in the userDidTap method

### ISSUE THREAD

**Issue by Conan42** [mousebird/WhirlyGlobe#830]
I would like to retrieve latitude and longitude in the usual format +90 to -90 ° latitude and +180 to -180 ° longitude in the userDidTap method. How to do?

I would also like to open a small window to put a popup menu at the Tap or LongPress, anyone has an idea?

**Comment by mousebird** [comment]
You get radians back, so just covert them to degrees.  degrees = radians/PI * 180

You can add a MaplyAnnotation if you'd like.
