### ISSUE TITLE
[Android] Need PopupWindow

### ISSUE THREAD

**Issue by Conan42** [mousebird/WhirlyGlobe#831]
I really need PopupWindow with a menu inside at the location of the click on the Map or the Globe to continue my project. Or I would know how to oblige to abandon this great API. You speak to me of using MaplyAnnotation. But it seems to me that this class is not implemented in the version Android of your API, only on iOS. Would anybody have an idea?

**Comment by mousebird** [comment]
I see, Android.  No there's no MaplyAnnotation on Android.  Views on top of OpenGL views don't work all that well so we use ScreenMarkers instead.
