### ISSUE TITLE
Overlay GRIB2 files

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#832]
Good evening,

I am still trying to represent 3D weather for my Ph.D. project. I found a data server that gives me 3D reflectivity of precipitation. However, the format is GRIB2. Is there a way to process or overlay these .grib2 files?

Cheers,

Sebastien.

**Comment by mousebird** [comment]
Not directly.  I've discussed it with a potential client, but that project hasn't moved forward.
