### ISSUE TITLE
[iOS]MaplyScreenMarker transparency issue

### ISSUE THREAD

**Issue by nhevaweb** [mousebird/WhirlyGlobe#833]
Hi,

I'm having an issue with MaplyScreenMarker when using a UIImage with some alpha.
![markers](https://cloud.githubusercontent.com/assets/23048593/22256688/d6c00b78-e25b-11e6-955b-7c81b28f8db7.png)
You can see at the top the image with (alpha = 1) and at the bottom (alpha = 0.5) on the blue circle.
I forced the MaplyScreenMarker color property to whiteColor since the image is tinted with that color and yet the color seems really dark.

Anyone else having this problem ?

**Comment by mousebird** [comment]
Multiply the alpha through the rest of the color.

**Comment by nhevaweb** [comment]
What do you mean @mousebird ?

I'm actually rendering an UIView to an UIImage for this ScreenMarker with the background rounded and a background color with an alpha.

If I display this UIImage on a random UIView, the color with the alpha component is fine.
If I'm using the same color as the fillColor of a MaplyVectorObject, the color is also fine on the map.

Thx for your time.

**Comment by mousebird** [comment]
What's the exact color?

**Comment by nhevaweb** [comment]
hexcode: 36A9DF
But It doesn't matter what color I set for the circle, I tried to render a UIImage from UIView with redColor with 0.5 alpha and I'm still getting a weird dark red color like it's mixed up with something else when i touch the alpha...

**Comment by mousebird** [comment]
I'm not sure I completely understand, but I'll explain how alpha works with markers and labels (and everything else).

If you want something fully opaque use (1.0,1.0,1.0,1.0).  If you want something half transparent use (0.5,0.5,0.5,0.5).

**Comment by nhevaweb** [comment]
Thx for answering!

All right let me explain then with this screenshot:
![screen shot 2017-01-26 at 10 38 10](https://cloud.githubusercontent.com/assets/23048593/22326598/ab589a28-e3b3-11e6-96d7-712a40806099.png)

As you can see the marker is way darker than the original image... That is my problem.

**Comment by mousebird** [comment]
Huh, that's interesting.  I'm not sure what the blending operation looks like for a UIKit overlay.

For the screen shader I can tell you we multiply the color, component by component with the pixel color of the provided UIImage.

**Comment by nhevaweb** [comment]
Sorry for this late reply.
Thanks for your answer, it works.
