### ISSUE TITLE
Prevent shape objects from showing through the globe

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#837]
Big polygons cut through the globe, instead of curving around with it. Is there a way to fix this?

**Comment by amirfl** [comment]
![img_4159](https://cloud.githubusercontent.com/assets/364326/22450752/c496833e-e736-11e6-9f68-ee50cc98adbc.PNG)

**Comment by mousebird** [comment]
Large polygons have to be subdivided to follow the globe.

Take a look at the TextureVectorTestCase in the AutoTester on iOS.
That example does a nice job of using clipToGrid: and tesselate:
