### ISSUE TITLE
Accesing MaplyLocationTracker's location manager

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#839]
Is it possible to get access to MaplyLocationTracker's location manager? My app has a button that allows the user to centers the map over his present location. Currently I'm using a separate CLLocationManager to manage that task. 
I would assume that since WhirlyGlobe already uses a CLLocationManager for the user location marker, my additional location manager is redundant.

**Comment by mousebird** [comment]
Can you expose this somewhere?

**Comment by rghosh0** [comment]
OK, will do.
