### ISSUE TITLE
Support for screen display of map scale

### ISSUE THREAD

**Issue by pbmorton** [mousebird/WhirlyGlobe#840]
My goal is to display a map scale ruler on a 2D map as shown in the attached screenshot. An easy and reusable solution for all users of WhirlyGlobe would be to have MaplyViewController display a scale, where this features is enabled or disabled via a MaplyViewController property. That is not supported, so instead I'm trying to calculate "meters across screen" for the displayed map so I can draw my own scale ruler on the map. My ViewController creates the MaplyViewController. When the map changes it reads MaplyBaseViewController.currentMapScale(). The currentMapScale cannot ASAIK be transformed to "meters across screen". I'm using a MaplySpericalMercator coordinate system at about -34 degrees south (WGS84). I find "meters across screen" != (currentMapScale * frameSize.x() * 0.00096).

![hamelin_bay_map](https://cloud.githubusercontent.com/assets/8908488/22730112/8a0caf72-ee20-11e6-9d9f-6bcb91429259.jpg)

**Comment by jerald-acacus** [comment]
+1

**Comment by mousebird** [comment]
The mapScale calculated there is for loading.  I'm fine with that as it is, but there is probably use for another version.

The way I've done this in the past is to sample a few points and calculate a value from that.  It works both on globe and map and deals with all sorts of strange problems.
