### ISSUE TITLE
missing laszip_api.h

### ISSUE THREAD

**Issue by auzreal** [mousebird/WhirlyGlobe#841]
I used pod settings below:
pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe', :branch => 'master'
and it keeps informing that laszip_api.h is missing, what should I do to import this lib?

**Comment by mousebird** [comment]
The pod is broken with respect to LASZip at the moment.  We'll take a look.

**Comment by rghosh0** [comment]
OK, I excluded the LASzip library from the cocoapod.  Now the settings in your example work.
