### ISSUE TITLE
Building from source script issues

### ISSUE THREAD

**Issue by rghosh0** [mousebird/WhirlyGlobe#842]
When I build from source on my Mac (Sierra 10.12.3), I run into a problem:

> /usr/local/Cellar/android-ndk/r13b/toolchains/mips64el-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: cannot find crtbegin_so.o: No such file or directory
> /usr/local/Cellar/android-ndk/r13b/toolchains/mips64el-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: cannot find crtend_so.o: No such file or directory

I don't have this problem when repeating in an XUbuntu 16.10 virtual image. Not sure why. My workaround for Mac is to exclude the mips64 architecture by changing build.gradle. There are two places where there is an APP_ABI argument for ndk-build.  I change it to the following:

`'APP_ABI=x86_64 x86 armeabi armeabi-v7a armeabi-v7a arm64-v8a'`

Also, in either case, I have another problem:

> /usr/local/Cellar/android-ndk/r13b/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:49: error: undefined reference to '__atomic_fetch_add_4'
> /usr/local/Cellar/android-ndk/r13b/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:49: error: undefined reference to '__atomic_fetch_add_4'
> /usr/local/Cellar/android-ndk/r13b/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:53: error: undefined reference to '__atomic_fetch_add_4'
> /usr/local/Cellar/android-ndk/r13b/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:53: error: undefined reference to '__atomic_fetch_add_4'

My workaround is adding -latomic to LOCAL_LDLIBS in jni/Android.mk

In Mac, I just followed the instructions on the tutorial page. In linux I got the latest Android Studio from their website (couple of days ago) and installed the NDK, CMake, and LLDB through SDK Manager.

**Comment by mousebird** [comment]
Thanks!
