### ISSUE TITLE
Code crashes on map teardown

### ISSUE THREAD

**Issue by pbmorton** [mousebird/WhirlyGlobe#843]
For branch "develop". When shutting down a MaplyViewController  MaplyViewController.viewWillDisappear, MaplyBaseViewController.dealloc and teardown are called. A couple of seconds later the code crashes on some platforms. The attached screen capture is the xcode stack trace.  I'm not observed this on all testing platforms I've tried. It always shows up on my test ipad running a debug build
![capture](https://cloud.githubusercontent.com/assets/8908488/23047333/2376b85e-f4ea-11e6-905b-2e385303ca0f.JPG)

**Comment by mousebird** [comment]
I've put in more guard code.  Let me know if this helps.

**Comment by pbmorton** [comment]
Latest develop branch code is still crashing about every 3rd or so time I tear down using:

    override func viewDidDisappear(_ animated: Bool) {
        print("MapViewController " + #function)
        
        if (baseViewC != nil) {
            baseViewC.willMove(toParentViewController: nil)
            baseViewC.view.removeFromSuperview()
            baseViewC.removeFromParentViewController()
            baseViewC.teardown() // explicitly called as recommended by Steve
            baseViewC = nil
            mapViewC = nil
        }
        super.viewDidDisappear(animated)
    }

**Comment by mousebird** [comment]
Are you using your own MBTiles vectors?
Can I borrow it?

**Comment by pbmorton** [comment]
Yes. I've sent them attached to a separate email.

**Comment by mousebird** [comment]
I managed to cause several interesting bugs, though not the exact one you saw.  They're all timing problems where the loading continues while the view controller is shutting down.

Those are now fixed so let me know if your problem is fixed as well.

**Comment by pbmorton** [comment]
I still sometimes see a crash on teardown related to screen labels. Attached are a few screen captures. If you know of some way I can better record xcode's debug navigator to send to you let me know.
![capture1](https://cloud.githubusercontent.com/assets/8908488/24086664/bf19817a-0d4e-11e7-860d-d0892fbf2b2d.JPG)
![capture2](https://cloud.githubusercontent.com/assets/8908488/24086661/bf08f3b4-0d4e-11e7-8336-c2ccf545bdf5.JPG)
![capture3](https://cloud.githubusercontent.com/assets/8908488/24086659/bef225d0-0d4e-11e7-9cc8-f3b11670a77a.JPG)
![capture4](https://cloud.githubusercontent.com/assets/8908488/24086660/bef82a20-0d4e-11e7-9e85-b801778c7247.JPG)
![capture5](https://cloud.githubusercontent.com/assets/8908488/24086662/bf0e5be2-0d4e-11e7-8de6-583e3da9a888.JPG)
![capture6](https://cloud.githubusercontent.com/assets/8908488/24086663/bf18eecc-0d4e-11e7-92bd-f1ade7725c06.JPG)
![capture7](https://cloud.githubusercontent.com/assets/8908488/24086665/bf3c41a6-0d4e-11e7-9bf2-37816e127da5.JPG)

**Comment by mousebird** [comment]
That looks good, thanks.
Since these are running on dispatch queues it's a matter of shutting them down at the right time.

As an aside, you've probably got a lot of data in each vector tile if they're taking so long to process.  Crashes are crashes, but this might load inefficiently.

**Comment by pbmorton** [comment]
I'll leave the vector tiles fat for now as they are doing a good job of
testing. I'll fix them later thanks.

**Comment by mousebird** [comment]
No reason to make them smaller for this bug.  Just a comment in general.

**Comment by mousebird** [comment]
Can you set a breakpoint in teardown in MaplyBaseViewController?
I need to know if that's getting called when the view controller is ending.

**Comment by mousebird** [comment]
Is this still happening?

**Comment by pbmorton** [comment]
Not seeing this crash anymore. The App has been release and has 135
downloads so far with no reported crashes.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-6402637093944661927_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mousebird** [comment]
Nice!

Hey, can I add this to the WhirlyGlobe apps page?

**Comment by pbmorton** [comment]
Yes, of course Steve. I'm happy to do anything I can to help you promote
your library. You've certainly helped me.

The next thing I'd like to do is display a map scale. You can expect some
more questions about this soon!
