### ISSUE TITLE
iOS - Current state of vector tile styles?

### ISSUE THREAD

**Issue by dangustafsson** [mousebird/WhirlyGlobe#844]
I am working on an app incorporating Whirlyglobe and it uses offline vector tiles. For a while now I have been developing using the MaplyVectorStyleSimpleGenerator to style the tiles but I need to work on the actual look of the map now.
I have been going over the AutoTester app but I cannot figure out how to actually style locally held tiles in mbtiles format using any MaplyVectorStyleDelegate other than the MaplyVectorStyleSimpleGenerator.  

For testing purposes I am using an mbtiles file downloaded from openmaptiles.org. I am also using the 'France.mbtiles' file included with the AutoTester. They both produce the same results.

Here is the code I use. I have included several styles in the snippet. In real testing only a single style is used at the time, the below snippet is just to show sample of how the various styles are loaded.

```
- (void) setupMap {
	
	// Create Main map view
	self.mapViewController = [[WhirlyGlobeViewController alloc] init];
	[self.view addSubview:_mapViewController.view];
	_mapViewController.view.backgroundColor = [UIColor greenColor];
	_mapViewController.view.frame = self.view.bounds;
	_mapViewController.clearColor = [UIColor blackColor];
	_mapViewController.frameInterval = 2;
	_mapViewController.delegate = self;

	
	// Style the map
	// -------------
	
	
	// This doesn't work. I don't know if MapzenGLStyle is supported with these tiles
	//
	NSString *stylePath = [[NSBundle mainBundle] pathForResource:@"MapzenGLStyle" ofType:@"json"];
	NSData *styleData = [NSData dataWithContentsOfFile:stylePath];
	MapnikStyleSet *style = [[MapnikStyleSet alloc] initForViewC:_mapViewController];
	[style loadJsonData:styleData];
	[style generateStyles];
	
	
	// This doesn't work. I don't know if this type of MaplyVectorStyleDelegate works with the tile format.
	//
	SLDStyleSet *style = [[SLDStyleSet alloc] initWithViewC:_mapViewController useLayerNames:YES relativeDrawPriority:0];
	NSURL *styleUrl = [[NSBundle mainBundle] URLForResource:@"MapzenSLDStyle" withExtension:@"sld"];
	[style loadSldURL:styleUrl];
	

	// This is partly working. It is only showing water(blue) and land(mapView clearColor)
	//
	NSString *stylePath = [[NSBundle mainBundle] pathForResource:@"MapzenStyles" ofType:@"json"];
	NSData *styleData = [NSData dataWithContentsOfFile:stylePath];
	MapnikStyleSet *style = [[MapnikStyleSet alloc] initForViewC:_mapViewController];
	[style loadJsonData:styleData];
	[style generateStyles];
	
	
	// This is partly working. It is only showing water(blue) and land(mapView clearColor)
	//
	NSString *stylePath = [[NSBundle mainBundle] pathForResource:@"osm-bright" ofType:@"xml"];
	NSData *styleData = [NSData dataWithContentsOfFile:stylePath];
	MapnikStyleSet *style = [[MapnikStyleSet alloc] initForViewC:_mapViewController];
	[style loadXmlData:styleData];
	[style generateStyles];
	

	// This is the only working style where roads and everything can be seen.
	//
	MaplyVectorStyleSimpleGenerator *style = [[MaplyVectorStyleSimpleGenerator alloc] initWithViewC:_mapViewController];

	//
	// End styles.
	// -----------
	
	// Vector tile layer
	MaplyMBTileSource *tileSource = [[MaplyMBTileSource alloc] initWithMBTiles:@"irel"];
	MapboxVectorTiles *tiles = [[MapboxVectorTiles alloc] initWithTileSources:@[tileSource] style:style viewC:_mapViewController];
	MaplyQuadPagingLayer *layer = [[MaplyQuadPagingLayer alloc] initWithCoordSystem:tileSource.coordSys delegate:tiles];
	layer.flipY = false;
	[_mapViewController addLayer:layer];
	
	// Animate to start position
	_mapViewController.height = 0.04;
	[_mapViewController animateToPosition:MaplyCoordinateMakeWithDegrees(-8.6704803, 52.5023056) time:1.0];
}
```

I don't actually know what format style can be used to style the vector tiles. I was a bit surprised at the osm-bright result. 
1) What style formats can be used to style vector mbtiles, like France.mbtiles?
2) Is there a MaplyStyle capable of styling vector tiles using any of the style formats? 

Any other guidance is greatly appreciated. The MaplyVectorStyleSimpleGenerator is working fine with the data and I thought I would be able to style using SLD in v2.5 but I just can't figure out how. 

Nevermind where the data is coming from, nor where the style is coming from. At this point this is just test data to get off the ground. 

Thank you!

**Comment by mousebird** [comment]
Your style file has to match the attributes in your data.  So you can't really mix and match different styles unless they're all written for the same data source.

SLD will work if you've built the SLD to match the attributes in the data.  We do have an SLD example in the AutoTester using Metro Extracts from Mapzen.  That should provide a good starting point.  However, that will only work for the attribute scheme in Metro Extracts.

**Comment by dangustafsson** [comment]
Aaah! That was not obvious to me. I thought the attributes were all standardised and a style sheet of a certain format could be used to style all maps. 
The map data I'm playing with right now is from openmaptiles.org and they offer off-the-shelf styles in Mapbox GL and CartoCSS. 
I know the Mapbox GL support was added back in 2.5, what class is used for the gl styles? I'm not sure what version openmaptiles use even, mightn't be a compatible version.
I tried to load the project.xml file into a MapnikStyleSet but that didn't work either. 
I'll see if I can find a different tile provider with working styles I can use.

**Comment by mousebird** [comment]
Mapbox GL style support is officially going back in 2.5.1.  I'm not sure it's in the best state right now.  I'm looking for a customer who needs an update on it so we can bring it back in properly.

The MapnikStyleSet probably has a different set of attributes from everything else.

**Comment by dangustafsson** [comment]
I've been looking around and I could only really find map data sources with matching mapbox-gl style sheets, it seems to be the most popular format. At least in my price range anyway.
I pulled out the MaplyMapboxVectorStyleSet classes from Git and added them directly to my app. It's not pretty but it's significantly better than what I had and will allow me to continue for another while until 2.5.1.

**Comment by mousebird** [comment]
The answer with vector styles is:  It depends.

Are you on support?  I'd like an excuse to do more with this.
