### ISSUE TITLE
Definition of display units in maply

### ISSUE THREAD

**Issue by jingyibo123** [mousebird/WhirlyGlobe#846]
Hello everyone, 

I just started developing with the Android version of maply 2D map, and I'm a bit lost with the function MapController#setPositionGeo(final double x,final double y,final double z)
In the JavaDoc the z is "Height above the map in display units.". I haven't been able to figure out the exact meaning or equation to calculate this parameter. Could anyone give me a hint or a link to an explanation? 
Similar is when adding a Marker. What is the exact definition of Marker.size ?

Thanks in advance.

**Comment by mousebird** [comment]
The map is somewhere around 1.0 in size (depending on the projection).  Try a height of 0.1 and adjust from there.

**Comment by jingyibo123** [comment]
Thanks for the response.
The thing is I'm drawing a itinerary on the map and I need to pre-calculate this parameter with some accuracy. I tried adjusting but failed to define a reasonable formula. 
Is it possible that you could tell me how the map projects? So that I could calculate between the height and the geographic distance per display unit. Thanks again.

**Comment by mousebird** [comment]
There are methods for finding the height to cover a given bounding box.  Perhaps that's what you want?

findHeightToViewBounds:  https://mousebird.github.io/WhirlyGlobe/reference/android_2_5/index.html

**Comment by jingyibo123** [comment]
Thanks a lot, works like a charm!
