### ISSUE TITLE
Location marker still displayed when location tracking has stopped

### ISSUE THREAD

**Issue by pbmorton** [mousebird/WhirlyGlobe#852]
Using develop branch.  When calling stopLocationTracking() the location marker on the map does not disappear. I fixed this temporarily by making the following code change in MaplyLocationTracker.mm.  This may not be the best way - please advise.

```
- (void) teardown {
    if (!_simulate)
        [self teardownLocationManager];
    _delegate = nil;

// **** Added Code start
    if (_markerObj) {
        [_theViewC removeObject:_markerObj];
        [_theViewC removeObject:_movingMarkerObj];
        _markerObj = nil;
        _movingMarkerObj = nil;
    }
    if (_shapeCircleObj) {
        [_theViewC removeObject:_shapeCircleObj];
        _shapeCircleObj = nil;
    }
// **** Added code end
}
```

**Comment by rghosh0** [comment]
Thanks. Your code looks good; I added it in the branch: https://github.com/mousebird/WhirlyGlobe/tree/hotfix/location-tracking-visibility-and-extents
After review this will be merged into the develop branch.
