### ISSUE TITLE
Stickers that cross +/-180 degrees longitude are not displayed

### ISSUE THREAD

**Issue by fmango** [mousebird/WhirlyGlobe#854]
If a sticker is positioned in such a way that it crosses the +/-180 degrees longitude line, it can be added to the map, but will not be visible. Stickers positioned immediately east or west of this longitude will be displayed normally. We have worked around this problem by cropping images and creating two stickers, placing one on each side of the problematic longitude. This has the minor side effect that a very narrow gap between the two stickers is visible at high zoom levels.

**Comment by mousebird** [comment]
Is this iOS or Android or both?

**Comment by fmango** [comment]
This is a prototype app that runs on iOS only.

**Comment by mousebird** [comment]
The problem with degrees is that the system can't really figure out when you want to drape a sticker over the -180/+180 line or you want it to go all the way around the earth instead.  But there's an easy solution.

Just add 360 or subtract 360 from one of the numbers.  Like this:
        sticker.ll = MaplyCoordinateMakeWithDegrees(-191.0, 0.0)
        sticker.ur = MaplyCoordinateMakeWithDegrees(-171.0, 10.0)

Then the sticker will correctly sit across the line.

**Comment by fmango** [comment]
I have been trying to do just this. Every time I use a longitude value < -180 for sticker.ll and a longitude value > -180 for sticker.ur, the sticker does not display on the map.

**Comment by mousebird** [comment]
Can you give me an example?  I'll try the same numbers here.

**Comment by fmango** [comment]
The values I'm using in my most recent test were: 
ll = -223.9008, -63.4974
ur = -105.3074, 36.1572

**Comment by mousebird** [comment]
I tried these numbers and got a sticker that I expected.

![img_0049](https://cloud.githubusercontent.com/assets/1040005/24310801/8d462da4-108e-11e7-829c-07a31e908f65.PNG)

On you on a reasonably recent version of the toolkit?

**Comment by fmango** [comment]
I'm pretty sure we're on version 2.4.

**Comment by mousebird** [comment]
Oh, you're using a flat map?  I'll try it with that.

**Comment by mousebird** [comment]
Things that overlap the boundaries of the 2D map can get a little weird.
The way I solved this was to make it more explicit in the sticker setup.  Used the destination coordinate system and set the coordinates accordingly.

In Swift that looks like this:
        sticker.coordSys = MaplySphericalMercator.init(webStandard: ())
        sticker.ll = (sticker.coordSys?.geo(toLocal: MaplyCoordinateMakeWithDegrees(-223.9008, -63.4974) ))!
        sticker.ur = (sticker.coordSys?.geo(toLocal: MaplyCoordinateMakeWithDegrees(-105.3074, 36.1572) ))!

The equivalent in ObjC is simple enough.  The trick is that we're telling the system we want the sticker in Spherical Mercator and then giving in the exact coordinates we'd like.  It eliminates some second guessing deep within the system.

This shows the overlapping sticker for me.  The only problem I see is that the double-drawing logic doesn't seem to work so if you're zoomed waaaay out you won't see the sticker drawn twice at either end of the map.  Let me know if that's a problem.

**Comment by fmango** [comment]
Initial testing seems to confirm that this does the trick! I'll experiment with different bounding boxes and see if I can find any other issues.

**Comment by fmango** [comment]
The only problem I'm seeing is that if I create a very large sticker (the example I tried extended from central Asia eastward across the Pacific all the way to the west coast of North America), panning east/west will cause the sticker to disappear at a certain point while it is still on the display. This happens at any zoom level I've tried. I can zoom in and be panning across east Asia and see the sticker disappear and reappear as I cross a certain longitude. The problem only seems to happen with stickers that span a very large range of longitudes.

**Comment by mousebird** [comment]
Do you need to do areas that are that large?

**Comment by fmango** [comment]
Possibly. At this point, we're allowing the user the freedom to define an arbitrarily large bounding box. We anticipate most users would not need a box that large, but some might.

**Comment by mousebird** [comment]
All right, I'll track down the problem when we're zoomed way out.

**Comment by mousebird** [comment]
I see what the problem is.  The logic that's forcing two draws isn't being triggered when the +180/-180 line isn't on the screen.  Which makes sense, but is unhelpful in this case.

I think this is a pretty rare case.  You'd need to have a truly enormous sticker that overlaps the line and the user would need to be looking at it in just the right way.

If you encounter this problem in practice, I can add a switch to force the dual rendering and it'll start working.  But if you don't encounter it, let's not worry about it.

**Comment by fmango** [comment]
It's not happening solely with large stickers for us. I believe it's happening for _any_ sticker that crosses +/-180 longitude.

**Comment by mousebird** [comment]
There's a fix in the develop branch that handles the overlap case.  It should always draw correctly now.
