### ISSUE TITLE
Brightness of color areas in stickers varies with location

### ISSUE THREAD

**Issue by fmango** [mousebird/WhirlyGlobe#855]
When a large sticker (or a set of stickers with the same colors) is placed on the map, visible differences in brightness can be seen. The most obvious difference occurs at +/-180 degrees longitude: colors will appear brighter west of this latitude, and darker east of it. A similar discrepancy can be observed on the opposite side of the world, although it is less consistent. The brightness change will generally be somewhere around 5 degrees east longitude, but no sharp transition is visible.

![img_0119](https://cloud.githubusercontent.com/assets/5949785/23812183/009ff820-059f-11e7-9543-12d0fd44c64c.PNG)

**Comment by mousebird** [comment]
Is this happen with two stickers?
Does it still happen if you just do one sticker as I mentioned in the other Issue?

**Comment by fmango** [comment]
This is happening in the Pacific with two stickers. If I attempt to create a single sticker spanning this area, the sticker is not visible at all.

Over Europe and Africa, I can see the effect whether using one or multiple stickers.

**Comment by mousebird** [comment]
Can you give me the coordinates of one over Europe that does this?

**Comment by fmango** [comment]
I'm currently using one that spans the Atlantic:
ll = -76.4594, -19.9719
ur = 19.954, 61.5041

Depending on the image used to create the sticker, the effect may or not be visible. When it is seen, it is affecting roughly the easternmost 10% of the sticker width for this particular bounding box.

**Comment by mousebird** [comment]
I get a reasonable result with these values too, but let's see what's going on with the other issue.

**Comment by fmango** [comment]
![simulator screen shot mar 27 2017 10 27 12 am](https://cloud.githubusercontent.com/assets/5949785/24365464/999a261a-12db-11e7-9c52-fe74f42518f8.png)
![simulator screen shot mar 27 2017 10 24 29 am](https://cloud.githubusercontent.com/assets/5949785/24365465/99a02c90-12db-11e7-9ef5-56740a568b54.png)

Here are a couple of screenshots from the simulator. Both used the same PNG file for the sticker; a solid green rectangle with green value 255, red and blue zero. You can see the sharp difference at +/- 180 longitude, and the more gradual shift just east of 0 longitude.

**Comment by mousebird** [comment]
This seems to be working fine in the develop branch, which is close to 2.5.
It looks like we may have been using the wrong shader in 2.4.  It almost looks like there was active lighting there.

You're not activating any of the atmospheric or lighting options on the map, are you?

**Comment by fmango** [comment]
No, we aren't.

**Comment by mousebird** [comment]
Okay, then 2.5 seems to work okay with this.

**Comment by fmango** [comment]
If this is fixed in 2.5, that's probably all the answer we need for now. We may update our app to 2.5 in the near future.

**Comment by mousebird** [comment]
I can't duplicate it in 2.5, but I can't guarantee it's fixed.  I'm not sure what would have caused it.

After you upgrade, let me know if it turns up again.

**Comment by fmango** [comment]
I'll test our app with 2.5 and let you know how it goes. If it fixes the issue for us (and regression testing is uneventful), we'll just do the upgrade earlier than we would have.

**Comment by fmango** [comment]
Upgrading to 2.5 turned out to make no difference for us. So if there's an issue with shaders, it looks like it's still there.

**Comment by mousebird** [comment]
I'll try to duplicate the test case exactly.  Can you send me the image you're using?
Then, if it fails to show up, you can build the AutoTester and see how your own case differs.

**Comment by fmango** [comment]
We get the same result with any image we try, as long as the geographic extent includes parts of both the Eastern and Western hemispheres. The problem is most obvious if the image has large areas of a single solid color. Here's the one I used in my last two examples.

![solidgreen](https://cloud.githubusercontent.com/assets/5949785/24658978/fbc9e2cc-1910-11e7-84b6-e739a14a6681.png)

**Comment by mousebird** [comment]
Here's what I'm getting:
![bigsquare](https://cloud.githubusercontent.com/assets/1040005/24677229/ee0e8334-193a-11e7-8483-fff7bfd544a9.PNG)

Can you see how your code differs from the [test case](https://github.com/mousebird/WhirlyGlobe/blob/develop/ios/apps/AutoTester/AutoTester/testCases/StickersTestCase.swift)?

**Comment by fmango** [comment]
I'll revisit that when I get a chance (we're in a time crunch right now), but from the code I looked at, there wasn't anything being done differently with the stickers themselves from the way we're doing it.

We don't actively use any shaders, so we should be getting whatever shader behavior is the default when we instantiate the MaplyViewController. Maybe there's a way to suppress shaders completely? I didn't see anything like that in the API...

**Comment by mousebird** [comment]
You always need at least one shader.  The map uses the simplest one by
default.

We should have the same case now.  So the question is where it differs.
