### ISSUE TITLE
Selection of markers fail

### ISSUE THREAD

**Issue by pbmorton** [mousebird/WhirlyGlobe#859]
Something has changed since commit a628cef404feb503df9b8626b169a425afe72b57. Until then the following code worked:

```
    let pointMarker = MaplyScreenMarker()
    pointMarker.image = image
    pointMarker.loc = MaplyCoordinateMakeWithDegrees(long, lat)
    let markerWidth = image.size.width
    let markerHeight = image.size.height
    pointMarker.size = CGSize(width: markerWidth, height: markerHeight)
    pointMarker.layoutImportance = MAXFLOAT
    pointMarker.offset = CGPoint(x:0, y:markerHeight/2)
    pointMarker.selectable = true
    let userObj = MyMarkerUserObject(<some stuff in here>)
    pointMarker.userObject = userObj
    markers.append(pointMarker)

```
and later:

```
    if (markers.count > 0) {
         markersObj = self.baseViewC?.addScreenMarkers(markers, desc: [kMaplyClusterGroup : (0)])
    }

```

and later:

>      func maplyViewController(_ viewC: MaplyViewController, didSelect selectedObj: NSObject) {
>          handleSelection(selectedObject: selectedObj)
>      }
>      
>      private func handleSelection(selectedObject: NSObject) {
>          if let so = selectedObject as? MaplyScreenMarker {
>              if let userObj = so.userObject as? MarkerUserObject {
>                  switch userObj.type {
>                  case MarkerType.point:
>                      addPopup(message: userObj.message)
>                  case MarkerType.entryNoDetail:
>                      addPopup(title: userObj.title, message: userObj.message)
>                  case MarkerType.entryDetailed:
>                      show(entry: userObj.entry!)
>                  }
>              }
>          }
>      }
> 

In the broken code the code line "if let so = selectedObject as? MaplyScreenMarker" always results in so = nil. It seems the downcasting fails.

Is this a bug or has the API changed?

**Comment by mousebird** [comment]
We'd added support for the allSelect: delegate call in the 2D map.  That broke the single select case.  Should now be fixed.
