### ISSUE TITLE
[iOS] MaplyShapeGreatCircle 

### ISSUE THREAD

**Issue by tobsterH** [mousebird/WhirlyGlobe#861]
Hi,

I'm using MaplyShapeGreatCircle to draw lines between two points on a globe (iOS).
Works like a charm most of the time, but I noticed that with some combinations of points the line does not draw properly and gets "hidden" by the globe.

I have tried increasing lineWidth and height, however that does not solve the issue. In general this appears with points that are about 500km in a more longitudinal way apart. In the screenshot below the lines are drawn correctly between Amsterdam - Berlin and Zurich - Berlin. There are no lines visible between Salzburg - Berlin, Linz - Berlin and Vienna - Berlin. If you have a close look you can see a little  bit of a blue line starting out of Salzburg but then disappearing quickly.

<img width="286" alt="globe_screenshot" src="https://cloud.githubusercontent.com/assets/26527349/24083816/dbe5ada8-0cde-11e7-9a39-685aab48a0e7.png">

Any ideas how to fix this?

Cheers

**Comment by mousebird** [comment]
The first step is to force the lines to draw after the globe.
So try setting kMaplyDrawPriority to kMaplyVectorDrawPriorityDefault

If the lines don't appear then, it may be a subdivision problem with the great circles.  If you could post the start and end points of the ones that's not showing up, that'd helpful.

**Comment by tobsterH** [comment]
Setting kMaplyDrawPriority unfortunately didn't help.

Here are two points where this behavior happens:

**Start Point**
latitude_deg = 48.1103
longitude_deg = 16.5697

**End Point**
latitude_deg = 52.5597
longitude_deg = 13.2877

**Comment by mousebird** [comment]
Try setting kMaplyZBufferRead: @NO

**Comment by tobsterH** [comment]
Thanks a lot! That solved it!

**Comment by mauh-akra** [comment]
Unfortunately, I'm facing the same issue, with several different locations. 
Without any globe texture, the line is drawn, but is missing the "height", no matter what height you set.
I guess that's also the reason why it's not visible, however, just like tobsterH I have no idea how to fix it

**Comment by mousebird** [comment]
Seeing kMaplyZBufferRead: @NO should fix the visibility issue.

**Comment by mauh-akra** [comment]
Thank you for your response, unfortunately, like tobsterH wrote before, it's not much help as this makes the great circles to be visible ALWAYS. Even behind the globe.

 It's easy to reproduce even in the whirlyglobe sample app, just use:
`MaplyShapeGreatCircle *greatCircle = [[MaplyShapeGreatCircle alloc] init];
greatCircle.startPt = MaplyCoordinateMakeWithDegrees(19.7847995758057, 50.0777015686035);
greatCircle.endPt = MaplyCoordinateMakeWithDegrees(20.9671001434, 52.1656990051);` 

 kMaplyZBufferRead: @NO, great circles always visible (even behind the globe)
![greatcirclezbufferoff](https://cloud.githubusercontent.com/assets/18396493/24493214/5e447890-152e-11e7-8298-daccd68999e5.png)
Great circle missing the height - missing black line between those two black points (start&end location used as mentioned above)
![greatcircleblackmissing](https://cloud.githubusercontent.com/assets/18396493/24493215/5e6e0fd4-152e-11e7-9345-8d85f169043f.png)

**Comment by mousebird** [comment]
Ah, so you're using height.  Yes, height requires the Z buffer be considered.

My recommendation would be to leave the z buffer on for the longer routes where you're using significant height, but turn it off for really short routes where there's little or no height.

**Comment by mauh-akra** [comment]
Please note this is what you've proposed before and then the lines are always visible - even when the globe rotates, they never disappear. I suspect the height doesn't matter here, even when set to 0 it's either partially visible or with z buffer off always visible (even when the lines are "behind" the globe)

**Comment by mousebird** [comment]
For the lines with zero height, try setting kMaplyShader: kMaplyShaderDefaultLineNoBackface

**Comment by mauh-akra** [comment]
Well, I tried, unfortunately still without success. It's still always visible (even when the lines are "behind" the globe)

**Comment by mousebird** [comment]
Could be that the shader isn't making it through.
I'll add it to the list for 2.5.1.

**Comment by mauh-akra** [comment]
That would be great, thanks in advance!
