### ISSUE TITLE
Custom MaplyTileSource

### ISSUE THREAD

**Issue by duzvik** [mousebird/WhirlyGlobe#864]
Hello, 
I have sql file with map tiles in format(x,y,z) with jpeg images(it's not https://github.com/mapbox/mbtiles-spec). I understand that such file can be processed with custom implementation of **MaplyTileSource**,  but I meet two problems:
* Z - is zoom level and it is reverted. (0 - i maximum zoom and 17 - is minimum zoom)
OK, I can simply revert it my custom implementation of **MaplyTileSource**. 
*  I don't understand  how WhirlyGlobe obtain the grid coordinates(row(x)  and column(y))  for a particular geographic location(Latitude, Longitude). 
I've reviewed **SphericalMercator.mm** and failed to find what i need.
Also I've found pseudo code for obtaining  grid coordinates at https://developer.here.com/rest-apis/documentation/enterprise-map-tile/topics/key-concepts.html

```
var lat = 52.525439, // Latitude
lon = 13.38727,    // Longitude
z = 12,        // Zoom level
latRad,
n,
xTile,
yTile;

latRad = lat * Math.PI / 180;
n = Math.pow(2, z);
xTile = n * ((lon + 180) / 360);
yTile = n * (1-(Math.log(Math.tan(latRad) + 1/Math.cos(latRad)) /
Math.PI)) / 2;
```
With this code I'm able to find correct image from my sql file for right geo coordinates.
But **MaplyQuadImageTilesLayer** requests  **MaplyTileSource** with  tileID that not match pseudocode. tileID.x - match to X in pseudocode and tileID.y  - nope.

How to convert Y(from pseudocode and my sql file with map tiles)  to tileID.y that requested by  **MaplyQuadImageTilesLayer**?

Thank you.

**Comment by mousebird** [comment]
Sometimes you have to flip the Y.
Something like: y = 2^zoom - y

**Comment by duzvik** [comment]
Thank you! It works.

**Comment by mousebird** [comment]
I'm on fire this morning.
