### ISSUE TITLE
Globe/Map introspection improvement.

### ISSUE THREAD

**Issue by joaquin-perezbarroso** [mousebird/WhirlyGlobe#867]
TO DO:
Add to: MaplyViewControllerLayer.h a new property: 

```
/** @brief Set as unique identifier, or group...
 @details use this property in order to localize this layer in the Globe/Map, you use in a predicate to catch as a load layer in Globe...
 */
@property (nonatomic, strong) NSString *identifier;
```

Add in: MaplyBaseViewController.h

```
/** @brief Return all layers loaded by user.
 @details All layers loaded by user than are currently loaded.
 */
-(NSArray *)loadedLayers;
```

And in MaplyBaseViewController.mm

```
-(NSArray *)loadedLayers
{
    return [NSArray arrayWithArray:userLayers];
}
```

Well, with this. Any user can check if a layer was loaded or not. We can use predicate to ask a layer, observers...

**Comment by mousebird** [comment]
Ranen, can you take a look at this after the big merge is done?

**Comment by jmnavarro** [comment]
@rghosh0 big merge for iOS is ready. You can start working again in `develop` branch

**Comment by rghosh0** [comment]
Thanks! Pull request for this issue is #872

**Comment by mousebird** [comment]
A question on the identifier.  We don't use this pattern so I'm not familiar with it.
Do we fill identifier with something like "WhirlyGlobeViewController"?  Or is it just something you fill in?

**Comment by joaquin-perezbarroso** [comment]
Well I'm going to explain a case of use.

Imagine, we have a map than we use in a bunch of places in our App, by example we have 8 viewControllers, and 6 of them use the map (as child viewcontroller), we use an unique map (a singlenton) in order a better performance and because in this map we load some layers (some are shared by 4 viewControllers, and so on...).
Well, we can load in a view controllers, a MaplyQuadPagingLayer with identifier = @"streets" (paging vector), another MaplyQuadImageTilesLayer with identifier = @"water", and more...
When we change the Map to another viewController we don't need any other object to know by example if the streets are loaded, only:
`BOOL streetLoaded = (BOOL)[[[[ICSharedMapVC sharedMap].map loadedLayers] filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@“identifier=%@“,@“streets”]count]; `

**Comment by mousebird** [comment]
Ranen, sounds like you had the right idea.  Proceed with that, but add in a default identifier.
