### ISSUE TITLE
Direction or map displayed incorrectly using location tracking (portrait vs. landscape mode)

### ISSUE THREAD

**Issue by stonetip** [mousebird/WhirlyGlobe#869]
Using location in the iOS simulator, e.g. the freeway drive, bike ride, there's no apparent issue. Also, there is no issue on a physical device strictly using portrait mode (regardless of lock type being set to MaplyLocationLockHeadingUp or MaplyLocationLockHeadingNorthUp) However, on a physical device held in landscape mode, inconsistencies arise.

Locked to **NorthUp**, if I am _moving north_ in **portrait** mode,  both the map and the directional arrow face north (the correct expectation). Switching to **landscape**, the map is still facing north but the directional arrow is facing west (toward the top of the screen if it was in portrait mode).

![](http://stonetip.com/images/northUpOrientations.png)

Locked to **HeadingUp**, again everything is okay in **portrait** mode. Switching to **landscape**, the directional arrow is pointed north but north on the map is now displayed to the east.

![](http://stonetip.com/images/headingUpOrientations.png)

For reference, the code I'm using to load and display a map:
[https://github.com/stonetip/He2A/blob/master/He2A/He2A_app/ViewController.swift](https://github.com/stonetip/He2A/blob/master/He2A/He2A_app/ViewController.swift)

**Comment by mousebird** [comment]
Should be fixed now.

**Comment by stonetip** [comment]
Thanks. I assume to try it out I'll need to clone the develop branch and build the binary. (Just checking so I will be efficient).

**Comment by mousebird** [comment]
Or you can grab a binary build from the [builds page](https://mousebird.github.io/WhirlyGlobe/builds/builds.html)
