### ISSUE TITLE
changing image layer alpha

### ISSUE THREAD

**Issue by rghosh0** [mousebird/WhirlyGlobe#87]
Hi,
I'm looking for a way to change the alpha of an image layer dynamically.

I noticed the color property for MaplyQuadImageTilesLayer, but I believe it only takes effect once, immediately after layer creation.  I tried changing it and calling reload on the layer, to see what kind of delay there might be, but it didn't seem to have an effect.

I guess it's not enough to write a custom shader for the MaplyQuadImageTilesLayer instance, because I'd also need to change the attribute value.

Can you give me a hint as to where's a good place to start?

**Comment by marcusficner** [comment]
Hi, could you give me a hint on how to use the MaplyShader to make a layer partially transparent? I've added a city lights layer and want to mimic iOS maps' night/day presentation, but I'm stuck with this and not very experienced with Shaders or OpenGL. Any advice would be highly appreciated!

**Comment by mousebird** [comment]
Yes, you could do the traditional day image/night image composition with shaders.

You need two layers with a modified shader.  The shader would take a sun direction vector and use that to generate a transparency.  I think you'd take the dot product of a vertex with the sun direction, run that up to x^3 (or x^(1/3)) or something and then use that as a transparency value.  For the light side you use the sun vector, for the dark side, you reverse the vector.

There are a lot of details, but it's possible.  Good luck!

**Comment by marcusficner** [comment]
Thank you very much! This seems pretty straightforward.. after some reading.

**Comment by mousebird** [comment]
Okay, good luck!
