### ISSUE TITLE
addAnnotation raise exception when coord not show in current screen

### ISSUE THREAD

**Issue by hilanderst** [mousebird/WhirlyGlobe#875]
i meet an issue when calling 
- (void)addAnnotation:(MaplyAnnotation *)annotate forPoint:(MaplyCoordinate)coord offset:(CGPoint)offset
for MaplyBaseViewController 
when an annotate is not show in current view rect, that is, the annotate's coordinate is on the back side of the globe. 

checking the source, 
CGPoint pt = [self screenPointFromGeo:coord];
...
 [annotate.calloutView presentCalloutFromRect:rect inView:glView constrainedToView:glView animated:YES];
or
[annotate.calloutView presentCalloutFromRect:rect inView:glView constrainedToView:glView animated:NO];

when the annotate's loc is not show on screen, pt's value is Nan, then make the exception.

i suggest add judgement for the return value for pt, if it is Nan, then just put it in an the annotation array,
[annotations addObject:annotate];
while did not show it immediataly here.

**Comment by hilanderst** [comment]
CGPoint pt = [self screenPointFromGeo:coord];

    // fix by highlander, for pt may be nan for not in current screen
    if(isnan(pt.x) || isnan(pt.y)){
        pt = CGPointMake(-20000.0, -20000.0);
    }
    
insert 4 lines of code at line number 876, fixed the issue. but -20000.0 is a tricky number, what it means is negative large number which not in show in current view frame.

**Comment by mousebird** [comment]
Merged the fix.  Thanks!
