### ISSUE TITLE
Markers are showing on wrong position when i'm adding with following location using this code

### ISSUE THREAD

**Issue by abrar-ul-Haq57** [mousebird/WhirlyGlobe#877]
MaplyScreenMarker *marker = [[MaplyScreenMarker alloc] init];
        marker.image = icon;
        marker.loc =  MaplyCoordinateMakeWithDegrees(33.732934, 73.09164);
        marker.size = CGSizeMake(40,40);
        [markers addObject:marker];
[theViewC addScreenMarkers:markers desc:nil];

**Comment by mousebird** [comment]
Need a little more information here.

**Comment by abrar-ul-Haq57** [comment]
Please define what kind of information need more
Actually i want tu add markers based on coordinates whenever i add marker with lattitude and longitude it shows on wrong loction not on coordinates locatuon

**Comment by mousebird** [comment]
The order of the coordinates is: longitude, latitude
