### ISSUE TITLE
Piling images in a globe to create a volume - Swift

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#883]
Good morning everyone,

I am trying to insert a pile of images in a globe to create a volume of weather data (grib2 weather data turned into jpeg format). I am not really sure how to do it. I have been looking in the component tester for an example of implementation of image tile pyramids but I didn't find anything. Did you guys ever tried any similar thing? If so, do you have some advices?

Have a nice day,

Sebastien.

**Comment by mousebird** [comment]
I have something I could give you access to.  Hit me up by email.
