### ISSUE TITLE
[Swift] "Pinch in" or "pinch out" always result in zoom out

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#884]
I tried the new development branch, but it seems a bug found it way in...

Pinching in or pinching out both result in zooming out.
Double tap = zoom in (good!)
Tap with 2 fingers = zoom out (good!)

So it seems only pinch out is confused...

**Comment by mousebird** [comment]
I just tried the develop branch and it zoomed in and out correctly for me on both map and globe.

**Comment by jmcazaux** [comment]
Bear with me, it seems my WhirlyGlobe sub module was on a detached head instead of develop...

Rebuilding everything...

**Comment by jmcazaux** [comment]
Nope.

Recompiled everything on develop and I can only zoom out.

Some information would help?

**Comment by mousebird** [comment]
Do you have a view extents set?

**Comment by jmcazaux** [comment]
Sorry, you lost me. 

What are view extents ?

**Comment by mousebird** [comment]
In the map did you call setViewExtents: at some point?

**Comment by jmcazaux** [comment]
No, not doing that.

**Comment by mousebird** [comment]
Can you try this with the AutoTester app on the Geography Class example?

**Comment by jmcazaux** [comment]
I'll do that and will let you know (most probably on Monday though)

**Comment by jmcazaux** [comment]
Ok, found the culprit.

This happens when using the empty initializer on a map controller.

Maybe it should be more than deprecated (or less than deprecated).
As far as I am concerned, this can be closed.
