### ISSUE TITLE
[iOS] issues screenPointFromGeo and geoFromScreenPoint

### ISSUE THREAD

**Issue by nhevaweb** [mousebird/WhirlyGlobe#886]
Hi, 

I'm trying to implement a zoom that fit a MaplyVectorObject (from GeoJSON) within my screen.
`MaplyBoundingBox vecBox = vectorObject.boundingBox;`
  `MaplyCoordinate center = MaplyCoordinateMake((vecBox.ll.x + vecBox.ur.x)/2.f, (vecBox.ll.y +vecBox.ur.y)/2.f);`
`CGFloat height = [maplyCarto findHeightToViewBounds: vecBox pos: center];`
`[maplyCarto animateToPosition:center height: height  time:0.6f];`

This is working great, see below
![france](https://cloud.githubusercontent.com/assets/23048593/24802886/cf1b91e4-1ba9-11e7-9787-b34f3a90b818.png)
![zoomtovector](https://cloud.githubusercontent.com/assets/23048593/24802892/d130779c-1ba9-11e7-8731-444d88077e02.png)

I read that findHeightToViewBounds is really inefficient. Is there a better way to do this ?

Now I'm trying to add some marging like this 
![zoomtovectorinsets](https://cloud.githubusercontent.com/assets/23048593/24803286/0e56f9b0-1bab-11e7-8a85-e862136297bb.png)

For that I'm converting my boundingBox in screenPoint applying my margin values and convert them back to a new wider boundingBox like this:
`MaplyBoundingBox vecBox = vectorObject.boundingBox;`
`CGPoint screenLL	=	[maplyCarto screenPointFromGeo: vecBox.ll];`
`CGPoint screenUR	=	[maplyCarto screenPointFromGeo: vecBox.ur];`
`screenLL.x -= 50;`
`screenLL.y += 50;`
`screenUR.x += 50;`
`screenUR.y -= 50;`
`newVecBox.ll = [maplyCarto geoFromScreenPoint:screenLL];`
`newVecBox.ur = [maplyCarto geoFromScreenPoint:screenUR];`
`MaplyCoordinate center = MaplyCoordinateMake((newVecBox.ll.x + newVecBox.ur.x)/2.f, (newVecBox.ll.y + newVecBox.ur.y)/2.f);`
`CGFloat height = [maplyCarto findHeightToViewBounds: newVecBox pos: center];`
`[maplyCarto animateToPosition:center height: height time:0.6f];`
**It works fine as long as the vector isn't partially or completely off screen.** 

If my vector is **slightly off screen**, the zoom is completely out of bounds and even when I call just :
`MaplyBoundingBox vecBox = vectorObject.boundingBox;`
`CGPoint screenLL	=	[maplyCarto screenPointFromGeo: vecBox.ll];` => x and/or y < 0
`CGPoint screenUR	=	[maplyCarto screenPointFromGeo: vecBox.ur];` => x and/or y < 0
`newVecBox.ll = [maplyCarto geoFromScreenPoint:screenLL];`
`newVecBox.ur = [maplyCarto geoFromScreenPoint:screenUR];`
I'm not applying any margin changes nor movement on the actual carto and yet newVecBox and vecBox are different. 
Am I missing something here ?

**Comment by mousebird** [comment]
findHeightToBounds is going to be fine if you call it only a few times per second.  I wouldn't call it a few thousand.

Is this the globe or the map?

**Comment by nhevaweb** [comment]
Okay.
This issue happens on the map, i didn't try it on the globe.

**Comment by mousebird** [comment]
In theory screenPointFromGeo: ought to be right.  Can you give me a few data values?

**Comment by nhevaweb** [comment]
Printing code: 
`MaplyBoundingBox bounding = vectorObject.boundingBox;`
`NSLog(@"ORIGINAL: LL.x = %f \t LL.y = %f", bounding.box.ll.x, bounding.box.ll.y);`
`NSLog(@"ORIGINAL: UR.x = %f \t UR.y = %f", bounding.box.ur.x, bounding.box.ur.y);`

`CGPoint ll	=	[maplyCarto screenPointFromGeo: bounding.box.ll];`
`CGPoint ur	=	[maplyCarto screenPointFromGeo: bounding.box.ur];`
`NSLog(@"SCREEN: LL.x = %f \t LL.y = %f", ll.x, ll.y);`
`NSLog(@"SCREEN: UR.x = %f \t UR.y = %f", ur.x, ur.y);`

`MaplyCoordinate newLL = [maplyCarto geoFromScreenPoint:ll];`
`MaplyCoordinate newUR = [maplyCarto geoFromScreenPoint:ur];`
`NSLog(@"COMPUTED: LL.x = %f \t LL.y = %f", newLL.x, newLL.y);`
`NSLog(@"COMPUTED: UR.x = %f \t UR.y = %f", newUR.x, newUR.y);`


- 1st case I'm zooming on a MaplyVectorObject's boudingBox from a height where I can see it completely
results are:
`ORIGINAL: LL.x = 0.036004 	 LL.y = 0.769968`
`ORIGINAL: UR.x = 0.125418 	 UR.y = 0.816887`
`SCREEN: LL.x = 286.894328 	 LL.y = 517.025631`
`SCREEN: UR.x = 447.738633 	 UR.y = 396.662192`
`COMPUTED: LL.x = 0.036004 	 LL.y = 0.769968`
`COMPUTED: UR.x = 0.125418 	 UR.y = 0.816887`

- 2sd case I'm zooming on a MaplyVectorObject's boudingBox from a height where I can see it partially (10% of the shape is out of the screen from the left)
results are:
`ORIGINAL: LL.x = 0.036004 	 LL.y = 0.769968`
`ORIGINAL: UR.x = 0.125418 	 UR.y = 0.816887`
`SCREEN: LL.x = -101.296544 	 LL.y = 609.399048`
`SCREEN: UR.x = 423.645708 	 UR.y = 216.572863`
`COMPUTED: LL.x = 0.053258 	 LL.y = 0.769968`
`COMPUTED: UR.x = 0.125418 	 UR.y = 0.816887`

- 3rd case I'm zooming on a MaplyVectorObject's boudingBox from a height where I can see it partially (50% of the shape is out of the screen from the top and right)
results are:
`ORIGINAL: LL.x = 0.036004 	 LL.y = 0.769968`
`ORIGINAL: UR.x = 0.125418 	 UR.y = 0.816887`
`SCREEN: LL.x = 356.037444 	 LL.y = 128.741595`
`SCREEN: UR.x = 692.294160 	 UR.y = -122.886927`
`COMPUTED: LL.x = 0.036004 	 LL.y = 0.769968`
`COMPUTED: UR.x = 0.096888 	 UR.y = 0.794253`

- 4th case I'm zooming out to the country's boudingBox from the 2sd image to the 1st one(see image in my 1st post)
results are:
`ORIGINAL: LL.x = -0.089749 	 LL.y = 0.721401`
`ORIGINAL: UR.x = 0.166860 	 UR.y = 0.891686`
`SCREEN: LL.x = -789.175467 	 LL.y = 1038.287081`
`SCREEN: UR.x = 850.045808 	 UR.y = -539.736430`
`COMPUTED: LL.x = 0.033791 	 LL.y = 0.752727`
`COMPUTED: UR.x = 0.125369 	 UR.y = 0.836860`

**Comment by mousebird** [comment]
Your logic seems right, but feels dodgy.  Rather than figure out why I just added a margin to the findHeightToViewBounds call.  Check the develop tree or wait for the next build on the builds page.

Are you on support?  You might want to be on support.
