### ISSUE TITLE
[Android] Any reason why .idea are not git ignored

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#888]
We usually put everything IDE related in gitignore.

I was wondering if there is a reason you did not?

This is bit annoying for PRs as there is a risk we would drag some local configuration into your project.

Same goes for local.properties files

**Comment by mousebird** [comment]
I've been fighting with this lately.  I'll take a look.

**Comment by jmcazaux** [comment]
You can probably lose android/library/Android/Android.iml and android/library/Android/.idea as well.

**Comment by jmcazaux** [comment]
I think this can be closed now.
