### ISSUE TITLE
[Android] AutoTester would not compile

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#889]
trying to compile the Android AutoTester from develop, I have the following
```
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/R;
```

I have spent most of the afternoon trying to fix it, but could not find the culprit.

Anyone else experiencing this?

**Comment by mousebird** [comment]
I've never seen this one before.  It sounds a bit like a cached library problem:
https://stackoverflow.com/questions/20087081/android-socialize-sdk-unable-to-execute-dex-multiple-dex-files-define

**Comment by jmcazaux** [comment]
Bear with me, it seems it happens when upgrading the Android Gradle pluggin in the SDK...

Making more tests...

**Comment by jmcazaux** [comment]
In fact, when the library is compiled with an Android Gradle plugin above 2.3.x, it breaks the application (the AutoTester or my own).

**Comment by mousebird** [comment]
Typical Android madness.  We'll probably need to just create a new AutoTester project.

It's on the list, so we'll look at it soon.

**Comment by jmcazaux** [comment]
In the meantime, the above PR works.

And I think the issue is more in the library than in the AutoTester.

**Comment by mousebird** [comment]
We seem to be on gradle 3.3 with version 2.3.1 of the plugin.
But full disclosure, I find gradle ridiculously complex for what it's doing, so I may be confused.
