### ISSUE TITLE
[Swift] WideVectors draw priority is ignored (or completely off)

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#892]
Within the attached PR, "Iron Bird Software issue tester" should show a stack with (from the bottom):
- some brown text
- a marker
- a large red cross (wide vectors)
- some other text

The red cross does not show and is actually under the base layer (can be seen when disabling it)

**Comment by mousebird** [comment]
My first comment would be to use the defaults for drawPriority, such as:
kMaplyVectorDrawPriorityDefault
kMaplyMarkerDrawPriorityDefault

**Comment by mousebird** [comment]
You can use those as offsets.  So kMaplyVectorDrawPriorityDefault+10 and so on.
If you want to intermingle different types, then use the base draw priority (look in the header where kMaplyVectorDrawPriorityDefault is) and offset from there.

**Comment by jmcazaux** [comment]
@mousebird , I have improved the test case according to your comment, but it did not change things much (bar the fact that wide vectors are now above the background).

According to my code I should have:
`
blue small text
wide vectors (red cross)
smiley
brown large text
background
`

What I have:
`
blue small text
smiley
brown large text
wide vectors (red cross)
background
`

**Comment by mousebird** [comment]
By custom we bump the labels and markers on top of everything else.

To turn that off set screenObjectDrawPriorityOffset = 0 in the view controller.

**Comment by jmcazaux** [comment]
It did the trick!

This kind of wizardry could maybe be documented somewhere?

**Comment by mousebird** [comment]
It's interesting to see someone move from Android to iOS.  Android is the newer, cleaner API and iOS has a lot of history.

**Comment by jmcazaux** [comment]
Yeah... 
Discovering this right now.
"History" is an interesting way to describe it.
