### ISSUE TITLE
[Swift] Markers using images filtered with a Core Image filter do not show

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#894]
I need to apply some color transformation to some markers and they do not show.
- the unmodified image shows
- when set to an ImageView the filtered image shows.
- when used as a marker, the filtered image does not show

**Comment by mousebird** [comment]
How are you applying these filters?

**Comment by jmcazaux** [comment]
Please see code in the attached PR (IBSIssueTesterTestCase.swift)

**Comment by mousebird** [comment]
I'm going to guess that the filter is being ignored when we extract the pixels from the UIImage.  Can you extract a "dumb" UIImage from the system?  That's likely to work better.

**Comment by jmcazaux** [comment]
Dumb image ?

You mean directly using an image asset?
Yes, this works, but I need to apply the filter as users can customize the appearance.
It is not one color only, it is fill + outline... Yes I know "very easy to overdo customization"...

**Comment by mousebird** [comment]
I mean that I think the CIFilter is not actually being run and is just sitting there on the CGImage.  But we need pixels.

Try turning it into an NSData containing PNG and then creating a UIImage from that.  If it works then we'll know that's what's going on.

**Comment by jmcazaux** [comment]
@mousebird it was indeed an issue with image processing.

I have updated the PR with the working example in case you want to keep it somewhere for reference.

Solution was here http://stackoverflow.com/questions/42590281/png-jpeg-representation-from-ciimage

**Comment by mousebird** [comment]
Too fancy for it's own good!

Thanks for the update.
