### ISSUE TITLE
[Swift] Custom MaplyQuadImageTilesLayer stops loading as soon as there is a failed tile

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#897]
I use extensively MaplyQuadImageTilesLayer on the Android side and I am a bit puzzled with API differences on the iOS/Swift side (not the first one).

On the IOS side, it seems the MaplyQuadImageTilesLayer stops loading as soon as a tile is not loaded.

Some of my layers have only a partial coverage.

I can trick the system by returning a transparent tile, but this feels a bit wrong.

**Comment by mousebird** [comment]
It will stop loading any higher level tiles once it gets a bad tile.  But it should continue loading other tiles.  It shouldn't just stop.

**Comment by jmcazaux** [comment]
Well, apparently it does stop. See attached test case.

**Comment by duzvik** [comment]
Just pass
`MaplyImageTile(asPlaceholder: ()) //set empty placeholder to ignore missed tiles
in func  image(forTile tileID: MaplyTileID) -> Any!  for missed images

**Comment by mousebird** [comment]
I should have looked more closely at this one before.  I assumed you'd turned up an actual error and was planning to build a more complicated test case.

But not, it was simpler.  You need to tell the quad images layer that you failed to load a tile.
Just add:
            tilesLayer.loadError(nil, forTile: tileID)
