### ISSUE TITLE
EXC_BAD_ACCESS on spatialite_init(TRUE)

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#899]
Hi,
    When I update to lastest version by cocoapods:
platform :ios, '8.0'

target 'GlobalRouteHD' do
    pod 'SpatialDBKit'
    pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe', :branch => 'master'
    
end

-->  it appears the follow problem:

![image](https://cloud.githubusercontent.com/assets/13251217/24938547/67371a02-1f6a-11e7-8380-1506680cc3ae.png)

  How to fix the problem? thank you !

**Comment by marychenyuan** [comment]
sorry, add prolbem picture:
![9b1fdd7d-143f-4805-bd83-fab5077d65ef](https://cloud.githubusercontent.com/assets/13251217/24938849/41efc116-1f6c-11e7-84ca-3d83c07ba896.png)

**Comment by marychenyuan** [comment]
After that, I replaced "SpatialDatabase.m" file with develop_2_4_1 branch version, not lastest version , it works!
but... it appears that password is wrong,when set key with data, retuen 21-->#define SQLITE_MISUSE      21   /* Library used incorrectly */

![c3934877-1799-43aa-b763-202ad6548829](https://cloud.githubusercontent.com/assets/13251217/24953549/49efecd2-1fae-11e7-8751-dd07a68fac98.png)


How can I fix this problem? thank you very much!

**Comment by mousebird** [comment]
Looks like a version mismatch between the FMDB WG-Maply uses and one you're pulling in from elsewhere.

However, the podspec for WG-Maply references FMDB so it's not likely to be on our side.  I'd check to see if you're pulling in a specific version of FMDB from somewhere else.

**Comment by marychenyuan** [comment]
I used follow code to pull the FMDB, not obtained by other place:

target 'GlobalRouteHD' do
pod 'SpatialDBKit'
pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe', :branch => 'master'

end
