### ISSUE TITLE
[iOS] Seeing much (much) higher CPU consumption than on Android

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#906]
With equivalent vector maps and level of details, I am seeing a much higher CPU consumption on mi iPad than on my Nexus 9 (iPad Air running iOS 10.3).

Though I am only updating location every second and by very small increments, the CPU stays between 150% and 160%. 

On the Nexus 9, I see a spike to 50% or 60% every second, but it goes down in between...
Note: it is not the % itself that matter, but the fact that it stays high.

**Comment by mousebird** [comment]
You're running with the Release version of the library, right?

**Comment by jmcazaux** [comment]
Ah... Did not pay attention to this.

I have integrated the source code as a library in my project.

How is the target set on the lib ?

**Comment by mousebird** [comment]
If you build Release it should build the library Release.

**Comment by jmcazaux** [comment]
Obviously it made a *massive* difference.
CPU consumption is now down to 25/30% and the app is feeling much smoother.

I know this is more an XCode question that a WG question, but is it possible to build the app for debug and the integrated lib for release ?

**Comment by jmnavarro** [comment]
I'm not totally sure, but probably not. Since you aren't using the binary but the source code, when the compiler is debug mode on, WG source code is compiled with debug info as well

**Comment by jmcazaux** [comment]
Ok, will look into this when time allows.
For now I have created a schema that uses "Release" when running the app.

I might revisit using source as well, I think I had a reason for not going binary, but right now I cannot remember.

You do not push a nightly binary to Cocoapods do you ?

**Comment by jmnavarro** [comment]
we don't. Cocoapods is the stable release (2.5 right now). But you can use nightly versions from your podfile. Check [builds page](http://mousebird.github.io/WhirlyGlobe/builds/builds.html)

**Comment by jmcazaux** [comment]
Yes indeed... Forgot that feature of Cocoapods...

I now remember why I switched to source (needed some new features that have now been merged)...

I'll try to move back to nightly binaries, but I propose we close down this issue as it has nothing to do with a performance issue anymore.
