### ISSUE TITLE
How to set the range the data view can scollview?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#907]
Hi,
    When I show my map data by WhirlyGlobe framework, I found I can't set the area to limit the data view scollview.  Now, When I slide hard, the map goes beyond the screen, How can I fix the problem?

**Comment by mousebird** [comment]
We don't use a UIScrollView, but I think I see what you mean.

If you're using a MaplyViewController you can call setViewExtents.  If you're using a WhirlyGlobeViewController there's no way to limit the extents.

**Comment by marychenyuan** [comment]
ok, Thank you !
