### ISSUE TITLE
Pixelated sticker?

### ISSUE THREAD

**Issue by adygithub** [mousebird/WhirlyGlobe#908]
Hello

I added an image over a map using MaplySticker (iOS), but the image used looks very pixelated when I zoom in. I did the same on Android with the Sticker class and in Android the sticker looks very smooth. 
How can I make a smooth sticker in iOS too? 

You can see the screenshots for iOS and Android here: [https://ibb.co/mvOtgQ](https://ibb.co/mvOtgQ) and [https://ibb.co/bWLH85](https://ibb.co/bWLH85)

The code:
`func addStickerIOS() {
                
        var currentRadarImage = UIImage(named: "Weather")!
        let radarImage = MaplySticker()
        
        radarImage.ll = MaplyCoordinateMakeWithDegrees(-10.53856, 42.46326)
        radarImage.ur = MaplyCoordinateMakeWithDegrees(19.75471, 59.06108)
        radarImage.image = currentRadarImage 
        radarImage.imageFormat = MaplyQuadImageFormat.image4Layer8Bit
        
        maplyController.addStickers([radarImage], desc: [kMaplySampleX: 1, kMaplySampleY: 1], mode: MaplyThreadMode.any)
}

private void addStickerAndroid() {
	
	Bitmap bm = BitmapFactory.decodeResource(getResources(), R.drawable.weather);
	
	MaplyTexture imageTexture = mapControl.addTexture(bm, new TextureSettings(), ThreadMode.ThreadAny); 
	
	ArrayList<MaplyTexture> texture = new ArrayList<MaplyTexture>();
	texture.add(imageTexture);
	
	Sticker weather = new Sticker();        
	weather.setLowerLeft(Math.toRadians(-10.53856), Math.toRadians(42.46326));
	weather.setUpperRight(Math.toRadians(19.75471), Math.toRadians(59.06108));
	weather.setSampling(1, 1);
	weather.setImages(texture);
	weather.setImageFormat(ImageFormat.MaplyImage4Layer8Bit);
	
	ArrayList<Sticker> stickers = new ArrayList<Sticker>();
	stickers.add(weather);
					
	mapControl.addStickers(stickers, new StickerInfo(), ThreadMode.ThreadAny);
}`

**Comment by mousebird** [comment]
If you run the AutoTester and zoom in on one of the smiley faces in the Sticker test, how do they look?

**Comment by adygithub** [comment]
The issue can be reproduced with the smiley faces from the AutoTester project. I tried the AutoTester for iOS and Android. The Android smiley has some antialiasing and it looks smoother, the iOS smiley has no antialiasing at all.

![smiley_android](https://cloud.githubusercontent.com/assets/13661925/25234906/3f8f339e-25ec-11e7-9201-a84d75b7b82c.png)
![smiley_ios](https://cloud.githubusercontent.com/assets/13661925/25235003/8882fe0a-25ec-11e7-93b0-c3dd838b424b.png)

Thank you for your time.

**Comment by mousebird** [comment]
You can fix this by adding the image explicitly as a texture.  I've updated the StickersTestCase in the AutoTester to show you how.
