### ISSUE TITLE
Can not find the file "libWhirlyGlobe­MaplyComponent.a"

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#909]
Hi,
   When I set up my project and follow the tutorial(http://mousebird.github.io/WhirlyGlobe/tutorial/ios/building_from_source.html),then my project can not find the file "libWhirlyGlobe­MaplyComponent.a", only find "libWhirlyGlobeLib.a", then I put it to my project, last, it appeard follow error:

![Uploading 61E4EA32-5AFF-4298-9D4E-44E4FC8EC119.png…]()

**Comment by mousebird** [comment]
Seem to be a duplicate.  There's another open issue.
