### ISSUE TITLE
Apple mach-O linker(Id) error

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#910]
Hi,
    After I setted up project and follow the tutorial("http://mousebird.github.io/WhirlyGlobe/tutorial/ios/building_from_source.html"),I didn't find "libWhirlyGlobe­MaplyComponent.a" instand of "libWhirlyGlobe­Lib.a" in my project,  and it appeard the problem:

![1](https://cloud.githubusercontent.com/assets/13251217/25238395/e1012092-261f-11e7-9238-d5d0e51fe96d.png)

  How can I fix the problem?

**Comment by jmnavarro** [comment]
Did you add the `.a` file to "Link to binary to libraries" settings?

**Comment by marychenyuan** [comment]
yes, I did.
![a13cbc0e-2a20-48d4-808b-114c7e166f04](https://cloud.githubusercontent.com/assets/13251217/25260523/746c3786-267f-11e7-89da-479d2ab0988a.png)

**Comment by marychenyuan** [comment]
and if I use simulators to run, also appeard:

**Comment by marychenyuan** [comment]
![2](https://cloud.githubusercontent.com/assets/13251217/25261547/f220a392-2684-11e7-8fb1-05761536ab64.png)

**Comment by jmnavarro** [comment]
where did you get that `.a` file? Probably it doesn't contain x86 architecture

**Comment by marychenyuan** [comment]
In the folder ->(projectName)/libs/WhirlyGlobeMaply
then do the code in the termimal:

git submodule init 
git submodule update

then I can see the file "libWhirlyGlobe­Lib.a" when click the "+":
![2](https://cloud.githubusercontent.com/assets/13251217/25323124/b51b8d78-28ef-11e7-95e3-4e7c686eee03.png)

**Comment by jmnavarro** [comment]
I'd recommend you to use [Cocoapods setup](http://mousebird.github.io/WhirlyGlobe/tutorial/ios/building_from_cocoapod.html) and use [nightly builds](http://mousebird.github.io/WhirlyGlobe/builds/builds.html) if you need unreleased changes.
