### ISSUE TITLE
[iOS] Error building from binary

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#911]
I have just switched from "source" to "binary" (using Cocoapods) and it did not go down well.

I have the following error...

I have tried with the latest nightly, build 210, build 214... Always the same output.

Is it because I used the source distrobiution and then switched to Cocoapods ?

I have tried to remove references in my project, but there might be some traces left behind.

Anyone using binary distribution with success?

Thx,
JM

```
Errno::EINVAL - Invalid argument - /Users/home/[Project]/Pods/WhirlyGlobe/WhirlyGlobeMaplyComponent.framework/WhirlyGlobeMaplyComponent
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho/fat_file.rb:62:in `read'
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho/fat_file.rb:62:in `open'
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho/fat_file.rb:62:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho.rb:31:in `new'
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho.rb:31:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/file_accessor.rb:379:in `dynamic_binary?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/file_accessor.rb:162:in `block in vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/file_accessor.rb:161:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/file_accessor.rb:161:in `vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/file_accessor.rb:170:in `vendored_static_frameworks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:105:in `add_static_dependency_build_settings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:78:in `block in add_settings_for_file_accessors_of_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:76:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:76:in `add_settings_for_file_accessors_of_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:193:in `block in generate_vendored_build_settings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:191:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:191:in `generate_vendored_build_settings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:74:in `generate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:87:in `block in create_xcconfig_file'
/
```

**Comment by jmnavarro** [comment]
humm weird...

I assume you're getting that error running `pod install`. Which Ruby version are you using? cocoapods is quite sensitive to that

And what is your `Podfile`?

**Comment by jmcazaux** [comment]
Hi @jmnavarro,

Ruby version is 2.0.0p648.
Cocoapod version is 1.2.1.

I have this in my podfile re WG:
```
use_frameworks!

pod 'WhirlyGlobe', :http => 'https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/iOS_daily_builds/WhirlyGlobe-Maply_Nightly_latest.zip'
```

I have tried with iOS build 214 as well (`https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/iOS_daily_builds/WhirlyGlobe-Maply_214.zip`).

Ruby sounds a bit odd, but I have no other issue with pods (this stated,I have no other pod using http download).

**Comment by jmnavarro** [comment]
Yes, I'd say you need a newer ruby for that cocoapods version.

Try with Ruby 2.3.x

**Comment by jmcazaux** [comment]
Ok, that is not linked to my project.

I have created a new empty project "from scratch" with just the WG binary dependency and I get the exact same error.

**Comment by mousebird** [comment]
Yeah, it's a Ruby or Cocoapods problem.  I get this sort of thing occasionally too.  You probably need to update Ruby.

**Comment by jmcazaux** [comment]
I have but no luck...

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.1 (8E1000a)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/home/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2a9a83617b2a1bf7487762a0c7886bc9142ea4e7
```

**Comment by jmcazaux** [comment]
Do you want me to commit this test project ?

It is juts 2mn to recreate.

**Comment by jmnavarro** [comment]
yes, please

**Comment by jmcazaux** [comment]
Here we go: https://github.com/ironbird-software/MapTester

**Comment by jmcazaux** [comment]
I am not sure it helps or it is related but the binary is huge as well (600+ MB).

Is it the right thing being zipped?

**Comment by jmnavarro** [comment]
Yes, it seems to be related.

Try with the [latest nightly build](https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/iOS_daily_builds/WhirlyGlobe-Maply_Nightly_395_2017-04-25.zip). It's 400+ MB instead of 600 MB

**Comment by jmcazaux** [comment]
Hi @jmnavarro,
your link works.

Only caveat is that it shows "2.4.1-nightly395" when installing pod.

Is it actually building from develop (2.5) or master ?

**Comment by jmnavarro** [comment]
yes, it's built from develop. The version label is outdated, I'm gonna change it right now
