### ISSUE TITLE
Using country Tiles

### ISSUE THREAD

**Issue by muniryasir** [mousebird/WhirlyGlobe#917]
I am trying to use a country tile instead of the whole world tile. The tester app that comes along with the maply framework crashes, please see the screenshot. The tile I tried to use was downloaded from following source

http://osmlab.github.io/osm-qa-tiles/country.html 

specifically 

(https://s3.amazonaws.com/mapbox/osm-qa-tiles/latest.country/andorra.mbtiles.gz)

Now, I understand the tiles may not be properly configured, in such case, what are the standards for the mbtiles to work?

Please let me know further information is required
<img width="794" alt="andorracrash" src="https://cloud.githubusercontent.com/assets/5457270/25481137/3f29a370-2b65-11e7-8362-1b2159c84d8d.PNG">

**Comment by mousebird** [comment]
That's usually a sign that the MBTiles file didn't load correctly.
I suggest you step into the MBTiles source setup and see if it read all the header information from the sqlite tables.

**Comment by muniryasir** [comment]
ok I will look into it
