### ISSUE TITLE
[Android] VectorStyle.buildObjects called with a null controller

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#923]
In the VectorStyle interface, it happens that `buildObjects(List<VectorObject> vectors, MaplyTileID maplyTileID, MaplyBaseController controller)`is called with a null controller.

I have put some checks in my code, but it might bite someone else in the back.

**Comment by mousebird** [comment]
Pushing this off for a bit.  The problem here is that the source is being shutdown while it's still processing data.  In theory it should be waiting for those threads to shut down before clearing the tile source.  Should look at why that's not happening.
