### ISSUE TITLE
Looking for relevant shapes

### ISSUE THREAD

**Issue by vvaleed** [mousebird/WhirlyGlobe#926]
Hi,

First of all WhirlyGlobe and team have done a wonderful job. We have tried to use this in our product(https://itunes.apple.com/us/app/ergo360/id552304846?mt=8). I am facing a little trouble wrapping around a disc around the globe such that a circle curves around the globe. I have tried using a circle and a cylinder with a very thin height but I am unable to produce my desired shape. Can anyone help me out here? Attached are some snapshots that will help you understand my problem. Thank you.
![simulator screen shot 07-may-2017 1 56 00 pm](https://cloud.githubusercontent.com/assets/10007144/25779283/e6af8900-332d-11e7-8946-70587fc08f38.png)
![simulator screen shot 07-may-2017 1 49 25 pm](https://cloud.githubusercontent.com/assets/10007144/25779284/e6b3b2c8-332d-11e7-8ad1-0d74b60a34ef.png)

**Comment by vvaleed** [comment]
I think I found out the partial answer myself. Stickers wrap around the globe nicely. Now trying to add them with a little bit of transparency/alpha.

**Comment by mousebird** [comment]
Cool app.  Do you mind if I add it to the [apps page](https://mousebird.github.io/WhirlyGlobe/apps/apps.html)?

Stickers could work, though there's the issue of geographic vs real distance.  If you want a bit more precision you can do it with a filled polygon.  If you're on iOS take a look at the TextureVectorTestCase in the AutoTester app.

You don't need the texturing there, probably, but it shows you how to subdivide a shape properly so that it follows the globe.

**Comment by vvaleed** [comment]
Hi Steve,
Thank you for your response. Yes you can add the app to your apps page. Your toolkit has enabled us to have offline maps in flight for our Ergo360 app's calculations/projections etc. That is why the app size is around 1.79 GB on the appstore. (1.7 GB maps)

**Comment by vvaleed** [comment]
Thank you for adding our app on your page. There is 1 small bug, you mixed up the links for Ergo360 and Epicenter on the apps page.

**Comment by mousebird** [comment]
Whoops, fixed.

Also we have a support program if you're interested.  Yearly iOS or Android support.  Hit me up at contact@mousebirdconsulting.com.

**Comment by hamzabinamin** [comment]
@mousebird Sorry but I am having trouble adding buttons to the globe view, it takes over the entire fragment, how do I add buttons or other view elements on the screen like the app screen above?

**Comment by mousebird** [comment]
That sounds like a general purpose Android question.  Not really what we do.
