### ISSUE TITLE
What does height mean for a 2D MaplyViewController?

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [mousebird/WhirlyGlobe#927]
The documentation for `MaplyViewController.height` states:

> @brief Current height above terrain.
    @details In 3D map mode this is the height from which the user is viewing the map.  Maps are usually -PI to +PI along their horizontal edges.

I'm used to other mapping engines where the height is expressed as the tile zoom level and I'm having a hard time mathematically understanding what this number means when animating toPosition.

Am I correct in saying it's the angle in radians of the viewport and the visible extent?  Kind of like this:  http://i.imgur.com/rZ5FfTe.png

**Comment by mousebird** [comment]
The map is projected onto a flat plane.  The reason we don't use zoom level is that we can project multiple maps from multiple coordinate systems onto that flat plane.

The map may run around -PI to +PI from side to side.  So if you're looking down at the plane with a view frustum of, say, 45 degrees, then height is the distance from the viewer to the plane.  1.0 is not an unreasonable value for height.

**Comment by ChrisLowe-Takor** [comment]
Okay thanks.  I still don't completely understand the units but after some trial and error I've come up with values that work for me which I'll leave it here for posterity.

```
static let countryZoomHeight: Float = 0.1
static let stateZoomHeight: Float = 0.01
static let cityZoomHeight: Float = 0.001
static let suburbZoomHeight: Float = 0.0001
static let streetZoomHeight: Float = 0.00001
```
