### ISSUE TITLE
didselect lofted vector not called

### ISSUE THREAD

**Issue by mwurm93** [mousebird/WhirlyGlobe#930]
Is selection on lofted vectors supported? I set the .selectable bool to true, so I do not know why I am not able to select. Thanks

private func addCountries() {
        // handle this in another thread
        let queue = DispatchQueue.global()
        queue.async() {
            let bundle = Bundle.main
            let allOutlines = bundle.paths(forResourcesOfType: "geojson", inDirectory: "country_json_50m")
            var vectorsToAdd = [AnyObject]()
            for outline in allOutlines {
                if let jsonData = NSData(contentsOfFile: outline),
                    let wgVecObj = MaplyVectorObject(fromGeoJSON: jsonData as Data) {
                    wgVecObj.selectable = true
                    // the admin tag from the country outline geojson has the country name ­ save
                    let attrs = wgVecObj.attributes
                    if let vecName = attrs.object(forKey: "ADMIN") as? NSObject {
                        wgVecObj.userObject = vecName
                    }
                    vectorsToAdd.append(wgVecObj)
                    
                }
            }
                    // add the outline and fill to our view
                    self.theViewC?.addLoftedPolys(vectorsToAdd, key: nil, cache: nil, desc: self.loftedVectorFillDict, mode: MaplyThreadMode.any)
                    self.theViewC?.addLoftedPolys(vectorsToAdd, key: nil, cache: nil, desc: self.loftedVectorOutlineDict, mode: MaplyThreadMode.any)
        }
    }

**Comment by mousebird** [comment]
It should work.  Try adding kMaplySelectable: @YES to the description dictionary.

**Comment by mwurm93** [comment]
worked when I added a vector (non-lofted) layer underneath
