### ISSUE TITLE
How can I set the globe opaque?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#931]
![img_0104](https://cloud.githubusercontent.com/assets/13251217/25994026/cbadb950-373e-11e7-97b1-a370cb9932d1.PNG)

Hi,
    When I use some ".shp" or ".geojson" files to load the white area, It appeard that the sphere is transparent,  How can I set the globe opaque? This will not appear on the back of the shadow.

    Thank you ~

**Comment by mousebird** [comment]
It's not transparent, it's just the tessellation of those giant areal features.
Any big features like this that cover significant portions of the globe need to be subdivided properly to show up right.

Take a look at the TextureVectorTestCase in the AutoTester app.  You don't need to do the texturing, but you do need to do the clipping and tessellation.
