### ISSUE TITLE
Remove vector on didSelect

### ISSUE THREAD

**Issue by mwurm93** [mousebird/WhirlyGlobe#932]
How can you remove a vector on didSelect? This code is not working for me, throwing the error "Tried to delete object that doesn't exist".

    func globeViewController(_ viewC: WhirlyGlobeViewController, didSelect selectedObj: NSObject) {
        handleSelection(selectedObject: selectedObj)
        self.theViewC?.remove([selectedObj], mode: MaplyThreadMode.any)
    }

**Comment by mousebird** [comment]
The selection object is a MaplyVectorObject if you selected a vector.  That's not what you remove.

You remove the MaplyComponentObject that you received when you called addVector:

**Comment by mwurm93** [comment]
How should I get the MaplyComponentObject which i want to remove? For context, I need to remove a colored vector (which I have drawn for each country) when tapped.

**Comment by mousebird** [comment]
You have to keep it around from when you added it in the first place.
