### ISSUE TITLE
iOS: Load lots of MaplyScreenMarker without stucking

### ISSUE THREAD

**Issue by ioscoder30** [mousebird/WhirlyGlobe#933]
I have to show lot of markers  on the globe approx 200 markers and currently I have managed to do this using MaplyScreenMarker but after scrolling for few seconds on globe it gets stuck and CPU takes more than 100 % of usage. 

I have added all the markers individually because at some point I have to change the maker image with another one, also I am making sure that if marker location is out of screen then it should be removed but still have the same stuck issue. Could you please guide me if there is some other way to achieve this effectively?

**Comment by jerald-acacus** [comment]
Are you adding the markers on the MaplyCurrentThread? If yes, this blocks the main thread. Try adding it on MaplyThreadAny.

**Comment by mousebird** [comment]
Make sure you're building Release rather than Debug on the device.

The markers really have to be grouped one way or another.  You can try letting the layout manager group them.  Just set the layoutImportance number to something like 1.  Then set the layoutSize to (0,0).  This will run all the markers through the layout manager where they'll be grouped into a single drawable.  But without a layoutSize they won't interfere with each other.

**Comment by ioscoder30** [comment]
Thanks @mousebird  @jerald-acacus  for your response but still I am getting the same stuck issue on scrolling. I guess the problem appears only if I remove and add marker frequently and on continous scrolling. Please suggest what else I can do.

**Comment by ioscoder30** [comment]
@mousebird I have also observed one more thing that I want to clarify with you, previously I was using framework v2.4 and the size was approximately 59 MB but today I have downloaded framework v2.5 from URL: http://mousebird.github.io/WhirlyGlobe/builds/builds.html and the size is 980 MB which is huge.

**Comment by mousebird** [comment]
Yes, the library got much bigger.  Bitcode, new architectures and so forth.  However, it is not much bigger when actually compiled into your app.

As for your issue about getting stuck, It sounds like you might be blocking your main thread.  It's best to add or remove lots of objects on another thread.  Just use a dispach_queue.  WG-Maply is thread safe.
