### ISSUE TITLE
How can I create a hollow circle?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#938]
Hi, 
     I need to create a hollow circle, then I only have positon of center point and radius. When I use MaplyShapeCircle object, I found it is a solid circle not a hollow circle, How can I fix my code? Thank you!

![img_0107](https://cloud.githubusercontent.com/assets/13251217/26342188/a24db28e-3fc9-11e7-979f-3774123657fa.PNG)

![2](https://cloud.githubusercontent.com/assets/13251217/26342155/7c0ee3ae-3fc9-11e7-98cd-3fbf440a2890.png)

**Comment by marychenyuan** [comment]
I means just have border width.

**Comment by mousebird** [comment]
MaplyShapeCircles are filled by their nature.  If you want a non-filled one you need to make a MaplyVectorObject with a circle in it.  You have to add the circle points yourself.

**Comment by marychenyuan** [comment]
Can I add a texture to this MaplyShapeCircle object?

**Comment by mousebird** [comment]
Nope.  Sounds like you want something we don't quite do.
