### ISSUE TITLE
(iOS) Unable to select lower vector object 

### ISSUE THREAD

**Issue by Gauravm15** [mousebird/WhirlyGlobe#939]
I had created two vector objects  on globe. On top there is an state vector layer and bottom I have linear vector object. I'm unable to select bottom layer (Red line area).

Below delegate doesn't help. It does not identify which vector object is tapped. It always gets the touch of top vector.
- (void)globeViewController:(WhirlyGlobeViewController *__nonnull)viewC didSelect:(NSObject *__nonnull)selectedObj
{
}
![screen shot 2017-05-23 at 7 50 18 pm](https://cloud.githubusercontent.com/assets/15883582/26358859/7de352dc-3ff1-11e7-9f64-914b19d03403.png)

**Comment by mousebird** [comment]
There's an allSelect variant of the delegate call.  Switch to that and you'll get all the vectors that surround a tap.
