### ISSUE TITLE
Tile loading / glitching without changing zoom

### ISSUE THREAD

**Issue by mwurm93** [mousebird/WhirlyGlobe#940]
Hello - 

I'm getting weird tile loading when panning around the WhirlyGlobe (stamen watercolor remote tiles). Importantly, I am not changing the zoom level at all when this is occurring. Do you know why this might be happening? In the screenshots below you can see that the tiles for a specific geo, e.g. western Africa, are not consistent and change when panning.

Thanks! 
<img width="344" alt="screen shot 2017-05-23 at 11 52 56 pm" src="https://cloud.githubusercontent.com/assets/6393161/26388686/10b64b2a-4013-11e7-9d74-9a4db692debf.png">
<img width="350" alt="screen shot 2017-05-23 at 11 53 04 pm" src="https://cloud.githubusercontent.com/assets/6393161/26388687/10cae3e6-4013-11e7-86d1-0cea50a5ae80.png">
<img width="341" alt="screen shot 2017-05-23 at 11 53 37 pm" src="https://cloud.githubusercontent.com/assets/6393161/26388688/10cb9322-4013-11e7-8bb1-a51026526f42.png">

**Comment by mousebird** [comment]
You mean the color changes?  Stamen tiles are different between the different zoom levels.  The globe has to mix those zoom levels to maintain coverage without overwhelming the renderer.

Check out the Stamen tiles in a web browser.  You'll see they're visibly different between levels.

**Comment by mwurm93** [comment]
I am not changing the zoom level, so why do tiles from differring zoom levels load? Is there a way to turn this off?    
  
  
  
  

  
  
>

**Comment by mousebird** [comment]
It's a globe.  We load a variety of zoom levels to cover the entire globe.

**Comment by mwurm93** [comment]
Gotcha, thank you. Besides Stamen, do you know of any free and good-looking remote tile sources?

**Comment by mousebird** [comment]
CartoDB has a bunch.  Beyond that, you have to pay.
