### ISSUE TITLE
[ios] currentMapZoom method bug?

### ISSUE THREAD

**Issue by klyatskin** [mousebird/WhirlyGlobe#941]
Detached from https://github.com/mousebird/WhirlyGlobe/issues/270

It seems for me that zoom calc is wrong in WhirlyKitView.mm: 236.

RadToDeg is redundant, a constant should be adjusted (how?). The function versioned below works fine for me and returns zoom for the Globe as expected...

- (double)currentMapZoom:(WhirlyKit::Point2f &)frameSize latitude:(double)latitude
{
  double mapWidthInMeters = (2 * self.heightAboveSurface *  tan(_fieldOfView/2.0) * EarthRadius);
  double metersPerPizel = mapWidthInMeters/frameSize.x();
  double zoom = log2(EarthRadius * /*RadToDeg*/(cos(latitude))/ metersPerPizel) - 8 - 6.856230 + 9; // https://github.com/mousebird/WhirlyGlobe/issues/270
    
  return zoom;
}

**Comment by mousebird** [comment]
You're right.  That doesn't make sense.  I'll change it.
Thanks.

**Comment by klyatskin** [comment]
👍
-- 

2017-06-01 17:31 GMT-04:00 Steve Gifford <notifications@github.com>:
