### ISSUE TITLE
Could we reduce the alpha to minimal?. 

### ISSUE THREAD

**Issue by Gauravm15** [mousebird/WhirlyGlobe#942]
For better visibility, below the vector layer. Is there any option we can reduce the alpha.?
Tried this but doesn't work..
color = [UIColor colorWithRed:255/255.0f green:102/255.0f blue:255/255.0f alpha:0.01];
        //color = [UIColor brownColor];
    }
    
    NSDictionary *vecDesc = @{
                              kMaplySelectable: @(true),
                              kMaplyColor: color,
                              kMaplyVecWidth: @(5.0),
                              kMaplyVecHeight: @(0.0),
                              kMaplyDrawPriority: @(10000),
                              kMaplyFilled :@(true),
                              kMaplySubdivType: kMaplySubdivGrid,
                              kMaplySubdivEpsilon: @(0.000001),
                              };

![screen shot 2017-05-26 at 6 59 38 pm](https://cloud.githubusercontent.com/assets/15883582/26496667/2167dd6e-4246-11e7-8fc5-ef36007a03ca.png)

**Comment by mousebird** [comment]
Multiply the alpha through the rest of the components.
