### ISSUE TITLE
Crash on map teardown in WhirlyKitFontTextureManager dealloc

### ISSUE THREAD

**Issue by pbmorton** [mousebird/WhirlyGlobe#943]
In the develop branch, code at e2fda5b5 (26 April) works error free but after updating to 644abc6ebc (May 24) it crashes when tearing down the map. Nothing else has changed in the App code using WhirlyGlobeMaply.  See attached. I see drawStringReps size=993 and the loop with the iterator does run successfully for many iterations. I did not step through it the full 993 times or add any debugging code. This is completely reproducible. I've cloned fresh code and rebuilt from scratch just by the way. Let me know if you need any more info or help reproducing this problem.

![wgm_crash](https://cloud.githubusercontent.com/assets/8908488/26570226/ec2bd2be-4541-11e7-9998-1864c4f0d1f8.JPG)

**Comment by mousebird** [comment]
That's very odd.  I've cleaned up a little code in there, but nothing dramatic.  Does this happen in the AutoTester?

**Comment by pbmorton** [comment]
Autotester? I haven't tried it. You can reproduce it by running my latest MapTest project. Do this:
-   631  git clone git@bitbucket.org:pbmorton/maptest.git maptest
  632  pwd
  633  cd maptest/
  634  ls
  635  ls libs/
  636  ls libs/WhirlyGlobeMaply/
  637  pwd
  638  git submodule init
  639  git submodule update
  640  cd libs/WhirlyGlobeMaply/
  641  git submodule init
  642  git submodule update
- run MapTest on a device. Tap "Show Map Several Clickable Markers". After the map is loaded press the back arrow. It will crash within a few seconds.

**Comment by mousebird** [comment]
It was a logic error with empty strings.  Working now.
