### ISSUE TITLE
This error always appears when I'm trying install Whirlyglobe for Android Studio

### ISSUE THREAD

**Issue by Rufuslit4z** [mousebird/WhirlyGlobe#944]
[armeabi] Compile++ thumb: Maply <= platform.cpp
[armeabi] Compile++ thumb: Maply <= glwrapper.cpp
[armeabi] SharedLibrary  : libMaply.so
/home/paul/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:49: error: undefined reference to '__atomic_fetch_add_4'
/home/paul/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:49: error: undefined reference to '__atomic_fetch_add_4'
/home/paul/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:53: error: undefined reference to '__atomic_fetch_add_4'
/home/paul/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:53: error: undefined reference to '__atomic_fetch_add_4'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: Leaving directory `/home/paul/Documents/STAGE/WhirlyGlobe/WhirlyGlobeSrc/Android'
make: *** [obj/local/armeabi/libMaply.so] Error 1
:buildNative FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildNative'.
> Process 'command '/home/paul/Android/Sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by mousebird** [comment]
Are you on the current develop branch?

**Comment by Rufuslit4z** [comment]
Yes normally that's ok 

TERMINAL SAY :
------------------------------------------------------------------
$ git checkout develop_3_0
WhirlyGlobeSrc/Android/jni/Android.mk
Déjà sur 'develop_3_0'
Votre branche est à jour avec 'origin/develop_3_0'.
------------------------------------------------------------------
But the problem persists, I don't understand why.

**Comment by AzharAli555** [comment]
I am facing the same issue in develop_3_0 branch.

**Comment by mousebird** [comment]
develop_3_0 is old.  Just use the develop branch for both iOS and Android

**Comment by AzharAli555** [comment]
Thanks for your promt reply , is there any why to stop verticall scroll
other than keepNorthUp as its giving jerking effect

**Comment by mousebird** [comment]
Only keepNorthUp I'm fraid.
