### ISSUE TITLE
How do I add a border to the line?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#945]
Hi,
     How do I add a border to the line object? follow is my code: 
MaplyCoordinate LineCoords[2];
        LineCoords[0] = runway.topPoint;
        LineCoords[1] = runway.buttomPoint;
        MaplyVectorObject *line = [[MaplyVectorObject alloc] initWithLineString:LineCoords numCoords:2 attributes:nil];
        
        NSDictionary *desc = @{kMaplyColor: [UIColor whiteColor],
                               kMaplyVecCentered: @(true),
                               kMaplySubdivType: kMaplySubdivGreatCircle,
                               kMaplySubdivEpsilon: @(0.001),
                               kMaplyVecWidth: @(15),//线宽
                               kMaplyWideVecJoinType: kMaplyWideVecMiterJoin};

        self.runwaylineObject = [self.globeVC addVectors:@[line] desc:desc mode:MaplyThreadAny];

**Comment by mousebird** [comment]
Well, you can add a bigger line with a higher priority and then a smaller line with a lower priority.
