### ISSUE TITLE
[Android] NPE in RendererWrapper.onDrawFrame

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#951]
```
Fatal Exception: java.lang.NullPointerException
       at com.mousebird.maply.RendererWrapper.onDrawFrame(RendererWrapper.java:135)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

**Comment by mousebird** [comment]
Is this one old?  Because I see an explicit null check on that line.

**Comment by jmcazaux** [comment]
I last merged in the 22nd of May.

Considering the number of issues I encountered the merge before last, I am not willing to merge again lightely...

**Comment by mousebird** [comment]
I think that onDrawFrame change predates May 22.

**Comment by mousebird** [comment]
Actually it was on May 22.

**Comment by jmcazaux** [comment]
Indeed I do not have it.

Do you think that there was any big dangerous change since the 22nd?

**Comment by mousebird** [comment]
Nope, nothing much new.
