### ISSUE TITLE
MaplyMultiplexTileSource delegate expects a wrong protocol

### ISSUE THREAD

**Issue by brototyp** [mousebird/WhirlyGlobe#954]
The `MaplyMultiplexTileSource ` has a `delegate` property that expects an objects that implements the `MaplyRemoteTileSourceDelegate` protocol. 

In reality it doesn't call the `remoteTileSource:modifyTileReturn:forTile:` method but calls [remoteTileInfo:modifyTileReturn:forTile:frame:](https://github.com/mousebird/WhirlyGlobe/blob/27a01740095c51a2f6b1f492b296ad10e8c66ed2/WhirlyGlobeSrc/WhirlyGlobe-MaplyComponent/src/MaplyMultiplexTileSource.mm#L311) that isn't declared in the Delegate.

**Comment by mousebird** [comment]
I see a delegate property of type MaplyMultiplexTileSourceDelegate on the MaplyMultiplexTileSource.

Looks like we made that change back in December.

**Comment by brototyp** [comment]
Hi @mousebird, thank you very much for your reply. Turns out that we had the SDK imported two times. At runtime it linked against the new one but the Xcode editor linked against the old one. You were totally right. Sorry for that and thanks!
