### ISSUE TITLE
[Android] ANRs not only on Nexus 7

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#955]
Digging a bit more in #902 I have noticed that it is impacting more then Nexus 7 2012.

Seems to be pretty random in OS version and platform.

They come with the same title in the Play Console:
**"Input dispatching timed out (Waiting to send non-key event because the touched window has not finished proce..."**

Considering I do not have this many users, it seems to happen quite a lot.

I have attached a few traces.

What else can I provide you to investigate this a bit more?
Obviously, there is not way to reproduce this in a controlled environment.

[more_anrs.txt](https://github.com/mousebird/WhirlyGlobe/files/1106673/more_anrs.txt)

**Comment by mousebird** [comment]
In the traces you attached I see the following:
The first is probably a layer shutdown run condition.  I think I could solve this with a timed semaphore.  I'll look into it.
The rest of these traces seem to be crashes in some of your object parsing code.  I don't see any relation to WG-Maply.

Did you mean to send me a different set of traces for ANRs?

**Comment by jmcazaux** [comment]
Nope,
the parsing issues in my code do not make any sense (due to where the happen).

I thought they might be due to something else? (app crash in another thread).

**Comment by mousebird** [comment]
I'm not seeing any action on WG-Maply's threads in those, other than the first one as I mentioned.

**Comment by jmcazaux** [comment]
Strange...

Would be great to solve it anyway though...
