### ISSUE TITLE
[Android] A new finalizer daemon issue (time out) ?

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#956]
I do not remember seeing this before...

```
Fatal Exception: java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
       at android.view.ThreadedRenderer.nDeleteProxy(ThreadedRenderer.java)
       at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:412)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
       at java.lang.Thread.run(Thread.java:818)
```

Could this be related to ANRs ?

**Comment by jmcazaux** [comment]
Fabric is suggesting some links
http://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin
https://github.com/realm/realm-java/issues/1390

**Comment by jmcazaux** [comment]
Actually its not new.

It has been happening since we merge the kit at the end of February (as far as we can tell)

**Comment by mousebird** [comment]
What platforms are you seeing this on?
The thread suggests it might just be older versions of the OS?

**Comment by jmcazaux** [comment]
Actually it seems that all issues happened on Nexus 7 with Android 5.1.1

**Comment by mousebird** [comment]
Anything other than a Nexus 7?  I'm puzzled why I'm hearing so much about the Nexus 7 lately.

**Comment by jmcazaux** [comment]
Nope, only Nexus 7 for this one.

One thing to note: Nexus 7 users are probably over represented in my user population as this format is well suited for aviation and the Nexus 7 2013 was a hit amongst pilots with its good value for monay (at the time).

Another thing. This is not happening as often as the ANRs on issue #955 and #902.

**Comment by mousebird** [comment]
Oh right, there aren't all that many Android tablets.

I've had problems with the finalizer before, though they were more obvious crashes.  There's a switch in the toolkit to explicitly release C++ side memory after an object is used to address this.  The only problem is you have to be careful with things like vector tiles where vector objects are used more than once.

**Comment by jmcazaux** [comment]
IIRC we tried this in the past and it did not work at all with vector tiles.

**Comment by mousebird** [comment]
Yeah, vector tiles can use vectors multiple times (for outlines).  It's not an approach I like very much.

**Comment by jmcazaux** [comment]
Yes, we do that... Happy to review other options if you can suggest some.

**Comment by mousebird** [comment]
If it's a finalizer problem it's probably because too many objects are being created and then cleaned up by the finalizer later on.  It's only the objects that have an explicit finalize(), which is everything that has a C++ side in WG-Maply.  Vectors, in particular.

What I'm wondering is if you're running out of memory before the finalizer gets around to doing its job properly.  In that case the dispose-after-use flag might help, but we'd need to move the logic into the vector tile loader.

Any idea if this is happening when the vector tile display is up?

**Comment by jmcazaux** [comment]
Do you mean when vectors are displaying ?

Yes, this most probably the case, 95% of my users use full vector maps.

**Comment by mousebird** [comment]
So maybe that would help.

**Comment by jmcazaux** [comment]
Sorry I am confused, what would help ?

**Comment by mousebird** [comment]
I put a disposeAfterRemoval in the MapboxVectorTileSource.  Try that out on the hotfix/shutdown-problems branch.  If it doesn't crash anything, I'll merge it in.

**Comment by jmcazaux** [comment]
I have tried again (if I remember well, we tried that in  the past) but it did not work.

When activated, most vectors just do not show and the application crashes after a few seconds when panning.

**Comment by mousebird** [comment]
All right, well don't turn that on, then.

**Comment by jmcazaux** [comment]
Good, this what I did ;)
