### ISSUE TITLE
When the scale is small, the element disappears.

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#959]
![2](https://user-images.githubusercontent.com/13251217/27817769-66620190-60c5-11e7-8404-3d5f6e6c4322.png)

Hi,
    When the scale is small, the element disappears. self.mcTaxiwayGuidanceLine is "MaplyComponentObject", Do I need to set more properties or modify the underlying implementation code?
    Could you help me?

**Comment by mousebird** [comment]
If it's really small, try it without the subdivision.

**Comment by marychenyuan** [comment]
I tried to delete the subdivision properties, it does not work.
![2](https://user-images.githubusercontent.com/13251217/27845703-139a6944-6164-11e7-97f1-47dc446123a3.png)

**Comment by marychenyuan** [comment]
There will still be a disappearance of the situation.

**Comment by mousebird** [comment]
Try modifying the AutoTester to produce the same effect.  Point me to the branch when you have that and I might take a look when I have some time.

**Comment by marychenyuan** [comment]
![2](https://user-images.githubusercontent.com/13251217/27850416-172270ca-6187-11e7-864c-ee4b276f5d93.png)

**Comment by mousebird** [comment]
I mean that you need to produce a test case that reproduces the problem.
Are you on support?  I don't believe you are.
So you need to make a very simple test case that duplicates the problem and then I'll look into it when I have a chance.
