### ISSUE TITLE
Need some explanation on iOS with vector data

### ISSUE THREAD

**Issue by ega4** [mousebird/WhirlyGlobe#960]
Hi MouseBird,
Really thanks for your amazing work.
We are currently trying to use your SDK to display online AND offline maps.
Main main problem is with online vector tiles. I think it's useless that i try to describe it, i have a video: https://youtu.be/FT2R8Pay7NE.
I think we will guess that it's like the tile are badly positionned and i want to know if you know from where it can come.

Another problem is that roads are not rendered, i've check my mbtiles and my stylesheet but it don't work, I have the same problem with carto. Do you know about it ?

We expect to work with you and are thinking of a way to collaborate with you.

Regards,
Evan

**Comment by ega4** [comment]
i find my solution in those parameters
`                layerQuad.flipY = false
                layerQuad.importance = 256*256
                layerQuad.useTargetZoomLevel = true`

sorry for this post.

And for road, classname is transportation, i don't know why.

We have now some issues with performances but at least, it work.

**Comment by mousebird** [comment]
Right, that makes sense.  
As for performance, I might set layerQuad.importance = 512*512
Vector tiles tend to be fairly dense in content.

Feel free to submit more issues if you run into additional problems.
