### ISSUE TITLE
maplyViewController:didStopMoving:userMotion: has incorrect userMotion flag

### ISSUE THREAD

**Issue by thorstenstark** [mousebird/WhirlyGlobe#961]
Both delegate methods for start and stop moving the map return the userMotion flag in unexpected ways. 
The method `maplyViewController:didStopMoving:userMotion:` for example has the following behaviour:
1) when the users moves the map and stops moving before releasing the touch the flag is true, which is correct
2) when the user starts moving and the releases while the map still scrolls a bit the flag is false
3) when animation programatically to a point on the map the returned flag is true.

**Comment by mousebird** [comment]
What version is this?

**Comment by thorstenstark** [comment]
It's the version from here: https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/WhirlyGlobe-Maply_Distribution_2_5.zip. Should be 2.5, but the podspec says 2.4.1-nightly295
