### ISSUE TITLE
Swift MaplyViewController animate method only one override available

### ISSUE THREAD

**Issue by w-flame** [mousebird/WhirlyGlobe#962]
Hello! I'm using latest compiled version 2.5 of framework and XCode 8.3.3 Swift project. 
Issue is that I can only use .animate method with (position, location, time) arguments and all other overrides are unawailable. And when I use this method I get white screen without map. Without it map showing and works.
I checked there are many overrides for WhirlyGlobeViewController. Maybe I missed something in setup?

**Comment by mousebird** [comment]
I'm using 8.3.3 and I see all the animate variants in Swift.
I find auto-complete pretty flakey with Swift, so perhaps that's it.

How are you constructing the position?  If you're using degrees, make sure to use the MaplyCoordinateMakeWithDegrees constructor.

**Comment by w-flame** [comment]
I'm using code from example, but I had to add onScreen parameter. 
```
...
let pos = CGPoint(x: mapContainer.bounds.midX, y: mapContainer.bounds.midY)
mapView.animate(toPosition: MaplyCoordinateMakeWithDegrees(-3.6704803, 40.5023056), onScreen: pos, time: 1.0)
```
I just can't figure out why other overrides doesn't appear though they are in header file.

**Comment by w-flame** [comment]
Just did setup procedure once again from the beginning and now it works! Thanks for trying to help!
