### ISSUE TITLE
Basemap issues in tiles

### ISSUE THREAD

**Issue by renanstig** [mousebird/WhirlyGlobe#964]
Hi, 

I'm not sure how to do that using your library, but I have this pattern and I would like to know how I'll get the value of "z", "x" and "y". 
http://{s}.wien.gv.at/basemap/geolandbasemap/normal/google3857/{z}/{y}/{x}.png
Can you help me with that?

Another problem is that my map is showing like this:

![simulator screen shot 7 jul 2017 13 16 38](https://user-images.githubusercontent.com/4225270/27956152-ce692ce6-6318-11e7-8cdf-336dfa0b936a.png)

Can anyone tell me what I should do to fix it?

Thanks,
Renan.

**Comment by mousebird** [comment]
Try setting flipY = true and then flipY = false and see which one works.

**Comment by renanstig** [comment]
Hi @mousebird ,

Doing what you suggested worked like a charm, thanks 👍
