### ISSUE TITLE
Designated initializer of the superclass "WhirlyGlobeViewController"

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#969]
Hello everyone,

Today I tried to create a custom class inheriting from WhirlyGlobeViewController. When I type the instruction line "super.init()", I get the following error:

![screen shot 2017-07-11 at 3 29 37 pm](https://user-images.githubusercontent.com/15698398/28086744-024db436-664e-11e7-969b-307bb46149df.png)

When I looked at the way an instance of WhilyGlobeViewController is done in the tutorial,  I see the following instruction line: 

"globe = WhirlyGlobeViewController()"

It looks like I am not using the good way to init the superclass. What am I doing wrong?

Have a nice day,

Sebboulnois.

**Comment by mousebird** [comment]
Swift sometimes gets annoyed by methods with no arguments.  Perhaps that's the case here?

Also, there's only a few cases where subclassing of the WG view controllers make sense.  Better to just make it a dependent view controller to your main one.

**Comment by Sebboulnois** [comment]
I still want my globe to be dependent to my main one. However, I would like to have a clean and light main view controller and avoid having all the set up (when you fill your controller with data such as layers, initial positions, vectors). Do you think it makes sense?

**Comment by mousebird** [comment]
Sure, you can do that.  This is a Swift thing with initializers.  I'm not sure what the fix is, but look for "Swift init subclass" and see what you get.

**Comment by Sebboulnois** [comment]
Did some research on Swift initialization patterns:

"A Swift class must initialize its own (non-inherited) properties (non-optional) before it calls its superclass’s designated initializer."

Since I don't plan on adding subclass properties, I should be able to directly use super.init(). They don't talk about the absence of arguments. Where can I find the designated initializer(s) of the WGViewController class?

**Comment by mousebird** [comment]
We have an init, no arguments.

**Comment by Sebboulnois** [comment]
Hmm. That's weird then. I might have to dig more for the problem. Let me know if anything comes to your mind.

Thank you!

**Comment by Sebboulnois** [comment]
Got some answers. Somehow, WGVController requires to call super.init(nibName: nil, bundle: nil). I did not get a specific answer of why yet, but it seems to me that when super.init() can't be called from the superclass, you might have to go higher in the hierarchy. In this case, I believe we have to call the designated initialiser for UIViewController (initWithNibName:bundle). Does it make sense to you?

I created a custom class of a map. For this one, I called super.init(mapType: .flatType). However, the compiler yells at me because I did not init the class with the super.init(nibName: nil, bundle: nil). I am wondering how I can fix that, since we can't call multiple super class initializers.

**Comment by mousebird** [comment]
I just have a regular init call for WhirlyGlobeViewController.  The mapType should be just for MaplyViewController.

**Comment by Sebboulnois** [comment]
Yes. I figured that out. What I am saying is that when it comes to a custom map class not only you need to init with the type of map but also the compiler is expecting a bundle argument. I'm not sure how to deal with that part:

<img width="1181" alt="screen shot 2017-07-11 at 6 44 34 pm" src="https://user-images.githubusercontent.com/15698398/28094155-12495af0-6669-11e7-8935-176918c1b562.png">

<img width="301" alt="screen shot 2017-07-11 at 6 44 52 pm" src="https://user-images.githubusercontent.com/15698398/28094164-18c0ea42-6669-11e7-863a-e169b9108eb3.png">

**Comment by Sebboulnois** [comment]
Hello,

I figured it out. It works now.

Sebastien.

**Comment by mousebird** [comment]
Oh good.  What did you have to do?

**Comment by Sebboulnois** [comment]
I pass the type of map as an argument when I initialize my custom map.

In the custom class:
<img width="679" alt="screen shot 2017-07-12 at 1 16 38 pm" src="https://user-images.githubusercontent.com/15698398/28130409-7bea2a8e-6704-11e7-9596-e76f0e4d1b8d.png">

In the main:
<img width="614" alt="screen shot 2017-07-12 at 1 16 49 pm" src="https://user-images.githubusercontent.com/15698398/28130411-816dc2b8-6704-11e7-8eb0-b709436df497.png">

That do you think?
