### ISSUE TITLE
There is no source for country and city name lables with location.

### ISSUE THREAD

**Issue by Shockwave7747** [mousebird/WhirlyGlobe#970]
I want to show country names in the globe, i can add one label obviously, and more labels too if i have an arraylist.... but there is no exact resource i found to be used for all labels, can you help me with it?

**Comment by Shockwave7747** [comment]
i am working on android btw.

**Comment by Shockwave7747** [comment]
can anyone please help me adding country name labels on the globe... i am digging the internet from morning to add the names of countries in android

**Comment by mousebird** [comment]
http://www.naturalearthdata.com/
