### ISSUE TITLE
Notification or Delegate method to use once layers are loaded on Globe/Map

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird/WhirlyGlobe#971]
I am using offline layers for my globe and map. Is there any notification or delegate I can use to know whether the layers have been added to the globe/map. I want to only start loading my markers and vectors once the layers have finished loading. Because sometimes, my markers and vectors would appear in the globe without the layers. Also, my progress hud would seem to show first before the layers have finished initially so it looks kinda weird.

**Comment by mousebird** [comment]
There's no loading notification for local data sources, I'm afraid.
