### ISSUE TITLE
[IOS] MaplyMovingScreenMarker keeps on moving

### ISSUE THREAD

**Issue by vvaleed** [mousebird/WhirlyGlobe#972]
Hi Steve,

I am facing a strange problem here. The endLoc isn't working as it should be, my marker starts from the starting point moves towards the end point, but it crosses the end point and keeps on moving until out of view. Here is the snippet I used.

`- (void) updatePositionMarker:(CLLocation *) location {
    
    if (MovingObj) {
        [globeViewC removeObject:MovingObj];
    }
    
    if (!MovingMarker) {
        MovingMarker = [[MaplyMovingScreenMarker alloc] init];
        MovingMarker.image = [UIImage imageNamed:@"aircraftpinpurple.png"];
        MovingMarker.size = CGSizeMake(32, 32);
        MovingMarker.layoutImportance = MAXFLOAT;
        MovingMarker.selectable = NO;
    }
    
    CLLocation *lastLocation = glastLocation ?: location;
    //NSTimeInterval duration = [location.timestamp timeIntervalSinceDate:glastLocation.timestamp];
    glastLocation = location;
    
    MovingMarker.duration = 3.0;
    MovingMarker.loc = MaplyCoordinateMakeWithDegrees(lastLocation.coordinate.longitude, lastLocation.coordinate.latitude);
    MovingMarker.endLoc = MaplyCoordinateMakeWithDegrees(location.coordinate.longitude, location.coordinate.latitude);
    
    MovingObj = [globeViewC addScreenMarkers:@[MovingMarker] desc:@{}];
}`

**Comment by mousebird** [comment]
Start/End just provide a starting point and vector.
To turn an object off when it's done you need to remove it on time or use the kMaplyEnableStart/kMaplyEnableEnd attributes with an NSDate.
