### ISSUE TITLE
Can't get the view displayed in the sample video, need help too.

### ISSUE THREAD

**Issue by blackbeared** [mousebird/WhirlyGlobe#973]
hello sir, i would like to thank you for your previous reply, but i need a bit more help please.
![screenshot_2017-07-15-00-40-12](https://user-images.githubusercontent.com/19996460/28227382-49ea2cd8-68f7-11e7-88b3-75d6e08abb16.png)

this is how i made it after two day of hard work, and that i what i want to make it look like...

![jjk](https://user-images.githubusercontent.com/19996460/28227513-e8985d64-68f7-11e7-9f9c-269cc5598ac5.PNG)
 can you plese help me with it sir? i was looking for tiles, but i can't find better tiles, and also dont know how to use them, what i found was 42GB collection of all vectors, which i cant afford in my application, as i only want to show countries and cities and their respective borders on the globe... nothing else... 
so please help me out.

**Comment by Shockwave7747** [comment]
and it will be more better if i can set the labels look like 3d as they are in pic below, do whirlyGlobe have 3dScreenLabel available?.... and also it will be better if i can fetch the tiles online with a link... 
or else please tell me if there any ready made source available for the globe that look like what i want...

**Comment by mousebird** [comment]
There's a shadow or an outline available in ScreenLabels.  Take a look at the documentation for addScreenLabels:

As for helping you design the look for your map, that's a complicated problem.

**Comment by Shockwave7747** [comment]
thank you for your reply sir, if you will give me any better reference to dig for, it will be helpful to me.. 👍
