### ISSUE TITLE
Can Ｍaply use for offline vector map usecase?

### ISSUE THREAD

**Issue by kochizufan** [mousebird/WhirlyGlobe#975]
Hi Steve,

Sorry this is not issue but just question..

Can Ｍaply be used for offline vector map usecase? 
Not only loading vector data, but also downloading vector dataset (by coutry or..) is need.

Background story is,
My friends have a usecase for creating Japan offline map application (iOS and Android).
So they are searching vector map library, at first I recommended Maps.me to them.
But they said Maps.me's library is difficult to use and not maintained well these days.
So I want to introduce Maply to them, if this SDK can be used for such usecases. 

Regards,
Kohei

**Comment by mousebird** [comment]
There are a number of apps that do just this.  The only problem is that it's a bit of work.

The best combination at present is to use data compiled into MBTiles and Styled Layer Descriptor (SLD) for the style sheets.  

Unfortunately you have to set all this up yourself.  You have to find the data, build the MBTiles file with vector tiles, and make your own SLD sheets.

We have a simple example in the AutoTester app with SLD and GeoJSON using Belfast.  There's also an example with MBTiles vectors from France, but no SLD.

**Comment by stonetip** [comment]
There are a several ways to create an MBTiles set, which underneath is a SQLite DB file (you can explore one of these with any DB manager that works with SQLite). I've found the easiest way to get going with it is to use MapBox's Tippecanoe, which will run on a Mac or Windows (using a Docker container). You create a set of one or more GeoJSON files and use Tippecanoe to package them. Depending on workflow, you may find other tools better for getting data out of a spatial DB, e.g. PostgreSQL. This is a good place to start.

**Comment by RandyHBH** [comment]
I generate my MBTiles Vector Tiles using [OpenMapTiles](https://openmaptiles.org/), but when i load the mbtiles give me this error `Bad image data for tile: 0: (0,0)`, maybe is bacuase WhirlyGlobe dosn't support the [OpenMapTiles Schema](https://openmaptiles.org/schema/). 
Can you help me? 
So where i can find the example with MBTiles, can you point the link?? Thanks a lot.

**Comment by stonetip** [comment]
https://github.com/mapbox/tippecanoe is where you can find the code/download and it's fairly well documented. In general, I've found that best results are obtained by using the -zg param, which will try to estimate only the necessary zoom levels and build tilesets accordingly. When I get more time, I'll put together more detail on the subject. There are definitely some things I've learned along the way (and I'm still far from mastery).
