### ISSUE TITLE
[Android] Geodesic Line

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe#979]
Hi,

Related to the issue #412, is it possible to have it on Android?

To render a geodesic line on iOS, the sample use this method: **subdivideToGlobeGreatCircle**

https://github.com/mousebird/WhirlyGlobe/blob/27a01740095c51a2f6b1f492b296ad10e8c66ed2/WhirlyGlobeSrc/AutoTester/AutoTester/testCases/GreatCircleTestCase.m

Regards

**Comment by Tourmen** [comment]
is it possible to have it on Android?
>> +1

**Comment by mousebird** [comment]
Now available on Android.
