### ISSUE TITLE
How to make Label and marker do not overlap?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#980]
For example, you can see airport "ZUUU":
![2](https://user-images.githubusercontent.com/13251217/28511336-534ca352-707f-11e7-92a3-301c53243dc0.png)

![3](https://user-images.githubusercontent.com/13251217/28511340-59d33e98-707f-11e7-9dbd-aa76a216e682.png)

The following is my code:
![1](https://user-images.githubusercontent.com/13251217/28511345-61c5ec86-707f-11e7-9854-9789d2d54830.png)

what should I do to fix the problem? Thank you!

**Comment by mousebird** [comment]
Use the layoutImportance with a value != MAXFLOAT to invoke the layout engine.

**Comment by marychenyuan** [comment]
I want to make imgMarker always appear, so I set the " imgMarker.layoutImportance = MAXFLOAT ". and I hope have this effect:   if the label overlap with any marker, label disappear.

current effect is: if the label overlap with other label, the label disappear. but if the label overlap with marker, label did not disppear.

**Comment by marychenyuan** [comment]
For example, I want to the airport's label "ZUGH"(MaplyScreenLabel)
![image](https://user-images.githubusercontent.com/13251217/28557872-a8c1343e-7141-11e7-9a27-762118df393a.png)
  did not cover other airport's mark (MaplyScreenMarker)
![image](https://user-images.githubusercontent.com/13251217/28557867-a02b95f8-7141-11e7-8109-61284a501ccc.png)

**Comment by marychenyuan** [comment]
Or the value of the layoutImportance is set to how much is appropriate...

**Comment by mousebird** [comment]
Given the marker a very large value other than MAXFLOAT.
They will interfere with each other, though.
