### ISSUE TITLE
How can I use cocapod to get latest version?

### ISSUE THREAD

**Issue by marychenyuan** [mousebird/WhirlyGlobe#981]
How can I use cocapod to get latest version? I want to update version  in my project, following code is my current code:

pod 'SpatialDBKit'
pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe', :branch => 'develop_2_4_1'

**Comment by mousebird** [comment]
There's a podspec in the develop branch.  If you point directly to that you should get the latest.
