### ISSUE TITLE
Double tap event on Maply vector object

### ISSUE THREAD

**Issue by ios-friendly-dev** [mousebird/WhirlyGlobe#982]
Hello Steve.

I am having an issue with double tap event on0 Maply vector object. As we have delegate method "didiSelect" which is called on single tap for selectable Maply vector object and this is working fine. But I need one more event to execute another operation so I added double tap gesture on map and using findObjectAtLocation I tried to get selected object but it always returns nil.

I have also checked by using "addSelectionVectors" method as you had suggested in another post but no luck, could you please let me know if I am doing something wrong here.

**Comment by mousebird** [comment]
Looks like findObjectAtLocation only handles non-vectors.
