### ISSUE TITLE
[Android] MaplyBaseController.changeSticker does not change priority

### ISSUE THREAD

**Issue by jmcazaux** [mousebird/WhirlyGlobe#985]
I need to be able to reorder stickers once they ave been created, but changeSticker has no effect on priority.

Reprocase on its way

**Comment by jmcazaux** [comment]
Hi Steve,
this one is creating some visual artefacts I'd like to get rid of.

Is the repro case not enough?

**Comment by stevesaildrone** [comment]
No doubt it's a fine repro case.  I have not had a chance to look at it yet.  Next week.

**Comment by mousebird** [comment]
No doubt it's a fine repro case. I have not had a chance to look at it yet. Next week.

Wrong account there, whoops.

**Comment by jmcazaux** [comment]
Ah Ok, thought it slept thru the net ;). Next week is fine, I plan to release next week-end.

**Comment by jmcazaux** [comment]
Hi Steve, any news from this one ?

**Comment by stevesaildrone** [comment]
Not yet.

**Comment by jmcazaux** [comment]
Erm...

**Comment by mousebird** [comment]
Should be fixed now.
