### ISSUE TITLE
Cant compile for Android

### ISSUE THREAD

**Issue by Tourmen** [mousebird/WhirlyGlobe#987]
Tried to build sources for Android and got errors.
Followed the instructions:
http://mousebird.github.io/WhirlyGlobe/tutorial/android/building-from-source.html

[x86] Compile++      : Maply <= Scene.cpp
[x86] Compile++      : Maply <= SceneRendererES.cpp
[x86] Compile++      : Maply <= SceneRendererES2.cpp
In file included from ../../third-party//eigen/Eigen/Core:248:0,
                 from ../../third-party//eigen/Eigen/Dense:1,
                 from ../../third-party//eigen/Eigen/Eigen:1,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/WhirlyVector.h:25,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Scene.h:26,
                 from jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:22:
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Drawable.h: In destructor 'virtual WhirlyKit::AddDrawableReq::~AddDrawableReq()':
../../third-party//eigen/Eigen/src/Core/util/Memory.h:607:12: error: 'static void WhirlyKit::Drawable::operator delete(void*)' is protected
       void operator delete(void * ptr) throw() { Eigen::internal::conditional_aligned_free<NeedsToAlign>(ptr); } \
            ^
../../third-party//eigen/Eigen/src/Core/util/Memory.h:624:41: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
 #define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                         ^
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Drawable.h:162:5: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
     EIGEN_MAKE_ALIGNED_OPERATOR_NEW;
     ^
jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:687:16: error: within this context
         delete drawable;
                ^
In file included from ../../third-party//eigen/Eigen/Core:248:0,
                 from ../../third-party//eigen/Eigen/Dense:1,
                 from ../../third-party//eigen/Eigen/Eigen:1,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/WhirlyVector.h:25,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Scene.h:26,
                 from jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:22:
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Drawable.h: In member function 'virtual void WhirlyKit::AddDrawableReq::execute(WhirlyKit::Scene*, WhirlyKit::SceneRendererES*, WhirlyKit::View*)':
../../third-party//eigen/Eigen/src/Core/util/Memory.h:607:12: error: 'static void WhirlyKit::Drawable::operator delete(void*)' is protected
       void operator delete(void * ptr) throw() { Eigen::internal::conditional_aligned_free<NeedsToAlign>(ptr); } \
            ^
../../third-party//eigen/Eigen/src/Core/util/Memory.h:624:41: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
 #define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                         ^
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Drawable.h:162:5: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
     EIGEN_MAKE_ALIGNED_OPERATOR_NEW;
     ^
jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:704:20: error: within this context
             delete drawable;
                    ^
In file included from ../../third-party//eigen/Eigen/Core:248:0,
                 from ../../third-party//eigen/Eigen/Dense:1,
                 from ../../third-party//eigen/Eigen/Eigen:1,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/WhirlyVector.h:25,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Scene.h:26,
                 from jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:22:
/home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h: In instantiation of 'std::__shared_count<_Lp>::__shared_count(_Ptr) [with _Ptr = WhirlyKit::Drawable*; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]':
/home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:871:39:   required from 'std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*) [with _Tp1 = WhirlyKit::Drawable; _Tp = WhirlyKit::Drawable; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]'
/home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr.h:113:32:   required from 'std::shared_ptr<_Tp>::shared_ptr(_Tp1*) [with _Tp1 = WhirlyKit::Drawable; _Tp = WhirlyKit::Drawable]'
jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:709:33:   required from here
../../third-party//eigen/Eigen/src/Core/util/Memory.h:607:12: error: 'static void WhirlyKit::Drawable::operator delete(void*)' is protected
       void operator delete(void * ptr) throw() { Eigen::internal::conditional_aligned_free<NeedsToAlign>(ptr); } \
            ^
../../third-party//eigen/Eigen/src/Core/util/Memory.h:624:41: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
 #define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                         ^
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Drawable.h:162:5: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
     EIGEN_MAKE_ALIGNED_OPERATOR_NEW;
     ^
In file included from /home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr.h:52:0,
                 from /home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/memory:82,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/RawData.h:24,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Texture.h:23,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Scene.h:27,
                 from jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:22:
/home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:573:8: error: within this context
        delete __p;
        ^
In file included from ../../third-party//eigen/Eigen/Core:248:0,
                 from ../../third-party//eigen/Eigen/Dense:1,
                 from ../../third-party//eigen/Eigen/Eigen:1,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/WhirlyVector.h:25,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Scene.h:26,
                 from jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:22:
/home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h: In instantiation of 'void std::_Sp_counted_ptr<_Ptr, _Lp>::_M_dispose() [with _Ptr = WhirlyKit::Drawable*; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]':
jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:811:1:   required from here
../../third-party//eigen/Eigen/src/Core/util/Memory.h:607:12: error: 'static void WhirlyKit::Drawable::operator delete(void*)' is protected
       void operator delete(void * ptr) throw() { Eigen::internal::conditional_aligned_free<NeedsToAlign>(ptr); } \
            ^
../../third-party//eigen/Eigen/src/Core/util/Memory.h:624:41: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF'
 #define EIGEN_MAKE_ALIGNED_OPERATOR_NEW EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF(true)
                                         ^
../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Drawable.h:162:5: note: in expansion of macro 'EIGEN_MAKE_ALIGNED_OPERATOR_NEW'
     EIGEN_MAKE_ALIGNED_OPERATOR_NEW;
     ^
In file included from /home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr.h:52:0,
                 from /home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/memory:82,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/RawData.h:24,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Texture.h:23,
                 from ../../WhirlyGlobeSrc/WhirlyGlobeLib/include/Scene.h:27,
                 from jni/../../..//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.cpp:22:
/home/anton/android/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:373:9: error: within this context
       { delete _M_ptr; }
         ^
make: *** [obj/local/x86/objs/Maply/__/__/__//WhirlyGlobeSrc/WhirlyGlobeLib/src//Scene.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/home/anton/rep/WhirlyGlobe/WhirlyGlobeSrc/Android'
:buildNative FAILED

**Comment by mousebird** [comment]
I think the compiler got pickier recently.  Try the develop branch.  That should be up to date.

We also provide [AARs](http://mousebird.github.io/WhirlyGlobe/builds/builds.html).

**Comment by Tourmen** [comment]
tried "develop" branch, no success with the library

:buildNative
make: Entering directory `/home/anton/rep/WhirlyGlobe/android/library/Android'

make: *** No rule to make target `jni/../../../..//third-party//glues/source//glues_error.c', needed by `obj/local/arm64-v8a/objs/Maply/__/__/__/__//third-party//glues/source//glues_error.o'.  Stop.
make: *** Waiting for unfinished jobs....

make: Leaving directory `/home/anton/rep/WhirlyGlobe/android/library/Android'
:buildNative FAILED

FAILURE: Build failed with an exception.

PS: Provided AAR are good. But still, are you worrying about building from sources or it is not important?

**Comment by mousebird** [comment]
Did you get the submodules?
git submodule init
git submodule update

**Comment by Tourmen** [comment]
Yes I tried. Still no success.
Need to clarify: I changed a branch to "develop", but should I go to WhirlyGlobe/WhirlyGlobeSrc/Android and run ./gradlew assemble (as documentation says). Or go to WhirlyGlobe/android/apps/AutoTesterAndroid and try to build it there (buildmaply.sh ?) ? Or any step you can suggest.

**Comment by mousebird** [comment]
The buildmaply script just does the assemble, but it only does it for a few architectures.

I'm not sure what to say.  Our build server seems to be doing it.  I can do it here.  Maybe check your Android Studio version?

**Comment by Tourmen** [comment]
So, I tried the same workflow on my MacBook and I was able to build the library eventually. 
But on Ubuntu I still cant achieve any progress.
From my perspective the ticket might be closed, but if did not have the MacBook I would not get a build)

**Comment by mousebird** [comment]
Odd that it would work on one, but not the other, particularly for that error.
