### ISSUE TITLE
Globe/Map.add function - Swift

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#990]
Hello guys,

I am having difficulties with the add function in Swift. Is the way you handle the description different from the Objective-C way?

![screen shot 2017-08-28 at 3 51 42 pm](https://user-images.githubusercontent.com/15698398/29790982-7090754c-8c09-11e7-82de-7ed67eb31ef0.png)

Moreover, does a Swift component tester exist? I think it would be useful to see the differences, if there are some.

Thank you very much,

Sebastien.

**Comment by mousebird** [comment]
There are a bunch of test cases in the AutoTester that use Swift.
And yes, the NSDictionary is handled very differently in Swift.  You don't use curly brackets or @ signs.

Otherwise WG-Maply works fine with Swift.  I'm using it pretty intensively myself.

**Comment by Sebboulnois** [comment]
Hello,

Thank you for directing me. My mistake, I did not notice the testCases folder in the auto tester.

Have a nice day,

Sebastien.
