### ISSUE TITLE
[SWIFT] - MaplyVectorObject width

### ISSUE THREAD

**Issue by Sebboulnois** [mousebird/WhirlyGlobe#996]
Hello (yes, me again),

I am creating a line on a map with a MaplyVectorObject and am trying to change its width directly with the kMaplyVecWidth attribute during the creation of the line:

![screen shot 2017-09-06 at 2 48 55 pm](https://user-images.githubusercontent.com/15698398/30129004-8add94ec-9312-11e7-86ae-b7d70f106b4d.png)

However, it doesn't seem to change anything on the screen. Am I using the attribute correctly?

Have a nice day,

Sebastien.

**Comment by mousebird** [comment]
You can put colors directly on vector objects, but not much else.
Put that attribute in the description dictionary you pass to addVectors.
